translations = {
    "base.align_neutral": "(Neutral)",
    "base.attack_looted": "  Saqueas {0} de oro de su cuerpo.",
    "base.auction_grimjaw": "Grimjaw",
    "base.buff_arcane_mastery": "  - Maestria Arcana: +15% dano de hechizos",
    "base.buff_potion_mastery": "  - Maestria en Pociones: +50% curacion (pociones, hierbas, elixires)",
    "base.buff_tricksters_luck": "  - Suerte del Embaucador: 20% probabilidad de bonus aleatorio",
    "base.experience_label": "  Experiencia: +{0}",
    "base.fame_notable": "Notable",
    "base.heading_to": "Dirigiendote a {0}...",
    "base.help_auction": "- Comprar y vender objetos (Casa de Subastas)",
    "base.help_boss": "- Estado y combate del Jefe Mundial (en linea)",
    "base.help_bug": "- Reportar un error (abre GitHub)",
    "base.help_commands_work": "  Estos comandos funcionan desde cualquier lugar:",
    "base.help_compact": "- Alternar modo compacto (movil/pantallas pequenas)",
    "base.help_emote": "- Emote (ej. /emote saluda)",
    "base.help_gear": "- Mostrar equipo detallado y bonificaciones (tuyo o equipo)",
    "base.help_gold": "- Mostrar oro y saldo bancario",
    "base.help_gossip": "- Chat global fuera de personaje (/gos)",
    "base.help_health": "- Mostrar salud y mana",
    "base.help_herb": "- Usar una hierba de tu bolsa",
    "base.help_inventory": "- Ver tu inventario",
    "base.help_key_bug": "- Reportar error",
    "base.help_key_help": "- Esta ayuda",
    "base.help_key_inventory": "- Inventario",
    "base.help_key_prefs": "- Preferencias",
    "base.help_key_status": "- Estado",
    "base.help_mail": "- Abrir tu buzon (en linea)",
    "base.help_materials": "- Ver materiales de fabricacion",
    "base.help_online_commands": "  Comandos en linea:",
    "base.help_potion": "- Usar una pocion curativa",
    "base.help_prefs": "- Abrir menu de preferencias",
    "base.help_quests": "- Ver misiones activas",
    "base.help_quick_keys": "  Teclas rapidas (un caracter):",
    "base.help_say": "- Hablar con jugadores en tu ubicacion",
    "base.help_shout": "- Gritar a todos los jugadores en linea",
    "base.help_stats": "- Ver tus estadisticas de personaje",
    "base.help_tell": "- Mensaje privado a un jugador",
    "base.help_time": "- Mostrar hora actual del dia",
    "base.help_trade": "- Ver paquetes de comercio (en linea)",
    "base.help_who": "- Ver quien esta en linea",
    "base.immortal_locked": "  Eres un ser de pura divinidad. El reino mortal no tiene nada para ti.",
    "base.invalid_choice": "Opcion invalida: '{0}'",
    "base.invalid_choice_simple": "Opcion invalida.",
    "base.level_up": "  *** SUBISTE DE NIVEL! Ahora eres Nivel {0}! ***",
    "base.location_label": "Ubicacion: ",
    "base.loot_label": "  Botin:",
    "base.lv_label": " Nv:",
    "base.mat_found_floors": "    Se encuentra en pisos del calabozo {0}-{1}",
    "base.materials_hint1": "  Materiales raros se encuentran en las profundidades del calabozo.",
    "base.materials_hint2": "  Derrota monstruos, abre cofres del tesoro y desafia a los Dioses Antiguos",
    "base.materials_hint3": "  para recolectar materiales necesarios para encantamientos poderosos.",
    "base.more": ", +{0} mas",
    "base.more_quests": "  ... y {0} misiones mas.",
    "base.mud_look": "mirar",
    "base.mud_to_redraw": " para redibujar",
    "base.no_active_character": "  No hay personaje activo.",
    "base.no_active_quests": "  No hay misiones activas. Visita el Castillo o habla con NPCs para encontrar misiones.",
    "base.no_antidotes": "No tienes antidotos. Compralos de mercaderes del calabozo o del curandero.",
    "base.no_healing_potions": "  No tienes pociones curativas.",
    "base.no_materials": "  No tienes materiales de fabricacion.",
    "base.no_one_to_talk": "No hay nadie aqui con quien hablar.",
    "base.nod_walk_away": "  Asientes y te alejas.",
    "base.not_poisoned": "No estas envenenado.",
    "base.nothing_happens": "No pasa nada.",
    "base.npc_says": "  {0} dice:",
    "base.npc_says_label": "  {0} dice:",
    "base.npc_whispers": "  {0} se acerca y susurra:",
    "base.online_only_auction": "  La Casa de Subastas solo esta disponible en modo en linea.",
    "base.online_only_boss": "  El Jefe Mundial solo esta disponible en modo en linea.",
    "base.online_only_bounties": "  Las recompensas solo estan disponibles en modo en linea.",
    "base.online_only_mail": "  El correo solo esta disponible en modo en linea.",
    "base.online_only_trade": "  El comercio solo esta disponible en modo en linea.",
    "base.or": ", o [",
    "base.others_going_about": "  ... y {0} otros ocupados en sus asuntos.",
    "base.poison_cleared": "El veneno finalmente ha dejado tu cuerpo!",
    "base.poison_damage": "El veneno recorre tus venas! (-{0} HP)",
    "base.poison_damage_turns": "El veneno recorre tus venas! (-{0} HP, {1} turnos restantes)",
    "base.poison_death": "El veneno ha cobrado tu vida!",
    "base.potion_healed": "  Bebes una pocion curativa y recuperas {0} HP!",
    "base.pref_auto_heal_toggled": "Auto-curar esta ahora {0}",
    "base.pref_autoequip_disabled": "Auto-Equipar DESACTIVADO",
    "base.pref_autoequip_disabled_desc": "Las compras iran directamente al inventario.",
    "base.pref_autoequip_enabled": "Auto-Equipar ACTIVADO",
    "base.pref_autoequip_enabled_desc": "Se te preguntara si equipar o guardar al comprar.",
    "base.pref_autolevel_disabled": "Auto-Subir Nivel DESACTIVADO",
    "base.pref_autolevel_disabled_desc": "Visita al Maestro de Nivel para subir manualmente.",
    "base.pref_autolevel_enabled": "Auto-Subir Nivel ACTIVADO",
    "base.pref_autolevel_enabled_desc": "Subiras de nivel automaticamente cuando tengas suficiente XP.",
    "base.pref_compact_disabled": "Modo Compacto DESACTIVADO",
    "base.pref_compact_disabled_desc": "Los menus usaran formato completo.",
    "base.pref_compact_enabled": "Modo Compacto ACTIVADO",
    "base.pref_compact_enabled_desc": "Los menus usaran formato compacto para movil/pantallas pequenas.",
    "base.pref_compact_enabled_keys": "Usa teclas numericas para navegar los menus.",
    "base.pref_font_set": "Fuente del terminal configurada a: {0}",
    "base.pref_font_update": "  La fuente se actualizara en el terminal en un momento.",
    "base.pref_intimate_fade": "Las escenas intimas ahora se 'desvanecen a negro'",
    "base.pref_intimate_full": "Las escenas intimas ahora mostraran contenido completo",
    "base.pref_sr_disabled": "Modo Lector de Pantalla DESACTIVADO",
    "base.pref_sr_disabled_desc": "Los menus usaran formato visual con arte ASCII.",
    "base.pref_sr_enabled": "Modo Lector de Pantalla ACTIVADO",
    "base.pref_sr_enabled_desc": "Los menus usaran formato de texto plano simplificado.",
    "base.pref_telemetry_disabled": "Telemetria Alpha DESACTIVADA",
    "base.pref_telemetry_disabled_desc": "Ya no recopilaremos estadisticas anonimas de juego.",
    "base.pref_telemetry_enabled": "Telemetria Alpha ACTIVADA",
    "base.pref_telemetry_enabled_desc": "Gracias por ayudarnos a mejorar el juego!",
    "base.pref_theme_set": "Tema de color configurado a: {0}",
    "base.qc_cmds": "Cmds  ",
    "base.qc_help": "Ayuda  ",
    "base.qc_inv": "Inv ",
    "base.qc_inventory": "Inventario  ",
    "base.qc_prefs": "Prefs  ",
    "base.qc_return_suffix": "olver  ",
    "base.qc_status_suffix": "stado  ",
    "base.rel_enemy": "Enemigo",
    "base.rel_friends": "Amigos",
    "base.rel_hated": "Odiado",
    "base.rel_hostile": "Hostil",
    "base.rel_married": "Casado",
    "base.rel_neutral": "Neutral",
    "base.rel_passionate": "Apasionado",
    "base.rel_respected": "Respetado",
    "base.rel_trusted": "Confiable",
    "base.rel_wary": "Cauteloso",
    "base.rest_available_after": "  Descanso disponible despues de las {0}:00 PM (Noche).",
    "base.rumor_castle": "Se habla de un pasaje secreto en el castillo. Pero ya he dicho demasiado.",
    "base.rumor_creature": "En lo profundo del calabozo, hay una criatura que custodia riquezas inimaginables.",
    "base.rumor_dark_alley": "He oido susurros de una tienda oculta en el Callejon Oscuro...",
    "base.rumor_healers": "Los curanderos pueden curar casi cualquier cosa, por un precio.",
    "base.rumor_king": "El rey se vuelve paranoico. Ve enemigos en todas partes.",
    "base.rumor_lower_levels": "Algunos aventureros nunca regresan de los niveles inferiores. Elige tu profundidad sabiamente.",
    "base.rumor_manwe": "Dicen que el mismo Manwe maldijo estos calabozos. Pero eso es solo un cuento... verdad?",
    "base.rumor_npc_items": "Algunos NPCs portan objetos poderosos. Derrotales en duelo y reclama su equipo!",
    "base.rumor_old_gods": "Los dioses antiguos se agitan en sus prisiones. Se avecinan tiempos oscuros.",
    "base.rumor_seals": "Dicen que siete sellos antiguos yacen ocultos en las profundidades del calabozo...",
    "base.rumor_stranger": "Un misterioso extrano ha sido visto por el pueblo. No confies en nadie.",
    "base.rumor_team": "Unete a otros si quieres sobrevivir los niveles mas profundos.",
    "base.rumor_temple": "Los sacerdotes del templo saben mas de lo que aparentan sobre los dioses antiguos.",
    "base.rumor_veloura": "He oido que hay una forma de salvar a Veloura... si tienes el valor para intentarlo.",
    "base.rumor_wave": "Una ola regresa al oceano... lo que sea que signifique. Tonterias cripticas si me preguntas.",
    "base.seals_collected": "{0}/7 recolectados",
    "base.server_time": "  Hora del Servidor: {0}",
    "base.shout_class_arcane": "murmura palabras arcanas",
    "base.shout_class_blade": "prueba el filo de una hoja",
    "base.shout_class_blessing": "ofrece una bendicion",
    "base.shout_class_flex": "flexiona sus musculos",
    "base.shout_class_polish": "pule su arma",
    "base.shout_class_pray": "reza en silencio",
    "base.shout_class_shadows": "observa desde las sombras",
    "base.shout_class_tome": "lee de un tomo antiguo",
    "base.shout_evil_curse": "murmura una maldicion entre dientes",
    "base.shout_evil_dagger": "afila una daga mientras te observa",
    "base.shout_evil_glare": "te mira amenazadoramente",
    "base.shout_evil_gold": "mira tu bolsa de oro con hambre",
    "base.shout_evil_laugh": "rie friamente",
    "base.shout_evil_sneer": "se burla de los debiles",
    "base.shout_evil_spit": "escupe al suelo cuando pasas",
    "base.shout_good_hum": "tararea una tonada alegre",
    "base.shout_good_news": "comparte noticias de sus ultimas aventuras",
    "base.shout_good_nod": "asiente respetuosamente",
    "base.shout_good_rumor": "menciona un rumor que escucho",
    "base.shout_good_smile": "sonrie calidamente",
    "base.shout_good_sword": "practica formas de espada con gracia",
    "base.shout_good_wave": "ofrece un saludo amistoso",
    "base.shout_neutral_business": "sigue con sus asuntos",
    "base.shout_neutral_chat": "charla con un mercader",
    "base.shout_neutral_gold": "cuenta sus monedas de oro",
    "base.shout_neutral_merchandise": "examina alguna mercancia",
    "base.shout_neutral_stretch": "se estira tras un largo viaje",
    "base.shout_neutral_thought": "parece perdido en sus pensamientos",
    "base.shout_neutral_yawn": "bosteza perezosamente",
    "base.slot_arms": "Brazos:    ",
    "base.slot_body": "Cuerpo:    ",
    "base.slot_cloak": "Capa:      ",
    "base.slot_face": "Cara:      ",
    "base.slot_feet": "Pies:      ",
    "base.slot_hands": "Manos:     ",
    "base.slot_head": "Cabeza:    ",
    "base.slot_left_ring": "Anillo Izq:",
    "base.slot_legs": "Piernas:   ",
    "base.slot_main_hand": "Mano Ppal: ",
    "base.slot_neck": "Cuello:    ",
    "base.slot_off_hand": "Mano Sec:  ",
    "base.slot_right_ring": "Anillo Der:",
    "base.slot_waist": "Cintura:   ",
    "base.standing_approves": "  {0} aprueba! (+10 reputacion)",
    "base.standing_decreased": "  Tu reputacion con {0} ha disminuido! (-50)",
    "base.standing_friendly": " (Amistoso)",
    "base.standing_hated": " (Odiado)",
    "base.standing_honored": " (Honrado)",
    "base.standing_hostile": " (Hostil)",
    "base.standing_neutral": " (Neutral)",
    "base.standing_revered": " (Reverenciado)",
    "base.standing_unfriendly": " (Hostil)",
    "base.stat_active_bonuses": "Bonificaciones Activas:",
    "base.stat_active_buffs": "Mejoras Activas:",
    "base.stat_active_effects": "Efectos Activos:",
    "base.stat_age": "Edad: ",
    "base.stat_agnostic": "Ninguno (Agnostico)",
    "base.stat_align_abilities": "  Habilidades de Alineamiento:",
    "base.stat_allegiance": "Lealtad: ",
    "base.stat_awakening": "  Despertar: {0} ({1}/7)",
    "base.stat_children": "Hijos: ",
    "base.stat_chivalry": "Caballeria: ",
    "base.stat_class": "Clase: ",
    "base.stat_combat_style": "Estilo de Combate: ",
    "base.stat_current_level": "Nivel Actual: ",
    "base.stat_darkness": "  |  Oscuridad: ",
    "base.stat_days": "{0} dias",
    "base.stat_deepest_floor": "Piso mas Profundo: ",
    "base.stat_evil": " Malvado",
    "base.stat_faction_hint": "  Visita el Castillo, Templo o Callejon Oscuro para saber mas.",
    "base.stat_faction_standing": "Reputacion de Faccion:",
    "base.stat_gold_bank": "Oro en Banco: ",
    "base.stat_gold_hand": "Oro en Mano: ",
    "base.stat_height": "  |  Altura: ",
    "base.stat_holy": "  Santo ",
    "base.stat_loyalty": "Lealtad: ",
    "base.stat_marital": "Estado Civil: ",
    "base.stat_married": "Casado",
    "base.stat_married_to": " con ",
    "base.stat_mental": "  |  Salud Mental: ",
    "base.stat_monarch": "*** MONARCA REINANTE ***",
    "base.stat_monster_defeats": "  |  Derrotas por Monstruos: ",
    "base.stat_monster_kills": "Monstruos Eliminados: ",
    "base.stat_monster_winrate": "Victoria vs Monstruos: ",
    "base.stat_name": "Nombre: ",
    "base.stat_no_faction": "No has jurado lealtad a ninguna faccion.",
    "base.stat_old_gods": "Dioses Antiguos: ",
    "base.stat_player_defeats": "  |  Derrotas por Jugadores: ",
    "base.stat_player_kills": "Jugadores Eliminados: ",
    "base.stat_pregnancy": "Embarazo: ",
    "base.stat_pvp_winrate": "Victoria PvP: ",
    "base.stat_race": "  |  Raza: ",
    "base.stat_rank": "Rango: ",
    "base.stat_royal_authority": "  Autoridad Real: +10% ATQ, +10% DEF, +5% HP",
    "base.stat_seals": "Sellos Antiguos: ",
    "base.stat_sex": "  |  Sexo: ",
    "base.stat_single": "Soltero",
    "base.stat_spouses_total": "  ({0} conyuges en total)",
    "base.stat_team": "Equipo: ",
    "base.stat_total_wealth": "Riqueza Total: ",
    "base.stat_weight": "  |  Peso: ",
    "base.stat_worshipped_god": "Dios Adorado: ",
    "base.stat_xp_need_total": " (Necesitas {0} total)",
    "base.stat_xp_next": "XP para Siguiente Nivel: ",
    "base.style_dual_wield": "Doble Arma (+1 ataque, -10% defensa)",
    "base.style_one_handed": "Una Mano",
    "base.style_sword_board": "Espada y Escudo (equilibrado, 20% bloqueo)",
    "base.style_two_handed": "Dos Manos (+25% dano, -15% defensa)",
    "base.talking_to": "Hablando con: {0}",
    "base.throne_belongs_to": "  El trono ahora pertenece a {0}.",
    "base.throne_vacant": "  El trono esta vacante.",
    "base.total_wealth": "  Riqueza Total: ",
    "base.training_points_hint": "  Ganaste puntos de entrenamiento! Visita al Maestro de Nivel para gastarlos.",
    "base.try_hint": "Prueba: [",
    "base.type_help": "  Escribe /help o solo / para ver los comandos.",
    "base.unknown_command": "  Comando desconocido: /{0}",
    "base.unknown_quest": "  • {0}",
    "base.visit_healer": "  Visita al Curandero para comprar algunos.",
    "base.weapon_power": "  Poder de Arma: ",
    "base.what_do_you_do": "Que haces?",
    "base.whisper_approving": "  Notas que algunos NPCs asienten con aprobacion al pasar.",
    "base.whisper_neutral": "  Notas que algunos NPCs susurran entre si cuando entras.",
    "base.whisper_uneasy": "  Notas que algunos NPCs intercambian miradas incomodas al llegar.",
    "base.who_talk_to": "  Con quien te gustaria hablar?",
    "base.world_boss_rampaging": "  *** {0} esta arrasando el reino! Escribe /boss para unirte a la pelea! ***",
    "base.wrath_active": "*** IRA DIVINA ACTIVA ***",
    "base.wrath_angered": "  Enfurecido: {0}",
    "base.wrath_by_worshipping": "  Por adorar a: {0}",
    "base.wrath_minor": "Menor (traicion de mismo alineamiento)",
    "base.wrath_moderate": "Moderada (traicion de alineamiento opuesto)",
    "base.wrath_punishment_hint": "  (El castigo puede ocurrir durante la exploracion del calabozo)",
    "base.wrath_severe": "Severa (gran traicion de alineamiento opuesto)",
    "base.wrath_severity": "  Severidad: {0}",
    "base.wrath_unknown": "Desconocida",
    "base.you_notice": "Notas:",
}
