translations = {
    # === CASTLE (93 keys) ===
    "castle.adopt_orphan": "Adoptar nuevo huerfano ({0} oro del tesoro)",
    "castle.arrest_which": "Arrestar conspiradores de cual conspiracion?",
    "castle.betrayal_noted": "Tu traicion a la corona ha sido registrada.",
    "castle.bounty_board_desc": "El tablero de recompensas del Rey muestra criminales buscados y amenazas.",
    "castle.bribe_which": "Sobornar a cual miembro de la corte para aumentar lealtad?",
    "castle.candidate_requirements": "Los candidatos deben ser nivel 10+, sin equipo, y no un NPC de historia.",
    "castle.challenge_failed": "Tu desafio ha fracasado. Apenas escapas con vida.",
    "castle.child_may_born": "Un hijo podria nacer de tu matrimonio con el tiempo.",
    "castle.children_delighted": "Los ninos estan encantados con tu generosidad!",
    "castle.choose_1_4": "Elige (1-4, o R para cancelar): ",
    "castle.choose_merc_role": "Elige un rol de mercenario:",
    "castle.choose_r_cancel": "Elige (o R para cancelar): ",
    "castle.chosen_challenge": "Has elegido desafiar por el trono!",
    "castle.claim_strengthened": "Su derecho al trono se ha fortalecido.",
    "castle.closed": "CERRADO",
    "castle.closed_past": "abierto",
    "castle.commands": "Comandos:",
    "castle.comment_label": "    {0}",
    "castle.commission_guard": "Guardia Real (puesto gratis, alta lealtad)",
    "castle.commission_mercenary": "Mercenario Real (guardaespaldas de mazmorra, mitad de costo)",
    "castle.commission_npc": "Liberar como ciudadano NPC",
    "castle.commission_orphan": "Comisionar huerfano (reclutar edad {0}+, 1,000 oro)",
    "castle.compassion_standing": "Tu compasion aumenta tu reputacion con el pueblo!",
    "castle.consider_marriage": "Considera un matrimonio real para producir herederos.",
    "castle.court_action": "Accion de la corte: ",
    "castle.court_member_entry": "  {0}. {1} ({2}, {3})",
    "castle.court_members": "MIEMBROS DE LA CORTE:",
    "castle.court_not_established": "La corte aun no ha sido establecida.",
    "castle.current_bodyguards": "Guardaespaldas Actuales:",
    "castle.designate_which": "Designar cual heredero? (numero): ",
    "castle.dismiss_which": "Despedir a cual miembro de la corte?",
    "castle.dismiss_which_bodyguard": "Despedir a cual guardaespaldas?",
    "castle.divorce_cancelled": "Divorcio cancelado.",
    "castle.divorce_warning": "ADVERTENCIA: El divorcio tendra graves consecuencias politicas!",
    "castle.eligible_orphans": "Huerfanos elegibles para comision:",
    "castle.establishment_toggled": "El {0} ahora esta {1}!",
    "castle.faction_neutral": "Neutral",
    "castle.faction_relations": "RELACIONES DE FACCION:",
    "castle.gift_amount": "Cantidad del regalo (oro): ",
    "castle.give_gifts_desc": "Dar regalos (aumentar felicidad)",
    "castle.heirs_title": "HEREDEROS AL TRONO:",
    "castle.hire_mercs_desc": "Contrata mercenarios de elite para acompanarte en la mazmorra.",
    "castle.insufficient_5000": "Fondos insuficientes! (Necesitas 5,000 oro)",
    "castle.insufficient_funds": "Fondos insuficientes!",
    "castle.insufficient_trial": "Fondos del tesoro insuficientes para el juicio!",
    "castle.intel_reports": "INFORMES DE INTELIGENCIA:",
    "castle.leave_team_crown": "Dejar tu equipo para buscar la corona? (S/N): ",
    "castle.legitimize_cost": "Cuesta 5,000 oro y reduce el derecho de herederos existentes.",
    "castle.legitimize_desc": "Puedes legitimar un hijo bastardo o adoptar un pupilo como heredero.",
    "castle.loyalty_raised_crown": "Lealtad: 90 (elevada por la corona)",
    "castle.marriage_desc_1": "Un matrimonio real puede asegurar alianzas, llenar el tesoro con dote,",
    "castle.marriage_desc_2": "y producir herederos para continuar tu dinastia.",
    "castle.must_leave_team_challenge": "Para desafiar por el trono, debes abandonar tu equipo.",
    "castle.new_heir_name": "Nombre del nuevo heredero: ",
    "castle.no_bodyguards": "No tienes guardaespaldas a tu servicio.",
    "castle.no_bodyguards_dismiss": "No tienes guardaespaldas que despedir.",
    "castle.no_bounties": "No hay recompensas publicadas por la Corona.",
    "castle.no_candidates": "No hay candidatos adecuados para matrimonio en este momento.",
    "castle.no_discovered_plots": "No hay complots descubiertos. Usa 'Detectar Amenazas' del Mago de la Corte.",
    "castle.no_guard_slots": "No hay puestos de guardia disponibles!",
    "castle.no_heir_designated": "Ningun heredero ha sido designado oficialmente.",
    "castle.no_heirs": "No tienes herederos.",
    "castle.no_heirs_designate": "No tienes herederos que designar!",
    "castle.no_merc_slots": "No hay puestos de mercenario disponibles!",
    "castle.no_orphans_gift": "No hay huerfanos a quienes regalar.",
    "castle.no_plots": "No se detectaron complots. La corte parece estable.",
    "castle.number_cancel": "Numero (0 para cancelar): ",
    "castle.open": "CERRADO",
    "castle.opened": "abierto",
    "castle.options": "Opciones:",
    "castle.orders_desc": "Emitir decretos y administrar el reino.",
    "castle.orders_menu_line1": "(E)stablecimientos   (P)roclamacion     (R)ecompensa",
    "castle.orders_menu_line2": "(V)olver",
    "castle.orphan_not_eligible": "Ese huerfano no es elegible para comision.",
    "castle.orphan_released": "Se abrira su propio camino, agradecido por el cuidado de la corona.",
    "castle.potential_candidates": "Candidatos Potenciales para Matrimonio:",
    "castle.proceed_yn": "Deseas continuar? (S/N): ",
    "castle.propose_candidate": "Proponer a cual candidato? (0 para cancelar): ",
    "castle.realm_at_peace": "El reino esta en paz... por ahora.",
    "castle.reconsider": "Lo reconsideras y das un paso atras.",
    "castle.role_dps_desc": "      - Explorador. Alto dano con ataques rapidos.",
    "castle.role_healer": "Sanador",
    "castle.role_healer_desc": "   - Clerigo. Sana aliados heridos, lanza hechizos sagrados.",
    "castle.role_support": "Apoyo",
    "castle.role_support_desc": "  - Paladin. Luchador equilibrado con sanacion y hechizos.",
    "castle.role_tank": "Tanque",
    "castle.role_tank_desc": "     - Guerrero. Alto PV y defensa, atrae ataques enemigos.",
    "castle.select_orphan": "Selecciona numero de huerfano: ",
    "castle.siege_vs": "=== {0} {1} vs {2} ===",
    "castle.try_more_renowned": "Quizas intenta de nuevo cuando seas mas reconocido...",
    "castle.use_detect_threats": "Usa el hechizo 'Detectar Amenazas' del Mago de la Corte.",
    "castle.visit_quest_hall": "Visita el Salon de Misiones en la Calle Principal para reclamar recompensas.",
    "castle.wanted": "BUSCADO:",

    # === INN (77 keys) ===
    "inn.alignment_compatible": "  Alineacion: Compatible (buena afinidad)",
    "inn.alignment_kindred": "  Alineacion: Almas afines (excelente afinidad)",
    "inn.alignment_neutral": "  Alineacion: Neutral (afinidad estandar)",
    "inn.alignment_opposing": "  Alineacion: Opuesta (pobre afinidad)",
    "inn.awaken_temple": "Despiertas en el Templo de la Luz...",
    "inn.bbs_desc": " Taberna humeante. La cerveza fluye. Seth Able te observa desde el rincon.",
    "inn.bbs_drink": "Beber",
    "inn.bbs_drinking_game": "Competencia",
    "inn.bbs_food": "Comida",
    "inn.bbs_gambling": "Apuestas",
    "inn.bbs_gossip": "Rumores",
    "inn.bbs_rest": "Descansar",
    "inn.bbs_seth": "Seth",
    "inn.bbs_talk": "Hablar",
    "inn.bbs_train": "Entrenar",
    "inn.challenging_npc": "Desafiando a {0} a un Duelo!",
    "inn.choose_patron": "Elige a quien acercarte (0-8): ",
    "inn.defeated_npc": "Has derrotado a {0}!",
    "inn.drink_bitter_brew": "La amarga bebida baja por tu garganta...",
    "inn.drink_effect_charisma": "La cerveza aumenta tu confianza! (+2 Carisma temporal)",
    "inn.drink_effect_hp": "Te sientes relajado y restaurado. (+5 PV)",
    "inn.drink_effect_strength": "Te sientes algo mareado pero mas fuerte! (+1 Fuerza temporal)",
    "inn.drink_effect_wisdom": "El alcohol te hace imprudente! (-1 Sabiduria temporal)",
    "inn.drink_order_ale": "Pides una jarra de cerveza al tabernero.",
    "inn.fight_now_prompt": "Pelear ahora? (s/N): ",
    "inn.gossip_lean_back": "Te recuestas y escuchas hablar a los parroquianos...",
    "inn.interacting_with": "Interactuando con {0}",
    "inn.invalid_choice": "Opcion invalida. Escribe 'look' para redibujar el menu.",
    "inn.navigation": "Navegacion:",
    "inn.npc_accepts_challenge": "{0} acepta tu desafio!",
    "inn.npc_changed_mind": "{0}: \\",
    "inn.npc_declines_duel": "{0} se rie y te hace un gesto de desprecio. \\",
    "inn.option_challenge_duel": " Desafio - Retar a un duelo",
    "inn.option_gift_cost": " Regalo - Dar un regalo (cuesta 50 oro)",
    "inn.option_talk_deep": " Hablar - Tener una conversacion profunda (coquetear, confesar, romance)",
    "inn.patrons_following": "Ves a los siguientes parroquianos aqui:",
    "inn.patrons_quiet": "La posada esta tranquila esta noche. No hay parroquianos interesantes.",
    "inn.rel_neutral": "Neutral",
    "inn.rest_dark_memories": "  Tu descanso es perturbado por oscuros recuerdos...",
    "inn.rest_dream_begins": "Mientras dormitas, un sueno toma forma...",
    "inn.rest_fatigue_reduced": "Un breve descanso alivia tu cansancio. (Fatiga -{0})",
    "inn.rest_full_health": "Ya estas a plena salud.",
    "inn.rest_quiet_corner": "Encuentras un rincon tranquilo y descansas un rato...",
    "inn.rest_recover_hp": "Te sientes renovado y recuperas {0} PV.",
    "inn.rest_recover_mana": "Tu mente se despeja, recuperando {0} mana.",
    "inn.rest_shadow_fades": "La Bendicion de las Sombras se desvanece mientras descansas...",
    "inn.return_to_menu": "[0] Volver al menu de la posada",
    "inn.seth_back_away": "Logras alejarte de Seth Able!",
    "inn.seth_bartender_drops": "Hasta el tabernero deja caer su vaso de asombro!",
    "inn.seth_beaten_again": "Has vencido a Seth Able otra vez!",
    "inn.seth_chuckle_retreat": "Los otros parroquianos se rien de tu retirada.",
    "inn.seth_come_back": "Seth Able te despide con un gesto desdenoso.",
    "inn.seth_coward": "Seth Able: \\",
    "inn.seth_crash_table": "Te estrellas contra una mesa y caes al suelo...",
    "inn.seth_earn_reward": "Ganas {0} experiencia y {1} oro.",
    "inn.seth_enough": "Seth Able te despide con un gesto desdenoso.",
    "inn.seth_fights_today": "(Peleas hoy: {0}/3)",
    "inn.seth_fist_connects": "El enorme puno de Seth Able conecta con tu mandibula!",
    "inn.seth_incredible": "INCREIBLE! Has derrotado a Seth Able!",
    "inn.seth_inn_falls_silent": "La posada se silencia cuando te acercas a Seth Able...",
    "inn.seth_knocks_out": "El poderoso golpe de Seth Able te deja inconsciente!",
    "inn.seth_legend": "Ahora eres una leyenda en esta taberna!",
    "inn.seth_massive_headache": "Despiertas mas tarde con un terrible dolor de cabeza...",
    "inn.seth_next_time": "'Quizas la proxima, chico!' gruñe Seth.",
    "inn.seth_passed_out": "Seth Able esta desmayado bajo una mesa. Intenta mas tarde.",
    "inn.seth_patrons_cheer": "Los parroquianos aclaman, pero ya han visto esto antes...",
    "inn.seth_patrons_laugh": "Los parroquianos rien mientras Seth vuelve a su bebida.",
    "inn.seth_player_stats": "Tu - Nivel {0} - PV: {1}/{2}",
    "inn.seth_shocked_silence": "La posada entera erupciona en un silencio atonito...",
    "inn.seth_stats_display": "Seth Able - Nivel {0} - PV: {1}",
    "inn.seth_walk_away": "'Eso es, vete!' grita Seth detras de ti.",
    "inn.seth_warning": "ADVERTENCIA: Seth Able es un oponente peligroso!",
    "inn.seth_waves_off": "Seth Able te despide con un gesto desdenoso.",
    "inn.teaser_scarred_soldier": "  En el rincon lejano, un soldado con cicatrices bebe solo.",
    "inn.teaser_seen_fights": "  Parece haber visto su cuota de peleas. No levanta la vista.",
    "inn.victory_spreads": "La noticia de tu victoria se extiende por la posada!",
    "inn.what_to_do": "Que te gustaria hacer?",

    # === INVENTORY (37 keys) ===
    "inventory.back": "  [Q] Volver",
    "inventory.cant_equip": "Este objeto no se puede equipar.",
    "inventory.cant_equip_unidentified": "No puedes equipar un objeto sin identificar.",
    "inventory.cursed_cant_drop": "El {0} esta MALDITO! No puedes soltarlo.",
    "inventory.cursed_cant_unequip": "El {0} esta MALDITO! No puedes desequiparlo.",
    "inventory.drop_item": "  [D] Soltar Objeto",
    "inventory.dropped_item": "Sueltas el {0}.",
    "inventory.enter_drop_number": "Numero de objeto a soltar (B1, B2, etc): ",
    "inventory.equip_identify_first": "  [E] Equipar Objeto (identificar primero)",
    "inventory.equip_item": "  [E] Equipar Objeto",
    "inventory.equipment_bonuses": "=== BONIFICACIONES DE EQUIPO ===",
    "inventory.equipped": "Equipado {0}.",
    "inventory.equipped_items": "=== OBJETOS EQUIPADOS ===",
    "inventory.left_finger": "  (L) Dedo izquierdo",
    "inventory.manage_item": "ADMINISTRAR OBJETO",
    "inventory.no_items_unequip": "No hay objetos que desequipar.",
    "inventory.nothing": "Nada",
    "inventory.one_handed_where": "Esta es un arma de una mano. Donde quieres equiparla?",
    "inventory.options": "Opciones:",
    "inventory.other": "Otro: ",
    "inventory.req_evil": "Alineacion maligna",
    "inventory.req_good": "Alineacion buena",
    "inventory.return_inventory": "  [Q] Volver al inventario",
    "inventory.returned_backpack": "(Objeto devuelto a tu mochila)",
    "inventory.right_finger": "  (R) Dedo derecho",
    "inventory.slot_left_ring": "Anillo Izquierdo",
    "inventory.slot_right_ring": "Anillo Derecho",
    "inventory.stats": "Stats: ",
    "inventory.style_one_handed": "Una Mano",
    "inventory.style_sword_board": "Espada y Escudo (equilibrado, 20% bloqueo)",
    "inventory.unequip_item": "  [U] Desequipar este objeto",
    "inventory.unequipped": "Desequipado {0}.",
    "inventory.unequipped_count": "Desequipado {0} objeto(s) a tu mochila.",
    "inventory.unequipping_all": "Desequipando todos los objetos...",
    "inventory.visit_healer_curse": "Visita al Sanador para remover la maldicion.",
    "inventory.visit_magic_shop": "Llevalo a la Tienda Magica para identificarlo primero.",
    "inventory.which_finger": "Equipar en cual dedo?",
}
