translations = {
    "dungeon.active_party": "  Grupo Activo:",
    "dungeon.air_colder": "El aire se vuelve mas frio.",
    "dungeon.allies_rejoin": "{0} aliado(s) se unen a tu grupo de mazmorra de tu ultima sesion.",
    "dungeon.allies_skipped": "{0} aliado(s) no pudieron unirse - grupo lleno (max {1}).",
    "dungeon.allies_too_expensive": "Estos aliados exigen mas oro del que tienes:",
    "dungeon.ambient_clang": "Un lejano golpe metalico resuena desde las profundidades.",
    "dungeon.ambient_draft": "Una corriente fria se filtra entre las piedras.",
    "dungeon.ambient_drips": "El agua gotea en algun lugar en la oscuridad.",
    "dungeon.ambient_groan": "El suelo se asienta con un gemido grave.",
    "dungeon.ambient_shadows": "Las sombras al borde de tu luz parecen moverse.",
    "dungeon.ambient_skitters": "Algo se arrastra debilmente detras de los muros.",
    "dungeon.ambient_torch": "Tu antorcha parpadea con una corriente invisible.",
    "dungeon.ambush": "EMBOSCADA! Los monstruos atacan!",
    "dungeon.ancient_presence_sealed": "Sientes una presencia antigua sellada en esta camara...",
    "dungeon.ancient_scroll_discover": "Descubres un pergamino antiguo en una grieta del muro.",
    "dungeon.ancient_scroll_header": "PERGAMINO ANTIGUO",
    "dungeon.ancient_scroll_symbols": "Extranos simbolos brillan tenuemente en el pergamino.",
    "dungeon.and_separator": " y ",
    "dungeon.arrive_at_level": "Llegas al Nivel {0}",
    "dungeon.artifact_deeper": "El artefacto yace en algun lugar mas profundo de la mazmorra...",
    "dungeon.at_the_inn": "  En la Posada:",
    "dungeon.awaken_temple": "Despiertas en el Templo de la Luz...",
    "dungeon.awakening_0": "El mundo parece solido y separado. Solo conoces lo fisico.",
    "dungeon.awakening_1": "En momentos de silencio, los limites se sienten delgados...",
    "dungeon.awakening_2": "Que es una ola sino el oceano en movimiento?",
    "dungeon.awakening_3": "Cuando el agua se encuentra con el agua, cual pierde su identidad?",
    "dungeon.awakening_4": "Algunas almas son mas viejas que los cuerpos que visten.",
    "dungeon.awakening_5": "Hijo de las aguas profundas, empiezas a recordar.",
    "dungeon.awakening_6": "Los limites se difuminan. El yo y el otro se funden en los bordes.",
    "dungeon.awakening_7": "La ola recuerda que es agua. Bienvenido de vuelta, Sonador.",
    "dungeon.awakening_unknown": "Estado desconocido",
    "dungeon.bbs_boss_presence": " >> Una presencia poderosa domina esta sala! <<",
    "dungeon.bbs_danger": "Peligro: ",
    "dungeon.bbs_exits": " Salidas:",
    "dungeon.bbs_gold": " Oro:",
    "dungeon.bbs_hostile_creatures": " >> Criaturas hostiles acechan en las sombras! <<",
    "dungeon.bbs_lv": " Nv:",
    "dungeon.bbs_mana": " Mana:",
    "dungeon.bbs_notice": " Aviso: ",
    "dungeon.bbs_potions": " Pociones:",
    "dungeon.bbs_stairs_down": " >> Escaleras descienden <<",
    "dungeon.bbs_treasure_glints": " >> Algo valioso brilla en la oscuridad! <<",
    "dungeon.bodyguards_join": "  Tus guardaespaldas reales te acompanan ({0}):",
    "dungeon.bonus_gold": "  Oro Extra: +{0}",
    "dungeon.bonus_gold_share": "  Oro Extra: +{0} (tu parte: {1})",
    "dungeon.bonus_xp": "  XP Extra: +{0}",
    "dungeon.bonus_xp_share": "  XP Extra: +{0} (tu parte: {1})",
    "dungeon.boss_blocks_path_sr": "AVISO: Un poderoso [{0}]{1}[/] bloquea tu camino!",
    "dungeon.boss_blocks_path_visual": "Un poderoso [{0}]{1}[/] bloquea tu camino!",
    "dungeon.boss_bonus": "Bonificacion: {0} oro, {1} experiencia!",
    "dungeon.boss_bonus_share": "Bonificacion: {0} oro, {1} XP (tu parte: {2}o, {3} XP)",
    "dungeon.boss_phrase_abyssal": "El vacio ansea tu esencia...",
    "dungeon.boss_phrase_catacombs": "Los muertos no descansan aqui...",
    "dungeon.boss_phrase_caverns": "Estas profundidades son mias!",
    "dungeon.boss_phrase_default": "Te atreves a desafiarme?",
    "dungeon.boss_phrase_demon": "Tu alma alimentara el infierno!",
    "dungeon.boss_phrase_frozen": "El frio te reclamara, como reclama todo...",
    "dungeon.boss_phrase_ruins": "Perturbas poderes mas alla de tu comprension!",
    "dungeon.boss_phrase_sewers": "No deberias haber bajado aqui...",
    "dungeon.boss_phrase_volcanic": "Arde en los fuegos de las profundidades!",
    "dungeon.boss_room_unconquered": "La sala del jefe sigue sin conquistar.",
    "dungeon.breadcrumb_1": "Los muros aqui parecen mas antiguos que el resto de la mazmorra. Extranos simbolos estan tallados en la piedra.",
    "dungeon.breadcrumb_2": "Tienes la incomoda sensacion de que algo te observa. No un monstruo. Algo mas.",
    "dungeon.breadcrumb_3": "Las sombras aqui abajo parecen moverse por si solas a veces. Probablemente solo es la luz de la antorcha.",
    "dungeon.breadcrumb_4": "Puedes oir algo como una respiracion lenta y pesada desde abajo. Probablemente solo es el viento.",
    "dungeon.breadcrumb_5": "El aire aqui abajo sabe levemente a sal, como el oceano. Eso no deberia ser posible tan bajo tierra.",
    "dungeon.breadcrumb_6": "Captas un sonido tenue, casi como susurros, pero no puedes distinguir las palabras.",
    "dungeon.breadcrumb_7": "Tu antorcha parpadea y notas algo tallado en el muro. Parece una ola.",
    "dungeon.breadcrumb_8": "Pasas junto a un charco y tu reflejo parece extrano. Cuando miras de nuevo, esta bien.",
    "dungeon.breadcrumb_floor": "Calle Principal > Mazmorras > Nivel {0}",
    "dungeon.breadcrumb_old_woman": "  Cuando la multitud se dispersa, una anciana agarra tu brazo.",
    "dungeon.breadcrumb_room": "Mazmorras > Nivel {0} > {1}",
    "dungeon.break_camp": "Levantas el campamento, recuperado pero cauteloso.",
    "dungeon.cannot_venture_deeper": "No puedes aventurarte mas alla del nivel {0} con tu fuerza actual.",
    "dungeon.chamber_empty": "La camara esta vacia. La presencia antigua ya fue tratada.",
    "dungeon.chapter_ascension": "Ascension - Los preparativos finales",
    "dungeon.chapter_awakening": "El Despertar - Un extrano en Dorashire",
    "dungeon.chapter_choice": "La Eleccion - Decidiendo tu destino",
    "dungeon.chapter_epilogue": "Epilogo - Las consecuencias",
    "dungeon.chapter_faction": "Eleccion de Faccion - Eligiendo tu lealtad",
    "dungeon.chapter_final": "Confrontacion Final - Enfrenta al Creador",
    "dungeon.chapter_first_blood": "Primera Sangre - Aprendiendo a luchar",
    "dungeon.chapter_first_god": "Primer Dios - Enfrentando el poder divino",
    "dungeon.chapter_god_war": "Guerra Divina - Los Dioses Antiguos despiertan",
    "dungeon.chapter_rising": "Poder Creciente - Fortaleciendo tu poder",
    "dungeon.chapter_stranger": "El Extrano - Conociendo al guia misterioso",
    "dungeon.chapter_unknown": "Capitulo Desconocido",
    "dungeon.chapter_whispers": "Los Susurros - Los dioses comienzan a agitarse",
    "dungeon.chest_acid": "Acido salpica tu bolsa de monedas! Pierdes {0} oro!",
    "dungeon.chest_discover_material": "Entre el tesoro, descubres un {0}!",
    "dungeon.chest_find_gold": "Encuentras {0} monedas de oro!",
    "dungeon.chest_gain_exp": "Ganas {0} experiencia!",
    "dungeon.chest_leap_back": "Saltas hacia atras justo a tiempo!",
    "dungeon.chest_leave_alone": "Sabiamente dejas el cofre en paz y continuas.",
    "dungeon.chest_mimic": "El cofre SE MUEVE! Es un MIMICO!",
    "dungeon.chest_no_react": "No pudiste reaccionar a tiempo!",
    "dungeon.chest_opens_treasure": "El cofre se abre revelando un tesoro reluciente!",
    "dungeon.chest_party_finds": "El grupo encuentra {0} oro y {1} XP!",
    "dungeon.chest_poison_gas": "Gas venenoso! Recibes {0} de dano!",
    "dungeon.chest_poisoned": "Has sido envenenado!",
    "dungeon.chest_reflexes_saved": "Tus reflejos te salvaron! (Agilidad: {0})",
    "dungeon.chest_spikes": "Pinchos salen disparados! Recibes {0} de dano!",
    "dungeon.chest_trap": "CLIC! Es una trampa!",
    "dungeon.chest_your_share": "Tu parte: {0} oro, {1} XP",
    "dungeon.chivalry_grows": "Tu caballerosidad crece. Te estas convirtiendo en el Salvador.",
    "dungeon.chivalry_increase": "Tu caballerosidad aumenta en {0}!",
    "dungeon.chivalry_increases_slightly": "Tu caballerosidad aumenta ligeramente.",
    "dungeon.chivalry_mercy": "+75 Caballerosidad - Tu piedad habla mas fuerte que cualquier espada.",
    "dungeon.closing_allied": "Caminas hacia la plaza. La gente susurra, pero nadie se atreve a hablar contra ti.",
    "dungeon.closing_default": "Caminas hacia la plaza.",
    "dungeon.closing_defeated": "La multitud se aparta mientras caminas hacia la plaza. Nadie te mira por mucho tiempo.",
    "dungeon.closing_saved": "Caminas hacia la plaza y, por primera vez en mucho tiempo, el pueblo se siente mas ligero.",
    "dungeon.closing_spared": "Caminas hacia la plaza. Algunos asienten con respeto silencioso. Otros miran hacia otro lado.",
    "dungeon.companion_hp": "    {0} - PV: {1}/{2}",
    "dungeon.confirm_leave": "Salir de la mazmorra y volver al pueblo? (S/N): ",
    "dungeon.continuing": "  [Continuando donde lo dejaste...]",
    "dungeon.continuing_where_left_off": "[Continuando donde lo dejaste...]",
    "dungeon.corpse_animates": "El cadaver se anima! Guardian no-muerto!",
    "dungeon.current_chapter": "Capitulo Actual: ",
    "dungeon.current_level": "Nivel actual: {0}",
    "dungeon.damsel_harassed": "Una mujer esta siendo acosada por un grupo de rufianes.",
    "dungeon.damsel_header_sr": "-- DAMISELA EN APUROS --",
    "dungeon.damsel_header_visual": "-- DAMISELA EN APUROS --",
    "dungeon.damsel_ignore_1": "Te das la vuelta y finges no darte cuenta.",
    "dungeon.damsel_ignore_2": "Sus gritos se desvanecen mientras continuas tu camino...",
    "dungeon.damsel_join_ruffians": "Te unes a los rufianes en su vileza!",
    "dungeon.damsel_reward": "Ella te recompensa con {0} oro!",
    "dungeon.damsel_rush_defense": "Corres en su defensa!",
    "dungeon.damsel_screams": "Escuchas gritos resonando por el corredor!",
    "dungeon.damsel_shameful": "Este es un acto vergonzoso!",
    "dungeon.damsel_steal": "Robas {0} oro a la mujer.",
    "dungeon.damsel_thanks": "La mujer te agradece profusamente!",
    "dungeon.damsel_unhand_her": "Corres en su defensa!",
    "dungeon.danger_of": "Peligro {0} de 3",
    "dungeon.darkness_deepens": "Tu oscuridad se profundiza. Te estas convirtiendo en el Usurpador.",
    "dungeon.darkness_deeper": "La oscuridad se profundiza.",
    "dungeon.darkness_increase": "Tu oscuridad aumenta en {0}!",
    "dungeon.decline_pay": "Decides no pagar. Tus aliados no te acompanaran esta vez.",
    "dungeon.deepest_accessible": "Mas profundo accesible: {0} (tu nivel + 10)",
    "dungeon.defeat_old_god_first": "Debes derrotar al Dios Antiguo en este piso antes de descender.",
    "dungeon.difficulty_challenging": "Desafiante",
    "dungeon.difficulty_dangerous": "Peligroso",
    "dungeon.difficulty_deadly": "MORTAL",
    "dungeon.difficulty_easy": "Facil",
    "dungeon.difficulty_fair": "Justo",
    "dungeon.difficulty_trivial": "Trivial",
    "dungeon.divine_gratitude": "Un fragmento de gratitud divina llena tu corazon.",
    "dungeon.dream_takes_shape": "Mientras dormitas, un sueno toma forma...",
    "dungeon.duelist_accept": "Aceptas el desafio de {0}!",
    "dungeon.duelist_decline": "Declinas cortesmente el desafio.",
    "dungeon.duelist_decline_known_1": "{0} parece decepcionado pero comprensivo.",
    "dungeon.duelist_decline_new_1": "{0} asiente respetuosamente.",
    "dungeon.duelist_emerges": "Un guerrero emerge de las sombras: {0}",
    "dungeon.duelist_header": "=== EL DUELISTA ===",
    "dungeon.duelist_insult": "Lanzas insultos al duelista!",
    "dungeon.duelist_insult_known_1": "Los ojos de {0} brillan con furia!",
    "dungeon.duelist_insult_new_1": "El rostro de {0} se contorsiona de rabia!",
    "dungeon.duelist_loss1_1": "{0} perdona tu vida!",
    "dungeon.duelist_loss3_1": "{0} suspira con decepcion.",
    "dungeon.duelist_loss_default_1": "{0} enfunda su espada.",
    "dungeon.duelist_record": "  Encuentros: {0} | Tus Victorias: {1} | Tus Derrotas: {2}",
    "dungeon.duelist_rewards": "+{0} oro, +{1} XP, +5 Caballerosidad",
    "dungeon.duelist_slain": "Has matado a {0} en combate deshonroso.",
    "dungeon.duelist_spirit_haunts": "Su espiritu te perseguira...",
    "dungeon.duelist_steel_clashes": "El acero choca contra el acero!",
    "dungeon.duelist_strength": "  Fuerza actual de {0}: Nivel {1}",
    "dungeon.duelist_walk_away": "{0} te observa alejarte.",
    "dungeon.echo_materializes": "  El eco de {0} se materializa a tu lado!",
    "dungeon.echoes_info": "  Los ecos de jugadores luchan como aliados IA con sus estadisticas reales.",
    "dungeon.echoing_voices_header": "=== VOCES RESONANTES ===",
    "dungeon.emerge_steps": "  Subes los ultimos escalones saliendo de la oscuridad.",
    "dungeon.emerge_sunlight": "  La luz del sol te ciega. El aire sabe diferente aqui arriba - limpio, vivo.",
    "dungeon.encounter_group_family": " de la familia {0}!",
    "dungeon.encounter_wiser": "El encuentro te deja mas sabio. (+{0} XP)",
    "dungeon.enter_target_level": "Ingresa nivel objetivo (o +/- para relativo): ",
    "dungeon.entering_dungeon": "Entras a la mazmorra...",
    "dungeon.event_desc_default": "descubre algo interesante",
    "dungeon.event_desc_lore": "descubre escritos antiguos",
    "dungeon.event_desc_memory": "experimenta una vision extrana",
    "dungeon.event_desc_merchant": "encuentra a un mercader errante",
    "dungeon.event_desc_mystery": "percibe algo inusual",
    "dungeon.event_desc_npc": "encuentra a alguien en la oscuridad",
    "dungeon.event_desc_puzzle": "descubre un mecanismo de rompecabezas",
    "dungeon.event_desc_rest": "encuentra un campamento seguro",
    "dungeon.event_desc_riddle": "encuentra una puerta de acertijos",
    "dungeon.event_desc_secret_boss": "perturba algo poderoso",
    "dungeon.event_desc_shrine": "encuentra un santuario misterioso",
    "dungeon.event_desc_treasure": "descubre un cofre del tesoro",
    "dungeon.event_hint_chest": ">> Un viejo cofre descansa en la esquina <<",
    "dungeon.event_hint_default": ">> Algo interesante hay aqui <<",
    "dungeon.event_hint_merchant": ">> Ves una figura junto a una pequena fogata <<",
    "dungeon.event_hint_mystery": ">> Algo inusual llama tu atencion <<",
    "dungeon.event_hint_npc": ">> Alguien mas esta aqui <<",
    "dungeon.event_hint_puzzle": ">> Extranos mecanismos cubren una pared <<",
    "dungeon.event_hint_rest": ">> Esta area parece relativamente segura <<",
    "dungeon.event_hint_settlement": ">> Luces y voces adelante - un asentamiento! <<",
    "dungeon.event_hint_shrine": ">> Un extrano altar irradia energia <<",
    "dungeon.examine_what": "Que quieres examinar?",
    "dungeon.explore_town_hint": "  Explora el pueblo y habla con NPCs memorables para iniciar sus historias.",
    "dungeon.face_god_prompt": "Deseas enfrentar a {0}? (S/N)",
    "dungeon.face_maelketh": "Deseas enfrentar a Maelketh, la Espada Rota? (S/N)",
    "dungeon.face_monsters": "Te enfrentas a {0} {1}!",
    "dungeon.fallen_adventurer_header": "=== AVENTURERO CAIDO ===",
    "dungeon.fallen_adventurer_journal": "Su diario desgastado yace abierto a su lado.",
    "dungeon.fallen_adventurer_remains": "Te encuentras con los restos de un {0} caido.",
    "dungeon.fallen_companions": "  Caidos:",
    "dungeon.fatigue_reduced": "Te sientes algo recuperado. (Fatiga -{0})",
    "dungeon.find_gold_coins": "Encuentras {0} monedas de oro.",
    "dungeon.find_healing_potions": "Encuentras {0} pociones de curacion.",
    "dungeon.first_clear_only": "(Bonificacion de completar solo en la primera vez)",
    "dungeon.flavor_abyssal": "La realidad se desmorona aqui. Que acecha mas alla de la cordura?",
    "dungeon.flavor_catacombs": "Antiguas tumbas se extienden ante ti. Los muertos no descansan en paz aqui.",
    "dungeon.flavor_caverns": "Cuevas naturales se retuercen en la oscuridad. Vida bioluminiscente proyecta sombras inquietantes.",
    "dungeon.flavor_default": "La oscuridad aguarda.",
    "dungeon.flavor_demon": "El infierno ha sangrado en este lugar. Gritos de tortura resuenan sin fin.",
    "dungeon.flavor_frozen": "Frio imposible. Tu aliento se congela. Cosas estan preservadas en el hielo.",
    "dungeon.flavor_ruins": "Las ruinas de una civilizacion olvidada. La magia aun perdura en estas piedras.",
    "dungeon.flavor_sewers": "El hedor es abrumador. Cosas acechan en las aguas fetidas abajo.",
    "dungeon.flavor_volcanic": "Rios de magma iluminan el camino. El calor es casi insoportable.",
    "dungeon.floor_recleared": "Has vuelto a limpiar este piso.",
    "dungeon.forged_alliance": "Has forjado una alianza mas alla de la comprension mortal.",
    "dungeon.ghost_appears": "Una figura espectral se materializa ante ti!",
    "dungeon.ghost_bet_prompt": "Tu apuesta (o 0 para declinar): ",
    "dungeon.ghost_cackles": "El fantasma cacarea mientras tu oro desaparece!",
    "dungeon.ghost_coward": "El fantasma se desvanece.",
    "dungeon.ghost_dice": "El fantasma saca un par de dados etereos.",
    "dungeon.ghost_fades": "El fantasma se desvanece.",
    "dungeon.ghost_fades_disappointed": "El fantasma se desvanece decepcionado.",
    "dungeon.ghost_fades_shadows": "El fantasma se desvanece entre las sombras...",
    "dungeon.ghost_greeting": "Una figura espectral se materializa ante ti!",
    "dungeon.ghost_header": "=== FANTASMA APOSTADOR ===",
    "dungeon.ghost_no_gold": "El fantasma se desvanece decepcionado.",
    "dungeon.ghost_pays": "El fantasma te paga a reganadientes {0} oro!",
    "dungeon.ghost_place_bet": "Tu apuesta (o 0 para declinar): ",
    "dungeon.ghost_player_roll": "Tu tiras: {0}",
    "dungeon.ghost_roll_result": "El fantasma saca: {0}",
    "dungeon.ghost_rolls": "El fantasma tira los dados...",
    "dungeon.ghost_tie": "EMPATE!",
    "dungeon.ghost_tie_msg": "EMPATE!",
    "dungeon.ghost_you_bet": "Apuestas {0} oro!",
    "dungeon.ghost_you_lose": "PIERDES!",
    "dungeon.ghost_you_win": "GANAS!",
    "dungeon.ghost_your_turn": "Tu turno de tirar...",
    "dungeon.god_alliance": "El Dios Antiguo ve algo en ti. Un entendimiento.",
    "dungeon.god_awaits_rescue": "  {0} espera ser rescatado. Busca el artefacto en pisos mas profundos.",
    "dungeon.god_awaits_return": "  {0} espera tu regreso. Tienes el artefacto.",
    "dungeon.god_corruption_lifts": "La corrupcion del Dios Antiguo se disipa. Recuerdan quienes eran.",
    "dungeon.god_fallen": "El Dios Antiguo ha caido. Su poder fluye hacia ti.",
    "dungeon.god_fled_retreat": "Te retiras de la presencia divina.",
    "dungeon.god_fled_wait": "El Dios Antiguo te observa partir. Pueden esperar.",
    "dungeon.god_floor_status": "  Piso {0}: {1} - {2}",
    "dungeon.god_intro_aurelion_1": "Una tenue luz parpadea en la oscuridad, luchando por persistir...",
    "dungeon.god_intro_aurelion_2": "AURELION, LA LUZ MENGUANTE, se manifiesta debilmente!",
    "dungeon.god_intro_aurelion_3": "El Dios de la Luz habla debilmente:",
    "dungeon.god_intro_maelketh_1": "El aire se carga con el aroma de antiguos campos de batalla...",
    "dungeon.god_intro_maelketh_2": "MAELKETH, LA ESPADA ROTA, se alza ante ti!",
    "dungeon.god_intro_maelketh_3": "El Dios de la Guerra habla:",
    "dungeon.god_intro_manwe_1": "La realidad misma tiembla. El sueno sabe que esta siendo observado...",
    "dungeon.god_intro_manwe_2": "MANWE, EL CREADOR DE TODO, se manifiesta!",
    "dungeon.god_intro_manwe_3": "El Creador habla con una voz que es todas las voces:",
    "dungeon.god_intro_noctura_1": "Las sombras se fusionan, formando figuras que observan...",
    "dungeon.god_intro_noctura_2": "NOCTURA, LA REINA DE LAS SOMBRAS, emerge de la oscuridad!",
    "dungeon.god_intro_noctura_3": "La Diosa de las Sombras susurra:",
    "dungeon.god_intro_terravok_1": "La montana misma parece respirar. La piedra se mueve como carne...",
    "dungeon.god_intro_terravok_2": "TERRAVOK, EL ROMPE MUNDOS, despierta!",
    "dungeon.god_intro_terravok_3": "El Dios de la Tierra retumba:",
    "dungeon.god_intro_thorgrim_1": "El peso del juicio presiona tu alma...",
    "dungeon.god_intro_thorgrim_2": "THORGRIM, EL JUEZ INJUSTO, desciende!",
    "dungeon.god_intro_thorgrim_3": "El Dios de la Ley pronuncia:",
    "dungeon.god_intro_veloura_1": "El aroma de rosas marchitas llena el aire...",
    "dungeon.god_intro_veloura_2": "VELOURA, EL CORAZON MARCHITO, aparece ante ti!",
    "dungeon.god_intro_veloura_3": "La Diosa del Amor llora:",
    "dungeon.god_name_aurelion": "Aurelion, Dios de la Luz",
    "dungeon.god_name_maelketh": "Maelketh, Dios del Caos",
    "dungeon.god_name_manwe": "Manwe, el Creador",
    "dungeon.god_name_noctura": "Noctura, Diosa de la Sombra",
    "dungeon.god_name_terravok": "Terravok, Dios de la Tierra",
    "dungeon.god_name_thorgrim": "Thorgrim, Dios de la Ley",
    "dungeon.god_name_veloura": "Veloura, Diosa del Amor",
    "dungeon.god_retreat_default": "El dios se retira... por ahora.",
    "dungeon.god_retreat_maelketh": "Sientes al dios retirarse de vuelta al letargo... por ahora.",
    "dungeon.god_retreat_manwe": "La presencia del Creador se desvanece, pero sientes su mirada sobre ti...",
    "dungeon.god_retreat_terravok": "La montana se asienta. Terravok sigue durmiendo.",
    "dungeon.god_retreats": "Sientes al dios retirarse de vuelta al letargo... por ahora.",
    "dungeon.god_slayer_buff": "  Poder divino surge a traves de ti! (+20% dano, +10% defensa por {0} combates)",
    "dungeon.god_spared_hope": "Los ojos del Dios Antiguo se abren con algo olvidado hace mucho - esperanza.",
    "dungeon.god_spared_lingers": "Se desvanecen de este lugar, pero su presencia perdura en tu corazon.",
    "dungeon.god_status_allied": "Aliado",
    "dungeon.god_status_awakened": "Despierto",
    "dungeon.god_status_consumed": "Consumido",
    "dungeon.god_status_corrupted": "Corrompido",
    "dungeon.god_status_defeated": "Derrotado",
    "dungeon.god_status_dormant": "Durmiente",
    "dungeon.god_status_dying": "Muriendo",
    "dungeon.god_status_hostile": "Hostil",
    "dungeon.god_status_imprisoned": "Aprisionado",
    "dungeon.god_status_neutral": "Neutral",
    "dungeon.god_status_saved": "Salvado",
    "dungeon.god_status_unknown": "Desconocido",
    "dungeon.god_title_aurelion": "Aurelion, la Luz Menguante",
    "dungeon.god_title_default": "el Dios Antiguo",
    "dungeon.god_title_maelketh": "Maelketh, la Espada Rota",
    "dungeon.god_title_manwe": "Manwe, el Creador",
    "dungeon.god_title_noctura": "Noctura, la Reina de las Sombras",
    "dungeon.god_title_terravok": "Terravok, el Rompe Mundos",
    "dungeon.god_title_thorgrim": "Thorgrim, el Juez Injusto",
    "dungeon.god_title_veloura": "Veloura, el Corazon Marchito",
    "dungeon.god_unknown_stirs": "  ???: Algo se agita en las profundidades...",
    "dungeon.gold_gained": "Oro ganado: {0}",
    "dungeon.ground_trembles": "La tierra tiembla. Una presencia antigua se agita...",
    "dungeon.group_leader_not_entered": "  Tu lider de grupo aun no ha entrado a la mazmorra.",
    "dungeon.guide_aurelion": "JEFE: Aurelion, Dios de la Luz aguarda!",
    "dungeon.guide_maelketh": "JEFE: Maelketh, Dios de la Guerra aguarda!",
    "dungeon.guide_manwe": "FINAL: Manwe aguarda. Tus elecciones determinan el final.",
    "dungeon.guide_noctura": "JEFE: Noctura, Diosa de la Sombra aguarda!",
    "dungeon.guide_seal_2": "SABER: El Segundo Sello aguarda aqui",
    "dungeon.guide_seal_3": "SABER: El Tercer Sello aguarda aqui",
    "dungeon.guide_seal_4": "SABER: El Cuarto Sello aguarda aqui",
    "dungeon.guide_seal_5": "SABER: El Quinto Sello aguarda aqui",
    "dungeon.guide_seal_6": "SABER: El Sexto Sello aguarda aqui",
    "dungeon.guide_seal_final": "SABER: El Sello Final aguarda aqui",
    "dungeon.guide_terravok": "JEFE: Terravok, Dios de la Tierra duerme aqui!",
    "dungeon.guide_thorgrim": "JEFE: Thorgrim, Dios de la Ley aguarda!",
    "dungeon.guide_veloura": "JEFE: Veloura, Diosa del Deseo aguarda!",
    "dungeon.hint_ancient_power": "CONSEJO: Poder antiguo espera a los que se atreven a descender mas...",
    "dungeon.hint_aurelion": "JEFE: Aurelion, Dios de la Luz, irradia desde este piso!",
    "dungeon.hint_destroy_darkness": "EVENTO: La paradoja Destruir Oscuridad espera a quienes tengan la Espada Forjada al Sol.",
    "dungeon.hint_loom_discovery": "EVENTO: El Telar del Tejedor de Almas espera ser descubierto en esta camara.",
    "dungeon.hint_maelketh": "JEFE: Maelketh, Dios de la Guerra, aguarda en las profundidades de este piso!",
    "dungeon.hint_manwe": "FINAL: Manwe aguarda. Tus elecciones determinaran el final.",
    "dungeon.hint_memory": "MEMORIA: Tu pasado olvidado saldra a la superficie aqui. Presta atencion a los suenos.",
    "dungeon.hint_noctura": "JEFE: Noctura, Diosa de la Sombra, acecha en la oscuridad de este piso!",
    "dungeon.hint_paradox_child": "EVENTO: La paradoja del Nino Poseido puede aparecer aqui. Elige sabiamente.",
    "dungeon.hint_seal_2": "SABER: El Segundo Sello espera - cuenta la primera guerra entre dioses.",
    "dungeon.hint_seal_3": "SABER: El Tercer Sello revela como Manwe corrompio a sus propios hijos.",
    "dungeon.hint_seal_4": "SABER: El Cuarto Sello habla de las cadenas eternas que atan a los dioses.",
    "dungeon.hint_seal_5": "SABER: El Quinto Sello contiene una profecia sobre tu llegada.",
    "dungeon.hint_seal_6": "SABER: El Sexto Sello muestra el arrepentimiento de Manwe - sus lagrimas cristalizadas.",
    "dungeon.hint_seal_final": "SABER: El Sello Final espera - la verdad de la Filosofia del Oceano.",
    "dungeon.hint_something_stirs": "CONSEJO: Algo poderoso se agita en las profundidades...",
    "dungeon.hint_soulweaver_price": "EVENTO: El Precio del Tejedor de Almas - una decision moral espera.",
    "dungeon.hint_terravok": "JEFE: Terravok, Dios de la Tierra, duerme aqui. Lo despertaras?",
    "dungeon.hint_thorgrim": "JEFE: Thorgrim, Dios de la Ley, tiene su corte en este piso!",
    "dungeon.hint_veloura": "JEFE: Veloura, Diosa del Deseo, te llama desde este piso!",
    "dungeon.how_respond": "  Como respondes?",
    "dungeon.invalid_choice": "Opcion invalida.",
    "dungeon.level_set_to": "Nivel de mazmorra establecido en {0}.",
    "dungeon.level_up_hint": "Sube de nivel para acceder a pisos mas profundos.",
    "dungeon.lore_all_seals": "- TODOS LOS SELLOS RECOLECTADOS - El final verdadero ahora es posible!",
    "dungeon.lore_corruption": "- Manwe corrompio a sus propios hijos - los Dioses Antiguos - para detener su guerra",
    "dungeon.lore_imprisonment": "- Los dioses han estado aprisionados diez mil anos, enloqueciendo lentamente",
    "dungeon.lore_none_1": "  Aun no has descubierto las verdades mas profundas...",
    "dungeon.lore_none_2": "  Explora las mazmorras. Encuentra los Sellos. Recuerda quien eres.",
    "dungeon.lore_ocean": "- La 'Filosofia del Oceano': No eres una ola luchando contra el oceano - ERES el oceano",
    "dungeon.lore_prophecy": "- La profecia habla de 'uno de mas alla del velo' que decidira el destino de los dioses",
    "dungeon.lore_seals": "- Siete Sellos contienen la historia de los Dioses Antiguos",
    "dungeon.lore_wave": "- Una voz te llama 'ola' - como si fueras parte de algo mas grande",
    "dungeon.may_ascend": "Aun puedes ascender para prepararte.",
    "dungeon.may_still_ascend": "Aun puedes ascender para prepararte.",
    "dungeon.merc_level_class": " - Nivel {0} {1}",
    "dungeon.monster_appears": "Un [{0}]{1}[/] aparece!",
    "dungeon.monster_attacks": "Un {0} ataca!",
    "dungeon.monster_encounter_sr": "-- ENCUENTRO CON MONSTRUO --",
    "dungeon.monster_encounter_visual": "-- ENCUENTRO CON MONSTRUO --",
    "dungeon.monster_hint_1": "Sombras se mueven al borde de tu antorcha...",
    "dungeon.monster_hint_2": "Oyes sonidos hostiles desde la oscuridad...",
    "dungeon.monster_hint_3": "Algo te observa desde las sombras...",
    "dungeon.monster_hint_4": "El aire se siente cargado de amenaza...",
    "dungeon.move_passage": "Avanzas por el pasaje...",
    "dungeon.must_defeat_god_floor": "Debes derrotar a {0} en el piso {1} antes de descender mas.",
    "dungeon.must_defeat_old_god_this_floor": "Debes derrotar al Dios Antiguo en este piso antes de descender.",
    "dungeon.need_gold_fee": "Necesitas {0} oro pero solo tienes {1}!",
    "dungeon.new_creatures_emerged": "[Nuevas criaturas han surgido de las profundidades...]",
    "dungeon.no_companions": "  No has reclutado companeros aun.",
    "dungeon.no_level_change": "Sin cambio de nivel de mazmorra.",
    "dungeon.no_story_progress": "  No has progresado en ninguna historia del pueblo aun.",
    "dungeon.not_on_team": "  {0} ya no esta en tu equipo.",
    "dungeon.notes_teach_something": "Leer sus notas te ensena algo! (+{0} XP)",
    "dungeon.nowhere_descend": "No hay lugar mas profundo al que descender.",
    "dungeon.objective_deeper": "Desciende mas profundo. Los Sellos restantes esperan en el abismo.",
    "dungeon.objective_ending": "La historia termina donde empezo. Busca tu final.",
    "dungeon.objective_explore": "Explora las mazmorras y hazte mas fuerte. Algo espera en las profundidades...",
    "dungeon.objective_face_manwe": "Todos los Sellos recolectados. Enfrenta a Manwe, el Creador. Elige tu final.",
    "dungeon.objective_find_seals": "Encuentra los Sellos de los Dioses Antiguos ocultos en la mazmorra. Contienen la verdad.",
    "dungeon.objective_more_seals": "Continua recolectando Sellos. Cada uno revela mas de la historia divina.",
    "dungeon.obtained_artifact": "Obtuviste: {0}!",
    "dungeon.ocean_header": "EL SUSURRO DEL OCEANO (Despertar: {0}/7)",
    "dungeon.outcome_allied": "aliado con",
    "dungeon.outcome_faced": "enfrentado",
    "dungeon.outcome_mercy": "mostrado piedad a",
    "dungeon.outcome_saved": "salvado",
    "dungeon.outcome_slain": "derrotado",
    "dungeon.paid_allies_prepare": "Pagaste {0} oro. Tus aliados se preparan para la mazmorra.",
    "dungeon.paid_gold": "Pagaste {0} oro.",
    "dungeon.pay_affordable": "Pagar {0} oro por los aliados que puedes costear? (S/N): ",
    "dungeon.pay_all_allies": "Pagar {0} oro para traer a tus aliados? (S/N): ",
    "dungeon.portal_avoid": "Sabiamente evitas el portal inestable. Se desvanece.",
    "dungeon.portal_carries_upward": "El portal te lleva hacia arriba!",
    "dungeon.portal_description_1": "Un portal resplandeciente flota ante ti, crepitando con energia.",
    "dungeon.portal_description_2": "Pulsa con una luz de otro mundo.",
    "dungeon.portal_emerge_floor": "Emerges en el piso {0}!",
    "dungeon.portal_grab_gold": "Agarras {0} oro antes de ser arrastrado de vuelta!",
    "dungeon.portal_guardian_crystal": "El guardian deja caer un cristal raro!",
    "dungeon.portal_header": "=== PORTAL MISTERIOSO ===",
    "dungeon.portal_hostile_dimension": "El portal lleva a una dimension hostil!",
    "dungeon.portal_learn_magic": "Aprendes algo sobre magia dimensional. (+{0} XP)",
    "dungeon.portal_study": "Estudias los patrones magicos del portal...",
    "dungeon.portal_treasure_dimension": "Te encuentras en una dimension de tesoros!",
    "dungeon.portal_whisks_deeper": "El portal te arrastra mas profundo en la mazmorra!",
    "dungeon.pray_for_fallen": "Dices una oracion silenciosa por el aventurero caido.",
    "dungeon.presence_blocks": "Una presencia poderosa bloquea tu descenso.",
    "dungeon.presence_blocks_descent": "Una presencia poderosa bloquea tu descenso.",
    "dungeon.press_enter_continue": "  Presiona Enter para continuar...",
    "dungeon.promised_loom": "Has prometido encontrar el Telar del Tejedor de Almas y regresar.",
    "dungeon.prove_yourself_hint": "Quizas debas demostrar tu valor en otro lugar antes de que se revele.",
    "dungeon.proven_sacred_floor": "Has demostrado tu valor en este piso sagrado!",
    "dungeon.quest_started_loom": "  [MISION INICIADA] Encuentra el Telar del Tejedor de Almas y regresa para salvar a este dios.",
    "dungeon.rare_material_found": "    MATERIAL RARO ENCONTRADO!",
    "dungeon.react_aurelion_def_comp_1": "El coro del templo canta una elegia mientras la noticia se esparce.",
    "dungeon.react_aurelion_def_comp_2": "Pero la sacerdotisa principal te mira y asiente. Ella entiende.",
    "dungeon.react_aurelion_def_comp_3": " dice en voz baja.",
    "dungeon.react_aurelion_def_def_1": "El sacerdote cae de rodillas en la calle.",
    "dungeon.react_aurelion_def_def_3": "Nubes de tormenta se juntan. El pueblo nunca se sintio tan oscuro.",
    "dungeon.react_aurelion_other_1": "El sol de la tarde se siente mas calido de lo usual.",
    "dungeon.react_aurelion_other_2": "La gente se protege los ojos, entrecerrandolos, sintiendo algo cambio.",
    "dungeon.react_aurelion_sav_1": "Luz dorada atraviesa las nubes mientras emerges.",
    "dungeon.react_aurelion_sav_2": "La multitud cae de rodillas, con lagrimas cayendo.",
    "dungeon.react_aurelion_sav_3": " El grito resuena de tejado en tejado.",
    "dungeon.react_aurelion_sav_4": "Las campanas del templo suenan en un patron no escuchado en mil anos.",
    "dungeon.react_default_1": "El pueblo te observa emerger de la mazmorra en silencio.",
    "dungeon.react_default_2": "Algo ha cambiado. Todos lo sienten.",
    "dungeon.react_maelketh_def_agg_1": "La multitud se abre ante ti. Un veterano murmura.",
    "dungeon.react_maelketh_def_agg_3": "Los ninos son llevados adentro. Las ventanas se cierran.",
    "dungeon.react_maelketh_def_def_1": "La multitud mira incredula. El dios de la guerra ha caido.",
    "dungeon.react_maelketh_def_def_2": "Un herrero deja su martillo. \\",
    "dungeon.react_maelketh_def_hum_1": "Los ninos se asoman detras de sus madres mientras emerges.",
    "dungeon.react_maelketh_def_hum_3": "Un viejo soldado te saluda — el primer saludo real en anos.",
    "dungeon.react_maelketh_other_1": "La multitud te observa con cauteloso respeto.",
    "dungeon.react_maelketh_sav_1": "Un viejo soldado llora abiertamente en la calle.",
    "dungeon.react_maelketh_sav_3": "Alguien empieza un himno. Otros se unen, timidamente al principio, luego con conviccion.",
    "dungeon.react_noctura_ally_1": "La gente evita tu mirada mientras caminas por la plaza.",
    "dungeon.react_noctura_ally_2": "Las sombras que proyectas parecen... mas largas de lo que deberian.",
    "dungeon.react_noctura_ally_3": "El gremio de ladrones deja una sola pluma negra en tu puerta.",
    "dungeon.react_noctura_def_agg_1": "Faroles arden en cada ventana esta noche.",
    "dungeon.react_noctura_def_agg_2": " Pero la celebracion se siente vacia.",
    "dungeon.react_noctura_def_agg_3": "Algunos se preguntan en silencio: quien vigila la oscuridad ahora?",
    "dungeon.react_noctura_def_def_1": "Las lamparas de la calle parecen mas brillantes. Los callejones menos profundos.",
    "dungeon.react_noctura_def_def_2": " dice un sereno, aliviado.",
    "dungeon.react_noctura_other_1": "El pueblo esta mas tranquilo esta noche. Mas calmado.",
    "dungeon.react_noctura_other_2": "La oscuridad cae como siempre, pero se siente mas suave de alguna forma.",
    "dungeon.react_noctura_sav_1": "El gremio de ladrones levanta un brindis silencioso tras puertas cerradas.",
    "dungeon.react_noctura_sav_2": "Los mercaderes revisan sus cerraduras dos veces esta noche.",
    "dungeon.react_noctura_sav_3": "Pero las sombras se sienten... vigilantes. Protectoras, incluso.",
    "dungeon.react_terravok_def_def_1": "La tierra tiembla bajo tus pies al emerger.",
    "dungeon.react_terravok_def_def_2": "Los edificios crujen. El polvo cae de las vigas.",
    "dungeon.react_terravok_def_def_3": " alguien susurra. Nadie tiene respuesta.",
    "dungeon.react_terravok_def_resp_1": "Los canteros se inclinan al pasar. Conocen la piedra mejor que nadie.",
    "dungeon.react_terravok_other_1": "Los adoquines se sienten mas firmes bajo tus pies.",
    "dungeon.react_terravok_other_2": "Los mineros te saludan desde la plaza. Lo sienten en la piedra.",
    "dungeon.react_terravok_sav_1": "La tierra misma parece suspirar de alivio.",
    "dungeon.react_terravok_sav_2": "Las grietas en los muros del pueblo se sellan ante tus ojos.",
    "dungeon.react_terravok_sav_3": "El viejo pozo, seco por decadas, empieza a fluir de nuevo.",
    "dungeon.react_thorgrim_def_def_1": "La bandera del juzgado ondea a media asta.",
    "dungeon.react_thorgrim_def_def_2": "Abogados y jueces susurran nerviosos. La ley se siente menos cierta hoy.",
    "dungeon.react_thorgrim_def_defy_1": "El magistrado observa desde su ventana, palido.",
    "dungeon.react_thorgrim_def_defy_2": "Los guardias ajustan el agarre de sus lanzas al pasar.",
    "dungeon.react_thorgrim_def_hon_1": "El juez del pueblo se quita el sombrero al pasar.",
    "dungeon.react_thorgrim_other_1": "La guardia del pueblo se mantiene un poco mas erguida al pasar.",
    "dungeon.react_thorgrim_sav_1": "El pueblo se alinea en filas formales para inclinarse al entrar.",
    "dungeon.react_thorgrim_sav_3": "Un sentido de orden se asienta sobre el pueblo como una manta calida.",
    "dungeon.react_veloura_def_agg_1": "Una pareja se abraza fuertemente al pasar.",
    "dungeon.react_veloura_def_agg_3": "La vendedora de flores en la esquina recoge su puesto en silencio.",
    "dungeon.react_veloura_def_def_1": "El pueblo se siente mas frio de alguna forma, incluso bajo el sol.",
    "dungeon.react_veloura_def_def_2": "Un bardo se detiene a mitad de cancion, incapaz de recordar la letra de una balada de amor.",
    "dungeon.react_veloura_def_merc_1": "La multitud esta callada. Una mujer coloca una flor en la entrada de la mazmorra.",
    "dungeon.react_veloura_def_merc_2": " alguien dice. Nadie discute. Nadie esta de acuerdo.",
    "dungeon.react_veloura_other_1": "La gente parece mas calida entre si mientras caminas por el pueblo.",
    "dungeon.react_veloura_other_2": "Una joven pareja te mira e inclina la cabeza en agradecimiento.",
    "dungeon.react_veloura_sav_1": "Las campanas del templo resuenan por el pueblo.",
    "dungeon.react_veloura_sav_2": " alguien grita desde un tejado.",
    "dungeon.react_veloura_sav_3": "Extranos se abrazan en la calle. Viejos rencores parecen suavizarse.",
    "dungeon.recite_scroll_prompt": "Recitar el pergamino? (S/N): ",
    "dungeon.recover_hp": "Recuperas {0} puntos de vida.",
    "dungeon.recover_mana": "Recuperas {0} mana.",
    "dungeon.recover_stamina": "Recuperas {0} energia.",
    "dungeon.remaining_gold": "Oro restante: {0}",
    "dungeon.remember_veloura": "  Recuerdas tu promesa a Veloura en el piso 40.",
    "dungeon.respawned": "  [La magia oscura de la mazmorra ha atraido nuevas criaturas desde las profundidades...]",
    "dungeon.return_veloura_loom": "  Regresa con el Telar para completar el rescate.",
    "dungeon.room_boss_presence": ">> Una presencia poderosa domina esta sala! <<",
    "dungeon.room_cleared": "La sala esta despejada!",
    "dungeon.room_stairs_down": ">> Escaleras descienden a un nivel mas profundo <<",
    "dungeon.room_treasure_glints": ">> Algo valioso brilla en la oscuridad! <<",
    "dungeon.scroll_blessing_hint": "Y recibiras una bendicion.",
    "dungeon.scroll_blessing_words": "Pronuncia: 'XAVARANTHE JHUSULMAX VASWIUN'",
    "dungeon.scroll_chivalry_gain": "Tu caballerosidad aumenta en {0}!",
    "dungeon.scroll_divine_light": "Luz divina te rodea!",
    "dungeon.scroll_found": "Has encontrado un pergamino! Dice:",
    "dungeon.scroll_ground_trembles": "La tierra tiembla mientras un mal antiguo despierta!",
    "dungeon.scroll_hidden_passage": "Un pasaje oculto se abre ante ti!",
    "dungeon.scroll_secret_gold": "Descubres {0} oro en la camara secreta!",
    "dungeon.scroll_secret_hint": "Y se te daran oportunidades.",
    "dungeon.scroll_secret_words": "Pronuncia: 'RANTVANTHI SHGELUUIM VARTHMIOPLXH'",
    "dungeon.scroll_stored": "Guardas cuidadosamente el pergamino para despues.",
    "dungeon.scroll_summoned_undead": "Has invocado a un {0}!",
    "dungeon.scroll_undead_hint": "Y veras el poder antiguo resurgir.",
    "dungeon.scroll_undead_words": "Pronuncia: 'ZASHNIVANTHE ULIPMAN NO SEE'",
    "dungeon.scroll_words_resonate": "Las palabras antiguas resuenan con poder...",
    "dungeon.seal_already_collected": "[i] El sello de este piso ya fue recolectado.",
    "dungeon.seal_collected_sr": "  Recolectado: {0} - {1}",
    "dungeon.seal_hidden_dungeon": "Oculto en las profundidades de la mazmorra",
    "dungeon.seal_hidden_town": "Oculto en las profundidades de la mazmorra",
    "dungeon.seal_not_collected_sr": "  No recolectado: {0} - {1}",
    "dungeon.seal_on_floor": "[!] Este piso contiene un Sello de la Verdad. Explora con cuidado.",
    "dungeon.seal_rooms_available": "    Salas con sello disponibles: {0}",
    "dungeon.seals_header": "SELLOS DE LOS DIOSES ANTIGUOS ({0}/7)",
    "dungeon.shrine_angry_spirit": "Un espiritu furioso emerge del santuario en ruinas!",
    "dungeon.shrine_desecrate": "Destrozas el santuario y robas las ofrendas!",
    "dungeon.shrine_desecrate_gold": "Encuentras {0} oro entre las ofrendas!",
    "dungeon.shrine_discover": "Descubres un santuario antiguo brillando con una luz extrana.",
    "dungeon.shrine_divine_light": "Luz divina te llena!",
    "dungeon.shrine_drains": "El santuario drena tu fuerza vital!",
    "dungeon.shrine_fully_healed": "Estas completamente curado!",
    "dungeon.shrine_gold_dissolves": "Tu oro se disuelve en el altar!",
    "dungeon.shrine_header_sr": "-- SANTUARIO MISTERIOSO --",
    "dungeon.shrine_header_visual": "-- SANTUARIO MISTERIOSO --",
    "dungeon.shrine_kneel": "Te arrodillas ante el santuario antiguo...",
    "dungeon.shrine_leave": "Sabiamente dejas el misterioso santuario en paz.",
    "dungeon.shrine_lose_gold": "Pierdes {0} oro!",
    "dungeon.shrine_lose_hp": "Pierdes {0} PV!",
    "dungeon.shrine_nothing": "Nada sucede.",
    "dungeon.shrine_offerings": "Ofrendas de oro y huesos rodean un altar de piedra.",
    "dungeon.shrine_silent": "El santuario esta en silencio...",
    "dungeon.shrine_stronger": "Te sientes mas fuerte! +{0} Fuerza!",
    "dungeon.shrine_wisdom": "Sabiduria antigua fluye hacia ti! +{0} EXP!",
    "dungeon.sr_subtitle": "  Abandonad toda esperanza los que entreis aqui",
    "dungeon.sr_title": "  LAS MAZMORRAS",
    "dungeon.status_boss_cleared": "Sala del jefe, despejada",
    "dungeon.status_boss_uncleared": "Sala del jefe, sin despejar",
    "dungeon.status_cleared": "Despejado",
    "dungeon.status_explored": "Explorado",
    "dungeon.status_monsters": "Monstruos presentes",
    "dungeon.status_safe": "Sala segura",
    "dungeon.status_stairs": "Escaleras abajo, despejado",
    "dungeon.status_stairs_cleared": "Escaleras abajo, despejado",
    "dungeon.staying_behind": "Se quedan atras:",
    "dungeon.stays_behind": "  {0} se queda atras.",
    "dungeon.step_all_seals": "- Recolecta los 7 Sellos para desbloquear el final verdadero",
    "dungeon.step_descend": "- Desciende mas profundo. Poderes antiguos esperan en el abismo.",
    "dungeon.step_grow": "- Hazte mas fuerte para adentrarte mas en la mazmorra",
    "dungeon.step_level": "- Sigue subiendo de nivel para acceder a pisos mas profundos",
    "dungeon.step_ready": "- Estas listo. Enfrenta al Creador en las profundidades mas oscuras.",
    "dungeon.step_seal_dungeon": "- Busca el {0} en las profundidades de la mazmorra",
    "dungeon.step_seal_town": "- Encuentra el {0} (oculto en algun lugar del pueblo)",
    "dungeon.step_stranger": "- Busca a 'El Extrano' - un NPC misterioso que sabe mas de lo que aparenta",
    "dungeon.story_battlefield_1": "Las piedras aqui estan manchadas con algo antiguo.",
    "dungeon.story_battlefield_2": "No es oxido. No es sangre mortal. Algo... dorado.",
    "dungeon.story_battlefield_3": "Armas de diseno imposible yacen por el suelo.",
    "dungeon.story_battlefield_4": "Demasiado grandes para manos humanas. Demasiado pesadas para brazos mortales.",
    "dungeon.story_battlefield_5": "Algo terrible sucedio aqui, mucho antes de que la historia comenzara.",
    "dungeon.story_battlefield_6": "Un SELLO DE LA VERDAD yace oculto en este piso.",
    "dungeon.story_battlefield_7": "Busca un santuario, biblioteca o camara sagrada para encontrarlo.",
    "dungeon.story_battlefield_title": "Campo de Batalla Antiguo",
    "dungeon.story_complete": "  [OK] {0} - Historia Completa",
    "dungeon.story_complete_sr": "  Completa: {0} - Historia Completa",
    "dungeon.story_depths_1": "Al descender al nivel 10, el aire se vuelve mas pesado.",
    "dungeon.story_depths_2": "Los muros aqui son mas antiguos, tallados por manos anteriores a la memoria.",
    "dungeon.story_depths_3": "Notas extranos simbolos repetidos - siete circulos entrelazados.",
    "dungeon.story_depths_4": "Un patron que tira de algo profundo dentro de ti...",
    "dungeon.story_depths_5": "En algun lugar adelante, las respuestas esperan.",
    "dungeon.story_depths_title": "Las Profundidades Comienzan",
    "dungeon.story_echoes_1": "Te ves a ti mismo en los muros.",
    "dungeon.story_echoes_2": "No un reflejo - un recuerdo.",
    "dungeon.story_echoes_3": "Has estado aqui antes.",
    "dungeon.story_echoes_4": "Mil veces. Un millon.",
    "dungeon.story_echoes_5": "El ciclo se repite.",
    "dungeon.story_echoes_6": "Manwe envia un fragmento de si mismo para experimentar la mortalidad.",
    "dungeon.story_echoes_7": "Para aprender. Para crecer. Para recordar lo que significa ser pequeno.",
    "dungeon.story_echoes_8": "Y al final, el fragmento regresa...",
    "dungeon.story_echoes_9": "A menos que esta vez, no lo haga.",
    "dungeon.story_echoes_title": "Camara de los Ecos",
    "dungeon.story_end_1": "Esto es todo.",
    "dungeon.story_end_10": "O, si recolectaste los Siete Sellos...",
    "dungeon.story_end_11": "Quizas algo mas es posible.",
    "dungeon.story_end_12": "Elige sabiamente. Esta es la unica eleccion que importa.",
    "dungeon.story_end_2": "Mas alla de este umbral, Manwe suena.",
    "dungeon.story_end_3": "El Creador que hizo todo.",
    "dungeon.story_end_4": "El dios que rompio a sus propios hijos.",
    "dungeon.story_end_5": "El oceano que olvido que era agua.",
    "dungeon.story_end_6": "Tienes tres opciones:",
    "dungeon.story_end_7": "  - DESTRUIRLO y tomar su poder (Usurpador)",
    "dungeon.story_end_8": "  - SALVARLO y restaurar a los dioses (Salvador)",
    "dungeon.story_end_9": "  - DESAFIARLO y forjar tu propio camino (Desafiante)",
    "dungeon.story_end_title": "El Fin de Todas las Cosas",
    "dungeon.story_failed": "  [X] {0} - Historia Fallida",
    "dungeon.story_failed_sr": "  No iniciada: {0} - Historia Fallida",
    "dungeon.story_in_progress": "  [~] {0} - Capitulo {1}/{2}",
    "dungeon.story_in_progress_sr": "  En progreso: {0} - Capitulo {1}/{2}",
    "dungeon.story_mourning_1": "Los muros aqui estan hechos de cristal.",
    "dungeon.story_mourning_2": "Gris azulado. Frio. Y humedo.",
    "dungeon.story_mourning_3": "No es agua. Algo mas espeso. Mas salado.",
    "dungeon.story_mourning_4": "Como si estos cristales se formaran de lagrimas.",
    "dungeon.story_mourning_5": "Oceanos de lagrimas, derramadas durante milenios.",
    "dungeon.story_mourning_6": "Congeladas en piedra. Un monumento a la tristeza.",
    "dungeon.story_mourning_7": "De quien es el dolor que podria llenar una montana?",
    "dungeon.story_mourning_8": "El SELLO DE LA VERDAD en este piso tiene la respuesta.",
    "dungeon.story_mourning_title": "Camara del Luto",
    "dungeon.story_oracle_1": "Un esqueleto se sienta sobre un trono de huesos.",
    "dungeon.story_oracle_2": "En la muerte, aun agarra un orbe de cristal.",
    "dungeon.story_oracle_3": "La Oraculo. La ultima mortal en hablar con los dioses.",
    "dungeon.story_oracle_4": "Ella vio el futuro antes de morir.",
    "dungeon.story_oracle_5": "Y lo que vio la hizo llorar.",
    "dungeon.story_oracle_6": "Palabras estan talladas en la piedra a sus pies:",
    "dungeon.story_oracle_8": "Un SELLO DE LA VERDAD espera. Contiene su profecia final.",
    "dungeon.story_oracle_title": "Tumba del Oraculo",
    "dungeon.story_prison_1": "Celdas vacias se extienden en la oscuridad.",
    "dungeon.story_prison_2": "No celdas para mortales - son enormes. Del tamano de catedrales.",
    "dungeon.story_prison_3": "Los barrotes estan hechos de algo que no es metal.",
    "dungeon.story_prison_4": "Algo que zumba con poder incluso ahora.",
    "dungeon.story_prison_5": "Lo que se guardaba aqui era inmenso. Y furioso.",
    "dungeon.story_prison_6": "Marcas de garras cicatrizan los muros, mas profundas de lo que cualquier espada podria cortar.",
    "dungeon.story_prison_7": "Un SELLO DE LA VERDAD tiene la respuesta de quien fue aprisionado aqui.",
    "dungeon.story_prison_title": "Prision de las Eras",
    "dungeon.story_purging_1": "Aurelion se alza ante ti, radiante con luz divina.",
    "dungeon.story_purging_2": "La Espada Forjada al Sol arde brillante en tus manos.",
    "dungeon.story_purging_3": "'Has ganado este momento,' habla el Dios de la Luz.",
    "dungeon.story_purging_4": "Te ofrezco el poder de acabar con toda oscuridad para siempre.",
    "dungeon.story_purging_title": "La Luz Purificadora",
    "dungeon.story_shrine_1": "Siete estatuas forman un circulo, rostros desgastados por el tiempo.",
    "dungeon.story_shrine_2": "Pero algo esta mal con ellas.",
    "dungeon.story_shrine_3": "La piedra misma parece... enferma. Retorcida.",
    "dungeon.story_shrine_4": "Como si las esculturas fueron cambiadas despues de ser creadas.",
    "dungeon.story_shrine_5": "Formas hermosas deformadas en algo grotesco.",
    "dungeon.story_shrine_6": "Que fuerza podria corromper la piedra misma?",
    "dungeon.story_shrine_7": "Un SELLO DE LA VERDAD espera a quienes buscan respuestas aqui.",
    "dungeon.story_shrine_title": "Santuario Corrompido",
    "dungeon.story_soulweaver_1": "En lo profundo de esta camara olvidada, algo antiguo te llama...",
    "dungeon.story_soulweaver_2": "Un dispositivo de delicadeza imposible descansa sobre un pedestal de piedra.",
    "dungeon.story_soulweaver_3": "Hilos de luz flotan de el como tela de arana en la brisa.",
    "dungeon.story_soulweaver_4": "Este es el Telar del Tejedor de Almas - el artefacto que puede deshacer la corrupcion divina.",
    "dungeon.story_soulweaver_5": "Justo lo que prometiste encontrar.",
    "dungeon.story_soulweaver_price_1": "El Telar del Tejedor de Almas pulsa con poder en tus manos.",
    "dungeon.story_soulweaver_price_2": "Y ante ti se encuentra alguien que nunca esperaste volver a ver...",
    "dungeon.story_soulweaver_price_title": "El Precio del Tejedor de Almas",
    "dungeon.story_soulweaver_title": "La Camara del Tejedor de Almas",
    "dungeon.story_threshold_1": "Estas al borde de la comprension.",
    "dungeon.story_threshold_2": "Un piso arriba, Manwe espera.",
    "dungeon.story_threshold_3": "El Creador. Tu creador.",
    "dungeon.story_threshold_4": "O quizas... tu mismo?",
    "dungeon.story_threshold_5": "Eres la ola que recordo que era el oceano.",
    "dungeon.story_threshold_6": "Y ahora el oceano debe responder por lo que ha hecho.",
    "dungeon.story_threshold_7": "Recolecta el sello final si no lo has hecho.",
    "dungeon.story_threshold_8": "Luego enfrenta la verdad.",
    "dungeon.story_threshold_title": "El Umbral",
    "dungeon.story_whispers_1": "Lo escuchas ahora - una voz al borde de la percepcion.",
    "dungeon.story_whispers_2": "No te habla. Habla COMO tu.",
    "dungeon.story_whispers_5": "La voz conoce tu verdadero nombre.",
    "dungeon.story_whispers_6": "El nombre que has olvidado.",
    "dungeon.story_whispers_title": "Los Susurros Comienzan",
    "dungeon.straggler_appears": "Un rezagado de los pisos superiores aparece a la vista...",
    "dungeon.strangers_attack_anyway": "Atacan de todas formas!",
    "dungeon.strangers_demand_gold": "Su lider exige tu oro!",
    "dungeon.strangers_draw_weapon": "Desenvaines tu arma y te preparas para la batalla!",
    "dungeon.strangers_dwarves": "enanos",
    "dungeon.strangers_dwarves_arms": "Llevan espadas y hachas.",
    "dungeon.strangers_dwarves_desc": "Un grupo de enanos armados se acerca!",
    "dungeon.strangers_escape_fail": "Te atrapan intentando escapar!",
    "dungeon.strangers_escape_success": "Logras escabullirte entre las sombras!",
    "dungeon.strangers_header": "=== EXTRANOS SE ACERCAN ===",
    "dungeon.strangers_leave_peace": "Los {0} te dejan en paz.",
    "dungeon.strangers_orcs": "orcos",
    "dungeon.strangers_orcs_arms": "Estan pobremente armados con palos y garrotes.",
    "dungeon.strangers_orcs_desc": "Un grupo de orcos emerge de las sombras!",
    "dungeon.strangers_pay_bribe": "Entregas a reganadientes {0} oro.",
    "dungeon.strangers_rogues": "picaros",
    "dungeon.strangers_rogues_arms": "Blanden cuchillos y estoques.",
    "dungeon.strangers_rogues_desc": "Una pandilla de picaros te rodea!",
    "dungeon.strangers_steal_gold": "Te golpean y roban {0} oro!",
    "dungeon.strangers_trolls": "trolls",
    "dungeon.strangers_trolls_arms": "Llevan garrotes y lanzas.",
    "dungeon.strangers_trolls_desc": "Una banda de trolls bloquea tu camino!",
    "dungeon.tag_boss": " [JEFE]",
    "dungeon.tag_cleared": "[DESPEJADO]",
    "dungeon.tag_danger": "[DESPEJADO]",
    "dungeon.theme_abyssal": "La realidad misma se deforma en estas profundidades malditas",
    "dungeon.theme_catacombs": "Antiguas camaras funerarias llenas de muertos inquietos",
    "dungeon.theme_caverns": "Cuevas naturales talladas por rios subterraneos",
    "dungeon.theme_demon": "Corredores infernales apestando a azufre",
    "dungeon.theme_display": "Tema: {0}",
    "dungeon.theme_frozen": "Salas cubiertas de hielo donde el frio mismo caza",
    "dungeon.theme_ruins": "Restos desmoronados de una civilizacion olvidada",
    "dungeon.theme_sewers": "Tuneles fetidos plagados de alimanas y peores cosas",
    "dungeon.theme_unknown": "Pasajes oscuros serpentean hacia lo desconocido",
    "dungeon.theme_volcanic": "Rios de lava y calor abrasador esperan",
    "dungeon.they_know": "  Saben lo que hiciste alla abajo. Tu {0} {1}.",
    "dungeon.threat_label": "  Amenaza: ",
    "dungeon.trap_acid": "Acido salpica tus pertenencias! Pierdes {0} oro!",
    "dungeon.trap_broken": "El mecanismo de la trampa esta roto. Nada sucede!",
    "dungeon.trap_broken_nothing": "Pero nada sucede... la trampa esta rota.",
    "dungeon.trap_curse_drain": "Una maldicion te drena! Pierdes {0} experiencia! (Resiste con Sabiduria/Constitucion)",
    "dungeon.trap_curse_resist": "Una maldicion oscura te envuelve, pero tu sabiduria protege tu mente! (Sabiduria: {0})",
    "dungeon.trap_dart_damage_poisoned": "Recibes {0} de dano y estas envenenado!",
    "dungeon.trap_darts": "Dardos envenenados! Recibes {0} de dano y estas envenenado!",
    "dungeon.trap_detect_assassin": ">> Tu ojo entrenado detecta un mecanismo de trampa! <<",
    "dungeon.trap_detect_general": ">> Percibes un peligro oculto... <<",
    "dungeon.trap_detect_ranger": ">> Tus instintos advierten de peligro oculto adelante! <<",
    "dungeon.trap_dodge_entirely": "Esquivas la trampa por completo! (Agilidad: {0})",
    "dungeon.trap_evade_agility": "Evitas la trampa agilmente! (Agilidad: {0})",
    "dungeon.trap_evade_reflexes": "Tus rapidos reflejos te salvan!",
    "dungeon.trap_fall_damage": "Caes en un pozo y recibes {0} de dano!",
    "dungeon.trap_find_gold": "Encuentras algo de oro oculto cerca del mecanismo.",
    "dungeon.trap_fire": "Una llamarada! Recibes {0} de dano por fuego!",
    "dungeon.trap_floor_gives_way": "El suelo cede bajo tus pies!",
    "dungeon.trap_header_sr": "AVISO: TRAMPA!",
    "dungeon.trap_header_visual": "AVISO: TRAMPA!",
    "dungeon.trap_magic_damage": "Recibes {0} de dano magico!",
    "dungeon.trap_net_falls": "Una red cae desde arriba, atrapandote!",
    "dungeon.trap_no_react": "No pudiste reaccionar a tiempo!",
    "dungeon.trap_pit": "El suelo cede! Caes en un pozo por {0} de dano!",
    "dungeon.trap_poison_darts": "Dardos envenenados salen de los muros!",
    "dungeon.trap_reflexes_save": "Tus rapidos reflejos te salvan!",
    "dungeon.trap_rune_explodes": "Una runa magica explota bajo tus pies!",
    "dungeon.trap_salvage": "Recuperas {0} oro de las partes de la trampa.",
    "dungeon.trap_struggle_free": "Te liberas con esfuerzo, pero pierdes tiempo...",
    "dungeon.trap_tripwire": "Activas un cable trampa!",
    "dungeon.treasure_chest_discover": "Descubres un cofre antiguo oculto entre las sombras!",
    "dungeon.treasure_chest_header": "* COFRE DEL TESORO *",
    "dungeon.treasure_exp_found": "Ganas {0} experiencia!",
    "dungeon.treasure_found_sr": "  TESORO ENCONTRADO!",
    "dungeon.treasure_gold_found": "Encuentras {0} monedas de oro!",
    "dungeon.treasure_party_finds": "El grupo encuentra {0} oro y {1} XP!",
    "dungeon.treasure_your_share": "Tu parte: {0} oro, {1} XP",
    "dungeon.troubled_rest": "Tu descanso es perturbado por recuerdos oscuros...",
    "dungeon.use_party_management": "Usa Gestion de Grupo para ajustar la composicion de tu grupo.",
    "dungeon.vanquished_all_foes": "Has vencido a todos los enemigos en este nivel!",
    "dungeon.veloura_senses": "Veloura percibe tu regreso - y lo que llevas.",
    "dungeon.veloura_warmth": "Sientes una calidez familiar al pisar este piso...",
    "dungeon.vision_fragment_settles": "  (Un fragmento de verdad se asienta en tu consciencia...)",
    "dungeon.vision_memory_stirs": "  (Algo se agita en tu memoria...)",
    "dungeon.visit_inn_hint": "  Visita la Posada para conocer aliados potenciales.",
    "dungeon.wait_for_leader": "  Espera a que tu lider entre primero, luego siguelo.",
    "dungeon.waits_at_entrance": "  {0} espera en la entrada.",
    "dungeon.wave_fragments": "  Fragmentos de Ola recolectados: {0}/{1}",
    "dungeon.whispers_echo": "Extranos susurros resuenan por los corredores...",
    "dungeon.word_spread": "  La noticia ya se ha esparcido.",
    "dungeon.wounded_bandage": "Intentas vendar sus heridas con tela...",
    "dungeon.wounded_begs": "Encuentras a un hombre herido apoyado contra el muro.",
    "dungeon.wounded_bleeding": "Sangra abundantemente y suplica ayuda.",
    "dungeon.wounded_dies": "Desafortunadamente, muere por sus heridas.",
    "dungeon.wounded_dies_cursing": "Muere maldiciendo tu nombre...",
    "dungeon.wounded_find": "Encuentras a un hombre herido apoyado contra el muro.",
    "dungeon.wounded_header_sr": "-- EXTRANO HERIDO --",
    "dungeon.wounded_header_visual": "-- EXTRANO HERIDO --",
    "dungeon.wounded_heal_potion": "Usas una pocion de curacion en el extrano herido.",
    "dungeon.wounded_helps": "Parece ayudar un poco.",
    "dungeon.wounded_leave_1": "Pasas por encima del moribundo y continuas.",
    "dungeon.wounded_leave_2": "Sus quejidos se desvanecen detras de ti...",
    "dungeon.wounded_recovers": "Se recupera lo suficiente para ponerse de pie.",
    "dungeon.wounded_reward": "Tu caballerosidad aumenta en {0}!",
    "dungeon.wounded_rob": "Registras las pertenencias del moribundo...",
    "dungeon.wounded_rob_gold": "Encuentras {0} oro en su bolsa.",
    "dungeon.xp_gained": "Experiencia ganada: {0}",
    "dungeon.xp_hint_bring_potions": "~{0} XP (trae pociones)",
    "dungeon.xp_hint_flee": "~{0} XP (huir recomendado!)",
    "dungeon.xp_hint_high_risk": "~{0} XP (alto riesgo)",
    "dungeon.xp_hint_not_worth": "~{0} XP (no vale tu tiempo)",
    "dungeon.you_encounter": "Te encuentras con ",
    "dungeon.you_enter_room": "Entras a: {0}",
    "dungeon.you_face_prefix": "Te enfrentas a ",
    "dungeon.you_notice": "Notas:",
    "dungeon.you_return_room": "Regresas a: {0}",
    "dungeon.your_level": "Tu nivel: {0}",
    "dungeon.your_response": "Tu respuesta: ",
}
