translations = {
    "base.trade_send_new": "]  Invia nuovo pacco  ",
    "base.trade_cancel_sent": "] Annulla pacco inviato",
    "base.trade_quit": "]  Esci",
    "base.trade_example": "  Esempio: Digita A1 per accettare il pacco #1, D1 per rifiutarlo",
    "base.trade_received_gold": "Ricevuto {0} oro!",
    "base.trade_accepted": "Pacco accettato!",
    "base.trade_declined": "Pacco rifiutato. Oggetti/oro restituiti al mittente.",
    "base.trade_cancelled": "Pacco annullato. Oro restituito.",
    "base.trade_too_many": "Hai troppi pacchi in uscita in sospeso (max 10).",
    "base.trade_send_to": "Invia a: ",
    "base.trade_player_not_found": "Giocatore '{0}' non trovato.",
    "base.trade_no_self": "Non puoi inviare pacchi a te stesso!",
    "base.trade_select_items": "Seleziona oggetti da inviare (fino a 5). Inserisci 0 per terminare.",
    "base.trade_your_inventory": "Il tuo inventario:",
    "base.trade_add_item": "Aggiungi oggetto # (0 per fermare): ",
    "base.trade_added": "Aggiunto {0}",
    "base.trade_gold_prompt": "Oro da inviare (hai {0}): ",
    "base.trade_empty": "Il pacco è vuoto - niente da inviare.",
    "base.trade_note": "Aggiungi una nota (opzionale): ",
    "base.bounty_empty": "  La bacheca delle taglie è vuota. Nessuna taglia attiva.",
    "base.bounty_place_menu": "] Metti Taglia    [",
    "base.bounty_my_menu": "] Le mie Taglie    [",
    "base.bounty_back_menu": "] Indietro",
    "base.bounty_choice": "\n  Scelta: ",
    "base.bounty_max": "\n  Hai già 3 taglie attive. Attendi che vengano riscosse.",
    "base.bounty_target_prompt": "\n  Nome del giocatore bersaglio: ",
    "base.bounty_no_self": "  Non puoi mettere una taglia su te stesso!",
    "base.bounty_not_found": "  Giocatore non trovato.",
    "base.bounty_not_enough": "  Non hai abbastanza oro!",
    "base.bounty_placed_header": "\n  === Taglie da te Piazzate ===",
    "base.bounty_none": "  Nessuna.",
    "base.bounty_on_you_header": "\n  === Taglie su di Te ===",
    "base.bounty_clean": "  Nessuna. Sei pulito!",
    "base.auction_hall_desc": "Una sala cavernosa di pietra levigata, fiancheggiata da vetrine e ",
    "base.auction_hall_desc2": "bancarelle di legno",
    "base.auction_hall_desc3": ". ",
    "base.auction_busy": "L'aria vibra di voci contrattanti e del tintinnio di borse di monete.",
    "base.auction_moderate": "Alcuni mercanti stanno dietro i loro banchi, richiamando i passanti.",
    "base.auction_quiet": "I banchi sono perlopiù vuoti oggi, la polvere si posa sui banconi.",
    "base.auction_grimjaw": "Grimjaw",
    "base.auction_grimjaw_desc": ", il banditore mezzo-orco, incombe dietro il registro. ",
    "base.auction_yawns": "Sbadiglia.",
    "base.auction_listings": "  Inserzioni: ",
    "base.auction_total_value": "   Valore totale: ",
    "base.auction_people": "  Persone qui: ",
    "base.auction_what_do": "Cosa vorresti fare?",
    "base.auction_browse": "sfoglia Inserzioni        ",
    "base.auction_sell": "endi Oggetto       ",
    "base.auction_my_listings": "e mie Inserzioni",
    "base.auction_return": "orna in Città         ",
    "base.auction_cancel_btn": "] Annulla",
    "base.auction_no_items": "\n  Nessun oggetto in vendita. Ricontrolla più tardi!",
    "base.auction_listings_header": "\nINSERZIONI ALL'ASTA",
    "base.auction_listings_header_box": "\n  ═══════════ INSERZIONI ALL'ASTA ═══════════",
    "base.auction_inspect": "\n  Inserisci # per ispezionare/comprare, o premi Invio per tornare indietro.",
    "base.auction_choice": "  Scelta: ",
    "base.auction_item_header": "\nDETTAGLI OGGETTO",
    "base.auction_item_header_box": "\n  ═══════════ DETTAGLI OGGETTO ═══════════",
    "base.auction_no_stats": "  Nessun bonus alle statistiche",
    "base.auction_req_good": "  Richiede allineamento Buono",
    "base.auction_req_evil": "  Richiede allineamento Malvagio",
    "base.auction_cursed": "  MALEDETTO",
    "base.auction_unavailable": "  (Dettagli oggetto non disponibili)",
    "base.auction_your_listing": "\n  Questa è una tua inserzione.",
    "base.auction_press_enter": "  Premi Invio per tornare indietro.",
    "base.auction_already_sold": "  Quell'oggetto è già stato venduto o è scaduto!",
    "base.auction_no_items_sell": "\n  Non hai oggetti da vendere!",
    "base.auction_max_listings": "\n  Hai già 5 inserzioni attive. Annullane una o attendi che scadano.",
    "base.auction_inv_header": "\nIL TUO INVENTARIO",
    "base.auction_inv_header_box": "\n  ═══════════ IL TUO INVENTARIO ═══════════",
    "base.auction_item_num": "\n  Oggetto # da vendere: ",
    "base.auction_asking_price": "  Prezzo richiesto (oro): ",
    "base.auction_invalid_price": "  Prezzo non valido.",
    "base.auction_duration": "\n  Seleziona la durata dell'inserzione:",
    "base.auction_duration_prompt": "\n  Durata (1-4): ",
    "base.auction_failed": "\n  Creazione inserzione fallita.",
    "base.auction_my_header": "\nLE MIE INSERZIONI",
    "base.auction_my_header_box": "\n  ═══════════ LE MIE INSERZIONI ═══════════",
    "base.auction_no_listings": "  Non hai inserzioni.",
    "base.auction_collect_gold": "] Raccogli tutto l'oro    ",
    "base.auction_collect_expired": "] Raccogli oggetti scaduti    ",
    "base.auction_cancel_collect": "] Annulla/raccogli inserzione    [Invio] Indietro",
    "base.auction_my_choice": "\n  Scelta: ",
    "base.auction_no_gold": "\n  Nessun oro da raccogliere.",
    "base.auction_no_expired": "\n  Nessun oggetto scaduto da raccogliere.",
    "base.auction_collect_failed": "  Raccolta oggetto fallita.",
    "base.auction_only_active": "  Puoi annullare solo inserzioni attive.",
    "base.auction_listing_cancelled": "  Inserzione annullata. Oggetto restituito all'inventario.",
    "base.using_2h_weapon": "(usa arma a 2 mani)",
    "base.totals_equipped": "  Totali ({0} oggetti equipaggiati):",
    "base.no_personality": "  Nessun profilo di personalità trovato!",
    "base.identity_header": "  === IDENTITÀ ===",
    "base.faction_header": "  === FAZIONE ===",
    "base.faction_label": "  Fazione:            ",
    "base.none_independent": "Nessuna (Indipendente)",
    "base.relationship_header": "  === STILE RELAZIONALE ===",
    "base.romance_header": "  === TRATTI ROMANTICI (0.0-1.0) ===",
    "base.polyamory_header": "  === VALUTAZIONE POLIAMORE ===",
    "base.open_polyamory": "  Aperto al poliamore: ",
    "base.very_likely": "MOLTO PROBABILE",
    "base.possible": "POSSIBILE",
    "base.unlikely": "IMPROBABILE",
    "base.polyamory_factors": "  Fattori chiave: Preferenza Relazione Aperta/Poliamorosa + Bassa Gelosia",
    "base.trade_send_prefix": "Inviare ",
    "base.trade_items_count": "{0} oggetto/i ",
    "base.trade_gold_amount": "+ {0} oro ",
    "base.trade_to_confirm": "a {0}? (S/N): ",
    "base.trade_package_sent": "Pacco inviato a {0}!",
    "base.bounty_amount_prompt": "  Importo della taglia (min {0}, hai {1}o): ",
    "base.bounty_min_amount": "  La taglia minima è {0} oro.",
    "base.bounty_placed": "\n  Taglia di {0} oro piazzata su {1}!",
    "base.bounty_total": "  {0} taglie attive per un totale di {1} oro!",
    "base.bounty_entry": "  {0} oro - pubblicata da {1}",
    "base.bounty_target_entry": "  {0} - {1} oro",
    "base.auction_slow_day": "\"Giornata morta. Vendi o mi fai solo perdere tempo?\"",
    "base.auction_few_things": "\"C'è qualcosa che vale la pena guardare. Consulta la bacheca.\"",
    "base.auction_plenty": "\"Merce in abbondanza oggi! Avanti, avanti!\"",
    "base.auction_and_others": " e altri {0}",
    "base.auction_talk": " Parla ({0})",
    "base.auction_type": "  Tipo: {0}    Valore: {1}o",
    "base.auction_req_level": "\n  Devi essere livello {0}+ per usare questo oggetto. (Sei livello {1})",
    "base.auction_need_more": "\n  Ti servono altri {0} oro per comprare questo.",
    "base.auction_buy_confirm": "\n  Comprare per {0} oro? (S/N): ",
    "base.auction_purchased": "\n  Acquistato {0} per {1} oro!",
    "base.auction_purchased_error": "\n  Oggetto acquistato ma impossibile aggiungere all'inventario. L'oro è stato detratto.",
    "base.auction_requires_level": "  Richiede Livello {0}+",
    "base.auction_requires_str": "  Richiede {0} Forza",
    "base.auction_fee_label": "  Commissione: ",
    "base.auction_fee_detail": "  ({0}% base + {1}% tassa)",
    "base.auction_need_fee": "\n  Ti servono {0} oro per la commissione. Hai {1}.",
    "base.auction_list_confirm": "\n  Inserire {0} per {1}o ({2}, commissione: {3}o)? (S/N): ",
    "base.auction_listed": "\n  {0} inserito per {1} oro! Commissione: {2}o. Scade tra {3}.",
    "base.auction_gold_awaiting": "\n  Oro in attesa di ritiro: {0}o ({1} oggetto/i{2})",
    "base.auction_expired_count": "  Oggetti scaduti da raccogliere: {0} oggetto/i{1}",
    "base.auction_sold_uncollected": "VENDUTO - RITIRA ORO",
    "base.auction_sold_collected": "VENDUTO - RITIRATO",
    "base.auction_expired_collect": "SCADUTO - RITIRA OGGETTO",
    "base.auction_expired_collected": "SCADUTO - RITIRATO",
    "base.auction_gold_collected": "\n  Ritirato {0} oro dalle vendite all'asta!",
    "base.auction_items_collected": "\n  Ritirati {0} oggetto/i scaduti nel tuo inventario.",
    "base.auction_collected_back": "  Ritirato {0} nel tuo inventario.",
    "combat.status_effects_label": "Effetti di Stato:",
    "combat.flee_label": "Fuga ",
    "combat.disarm_label": "Disarma ",
    "combat.hide_label": "Nascondi ",
    "combat.save_label": "Salva",
    "combat.enemies_label": "Nemici:",
    "combat.choose_cancel": "Scegli (0 per annullare): ",
    "combat.replace_yn": "Sostituire? (S/N): ",
    "combat.choose_target": "Scegli bersaglio: ",
    "combat.choose_aid": "Scegli metodo di aiuto: ",
    "combat.choose_spell": "Scegli incantesimo: ",
    "combat.target_label": "Bersaglio: ",
    "combat.enter_ability_num": "Inserisci numero abilità (0 per annullare): ",
    "combat.enter_spell_num": "Inserisci numero incantesimo (0 per annullare): ",
    "combat.which_potion": "Quale pozione?",
    "combat.target_all_yn": "Colpire tutti i mostri? (S/N): ",
    "combat.available_abilities": "Abilità Disponibili:",
    "combat.available_spells": "Incantesimi Disponibili:",
    "combat.select_healing_spell": "Seleziona incantesimo di cura:",
    "combat.select_heal_target": "Seleziona bersaglio da curare:",
    "combat.select_target": "Seleziona bersaglio:",
    "combat.team_xp_distribution": "Distribuzione PE del Gruppo:",
    "combat.equipment_salvaged": "Equipaggiamento recuperato:",
    "combat.invalid_target": "Bersaglio non valido!",
    "combat.invalid_choice": "Scelta non valida.",
    "combat.invalid_action": "Azione non valida, riprova",
    "combat.invalid_option": "Scegli un'opzione valida.",
    "combat.monster_already_dead": "Quel mostro è già morto!",
    "combat.no_spells_yet": "Non conosci ancora nessun incantesimo!",
    "combat.invalid_choice_excl": "Scelta non valida!",
    "combat.unknown_ability": "Abilità sconosciuta!",
    "combat.invalid_target_list": "Bersaglio non valido. Inserisci un numero dalla lista sopra.",
    "combat.mana_already_full": "Il tuo mana è già al massimo!",
    "combat.already_cast_spell": "Hai già lanciato un incantesimo in questo turno!",
    "combat.cant_cast_spell": "Non puoi lanciare questo incantesimo adesso!",
    "combat.invalid_spell_selection": "Selezione incantesimo non valida!",
    "combat.no_abilities_yet": "Non hai ancora appreso nessuna abilità!",
    "combat.cant_use_ability": "Non puoi usare quell'abilità adesso!",
    "combat.no_castable_spells": "Non conosci incantesimi che puoi lanciare!",
    "combat.spell_cancelled": "Incantesimo annullato.",
    "combat.quickbar_empty": "Quello slot della barra rapida è vuoto!",
    "combat.not_available_pvp": "Quell'azione non è disponibile nel combattimento PvP.",
    "combat.no_matching_ability": "Nessuna abilità corrispondente disponibile — uso attacco base.",
    "combat.sunforged_guides": "La Lama Forgiata dal Sole guida il tuo colpo con precisione!",
    "combat.sunforged_blazes": "La Lama Forgiata dal Sole arde di fuoco sacro!",
    "combat.backstab_no_effect": "La pugnalata alle spalle non ha effetto in questo combattimento!",
    "combat.monster_no_mercy": "Il mostro non mostra pietà!",
    "combat.monster_pity": "Il mostro ha pietà di te e ti lascia vivere!",
    "combat.monk_nods": "Il monaco annuisce e prosegue per la sua strada.",
    "combat.monk_bows": "Il monaco si inchina e se ne va.",
    "combat.auto_combat_pause": "Il combattimento si metterà in pausa se prendi il controllo manuale.",
    "combat.one_handed_where": "Questa è un'arma a una mano. Dove vuoi equipaggiarla?",
    "combat.both_rings_occupied": "Entrambi gli slot anello sono occupati. Quale anello vuoi sostituire?",
    "combat.alive_but_cost": "Sei vivo. Ma a quale prezzo?",
    "combat.more_challenges": "I sotterranei nascondono molte altre sfide...",
    "combat.darkness_claims": "L'oscurità ti reclama.",
    "combat.gods_heard_prayers": "Gli dèi hanno udito le tue preghiere!",
    "combat.temple_priests_chant": "I sacerdoti del tempio intonano parole sacre...",
    "combat.magic_pulls_soul": "La loro magia strappa la tua anima dal vuoto!",
    "combat.cold_presence": "Avverti una presenza gelida...",
    "combat.death_claims": "La morte ti reclama...",
    "combat.item_slips": "Un oggetto ti sfugge dalla presa mentre cadi!",
    "combat.berserker_rage": "I tuoi occhi si tingono di rosso dalla furia! Nessuna ritirata, nessuna pietà!",
    "combat.berserker_fight_death": "Combatterai fino alla morte — la tua o la loro!",
    "combat.berserker_subsides": "La furia sanguinaria si placa mentre il tuo nemico cade...",
    "combat.berserker_not_enough": "La tua furia da berserker non è stata sufficiente...",
    "combat.berserker_glorious": "Cadi in una battaglia gloriosa!",
    "combat.acid_ignores_armor": "L'acido ignora l'armatura!",
    "combat.critical_from_shadows": "Colpo critico dalle ombre!",
    "combat.vanish_puff_smoke": "Svanisci in una nube di fumo!",
    "combat.prepare_dodge": "Ti prepari a schivare il prossimo attacco!",
    "combat.melody_steels": "La melodia tempra la tua risolutezza! (+10 Attacco per 3 turni)",
    "combat.will_unbreakable": "La tua volontà diventa infrangibile! Gli effetti di stato non possono toccarti!",
    "combat.reckless_swing": "Colpo spericolato! Ti lasci scoperto!",
    "combat.divine_energy": "Energia divina irradia dalla tua arma!",
    "combat.strike_vital": "Colpisci un punto vitale!",
    "combat.melt_shadows": "Ti fondi con le ombre, quasi impossibile da colpire!",
    "combat.blend_surroundings": "Ti mimetizzi perfettamente con l'ambiente circostante!",
    "combat.holy_light": "La luce sacra ti avvolge!",
    "combat.vanish_completely": "Svanisci completamente! Il tuo prossimo attacco colpirà dalle ombre!",
    "combat.shadows_embrace": "Le ombre ti abbracciano. Il potere di Noctura scorre attraverso di te!",
    "combat.become_legend": "Diventi la leggenda! Canti di potere scorrono attraverso di te!",
    "combat.status_immunity_fades": "La tua immunità agli stati svanisce.",
    "combat.manage_escape": "Riesci a fuggire!",
    "combat.last_stand": "Ultima Resistenza! Combatti con forza disperata!",
    "combat.raise_guard": "Alzi la guardia, preparandoti a deviare i colpi in arrivo.",
    "combat.power_attack_no_effect": "L'Attacco Potente non ha effetto in questo combattimento!",
    "combat.precise_strike_no_effect": "Il Colpo Preciso non ha effetto in questo combattimento!",
    "combat.missile_misses": "Il tuo proiettile manca il bersaglio.",
    "combat.bloodthirsty_rage": "Ti lanci in una furia sanguinaria!",
    "combat.smite_no_effect": "Punizione Sacra non ha effetto in questo combattimento!",
    "combat.out_of_smites": "Hai esaurito le cariche di punizione sacra!",
    "combat.nothing_to_disarm": "Niente da disarmare!",
    "combat.disarm_failed": "Tentativo di disarmo fallito!",
    "combat.hide_shadows": "Ti fondi con le ombre, pronto a colpire!",
    "combat.hide_failed": "Non riesci a trovare copertura e resti esposto.",
    "combat.tame_respect": "Ti guarda con nuovo rispetto...",
    "combat.tame_fight_alongside": "Combatterà al tuo fianco per questa battaglia!",
    "combat.tame_too_strong": "La volontà della creatura è troppo forte...",
    "combat.contracted_plague": "Hai contratto la pestilenza!",
    "combat.precise_no_effect": "Il Colpo Preciso non ha effetto in questo combattimento!",
    "combat.nothing_disarm": "Niente da disarmare!",
    "combat.hide_shadows_strike": "Ti fondi con le ombre, pronto a colpire!",
    "combat.execution_double": "ESECUZIONE! Danno doppio al nemico ferito!",
    "combat.last_stand_attack": "ULTIMA RESISTENZA! La disperazione alimenta il tuo attacco!",
    "combat.smoke_obscures": "Una nube di fumo ti nasconde dagli attacchi!",
    "combat.berserker_rage_fury": "FURIA BERSERKER! Entri in un delirio di sangue!",
    "combat.war_god_fury": "LA FURIA DEL DIO DELLA GUERRA ARDE DENTRO DI TE!",
    "combat.bloodlust_heal": "SETE DI SANGUE! Ogni uccisione ti curerà!",
    "combat.unstoppable_afflictions": "INARRESTABILE! Scrolli di dosso ogni afflizione!",
    "combat.divine_shield_light": "Uno scudo divino di pura luce ti circonda!",
    "combat.brilliant_light": "Una luce abbagliante squarcia le tenebre!",
    "combat.available_spells_label": "Incantesimi disponibili:",
    "combat.first_battle_tip": "SUGGERIMENTO: La tua Prima Battaglia!",
    "base.send_to_prompt": "Invia a: ",
    "base.immortal_locked": "  Sei un essere di pura divinità. Il regno mortale non ha nulla per te.",
    "base.establishment_closed": "  Questo esercizio è stato CHIUSO per decreto reale!",
    "base.establishment_closed_by": "  Per ordine di {0} {1}, questo luogo è interdetto.",
    "base.also_here": "Anche qui",
    "base.deposed": "  Sei stato DEPOSTO! Non sei più il monarca!",
    "base.throne_belongs_to": "  Il trono ora appartiene a {0}.",
    "base.throne_vacant": "  Il trono è vacante.",
    "base.whisper_uneasy": "  Noti alcuni PNG scambiarsi sguardi inquieti al tuo arrivo.",
    "base.whisper_approving": "  Noti alcuni PNG annuire con approvazione al tuo passaggio.",
    "base.whisper_neutral": "  Noti alcuni PNG sussurrare tra loro al tuo ingresso.",
    "base.guard_messenger": "Un messaggero accorre con notizie terribili!",
    "base.guard_level": "Livello",
    "base.guard_challenging": "sta sfidando {0} {1} per il trono!",
    "base.guard_honor_bound": "Come Guardia Reale, sei vincolato dall'onore a difendere la corona!",
    "base.guard_rush_question": "Correrai al castello per aiutare nella difesa?",
    "base.guard_rush_prompt": "Correre a difendere il trono? (S/N): ",
    "base.guard_rush_castle": "Ti precipiti verso il castello, spada sguainata!",
    "base.guard_loyalty_unquestioned": "La tua lealtà alla corona non sarà messa in dubbio!",
    "base.guard_turn_away": "Volti le spalle al tuo dovere...",
    "base.guard_crown_remembers": "La corona ricorderà questo tradimento.",
    "base.guard_loyalty_dropped": "La tua lealtà è scesa al {0}%!",
    "base.guard_stripped": "*** Sei stato PRIVATO del tuo status di Guardia Reale! ***",
    "base.level_up": "  *** LIVELLO SU! Sei ora Livello {0}! ***",
    "base.training_points_hint": "  Hai guadagnato punti addestramento! Visita il Maestro di Livello per spenderli.",
    "base.system_message": "*** MESSAGGIO DI SISTEMA ***",
    "base.world_boss_rampaging": "  *** {0} sta seminando distruzione nel reame! Digita /boss per unirti alla battaglia! ***",
    "base.poison_damage_turns": "Il veleno scorre nelle tue vene! (-{0} PV, {1} turni rimasti)",
    "base.poison_damage": "Il veleno scorre nelle tue vene! (-{0} PV)",
    "base.poison_death": "Il veleno ti ha reclamato la vita!",
    "base.poison_cleared": "Il veleno ha finalmente lasciato il tuo organismo!",
    "base.shout_evil_glare": "ti lancia uno sguardo minaccioso",
    "base.shout_evil_curse": "mormora una maledizione sottovoce",
    "base.shout_evil_gold": "guarda la tua borsa d'oro con avidità",
    "base.shout_evil_spit": "sputa a terra al tuo passaggio",
    "base.shout_evil_dagger": "affila un pugnale osservandoti",
    "base.shout_evil_laugh": "ride freddamente",
    "base.shout_evil_sneer": "ghigna verso i deboli",
    "base.shout_good_nod": "annuisce con rispetto",
    "base.shout_good_wave": "saluta amichevolmente",
    "base.shout_good_news": "racconta le sue ultime avventure",
    "base.shout_good_rumor": "menziona una voce che ha sentito",
    "base.shout_good_sword": "pratica forme di spada con grazia",
    "base.shout_good_hum": "canticchia un motivetto allegro",
    "base.shout_good_smile": "sorride calorosamente",
    "base.shout_neutral_business": "si occupa dei propri affari",
    "base.shout_neutral_thought": "sembra perso nei pensieri",
    "base.shout_neutral_merchandise": "esamina della merce",
    "base.shout_neutral_chat": "chiacchiera con un mercante",
    "base.shout_neutral_stretch": "si stiracchia dopo un lungo viaggio",
    "base.shout_neutral_gold": "conta le proprie monete d'oro",
    "base.shout_neutral_yawn": "sbadiglia pigramente",
    "base.shout_class_flex": "flette i muscoli",
    "base.shout_class_polish": "lucida la propria arma",
    "base.shout_class_tome": "legge da un antico tomo",
    "base.shout_class_arcane": "mormora parole arcane",
    "base.shout_class_blessing": "offre una benedizione",
    "base.shout_class_pray": "prega in silenzio",
    "base.shout_class_shadows": "osserva dalle ombre",
    "base.shout_class_blade": "saggia il filo di una lama",
    "base.align_evil": "(Malvagio)",
    "base.align_good": "(Buono)",
    "base.align_neutral": "(Neutrale)",
    "base.rel_married": "Sposato",
    "base.rel_in_love": "Innamorato",
    "base.rel_passionate": "Appassionato",
    "base.rel_friends": "Amici",
    "base.rel_trusted": "Fidato",
    "base.rel_respected": "Rispettato",
    "base.rel_neutral": "Neutrale",
    "base.rel_wary": "Diffidente",
    "base.rel_hostile": "Ostile",
    "base.rel_enemy": "Nemico",
    "base.rel_hated": "Odiato",
    "base.you_notice": "Noti:",
    "base.others_going_about": "  ... e altri {0} che si occupano dei propri affari.",
    "base.activity_inn_drink": "sorseggia un drink al bancone",
    "base.activity_inn_chat": "chiacchiera con gli altri avventori",
    "base.activity_inn_corner": "siede da solo a un tavolo in un angolo",
    "base.activity_church_pray": "prega in silenzio",
    "base.activity_church_candle": "accende una candela all'altare",
    "base.activity_church_priest": "parla con uno dei sacerdoti",
    "base.activity_weapon_blade": "esamina una lama appesa alla parete",
    "base.activity_weapon_mace": "saggia il peso di una mazza",
    "base.activity_weapon_haggle": "contratta sui prezzi",
    "base.activity_armor_gauntlets": "prova un paio di guanti d'arme",
    "base.activity_armor_shield": "ispeziona uno scudo",
    "base.activity_armor_chainmail": "ammira una cotta di maglia",
    "base.activity_magic_scroll": "studia una pergamena con interesse",
    "base.activity_magic_crystal": "scruta in una sfera di cristallo",
    "base.activity_magic_potion": "annusa una pozione sospetta",
    "base.activity_auction_bid": "fa un'offerta a un'asta",
    "base.activity_auction_browse": "sfoglia le inserzioni dell'asta",
    "base.activity_auction_appraise": "valuta oggetti in vendita",
    "base.activity_healer_potions": "esamina le pozioni curative",
    "base.activity_healer_waiting": "attende di vedere il guaritore",
    "base.activity_street_stroll": "passeggia per la strada",
    "base.activity_street_lean": "è appoggiato a un muro, osservando i passanti",
    "base.activity_street_talk": "parla con un amico",
    "base.activity_street_business": "si occupa dei propri affari",
    "base.activity_alley_lurk": "si aggira tra le ombre",
    "base.activity_alley_whisper": "sussurra a una figura incappucciata",
    "base.activity_alley_watch": "tiene d'occhio il vicolo",
    "base.activity_castle_court": "si occupa degli affari di corte",
    "base.activity_castle_guard": "monta la guardia vicino alla sala del trono",
    "base.activity_castle_courtier": "parla con un cortigiano",
    "base.available_actions": "Azioni disponibili:",
    "base.exits": "Uscite:",
    "base.location_label": "Luogo: ",
    "base.bc_main_street": "Via Principale",
    "base.bc_home": "Via dell'Ancora > Casa Tua",
    "base.bc_anchor_road": "Via Principale > Via dell'Ancora",
    "base.bc_weapon_shop": "Via Principale > Armeria",
    "base.bc_armor_shop": "Via Principale > Negozio Armature",
    "base.bc_magic_shop": "Via Principale > Bottega Magica",
    "base.bc_the_inn": "Via Principale > La Locanda",
    "base.bc_dark_alley": "Via Principale > Vicolo Oscuro",
    "base.bc_church": "Via Principale > Chiesa",
    "base.bc_bank": "Via Principale > Banca",
    "base.bc_castle": "Via Principale > Castello Reale",
    "base.bc_prison": "Via dell'Ancora > Fuori dalla Prigione",
    "base.bc_unknown": "Sconosciuto",
    "base.qc_status_suffix": "tato  ",
    "base.qc_return_suffix": "itorno  ",
    "base.qc_inventory": "Inventario  ",
    "base.qc_help": "Aiuto  ",
    "base.qc_talk": "Parla",
    "base.qc_prefs": "Pref  ",
    "base.qc_cmds": "Cmd  ",
    "base.qc_bug": "Bug",
    "base.more": ", +{0} altri",
    "base.lv_label": " Lv:",
    "base.qc_inv": "Inv ",
    "base.mud_look": "guarda",
    "base.mud_to_redraw": " per ridisegnare",
    "base.antidote_used": "Bevi un antidoto — il veleno defluisce dal tuo corpo!",
    "base.antidotes_remaining": "Antidoti rimanenti: {0}/{1}",
    "base.not_poisoned": "Non sei avvelenato.",
    "base.no_antidotes": "Non hai antidoti. Comprali dai mercanti del sotterraneo o dal guaritore.",
    "base.online_only_mail": "  La posta è disponibile solo in modalità online.",
    "base.online_only_trade": "  Il commercio è disponibile solo in modalità online.",
    "base.online_only_bounties": "  Le taglie sono disponibili solo in modalità online.",
    "base.online_only_auction": "  La Casa d'Aste è disponibile solo in modalità online.",
    "base.online_only_boss": "  Il Boss Mondiale è disponibile solo in modalità online.",
    "base.compact_enabled": "  Modalità Compatta ATTIVATA - menù ottimizzati per mobile/schermi piccoli.",
    "base.compact_disabled": "  Modalità Compatta DISATTIVATA - menù a dimensione piena ripristinati.",
    "base.unknown_command": "  Comando sconosciuto: /{0}",
    "base.type_help": "  Digita /help o solo / per la lista dei comandi.",
    "base.help_commands_work": "  Questi comandi funzionano da qualsiasi luogo:",
    "base.help_stats": "- Visualizza le statistiche del personaggio",
    "base.help_inventory": "- Visualizza il tuo inventario",
    "base.help_quests": "- Visualizza le missioni attive",
    "base.help_gold": "- Mostra oro e saldo in banca",
    "base.help_health": "- Mostra salute e stato mana",
    "base.help_gear": "- Mostra equipaggiamento dettagliato e bonus (tuo o del gruppo)",
    "base.help_potion": "- Usa una pozione curativa",
    "base.help_herb": "- Usa un'erba dalla tua borsa",
    "base.help_materials": "- Visualizza materiali di fabbricazione",
    "base.help_time": "- Mostra l'ora attuale",
    "base.help_prefs": "- Apri menù preferenze",
    "base.help_mail": "- Apri la tua cassetta postale (online)",
    "base.help_trade": "- Visualizza pacchi commerciali (online)",
    "base.help_auction": "- Compra e vendi oggetti (Casa d'Aste)",
    "base.help_boss": "- Stato e combattimento del Boss Mondiale (online)",
    "base.help_compact": "- Attiva/disattiva modalità compatta (mobile/schermi piccoli)",
    "base.help_bug": "- Segnala un bug (apre GitHub)",
    "base.help_quick_keys": "  Tasti rapidi (singolo carattere):",
    "base.help_key_inventory": "- Inventario",
    "base.help_key_prefs": "- Preferenze",
    "base.help_key_status": "- Stato",
    "base.help_key_help": "- Questo aiuto",
    "base.help_key_bug": "- Segnala bug",
    "base.help_online_commands": "  Comandi online:",
    "base.help_say": "- Parla ai giocatori nel tuo luogo",
    "base.help_shout": "- Grida a tutti i giocatori online",
    "base.help_tell": "- Messaggio privato a un giocatore",
    "base.help_emote": "- Emote (es. /emote saluta con la mano)",
    "base.help_who": "- Vedi chi è online",
    "base.help_gossip": "- Chat globale fuori personaggio (/gos)",
    "base.no_active_quests": "  Nessuna missione attiva. Visita il Castello o parla con i PNG per trovare missioni.",
    "base.unknown_quest": "  \u2022 {0}",
    "base.more_quests": "  ... e altre {0} missioni.",
    "base.mat_found_floors": "    Si trova ai piani del sotterraneo {0}-{1}",
    "base.no_materials": "  Non hai materiali di fabbricazione.",
    "base.materials_hint1": "  Materiali rari si trovano nelle profondità del sotterraneo.",
    "base.materials_hint2": "  Sconfiggi mostri, apri forzieri del tesoro e sfida gli Antichi Dèi",
    "base.materials_hint3": "  per raccogliere i materiali necessari per potenti incantamenti.",
    "base.gold_on_hand": "  Oro in Mano: ",
    "base.bank_balance": "  Saldo in Banca: ",
    "base.total_wealth": "  Ricchezza Totale: ",
    "base.time_label": "Ora",
    "base.can_rest": "  Puoi riposare per la notte.",
    "base.rest_available_after": "  Riposo disponibile dopo le {0}:00 (Sera).",
    "base.server_time": "  Ora del Server: {0}",
    "base.fatigue_label": "  Affaticamento: ",
    "base.fatigue_exhausted_penalty": " — -10% danno/difesa/PE",
    "base.fatigue_tired_penalty": " — -5% danno/difesa",
    "base.fame_label": "  Fama: ",
    "base.fame_legendary": "Leggendaria",
    "base.fame_renowned": "Rinomata",
    "base.fame_well_known": "Ben Conosciuta",
    "base.fame_notable": "Notevole",
    "base.fame_unknown": "Sconosciuta",
    "base.fame_nobody": "Nessuno",
    "base.no_active_character": "  Nessun personaggio attivo.",
    "base.already_full_health": "  Sei già in piena salute!",
    "base.no_healing_potions": "  Non hai pozioni curative.",
    "base.visit_healer": "  Visita il Guaritore per comprarne.",
    "base.potion_healed": "  Bevi una pozione curativa e recuperi {0} PV!",
    "base.potions_remaining": "Pozioni rimanenti",
    "base.invalid_choice": "Scelta non valida: '{0}'",
    "base.try_hint": "Prova: [",
    "base.or": ", o [",
    "base.for_help": "per aiuto",
    "base.nothing_happens": "Non succede nulla.",
    "base.heading_to": "In cammino verso {0}...",
    "base.continue_on_way": "Dopo l'incontro, prosegui per la tua strada...",
    "base.ambush_faction_found": "Un membro di {0} ti ha trovato!",
    "base.what_do_you_do": "Cosa fai?",
    "base.ambush_fight": "ombatti - Affronta l'aggressore",
    "base.ambush_run": "uggi  - Tenta la fuga (può fallire)",
    "base.ambush_escaped": "Riesci a fuggire nella folla!",
    "base.ambush_blocked": "Non sei riuscito a scappare! Ti sbarrano il passo!",
    "base.combat_begins": "IL COMBATTIMENTO HA INIZIO!",
    "base.ambush_defeated": "Hai sconfitto {0}!",
    "base.experience_label": "  Esperienza: +{0}",
    "base.loot_label": "  Bottino:",
    "base.standing_decreased": "  La tua reputazione con {0} è diminuita! (-50)",
    "base.standing_approves": "  {0} approva! (+10 reputazione)",
    "base.ambush_disengaged": "Sei riuscito a disimpegnarti dal combattimento!",
    "base.combat_speed_set": "Velocità di combattimento impostata a: {0}",
    "base.pref_auto_heal_toggled": "Auto-cura ora è {0}",
    "base.pref_intimate_fade": "Le scene intime ora avranno una 'dissolvenza al nero'",
    "base.pref_intimate_full": "Le scene intime mostreranno ora il contenuto completo",
    "base.pref_sr_enabled": "Modalità Screen Reader ATTIVATA",
    "base.pref_sr_enabled_desc": "I menù useranno un formato di testo semplificato.",
    "base.pref_sr_disabled": "Modalità Screen Reader DISATTIVATA",
    "base.pref_sr_disabled_desc": "I menù useranno il formato visivo con arte ASCII.",
    "base.pref_telemetry_disabled": "Telemetria Alpha DISATTIVATA",
    "base.pref_telemetry_disabled_desc": "Non raccoglieremo più statistiche di gioco anonime.",
    "base.pref_telemetry_enabled": "Telemetria Alpha ATTIVATA",
    "base.pref_telemetry_enabled_desc": "Grazie per aiutarci a migliorare il gioco!",
    "base.pref_theme_set": "Tema colori impostato a: {0}",
    "base.pref_font_set": "Font del terminale impostato a: {0}",
    "base.pref_font_update": "  Il font si aggiornerà nel terminale a breve.",
    "base.pref_autolevel_enabled": "Livello Automatico ATTIVATO",
    "base.pref_autolevel_enabled_desc": "Salirai di livello automaticamente quando avrai abbastanza PE.",
    "base.pref_autolevel_disabled": "Livello Automatico DISATTIVATO",
    "base.pref_autolevel_disabled_desc": "Visita il Maestro di Livello per salire di livello manualmente.",
    "base.pref_compact_enabled": "Modalità Compatta ATTIVATA",
    "base.pref_compact_enabled_desc": "I menù useranno un layout compatto per mobile/schermi piccoli.",
    "base.pref_compact_enabled_keys": "Usa i tasti numerici per navigare i menù.",
    "base.pref_compact_disabled": "Modalità Compatta DISATTIVATA",
    "base.pref_compact_disabled_desc": "I menù useranno il layout a dimensione piena.",
    "base.pref_autoequip_disabled": "Auto-Equipaggia DISATTIVATO",
    "base.pref_autoequip_disabled_desc": "Gli acquisti nei negozi andranno direttamente nell'inventario.",
    "base.pref_autoequip_enabled": "Auto-Equipaggia ATTIVATO",
    "base.pref_autoequip_enabled_desc": "Ti verrà chiesto se equipaggiare o mettere nell'inventario all'acquisto.",
    "base.invalid_choice_simple": "Scelta non valida.",
    "base.no_one_to_talk": "Non c'è nessuno qui con cui parlare.",
    "base.who_talk_to": "  Con chi vorresti parlare?",
    "base.never_mind": "Non importa",
    "base.talk_to_who": "Parlare con chi? ",
    "base.decide_not_talk": "Decidi di non parlare con nessuno.",
    "base.talking_to": "Parli con: {0}",
    "base.female": "Femmina",
    "base.male": "Maschio",
    "base.npc_says": "  {0} dice:",
    "base.chat_with_them": " Chiacchiera con loro",
    "base.ask_rumors": " Chiedi delle voci",
    "base.ask_dungeons": " Chiedi dei sotterranei",
    "base.challenge_duel": " Sfida a duello",
    "base.deep_conversation": " Fai una conversazione profonda...",
    "base.attack_npc": " Attacca...",
    "base.walk_away": "Allontanati",
    "base.debug_personality": "(DEBUG) Visualizza tratti di personalità",
    "base.nod_walk_away": "  Annuisci e ti allontani.",
    "base.ask_rumors_to": "  Chiedi a {0} se ha sentito voci interessanti...",
    "base.npc_whispers": "  {0} si avvicina e sussurra:",
    "base.rumor_seals": "Dicono che sette sigilli antichi giacciano nascosti nelle profondità del sotterraneo...",
    "base.rumor_old_gods": "Gli antichi dèi si agitano nelle loro prigioni. Tempi oscuri si avvicinano.",
    "base.rumor_stranger": "Uno straniero misterioso è stato avvistato in città. Non fidarti di nessuno.",
    "base.rumor_king": "Il re diventa sempre più paranoico. Vede nemici ovunque.",
    "base.rumor_creature": "Nelle profondità del sotterraneo, c'è una creatura che custodisce ricchezze inimmaginabili.",
    "base.rumor_lower_levels": "Alcuni avventurieri non tornano mai dai livelli inferiori. Scegli la tua profondità con saggezza.",
    "base.rumor_dark_alley": "Ho sentito sussurrare di un negozio nascosto nel Vicolo Oscuro...",
    "base.rumor_temple": "I sacerdoti del tempio sanno più di quanto lascino intendere sugli antichi dèi.",
    "base.rumor_castle": "Si parla di un passaggio segreto nel castello. Ma ho già detto troppo.",
    "base.rumor_wave": "Un'onda torna all'oceano... qualunque cosa significhi. Nonsense criptico, se me lo chiedi.",
    "base.rumor_manwe": "Dicono che Manwe in persona abbia maledetto questi sotterranei. Ma è solo una storia... vero?",
    "base.rumor_healers": "I guaritori possono curare quasi tutto, a un prezzo.",
    "base.rumor_team": "Fai squadra con altri se vuoi sopravvivere ai livelli più profondi.",
    "base.rumor_veloura": "Ho sentito che c'è un modo per salvare Veloura... se hai il coraggio di provarci.",
    "base.rumor_npc_items": "Alcuni PNG portano oggetti potenti. Sconfiggili in un duello e reclama il loro equipaggiamento!",
    "base.ask_dungeons_to": "  Chiedi a {0} dei sotterranei...",
    "base.dungeon_not_ready": "  \\",
    "base.dungeon_get_stronger": "  \\",
    "base.dungeon_upper_ok": "  \\",
    "base.dungeon_watch_floor": "  \\",
    "base.dungeon_you_experienced": "  \\",
    "base.dungeon_good_luck": "  \\",
    "base.duel_challenge": "  Sfidi {0} a duello!",
    "base.npc_says_label": "  {0} dice:",
    "base.duel_decline_strong": "  \\",
    "base.duel_decline_weak": "  \\",
    "base.duel_decline_busy": "  \\",
    "base.duel_accepted": "  {0} accetta la tua sfida!",
    "base.duel_honorably": "  \\",
    "base.duel_victory": "Hai sconfitto {0} in un combattimento onorevole!",
    "base.duel_defeat": "{0} ha avuto la meglio su di te...",
    "base.attack_teammate": "  Non puoi attaccare un tuo compagno di squadra!",
    "base.attack_dangerous": "  {0} è livello {1}. Sembra estremamente pericoloso.",
    "base.attack_confirm": "  Sei sicuro? (S/N): ",
    "base.attack_reconsider": "  Ci ripensi.",
    "base.attack_lunge": "  Sguaini la tua arma e ti lanci contro {0}!",
    "base.attack_treacherous": "  \\",
    "base.attack_killed": "{0} cade a terra, senza vita.",
    "base.attack_looted": "  Saccheggi {0} oro dal suo corpo.",
    "base.attack_darkness": "  (+{0} Oscurità)",
    "base.attack_overpowered": "{0} ti ha sopraffatto...",
    "base.attack_remember": "  Se ne ricorderanno.",
    "base.stat_name": "Nome: ",
    "base.stat_class": "Classe: ",
    "base.stat_race": "  |  Razza: ",
    "base.stat_sex": "  |  Sesso: ",
    "base.stat_age": "Età: ",
    "base.stat_height": "  |  Altezza: ",
    "base.stat_weight": "  |  Peso: ",
    "base.stat_royal_authority": "  Autorità Reale: +10% ATT, +10% DIF, +5% PV",
    "base.stat_current_level": "Livello Attuale: ",
    "base.stat_xp_next": "PE per il Prossimo Livello: ",
    "base.stat_xp_need_total": " (Servono {0} in totale)",
    "base.stat_combat_style": "Stile di Combattimento: ",
    "base.style_two_handed": "Due Mani (+25% danno, -15% difesa)",
    "base.style_dual_wield": "Doppia Arma (+1 attacco, -10% difesa)",
    "base.style_sword_board": "Spada e Scudo (bilanciato, 20% probabilità di parata)",
    "base.style_one_handed": "Una Mano",
    "base.slot_main_hand": "Mano Principale: ",
    "base.slot_off_hand": "Mano Secondaria: ",
    "base.slot_head": "Testa:     ",
    "base.slot_body": "Corpo:     ",
    "base.slot_arms": "Braccia:   ",
    "base.slot_hands": "Mani:      ",
    "base.slot_legs": "Gambe:     ",
    "base.slot_feet": "Piedi:     ",
    "base.slot_waist": "Vita:      ",
    "base.slot_face": "Volto:     ",
    "base.slot_cloak": "Mantello:  ",
    "base.slot_neck": "Collo:     ",
    "base.slot_left_ring": "Anello Sin:",
    "base.slot_right_ring": "Anello Des:",
    "base.stat_active_effects": "Effetti Attivi:",
    "base.effect_magic_ac": "  - Bonus CA Magica: +{0}",
    "base.effect_stoneskin": "  - Pelle di Pietra: {0} assorbimento danno",
    "base.effect_raging": "  - IN FURIA! (+Forza, +PV, -CA)",
    "base.effect_smite": "  - Punizione Sacra: {0} cariche",
    "base.stat_active_buffs": "Potenziamenti Attivi:",
    "base.buff_potion_mastery": "  - Maestria Pozioni: +50% cura (pozioni, erbe, elisir)",
    "base.buff_arcane_mastery": "  - Maestria Arcana: +15% danno incantesimi",
    "base.buff_tricksters_luck": "  - Fortuna del Furfante: 20% probabilità di bonus casuale",
    "base.awakening_dormant": "Dormiente",
    "base.awakening_stirring": "Agitato",
    "base.awakening_aware": "Consapevole",
    "base.awakening_seeking": "Cercante",
    "base.awakening_illuminated": "Illuminato",
    "base.awakening_transcendent": "Trascendente",
    "base.awakening_enlightened": "Risvegliato",
    "base.awakening_awakened": "Destato",
    "base.stat_awakening": "  Risveglio: {0} ({1}/7)",
    "base.stat_gold_hand": "Oro in Mano: ",
    "base.stat_gold_bank": "Oro in Banca: ",
    "base.stat_total_wealth": "Ricchezza Totale: ",
    "base.stat_marital": "Stato Civile: ",
    "base.stat_married": "Sposato",
    "base.stat_married_to": " con ",
    "base.stat_spouses_total": "  ({0} coniugi in totale)",
    "base.stat_children": "Figli: ",
    "base.stat_pregnancy": "Gravidanza: ",
    "base.stat_days": "{0} giorni",
    "base.stat_in_relationship": "In una relazione ({0} amanti)",
    "base.stat_single": "Celibe",
    "base.stat_team": "Squadra: ",
    "base.stat_chivalry": "Cavalleria: ",
    "base.stat_darkness": "  |  Oscurità: ",
    "base.stat_holy": "  Sacro ",
    "base.stat_evil": " Malvagio",
    "base.stat_align_abilities": "  Abilità di Allineamento:",
    "base.stat_loyalty": "Lealtà: ",
    "base.stat_mental": "  |  Salute Mentale: ",
    "base.stat_monarch": "*** MONARCA REGNANTE ***",
    "base.stat_allegiance": "Alleanza: ",
    "base.stat_rank": "Rango: ",
    "base.stat_active_bonuses": "Bonus Attivi:",
    "base.faction_crown_bonus": "  \u2022 10% di sconto in tutti i negozi",
    "base.faction_faith_bonus": "  \u2022 25% di sconto sui servizi di guarigione",
    "base.faction_shadows_bonus": "  \u2022 20% prezzi migliori alla vendita di oggetti",
    "base.stat_no_faction": "Non hai giurato fedeltà a nessuna fazione.",
    "base.stat_faction_hint": "  Visita il Castello, il Tempio o il Vicolo Oscuro per saperne di più.",
    "base.stat_faction_standing": "Reputazione con le Fazioni:",
    "base.standing_revered": " (Venerato)",
    "base.standing_honored": " (Onorato)",
    "base.standing_friendly": " (Amichevole)",
    "base.standing_neutral": " (Neutrale)",
    "base.standing_unfriendly": " (Ostile)",
    "base.standing_hostile": " (Nemico)",
    "base.standing_hated": " (Odiato)",
    "base.stat_monster_kills": "Mostri Uccisi: ",
    "base.stat_monster_defeats": "  |  Sconfitte da Mostri: ",
    "base.stat_player_kills": "Giocatori Uccisi: ",
    "base.stat_player_defeats": "  |  Sconfitte da Giocatori: ",
    "base.stat_monster_winrate": "Tasso Vittorie vs Mostri: ",
    "base.stat_pvp_winrate": "Tasso Vittorie PvP: ",
    "base.stat_deepest_floor": "Piano Più Profondo Raggiunto: ",
    "base.stat_old_gods": "Antichi Dèi: ",
    "base.gods_defeated": "{0} sconfitti",
    "base.gods_allied": "{0} alleati",
    "base.gods_saved": "{0} salvati",
    "base.gods_awaiting": "{0} in attesa di salvataggio",
    "base.gods_none": "Nessuno incontrato",
    "base.god_have_artifact": "  {0}: Hai l'artefatto. Torna al suo piano.",
    "base.god_seek_artifact": "  {0}: Cerca l'artefatto più in profondità nel sotterraneo.",
    "base.stat_seals": "Sigilli Antichi: ",
    "base.seals_collected": "{0}/7 raccolti",
    "base.stat_worshipped_god": "Dio Adorato: ",
    "base.stat_agnostic": "Nessuno (Agnostico)",
    "base.wrath_active": "*** IRA DIVINA ATTIVA ***",
    "base.wrath_angered": "  Adirato: {0}",
    "base.wrath_by_worshipping": "  Per aver adorato: {0}",
    "base.wrath_minor": "Minore (tradimento stesso allineamento)",
    "base.wrath_moderate": "Moderata (tradimento allineamento opposto)",
    "base.wrath_severe": "Grave (grande tradimento allineamento opposto)",
    "base.wrath_unknown": "Sconosciuta",
    "base.wrath_severity": "  Gravità: {0}",
    "base.wrath_punishment_hint": "  (La punizione può colpire durante l'esplorazione del sotterraneo)",
    "base.affliction_blind": "  - Cieco",
    "base.affliction_plague": "  - Pestilenza",
    "base.affliction_smallpox": "  - Vaiolo",
    "base.affliction_measles": "  - Morbillo",
    "base.affliction_leprosy": "  - Lebbra",
    "base.affliction_poisoned": "  - Avvelenato (Livello {0})",
    "base.affliction_addicted": "  - Dipendente (Livello {0})",
    "base.affliction_haunted": "  - Perseguitato da {0} demone/i",
    "base.gear_inspect_who": "  Di chi vuoi ispezionare l'equipaggiamento?",
    "base.gear_selection_prompt": "  Selezione (o Invio per il tuo): ",
    "base.equipment_totals": "Totali Equipaggiamento:",
    "base.weapon_power": "  Potenza Arma: ",
    "base.armor_class": "  |  Classe Armatura: ",
    "base.bonuses": "  Bonus: ",
}
