translations = {
    "healer.health_status": "IL TUO STATO DI SALUTE",
    "healer.header": "L'ARCO D'ORO - CAPANNA DEL GUARITORE",
    "healer.heal": "Cura PV",
    "healer.full_heal": "Cura Completa",
    "healer.cure_poison": "Cura Veleno",
    "healer.cure_disease": "Cura Malattia",
    "healer.decurse": "Rimuovi Maledizione",
    "healer.resurrect": "Resurrezione",
    "healer.buy_potions": "Compra Pozioni",
    "healer.mana_potions": "Pozioni di Mana",
    "healer.buy_antidotes": "Compra Antidoti",
    "healer.addiction": "Riabilitazione Dipendenza",
    "healer.status": "Stato",
    "healer.return": "Torna alla Via Principale",
    "healer.section_healing": "Servizi di Guarigione",
    "healer.section_disease": "Trattamento Malattie",
    "healer.section_other": "Altri Servizi",
    "healer.sr_title": "L'ARCO D'ORO - CAPANNA DEL GUARITORE",
    "healer.shopkeeper_mood": "{0} il Grosso siede alla scrivania, leggendo un libro.",
    "healer.mira_teaser1": "Una giovane donna s'inginocchia accanto a un viaggiatore ferito, curando",
    "healer.mira_teaser2": "le sue ferite con attenzione. È brava. Si capisce che lo ha fatto molte volte.",
    "healer.afflictions_label": "Afflizioni",
    "healer.affliction_poison": "Veleno",
    "healer.affliction_blind": "Cecità",
    "healer.affliction_plague": "Peste",
    "healer.affliction_smallpox": "Vaiolo",
    "healer.affliction_measles": "Morbillo",
    "healer.affliction_leprosy": "Lebbra",
    "healer.affliction_bane": "Flagello",
    "healer.affliction_poisoned": "Avvelenato",
    "healer.affliction_lovers_bane": "Flagello dell'Amante",
    "healer.services_available": "Servizi Disponibili:",
    "healer.expert_prompt": "Capanna del Guaritore (H,F,B,M,P,C,D,A,S,R) :",
    "healer.alignment_discount": "Il tuo allineamento {0} ti garantisce uno sconto del {1}%!",
    "healer.alignment_markup": "Il tuo allineamento {0} causa un sovrapprezzo del {1}%.",
    "healer.world_discount": "Eventi Mondiali: sconto del {0}% attivo!",
    "healer.world_markup": "Eventi Mondiali: aumento dei prezzi del {0}%!",
    "healer.already_full": "\"{0}, sei già in piena salute,\" dice {1} con un'alzata di spalle.",
    "healer.how_much_hp": "\"Quanti PV vorresti ripristinare?\"",
    "healer.asks": ", chiede {0}.",
    "healer.base_cost_info": "Il costo base è {0} monete d'oro per PV ripristinato.",
    "healer.hp_prompt": "Quanti PV ripristinare (0 per annullare)? ",
    "healer.come_back_healing": "\"Torna quando avrai bisogno di cure.\"",
    "healer.cant_afford_healing": "Non puoi permetterti tante cure!",
    "healer.can_afford_up_to": "Puoi permetterti fino a {0} PV.",
    "healer.hands_on_wounds": "{0} posa le mani sulle tue ferite...",
    "healer.warm_light": "Una calda luce ti attraversa!",
    "healer.healed_hp": "Sei stato curato per {0} PV!",
    "healer.cost_line": "Costo: {0} monete d'oro",
    "healer.already_full2": "\"Sei già in piena salute, {0}!\"",
    "healer.full_restore_cost": "\"Un ripristino completo ti costerà {0} monete d'oro,\" dice {1}, esaminando le tue ferite.",
    "healer.proceed_full_heal": "Procedere con la cura completa (S/N)? ",
    "healer.as_you_wish": "\"Come desideri.\"",
    "healer.cant_afford": "Non puoi permettertelo!",
    "healer.begins_ritual": "{0} inizia il rituale di guarigione...",
    "healer.divine_light": "La luce divina ti avvolge!",
    "healer.completely_healed": "Sei completamente guarito!",
    "healer.hp_restored_to": "PV ripristinati a {0}/{1}",
    "healer.mana_restored_to": "Mana ripristinato a {0}/{1}",
    "healer.potions_price": "\"Le pozioni curative costano {0} monete d'oro ciascuna (tasse incluse),\" dice {1}, indicando lo scaffale di fiale.",
    "healer.max_potions": "Stai trasportando il numero massimo di pozioni curative! ({0})",
    "healer.current_potions": "Al momento hai {0}/{1} pozioni curative.",
    "healer.can_afford_potions": "Puoi permetterti fino a {0} pozioni.",
    "healer.how_many_potions": "Quante pozioni comprare (0 per annullare)? ",
    "healer.come_back_supplies": "\"Torna quando avrai bisogno di scorte.\"",
    "healer.cant_afford_many": "Non puoi permettertene tante!",
    "healer.handed_potions": "{0} ti porge {1} pozion{2} curativ{2}.",
    "healer.now_have_potions": "Ora hai {0} pozioni curative.",
    "healer.no_mana_use": "\"I {0} non hanno bisogno di pozioni di mana,\" dice {1}, scuotendo la testa.",
    "healer.mana_price": "\"Le pozioni di mana costano {0} monete d'oro ciascuna (tasse incluse). Ciascuna ripristina {1} mana,\" dice {2}, prendendo fiale azzurre dallo scaffale.",
    "healer.current_mana_potions": "Al momento hai {0} pozioni di mana (max {1}).",
    "healer.max_mana_potions": "Stai trasportando il numero massimo di pozioni di mana!",
    "healer.handed_mana": "{0} ti porge {1} pozion{2} di mana.",
    "healer.now_have_mana": "Ora hai {0} pozioni di mana.",
    "healer.antidote_intro": "\"{0} estrae piccole fiale verdi.\"",
    "healer.antidote_price": "\"Antidoti — {0} monete d'oro ciascuno. Curano il veleno all'istante.\"",
    "healer.max_antidotes": "Stai trasportando il numero massimo di antidoti! ({0})",
    "healer.current_antidotes": "Al momento hai {0}/{1} antidoti.",
    "healer.can_afford_antidotes": "Puoi permetterti fino a {0} antidoti.",
    "healer.how_many_antidotes": "Quanti antidoti comprare (0 per annullare)? ",
    "healer.handed_antidotes": "{0} ti porge {1} antidot{2}.",
    "healer.now_have_antidotes": "Ora hai {0} antidoti.",
    "healer.antidote_tip": "Usa /antidoto o [D] nel menu pozioni del dungeon per curare il veleno.",
    "healer.check_poison": "\"Lascia che controlli il veleno nel tuo sangue...\" dice {0}, esaminandoti attentamente.",
    "healer.not_poisoned": "\"Non sei avvelenato! Il tuo sangue è pulito.\"",
    "healer.venom_found": "\"Ah sì, posso vedere il veleno scorrere nelle tue vene.\"",
    "healer.purge_cost": "\"Purificarti da questo veleno costerà {0} monete d'oro.\"",
    "healer.cure_poison_prompt": "Curare il veleno (S/N)? ",
    "healer.careful_poison": "\"Fai attenzione, il veleno continuerà a farti del male!\"",
    "healer.cant_afford_antidote": "Non puoi permetterti l'antidoto!",
    "healer.mixing_antidote": "{0} prepara un antidoto verde luminescente...",
    "healer.drink_mixture": "Bevi l'amara mistura...",
    "healer.poison_purged": "Il veleno è stato purificato dal tuo corpo!",
    "healer.no_longer_poisoned": "Non sei più avvelenato!",
    "healer.examine_diseases": "\"Bene, lascia che ti visiti!\" dice {0}.",
    "healer.disease_blindness": "Cecità",
    "healer.disease_plague": "Peste",
    "healer.disease_smallpox": "Vaiolo",
    "healer.disease_measles": "Morbillo",
    "healer.disease_leprosy": "Lebbra",
    "healer.disease_lovers_bane": "Flagello dell'Amante",
    "healer.no_diseases": "Nessuna malattia trovata!",
    "healer.wasting_time": "\"Mi stai facendo perdere tempo!\" dice {0} e torna alla scrivania.",
    "healer.affecting_diseases": "Malattie in Corso",
    "healer.cure_all": "(C)ura tutte le malattie - {0} monete d'oro",
    "healer.choose_disease": "Scegli la malattia da curare (o C per tutte, R per annullare): ",
    "healer.come_back_treatment": "\"Torna quando sarai pronto per il trattamento.\"",
    "healer.complete_healing_cost": "\"Un processo di guarigione completo ti costerà {0} monete d'oro,\" dice {1}.",
    "healer.go_ahead_pay": "Procedere e pagare (S/N)? ",
    "healer.healing_disease_cost": "\"Per curare {0} voglio {1} monete d'oro,\" dice {2}.",
    "healer.give_gold": "Dai l'oro a {0}. Ti dice di sdraiarti su un",
    "healer.bed_nearby": "letto, in una stanza qui vicino.",
    "healer.fall_asleep": "Ti addormenti presto",
    "healer.wake_up1": "Quando ti svegli dal tuo meritato riposo, ti senti",
    "healer.wake_up2": "molto più forte di prima!",
    "healer.walk_out": "Esci verso {0}...",
    "healer.check_equipment": "\"Bene, lascia che dia un'occhiata al tuo equipaggiamento!\" dice {0}.",
    "healer.equipment_alright": "\"Il tuo equipaggiamento è a posto!\"",
    "healer.nods_approvingly": "{0} annuisce con approvazione.",
    "healer.curse_cost": "\"Costerà {0} monete d'oro rimuovere la maledizione.\"",
    "healer.curse_warning": "ATTENZIONE: L'oggetto verrà distrutto nel processo!",
    "healer.remove_curse_prompt": "Rimuovere la maledizione (S/N)? ",
    "healer.strange_spells": "{0} recita strani incantesimi...",
    "healer.suddenly": "All'improvviso!",
    "healer.disintegrates": "L'{0} si disintegra!",
    "healer.smiles_pay1": "{0} ti sorride. Paghi il vecchio per",
    "healer.smiles_pay2": "il suo servizio ben eseguito.",
    "healer.gold_label": "Oro",
    "healer.healing_potions_label": "Pozioni Curative",
    "healer.status_poisoned": "*AVVELENATO* - Perdi PV ogni giorno!",
    "healer.status_blindness": "*Cecità* - Precisione ridotta",
    "healer.status_plague": "*Peste* - Gravi penalità alle statistiche",
    "healer.status_smallpox": "*Vaiolo* - Costituzione indebolita",
    "healer.status_measles": "*Morbillo* - Abilità ridotte",
    "healer.status_leprosy": "*Lebbra* - Grave debilitazione",
    "healer.status_lovers_bane": "*Flagello dell'Amante* - Contratto a Via dell'Amore",
    "healer.not_infected": "Non sei infetto!",
    "healer.stay_healthy": "Resta in salute!",
    "healer.drug_status": "Stato Sostanze:",
    "healer.active_drug": "Sostanza Attiva: {0} ({1} giorni rimanenti)",
    "healer.no_drug_effects": "Nessun effetto di sostanze attivo.",
    "healer.addicted_level": "*DIPENDENTE* - Livello di dipendenza: {0}%",
    "healer.rehab_available": "Trattamento riabilitativo disponibile per {0} monete d'oro.",
    "healer.no_dependency": "\"{0}, non mostri segni di dipendenza da sostanze,\" dice {1} dopo averti visitato.",
    "healer.substance_taken_hold": "\"{0}, posso vedere che la sostanza si è impossessata di te,\" dice {1} con gravità.",
    "healer.active_drug_display": "Sostanza Attiva: {0} ({1} giorni rimanenti)",
    "healer.addiction_level_display": "Livello di Dipendenza: {0}%",
    "healer.drug_tolerances": "Tolleranze: {0} sostanza/e",
    "healer.treatment_cost_quote": "\"Il trattamento riabilitativo costerà {0} monete d'oro.\"",
    "healer.base_cost_label": "Costo base: {0} monete d'oro",
    "healer.surcharge": "Supplemento per gravità dipendenza: {0} monete d'oro",
    "healer.treatment_will": "Questo trattamento:",
    "healer.will_purge": "- Purifica immediatamente tutti gli effetti delle sostanze",
    "healer.will_cure": "- Cura completamente la tua dipendenza",
    "healer.will_reset": "- Azzera tutte le tolleranze alle sostanze",
    "healer.proceed_rehab": "Procedere con la riabilitazione (S/N)? ",
    "healer.door_open": "\"La porta è sempre aperta quando sarai pronto, {0}.\"",
    "healer.cant_afford_treatment": "Non puoi permetterti il trattamento!",
    "healer.find_gold": "\"Forse troverai l'oro in qualche modo... Sarò qui.\"",
    "healer.private_room": "{0} ti conduce in una stanza privata sul retro...",
    "healer.purifying_herbs": "Prepara una complessa mistura di erbe purificanti...",
    "healer.treatment_begins": "Il trattamento ha inizio",
    "healer.painful_treatment": "Dopo ore di trattamento doloroso ma efficace...",
    "healer.body_cleansed": "Il tuo corpo è stato purificato da tutte le sostanze!",
    "healer.addiction_cured": "La tua dipendenza è stata curata!",
    "healer.tolerances_reset": "Tutte le tolleranze alle sostanze sono state azzerate!",
    "healer.free_chains": "\"{0}, sei libero dalle catene della dipendenza.\"",
    "healer.stay_clean": "{0} sorride calorosamente. \"Resta pulito, amico mio.\"",
    "healer.menu_heal_hp": "(H) Cura PV       - Ripristina alcuni PV ({0} oro per PV)",
    "healer.menu_full_heal": "(F) Cura Completa - Ripristina tutti i PV (costo variabile)",
    "healer.menu_buy_potions": "(B) Pozioni       - Acquista pozioni curative ({0} oro ciascuna)",
    "healer.menu_mana_potions": "(M) Pozioni Mana  - Acquista pozioni di mana ({0} oro ciascuna)",
    "healer.menu_poison_cure": "(P) Cura Veleno   - Rimuovi il veleno ({0} oro)",
    "healer.menu_cure_disease": "(C) Cura Malattia - Cura le afflizioni (costo variabile)",
    "healer.menu_blindness": "Cecità:           {0} oro",
    "healer.menu_plague": "Peste:            {0} oro",
    "healer.menu_smallpox": "Vaiolo:           {0} oro",
    "healer.menu_measles": "Morbillo:         {0} oro",
    "healer.menu_leprosy": "Lebbra:           {0} oro",
    "healer.menu_lovers_bane": "Flagello Amante:  {0} oro",
    "healer.menu_decurse": "(D) Rimuovi Malediz. - Rimuovi maledizione ({0} oro)",
    "healer.menu_addiction": "(A) Riabilitazione   - Cura dipendenza ({0} oro)",
    "healer.menu_status": "(S) Stato            - Visualizza il tuo stato di salute",
    "healer.menu_return": "(R) Ritorna          - Torna alla Via Principale",
    "healer.menu_heal_suffix": "ura PV         ",
    "healer.menu_full_suffix": "ura Completa    ",
    "healer.menu_potions_suffix": "ozioni          ",
    "healer.menu_mana_suffix": "ana Pozioni",
    "healer.menu_poison_suffix": "ura Veleno     ",
    "healer.menu_disease_suffix": "ura Malattia    ",
    "healer.menu_decurse_suffix": "imuovi Malediz.",
    "healer.menu_addiction_suffix": "iabilitazione   ",
    "healer.menu_status_suffix": "tato            ",
    "healer.menu_return_suffix": "itorna in strada",
    "healer.bbs_hp": " PV:",
    "healer.bbs_gold": "  Oro:",
    "healer.bbs_potions": "  Pozioni:",
    "healer.invalid_choice": "Scelta non valida. Scrivi 'look' per ridisegnare il menu.",
    "healer.services_title": "{0} - Servizi",
    "healer.tax_healing": "Guarigione",
    "healer.tax_full_healing": "Guarigione Completa",
    "healer.tax_potions": "Pozioni Curative",
    "healer.tax_mana_potions": "Pozioni di Mana",
    "healer.tax_antidotes": "Antidoti",
    "healer.tax_poison_cure": "Cura Veleno",
    "healer.tax_disease_cures": "Cure Malattie",
    "healer.tax_disease_cure": "Cura Malattia",
    "healer.tax_curse_removal": "Rimozione Maledizione",
    "healer.tax_rehab": "Trattamento Riabilitativo",
    "healer.mana_how_many": "Quante pozioni comprare (0 per annullare)? ",
    "healer.disease_gold": "oro",
    "healer.invalid_choice_short": "Scelta non valida.",
    "bank.header": "LA BANCA FERROFORTE",
    "bank.access_denied": "ACCESSO NEGATO",
    "bank.robbery_header": "RAPINA IN BANCA",
    "bank.defeated": "SCONFITTO! Le guardie ti sopraffanno!",
    "bank.section_services": "Servizi Bancari:",
    "bank.section_account": "Stato del Tuo Conto",
    "bank.deposit": "Deposita",
    "bank.withdraw": "Preleva",
    "bank.balance": "Saldo: {0} monete d'oro",
    "bank.loan": "Richiedi Prestito",
    "bank.repay": "Rimborsa Prestito",
    "bank.transfer": "Trasferisci",
    "bank.interest": "Info Interessi",
    "bank.history": "Storico Conto",
    "bank.guard": "Servizio di Guardia",
    "bank.resign_guard": "DIMETTITI DAL SERVIZIO DI GUARDIA",
    "bank.robbery": "Rapina la Banca",
    "bank.return": "Torna alla Via Principale",
    "bank.loan_services": "SERVIZI DI PRESTITO",
    "bank.tagline": "              \"Dove la Vostra Fortuna è la Nostra Fondazione\"",
    "bank.bbs_on_hand": " Disponibile:",
    "bank.bbs_bank": "  Banca:",
    "bank.bbs_total": "  Totale:",
    "bank.bbs_loan": "  Prestito:",
    "bank.bbs_guard_on": "  Guardia:SÌ",
    "bank.menu_deposit": "eposita Oro        ",
    "bank.menu_withdraw": "releva Oro         ",
    "bank.menu_transfer": "rasferisci a Giocatore",
    "bank.menu_loan": "restito            ",
    "bank.menu_interest": "nfo Interessi       ",
    "bank.menu_history": "torico Conto",
    "bank.menu_guard": "uardia              ",
    "bank.menu_resign": " Dimetti Guardia     ",
    "bank.menu_rob": "apina la Banca!",
    "bank.menu_return": " Torna alla Via Principale",
    "bank.no_gold_deposit": "{0} sospira pesantemente. \"Non hai oro da depositare, amico mio.\"",
    "bank.empty_pockets": "\"Torna quando le tue tasche non saranno così... vuote.\"",
    "bank.leans_forward": "{0} si sporge in avanti con impazienza, gli occhi luccicanti.",
    "bank.how_much_deposit": "\"Quanto vorresti depositare, {0}?\"",
    "bank.invalid_amount": "Importo non valido.",
    "bank.more_than_have": "{0} ridacchia. \"Non puoi depositare più di quanto possiedi!\"",
    "bank.counts_coins": "{0} conta le monete con precisione esperta, poi timbra la tua ricevuta.",
    "bank.safer_than_crown": "\"Il tuo oro è ora più al sicuro dei gioielli della corona del Re!\"",
    "bank.account_empty": "{0} scuote la testa con tristezza.",
    "bank.earn_some_gold": "\"Il tuo conto è vuoto. Forse dovresti provare a guadagnare un po' d'oro?\"",
    "bank.disappointed": "{0} sembra leggermente deluso ma professionale.",
    "bank.how_much_withdraw": "\"Quanto vorresti prelevare, {0}?\"",
    "bank.invalid_amount2": "{0} si acciglia. \"Importo non valido.\"",
    "bank.not_that_much": "{0} sospira. \"Non hai tutto quell'oro nel tuo conto.\"",
    "bank.counts_reluctance": "{0} conta il tuo oro con un velo di riluttanza.",
    "bank.careful_gold": "\"Fai attenzione con tutto quell'oro là fuori. Le strade non sono sempre sicure.\"",
    "bank.need_gold_transfer": "{0} scuote la testa.",
    "bank.need_gold_transfer2": "\"Devi avere oro nel tuo conto per effettuare un trasferimento.\"",
    "bank.transfer_ledger": "{0} estrae un registro dei trasferimenti.",
    "bank.whose_account": "\"A quale conto desideri trasferire l'oro?\"",
    "bank.cant_find_account": "{0} controlla i suoi registri. \"Non trovo quel titolare di conto.\"",
    "bank.stamps_transfer": "{0} timbra il documento di trasferimento con un gran gesto.",
    "bank.recipient_notified": "\"Il destinatario è stato notificato. Eccellente fare affari con voi!\"",
    "bank.adjusts_spectacles": "{0} sistema i suoi occhiali ed esamina la tua pratica.",
    "bank.financial_assistance": "\"Ah, cercate un po' di assistenza finanziaria, vero?\"",
    "bank.already_loan": "\"Avete già un prestito in sospeso. Desiderate rimborsarlo?\"",
    "bank.repay_full": "Rimborsa l'intero importo ({0} oro)",
    "bank.partial_repay": "Rimborso parziale",
    "bank.not_now": "Non ora",
    "bank.produces_pamphlet": "{0} produce un opuscolo consunto.",
    "bank.questions_open": "\"Domande? La mia porta è sempre aperta... durante l'orario di lavoro.\"",
    "bank.reviews_records": "{0} sistema i suoi occhiali e rivede i tuoi registri...",
    "bank.account_holder": "Titolare del Conto: {0}",
    "bank.gold_on_hand_detail": "  Oro Disponibile:   {0}",
    "bank.gold_in_bank_detail": "  Oro in Banca:      {0}",
    "bank.total_net_worth": "  Patrimonio Totale: {0}",
    "bank.outstanding_loan": "  Prestito in Sospeso: {0} oro",
    "bank.daily_interest_loan": "  Interesse Giornaliero: {0} oro (5%)",
    "bank.interest_earned": "  Interessi Maturati: {0} oro (totale)",
    "bank.daily_interest_savings": "  Interesse Giornaliero: {0} oro (0,1%)",
    "bank.status_active": "  Stato: ATTIVO",
    "bank.daily_wage": "  Paga Giornaliera: {0} oro",
    "bank.guard_level_bonus": "  Bonus livello: {0} oro per livello",
    "bank.sir": "signore",
    "bank.madam": "signora",
    "bank.withdraw_success": "Prelevi {0} monete d'oro.",
    "church.header": "CHIESA DELLE BUONE OPERE",
    "church.donate": "Fai una donazione alla Chiesa",
    "church.blessing": "Acquista una benedizione",
    "church.healing": "Cerca servizi di guarigione",
    "church.marriage": "Organizza una cerimonia nuziale",
    "church.confess": "Confessa i tuoi peccati",
    "church.records": "REGISTRI DELLA CHIESA",
    "church.bishop": "Parla con il Vescovo",
    "church.return": "Torna alla Via Principale",
    "church.healing_services": "SERVIZI DI GUARIGIONE DELLA CHIESA",
    "church.confession": "CONFESSIONE",
    "church.audience_bishop": "UDIENZA CON IL VESCOVO",
    "church.entry_denied": "INGRESSO NEGATO!",
    "church.holy_wards": "Le protezioni sacre che circondano questo luogo sacro respingono chi ha un allineamento oscuro.",
    "church.cleanse_soul": "Forse una confessione in un santuario neutrale potrebbe aiutare a purificare la tua anima...",
    "church.press_return": "Premi Invio per tornare in strada...",
    "church.desc1": "Ti trovi in una magnifica cattedrale con archi svettanti e vetrate colorate",
    "church.desc2": "che proiettano luce multicolore sul pavimento di pietra. L'aria è pervasa",
    "church.desc3": "dal profumo dell'incenso e dal mormorio sommesso delle preghiere. Candele tremolano",
    "church.desc4": "sull'altare e reliquie religiose rivestono le pareti.",
    "church.sr_desc": "Una magnifica cattedrale con archi svettanti e vetrate colorate.",
    "church.chivalry": "La tua cavalleria attuale: {0}",
    "church.darkness": "La tua oscurità attuale: {0}",
    "church.alignment": "Il tuo allineamento morale: {0}",
    "church.sr_alignment_line": "Cavalleria: {0}  Oscurità: {1}  Allineamento: {2}",
    "church.bishop_approves": "{0} annuisce con approvazione per la tua presenza virtuosa.",
    "church.bishop_concerned": "{0} appare preoccupato per l'oscurità nella tua anima.",
    "church.bishop_welcomes": "{0} ti dà il benvenuto in questo luogo sacro.",
    "church.services_title": "Servizi della Chiesa Disponibili:",
    "church.sr_services_title": "Servizi della Chiesa:",
    "church.bbs_alignment": " Allineamento: ",
    "church.bbs_chivalry": "  Cavalleria:",
    "church.bbs_darkness": "  Oscurità:",
    "church.donate_have_gold": "Hai {0} {1}.",
    "church.donate_how_much": "Quanto vuoi donare alla Chiesa?",
    "church.donate_amount_prompt": "Importo: ",
    "church.donate_invalid": "Importo non valido.",
    "church.donate_zero": "La Chiesa apprezza la tua presenza, se non la tua generosità.",
    "church.donate_no_gold": "Furfante! Non hai tutto quell'oro!",
    "church.donate_confirm": "Donare {0} {1} alla Chiesa? (S/N): ",
    "church.donate_cancelled": "Forse un'altra volta.",
    "church.donate_appreciated": "Il tuo contributo di {0} {1} è apprezzato.",
    "church.donate_virtue": "La tua virtù e il sostegno della Chiesa aumentano.",
    "church.donate_blessed_by": "Sei benedetto da {0}.",
    "church.donate_chivalry_gain": "Guadagni {0} punti cavalleria!",
    "church.donate_faith_gain": "La tua pietà è stata annotata. (+{0} reputazione presso la Fede)",
    "church.blessing_pure": "La tua anima non ha bisogno di salvezza (fortunato te).",
    "church.blessing_how_much": "Quanto vuoi offrire per una benedizione?",
    "church.blessing_no_offering": "La Chiesa non può concedere la salvezza senza un'offerta adeguata.",
    "church.blessing_no_gold": "Non hai tutto quell'oro!",
    "church.blessing_confirm": "Acquistare la benedizione per {0} {1}? (S/N): ",
    "church.blessing_cancelled": "La tua anima resta com'era.",
    "church.blessing_contribution": "Il tuo contributo di {0} {1} ti concede la salvezza.",
    "church.blessing_lightens": "La tua anima oscura si alleggerisce.",
    "church.blessing_ritual": "{0} compie un sacro rituale su di te.",
    "church.blessing_divine_light": "Una luce divina ti circonda!",
    "church.blessing_chivalry": "Guadagni {0} punti cavalleria!",
    "church.blessing_darkness_decrease": "La tua oscurità diminuisce di {0} punti!",
    "church.blessing_days": "Sei benedetto per 7 giorni!",
    "church.blessing_faith": "La Fede riconosce la tua devozione. (+{0} reputazione presso la Fede)",
    "church.heal_perfect": "Sei in perfetta salute, nel corpo e nell'anima.",
    "church.heal_blessed": "{0} ti benedice per la tua buona sorte.",
    "church.heal_examines": "{0} ti esamina attentamente...",
    "church.heal_available": "Servizi di guarigione disponibili:",
    "church.heal_restore_hp": "- Ripristina salute: {0} {1}",
    "church.heal_blindness": "- Cura cecità: {0} {1}",
    "church.heal_plague": "- Cura peste: {0} {1}",
    "church.heal_smallpox": "- Cura vaiolo: {0} {1}",
    "church.heal_measles": "- Cura morbillo: {0} {1}",
    "church.heal_leprosy": "- Cura lebbra: {0} {1}",
    "church.heal_complete": "- Guarigione completa (tutte le condizioni): {0} {1}",
    "church.heal_prompt": "Quale guarigione cerchi? (H) Salute, (B) Cecità, (P) Peste, (S) Vaiolo, (M) Morbillo, (L) Lebbra, (A) Tutto, (N) Niente: ",
    "church.heal_gods_watch": "Che gli dèi veglino su di te.",
    "church.heal_not_needed": "Non hai bisogno di quella particolare guarigione.",
    "church.heal_need_gold": "Ti servono {0} {1} per {2}.",
    "church.heal_return_funds": "Torna quando avrai fondi sufficienti.",
    "church.heal_pay_confirm": "Pagare {0} {1} per {2}? (S/N): ",
    "church.heal_cancelled": "Forse un'altra volta.",
    "church.heal_ritual": "{0} inizia un sacro rituale di guarigione...",
    "church.heal_wounds_close": "Le tue ferite si chiudono e la tua forza ritorna!",
    "church.heal_sight_restored": "La tua vista è ripristinata! Il mondo torna a fuoco!",
    "church.heal_plague_cured": "La peste abbandona il tuo corpo! Ti senti purificato!",
    "church.heal_smallpox_cured": "Il vaiolo è curato! La tua pelle si rischiara!",
    "church.heal_measles_cured": "Il morbillo svanisce! Ti senti di nuovo in salute!",
    "church.heal_leprosy_cured": "La lebbra è bandita! Il tuo corpo è risanato!",
    "church.heal_all_cured": "La luce divina riempie il tuo corpo! Tutte le afflizioni sono curate!",
    "church.heal_completely_restored": "Sei completamente ristabilito!",
    "church.heal_faith_wisdom": "La tua fede nella guarigione divina ti dona saggezza! (+{0} cavalleria)",
    "church.marriage_title": "=== CERIMONIE NUZIALI ===",
    "church.marriage_already": "Sei già sposato con {0}!",
    "church.marriage_no_perform": "La Chiesa non celebra cerimonie per chi è già sposato.",
    "church.marriage_bishop_smile": "{0} si avvicina con un sorriso caloroso.",
    "church.marriage_seeking": "\"Ah, cerchi la sacra unione del matrimonio!\"",
    "church.marriage_sacred": "\"Questa è una delle cerimonie più sacre della Chiesa.\"",
    "church.marriage_hearts_burn": "\"Per il matrimonio, entrambi i cuori devono ardere d'amore.\"",
    "church.marriage_consult": "\"Lascia che consulti gli spiriti e veda a che punto è il tuo cuore...\"",
    "church.marriage_closest": "  Le tue relazioni più strette:",
    "church.marriage_header_row": "  Nome                     Tu → Loro     Loro → Te",
    "church.marriage_nearly_ready": "\"Ah, {0} è quasi pronto! Continua a corteggiare a Via dell'Amore.\"",
    "church.marriage_passion_stirs": "\"La passione si agita, ma l'amore non è ancora sbocciato. Visita Via dell'Amore.\"",
    "church.marriage_need_nurturing": "\"Questi legami hanno bisogno di essere coltivati prima che suonino le campane nuziali.\"",
    "church.marriage_no_connections": "\"Non percepisco alcuna connessione romantica nel tuo cuore.\"",
    "church.marriage_how_to": "Come raggiungere il matrimonio:",
    "church.marriage_step1": "  1. Visita Via dell'Amore [X] — complimenti, bevute, appuntamenti e regali",
    "church.marriage_step2": "  2. Le scene intime approfondiscono i legami da entrambi i lati",
    "church.marriage_step3": "  3. Le pozioni d'amore al Negozio di Magia [M] danno una spinta",
    "church.marriage_step4": "  4. Sia tu CHE il tuo partner dovete raggiungere lo stato 'Innamorato'",
    "church.marriage_step_note": "  Nota: Parlare normalmente [0] costruisce solo fino all'Amicizia.",
    "church.marriage_those_who_would": "\"Vedo che ci sono coloro che ti sposerebbero:\"",
    "church.marriage_services": "Servizi per cerimonie nuziali:",
    "church.marriage_standard": "- Cerimonia standard: {0} {1}",
    "church.marriage_elaborate": "- Cerimonia elaborata: {0} {1}",
    "church.marriage_royal": "- Cerimonia reale: {0} {1}",
    "church.marriage_who_prompt": "Chi desideri sposare? (Inserisci numero o nome, o Q per annullare): ",
    "church.marriage_come_back": "\"Torna quando sarai pronto.\"",
    "church.marriage_not_among": "\"{0}\" non è tra coloro che ti sposerebbero.",
    "church.marriage_only_love": "Puoi sposare solo qualcuno che è innamorato di te.",
    "church.marriage_type_prompt": "Che tipo di cerimonia? (S)tandard, (E)laborata, (R)eale: ",
    "church.marriage_need_gold": "Ti servono {0} {1} per questa cerimonia.",
    "church.marriage_proceed": "Procedere con il matrimonio con {0} per {1} {2}? (S/N): ",
    "church.marriage_more_certain": "Forse quando sarai più sicuro.",
    "church.marriage_bishop_frowns": "{0} si acciglia e scuote la testa.",
    "church.wedding_title": "=== CERIMONIA NUZIALE ===",
    "church.wedding_begins": "{0} dà inizio alla sacra cerimonia...",
    "church.wedding_married": "Ora sei sposato con {0}!",
    "church.wedding_bells": "Le campane della Chiesa suonano in festa!",
    "church.wedding_chivalry": "La tua cavalleria aumenta di 10!",
    "church.wedding_charm": "Il tuo fascino aumenta di 5!",
    "church.wedding_children": "\"Che la vostra unione sia benedetta con figli!\"",
    "church.wedding_love_corner": "(Visita l'Angolo dell'Amore per momenti intimi)",
    "church.confess_leads": "{0} ti conduce in un confessionale privato.",
    "church.confess_speak": "\"Parla, figlio mio, e alleggerisci la tua anima.\"",
    "church.confess_pure": "\"La tua anima è pura, non hai bisogno di confessione.\"",
    "church.confess_righteous": "\"Va' e prosegui sul tuo cammino virtuoso.\"",
    "church.confess_darkness": "La tua oscurità attuale: {0}",
    "church.confess_reduce": "La confessione può ridurre la tua oscurità fino a {0} punti.",
    "church.confess_prompt": "Desideri confessare i tuoi peccati? (S/N): ",
    "church.confess_return": "\"Torna quando sarai pronto ad affrontare i tuoi peccati.\"",
    "church.confess_begin": "Inizi a confessare i tuoi peccati...",
    "church.confess_forgiven": "\"I tuoi peccati sono perdonati, figlio mio.\"",
    "church.confess_sin_no_more": "\"Va' e non peccare più.\"",
    "church.confess_darkness_decrease": "La tua oscurità diminuisce di {0} punti!",
    "church.confess_chivalry_increase": "La tua cavalleria aumenta di {0} punti!",
    "church.confess_cleansed": "Ti senti spiritualmente purificato!",
    "church.blood_pauses": "{0} si ferma. La sua espressione si fa cupa.",
    "church.blood_something_else": "\"Aspetta. C'è qualcos'altro. Qualcosa di più profondo.\"",
    "church.blood_sense_blood": "\"Percepisco sangue sulla tua anima. Non solo peccato. Morte.\"",
    "church.blood_cost": "\"L'assoluzione dal sangue richiede una donazione di {0} monete d'oro.\"",
    "church.blood_not_erase": "\"Non cancellerà ciò che hai fatto. Ma potrebbe alleggerire il peso.\"",
    "church.blood_murder_weight": "  Il tuo peso di sangue: {0}",
    "church.blood_absolution_cost": "  Costo dell'assoluzione: {0} oro",
    "church.blood_weight_reduced_by": "  Peso ridotto di: {0}",
    "church.blood_accept": "Accettare l'assoluzione dal sangue? (S/N): ",
    "church.blood_hands": "{0} posa le mani sul tuo capo.",
    "church.blood_shared": "\"Il sangue non si lava via. Ma il peso... il peso può essere condiviso.\"",
    "church.blood_reduced": "Peso di sangue ridotto di {0}! (Ora {1})",
    "church.blood_gold_cost": "(-{0} oro)",
    "church.blood_remains": "\"Il peso resta, allora. Torna quando sarai pronto.\"",
    "church.records_title": "Registri e Statistiche della Chiesa:",
    "church.records_history": "La Tua Storia con la Chiesa:",
    "church.records_donations": "- Donazioni totali effettuate: {0} {1}",
    "church.records_blessings": "- Benedizioni ricevute: {0}",
    "church.records_healings": "- Guarigioni ricevute: {0}",
    "church.records_chivalry": "- Cavalleria attuale: {0}",
    "church.records_darkness": "- Oscurità attuale: {0}",
    "church.records_alignment": "- Allineamento morale: {0}",
    "church.records_church_stats": "Statistiche della Chiesa:",
    "church.records_month_donations": "- Donazioni totali questo mese: {0} {1}",
    "church.records_month_marriages": "- Matrimoni celebrati questo mese: {0}",
    "church.records_month_blessings": "- Benedizioni concesse questo mese: {0}",
    "church.records_month_souls": "- Anime salvate dall'oscurità: {0}",
    "church.bishop_approaches": "{0} si avvicina con un'espressione serena.",
    "church.bishop_righteous": "\"Ah, un'anima davvero virtuosa si erge davanti a me!\"",
    "church.bishop_beacon": "\"Le tue buone azioni risplendono come un faro nell'oscurità.\"",
    "church.bishop_continue": "\"Prosegui sul tuo cammino di virtù, figlio mio.\"",
    "church.bishop_reward": "\"Come ricompensa per la tua rettitudine, accetta questa benedizione!\"",
    "church.bishop_blessing_days": "Ricevi una benedizione divina per 3 giorni!",
    "church.bishop_chivalry5": "La tua cavalleria aumenta di 5!",
    "church.bishop_darkness_sense": "\"Percepisco una grande oscurità nella tua anima, figlio mio.\"",
    "church.bishop_redemption": "\"Devi cercare la redenzione prima che sia troppo tardi.\"",
    "church.bishop_consider": "\"Considera di fare una donazione o acquistare una benedizione.\"",
    "church.bishop_insist": "\"Anzi, insisto che tu confessi immediatamente i tuoi peccati!\"",
    "church.bishop_force_confess": "Il Vescovo incoraggia fortemente la confessione. Confessarti ora? (S/N): ",
    "church.bishop_neutral1": "\"Benvenuto, figlio mio. La tua anima cammina sul confine tra luce e ombra.\"",
    "church.bishop_neutral2": "\"Scegli il tuo cammino con saggezza, poiché ogni azione plasma il tuo destino.\"",
    "church.bishop_neutral3": "\"La Chiesa è pronta a guidarti verso la rettitudine.\"",
    "church.bishop_wisdom_title": "Saggezza del Vescovo:",
    "church.bishop_wisdom1": "\"La carità fatta in segreto vale il doppio di quella fatta in pubblico.\"",
    "church.bishop_wisdom2": "\"Un cuore puro ha più valore di tutto l'oro del regno.\"",
    "church.bishop_wisdom3": "\"Chi aiuta gli altri troverà aiuto quando ne avrà più bisogno.\"",
    "church.bishop_wisdom4": "\"L'oscurità fugge dalla luce delle buone azioni.\"",
    "church.bishop_wisdom5": "\"La via della salvezza è lastricata di atti di gentilezza.\"",
    "church.align_saintly": "Santo",
    "church.align_very_good": "Molto Buono",
    "church.align_good": "Buono",
    "church.align_neutral": "Neutrale",
    "church.align_evil": "Malvagio",
    "church.align_very_evil": "Molto Malvagio",
    "church.align_demonic": "Demoniaco",
    "bank.deposit_gold": "DEPOSITA ORO",
    "bank.withdraw_gold": "PRELEVA ORO",
    "bank.transfer_gold": "TRASFERISCI ORO",
    "bank.interest_rates": "INTERESSI E TASSI",
    "bank.rate_schedule": "TABELLA TASSI BANCA FERROFORTE",
    "bank.account_summary": "RIEPILOGO CONTO",
    "bank.guard_duty": "CANDIDATURA GUARDIA",
    "healer.rehab_program": "Programma di Riabilitazione dalla Dipendenza",
    "bank.gold_on_hand": "Oro Disponibile:  ",
    "bank.gold_in_bank": "Oro in Banca:     ",
    "bank.total_worth": "Patrimonio Totale:",
    "bank.guard_active": "Stato Guardia:    ATTIVO (Paga: {0}/giorno)",
    "bank.loan_status": "Prestito in Sospeso: {0} oro (interesse giornaliero 5%!)",
    "bank.deposit_no_gold": "Non hai oro da depositare.",
    "bank.deposit_amount": "Oro disponibile: {0}",
    "bank.deposit_balance": "Saldo bancario attuale: {0}",
    "bank.deposit_prompt": "Inserisci l'importo (o 'all' per tutto, 0 per annullare):",
    "bank.transaction_cancelled": "Transazione annullata.",
    "bank.deposit_more_than_have": "Non puoi depositare più di quanto possiedi!",
    "bank.deposit_success": "Depositi {0} monete d'oro.",
    "bank.new_balance": "Nuovo saldo bancario: {0} oro",
    "bank.withdraw_empty": "Il tuo conto è vuoto.",
    "bank.withdraw_amount": "Saldo bancario: {0}",
    "bank.withdraw_prompt": "Inserisci l'importo (o 'all' per tutto, 0 per annullare):",
    "bank.withdraw_not_enough": "Non hai tutto quell'oro nel tuo conto.",
    "bank.remaining_balance": "Saldo bancario rimanente: {0} oro",
    "bank.transfer_no_gold": "Devi avere oro nel tuo conto per effettuare un trasferimento.",
    "bank.transfer_to": "Trasferisci a: {0}",
    "bank.transfer_your_balance": "Il tuo saldo: {0}",
    "bank.transfer_amount_prompt": "Inserisci l'importo da trasferire:",
    "bank.transfer_insufficient": "Fondi insufficienti.",
    "bank.transfer_complete": "Trasferimento completato! {0} oro inviato a {1}.",
    "bank.transfer_cancelled": "Trasferimento annullato.",
    "bank.account_holders": "Titolari di conto conosciuti:",
    "bank.select_recipient": "Inserisci numero destinatario (o nome), 0 per annullare:",
    "bank.account_not_found": "Non riesco a trovare quel titolare di conto.",
    "bank.loan_outstanding": "Prestito in sospeso: {0} oro (interesse giornaliero 5%!)",
    "bank.loan_repay_full": "Rimborsa l'intero importo",
    "bank.loan_repay_partial": "Rimborso parziale",
    "bank.loan_not_now": "Non ora",
    "bank.loan_repaid": "Prestito completamente rimborsato! Il tuo credito è ristabilito.",
    "bank.loan_repay_prompt": "Inserisci l'importo del rimborso:",
    "bank.loan_partial_repaid": "Hai rimborsato {0} oro. Prestito rimanente: {1}",
    "bank.loan_offer": "In base al tuo livello ({0}), posso offrirti fino a {1} oro.",
    "bank.loan_warning": "ATTENZIONE: I prestiti maturano interessi giornalieri del 5%!",
    "bank.loan_consequences": "IL MANCATO RIMBORSO COMPORTERÀ:",
    "bank.loan_seize": "  - Sequestro automatico dei depositi bancari",
    "bank.loan_collectors": "  - Esattori che verranno a trovarti (non sono gentili)",
    "bank.loan_darkness": "  - Aumento della tua Oscurità e del livello di Ricercato",
    "bank.loan_banned": "  - Espulsione definitiva dalla banca",
    "bank.loan_amount_prompt": "Inserisci l'importo del prestito (0 per annullare):",
    "bank.loan_approved": "Prestito approvato! {0} oro è stato aggiunto alla tua borsa.",
    "bank.loan_remember": "Ricorda: interesse giornaliero del 5%. Non costringerci a mandare gli esattori...",
    "bank.interest_savings": "Interessi sui Risparmi:",
    "bank.interest_savings_rate": "  Tasso giornaliero: 0,1% su tutti i depositi",
    "bank.interest_savings_calc": "  Gli interessi vengono calcolati e aggiunti ogni giorno a mezzanotte.",
    "bank.interest_loan": "Interessi sul Prestito:",
    "bank.interest_loan_rate": "  Tasso giornaliero: 5% sul saldo in sospeso",
    "bank.interest_loan_compound": "  Gli interessi si accumulano giornalmente. Rimborsa prontamente!",
    "bank.guard_wages_title": "Paga della Guardia:",
    "bank.guard_wages_base": "  Base: 1.000 oro/giorno",
    "bank.guard_wages_hazard": "  Indennità di rischio: Varia in base ai tentativi di rapina",
    "bank.guard_position": "DETTAGLI POSIZIONE DI GUARDIA:",
    "bank.guard_wage_detail": "  Paga giornaliera: {0} oro",
    "bank.guard_duties": "  Compiti: Proteggere la banca dai tentativi di rapina",
    "bank.guard_risk": "  Rischio: Potresti essere chiamato a combattere criminali pericolosi",
    "bank.guard_accept": "Accetti questa posizione? (S/N)",
    "bank.guard_hired": "Congratulazioni! Ora sei una Guardia della Banca!",
    "bank.guard_public_prompt": "Rendere pubblica la tua assunzione? (S/N)",
    "bank.guard_public_note": "(Potrebbe scoraggiare i criminali... o renderti un bersaglio)",
    "bank.guard_not_employed": "Al momento non sei impiegato come guardia della banca.",
    "bank.guard_resign_confirm": "Confermi le dimissioni? (S/N)",
    "bank.guard_wage_current": "Paga attuale: {0} oro/giorno",
    "bank.guard_resigned": "Ti sei dimesso dal servizio di guardia.",
    "bank.guard_stay": "Decidi di restare guardia.",
    "bank.rob_guard_conflict": "Non puoi rapinare la banca che hai giurato di proteggere!",
    "bank.rob_exhausted": "Hai esaurito i tuoi tentativi di rapina per oggi.",
    "bank.rob_survey": "Studi le difese della banca...",
    "bank.rob_safe": "  Contenuto della Cassaforte: ~{0} oro (potresti rubarne il 25%)",
    "bank.rob_guards": "  Guardie della Banca: {0} professionisti armati",
    "bank.rob_player_guards": "  Guardie Avventuriere: {0} avventurieri in servizio",
    "bank.rob_alarm": "  Sistema d'Allarme: Rune naniche (molto rumorose)",
    "bank.rob_warning": "ATTENZIONE: La rapina CAUSERÀ:",
    "bank.rob_chivalry": "  - La tua Cavalleria verrà azzerata",
    "bank.rob_dark": "  - Aumento significativo della tua Oscurità",
    "bank.rob_wanted": "  - Sarai RICERCATO dalle autorità",
    "bank.rob_death": "  - Possibile morte",
    "bank.rob_confirm": "Sei ASSOLUTAMENTE SICURO? Scrivi 'ROB' per confermare:",
    "bank.rob_cold_feet": "Ti trema la mano? Scelta saggia.",
    "bank.rob_leave": "Lasci silenziosamente la banca. Certi crimini non valgono il rischio.",
    "bank.rob_success": "SUCCESSO! Hai rubato {0} monete d'oro!",
    "bank.rob_flee": "Afferri manciate d'oro e fuggi nella notte!",
    "bank.rob_authorities": "Le autorità ti cercheranno...",
    "bank.rob_beaten": "Vieni picchiato fino a perdere i sensi e trascinato nel rigagnolo.",
    "bank.rob_confiscate": "Le guardie confiscano {0} monete d'oro come 'risarcimento danni'.",
    "bank.rob_fled_empty": "Fuggi dalla banca a mani vuote!",
    "bank.rob_face_seen": "Almeno sei vivo... ma le guardie ti hanno visto bene in faccia.",
    "bank.account_status_debt": "INDEBITATO",
    "bank.account_status_good": "In Regola",
    "bank.financial_overview": "Panoramica Finanziaria:",
    "bank.loan_details": "Dettagli Prestito:",
    "bank.account_statistics": "Statistiche del Conto:",
    "bank.guard_employment": "Impiego come Guardia:",
    "bank.account_since": "\"Il tuo conto è stato con noi fin dall'inizio,\" nota {0}.",
    "bank.guard_already": "{0} sorride. \"Sei già una delle nostre migliori guardie!\"",
    "bank.guard_current_wage": "\"La tua paga attuale è {0} oro al giorno.\"",
    "bank.guard_level_req_head": "{0} scuote la testa.",
    "bank.guard_level_req": "\"Mi dispiace, ma richiediamo che le guardie siano almeno di livello {0}.\"",
    "bank.guard_level_req_come_back": "\"Torna quando avrai più esperienza.\"",
    "bank.guard_darkness_head": "{0} ti osserva con sospetto.",
    "bank.guard_darkness_check": "\"Il nostro controllo dei precedenti rivela... informazioni preoccupanti sulle tue attività.\"",
    "bank.guard_darkness_deny": "\"Non possiamo assumere qualcuno con una reputazione così oscura.\"",
    "bank.guard_reviews": "{0} esamina attentamente le tue credenziali.",
    "bank.guard_position_title": "DETTAGLI POSIZIONE DI GUARDIA:",
    "bank.guard_daily_wage": "  Paga giornaliera: {0} oro",
    "bank.guard_accept_prompt": "Accetti questa posizione? (S/N)",
    "bank.guard_handshake": "{0} ti stringe la mano con fermezza.",
    "bank.guard_welcome": "\"Benvenuto nella squadra! La tua paga sarà depositata giornalmente.\"",
    "bank.guard_sharp": "\"Tieni la tua arma pronta e gli occhi vigili!\"",
    "bank.guard_public_hint": "(Potrebbe scoraggiare i criminali... o renderti un bersaglio)",
    "bank.guard_another_time": "{0} annuisce con comprensione. \"Forse un'altra volta.\"",
    "bank.resign_not_employed": "Al momento non sei impiegato come guardia della banca.",
    "bank.resign_disappointed": "{0} sembra deluso.",
    "bank.resign_certain": "\"Sei sicuro di volerti dimettere? Il tuo servizio è stato prezioso.\"",
    "bank.resign_wage_current": "Paga attuale: {0} oro/giorno",
    "bank.resign_confirm": "Confermi le dimissioni? (S/N)",
    "bank.resign_done": "Ti sei dimesso dal servizio di guardia.",
    "bank.resign_thanked": "{0} sospira. \"Va bene. Grazie per il tuo servizio.\"",
    "bank.resign_remain": "Decidi di restare guardia.",
    "bank.rob_guard_conflict2": "Sarebbe una grave violazione del contratto... e dell'etica.",
    "bank.rob_exhausted2": "Le guardie sono troppo all'erta dopo il tuo tentativo precedente.",
    "bank.rob_safe_contents": "  Contenuto della Cassaforte: ~{0} oro (potresti rubarne il 25%)",
    "bank.rob_bank_guards": "  Guardie della Banca: {0} professionisti armati",
    "bank.rob_warning_title": "ATTENZIONE: La rapina CAUSERÀ:",
    "bank.rob_darkness": "  - Aumento significativo della tua Oscurità",
    "bank.rob_options": "Opzioni:",
    "bank.rob_option_rob": "Rapina la banca (COMMETTI IL CRIMINE)",
    "bank.rob_option_inspect": "Ispeziona prima le guardie",
    "bank.rob_option_abort": "Abbandona - è una follia",
    "bank.rob_enemies_rush": "{0} nemici si precipitano a fermarti!",
    "bank.rob_draw_weapon": "Sguaini la tua arma e carichi verso il caveau!",
    "bank.rob_banker_screams": "{0} urla e si tuffa sotto la scrivania!",
    "bank.rob_alarms": "GLI ALLARMI RISUONANO in tutta la banca!",
    "bank.rob_vault_remaining": "Il caveau della banca ora contiene {0} oro.",
    "bank.rob_confiscate_bank": "({0} sequestrato dal tuo conto bancario)",
    "bank.inspect_observe": "Osservi disinvoltamente le guardie...",
    "bank.inspect_captain": "  Capitano della Guardia - Spadone e Cotta di Maglia",
    "bank.inspect_captain_desc": "    (Sembra temprato dalla battaglia e pericoloso)",
    "bank.inspect_guard": "  Guardia #{0} - Alabarda e Giaco",
    "bank.inspect_dog": "  Cane da Guardia - Pitbull Feroce",
    "bank.inspect_dog_desc": "    (Tira il guinzaglio, fissandoti con fame)",
    "bank.inspect_adventurers": "Guardie Avventuriere in Servizio:",
    "bank.robbery_banner_top": "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "bank.robbery_banner_mid": "!                         RAPINA IN CORSO!                                  !",
    "bank.banned_guards_block": "Mentre ti avvicini alle porte della banca, due enormi guardie ti sbarrano il passo.",
    "bank.banned_recognized": "\"TU!\" ringhia uno di loro, riconoscendoti all'istante.",
    "bank.banned_owed": "\"Devi alla Banca Ferroforte oltre {0} monete d'oro!\"",
    "bank.banned_message": "\"Sei ESPULSO da questo istituto finché non salderai il tuo debito.\"",
    "bank.banned_consequences": "\"L'unico modo per entrare è ripagare ciò che devi... o affrontare le conseguenze.\"",
    "bank.banned_knuckles": "Le guardie si fanno scrocchiare le nocche minacciosamente.",
    "bank.banned_leave": "Vai via (l'unica opzione)",
    "bank.desc_enter": "Varchi le massicce porte di bronzo della Banca Ferroforte, il più",
    "bank.desc_enter2": "antico e sicuro istituto finanziario del reame. I pavimenti di marmo",
    "bank.desc_enter3": "brillano sotto lampadari di cristallo incantati che non tremolano mai.",
    "bank.desc_vault": "Enormi porte del caveau forgiate dai nani dominano la parete di fondo, incise con",
    "bank.desc_vault2": "antiche rune di protezione. Guardie armate stanno sull'attenti, con gli",
    "bank.desc_vault3": "occhi che scrutano costantemente alla ricerca di pericoli.",
    "bank.desc_banker_intro": "Dietro un ornato bancone di mogano, ",
    "bank.desc_banker_name": "{0}",
    "bank.desc_banker_title": " il banchiere gnomo",
    "bank.desc_banker_desc": "sistema i suoi occhiali dorati e ti scruta con occhi sagaci.",
    "bank.desc_banker_desc2": "Nonostante la sua piccola statura, emana un'aura di assoluta autorità",
    "bank.desc_banker_desc3": "su tutte le questioni finanziarie.",
    "bank.desc_vault_estimate": "[Stimi che il caveau contenga circa {0} monete d'oro...]",
    "bank.sr_title": "LA BANCA FERROFORTE",
    "bank.sr_tagline": "Dove la Vostra Fortuna è la Nostra Fondazione",
    "bank.sr_guard_status": "Stato Guardia: ATTIVO, Paga: {0} al giorno",
    "bank.sr_loan_status": "Prestito in Sospeso: {0} oro, interesse giornaliero 5%",
    "bank.sr_banking_services": "Servizi Bancari:",
    "church.bbs_donate": "Donazione",
    "church.bbs_blessing": "Benedizione",
    "church.bbs_heal": "Guarigione",
    "church.bbs_marriage": "Matrimonio",
    "church.bbs_confess": "Confessione",
    "church.bbs_records": "Registri",
    "church.bbs_bishop": "Vescovo",
    "church.bbs_return": "Ritorna",
    "church.service_health": "guarigione",
    "church.service_blindness": "cura cecità",
    "church.service_plague": "cura peste",
    "church.service_smallpox": "cura vaiolo",
    "church.service_measles": "cura morbillo",
    "church.service_leprosy": "cura lebbra",
    "church.service_complete": "guarigione completa",
}
