translations = {
    "combat.header": "COMBATTIMENTO",
    "combat.encounter": "Un {0} appare!",
    "combat.encounter_multi": "{0} mostri appaiono!",
    "combat.attack": "Attacca",
    "combat.cast_spell": "Lancia Incantesimo",
    "combat.use_ability": "Usa Abilità",
    "combat.defend": "Difendi",
    "combat.flee": "Fuggi",
    "combat.use_item": "Usa Oggetto",
    "combat.use_herb": "Usa Erba",
    "combat.taunt": "Provoca",
    "combat.hide": "Nasconditi",
    "combat.power_attack": "Attacco Potente",
    "combat.precise_strike": "Colpo Preciso",
    "combat.disarm": "Disarma",
    "combat.aid_ally": "Aiuta Alleato",
    "combat.you_attack": "Attacchi {0}!",
    "combat.you_hit": "Colpisci {0} per {1} danni!",
    "combat.you_miss": "Manchi {0}!",
    "combat.you_critical": "COLPO CRITICO! Colpisci {0} per {1} danni!",
    "combat.you_kill": "Hai sconfitto {0}!",
    "combat.monster_attacks": "{0} ti attacca!",
    "combat.monster_hits": "{0} ti colpisce per {1} danni!",
    "combat.monster_misses": "{0} ti manca!",
    "combat.monster_critical": "{0} mette a segno un COLPO CRITICO per {1} danni!",
    "combat.you_dodge": "Schivi l'attacco di {0}!",
    "combat.you_block": "Blocchi l'attacco di {0} con il tuo scudo!",
    "combat.you_flee": "Fuggi dal combattimento!",
    "combat.flee_fail": "Non riesci a fuggire!",
    "combat.you_died": "Sei stato sconfitto!",
    "combat.companion_attacks": "{0} attacca {1}!",
    "combat.companion_hits": "{0} colpisce {1} per {2} danni!",
    "combat.companion_dodges": "{0} schiva agilmente l'attacco di {1}!",
    "combat.monster_attacks_companion": "{0} attacca {1}!",
    "combat.monster_hits_companion": "{0} colpisce {1} per {2} danni!",
    "combat.victory": "VITTORIA!",
    "combat.xp_gained": "Hai guadagnato {0} esperienza!",
    "combat.gold_gained": "Hai trovato {0} monete d'oro!",
    "combat.loot_found": "Hai trovato: {0}!",
    "combat.level_up": "LIVELLO SUPERIORE! Sei ora al livello {0}!",
    "combat.defend_action": "Ti prepari per il prossimo attacco.",
    "combat.power_attack_action": "Sferra un colpo devastante!",
    "combat.precise_strike_action": "Miri con precisione!",
    "combat.backstab_action": "Colpisci dalle ombre!",
    "combat.afflicted_with": "Sei afflitto da {0}!",
    "combat.armor_absorbed": "L'armatura di {0} ha assorbito {1} punti!",
    "combat.armor_absorbed_pierced": "L'armatura di {0} ha assorbito {1} punti! (Perforata {2}%)",
    "combat.critical_hit": "COLPO CRITICO!",
    "combat.devastating_blow": "Colpo devastante!",
    "combat.divine_fury": "La furia divina guida il tuo colpo!",
    "combat.divine_light_turns_death": "La luce divina ti avvolge, allontanando la morte!",
    "combat.divine_protection_absorbs": "La protezione divina assorbe {0} danni!",
    "combat.dark_power_drain": "Il potere oscuro risucchia {0} vita dal tuo nemico!",
    "combat.enchant_fire": "Le fiamme erompono dalla tua arma! {0} danni da fuoco! (Fuoco della Fenice)",
    "combat.enchant_frost": "Il gelo si propaga dall'impatto! Difesa di {0} ridotta! (Morso del Gelo)",
    "combat.enchant_holy": "La luce divina colpisce nel segno! {0} danni sacri! (Radiosità)",
    "combat.enchant_holy_undead": "La luce sacra brucia il non-morto! {0} danni radianti! (Punizione)",
    "combat.enchant_lightning_resist": "Un fulmine scaturisce dal tuo colpo! {0} danni da scarica! {1} resiste allo stordimento! (Folgore)",
    "combat.enchant_lightning_stun": "Un fulmine scaturisce dal tuo colpo! {0} danni da scarica! {1} è stordito! (Folgore)",
    "combat.enchant_shadow": "Le ombre si avvolgono sulla lama! {0} danni d'ombra! (Colpo Oscuro)",
    "combat.enchant_siphon": "La tua arma risucchia {0} mana! (Risucchio)",
    "combat.enchant_venom": "Il veleno penetra nella ferita! {0} danni da veleno! (Colpo Velenoso)",
    "combat.gnoll_bite_poison": "Il tuo morso velenoso avvelena {0}!",
    "combat.god_intervenes": "{0} interviene!",
    "combat.boon_drain": "Il potere divino risucchia {0} vita! (Benedizione)",
    "combat.lifedrinker": "La tua arma risucchia {0} vita! (Bevitore di Vita)",
    "combat.sunforged_heal": "La luce radiante guarisce {0} di {1} PV!",
    "combat.invulnerable_block": "L'attacco non può penetrare il tuo scudo divino!",
    "combat.iron_will_resists": "La tua volontà di ferro resiste a {0}!",
    "combat.mark_fades": "Il marchio su {0} svanisce.",
    "combat.monster_charmed": "{0} esita, ammaliato dalla tua presenza!",
    "combat.monster_shakes_fear": "{0} scuote via la paura!",
    "combat.monster_sluggish": "{0} si muove con lentezza e spreca il suo turno!",
    "combat.monster_wakes": "{0} si sveglia!",
    "combat.off_hand_strike": "Colpo con la mano secondaria!",
    "combat.poison_tick": "{0} subisce {1} danni da veleno!",
    "combat.potion_mastery": "La Maestria nelle Pozioni potenzia l'effetto!",
    "combat.potions_count": "Hai {0} pozioni curative.",
    "combat.potions_how_many": "Quante pozioni? (1-{0}, F=tutte, Invio=1): ",
    "combat.potions_missing_hp": "Mancano {0} PV. (~{1} pozioni per il massimo)",
    "combat.potions_used_heal": "Usi {0} pozione/i e recuperi {1} PV!",
    "combat.precision_strike_crit": "Colpo di precisione! ({0}% probabilità critico)",
    "combat.quick_heal_potion": "Trangugi rapidamente una pozione curativa per {0} PV!",
    "combat.scales_destroy": "{0} viene distrutto dalla giustizia karmica!",
    "combat.scales_reflect": "La Bilancia della Legge riflette {0} danni su {1}!",
    "combat.shadow_dodge": "Scivoli tra le ombre, eludendo l'attacco di {0}!",
    "combat.shield_absorbs": "Il tuo scudo assorbe {0} danni!",
    "combat.shield_absorbs_most": "Il tuo scudo assorbe la maggior parte del colpo! Subisci solo {0} danni!",
    "combat.solid_hit": "Colpo solido!",
    "combat.thorns_kill": "{0} cade sotto le tue spine!",
    "combat.thorns_reflect": "Le spine riflettono {0} danni su {1}! (Ritorsione)",
    "combat.worldstone_absorbs": "La Pietra del Mondo assorbe l'impatto! (-{0})",
    "combat.you_take_damage": "Subisci {0} danni!",
    "combat.you_take_damage_heals": "Subisci {0} danni! {1} guarisce {2}!",
    "combat.blur_miss": "L'attacco colpisce solo immagini illusorie!",
    "combat.boss_confused": "{0} esita, confuso da contraddizioni interne!",
    "combat.brace_for_impact": "Ti prepari all'impatto e subisci solo {0} danni!",
    "combat.burn_tick": "{0} subisce {1} danni da ustione!",
    "combat.drug_drain": "[Effetto Collaterale Droga] Le droghe ti sottraggono {0} PV!",
    "combat.facing": "Stai affrontando: {0}",
    "combat.fatigue_exhaustion": "(Lo sfinimento grava pesantemente su di te)",
    "combat.fighting_alongside": "Combattono al tuo fianco:",
    "combat.monster_says": "{0} dice: \"{1}\"",
    "combat.monster_uses_ability": "{0} usa {1}!",
    "combat.npc_status_prevented": "{0} è {1}!",
    "combat.poison_courses": "Il veleno scorre nelle tue vene! (-{0} PV)",
    "combat.pvp_action_unavailable": "Quell'azione non è disponibile nel combattimento PvP.",
    "combat.speed_set_to": "Velocità di combattimento impostata a: {0}",
    "combat.stunned": "{0} è stordito e non può agire!",
    "combat.teammate_entry": "  - {0} (Livello {1})",
    "combat.troll_regen": "[Rigenerazione Troll] Rigeneri {0} PV!",
    "combat.you_status_prevented": "Sei {0} e non puoi agire!",
    "combat.backstab_fail_noticed": "Il tuo bersaglio ti nota! Pugnalata alle spalle fallita!",
    "combat.backstab_shadows": "Scivoli nelle ombre dietro {0}...",
    "combat.critical_backstab": "PUGNALATA CRITICA ALLE SPALLE!",
    "combat.disarm_attempt": "Tenti di disarmare {0}!",
    "combat.disarm_success": "Fai saltare l'arma! {0} perde il bonus dell'arma!",
    "combat.hide_bonus": "Nasconderti ti dà un vantaggio in combattimento!",
    "combat.need_bow": "Ti serve un Arco equipaggiato per usare l'Attacco a Distanza!",
    "combat.not_enough_stamina": "Vigore insufficiente! (Necessario {0}, hai {1})",
    "combat.off_hand_strike_at": "Colpo con la mano secondaria su {0}!",
    "combat.power_attack_hit": "L'ATTACCO POTENTE colpisce {0} per {1} danni!",
    "combat.power_attack_windup": "Carichi un colpo devastante...",
    "combat.precise_strike_aim": "Miri con attenzione al punto debole di {0}...",
    "combat.precise_strike_hit": "Il colpo preciso colpisce {0} per {1} danni!",
    "combat.rage_effect": "FURIA! Danni aumentati in questo turno!",
    "combat.ranged_fire": "Tiri con il tuo {0}!",
    "combat.ranged_hit": "La freccia colpisce {0} per {1} danni!",
    "combat.smite_channel": "Incanali il potere divino nel tuo colpo!",
    "combat.smite_damage": "La punizione sacra infligge {0} danni a {1}!",
    "combat.soul_strike_channel": "Incanali il potere delle anime consumate...",
    "combat.soul_strike_damage": "Il colpo dell'anima infligge {0} danni a {1}!",
    "combat.taunt_enraged": "{0} si infuria e si concentra su di te!",
    "combat.taunt_target": "Provochi {0}, abbassando la sua difesa!",
    "combat.auto_heal_potions": "Bevi {0} pozione/i e recuperi {1:N0} PV. ({2}/{3} PV, {4} pozioni rimaste)",
    "combat.auto_mana_potions": "Bevi {0} pozione/i di mana e recuperi {1:N0} PM. ({2}/{3} PM, {4} pozioni di mana rimaste)",
    "combat.enchant_fire_multi": "  Le fiamme erompono! {0} danni da fuoco a {1}! (Fuoco della Fenice)",
    "combat.enchant_frost_multi": "  Il gelo si propaga! Difesa di {0} ridotta! (Morso del Gelo)",
    "combat.enchant_holy_multi": "  Colpo divino! {0} danni sacri a {1}! (Radiosità)",
    "combat.enchant_holy_undead_multi": "  La luce sacra brucia! {0} danni radianti a {1}! (Punizione)",
    "combat.enchant_lightning_resist_multi": "  Un fulmine scaturisce! {0} danni da scarica a {1}! Resiste allo stordimento! (Folgore)",
    "combat.enchant_lightning_stun_multi": "  Un fulmine scaturisce! {0} danni da scarica a {1}! Stordito! (Folgore)",
    "combat.enchant_shadow_multi": "  Le ombre si avvolgono! {0} danni d'ombra a {1}! (Colpo Oscuro)",
    "combat.enchant_siphon_multi": "  L'arma risucchia {0} mana! (Risucchio)",
    "combat.enchant_venom_multi": "  Il veleno penetra! {0} danni da veleno a {1}! (Colpo Velenoso)",
    "combat.loot_ability_req_block": "  Equipaggiare questo {0} nella mano principale le disabiliterà.",
    "combat.loot_ability_req_warning": "  NOTA: Alcune delle tue abilità richiedono un {0}.",
    "combat.loot_added_inventory": "{0} aggiunto all'inventario.",
    "combat.loot_ally_picks_up": "{0} raccoglie {1} — un miglioramento del {2}%!",
    "combat.loot_armor_power": "  Potenza Armatura: +{0}",
    "combat.loot_attack_power": "  Potenza Attacco: +{0}",
    "combat.loot_boss_drop": "Il Boss lascia cadere equipaggiamento potente!",
    "combat.loot_cannot_equip": "  Non puoi equipaggiare questo oggetto. {0}",
    "combat.loot_champion_drop": "Il Campione lascia cadere equipaggiamento prezioso!",
    "combat.loot_cursed_hint": "  Visita il Negozio di Magia per rimuovere la maledizione.",
    "combat.loot_cursed_warning": "  ATTENZIONE: Questo oggetto è MALEDETTO!",
    "combat.loot_drop_from": "  ── BOTTINO da {0} ──",
    "combat.loot_drop_from_sr": "  BOTTINO da {0}:",
    "combat.loot_epic_drop": "      ** BOTTINO EPICO! **",
    "combat.loot_equip_failed": "Impossibile equipaggiare: {0}",
    "combat.loot_equip_failed_inventory": "Impossibile equipaggiare: {0}. Aggiunto all'inventario.",
    "combat.loot_equip_option": "(E)quipaggia subito",
    "combat.loot_found_on_corpse": "L'hai trovato sul cadavere del {0}.",
    "combat.loot_identify_hint": "  Portalo al Negozio di Magia per farlo identificare.",
    "combat.loot_invalid_choice": "Scelta non valida '{0}'. Inserisci E, T o P.",
    "combat.loot_invalid_passing": "Scelta non valida — si passa oltre.",
    "combat.loot_invalid_taking": "Scelta non valida '{0}' — oggetto preso nell'inventario.",
    "combat.loot_item_found": "       OGGETTO TROVATO!",
    "combat.loot_left_behind": "L'oggetto viene lasciato indietro.",
    "combat.loot_legendary_drop": "*** BOTTINO LEGGENDARIO! ***",
    "combat.loot_offered_to": "  Bottino offerto a {0} (a rotazione)...",
    "combat.loot_pass_option": "(P)assa",
    "combat.loot_rare_drop": "     * BOTTINO RARO! *",
    "combat.loot_spell_req_block": "  Equipaggiare questo {0} impedirà il lancio di incantesimi.",
    "combat.loot_spell_req_warning": "  NOTA: I tuoi incantesimi di {0} richiedono un {1}.",
    "combat.loot_take_option": "(T)ieni nell'inventario",
    "combat.loot_teammate_equips": "  {0} equipaggia {1}!",
    "combat.loot_teammate_passes": "  {0} passa su {1}.",
    "combat.loot_teammate_takes": "  {0} prende {1}.",
    "combat.loot_timed_out": "(Tempo scaduto — si passa oltre)",
    "combat.loot_timed_out_taken": "(Tempo scaduto — oggetto preso nell'inventario)",
    "combat.loot_type": "  Tipo: {0}",
    "combat.loot_type_necklace": "Collana",
    "combat.loot_type_ring": "Anello",
    "combat.loot_unidentified": "  Le proprietà dell'oggetto sono sconosciute.",
    "combat.loot_unidentified_item": "un oggetto non identificato",
    "combat.loot_value": "  Valore: {0} oro",
    "combat.loot_won_roll": "Hai vinto il tiro per il bottino di {0}!",
    "combat.loot_you_pass": "Passi sull'oggetto.",
    "combat.soulweaver_heal": "Il Telaio dell'Anima ricuce le tue ferite... (+{0} PV)",
    "combat.ability_aoe_all": "L'attacco colpisce tutti i nemici!",
    "combat.ability_aoe_confusion": "Il caos lascia i nemici sopravvissuti disorientati!",
    "combat.ability_aoe_holy": "Il giudizio divino si abbatte su tutti i nemici!",
    "combat.ability_armor_pierce": "L'attacco ignora l'armatura!",
    "combat.ability_attack_up": "Attacco aumentato di {1} per {2} turni!",
    "combat.ability_attack_up_npc": "L'attacco di {0} aumentato di {1} per {2} turni!",
    "combat.ability_berserker_rage": "FURIA BERSERKER! Entri in un'ira sanguinaria!",
    "combat.ability_berserker_rage_npc": "FURIA BERSERKER! {0} entra in un'ira sanguinaria!",
    "combat.ability_champion_heal": "Lo spirito del Campione ti guarisce di {1} PV!",
    "combat.ability_champion_heal_npc": "Lo spirito del Campione guarisce {0} di {1} PV!",
    "combat.ability_champion_strike": "Un colpo degno delle leggende!",
    "combat.ability_charmed": "{0} è ammaliato e potrebbe esitare ad attaccare!",
    "combat.ability_cooldown": "{0} è in ricarica per altri {1} turni!",
    "combat.ability_cooldown_set": "  ({0} ricarica: {1} turni)",
    "combat.ability_critical": "ABILITÀ CRITICA!",
    "combat.ability_defense_down": "Difesa ridotta di {1} (furia)!",
    "combat.ability_defense_down_npc": "Difesa di {0} ridotta di {1} (furia)!",
    "combat.ability_defense_up": "Difesa aumentata di {1} per {2} turni!",
    "combat.ability_defense_up_npc": "Difesa di {0} aumentata di {1} per {2} turni!",
    "combat.ability_desperation": "DISPERAZIONE! {0} danni bonus!",
    "combat.ability_divine_heal": "L'energia divina ti guarisce di {1} PV!",
    "combat.ability_divine_heal_npc": "L'energia divina guarisce {0} di {1} PV!",
    "combat.ability_divine_radiate": "L'energia divina irradia dalla tua arma!",
    "combat.ability_divine_radiate_npc": "L'energia divina irradia dall'arma di {0}!",
    "combat.ability_divine_vengeance": "VENDETTA DIVINA! +{0} danni sacri!",
    "combat.ability_dodge_next": "Ti prepari a schivare il prossimo attacco!",
    "combat.ability_dodge_next_npc": "{0} si prepara a schivare il prossimo attacco!",
    "combat.ability_escape": "Svanisci in una nuvola di fumo!",
    "combat.ability_escape_npc": "{0} svanisce in una nuvola di fumo!",
    "combat.ability_execute": "ESECUZIONE! Danni doppi contro il nemico ferito!",
    "combat.ability_fire_bonus": "Il fuoco arde con intensità! {0} danni bonus!",
    "combat.ability_fire_explode": "La bomba esplode in un'ondata di fiamme!",
    "combat.ability_fury": "LA FURIA DEL DIO DELLA GUERRA ARDE IN TE!",
    "combat.ability_fury_npc": "LA FURIA DEL DIO DELLA GUERRA ARDE IN {0}!",
    "combat.ability_holy_smite": "PUNIZIONE SACRA! Il non-morto brucia nel fuoco divino! +{0} danni!",
    "combat.ability_inspire_allies": "I tuoi alleati sono ispirati! (+15 Attacco per 3 turni)",
    "combat.ability_inspire_allies_npc": "La melodia di {0} ispira il gruppo! (+15 Attacco per 3 turni)",
    "combat.ability_inspire_self": "La melodia rafforza la tua determinazione! (+10 Attacco per 3 turni)",
    "combat.ability_inspire_self_npc": "La melodia rafforza la determinazione di {0}! (+10 Attacco per 3 turni)",
    "combat.ability_last_stand": "ULTIMA RESISTENZA! La disperazione alimenta il tuo attacco!",
    "combat.ability_last_stand_npc": "ULTIMA RESISTENZA! La disperazione alimenta l'attacco di {0}!",
    "combat.ability_npc_deals_damage": "{0} infligge {1} danni a {2}!",
    "combat.ability_npc_recovers": "{0} recupera {1} PV!",
    "combat.ability_poisoned": "{0} è avvelenato!",
    "combat.ability_proficiency_up": "  La tua competenza in {0} è migliorata a {1}!",
    "combat.ability_purified": "{0} è purificato!",
    "combat.ability_reckless": "Colpo avventato! Ti esponi al contrattacco!",
    "combat.ability_reckless_npc": "Colpo avventato! {0} si espone al contrattacco!",
    "combat.ability_resist_all": "La tua volontà diventa indistruttibile! Gli effetti di stato non possono toccarti!",
    "combat.ability_resist_all_npc": "La volontà di {0} diventa indistruttibile! Gli effetti di stato non possono toccarlo!",
    "combat.ability_shadow_crit": "Colpo critico dalle ombre!",
    "combat.ability_smoke": "Una nube di fumo ti nasconde dagli attacchi!",
    "combat.ability_smoke_npc": "Una nube di fumo nasconde {0} dagli attacchi!",
    "combat.ability_stamina": "  (Vigore: {0}/{1})",
    "combat.ability_stun_resist": "{0} resiste allo stordimento!",
    "combat.ability_stunned": "{0} è stordito!",
    "combat.ability_target_slain": "{0} è stato ucciso!",
    "combat.ability_use": "» {0} usa {1}! (-{2} vigore)",
    "combat.ability_vital_strike": "Colpisci un punto vitale!",
    "combat.ability_vital_strike_npc": "{0} colpisce un punto vitale!",
    "combat.ability_you_deal_damage": "Infliggi {1} danni a {2}!",
    "combat.ability_you_recover": "Recuperi {1} PV!",
    "combat.off_hand_strike_npc": "{0} segue con un colpo della mano secondaria su {1}!",
    "combat.ability_assassinated": "ASSASSINATO! {0} cade all'istante!",
    "combat.ability_bloodlust": "SETE DI SANGUE! Ogni uccisione ti guarirà!",
    "combat.ability_bloodlust_npc": "SETE DI SANGUE! Ogni uccisione guarirà {0}!",
    "combat.ability_cleanse": "La luce purificatrice elimina {0} afflizione/i!",
    "combat.ability_confusion_resist": "{0} non capisce la battuta.",
    "combat.ability_confusion_success": "{0} è disorientato dalla battuta!",
    "combat.ability_death_blossom": "FIORITURA DI MORTE! Le lame colpiscono in ogni direzione!",
    "combat.ability_evasion": "Ti dissolvi nelle ombre, quasi impossibile da colpire!",
    "combat.ability_evasion_npc": "{0} si dissolve nelle ombre, quasi impossibile da colpire!",
    "combat.ability_fear_resist": "{0} resiste alla tua intimidazione!",
    "combat.ability_fear_resist_npc": "{0} resiste all'intimidazione di {1}!",
    "combat.ability_fear_success": "{0} è terrorizzato dal tuo ruggito!",
    "combat.ability_fear_success_npc": "{0} è terrorizzato dal ruggito di {1}!",
    "combat.ability_freeze_resist": "Il gelo morde {0} ma non lo congela!",
    "combat.ability_frenzy": "FRENESIA! {0} colpi aggiuntivi!",
    "combat.ability_frenzy_strike": "  Colpo {0}: {1} danni!",
    "combat.ability_frozen": "{0} è congelato completamente!",
    "combat.ability_holy_wash": "La luce sacra ti pervade!",
    "combat.ability_holy_wash_npc": "La luce sacra pervade {0}!",
    "combat.ability_immunity": "INARRESTABILE! Ti scrolli di dosso ogni afflizione!",
    "combat.ability_immunity_npc": "INARRESTABILE! {0} si scrolla di dosso ogni afflizione!",
    "combat.ability_invulnerable": "Uno scudo divino di luce pura ti circonda!",
    "combat.ability_invulnerable_npc": "Uno scudo divino di luce pura circonda {0}!",
    "combat.ability_kill_miss": "Il colpo mortale manca il punto vitale per un soffio!",
    "combat.ability_marked": "{0} è marchiato! Tutti gli attacchi infliggono il 30% di danni bonus!",
    "combat.ability_stealth": "Ti mimetizzi perfettamente con l'ambiente!",
    "combat.ability_stealth_npc": "{0} si mimetizza perfettamente con l'ambiente!",
    "combat.ability_torn_apart": "  {0} viene fatto a pezzi!",
    "combat.ability_vanish": "Svanisci completamente! Il tuo prossimo attacco colpirà dalle ombre!",
    "combat.ability_vanish_npc": "{0} svanisce completamente! Il suo prossimo attacco colpirà dalle ombre!",
    "combat.frozen": "{0} è congelato completamente!",
    "combat.asleep": "{0} sta dormendo profondamente!",
    "combat.feared": "{0} è paralizzato dalla paura!",
    "combat.you_slain": "Hai ucciso il {0}!",
    "combat.boss_defeated": "BOSS SCONFITTO!",
    "combat.defeated_count": "Sconfitti {0} mostro/i!",
    "combat.xp_label": "Esperienza guadagnata: {0}",
    "combat.gold_label": "Oro guadagnato: {0}",
    "combat.world_event_xp": "(Bonus evento mondiale: +{0} PE)",
    "combat.world_event_gold": "(Bonus evento mondiale: +{0} oro)",
    "combat.spouse_bonus": "(Bonus amore coniuge: +{0} PE) <3",
    "combat.divine_favor": "(Favore di {0}: +{1} PE)",
    "combat.team_penalty": "(Penalità alleato di alto livello: -{0} PE, {1}% tasso)",
    "combat.team_bonus": "(Bonus squadra: +{0} PE, +{1} oro)",
    "combat.xp_share": "(La tua parte: {0}% di {1} PE)",
    "combat.pickup_weapon": "Vuoi raccogliere il {0}? (S/N)",
    "combat.pickup_armor": "Vuoi prendere il {0}? (S/N)",
    "combat.picked_up": "Hai raccolto {0}.",
    "combat.escaped": "Sei fuggito dal combattimento!",
    "combat.escaped_battle": "Sei fuggito dalla battaglia!",
    "combat.escape_confusion": "Fuggi approfittando della confusione!",
    "combat.smoke_bomb": "Lanci una bomba fumogena e svanisci nella foschia!",
    "combat.attempt_flee": "Tenti di fuggire dal combattimento!",
    "combat.escape_chance": "(Probabilità di fuga: {0}%)",
    "combat.no_escape": "MODALITÀ INCUBO: Non c'è via di fuga. Combatti o muori!",
    "combat.wont_escape": "Il mostro non ti permette di fuggire!",
    "combat.flee_damage": "Mentre ti volti per fuggire, subisci {0} danni!",
    "combat.critical_warning": "ATTENZIONE: Sei gravemente ferito!",
    "combat.partial_victory": "Hai sconfitto {0} mostro/i prima di fuggire!",
    "combat.party_fallen": "{0} è caduto, ma il gruppo è vittorioso!",
    "combat.menu_actions": "Azioni:",
    "combat.menu_quickbar": "Barra rapida:",
    "combat.menu_defend_desc": "D - Difendi, riduce i danni del 50 percento",
    "combat.menu_heal_potions": "H - Cura, Pozioni: {0} di {1}",
    "combat.menu_heal_none": "H - Cura, Nessuna Pozione",
    "combat.menu_herb_pouch": "J - Sacca Erbe ({0} erbe)",
    "combat.menu_rage": "G - Furia, Rabbia berserker",
    "combat.menu_ranged": "V - Attacco a Distanza",
    "combat.menu_ranged_need_bow": "V - Attacco a Distanza (Serve Arco)",
    "combat.menu_power_attack": "P - Attacco Potente, 1.75x danni, 15 vigore",
    "combat.menu_precise_strike": "E - Colpo Preciso, maggiore precisione",
    "combat.menu_disarm": "I - Disarma, rimuovi bonus arma",
    "combat.menu_taunt": "T - Provoca, abbassa difesa nemica",
    "combat.menu_hide": "L - Nasconditi, tenta di sgattaiolare via",
    "combat.menu_coat_blade": "B - Avvelena Lama, Fiale: {0}",
    "combat.menu_retreat": "R - Ritirata, tenta di fuggire",
    "combat.menu_mercy": "M - Supplica Pietà",
    "combat.menu_fight_death": "F - Combatti fino alla Morte, nessuna ritirata",
    "combat.menu_flee_pvp": "R - Fuggi dal Combattimento",
    "combat.menu_view_status": "S - Visualizza Stato",
    "combat.menu_speed": "SPD - Velocità Combattimento, attuale {0}",
    "combat.speed_instant": "Istantaneo",
    "combat.speed_fast": "Veloce",
    "combat.speed_normal": "Normale",
    "combat.menu_unavailable": "(non disponibile)",
    "combat.choose_action": "Scegli azione: ",
    "combat.combat_menu": "Menu Combattimento",
    "combat.heal_potions_short": "Cura (Pozioni: {0}/{1})",
    "combat.heal_none_short": "Cura (Nessuna Pozione)",
    "combat.herb_pouch_short": "Sacca Erbe ({0} erbe)",
    "combat.rage_short": "Furia (Rabbia berserker!)",
    "combat.ranged_short": "Attacco a Distanza",
    "combat.ranged_need_bow_short": "Attacco a Distanza (Serve Arco)",
    "combat.coat_blade_short": "Avvelena Lama (Fiale: {0})",
    "combat.mercy_short": "Supplica Pietà",
    "combat.fight_death_short": "Combatti fino alla Morte (nessuna ritirata)",
    "combat.flee_pvp_short": "Fuggi dal Combattimento",
    "combat.view_status_short": "Visualizza Stato",
    "combat.speed_label": "Velocità Combattimento: {0}",
    "combat.your_hp": "I tuoi PV: {0} di {1}",
    "combat.enemy_hp": "Nemico: {0}, PV: {1}",
    "combat.opponent_hp": "Avversario: {0}, PV: {1} di {2}",
    "combat.status_label": "Stato: {0}",
    "combat.dungeon_menu": "Menu Combattimento Segrete",
    "combat.menu_use_item_potions": "I - Usa Oggetto, Pozioni: {0}",
    "combat.menu_use_item_none": "I - Usa Oggetto, Nessuna Pozione",
    "combat.menu_aid_ally": "H - Aiuta Alleato",
    "combat.menu_aid_ally_none": "H - Aiuta Alleato, Nessun mezzo per aiutare",
    "combat.menu_coat_blade_desc": "B - Avvelena Lama, Fiale: {0}",
    "combat.menu_save_boss": "V - Tenta Salvataggio, usa il Telaio dell'Anima",
    "combat.menu_auto": "AUTO - Modalità Combattimento Automatico",
    "combat.use_item_potions_short": "Usa Oggetto (Pozioni: {0}/{1})",
    "combat.use_item_none_short": "Usa Oggetto (Nessuna Pozione)",
    "combat.aid_ally_short": "Aiuta Alleato",
    "combat.aid_ally_none_short": "Aiuta Alleato (Nessun mezzo per aiutare)",
    "combat.save_boss_short": "Salva Boss (Telaio dell'Anima)",
    "combat.auto_short": "Combattimento Automatico",
    "combat.group_your_turn": "IL TUO TURNO ({0})",
    "combat.group_action_prompt": "Azione: ",
    "base.important_news": "NOTIZIE IMPORTANTI",
    "base.castle_under_attack": "*** URGENTE: IL CASTELLO È SOTTO ATTACCO! ***",
    "base.mysterious_encounter": "UN INCONTRO MISTERIOSO",
    "base.quick_commands": "COMANDI RAPIDI",
    "base.active_quests": "MISSIONI ATTIVE",
    "base.crafting_materials": "MATERIALI DI CREAZIONE",
    "base.ambush": "IMBOSCATA!",
    "base.rewards": "RICOMPENSE",
    "base.people_nearby": "PERSONE NEI DINTORNI",
    "base.character_status": "STATO DEL PERSONAGGIO",
    "base.basic_information": "INFORMAZIONI DI BASE",
    "base.level_experience": "LIVELLO E ESPERIENZA",
    "base.combat_statistics": "STATISTICHE DI COMBATTIMENTO",
    "base.equipment": "EQUIPAGGIAMENTO",
    "base.wealth": "RICCHEZZE",
    "base.relationships": "RELAZIONI",
    "base.alignment_reputation": "ALLINEAMENTO E REPUTAZIONE",
    "base.faction": "FAZIONE",
    "base.battle_record": "REGISTRO DI BATTAGLIA",
    "base.dungeon_progress": "PROGRESSI NELLE SEGRETE",
    "base.divine_status": "STATO DIVINO",
    "base.artifacts": "ARTEFATTI",
    "base.afflictions": "AFFLIZIONI",
    "base.your_mailbox": "LA TUA POSTA",
    "base.trade_packages": "PACCHI COMMERCIALI",
    "base.bounty_board": "TABELLONE DELLE TAGLIE",
    "base.auction_house": "CASA D'ASTE",
    "combat.bar_hp": "PV",
    "combat.bar_mp": "PM",
    "combat.bar_st": "VI",
    "combat.bar_atk": "ATT",
    "combat.bar_def": "DIF",
    "combat.bar_shield": "Scudo",
    "combat.bar_pot": "Poz",
    "combat.bar_potions": "Pozioni",
    "combat.bar_allies": "Alleati",
    "combat.bar_skills": "Abilità",
    "combat.status_combat": "Stato Combattimento",
    "combat.status_name": "Nome",
    "combat.status_strength_label": "Forza",
    "combat.status_defence_label": "Difesa",
    "combat.status_weapon_power": "Potenza Arma",
    "combat.status_armor_power": "Potenza Armatura",
    "combat.status_active_effects": "Effetti Attivi",
    "combat.injured": "[FERITO]",
    "combat.your_status": "Il tuo Stato:",
    "combat.quick_heal": "Cura rapida: {0} PV!",
    "combat.you_hesitate": "Esiti...",
    "combat.sr_hp": "PV: {0} di {1} ({2} percento, {3})",
    "combat.sr_mp": "PM: {0} di {1} ({2} percento)",
    "combat.sr_stamina": "Vigore: {0} di {1} ({2} percento)",
    "combat.sr_potions": "Pozioni: {0} di {1}",
    "combat.sr_attack_defense": "Attacco: {0}, Difesa: {1}",
    "combat.sr_magic_shield": "Scudo Magico: {0} danni rimanenti",
    "combat.sr_status_effects": "Effetti di stato: ",
    "combat.sr_allies": "Alleati:",
    "combat.sr_teammate_hp": " - PV: {0} di {1} ({2} percento, {3})",
    "combat.sr_teammate_mp": ", PM: {0} di {1}",
    "combat.sr_teammate_potions": ", Pozioni: {0}",
    "combat.status_healthy": "in salute",
    "combat.status_wounded": "ferito",
    "combat.status_badly_hurt": "gravemente ferito",
    "combat.status_critical": "critico",
    "combat.round_header": "──Turno {0}──",
    "combat.critical_miss": "MANCATO CRITICO! Inciampi malamente!",
    "combat.full_health": "Sei già al massimo della salute!",
    "combat.herb_empty": "La tua sacca di erbe è vuota!",
    "combat.defend_stance": "Assumi una posizione difensiva!",
    "combat.auto_combat_on": "Combattimento automatico attivato! Attaccherai automaticamente ogni turno.",
    "combat.auto_combat_off": "[COMBATTIMENTO AUTOMATICO] Fermato. Prendi il controllo manuale.",
    "combat.fatigue_dull": "(La stanchezza ottunde i tuoi riflessi)",
    "combat.slain_ambush": "Sei caduto nell'imboscata!",
    "combat.succumb_wounds": "Soccombi alle tue ferite!",
    "combat.fled_combat": "Sei fuggito dal combattimento.",
    "combat.accept_fate": "Accetti il tuo destino...",
    "combat.stunned_no_act": "Sei stordito e non puoi agire in questo turno!",
    "combat.cannot_act": "Sei {0} e non puoi agire!",
    "combat.divine_light_saves": "Una luce dorata risplende intorno a te!",
    "combat.divine_restored": "Sei riportato a {0} PV!",
    "combat.divine_shield_absorbs": "Il tuo scudo divino assorbe il colpo!",
    "combat.divine_shield_ability": "Il tuo scudo divino assorbe l'abilità!",
    "combat.divine_shield_drain": "Il tuo scudo divino devia il risucchio vitale!",
    "combat.beg_mercy": "Supplichi pietà!",
    "combat.pleas_deaf": "Le tue suppliche cadono nel vuoto!",
    "combat.fire_burn": "Il fuoco brucia {0} per {1} danni!",
    "combat.poison_burn": "Il veleno brucia {0} per {1} danni!",
    "combat.ice_shatters": "Il ghiaccio intorno a {0} si frantuma!",
    "combat.confusion_stumble": "{0} barcolla confuso!",
    "combat.confusion_self_damage": "{0} si colpisce da solo nella confusione per {1} danni!",
    "combat.confusion_defeat": "{0} si sconfigge da solo!",
    "combat.song_resonates": "Il tuo canto risuona attraverso il gruppo!",
    "combat.unidentified_no_equip": "Non puoi equipaggiare un oggetto non identificato. Lo metti nell'inventario.",
    "combat.cursed_bind": "Equipaggi l'oggetto... e senti una presenza oscura legarsi a te!",
    "combat.cursed_hold": "La maledizione prende possesso! Non puoi rimuovere questo oggetto normalmente.",
    "combat.target_damage": "{0} subisce {1} danni!",
    "combat.backstab_attempt": "Tenti una pugnalata alle spalle!",
    "combat.backstab_success": "PUGNALATA ALLE SPALLE! Colpisci dalle ombre per {0} danni!",
    "combat.backstab_fail": "Il tuo tentativo di pugnalata alle spalle fallisce!",
    "combat.soul_strike": "Incanali il potere divino per un Colpo dell'Anima!",
    "combat.soul_strike_hit": "L'energia divina colpisce per {0} danni!",
    "combat.soul_strike_fail": "La tua anima non ha la purezza necessaria per questo attacco!",
    "combat.ability_rage": "FURIAAAAA! Entri in una furia berserker!",
    "combat.hide_success": "Scivoli nelle ombre, nascosto alla vista...",
    "combat.hide_fail": "Tenti di nasconderti ma i nemici ti avvistano!",
    "combat.disarm_fail": "Il tuo tentativo di disarmo fallisce!",
    "combat.taunt_aoe": "Il tuo ruggito tonante rimbomba nella stanza! Tutti i nemici si rivolgono verso di te!",
    "combat.ranged_aim_true": "La tua mira è precisa!",
    "combat.poison_already_coated": "La tua lama è già ricoperta di {0}.",
    "combat.poison_keep_current": "Mantieni il rivestimento attuale.",
    "combat.poison_no_knowledge": "Non sai ancora come usare i veleni!",
    "combat.poison_coat": "Ricopri con cura la lama con {0}.",
    "combat.poison_glistens": "La tua arma luccica con una lucentezza letale...",
    "combat.trickster_lucky_hit": "Fortuna del Briccone! Il tuo attacco colpisce con forza inaspettata!",
    "combat.trickster_dodge": "Fortuna del Briccone! Danzi di lato, pronto a schivare!",
    "combat.first_blood_title": "PRIMO SANGUE!",
    "combat.first_blood_message": "Hai ucciso il tuo primo mostro!",
    "combat.proficiency_up": "La tua esperienza di combattimento cresce! Attacco Base è ora {0}!",
    "combat.trickster_stamina": "Fortuna del Briccone! L'emozione ripristina {0} vigore!",
    "combat.victory_title": "=== VITTORIA! ===",
    "combat.defeated_player": "Hai sconfitto {0}!",
    "combat.ability_noctura_shadow": "Le ombre di Noctura avvolgono {0}, prosciugando la sua volontà di combattere!",
    "combat.ability_noctura_shadow_npc": "{0} invoca le ombre di Noctura per prosciugare la volontà del nemico!",
    "combat.ability_transmute": "Transmuti l'essenza della battaglia in energia ristoratrice!",
    "combat.ability_legend_incarnate": "Incanali il potere di una leggenda dimenticata!",
    "combat.ability_legend_incarnate_npc": "{0} incanala il potere di una leggenda dimenticata!",
    "combat.ability_legendary_resist": "La tua resilienza leggendaria respinge il colpo!",
    "combat.ability_legendary_stagger": "La forza leggendaria fa barcollare i nemici vicini!",
    "combat.ability_avatar_destruction": "Diventi un AVATAR DELLA DISTRUZIONE!",
    "combat.ability_avatar_light": "Diventi un AVATAR DELLA LUCE!",
    "combat.ability_undertow": "La risacca trascina {0}, indebolendo i suoi colpi!",
    "combat.ability_riptide": "Una corrente impetuosa attraversa {0}, prosciugandone la forza!",
    "combat.ability_breakwater": "Diventi un muro infrangibile di pietra oceanica!",
    "combat.ability_regen_20": "Acque vive scorrono nelle tue vene, sanando le ferite ogni turno!",
    "combat.ability_abyssal_anchor": "Ti ancorai al fondale oceanico! I nemici lottano contro la corrente!",
    "combat.ability_sanctified_torrent": "Acque santificate si abbattono su {0} per {1} danni!",
    "combat.ability_sanctified_torrent_holy": "Acque santificate si abbattono su {0} per {1} danni! (SACRO!)",
    "combat.ability_sanctified_torrent_heal": "Le acque sacre ti guariscono di {0} PV!",
    "combat.ability_oceans_embrace": "L'Oceano ti abbraccia, guarendo {0} PV e purificando ogni afflizione!",
    "combat.ability_oceans_embrace_ally": "  {0} viene guarito di {1} PV!",
    "combat.ability_tidal_colossus": "TI ERGI COME UN COLOSSO DI MAREA! Nulla può farti vacillare!",
    "combat.ability_eternal_vigil": "L'eterna veglia dell'Oceano ti protegge! Tutti i nemici sono attratti dalla tua forma invulnerabile!",
    "combat.ability_wrath_deep_kill": "L'OCEANO RECLAMA {0}! Trascinato negli abissi!",
    "combat.ability_wrath_deep": "L'ira degli Abissi si abbatte su {0} per {1} danni!",
    "combat.ability_wrath_deep_heal": "L'oceano ripristina {0} PV!",
    "combat.ability_party_buff": "Una cadenza ispiratrice riempie l'aria! Tutti gli alleati sono pervasi di potere!",
    "combat.ability_double_vs_debuffed": "Un'eco d'onda colpisce {0} per {1} danni!",
    "combat.ability_double_vs_debuffed_resonance": "L'eco d'onda RISUONA con la debolezza di {0} per {1} danni DOPPI!",
    "combat.ability_empathic_link": "Un legame empatico si forma! I danni sono condivisi, i fardelli alleggeriti!",
    "combat.ability_crescendo_aoe": "Il crescendo colpisce {0} per {1} danni!",
    "combat.ability_crescendo_aoe_allies": "  ({0} alleati hanno amplificato l'armonia di +{1} danni!)",
    "combat.ability_harmonic_shield": "Uno scudo armonico avvolge il tuo gruppo! Gli attacchi vengono riflessi!",
    "combat.ability_dissonant_wave": "La dissonanza scuote {0}! (Indebolito, Vulnerabile)",
    "combat.ability_dissonant_wave_stun": "La dissonanza scuote {0}! (Indebolito, Vulnerabile, STORDITO!)",
    "combat.ability_resonance_cascade": "La risonanza a catena attraversa {0} per {1} danni!",
    "combat.ability_resonance_cascade_amplified": "  (Catena amplificata da {0} bersagli: {1}% danni!)",
    "combat.ability_tidal_harmony_ally": "  {0} viene guarito di 200 PV!",
    "combat.ability_tidal_harmony": "L'armonia delle maree ristora il tuo gruppo e potenzia i tuoi colpi!",
    "combat.ability_oceans_voice": "L'OCEANO PARLA ATTRAVERSO DI TE! Tutti gli alleati sono pervasi di potere divino!",
    "combat.ability_grand_finale": "IL GRAN FINALE colpisce {0} per {1} danni!",
    "combat.ability_grand_finale_buffs": "  ({0} potenziamenti consumati per +{1} danni bonus!)",
    "combat.ability_temporal_feint": "Ti muovi tra gli istanti! Il tuo prossimo colpo è inevitabile!",
    "combat.ability_borrowed_power": "Il potere di {0} vite passate ti pervade! (+{0} a tutte le statistiche di combattimento)",
    "combat.ability_echo_25": "La realtà si frattura intorno a {0} per {1} danni!",
    "combat.ability_echo_25_echo": "  La frattura fa ECO! {0} danni aggiuntivi!",
    "combat.ability_quantum_state": "Esisti in una sovrapposizione quantistica! Gli attacchi ti attraversano!",
    "combat.ability_entropy_aoe": "L'entropia consuma {0} per {1} danni! (Vulnerabile!)",
    "combat.ability_timeline_split": "Un clone temporale si materializza accanto a te, rispecchiando ogni tuo colpo!",
    "combat.ability_causality_loop": "{0} è intrappolato in un ciclo causale! La sua stessa violenza si ritorce contro!",
    "combat.ability_chrono_surge": "Il tempo accelera intorno a te! Ti muovi con velocità impossibile!",
    "combat.ability_singularity": "La singolarità schiaccia {0} per {1} danni!",
    "combat.ability_singularity_stun": "La singolarità schiaccia {0} per {1} danni! (STORDITO: 2x!)",
    "combat.ability_temporal_prison_resist": "{0} resiste alla prigione temporale!",
    "combat.ability_temporal_prison": "{0} è congelato nel tempo per {1} turni!",
    "combat.ability_cycles_end": "IL CICLO FINISCE QUI! {0} subisce {1} danni!",
    "combat.ability_cycles_end_bonus": "  (Potenziato da {0} cicli: +{1} danni bonus!)",
    "combat.ability_shadow_harvest": "Le ombre mietono {0} per {1} danni! Assorbi {2} PV!",
    "combat.ability_corrupting_dot": "La corruzione si insinua in {0}! La sua forza vitale ti nutre!",
    "combat.ability_umbral_step": "Ti dissolvi nell'ombra! Il tuo prossimo colpo sarà letale!",
    "combat.ability_lifesteal_10": "L'autorità oscura scorre in te! I tuoi colpi risucchiano la forza vitale!",
    "combat.ability_overflow_aoe": "Il sigillo si frattura attraverso {0} per {1} danni!",
    "combat.ability_overflow_aoe_spread": "  L'overflow erutta in {0} per {1} danni!",
    "combat.ability_soul_leech": "La sanguisuga dell'anima risucchia {0} per {1} danni! Assorbi {2} PV!",
    "combat.ability_soul_leech_corrupt": "La sanguisuga dell'anima risucchia {0} per {1} danni! Assorbi {2} PV! (Bonus corruzione!)",
    "combat.ability_abyssal_eruption": "L'eruzione abissale inghiotte {0} per {1} danni! (Corrotto!)",
    "combat.ability_dark_pact": "Offri {0} PV all'abisso! Il potere oscuro ti pervade!",
    "combat.ability_prison_wardens_command": "Imponi il tuo dominio su {0}! (-{1} ATT, -{2} DIF)",
    "combat.ability_consume_soul": "Consumi l'anima di {0} per {1} danni!",
    "combat.ability_consume_soul_bonus": "  La sua essenza ti potenzia permanentemente! (+5 ATT in questo combattimento)",
    "combat.ability_abyss_unchained": "L'ABISSO SCATENATO schiaccia {0} per {1} danni!",
    "combat.ability_abyss_unchained_heal": "L'abisso ti riporta a piena salute e purga ogni afflizione!",
    "combat.ability_lifesteal_30": "Il tuo colpo famelico dilania {0} per {1} danni! Ti nutri di {2} PV!",
    "combat.ability_offer_flesh_desperate": "Offri {0} PV! POTERE DISPERATO — bonus DOPPIO! (+120 ATT totali)",
    "combat.ability_offer_flesh": "Sacrifichi {0} PV al vuoto! Il potere oscuro scorre in te!",
    "combat.ability_execute_reap_triple": "MIETITURA! Il debole {0} viene raccolto per {1} danni TRIPLI!",
    "combat.ability_execute_reap": "Mieti {0} per {1} danni!",
    "combat.ability_damage_reflect_25": "Il vuoto ti avvolge come un sudario! Gli attacchi vengono riflessi!",
    "combat.ability_apotheosis": "SACRIFICHI {0} PV E DIVENTI LA ROVINA INCARNATA!",
    "combat.ability_apotheosis_detail": "  +100 ATT, tutti i nemici colpiti, 20% risucchio vita!",
    "combat.ability_devour": "DIVORI {0} per {1} danni e ti nutri di {2} PV!",
    "combat.ability_entropic_blade": "La tua lama entropica taglia OGNI difesa! {0} subisce {1} danni! (-{2} PV)",
    "combat.ability_blood_frenzy": "Sacrifichi {0} PV in una frenesia di sangue! Attacchi due volte per turno!",
    "combat.ability_void_rupture": "La rottura del vuoto dilania {0} per {1} danni!",
    "combat.ability_void_rupture_explode": "  L'esplosione del vuoto da {0} uccisioni colpisce {1} per {2}!",
    "combat.ability_deaths_embrace": "La morte ti avvolge nel suo abbraccio — non cadrai facilmente!",
    "combat.ability_deaths_embrace_detail": "  (Rigenerazione per 3 turni, prossimo attacco schivato)",
    "combat.ability_annihilation_kill": "ANNICHILAZIONE! {0} È CANCELLATO DALL'ESISTENZA! (-{1} PV)",
    "combat.ability_annihilation": "L'ANNICHILAZIONE colpisce {0} per {1} danni! (-{2} PV)",
    "combat.no_abilities": "Non hai ancora appreso alcuna abilità!",
    "combat.no_abilities_hint": "Addestrati dal Maestro di Livello per sbloccare abilità man mano che avanzi di livello.",
    "combat.invalid_spell": "Incantesimo non valido.",
    "combat.need_weapon_spell": "Ti serve un {0} equipaggiato per lanciare incantesimi!",
    "combat.not_enough_mana": "Mana insufficiente!",
    "combat.spell_proficiency_up": "  La tua competenza in {0} è migliorata a {1}!",
    "combat.spell_sleep": "{0} si addormenta!",
    "combat.spell_fear": "{0} si raggomitola per la paura!",
    "combat.spell_resist_stun": "{0} resiste allo stordimento!",
    "combat.spell_stunned": "{0} è stordito!",
    "combat.spell_slowed": "{0} è rallentato!",
    "combat.spell_poisoned": "{0} è avvelenato!",
    "combat.spell_frozen": "{0} è congelato completamente!",
    "combat.spell_chilled": "{0} è gelato fino alle ossa!",
    "combat.spell_web_resist": "{0} si libera dalle ragnatele!",
    "combat.spell_web": "{0} è intrappolato in ragnatele appiccicose!",
    "combat.spell_mass_confusion": "{0} è sopraffatto dal caos psichico!",
    "combat.spell_dominate": "La volontà di {0} è spezzata — ora ti serve!",
    "combat.spell_holy_bonus": "La luce sacra brucia {0} per {1} danni bonus!",
    "combat.spell_fire": "{0} prende fuoco!",
    "combat.spell_drain": "Risucchi {0} forza vitale da {1}!",
    "combat.spell_death_kill": "La magia mortale reclama la forza vitale residua di {0}!",
    "combat.spell_death_resist": "{0} resiste al colpo mortale!",
    "combat.spell_disintegrate": "L'armatura di {0} si disintegra! (-{1} difesa)",
    "combat.spell_psychic": "L'onda psichica scuote la mente di {0}!",
    "combat.spell_dispel": "Gli incantamenti oscuri vengono strappati da {0}!",
    "combat.spell_convert_touch": "{0} è toccato dalla luce divina!",
    "combat.spell_convert_unholy_resist": "La creatura empia resiste alla luce divina!",
    "combat.spell_convert_flee": "{0} riconosce i propri errori e fugge!",
    "combat.spell_convert_pacify_resist": "{0} resiste alla luce sacra!",
    "combat.spell_convert_pacify": "{0} è pacificato dalla luce sacra!",
    "combat.spell_convert_success": "{0} è convertito alla tua causa!",
    "combat.spell_convert_fail": "{0} resiste al tentativo di conversione!",
    "combat.spell_escape": "{0} svanisce in un turbine di energia arcana!",
    "combat.no_allies_to_aid": "Nessun alleato disponibile da aiutare.",
    "combat.aid_no_mana_pool": "{0} non usa il mana!",
    "combat.aid_full_mana": "{0} ha già il mana al massimo!",
    "combat.aid_give_mana_potion": "Dai una pozione di mana a {0}!",
    "combat.aid_give_mana_potions": "Dai {0} pozioni di mana a {1}!",
    "combat.aid_recover_mp": "{0} recupera {1} PM!",
    "combat.aid_mana_full": "Il mana di {0} è completamente ripristinato!",
    "combat.aid_full_health": "{0} è già al massimo della salute!",
    "combat.aid_give_heal_potion": "Dai una pozione curativa a {0}!",
    "combat.aid_give_heal_potions": "Dai {0} pozioni curative a {1}!",
    "combat.aid_recover_hp": "{0} recupera {1} PV!",
    "combat.aid_fully_healed": "{0} è completamente guarito!",
    "combat.aid_no_heal_spells": "Non hai incantesimi di guarigione disponibili.",
    "combat.spell_fails": "L'incantesimo non ha effetto.",
    "combat.spell_fizzles": "L'incantesimo svanisce nel nulla!",
    "combat.teammate_mana_potion": "{0} beve una pozione di mana e recupera {1} PM!",
    "combat.teammate_drinks_potion": "{0} beve una pozione curativa!",
    "combat.teammate_gives_potion": "{0} dà una pozione curativa a {1}!",
    "combat.echo_dissipates": "  L'eco di {0} si dissolve nella nebbia...",
    "combat.echo_unharmed": "  Il suo vero sé è illeso.",
    "combat.companion_falls": "{0} cade!",
    "combat.npc_fallen": "  {0} è caduto in battaglia!",
    "combat.grief_onset": "  Un'ondata di dolore ti pervade. (Fase: Negazione)",
    "combat.grief_combat_effect": "  Il tuo dolore influenzerà le tue prestazioni in combattimento.",
    "combat.spouse_fallen": "Il tuo amato coniuge {0} è caduto...",
    "combat.lover_fallen": "Il tuo amante {0} è caduto...",
    "combat.perhaps_saved": "Forse può ancora essere salvato...",
    "combat.teammate_sacrifice": "Il tuo leale compagno di squadra {0} ha fatto il sacrificio supremo.",
    "combat.mercenary_gone": "  La tua guardia del corpo assunta non c'è più. Dovrai assumerne un'altra.",
    "base.how_respond": "  Come rispondi?",
    "base.your_response": "La tua risposta: ",
    "base.you_paid_gold": "  (Hai pagato {0} oro)",
    "base.plus_chivalry": "  (+{0} Cavalleria)",
    "base.plus_darkness": "  (+{0} Oscurità)",
    "base.reward_chivalry": "  +{0} Cavalleria!",
    "base.reward_wisdom": "  +{0} Saggezza!",
    "base.reward_dexterity": "  +{0} Destrezza!",
    "base.fragment_truth": "  (Un frammento di verità si insedia nella tua coscienza...)",
    "base.something_shifts": "  (Qualcosa cambia nella tua comprensione...)",
    "base.deeper_understanding": "  (Una comprensione più profonda si insedia in te...)",
    "base.minus_gold": "  (-{0} oro)",
    "base.npc_approaches": "{0} ti si avvicina.",
    "base.npc_gift_dialogue": "\"Non ti ho mai ringraziato come si deve. Prendi questo — non è molto, ma...\"",
    "base.received_gold": "  (Ricevuto {0} oro)",
    "base.npc_catches_eye": "{0} attira il tuo sguardo e si avvicina.",
    "base.tip_weapons": "\"Ho sentito dire che ci sono armi potenti nascoste nei piani più profondi delle segrete. Stai attento laggiù.\"",
    "base.tip_healer": "\"Un consiglio — il guaritore offre prezzi migliori se compri in quantità.\"",
    "base.tip_training": "\"Ultimamente mi sono allenato in palestra. Dovresti provare — i risultati ne valgono la pena.\"",
    "base.tip_temple": "\"I sacerdoti del tempio si sono comportati in modo strano ultimamente. Qualcosa li turba.\"",
    "base.tip_marketplace": "\"Tieni d'occhio il mercato. Merci rare passano di tanto in tanto.\"",
    "base.npc_smiles": "{0} sorride al tuo passaggio.",
    "base.compliment1": "\"Che piacere vederti, amico. Questa città è un posto migliore con te.\"",
    "base.compliment2": "\"Ho sentito storie sulle tue avventure. Roba impressionante.\"",
    "base.compliment3": "\"Sai, la gente qui ti ammira. Continua così.\"",
    "base.compliment4": "\"Stavo proprio parlando di te l'altro giorno. Solo cose buone, ovviamente.\"",
    "base.npc_presses": "{0} ti mette qualcosa in mano.",
    "base.npc_heal_dialogue": "\"Sembra che ti serva questo. Stai al sicuro là fuori.\"",
    "base.restored_hp": "  (Ripristinati {0} PV)",
    "base.already_healthy": "  (Sei già in buona salute.)",
    "base.npc_blocks_path": "{0} ti blocca il cammino.",
    "base.threat1": "\"So cosa hai fatto. Stai lontano da me e dai miei, o la prossima volta non sarà una chiacchierata.\"",
    "base.threat2": "\"Hai un bel coraggio a farti vedere da queste parti.\"",
    "base.threat3": "\"Guardati le spalle. Non tutti qui sono clementi come me.\"",
    "base.npc_catches_arm": "{0} ti afferra il braccio mentre passi.",
    "base.warning_talking": "\"La gente parla di te. E non in modo positivo. Forse dovresti mantenere un basso profilo.\"",
    "base.npc_stares_down": "{0} ti fissa dall'altra parte della stanza.",
    "base.hand_on_pommel": "La sua mano poggia vistosamente sull'impugnatura della propria arma.",
    "base.not_welcome": "Il messaggio è chiaro: non sei il benvenuto qui.",
    "base.mail_unread": "Non letti: {0}",
    "base.mailbox_empty": "La tua casella postale è vuota.",
    "base.mail_delete_menu": "]ancella #  [",
    "base.mail_next_menu": "]ag. Succ.  [",
    "base.mail_prev_menu": "]ag. Prec.  [",
    "base.mail_deleted": "Messaggio cancellato.",
    "base.mail_message_from": "MESSAGGIO DA {0}",
    "base.mail_message_from_box": "═══ MESSAGGIO DA {0} ═══",
    "base.mail_date": "Data: {0}",
    "base.mail_type": "Tipo: {0}",
    "base.mail_daily_limit": "Hai raggiunto il limite giornaliero di posta (20 messaggi).",
    "base.mail_send_to": "Invia a: ",
    "base.mail_player_not_found": "Giocatore '{0}' non trovato.",
    "base.mail_message_prompt": "Messaggio (max 200 caratteri):",
    "base.mail_sent": "Messaggio inviato a {0}!",
    "base.trade_incoming": "In arrivo ({0} in sospeso):",
    "base.trade_no_pending": "  Nessun pacco in sospeso.",
    "base.trade_sent": "Inviati ({0} in sospeso):",
    "base.trade_no_outgoing": "  Nessun pacco in uscita.",
    "base.trade_commands": "  Comandi:  Digita una lettera + numero insieme, es. A1, D2, C3",
    "base.trade_accept": "] Accetta pacco    ",
    "base.trade_decline": "] Rifiuta pacco",
}
