translations = {
    "inn.food_option_bread": "Pane e Formaggio ({0}g) - Ripristina {1} HP",
    "inn.food_option_feast": "Banchetto dell'Avventuriero ({0}g) - Ripristina {1} HP, +{2} a tutte le statistiche per {3} combattimenti",
    "inn.food_option_cancel": "Annulla",
    "inn.food_cant_afford": "Non puoi permetterti quel pasto!",
    "inn.food_enjoy": "Gusti un {0}.",
    "inn.food_hp_restored": "Ripristinati {0} HP! (HP: {1}/{2})",
    "inn.food_buff_applied": "Ti senti potenziato! Statistiche aumentate per {0} combattimenti.",
    "inn.companions_title": "COMPAGNI",
    "inn.companions_none_available": "Nessun compagno è disponibile qui.",
    "inn.companions_available": "Compagni Disponibili:",
    "inn.companions_npc_entry": "  {0} — {1} Livello {2} ({3})",
    "inn.companions_recruited": "I Tuoi Compagni:",
    "inn.companions_active": " [Attivo]",
    "inn.companions_inactive": " [Inattivo]",
    "inn.companions_interact_prompt": "Seleziona compagno # (o Invio per uscire): ",
    "inn.recruit_title": "RECLUTA {0}",
    "inn.recruit_option_recruit": "Recluta come compagno",
    "inn.recruit_option_info": "Scopri di più",
    "inn.recruit_option_cancel": "Annulla",
    "inn.recruit_success": "{0} si è unito al tuo gruppo!",
    "inn.recruit_requirements_not_met": "Non soddisfi i requisiti per reclutare {0}.",
    "inn.recruit_party_full": "Il tuo gruppo è pieno! Puoi avere al massimo {0} compagni.",
    "inn.party_title": "GESTIONE GRUPPO",
    "inn.party_companion_entry": "  {0}. {1} — {2} Livello {3} (HP: {4}/{5}){6}",
    "inn.party_option_talk": "Parla con il compagno",
    "inn.party_option_equipment": "Equipaggiamento",
    "inn.party_option_abilities": "Abilità",
    "inn.party_option_switch": "Cambia compagni attivi",
    "inn.party_option_dismiss": "Congeda compagno",
    "inn.party_option_back": "Indietro",
    "inn.companion_detail_title": "{0} - DETTAGLI COMPAGNO",
    "inn.companion_detail_class": "Classe: {0}",
    "inn.companion_detail_level": "Livello: {0}",
    "inn.companion_detail_hp": "HP: {0}/{1}",
    "inn.companion_detail_role": "Ruolo: {0}",
    "inn.companion_detail_loyalty": "Lealtà: {0}/100",
    "inn.companion_detail_str": "  FOR: {0}",
    "inn.companion_detail_dex": "  DES: {0}",
    "inn.companion_detail_agi": "  AGI: {0}",
    "inn.companion_detail_con": "  COS: {0}",
    "inn.companion_detail_int": "  INT: {0}",
    "inn.companion_detail_wis": "  SAG: {0}",
    "inn.companion_detail_cha": "  CAR: {0}",
    "inn.companion_detail_sta": "  STA: {0}",
    "inn.switch_title": "CAMBIA COMPAGNI ATTIVI",
    "inn.switch_current_active": "Compagni attualmente attivi:",
    "inn.switch_select_prompt": "Seleziona compagno da attivare/disattivare: ",
    "inn.switch_activated": "{0} è ora ATTIVO e ti accompagnerà in combattimento.",
    "inn.switch_deactivated": "{0} è ora INATTIVO e attenderà alla locanda.",
    "inn.switch_max_active": "Hai già il numero massimo di compagni attivi!",
    "inn.talk_companion_title": "CONVERSAZIONE CON {0}",
    "inn.talk_companion_option_chat": "Chiacchiera",
    "inn.talk_companion_option_quest": "Missione Personale",
    "inn.talk_companion_option_romance": "Romanticismo",
    "inn.talk_companion_option_gift": "Fai un Regalo",
    "inn.talk_companion_option_history": "Storia",
    "inn.talk_companion_option_back": "Indietro",
    "inn.companion_dialogue_aldric_1": "\"Il sotterraneo cela molti segreti. Stammi vicino e ti coprirò le spalle.\"",
    "inn.companion_dialogue_aldric_2": "\"Un altro giorno, un'altra battaglia. È la vita che abbiamo scelto.\"",
    "inn.companion_dialogue_vex_1": "\"Queste tasche non si svuoteranno da sole. Troviamo qualche bersaglio.\"",
    "inn.companion_dialogue_vex_2": "\"La fiducia è un lusso nel nostro mestiere. Ma tu mi vai bene.\"",
    "inn.companion_dialogue_lyris_1": "\"Gli Antichi Dèi parlano attraverso il vento. Riesci a sentirli?\"",
    "inn.companion_dialogue_lyris_2": "\"La magia scorre in ogni cosa. Basta sapere dove cercare.\"",
    "inn.companion_dialogue_mira_1": "\"Lascia che controlli quelle ferite. Un avventuriero sano è un avventuriero vivo.\"",
    "inn.companion_dialogue_mira_2": "\"Il tempio mi ha addestrata bene, ma il sotterraneo insegna di più.\"",
    "inn.companion_dialogue_melodia_1": "\"Ogni battaglia ha un ritmo. Lascia che trovi la canzone giusta per la nostra.\"",
    "inn.companion_dialogue_melodia_2": "\"Le antiche ballate parlano di eroi. Forse ne scriveremo una nuova.\"",
    "inn.companion_dialogue_generic_1": "\"Pronti per l'avventura? Andiamo!\"",
    "inn.companion_dialogue_generic_2": "\"Ti copro le spalle, amico.\"",
    "inn.quest_no_quest": "{0} non ha una missione personale disponibile al momento.",
    "inn.quest_active": "Missione Attiva: {0}",
    "inn.quest_progress": "Progresso: {0}",
    "inn.quest_completed": "La missione personale di {0} è completata!",
    "inn.quest_hint": "{0} dice: \"{1}\"",
    "inn.romance_title": "ROMANTICISMO CON {0}",
    "inn.romance_not_interested": "{0} non sembra interessato al romanticismo.",
    "inn.romance_loyalty_low": "Il tuo legame con {0} non è ancora abbastanza forte.",
    "inn.romance_milestone_1": "{0} ti sorride calorosamente.",
    "inn.romance_milestone_2": "{0} ti prende dolcemente la mano.",
    "inn.romance_milestone_3": "{0} ti guarda negli occhi.",
    "inn.romance_milestone_4": "\"{0} si avvicina e sussurra qualcosa di tenero.\"",
    "inn.gift_companion_title": "FAI UN REGALO A {0}",
    "inn.gift_companion_option_gold": "Dona oro",
    "inn.gift_companion_option_potion": "Dona pozione",
    "inn.gift_companion_option_item": "Dona oggetto equipaggiato",
    "inn.gift_companion_option_cancel": "Annulla",
    "inn.gift_companion_gold_prompt": "Quanto oro? (Hai {0}): ",
    "inn.gift_companion_gold_given": "Dai {0} monete d'oro a {1}. La sua lealtà aumenta!",
    "inn.gift_companion_potion_given": "Dai una pozione a {0}. La sua lealtà aumenta!",
    "inn.gift_companion_no_potions": "Non hai pozioni da donare.",
    "inn.history_title": "{0} - STORIA",
    "inn.history_joined": "Si è unito il giorno {0}.",
    "inn.history_battles": "Battaglie combattute insieme: {0}",
    "inn.history_loyalty": "Lealtà attuale: {0}",
    "inn.history_none": "Nessuna storia degna di nota per ora.",
    "inn.equipment_title": "{0} - EQUIPAGGIAMENTO",
    "inn.equipment_option_view": "Visualizza equipaggiamento",
    "inn.equipment_option_equip": "Equipaggia oggetto",
    "inn.equipment_option_unequip": "Rimuovi oggetto",
    "inn.equipment_option_take_all": "Prendi tutto l'equipaggiamento",
    "inn.equipment_option_back": "Indietro",
    "inn.equip_slot_weapon": "Arma",
    "inn.equip_slot_off_hand": "Mano Secondaria",
    "inn.equip_slot_body": "Corpo",
    "inn.equip_slot_head": "Testa",
    "inn.equip_slot_arms": "Braccia",
    "inn.equip_slot_hands": "Mani",
    "inn.equip_slot_legs": "Gambe",
    "inn.equip_slot_feet": "Piedi",
    "inn.equip_slot_waist": "Vita",
    "inn.equip_slot_face": "Volto",
    "inn.equip_slot_cloak": "Mantello",
    "inn.equip_slot_neck": "Collo",
    "inn.equip_slot_left_finger": "Dito Sinistro",
    "inn.equip_slot_right_finger": "Dito Destro",
    "inn.equip_slot_empty": "(vuoto)",
    "inn.equip_slot_two_handed": "(usa arma a 2 mani)",
    "inn.equip_slot_unidentified": "Oggetto Non Identificato",
    "inn.equip_select_slot": "Seleziona slot da equipaggiare: ",
    "inn.equip_no_items": "Non hai oggetti per quello slot.",
    "inn.equip_select_item": "Seleziona oggetto da equipaggiare (o Invio per annullare): ",
    "inn.equip_equipped": "Equipaggiato {0} su {1}.",
    "inn.equip_unequip_select": "Seleziona slot da rimuovere: ",
    "inn.equip_unequipped": "Rimosso {0} da {1}.",
    "inn.equip_slot_already_empty": "Quello slot è già vuoto.",
    "inn.equip_take_all_confirm": "Prendere tutto l'equipaggiamento da {0}? (S/N): ",
    "inn.equip_take_all_done": "Hai preso tutto l'equipaggiamento da {0}.",
    "inn.equip_take_all_nothing": "{0} non ha equipaggiamento da prendere.",
    "inn.abilities_title": "{0} - ABILITÀ",
    "inn.abilities_toggle_prompt": "Seleziona abilità # da attivare/disattivare (o Invio per tornare): ",
    "inn.abilities_enabled": "{0}/{1} abilità attivate",
    "inn.abilities_disabled": "{0} DISATTIVATA",
    "inn.abilities_none": "{0} non ha abilità da gestire.",
    "inn.training_title": "ADDESTRAMENTO COL MAESTRO",
    "inn.training_welcome": "Il Maestro d'Addestramento annuisce al tuo avvicinarti.",
    "inn.training_welcome_quote": "\"Benvenuto, {0}. Pronto a superare i tuoi limiti?\"",
    "inn.training_option_str": "Addestra Forza ({0} oro)",
    "inn.training_option_dex": "Addestra Destrezza ({0} oro)",
    "inn.training_option_con": "Addestra Costituzione ({0} oro)",
    "inn.training_option_int": "Addestra Intelligenza ({0} oro)",
    "inn.training_option_agi": "Addestra Agilità ({0} oro)",
    "inn.training_option_cancel": "Annulla",
    "inn.training_cant_afford": "Non puoi permetterti quella sessione di addestramento!",
    "inn.training_stat_improved": "La tua {0} è migliorata! ({1} → {2})",
    "inn.training_grueling": "Una sessione di addestramento estenuante!",
    "inn.training_exhausting": "Una sessione estenuante ma gratificante!",
    "inn.training_master_nods": "\"Buon lavoro,\" il maestro annuisce con approvazione.",
    "inn.training_max_reached": "\"Hai raggiunto il limite di ciò che posso insegnarti per {0}.\"",
    "inn.gambling_title": "SALA DA GIOCO",
    "inn.gambling_desc": "Una stanza fumosa sul retro dove si vincono e si perdono fortune.",
    "inn.gambling_option_high_low": "Dadi Alto-Basso",
    "inn.gambling_option_skull": "Teschio e Ossa",
    "inn.gambling_option_arm_wrestle": "Braccio di Ferro",
    "inn.gambling_option_leave": "Esci",
    "inn.high_low_title": "DADI ALTO-BASSO",
    "inn.high_low_rules": "Indovina se il prossimo tiro sarà più alto o più basso. 3 vittorie = jackpot!",
    "inn.high_low_wager_prompt": "Piazza la tua scommessa (da {0} a {1} oro): ",
    "inn.high_low_cant_afford": "Non puoi permetterti quella scommessa!",
    "inn.high_low_current_roll": "Tiro attuale: {0}",
    "inn.high_low_prompt": "Più alto (H) o più basso (L)? ",
    "inn.high_low_next_roll": "Prossimo tiro: {0}",
    "inn.high_low_correct": "Corretto!",
    "inn.high_low_wrong": "Sbagliato! I dadi ti tradiscono.",
    "inn.high_low_same": "Stesso numero! Vince il banco.",
    "inn.high_low_streak": "Serie di vittorie: {0}/3",
    "inn.high_low_jackpot": "JACKPOT! Hai vinto {0} oro!",
    "inn.high_low_lost": "Hai perso {0} oro.",
    "inn.high_low_continue": "Continuare a giocare? (S/N): ",
    "inn.skull_title": "TESCHIO E OSSA",
    "inn.skull_rules": "Avvicinati il più possibile a 21 senza superarlo.",
    "inn.skull_wager_prompt": "Piazza la tua scommessa (da {0} a {1} oro): ",
    "inn.skull_cant_afford": "Non puoi permetterti quella scommessa!",
    "inn.skull_your_hand": "La tua mano: {0} ({1})",
    "inn.skull_dealer_shows": "Il mazziere mostra: {0}",
    "inn.skull_hit_or_stand": "Carta (H) o Stai (S)? ",
    "inn.skull_drew": "Hai pescato: {0}",
    "inn.skull_bust": "SBALLATO! Hai superato 21.",
    "inn.skull_dealer_hand": "Mano del mazziere: {0} ({1})",
    "inn.skull_dealer_hits": "Il mazziere pesca: {0}",
    "inn.skull_dealer_busts": "Il mazziere sballa!",
    "inn.skull_you_win": "Hai vinto {0} oro!",
    "inn.skull_you_lose": "Hai perso {0} oro!",
    "inn.skull_push": "Parità! Scommessa restituita.",
    "inn.skull_blackjack": "TESCHIO E OSSA! 21 naturale! Hai vinto {0} oro!",
    "inn.arm_wrestle_title": "BRACCIO DI FERRO",
    "inn.arm_wrestle_desc": "Metti alla prova la tua forza contro un altro avventore!",
    "inn.arm_wrestle_opponent": "Il tuo avversario: {0} (FOR: {1})",
    "inn.arm_wrestle_wager_prompt": "Piazza la tua scommessa (da {0} a {1} oro): ",
    "inn.arm_wrestle_cant_afford": "Non puoi permetterti quella scommessa!",
    "inn.arm_wrestle_round": "--- Spinta {0} ---",
    "inn.arm_wrestle_you_push": "Spingi con tutta la tua forza!",
    "inn.arm_wrestle_opponent_pushes": "{0} spinge con forza!",
    "inn.arm_wrestle_you_gaining": "Stai guadagnando terreno!",
    "inn.arm_wrestle_opponent_gaining": "{0} sta guadagnando terreno!",
    "inn.arm_wrestle_even": "Siete alla pari!",
    "inn.arm_wrestle_you_win": "Schiacci il suo braccio sul tavolo! Vittoria!",
    "inn.arm_wrestle_you_lose": "{0} ti inchioda il braccio! Sconfitta!",
    "inn.arm_wrestle_gold_won": "Hai vinto {0} oro!",
    "inn.arm_wrestle_gold_lost": "Hai perso {0} oro!",
    "inn.arm_wrestle_str_bonus": "La forza del tuo braccio migliora! (+1 FOR)",
    "inn.arm_wrestle_no_opponents": "Nessuno vuole fare braccio di ferro in questo momento.",
    "inn.rent_title": "AFFITTA UNA STANZA",
    "inn.rent_cost": "Una stanza costa {0} oro a notte.",
    "inn.rent_prompt": "Affittare una stanza e disconnettersi? (S/N): ",
    "inn.rent_cant_afford": "  Non puoi permettertelo!",
    "inn.rent_settling_in": "Ti sistemi nella tua stanza per la notte...",
    "inn.rent_game_saved": "Partita salvata. Sogni d'oro!",
    "inn.rent_logging_out": "Disconnessione in corso...",
    "inn.attack_sleeper_title": "ATTACCA UN DORMIENTE",
    "inn.attack_sleeper_desc": "I seguenti avventurieri stanno dormendo alla locanda:",
    "inn.attack_sleeper_no_one": "Nessuno sta dormendo alla locanda in questo momento.",
    "inn.attack_sleeper_select": "Seleziona bersaglio # (o Invio per uscire): ",
    "inn.attack_sleeper_npc_entry": "  {0}. {1} — Livello {2} {3}",
    "inn.attack_sleeper_confirm": "Attaccare {0} nel sonno? (S/N): ",
    "inn.attack_sleeper_cowardly": "Ti avvicini furtivamente all'avventuriero addormentato...",
    "inn.attack_sleeper_guard_blocks": "La guardia di {0}, {1}, blocca il tuo attacco!",
    "inn.attack_sleeper_guard_defeated": "Hai sconfitto la guardia di {0}!",
    "inn.attack_sleeper_guard_wins": "La guardia di {0} ti ha sconfitto! Te ne vai via pieno di vergogna.",
    "inn.attack_sleeper_wakes": "{0} si sveglia e reagisce!",
    "inn.attack_sleeper_victory": "Hai sconfitto {0} nel sonno!",
    "inn.attack_sleeper_gold_stolen": "Hai rubato {0} oro!",
    "inn.attack_sleeper_item_stolen": "Hai rubato il loro {0}!",
    "inn.attack_sleeper_xp_gained": "Hai guadagnato {0} PE per l'atto vile.",
    "inn.attack_sleeper_defeat": "{0} ti ha respinto! Ti ritiri nella vergogna.",
    "inn.attack_sleeper_alignment_shift": "Il tuo allineamento si sposta verso il male.",
    "inn.attack_sleeper_killed": "Hai ucciso {0} nel sonno!",
    "inn.attack_sleeper_mercy": "Decidi di mostrare pietà e te ne vai.",
    "inn.npc_level_class": "Livello {0} {1}",
    "inn.npc_knocks_unconscious": "{0} ti stende privo di sensi!",
    "inn.giving_gift": "Fai un regalo a {0}",
    "inn.relationship_improves": "(La vostra relazione migliora notevolmente!)",
    "inn.gift_cost": "(-50 oro)",
    "inn.mood_aggressive": "Sembra aggressivo e pericoloso.",
    "inn.mood_friendly": "Sembra amichevole e accessibile.",
    "inn.mood_tired": "Sembra stanco e provato dalla battaglia.",
    "inn.mood_relaxed": "Sembra rilassato e a suo agio.",
    "inn.rel_married": "Sposato",
    "inn.rel_in_love": "Innamorato",
    "inn.rel_close_friend": "Amico Intimo",
    "inn.rel_neutral": "Neutrale",
    "inn.rel_disliked": "Antipatico",
    "inn.rel_hated": "Nemico Odiato",
    "inn.drinking_need_gold": "Ti servono almeno 20 monete d'oro per partecipare alla gara di bevute!",
    "inn.drinking_not_enough_patrons": "Non ci sono abbastanza avventori al bar per una gara!",
    "inn.drinking_jump_bar": "  Salti sul bancone del bar!",
    "inn.drinking_challenge_shout": "  \"Avanti branco di ubriaconi pigri! Vi sfido a una gara di bevute!\"",
    "inn.drinking_silence": "  Cala un silenzio improvviso nella stanza",
    "inn.drinking_rowdy_approach": "  Poi un gruppo di personaggi turbolenti si fa avanti verso di te...",
    "inn.drinking_choose_drink": "  Scegli la Tua Bevanda da Competizione:",
    "inn.drink_ale_desc": "Birra           - Tranquilla, più turni da sopravvivere",
    "inn.drink_stout_desc": "Birra Scura     - Una scelta solida per bevitori seri",
    "inn.drink_bomber_desc": "Bomba di Seth   - Carburante! Solo i coraggiosi osano...",
    "inn.drinking_favourite": "  Il favorito in questa gara è... ",
    "inn.drinking_round": "  === Turno di Bevute #{0} ===   ({1} concorrenti rimasti)",
    "inn.drinking_drink_name": "  Bevanda: {0}",
    "inn.drinking_soberness": "  La tua sobrietà: {0}",
    "inn.drinking_down": " Giù il boccale!",
    "inn.drinking_bow_out": " Cerca di ritirarti con grazia",
    "inn.drinking_what_do": "  Che fai? ",
    "inn.drinking_bow_success1": "  Ti alzi in piedi con fermezza e fai un inchino alla folla.",
    "inn.drinking_bow_success2": "  \"Conosco i miei limiti, amici. Buona fortuna a tutti!\"",
    "inn.drinking_bow_success3": "  La folla concede un applauso cortese, seppur deluso.",
    "inn.drinking_bow_fail1": "  Cerchi di alzarti ma le gambe ti tremano...",
    "inn.drinking_bow_fail2": "  \"Siediti! Non vai da nessuna parte!\"",
    "inn.drinking_bow_fail3": "  La folla ti ficca un altro bicchiere in mano!",
    "inn.drinking_take_beer": "  Prendi la tua birra...",
    "inn.drinking_spinning": "  La stanza gira!",
    "inn.drinking_laughter": "  Senti risate malevole mentre barcolli per la stanza...",
    "inn.drinking_fall": "  ...e infine cadi pesantemente a terra!",
    "inn.drinking_failed": "  Non ce l'hai fatta, ratto ubriacone!",
    "inn.drinking_takes_his": " prende la sua birra...",
    "inn.drinking_takes_her": " prende la sua birra...",
    "inn.drinking_opp_reels": " comincia a barcollare in preda ai fumi!",
    "inn.drinking_opp_falls": "  Tutti ridono mentre {0} barcolla e crolla a terra!",
    "inn.drinking_bites_dust": "  Un altro che morde la polvere!",
    "inn.drinking_soberness_eval": "  --- Valutazione Sobrietà del Turno ---",
    "inn.contest_lasted": "  La gara è durata {0} turni di {1}.",
    "inn.contest_congrats": "  Congratulazioni!",
    "inn.contest_stayed_sober": "  Sei riuscito a restare sobrio più a lungo degli altri!",
    "inn.contest_three_cheers": "  Tre evviva per il Campione di Bevute! ",
    "inn.contest_xp_reward": "  Ricevi {0:N0} punti esperienza!",
    "inn.contest_gold_reward": "  Vinci {0:N0} oro dal montepremi!",
    "inn.contest_passed_out": "  Sei svenuto al turno {0}!",
    "inn.contest_headache": "  Ti svegli più tardi con un tremendo mal di testa.",
    "inn.contest_winner": "  {0} ha vinto la gara dopo {1} turni!",
    "inn.contest_no_winner": "  Nessuno è riuscito a restare in piedi! Non c'è un vincitore.",
    "inn.contest_consolation_xp": "  Hai guadagnato {0:N0} esperienza per aver partecipato.",
    "inn.sober_sober": "Sobrio",
    "inn.sober_tipsy": "Brillo",
    "inn.sober_dizzy": "Stordito",
    "inn.sober_wasted": "Distrutto",
    "inn.sober_blind_drunk": "Ubriaco Fradicio!",
    "inn.sleep_not_late": "Non è abbastanza tardi per dormire. Prova ad aspettare fino a sera.",
    "inn.sleep_room_shown": "Il locandiere ti mostra una piccola stanza al piano di sopra...",
    "inn.sleep_dark_memories": "Ricordi oscuri invadono i tuoi sogni, lasciandoti meno riposato...",
    "inn.sleep_refreshed": "Ti svegli completamente riposato!",
    "inn.sleep_recover_mana": "Recuperati {0} HP, {1} mana. ({2}% di recupero)",
    "inn.sleep_recover_stamina": "Recuperati {0} HP, {1} stamina. ({2}% di recupero)",
    "inn.sleep_dreams_unfold": "Mentre il sonno ti avvolge, i sogni prendono forma...",
    "inn.sleep_drift_off": "Ti addormenti...",
    "inn.food_hearty_meal": "Ordini un pasto abbondante di carne arrosto e pane.",
    "inn.food_stamina_boost": "Il cibo riempie il tuo stomaco e rinvigorisce la tua stamina!",
    "inn.food_hp_recover": "Recuperi anche {0} HP dal pasto nutriente.",
    "inn.no_companions_available": "Non ci sono stranieri in cerca di compagni d'avventura al momento.",
    "inn.companions_watching": "Negli angoli bui della locanda, diverse figure sembrano osservarti...",
    "inn.return_to_bar": " Torna al bar",
    "inn.approach_who": "Chi vuoi avvicinare? ",
    "inn.you_approach": "Ti avvicini a {0}, {1}...",
    "inn.greetings_traveler": "\"Salve, viaggiatore. Sembri uno che potrebbe aver bisogno d'aiuto...\"",
    "inn.background_label": "Passato: {0}",
    "inn.combat_role_label": "Ruolo in Combattimento: {0}",
    "inn.abilities_label": "Abilità: {0}",
    "inn.recruit_companion": "Recluta questo compagno",
    "inn.talk_more": "Parla ancora per saperne di più",
    "inn.leave_them_be": "Lascialo in pace",
    "inn.companion_joined": "{0} si è unito a te come compagno!",
    "inn.companion_fight_by_side": "Ti accompagnerà nei sotterranei e combatterà al tuo fianco.",
    "inn.companion_die_warning": "ATTENZIONE: I compagni possono morire permanentemente. Proteggili bene.",
    "inn.companion_shares_story": "{0} racconta la sua storia...",
    "inn.personal_quest_label": "Missione Personale: {0}",
    "inn.nod_return": "Annuisci a {0} e torni al bar.",
    "inn.no_companions_yet": "Non hai ancora nessun compagno.",
    "inn.active_companions": "COMPAGNI ATTIVI ({0}/{1}):",
    "inn.no_active_companions": "(Nessun compagno attivo - seleziona dalle riserve sotto)",
    "inn.reserve_companions": "COMPAGNI IN RISERVA:",
    "inn.fallen_companions": "COMPAGNI CADUTI:",
    "inn.died_label": "Morto: {0}",
    "inn.options": "Opzioni:",
    "inn.talk_to": "Parla con {0}",
    "inn.switch_companions": "Cambia compagni attivi",
    "inn.companion_limit": "Puoi avere fino a {0} compagni attivi nel sotterraneo.",
    "inn.companion_warning": "I compagni attivi combattono al tuo fianco ma possono essere feriti o uccisi.",
    "inn.select_to_activate": "Seleziona i compagni da attivare (inserisci i numeri separati da spazi):",
    "inn.example_activate": "Esempio: '1 3' per attivare i compagni 1 e 3",
    "inn.enter_nothing": "Non inserire nulla per mantenere la selezione attuale",
    "inn.activate_prompt": "Attiva: ",
    "inn.no_changes": "Nessuna modifica apportata.",
    "inn.no_valid_selected": "Nessun compagno valido selezionato. Nessuna modifica apportata.",
    "inn.party_updated": "Gruppo aggiornato!",
    "inn.now_active": "{0} è ora attivo.",
    "inn.update_failed": "Aggiornamento del gruppo fallito.",
    "inn.background": "Passato:",
    "inn.stats": "Statistiche:",
    "inn.level_role": "Livello: {0} | Ruolo: {1}",
    "inn.hp_atk_def": "HP: {0}  |  ATT: {1}  |  DIF: {2}",
    "inn.items_equipped": "({0} oggett{1} equipaggiato/i — le statistiche includono i bonus dell'equipaggiamento)",
    "inn.begin_quest": "Inizia Missione Personale: {0}",
    "inn.discuss_progress": "Discuti il Progresso della Missione",
    "inn.deepen_bond_today": "Rafforza il legame (già visitato oggi)",
    "inn.spend_time_max": "Passa del tempo insieme (Legame massimo)",
    "inn.deepen_bond": "Rafforza il tuo legame...",
    "inn.give_a_gift": "Fai un regalo",
    "inn.view_history": "Visualizza la storia insieme",
    "inn.manage_equipment": "Gestisci Equipaggiamento",
    "inn.manage_skills": "Gestisci Abilità di Combattimento",
    "inn.speaks_quietly": "{0} parla a bassa voce:",
    "inn.accept_quest": "Accetta questa missione",
    "inn.not_yet": "Non ancora",
    "inn.will_you_help": "Mi aiuterai? ",
    "inn.quest_begun": "Missione Iniziata: {0}",
    "inn.nods_gratefully": "{0} annuisce con gratitudine.",
    "inn.quest_in_progress": "Stato Missione: In Corso",
    "inn.seek_clues": "Cerca indizi nelle profondità del sotterraneo...",
    "inn.already_spent_time": "Hai già passato del tempo con {0} oggi.",
    "inn.perhaps_tomorrow": "Forse domani potrete condividere un altro momento insieme.",
    "inn.quiet_corner": "Tu e {0} trovate un angolo tranquillo per parlare.",
    "inn.tavern_fades": "Il rumore della taverna sfuma in un mormorio di sottofondo.",
    "inn.romance_1": "Condividi un momento di comprensione con {0}.",
    "inn.romance_2": "I vostri occhi si incontrano, e qualcosa di inespresso passa tra voi.",
    "inn.romance_3": "La mano di {0} sfiora la tua.",
    "inn.romance_4": "Il mondo sembra restringersi a solo voi due.",
    "inn.romance_5": "{0} si avvicina, con voce sommessa.",
    "inn.romance_default": "Il legame tra te e {0} si approfondisce.",
    "inn.bond_max": "Il tuo legame con {0} è più profondo che mai.",
    "inn.bond_stronger": "Il vostro legame si è rafforzato.",
    "inn.seems_distracted": "Godetevi il momento, ma {0} sembra distratto stasera.",
    "inn.higher_cha": "(Un Carisma più alto migliora le tue possibilità)",
    "inn.build_trust": "(Costruisci più fiducia prima di approfondire questo legame)",
    "inn.gift_options": "Opzioni Regalo:",
    "inn.gift_simple": "Regalo Semplice (50 oro) - +3 lealtà",
    "inn.gift_fine": "Regalo Raffinato (200 oro) - +8 lealtà",
    "inn.gift_rare": "Regalo Raro (500 oro) - +15 lealtà",
    "inn.cancel": "Annulla",
    "inn.choose": "Scegli: ",
    "inn.give_gift_desc": "Dai a {0} {1}.",
    "inn.gift_smile": "{0} sorride calorosamente. (+{1} lealtà)",
    "inn.gift_trinket": "un grazioso ninnolo",
    "inn.gift_jewelry": "un gioiello raffinato",
    "inn.gift_artifact": "un artefatto raro",
    "inn.history_with": "Storia con {0}",
    "inn.journey_begun": "Il vostro viaggio insieme è appena iniziato...",
    "inn.days_together": "Giorni insieme: {0}",
    "inn.total_loyalty": "Lealtà totale guadagnata: {0}%",
    "inn.current_equipment": "Equipaggiamento Attuale:",
    "inn.equip_from_inventory": "Equipaggia oggetto dal tuo inventario",
    "inn.unequip_item": "Rimuovi oggetto da loro",
    "inn.take_all_equipment": "Prendi tutto il loro equipaggiamento",
    "inn.done_return": "Fatto / Torna",
    "inn.available_equipment": "Equipaggiamento disponibile:",
    "inn.select_item": "Seleziona oggetto (0 per annullare): ",
    "inn.must_identify": "Devi identificare questo oggetto prima di darlo a un compagno.",
    "inn.cannot_use": "{0} non può usare questo oggetto: {1}",
    "inn.which_hand": "Quale mano?",
    "inn.main_hand": "Mano principale",
    "inn.off_hand": "Mano secondaria",
    "inn.equipped_item": "{0} ha equipaggiato {1}!",
    "inn.failed_equip": "Equipaggiamento fallito: {0}",
    "inn.equipped_items": "Oggetti equipaggiati:",
    "inn.select_unequip": "Seleziona slot da rimuovere (0 per annullare): ",
    "inn.cursed_cannot_remove": "{0} è maledetto e non può essere rimosso!",
    "inn.took_from": "Preso {0} da {1}.",
    "inn.added_inventory": "Oggetto aggiunto al tuo inventario.",
    "inn.failed_unequip": "Rimozione oggetto fallita.",
    "inn.take_all_confirm": "Prendere TUTTO l'equipaggiamento da {0}?",
    "inn.leave_nothing": "Rimarrà senza nulla. Confermi (S/N): ",
    "inn.took_items": "Preso {0} oggett{1} da {2}.",
    "inn.no_equipment_to_take": "{0} non aveva equipaggiamento da prendere.",
    "inn.cursed_not_removed": "Impossibile rimuovere oggetti maledetti: {0}",
    "inn.using_2h": "(usa arma a 2 mani)",
    "inn.empty_slot": "(vuoto)",
    "inn.no_abilities": "Nessuna abilità di combattimento disponibile ancora.",
    "inn.toggle_ability": "Attiva/disattiva abilità",
    "inn.enable_all": "Attiva tutte",
    "inn.all_enabled": "Tutte le abilità attivate!",
    "inn.enabled": "Attivata: {0}",
    "inn.disabled": "Disattivata: {0}",
    "inn.trainer_intro1": "Un veterano coperto di cicatrici siede nell'angolo, affilando metodicamente una lama.",
    "inn.trainer_intro2": "Alza lo sguardo al tuo avvicinarti.",
    "inn.trainer_quote1": "\"Vuoi diventare più forte? Posso aiutarti — a un prezzo.\"",
    "inn.trainer_quote2": "\"Ogni sessione spinge il tuo corpo e la tua mente oltre i limiti naturali.\"",
    "inn.trainer_quote3": "\"Ma più andiamo a fondo, più diventa difficile — e più costa.\"",
    "inn.train_header": "# Stat. Attuale Addestrato Prossimo Costo",
    "inn.your_gold": "Il Tuo Oro: {0}",
    "inn.train_prompt": "Scegli statistica da addestrare (1-8, 0 per uscire): ",
    "inn.stat_maxed_quote": "\"La tua {0} è stata spinta al limite di ciò che l'addestramento può ottenere.\"",
    "inn.find_other_ways": "\"Dovrai trovare altri modi per diventare più forte.\"",
    "inn.need_gold_train": "Ti servono {0} oro ma ne hai solo {1}.",
    "inn.come_back_afford": "\"Torna quando potrai permetterti i miei servizi.\"",
    "inn.need_materials": "\"Questo livello di addestramento richiede materiali rari per superare i tuoi limiti.\"",
    "inn.missing_material": "Mancante: {0}x {1}",
    "inn.materials_dungeon": "Questi materiali si trovano nelle profondità del sotterraneo.",
    "inn.material_dissolves": "{0} si dissolve nel tuo corpo, alimentando la trasformazione...",
    "inn.pay_trainer": "Paghi il Maestro Addestratore {0} oro.",
    "inn.train_str": "Ore di sollevamento, trazione e distruzione più tardi...",
    "inn.train_dex": "Schivare coltelli lanciati, afferrare monete in volo, infilare aghi...",
    "inn.train_con": "Corse di resistenza, bagni di ghiaccio e un tonico alle erbe davvero orribile...",
    "inn.train_int": "Enigmi, giochi di strategia e testi antichi finché la testa non pulsa...",
    "inn.train_wis": "Meditazione, esercizi di percezione e imparare ad ascoltare il silenzio...",
    "inn.train_cha": "Parlare in pubblico, esercizi di negoziazione e un taglio di capelli molto costoso...",
    "inn.train_agi": "Percorsi a ostacoli, travi d'equilibrio e salti su cose sempre più taglienti...",
    "inn.train_sta": "Correre fino a crollare, e poi correre ancora...",
    "inn.stat_increased": "La tua {0} è aumentata a {1}! (+1)",
    "inn.sessions_remaining": "\"Buon lavoro. Hai ancora {0} sessioni disponibili per {1}.\"",
    "inn.gambling_intro1": "Scendi una scala stretta in una stanza fumosa sotto la Locanda.",
    "inn.gambling_intro2": "Il tintinnio dei dadi e il mormorio delle scommesse riempiono l'aria.",
    "inn.games_available": "Giochi Disponibili:",
    "inn.game_highlow": "Dadi Alto-Basso    (Indovina più alto o più basso, vincita 1.8x)",
    "inn.game_skulls": "Teschio e Ossa     (Blackjack con tessere d'osso, vincita 2x)",
    "inn.game_arm_wrestling": "Braccio di Ferro   (Sfida di FOR vs PNG, {0}/{1} oggi)",
    "inn.choose_game": "Scegli un gioco (0 per uscire): ",
    "inn.no_gold_wager": "Non hai oro da scommettere!",
    "inn.gold_on_hand": "Oro in mano: {0}",
    "inn.how_much_wager": "Quanto vuoi scommettere? ",
    "inn.invalid_bet": "Scommessa non valida.",
    "inn.not_enough_gold_wager": "Non hai abbastanza oro!",
    "inn.dealer_rolls": "Il mazziere tira: [{0}]",
    "inn.next_roll_higher_lower": "Il prossimo tiro sarà ",
    "inn.invalid_forfeited": "Scelta non valida. Scommessa persa.",
    "inn.next_roll": "Il prossimo tiro: [{0}]",
    "inn.tie_returned": "Parità! La tua scommessa è restituita.",
    "inn.you_win": "Hai vinto! +{0} oro!",
    "inn.double_nothing": "Raddoppia o niente? Piatto attuale: {0}g ",
    "inn.max_double_down": "Massimo di raddoppi raggiunto. Si riscuotono le vincite!",
    "inn.you_lose": "Hai perso! -{0} oro.",
    "inn.gold_remaining": "Oro rimanente: {0}",
    "inn.bones_rules1": "Regole: Pesca tessere d'osso per raggiungere 21 senza superarlo.",
    "inn.bones_rules2": "Tessere speciali (Teschio, Corona, Spada) = 10. Il mazziere sta a 17.",
    "inn.your_tiles": "Le tue tessere: {0} = {1}",
    "inn.natural_21": "TESCHIO E OSSA! 21 naturale!",
    "inn.you_drew": "Hai pescato: {0} ({1}) — Totale: {2}",
    "inn.bust": "SBALLATO! Hai superato 21.",
    "inn.bust_lose": "Hai perso {0} oro. Rimanente: {1}",
    "inn.dealer_turn": "Turno del mazziere...",
    "inn.dealer_total": "Totale del mazziere: {0}",
    "inn.dealer_busts": "Il mazziere sballa! Hai vinto {0} oro!",
    "inn.bones_beats": "Teschio e Ossa batte il mazziere! Hai vinto {0} oro!",
    "inn.beat_dealer": "Hai battuto il mazziere! Hai vinto {0} oro!",
    "inn.push": "Parità! Scommessa restituita.",
    "inn.dealer_wins": "Il mazziere vince. Hai perso {0} oro.",
    "inn.enough_today": "\"Ne hai avuto abbastanza per oggi, amico. Torna domani.\"",
    "inn.no_arm_wrestling": "Nessuno sembra interessato al braccio di ferro in questo momento.",
    "inn.challenger_slams": "{0} (Livello {1}, FOR {2}) sbatte il",
    "inn.challenger_grins": "gomito sul tavolo e ti sorride beffardo.",
    "inn.gold_says": "\"{0} monete d'oro che ti butto giù.\"",
    "inn.need_gold_challenge": "Ti servono {0} oro per accettare la sfida.",
    "inn.accept_challenge": "Accetti la sfida? ({0}g) ",
    "inn.back_away": "Ti allontani dal tavolo.",
    "inn.clasp_hands": "Vi afferrate le mani...",
    "inn.three_two_one": "Tre... due... uno... VIA!",
    "inn.slam_arm": "Schiacci il braccio di {0} sul tavolo!",
    "inn.win_gold": "Hai vinto {0} oro!",
    "inn.opponent_forces": "{0} ti forza il braccio giù con un grugnito!",
    "inn.lose_gold": "Hai perso {0} oro.",
    "inn.draw_match": "Nessuno dei due si muove! È un pareggio.",
    "inn.matches_today": "Incontri di braccio di ferro oggi: {0}/{1}",
    "inn.need_gold_room": "Ti servono {0} oro per una stanza. Hai {1} in mano e {2} in banca.",
    "inn.room_cost": "Costo stanza: {0} oro",
    "inn.room_healed": "Verrai curato completamente e disconnesso in sicurezza.",
    "inn.room_bonus": "Dormire alla Locanda garantisce +50% ATT/DIF se vieni attaccato.",
    "inn.guards_hired": "Guardie assunte: {0}/{1}",
    "inn.done_hiring": "Finito di assumere",
    "inn.cant_afford_guard": "Non puoi permetterti quella guardia.",
    "inn.hired_guard": "Assunta {0}! (HP: {1})",
    "inn.total_cost": "Costo totale: {0} oro (Stanza: {1} + Guardie: {2})",
    "inn.rent_confirm": "  Affittare questa stanza e disconnettersi? (s/N): ",
    "inn.decide_not_rent": "Decidi di non affittare una stanza.",
    "inn.cant_afford": "Non puoi permettertelo!",
    "inn.bank_withdrawn": "({0}g prelevati dal tuo conto in banca)",
    "inn.shadow_fades": "La Benedizione delle Ombre svanisce mentre riposi...",
    "inn.room_private": "Il locandiere ti mostra una stanza privata al piano superiore.",
    "inn.room_lock": "Chiudi a chiave la pesante porta e crolli su un vero letto.",
    "inn.guards_position": "Le tue {0} guardi{1} si posizionano fuori dalla porta.",
    "inn.deep_sleep": "Sprofondii in un sonno profondo e protetto... (disconnessione)",
    "inn.no_sleepers": "Nessun dormiente vulnerabile alla Locanda.",
    "inn.sleeping_guests": "Locanda — Ospiti Addormentati",
    "inn.sleeping_npc": "PNG ADDORMENTATO",
    "inn.sleeping_player": "GIOCATORE ADDORMENTATO",
    "inn.who_attack": "Chi attacchi? (numero o nome, vuoto per annullare): ",
    "inn.no_such_sleeper": "Nessun dormiente con quel nome.",
    "inn.no_longer_here": "Non sono più qui.",
    "inn.pick_lock": "Forzi la serratura della stanza di {0} alla Locanda...",
    "inn.steal_gold": "Rovisti tra i loro averi e rubi {0} oro!",
    "inn.leave_body": "Lasci il corpo di {0} nella stanza.",
    "inn.fought_off": "{0} ti ha respinto — le spesse mura della Locanda hanno attutito il trambusto!",
    "inn.sneak_toward": "Ti intrufoli verso la stanza di {0} alla Locanda...",
    "inn.guard_blocks": "Un {0} ti blocca la strada!",
    "inn.cut_down_guard": "Abbatti il {0}!",
    "inn.guard_drives_back": "Il {0} ti respinge! Attacco fallito!",
    "inn.reach_target": "Raggiungi {0}...",
    "inn.steal_item": "Prendi anche il loro {0}!",
    "inn.fought_off_sleep": "{0} ti ha respinto persino nel sonno!",
    "inn.standing_plummeted": "La tua reputazione con {0} è crollata! ({1})",
    "inn.not_available": "Non disponibile.",
    "inn.could_not_load": "Impossibile caricare i loro dati.",
    "inn.sb_rules1": "Regole: Pesca tessere d'osso per raggiungere 21 senza superarlo.",
    "inn.sb_rules2": "Tessere speciali (Teschio, Corona, Spada) = 10. Il mazziere sta a 17.",
    "inn.not_enough_gold_bet": "Non hai abbastanza oro!",
    "inn.sb_your_tiles": "Le tue tessere: {0} = {1}",
    "inn.sb_natural21": "TESCHIO E OSSA! 21 naturale!",
    "inn.sb_hit": "[H]",
    "inn.sb_or": "it o ",
    "inn.sb_stand": "[S]",
    "inn.sb_drew": "Hai pescato: {0} ({1}) — Totale: {2}",
    "inn.sb_bust": "SBALLATO! Hai superato 21.",
    "inn.sb_bust_lose": "Hai perso {0} oro. Rimanente: {1}",
    "inn.sb_dealer_turn": "Turno del mazziere...",
    "inn.sb_dealer_total": "Totale del mazziere: {0}",
    "inn.sb_dealer_busts": "Il mazziere sballa! Hai vinto {0} oro!",
    "inn.sb_beats_dealer": "Teschio e Ossa batte il mazziere! Hai vinto {0} oro!",
    "inn.sb_you_beat": "Hai battuto il mazziere! Hai vinto {0} oro!",
    "inn.sb_push": "Parità! Scommessa restituita.",
    "inn.sb_dealer_wins": "Il mazziere vince. Hai perso {0} oro.",
    "inn.aw_enough_today": "\"Ne hai avuto abbastanza per oggi, amico. Torna domani.\"",
    "inn.aw_no_interested": "Nessuno sembra interessato al braccio di ferro in questo momento.",
    "inn.aw_challenger_slams": "{0} (Livello {1}, FOR {2}) sbatte il",
    "inn.aw_challenger_grins": "gomito sul tavolo e ti sorride beffardo.",
    "inn.aw_wager_challenge": "\"{0} monete d'oro che ti butto giù.\"",
    "inn.aw_need_gold": "Ti servono {0} oro per accettare la sfida.",
    "inn.aw_accept_challenge": "Accetti la sfida? ({0}g) ",
    "inn.aw_back_away": "Ti allontani dal tavolo.",
    "inn.aw_clasp_hands": "Vi afferrate le mani...",
    "inn.aw_three_two_one": "Tre... due... uno... VIA!",
    "inn.aw_you_slam": "Schiacci il braccio di {0} sul tavolo!",
    "inn.aw_you_win": "Hai vinto {0} oro!",
    "inn.aw_they_slam": "{0} ti forza il braccio giù con un grugnito!",
    "inn.aw_you_lose": "Hai perso {0} oro.",
    "inn.aw_draw": "Nessuno dei due si muove! È un pareggio.",
    "inn.aw_matches_today": "Incontri di braccio di ferro oggi: {0}/{1}",
    "inn.rent_need_gold": "Ti servono {0} oro per una stanza. Hai {1} in mano e {2} in banca.",
    "inn.rent_room_cost": "\n  Costo stanza: {0} oro",
    "inn.rent_healed_logout": "  Verrai curato completamente e disconnesso in sicurezza.",
    "inn.rent_sleep_bonus": "  Dormire alla Locanda garantisce +50% ATT/DIF se vieni attaccato.\n",
    "inn.rent_guards_hired": "  Guardie assunte: {0}/{1}",
    "inn.rent_done_hiring": " Finito di assumere",
    "inn.rent_gold_summary": "\n  Il tuo oro: {0} (banca: {1})  |  Stanza: {2}  |  Guardie: {3}  |  Totale: {4}",
    "inn.rent_cant_afford_guard": "  Non puoi permetterti quella guardia.",
    "inn.rent_hired_guard": "  Assunta {0}! (HP: {1})",
    "inn.rent_total_cost": "\n  Costo totale: {0} oro (Stanza: {1} + Guardie: {2})",
    "inn.rent_cancelled": "  Decidi di non affittare una stanza.",
    "inn.rent_bank_withdraw": "  ({0}g prelevati dal tuo conto in banca)",
    "inn.rent_shadow_fades": "  La Benedizione delle Ombre svanisce mentre riposi...",
    "inn.rent_room_desc1": "\n  Il locandiere ti mostra una stanza privata al piano superiore.",
    "inn.rent_room_desc2": "  Chiudi a chiave la pesante porta e crolli su un vero letto.",
    "inn.rent_guards_position": "  Le tue {0} guardie si posizionano fuori dalla porta.",
    "inn.rent_deep_sleep": "\n  Sprofondii in un sonno profondo e protetto... (disconnessione)",
    "inn.atk_not_available": "Non disponibile.",
    "inn.atk_no_sleepers": "Nessun dormiente vulnerabile alla Locanda.",
    "inn.atk_sleeping_guests": "Locanda — Ospiti Addormentati",
    "inn.atk_who_attack": "\nChi attacchi? (numero o nome, vuoto per annullare): ",
    "inn.atk_no_such_sleeper": "Nessun dormiente con quel nome.",
    "inn.atk_no_longer_here": "Non sono più qui.",
    "inn.atk_pick_lock": "\n  Forzi la serratura della stanza di {0} alla Locanda...\n",
    "inn.atk_steal_gold": "Rovisti tra i loro averi e rubi {0} oro!",
    "inn.atk_leave_body": "\nLasci il corpo di {0} nella stanza.",
    "inn.atk_faction_plummet": "La tua reputazione con {0} è crollata! (-250)",
    "inn.atk_fought_off": "{0} ti ha respinto — le spesse mura della Locanda hanno attutito il trambusto!",
    "inn.atk_cant_load": "Impossibile caricare i loro dati.",
    "inn.atk_sneak_toward": "\n  Ti intrufoli verso la stanza di {0} alla Locanda...\n",
    "inn.atk_guard_blocks": "\n  Un {0} ti blocca la strada!",
    "inn.atk_cut_down_guard": "  Abbatti il {0}!",
    "inn.atk_guard_repels": "  Il {0} ti respinge! Attacco fallito!",
    "inn.atk_reach_target": "\n  Raggiungi {0}...\n",
    "inn.atk_steal_item": "Prendi anche il loro {0}!",
    "inn.atk_player_fought_off": "{0} ti ha respinto persino nel sonno!",
    "inn.drinking_glugg": "Glugg...",
    "inn.drinking_glugg_end": "Glugg...!",
    "inn.drinking_you_dash": "  Tu - ",
    "inn.drinking_hooray": "...Evviva! ",
    "inn.drinking_hooray_end": "...Evviva!",
    "inn.loyalty_label": "    Lealtà: ",
    "inn.trust_label": " | Fiducia: ",
    "inn.active_label": " [ATTIVO]",
    "inn.using_2h_weapon": "(usa arma a 2 mani)",
    "inn.slot_empty": "(vuoto)",
    "inn.which_hand_pre": "Quale mano? [",
    "inn.which_hand_mid": "]ano principale o [",
    "inn.which_hand_post": "]ano secondaria?",
    "inn.cursed_label": " (MALEDETTO)",
    "inn.no_abilities_yet": "Nessuna abilità di combattimento disponibile ancora.",
    "inn.all_abilities_enabled": "Tutte le abilità attivate!",
    "inn.hl_will_next_be": "Il prossimo tiro sarà ",
    "inn.hl_igher_or": "iù alto o ",
    "inn.hl_ower": "iù basso? ",
    "castle.header_num": "#",
    "castle.header_name": "Nome",
    "castle.header_rank": "Grado",
    "castle.header_loyalty": "Lealtà",
    "castle.header_crime": "Crimine",
    "castle.header_days_left": "Giorni Rim.",
    "castle.header_sentence": "Condanna",
    "castle.header_served": "Scontati",
    "castle.header_bail": "Cauzione",
    "castle.header_type": "Tipo",
    "castle.header_from": "Da",
    "castle.header_subject": "Oggetto",
    "castle.header_status": "Stato",
    "castle.header_salary": "Salario",
    "castle.header_level": "Livello",
    "castle.header_hp": "HP",
    "castle.header_strength": "Forza",
    "castle.header_lvl": "Liv",
    "castle.header_str": "FOR",
    "castle.header_def": "DIF",
    "castle.header_cost": "Costo",
    "castle.header_feed": "Cibo/Giorno",
    "castle.header_title": "Titolo",
    "castle.header_reign": "Regno",
    "castle.header_end": "Fine",
    "castle.header_age": "Età",
    "castle.header_sex": "Sesso",
    "castle.header_claim": "Diritto",
    "castle.header_race": "Razza",
    "castle.header_happy": "Felicità",
    "castle.header_dowry": "Dote",
    "castle.header_faction_benefit": "Beneficio Fazione",
    "castle.header_faction": "Fazione",
    "castle.header_influence": "Influenza",
    "castle.header_role": "Ruolo",
    "castle.royal_decree": "Per decreto reale di {0} {1}:",
    "castle.orphan_summary": "Orfani: {0}/{1}   Costo giornaliero di mantenimento: {2} oro ({3} per bambino)",
    "castle.orphan_age_sex_happy": "  Età: {0}   Sesso: {1}   Felicità: {2}%",
    "castle.orphan_type_orphaned": "  Tipo: Orfano (entrambi i genitori deceduti)",
    "castle.orphan_arrived": "  Arrivato: {0}",
    "castle.orphan_no_eligible": "Nessun vero orfano di età {0}+ disponibile per l'arruolamento.",
    "castle.orphan_insuff_treasury": "Fondi del tesoro insufficienti! Servono {0} oro per i costi di addestramento.",
    "castle.orphan_entry": "  {0}. {1} (Età {2}, {3}, {4})",
    "castle.orphan_commission_as": "Arruola {0} come:",
    "castle.orphan_treasury_minus": "Tesoro: -{0} oro",
    "castle.orphan_merc_insuff": "Fondi del tesoro insufficienti! Servono {0} oro.",
    "castle.orphan_full": "L'orfanotrofio è pieno ({0} bambini).",
    "castle.orphan_adopt_insuff": "Fondi del tesoro insufficienti! Servono {0} oro per coprire i costi di accoglienza.",
    "castle.orphan_treasury_balance": "Tesoro: {0} oro",
    "castle.orphan_happy_boost": "La felicità degli orfani è aumentata del {0}%!",
    "castle.already_married": "Sei già sposato con {0}.",
    "castle.married_on": "Sposato il: {0}",
    "castle.spouse_happiness": "Felicità del coniuge: {0}%",
    "castle.original_faction": "Fazione originale: {0}",
    "castle.send_proposal": "Invii una proposta reale a {0}...",
    "castle.dowry_received": "Dote ricevuta: {0} oro!",
    "castle.faction_loyalty_up": "La lealtà della fazione {0} è aumentata!",
    "castle.spouse_pleased": "Il tuo coniuge è compiaciuto! Felicità +{0}%",
    "castle.faction_turn_against": "La fazione {0} si rivolterà contro di te.",
    "castle.divorced": "Hai divorziato da {0}.",
    "castle.faction_furious": "La fazione {0} è furiosa!",
    "castle.foiled_plot": "SVENTATO: complotto di {0} da parte di {1}",
    "castle.spies_report": "Le tue spie riportano {0} voc(i) d'intrigo...",
    "castle.arrested": "I cospiratori sono stati arrestati e imprigionati! (-{0}g)",
    "castle.promote_which": "Promuovere quale membro della corte? (Costo: {0}g dal tesoro)",
    "castle.current_heir": "Erede designato attuale: {0}",
    "castle.max_bodyguards": "Guardie del corpo massime: {0}",
    "castle.max_bodyguards_already": "Hai già {0} guardie del corpo — il massimo consentito.",
    "castle.need_gold_merc": "Ti servono {0} oro per assoldare un mercenario. Hai {1}g.",
    "castle.merc_role": "  Ruolo: {0} ({1})  Livello: {2}",
    "castle.merc_hp_str_def": "  HP: {0}  FOR: {1}  DIF: {2}",
    "castle.merc_weap_arm": "  Potenza Arma: {0}  Potenza Armatura: {1}",
    "castle.merc_mana_potions": "  Mana: {0}  Pozioni: {1}",
    "castle.merc_cost": "  Costo: {0} oro. Rimanente: {1}g",
    "castle.merc_mp": " MP: {0}/{1}",
    "castle.hire_merc_btn": "ssolda Mercenario ({0}g)   ",
    "castle.dismiss_btn": "ongeda   ",
    "castle.return_btn": "itorna",
    "castle.quest_comment": "    {0}",
    "castle.quest_objective": "Obiettivo: {0}",
    "castle.quest_target": "Bersaglio: {0} x{1}",
    "castle.crown_standing": "La Corona apprezza la tua lealtà. (+{0} reputazione con la Corona)",
    "castle.already_member": "Sei attualmente membro di '{0}'.",
    "castle.left_team": "Hai lasciato '{0}' per inseguire la corona.",
    "castle.must_defeat": "Devi sconfiggere {0} {1} in combattimento.",
    "castle.warn_monsters": "ATTENZIONE: Devi prima sconfiggere {0} Guardie Mostro!",
    "castle.warn_guards": "ATTENZIONE: Devi anche sconfiggere {0} Guardie Reali!",
    "castle.strike_monster": "Colpisci il {0} per {1} danni! (HP Mostro: {2})",
    "castle.monster_claws": "Il {0} ti artigliia per {1} danni! (I tuoi HP: {2})",
    "castle.slain_by_monster": "Sei stato ucciso dal {0}!",
    "castle.defeated_monster": "Hai sconfitto il {0}!",
    "castle.slip_past": "Come ex guardia, superi indisturbato il tuo stesso posto di guardia...",
    "castle.guard_stats": "Livello {0} | FOR: {1} | DIF: {2} | Lealtà: {3}%",
    "castle.strike_guard": "Colpisci {0} per {1} danni! (HP Guardia: {2})",
    "castle.defeated_by_guard": "Sei stato sconfitto da {0}!",
    "castle.defeated_guard": "Hai sconfitto {0}!",
    "castle.king_stats": "Livello {0} | FOR: {1} | DIF: {2} | HP: {3}",
    "castle.strike_king": "Colpisci per {0} danni! (HP Re: {1})",
    "castle.npc_lv": " Lv{0}",
    "castle.crown_blade": "Lama della Corona     {0}g   PotArma {1}",
    "castle.royal_plate": "Corazza Guardia Reale {0}g   PotArm {1}",
    "castle.crown_shield": "Scudo della Corona    {0}g   PotArm {1}",
    "castle.signet_ring": "Anello del Sigillo    {0}g   +5 CAR, +5 FOR",
    "castle.siege_king": "  Re: {0} {1}",
    "castle.siege_monster_guards": "  Guardie Mostro: {0}",
    "castle.siege_royal_guards": "  Guardie Reali: {0}",
    "castle.siege_total_defenders": "  Difensori Totali: {0}",
    "castle.siege_you": "  TU — {0} (Lv {1} {2})",
    "castle.siege_begins_sr": "L'ASSEDIO HA INIZIO!",
    "castle.siege_begins": "           L'ASSEDIO HA INIZIO!",
    "castle.team_strikes_monster": "  La tua squadra colpisce {0} per {1} danni! (HP: {2})",
    "castle.siege_overwhelmed": "La tua forza d'assedio è stata sopraffatta da {0}!",
    "castle.team_strikes_guard": "  La tua squadra colpisce {0} per {1}! (HP: {2})",
    "castle.siege_defeated_by": "La tua forza d'assedio è stata sconfitta da {0}!",
    "castle.siege_failed_sr": "L'ASSEDIO È FALLITO!",
    "castle.siege_failed": "          L'ASSEDIO È FALLITO!",
    "castle.siege_guards_defeated_sr": "TUTTE LE GUARDIE SCONFITTE - LA SALA DEL TRONO ATTENDE!",
    "castle.siege_king_stats": "Livello {0} | FOR: {1} | DIF: {2} | HP: {3}",
    "castle.siege_strike_king": "Colpisci {0} per {1} danni! (HP Re: {2})",
    "castle.court_developing": "(I membri della corte appariranno man mano che il regno si sviluppa)",
    "castle.courtiers_scheming": "* Alcuni cortigiani sembrano tramare...",
    "castle.court_menu_visual": "[D]esmetti  [A]rresta Cospiratore  [C]orrompi  [P]romuovi  [Q]Esci",
    "castle.faction_status": "  {0}: {1} ({2}%)",
    "castle.faction_loyal": "Leale",
    "castle.faction_neutral": "Neutrale",
    "castle.faction_hostile": "Ostile",
    "castle.court_member_entry": "  {0}. {1} ({2}, {3})",
    "castle.dismissed_from_court": "{0} è stato destituito dalla corte!",
    "castle.plot_entry": "  {0}. {1} da parte di {2} (Costo processo: {3}g)",
    "castle.loyalty_label": "Lealtà: {0}% ",
    "castle.cost_label": "(Costo: {0}g)",
    "castle.bribe_abandoned": "{0} ha abbandonato le sue trame! (+{1} lealtà, -{2}g)",
    "castle.bribe_loyalty_up": "La lealtà di {0} è aumentata a {1}%. (+{2} lealtà, -{3}g)",
    "castle.promote_entry": "  {0}. {1} ({2}, Influenza: {3})",
    "castle.promoted": "{0} è stato promosso! (+{1} lealtà, +5 influenza, -{2}g)",
    "castle.candidate_entry": "{0} +20 relazioni con {1}",
    "castle.accepts_proposal": "{0} accetta la tua proposta!",
    "castle.declines_proposal": "{0} declina cortesemente la tua proposta.",
    "castle.commissioned_guard": "{0} è stato arruolato come Guardia Reale!",
    "castle.commissioned_merc": "{0} è stato arruolato come Mercenario Reale ({1})!",
    "castle.released_citizen": "{0} è stato rilasciato nel mondo come cittadino!",
    "castle.boy": "ragazzo",
    "castle.girl": "ragazza",
    "castle.merc_entry": "  {0}. {1} - Livello {2} {3} ({4}) - HP: {5}/{6}",
    "castle.merc_level_entry": " - Livello {0} {1} ({2})",
    "castle.merc_hp_entry": " - HP: {0}/{1}",
    "castle.hired_bodyguard": "{0} è stato assunto come guardia del corpo reale!",
    "castle.dismiss_merc_entry": "  {0}. {1} (Livello {2} {3})",
    "castle.dismissed_merc": "{0} è stato congedato dal tuo servizio.",
    "castle.reward_label": "    Ricompensa: {0}",
    "castle.comment_label": "    {0}",
    "castle.fight_monster_guard": "=== Combattimento Guardia Mostro: {0} (Livello {1}) ===",
    "castle.fight_royal_guard": "=== Combattimento Guardia Reale: {0} ===",
    "castle.guard_flees": "{0} vede la tua forza e fugge dal combattimento!",
    "castle.guard_strikes": "{0} ti colpisce per {1} danni! (I tuoi HP: {2})",
    "castle.final_battle": "=== Battaglia Finale: {0} {1} ===",
    "castle.round_label": "--- Turno {0} ---",
    "castle.king_strikes": "{0} colpisce per {1} danni! (I tuoi HP: {2})",
    "castle.siege_member_entry": "  {0} (Lv {1})",
    "castle.siege_monster_blocks": ">>> Guardia Mostro: {0} (Livello {1}) blocca il passaggio! <<<",
    "castle.siege_monster_strikes": "  {0} contrattacca per {1}! (HP Squadra: {2})",
    "castle.siege_monster_defeated": "  {0} è stato sconfitto!",
    "castle.siege_guard_stands": ">>> Guardia Reale: {0} (Lealtà: {1}%) resiste! <<<",
    "castle.siege_guard_surrenders": "  {0} getta l'arma e si arrende!",
    "castle.siege_guard_fights": "  {0} contrattacca per {1}! (HP Squadra: {2})",
    "castle.siege_guard_defeated": "  {0} è stato sconfitto!",
    "castle.siege_vs": "=== {0} {1} contro {2} ===",
    "castle.siege_king_strikes": "{0} ti colpisce per {1}! (I tuoi HP: {2})",
    "castle.darkness_label": " (Oscurità: {0})",
    "castle.heir_designated": "{0} è stato ufficialmente designato come tuo erede!",
    "castle.heir_added": "{0} è stato aggiunto alla linea di successione!",
    "castle.gold_label": "\n  Oro: {0}",
    "castle.orders_desc": "Emana decreti e gestisci il regno.",
    "castle.commands": "Comandi:",
    "castle.orders_menu_line1": "(E)sercizi commerciali    (P)roclamazione     (T)aglia su qualcuno",
    "castle.orders_menu_line2": "(R)itorna",
    "castle.open": "CHIUSO",
    "castle.closed": "CHIUSO",
    "castle.opened": "aperto",
    "castle.closed_past": "aperto",
    "castle.establishment_toggled": "{0} è ora {1}!",
    "castle.adopt_orphan": "Adotta nuovo orfano ({0} oro dal tesoro)",
    "castle.commission_orphan": "Arruola orfano (recluta età {0}+, 1.000 oro)",
    "castle.give_gifts_desc": "Fai regali (aumenta la felicità)",
    "castle.eligible_orphans": "Orfani idonei all'arruolamento:",
    "castle.select_orphan": "Seleziona numero orfano: ",
    "castle.orphan_not_eligible": "Quell'orfano non è idoneo all'arruolamento.",
    "castle.commission_guard": "Guardia Reale (slot guardia gratuito, alta lealtà)",
    "castle.commission_mercenary": "Mercenario Reale (guardia del corpo nel sotterraneo, metà costo)",
    "castle.commission_npc": "Rilascia come cittadino PNG",
    "castle.no_guard_slots": "Nessuno slot guardia disponibile!",
    "castle.loyalty_raised_crown": "Lealtà: 90 (cresciuto dalla corona)",
    "castle.no_merc_slots": "Nessuno slot mercenario disponibile!",
    "castle.orphan_released": "Si farà strada nel mondo, grato per le cure della corona.",
    "castle.compassion_standing": "La tua compassione aumenta la tua reputazione con il popolo!",
    "castle.no_orphans_gift": "Non ci sono orfani a cui fare regali.",
    "castle.gift_amount": "Importo del regalo (oro): ",
    "castle.children_delighted": "I bambini sono entusiasti della tua generosità!",
    "castle.options": "Opzioni:",
    "castle.gift_spouse_option": "]egalo al coniuge (migliora la felicità)",
    "castle.divorce_option": "]ivorzio (conseguenze politiche)",
    "castle.return_option": "]itorna",
    "castle.marriage_desc_1": "Un matrimonio reale può assicurare alleanze, riempire il tesoro con la dote,",
    "castle.marriage_desc_2": "e produrre eredi per continuare la tua dinastia.",
    "castle.no_candidates": "Non ci sono candidati idonei al matrimonio al momento.",
    "castle.candidate_requirements": "I candidati devono essere livello 10+, non in una squadra, e non un PNG della storia.",
    "castle.potential_candidates": "Candidati Potenziali al Matrimonio:",
    "castle.propose_candidate": "Proposta a quale candidato? (0 per annullare): ",
    "castle.try_more_renowned": "Forse riprova quando sarai più rinomato...",
    "castle.insufficient_funds": "Fondi insufficienti!",
    "castle.divorce_warning": "ATTENZIONE: Il divorzio avrà gravi conseguenze politiche!",
    "castle.divorce_cancelled": "Divorzio annullato.",
    "castle.court_members": "MEMBRI DELLA CORTE:",
    "castle.court_not_established": "La corte non è stata ancora istituita.",
    "castle.intel_reports": "RAPPORTI DI INTELLIGENCE:",
    "castle.use_detect_threats": "Usa l'incantesimo 'Rileva Minacce' del Mago di Corte per investigare.",
    "castle.no_plots": "Nessun complotto rilevato. La corte sembra stabile.",
    "castle.faction_relations": "RELAZIONI TRA FAZIONI:",
    "castle.court_action": "Azione di corte: ",
    "castle.dismiss_which": "Destituire quale membro della corte?",
    "castle.number_cancel": "Numero (0 per annullare): ",
    "castle.no_discovered_plots": "Nessun complotto scoperto. Usa 'Rileva Minacce' del Mago di Corte per trovare cospiratori.",
    "castle.arrest_which": "Arrestare i cospiratori di quale cospirazione?",
    "castle.insufficient_trial": "Fondi del tesoro insufficienti per il processo!",
    "castle.bribe_which": "Corrompere quale membro della corte per aumentare la lealtà?",
    "castle.heirs_title": "EREDI AL TRONO:",
    "castle.no_heirs": "Non hai eredi.",
    "castle.consider_marriage": "Considera di organizzare un matrimonio reale per avere eredi.",
    "castle.child_may_born": "Un figlio potrebbe nascere dal tuo matrimonio col tempo.",
    "castle.no_heir_designated": "Nessun erede è stato ufficialmente designato.",
    "castle.designate_heir_option": "]esigna un erede",
    "castle.name_heir_option": "]omina un nuovo erede (adotta/legittima)",
    "castle.no_heirs_designate": "Non hai eredi da designare!",
    "castle.designate_which": "Designare quale erede? (numero): ",
    "castle.claim_strengthened": "Il suo diritto al trono è stato rafforzato.",
    "castle.legitimize_desc": "Puoi legittimare un figlio bastardo o adottare un pupillo come erede.",
    "castle.legitimize_cost": "Questo costa 5.000 oro e riduce il diritto di successione degli eredi esistenti.",
    "castle.insufficient_5000": "Fondi insufficienti! (Servono 5.000 oro)",
    "castle.new_heir_name": "Nome del nuovo erede: ",
    "castle.hire_mercs_desc": "Assoldà mercenari d'élite per accompagnarti nel sotterraneo.",
    "castle.no_bodyguards": "Non hai guardie del corpo al tuo servizio.",
    "castle.current_bodyguards": "Guardie del Corpo Attuali:",
    "castle.choose_merc_role": "Scegli un ruolo mercenario:",
    "castle.role_tank": "Difensore",
    "castle.role_tank_desc": "     - Guerriero. Alti HP e difesa, attira gli attacchi nemici.",
    "castle.role_healer": "Guaritore",
    "castle.role_healer_desc": "   - Chierico. Cura i membri del gruppo feriti, lancia incantesimi sacri.",
    "castle.role_dps": "DPS",
    "castle.role_dps_desc": "      - Ranger. Alto danno con attacchi rapidi.",
    "castle.role_support": "Supporto",
    "castle.role_support_desc": "  - Paladino. Combattente bilanciato con guarigione e incantesimi di combattimento.",
    "castle.choose_1_4": "Scegli (1-4, o R per annullare): ",
    "castle.no_bodyguards_dismiss": "Non hai guardie del corpo da congedare.",
    "castle.dismiss_which_bodyguard": "Congedare quale guardia del corpo?",
    "castle.choose_r_cancel": "Scegli (o R per annullare): ",
    "castle.bounty_board_desc": "La bacheca personale delle taglie del Re mostra criminali ricercati e minacce.",
    "castle.no_bounties": "Nessuna taglia è stata emessa dalla Corona.",
    "castle.realm_at_peace": "Il regno è in pace... per ora.",
    "castle.wanted": "RICERCATO:",
    "castle.visit_quest_hall": "Visita la Sala delle Missioni nella Via Principale per riscuotere le taglie.",
    "castle.must_leave_team_challenge": "Per sfidare per il trono, devi abbandonare la tua squadra.",
    "castle.leave_team_crown": "Lasciare la tua squadra per inseguire la corona? (S/N): ",
    "castle.chosen_challenge": "Hai scelto di sfidare per il trono!",
    "castle.proceed_yn": "Vuoi procedere? (S/N): ",
    "castle.reconsider": "Ci ripensi e ti fai indietro.",
    "castle.challenge_failed": "La tua sfida è fallita. Scampi a malapena con la vita.",
    "castle.betrayal_noted": "Il tuo tradimento della corona è stato annotato.",
    "inn.desc_dimly_lit": "La locanda è debolmente illuminata da candele tremolanti. Rozzi tavoli di legno sono occupati",
    "inn.desc_bartender": "da viaggiatori, mercanti e attaccabrighe locali. Il barista ti osserva con sospetto.",
    "inn.desc_seth_hunched": "Seth Able, il famigerato combattente ubriacone, siede accasciato su un boccale",
    "inn.desc_seth_bloodshot": "nell'angolo. I suoi occhi iniettati di sangue scrutano la stanza, in cerca di guai.",
    "inn.teaser_scarred_soldier": "  Nell'angolo più lontano, un soldato coperto di cicatrici siede solo, sorseggiando un drink.",
    "inn.teaser_seen_fights": "  Sembra aver visto la sua parte di battaglie. Non alza lo sguardo.",
    "inn.navigation": "Navigazione:",
    "inn.bbs_desc": " Taverna fumosa. La birra scorre a fiotti. Seth Able ti osserva dall'angolo.",
    "inn.drink_order_ale": "Ordini un boccale di birra dal barista.",
    "inn.drink_bitter_brew": "L'amaro intruglio scende lungo la tua gola...",
    "inn.drink_effect_charisma": "La birra aumenta la tua sicurezza! (+2 Carisma temporaneo)",
    "inn.drink_effect_strength": "Ti senti un po' stordito ma più forte! (+1 Forza temporanea)",
    "inn.drink_effect_wisdom": "L'alcol ti rende spericolato! (-1 Saggezza temporanea)",
    "inn.drink_effect_hp": "Ti senti rilassato e ristabilito. (+5 HP)",
    "inn.seth_passed_out": "Seth Able è svenuto sotto un tavolo. Riprova più tardi.",
    "inn.seth_waves_off": "Seth Able ti liquida con un gesto sprezzante.",
    "inn.seth_enough": "Seth Able ti liquida con un gesto sprezzante.",
    "inn.seth_come_back": "Seth Able ti liquida con un gesto sprezzante.",
    "inn.seth_warning": "ATTENZIONE: Seth Able è un avversario pericoloso!",
    "inn.seth_stats_display": "Seth Able - Livello {0} - HP: {1}",
    "inn.seth_player_stats": "Tu - Livello {0} - HP: {1}/{2}",
    "inn.seth_fights_today": "(Combattimenti oggi: {0}/3)",
    "inn.seth_coward": "Seth Able: \\",
    "inn.seth_inn_falls_silent": "La locanda ammutolisce mentre ti avvicini a Seth Able...",
    "inn.awaken_temple": "Ti risvegli al Tempio della Luce...",
    "inn.seth_incredible": "INCREDIBILE! Hai sconfitto Seth Able!",
    "inn.seth_shocked_silence": "L'intera locanda esplode in un silenzio scioccato...",
    "inn.seth_bartender_drops": "Persino il barista lascia cadere il bicchiere dallo stupore!",
    "inn.seth_legend": "Sei ormai una leggenda in questa taverna!",
    "inn.seth_beaten_again": "Hai battuto Seth Able di nuovo!",
    "inn.seth_patrons_cheer": "Gli avventori esultano, ma l'hanno già visto...",
    "inn.seth_earn_reward": "Guadagni {0} esperienza e {1} oro.",
    "inn.seth_knocks_out": "Il potente colpo di Seth Able ti manda al tappeto!",
    "inn.seth_massive_headache": "Ti svegli più tardi con un tremendo mal di testa...",
    "inn.seth_back_away": "Riesci a indietreggiare da Seth Able!",
    "inn.seth_walk_away": "'Giusto così, vattene!' grida Seth alle tue spalle.",
    "inn.seth_chuckle_retreat": "Gli altri avventori ridacchiano della tua ritirata.",
    "inn.seth_fist_connects": "Il massiccio pugno di Seth Able si abbatte sulla tua mascella!",
    "inn.seth_crash_table": "Ti schianti contro un tavolo e scivoli a terra...",
    "inn.seth_patrons_laugh": "Gli avventori ridono mentre Seth torna al suo drink.",
    "inn.seth_next_time": "'Magari la prossima volta, ragazzo!' borbotta Seth.",
    "inn.patrons_quiet": "La locanda è tranquilla stasera. Nessun avventore interessante con cui parlare.",
    "inn.patrons_following": "Vedi i seguenti avventori qui:",
    "inn.return_to_menu": "[0] Torna al menu della locanda",
    "inn.choose_patron": "Scegli qualcuno da avvicinare (0-8): ",
    "inn.interacting_with": "Interazione con {0}",
    "inn.alignment_kindred": "  Allineamento: Spiriti affini (ottimo rapporto)",
    "inn.alignment_compatible": "  Allineamento: Compatibile (buon rapporto)",
    "inn.alignment_neutral": "  Allineamento: Neutrale (rapporto standard)",
    "inn.alignment_opposing": "  Allineamento: Opposto (rapporto scarso)",
    "inn.what_to_do": "Cosa vorresti fare?",
    "inn.option_talk_deep": " Parla - Conversazione profonda (flirtare, confessare, romanticismo)",
    "inn.option_challenge_duel": " Sfida - Sfida a duello",
    "inn.option_gift_cost": " Regalo - Fai un regalo (costa 50 oro)",
    "inn.challenging_npc": "Sfidi {0} a duello!",
    "inn.npc_declines_duel": "{0} ride e ti liquida con un gesto. \\",
    "inn.npc_accepts_challenge": "{0} accetta la tua sfida!",
    "inn.npc_regret_decision": "{0} accetta la tua sfida!",
    "inn.fight_now_prompt": "Combattere ora? (s/N): ",
    "inn.npc_changed_mind": "{0}: \\",
    "inn.defeated_npc": "Hai sconfitto {0}!",
    "inn.victory_spreads": "La notizia della tua vittoria si diffonde per la locanda!",
    "inn.gossip_lean_back": "Ti appoggi allo schienale e ascolti i pettegolezzi degli avventori...",
    "inn.rest_quiet_corner": "Trovi un angolo tranquillo e riposi per un po'...",
    "inn.rest_shadow_fades": "La Benedizione delle Ombre svanisce mentre riposi...",
    "inn.rest_recover_hp": "Ti senti riposato e recuperi {0} HP.",
    "inn.rest_recover_mana": "La tua mente si schiarisce, recuperando {0} mana.",
    "inn.rest_dark_memories": "  Il tuo riposo è turbato da ricordi oscuri...",
    "inn.rest_full_health": "Sei già in piena salute.",
    "inn.rest_fatigue_reduced": "Un breve riposo allevia la tua stanchezza. (Fatica -{0})",
    "inn.rest_dream_begins": "Mentre ti assopisci, un sogno prende forma...",
    "inn.bandit.sitting_at_bar": "Sei seduto al bancone, sorseggiando un drink dopo una lunga giornata.",
    "inn.bandit.bandits_enter": "La porta si spalanca e un gruppo di banditi armati entra con aria spavalderia.",
    "inn.bandit.leader_threat1": "\"Tutti fermi dove siete! Consegnate il vostro oro,\"",
    "inn.bandit.leader_threat2": "\"o dipingeremo queste pareti col vostro sangue!\"",
    "inn.bandit.draw_weapons": "I banditi sguainano le armi, l'acciaio brilla alla luce del fuoco.",
    "inn.bandit.patrons_scatter": "Gli avventori si buttano al riparo, rovesciando sedie e boccali.",
    "inn.bandit.chair_scrapes": "*Una sedia stride contro il pavimento...*",
    "inn.bandit.stranger_rises": "Uno straniero si alza lentamente da un tavolo d'angolo.",
    "inn.bandit.tattered_armor": "Indossa un'armatura logora ma ben mantenuta,",
    "inn.bandit.battered_shield": "e porta uno scudo ammaccato che ha chiaramente visto molte battaglie.",
    "inn.bandit.aldric_sporting": "\"Non mi sembra molto sportivo, vero?\"",
    "inn.bandit.leader_stay_out": "\"Stattene fuori, vecchio, a meno che tu non voglia morire!\"",
    "inn.bandit.aldric_i_am_trouble": "\"IO SONO il guaio che non volete trovare.\"",
    "inn.bandit.stranger_efficiency": "Lo straniero si muove con brutale efficienza.",
    "inn.bandit.shield_deflects": "Il suo scudo devia la prima lama mentre la sua spada disarma un altro.",
    "inn.bandit.strike_sprawling": "Un singolo colpo potente manda il terzo bandito a terra.",
    "inn.bandit.leader_flees": "Il capo dei banditi dà un'occhiata e fugge nella notte.",
    "inn.bandit.wipes_blood": "Lo straniero si pulisce il sangue dallo scudo e si volta verso di te.",
    "inn.bandit.aldric_reputation": "\"Questa locanda aveva una reputazione migliore, un tempo.\"",
    "inn.bandit.extends_hand": "Tende una mano callosa.",
    "inn.bandit.aldric_name": "\"Mi chiamo Aldric. Ex cavaliere, attualmente... vagabondo.\"",
    "inn.bandit.aldric_purpose": "\"Cercavo qualcuno con cui valesse la pena combattere al fianco.\"",
    "inn.bandit.glances_appraisingly": "Ti osserva con aria di valutazione.",
    "inn.bandit.aldric_shield_back": "\"Sembri uno a cui servirebbe qualcuno che gli guardi le spalle.\"",
    "inn.bandit.aldric_protecting": "\"E io potrei usare qualcuno che valga la pena proteggere.\"",
    "inn.bandit.accept_aldric": "Accetta l'offerta di Aldric",
    "inn.bandit.decline_aldric": "Declina cortesemente",
    "inn.bandit.aldric_nods_solemnly": "Aldric annuisce solennemente.",
    "inn.bandit.aldric_find_trouble": "\"Bene. Ho il presentimento che troveremo un sacco di guai insieme.\"",
    "inn.bandit.aldric_got_your_back": "\"Ma almeno ora, hai qualcuno che ti guarda le spalle.\"",
    "inn.bandit.aldric_joined": "*** Aldric si è unito al tuo gruppo! ***",
    "inn.bandit.aldric_tank_hint": "(Aldric è un compagno Difensore - attirerà gli attacchi nemici e ti proteggerà)",
    "inn.bandit.aldric_disappointed": "Aldric sembra leggermente deluso, ma annuisce.",
    "inn.bandit.aldric_understand": "\"Capisco. Non tutti vogliono uno straniero al proprio fianco.\"",
    "inn.bandit.aldric_change_mind": "\"Ma se cambi idea, mi troverai qui.\"",
    "inn.bandit.aldric_recruit_later": "(Potrai reclutare Aldric più tardi visitando la Locanda)",
    "inn.bandit.aldric_you_alright": "\"Tutto bene, {0}?\"",
}
