translations = {
    "dungeon.entering": "Entrando nel piano {0} del sotterraneo...",
    "dungeon.floor": "Piano {0}",
    "dungeon.explore": "Esplora",
    "dungeon.descend": "Discendi",
    "dungeon.ascend": "Risali",
    "dungeon.change_floor": "Cambia Piano",
    "dungeon.camp": "Accampamento",
    "dungeon.leave": "Esci dal Sotterraneo",
    "dungeon.empty_room": "La stanza è vuota.",
    "dungeon.monster_room": "Avverti il pericolo davanti a te...",
    "dungeon.treasure_room": "Hai trovato uno scrigno del tesoro!",
    "dungeon.trap": "Hai attivato una trappola!",
    "dungeon.safe_haven": "Hai trovato un rifugio sicuro dove riposare!",
    "dungeon.actions": "Azioni:",
    "dungeon.fight": "Combatti i mostri",
    "dungeon.collect_treasure": "Raccogli il tesoro",
    "dungeon.investigate": "Indaga sull'evento",
    "dungeon.examine": "Esamina i dettagli",
    "dungeon.descend_stairs": "Scendi le scale",
    "dungeon.make_camp": "Allestisci l'accampamento e recupera",
    "dungeon.map": "Mappa",
    "dungeon.guide": "Guida",
    "dungeon.inventory": "Inventario",
    "dungeon.potions": "Pozioni",
    "dungeon.herbs": "Erbe ({0})",
    "dungeon.status": "Stato",
    "dungeon.leave_dungeon": "Esci dal sotterraneo",
    "dungeon.leave_prayers": "Lasciala alle sue preghiere",
    "dungeon.ask_join": "Chiedile di unirti a te",
    "dungeon.talk_more": "Parla ancora",
    "dungeon.remove_member": "Rimuovi qualcuno per fare posto",
    "dungeon.cancel_recruit": "Annulla il reclutamento",
    "dungeon.no_potions": "Non hai pozioni curative!",
    "dungeon.heal_full": "Curati completamente (usa più pozioni)",
    "dungeon.heal_teammate": "Cura un Compagno",
    "dungeon.heal_all": "Cura TUTTI i Membri del Gruppo al massimo",
    "dungeon.return_dungeon": "Torna al Sotterraneo",
    "dungeon.trade_supplies": "Commercia - Compra provviste",
    "dungeon.return": "Torna al sotterraneo",
    "dungeon.level_raise": "* Puoi salire di livello! Visita il tuo Maestro per avanzare! *",
    "dungeon.story_journal": "D I A R I O   D I   S T O R I A",
    "dungeon.boss_encounter": "*** SCONTRO CON IL BOSS ***",
    "dungeon.floor_conquered": "PIANO CONQUISTATO!",
    "dungeon.forgotten_shrine": "IL SANTUARIO DIMENTICATO",
    "dungeon.merchant": "MERCANTE ITINERANTE",
    "dungeon.merchant_wares": "MERCI DEL MERCANTE",
    "dungeon.party_management": "GESTIONE DEL GRUPPO",
    "dungeon.potions_menu": "MENU POZIONI",
    "dungeon.divine_wrath": "*** IRA DIVINA ***",
    "dungeon.section_companions": "I TUOI COMPAGNI",
    "dungeon.party_restored": "GRUPPO RIPRISTINATO",
    "dungeon.section_quest": "LA TUA MISSIONE",
    "dungeon.section_learned": "CIÒ CHE HAI APPRESO",
    "dungeon.section_next_steps": "PROSSIMI PASSI CONSIGLIATI",
    "dungeon.section_old_gods": "GLI ANTICHI DÈI",
    "dungeon.section_stories": "STORIE DELLA CITTÀ",
    "dungeon.section_companions_journal": "COMPAGNI",
    "dungeon.section_combat": "COMBATTIMENTO!",
    "dungeon.section_floor_cleared": "PIANO LIBERATO",
    "dungeon.section_exploring": "ESPLORAZIONE",
    "dungeon.section_supplies": "PROVVISTE",
    "dungeon.section_rare_items": "OGGETTI RARI (Esclusivi del Sotterraneo!)",
    "dungeon.section_xp_dist": "Distribuzione PE",
    "dungeon.section_your_status": "IL TUO STATO",
    "dungeon.section_team_status": "STATO DELLA SQUADRA",
    "dungeon.exits": "Uscite:",
    "dungeon.fully_cleared": "completamente liberato",
    "dungeon.cleared": "liberato",
    "dungeon.explored": "esplorato",
    "dungeon.unknown": "sconosciuto",
    "dungeon.dungeon_level": "SOTTERRANEO  LIVELLO   {0}",
    "dungeon.theme": "Tema",
    "dungeon.rooms": "Stanze",
    "dungeon.danger_level": "Livello di Pericolo",
    "dungeon.explored_count": "Esplorate",
    "dungeon.cleared_count": "Liberate",
    "dungeon.your_party": "Il tuo Gruppo: {0} membro/i",
    "dungeon.seal_hint": ">> Un Sigillo degli Antichi Dèi è nascosto in questo piano! <<",
    "dungeon.enter_dungeon": "Entra nel sotterraneo",
    "dungeon.journal": "Diario, progressi delle missioni",
    "dungeon.party_mgmt": "Gestione del gruppo",
    "dungeon.level_change": "Cambia livello, più o meno 10",
    "dungeon.return_town": "Torna in città",
    "dungeon.party_member_entry": "  {0}. {1} (Livello {2} {3}) - PV: {4}/{5}",
    "dungeon.remove_who": "Chi vuoi rimuovere? (#): ",
    "dungeon.removed_from_party": "{0} è stato rimosso dal gruppo.",
    "dungeon.party_full": "Il tuo gruppo è al completo!",
    "dungeon.merchant_greeting": "Un mercante girovago appare!",
    "dungeon.merchant_potions": "  Pozioni Curative: {0}m ciascuna (Ne hai {1})",
    "dungeon.merchant_buy_prompt": "Quante ne vuoi comprare? (0 per saltare): ",
    "dungeon.merchant_bought": "Comprate {0} pozioni curative per {1}m!",
    "dungeon.merchant_cant_afford": "Non puoi permetterti tutto questo!",
    "dungeon.witch_doctor": "Uno stregone offre di curare i tuoi malanni!",
    "dungeon.witch_cure_cost": "  Cura malattia: {0}m",
    "dungeon.witch_cure_prompt": "Accetti la cura? (S/N): ",
    "dungeon.witch_cured": "Lo stregone cura la tua malattia!",
    "dungeon.witch_no_gold": "Non hai abbastanza monete d'oro!",
    "dungeon.witch_healthy": "Sei già in salute!",
    "dungeon.potion_healed": "Curato {0} PV! (PV: {1}/{2})",
    "dungeon.mana_potion_restored": "Ripristinati {0} PM! (PM: {1}/{2})",
    "dungeon.no_mana_potions": "Non hai pozioni di mana!",
    "dungeon.level_too_low": "Devi essere almeno livello {0} per accedere al piano {1}!",
    "dungeon.level_too_high": "Il piano {0} è troppo lontano sotto il tuo livello ({1}). Massimo accessibile: piano {2}.",
    "dungeon.safe_rest_healed": "Ti sei riposato e hai recuperato {0} PV.",
    "dungeon.camping_header": "=== Accampamento ===",
    "dungeon.camping_rest": "Allestisci l'accampamento e ti riposi...",
    "dungeon.camping_healed": "Recuperati {0} PV dall'accampamento.",
    "dungeon.camping_fatigue": "Fatica ridotta di {0}.",
    "dungeon.floor_cleared": "Questo piano è stato liberato!",
    "dungeon.descend_prompt": "Discendere al piano {0}? (S/N): ",
    "dungeon.ascend_prompt": "Risalire al piano {0}? (S/N): ",
    "dungeon.trap_detected": "Hai individuato una trappola! Tentare di disattivarla? (S/N): ",
    "dungeon.trap_disarmed": "Trappola disattivata con successo!",
    "dungeon.trap_triggered": "Una trappola è stata attivata!",
    "dungeon.trap_sprung": "Sei caduto in una trappola! {0} danni!",
    "dungeon.potion_cache_header": "SCORTA DI POZIONI",
    "dungeon.potion_cache_header_sr": "-- SCORTA DI POZIONI --",
    "dungeon.potion_cache_msg_1": "Scopri la borsa abbandonata di un guaritore!",
    "dungeon.potion_cache_msg_2": "Lo zaino di un avventuriero caduto contiene provviste curative!",
    "dungeon.potion_cache_msg_3": "Trovi la scorta abbandonata di pozioni di un monaco!",
    "dungeon.potion_cache_msg_4": "Un'alcova nascosta rivela un deposito di elisir curativi!",
    "dungeon.potion_cache_msg_5": "Il cadavere di un chierico stringe una sacca di pozioni!",
    "dungeon.potion_cache_max": "Hai già il numero massimo di pozioni!",
    "dungeon.potion_cache_leave": "Lasci le pozioni per un altro avventuriero.",
    "dungeon.potion_cache_collect": "Raccogli {0} pozione/i curativa/e!",
    "dungeon.potion_cache_count": "Pozioni: {0}/{1}",
    "dungeon.potion_cache_left_behind": "(Hai dovuto lasciare indietro {0} pozione/i — capacità massima raggiunta)",
    "dungeon.merchant_appears": "Un mercante itinerante emerge dalle ombre!",
    "dungeon.merchant_greeting_text": "\"Salve, valoroso avventuriero! Vi va di commerciare?\"",
    "dungeon.merchant_trade_or_attack": "(C)ommercio col mercante o (A)ttacco per le merci? ",
    "dungeon.merchant_rob": "Decidi di derubare il povero mercante!",
    "dungeon.merchant_loot_split": "Saccheggi {0} monete d'oro e 3 pozioni curative dal mercante! (divise in {1} parti)",
    "dungeon.merchant_loot": "Saccheggi {0} monete d'oro e 3 pozioni curative dal mercante!",
    "dungeon.merchant_darkness": "+10 Oscurità per aver attaccato un mercante innocente!",
    "dungeon.merchant_goodbye": "Il mercante saluta e svanisce nelle ombre.",
    "dungeon.merchant_healing_potion": "Pozione Curativa ({0}m)",
    "dungeon.merchant_mega_potion": "Mega Pozione ({0}m) - Guarigione completa!",
    "dungeon.merchant_antidote": "Antidoto ({0}m) - Cura il veleno ({1}/{2})",
    "dungeon.merchant_buy_max": "Compra Pozioni al Massimo ({0}m)",
    "dungeon.merchant_buy_max_full": "Compra Pozioni al Massimo (pieno!)",
    "dungeon.merchant_leave_shop": "Lascia il negozio",
    "dungeon.merchant_cant_carry_potions": "\"Non puoi portare altre pozioni, amico!\"",
    "dungeon.merchant_purchased_potion": "Acquistata 1 pozione curativa! ({0}/{1})",
    "dungeon.merchant_mega_full_heal": "Bevi la mega pozione — SALUTE COMPLETAMENTE RIPRISTINATA!",
    "dungeon.merchant_cant_carry_antidotes": "\"Non puoi portare altri antidoti, amico!\"",
    "dungeon.merchant_antidote_cure": "Bevi l'antidoto — il veleno defluisce dal tuo corpo!",
    "dungeon.merchant_purchased_antidote": "Acquistato 1 antidoto! ({0}/{1})",
    "dungeon.merchant_full_potions": "\"Hai già il massimo di pozioni!\"",
    "dungeon.merchant_purchased_potions": "Acquistate {0} pozioni per {1}m!",
    "dungeon.merchant_potions_count": "Pozioni: {0}/{1}",
    "dungeon.merchant_afford_partial": "Puoi permetterti solo {0} pozioni.",
    "dungeon.merchant_safe_travels": "\"Buon viaggio, avventuriero!\"",
    "dungeon.merchant_invalid": "Scelta non valida.",
    "dungeon.merchant_item_sold": "\"Quell'oggetto è già stato venduto, amico.\"",
    "dungeon.merchant_need_gold": "\"Vi servono {0} monete d'oro per {1}.\"",
    "dungeon.merchant_come_back": "\"Tornate quando avrete più monete!\"",
    "dungeon.merchant_purchase_confirm": "Acquistare {0} per {1} monete d'oro? (S/N)",
    "dungeon.merchant_added_inventory": "Aggiunto al tuo inventario.",
    "dungeon.merchant_fine_choice": "\"Un'ottima scelta! Usatelo bene.\"",
    "dungeon.merchant_another_time": "\"Forse un'altra volta.\"",
    "dungeon.merchant_current_weapon": "Potenza della tua arma attuale: {0}",
    "dungeon.merchant_current_armor": "Potenza della tua armatura attuale: {0}",
    "dungeon.witch_doctor_header": "=== INCONTRO CON LO STREGONE ===",
    "dungeon.witch_doctor_meet": "Incontri il malvagio Stregone Mbluta!",
    "dungeon.witch_doctor_demand": "Esige {0} monete d'oro o ti maledirà!",
    "dungeon.witch_doctor_prompt": "(P)aga lo stregone o (F)uggi? ",
    "dungeon.witch_doctor_pay": "Paghi lo stregone a malincuore.",
    "dungeon.witch_doctor_vanish": "Svanisce nell'oscurità...",
    "dungeon.witch_doctor_flee": "Riesci a fuggire dal malvagio stregone!",
    "dungeon.witch_doctor_cursed": "Non riesci a scappare e vieni maledetto!",
    "dungeon.witch_doctor_lose_exp": "Perdi {0} punti esperienza!",
    "dungeon.witch_doctor_lose_fights": "Perdi {0} combattimenti nel sotterraneo!",
    "dungeon.witch_doctor_lose_pfights": "Perdi {0} combattimenti tra giocatori!",
    "dungeon.witch_doctor_no_gold": "Appare uno stregone ma, vedendo che non hai oro, se ne va.",
    "dungeon.must_defeat_old_god": "Devi sconfiggere l'Antico Dio su questo piano prima di scendere più in profondità.",
    "dungeon.cant_venture_deeper": "Non puoi avventurarti oltre il livello {0} con la tua forza attuale.",
    "dungeon.level_up_access": "Sali di livello per accedere ai piani più profondi.",
    "dungeon.descend_to": "Discendi al livello {0} del sotterraneo.",
    "dungeon.deepest_level": "Hai raggiunto il livello più profondo del sotterraneo.",
    "dungeon.ascend_to": "Risali al livello {0} del sotterraneo.",
    "dungeon.no_one_to_bring": "Non hai nessuno da portare con te.",
    "dungeon.get_team": "Sposati, recluta compagni o unisciti a una squadra!",
    "dungeon.team_label": "Squadra: {0}",
    "dungeon.team_turf": "La squadra controlla il territorio: {0}",
    "dungeon.no_team_loved_ones": "Non fai parte di una squadra, ma i tuoi cari possono unirsi a te.",
    "dungeon.current_dungeon_party": "Gruppo Attuale nel Sotterraneo:",
    "dungeon.available_companions": "Compagni Disponibili (in riserva):",
    "dungeon.available_allies": "Alleati Disponibili (non nel gruppo del sotterraneo):",
    "dungeon.no_allies_available": "Nessun alleato disponibile per il tuo gruppo nel sotterraneo.",
    "dungeon.options": "Opzioni:",
    "dungeon.add_companion_party": "] Aggiungi compagno al gruppo",
    "dungeon.add_ally": "]ggiungi alleato al gruppo",
    "dungeon.remove_ally": "]imuovi alleato dal gruppo",
    "dungeon.xp_distribution_pct": "] Distribuzione PE ({0}% assegnata)",
    "dungeon.back_dungeon_menu": "]ndietro al menu sotterraneo",
    "dungeon.party_full_max4": "Il tuo gruppo è al completo (massimo 4 compagni)!",
    "dungeon.invalid_companion": "Selezione compagno non valida.",
    "dungeon.no_team_members": "Nessun membro della squadra disponibile.",
    "dungeon.no_teammates_remove": "Nessun compagno da rimuovere.",
    "dungeon.companion_role": "Ruolo: {0}",
    "dungeon.could_not_add": "Impossibile aggiungere {0} al gruppo.",
    "dungeon.enter_team_number": "Inserisci il numero del membro da aggiungere (1-{0}): ",
    "dungeon.npc_higher_level": "{0} è {1} livelli più forte di te.",
    "dungeon.npc_demand_fee": "Esigono {0} monete d'oro per accompagnarti nel sotterraneo.",
    "dungeon.your_gold": "Il tuo oro: {0}",
    "dungeon.cannot_afford_fee": "Non puoi permetterti questa cifra!",
    "dungeon.pay_fee_confirm": "Pagare {0} monete d'oro? (S/N): ",
    "dungeon.npc_shrugs": "{0} fa spallucce e resta indietro.",
    "dungeon.paid_fee": "Pagate {0} monete d'oro.",
    "dungeon.npc_joins": "{0} si unisce al tuo gruppo nel sotterraneo!",
    "dungeon.fight_alongside": "Combatteranno al tuo fianco contro i mostri.",
    "dungeon.xp_penalty_warning": "Attenzione: Penalità PE attiva ({0}% a causa di un alleato di livello elevato)",
    "dungeon.team_bonus": "Bonus squadra: +15% PE e oro dalle battaglie!",
    "dungeon.enter_party_remove": "Inserisci il numero del membro da rimuovere (2-{0}): ",
    "dungeon.grouped_player_leave": "{0} è un giocatore raggruppato — deve digitare /leave per uscire dal gruppo.",
    "dungeon.companion_steps_back": "{0} si ritira dalla prima linea.",
    "dungeon.companion_available": "(Resta disponibile — usa la Gestione del Gruppo per richiamarlo)",
    "dungeon.npc_returns_town": "{0} lascia il gruppo e torna in città.",
    "dungeon.member_leaves_party": "{0} lascia il gruppo.",
    "dungeon.companion_rejoins": "{0} si riunisce al tuo gruppo!",
    "dungeon.grouped_independent": "({0} giocatore/i raggruppato/i guadagnano PE indipendentemente)",
    "dungeon.current_party_xp": "Gruppo attuale:",
    "dungeon.xp_unallocated": "Attenzione: {0}% dei PE non è assegnata!",
    "dungeon.xp_adjust_prompt": "Inserisci il numero dello slot da modificare, [E]qua distribuzione, o [I]ndietro:",
    "dungeon.xp_even_split": "PE divisi equamente: {0}% per te, {1}% per ogni compagno.",
    "dungeon.xp_slot_empty": "Quello slot è vuoto.",
    "dungeon.xp_set_prompt": "Imposta % PE per {0} (0-{1}, attualmente {2}%): ",
    "dungeon.xp_min_self": "Devi tenere almeno il 10% dei PE per te stesso.",
    "dungeon.xp_total_exceeded": "Il totale sarebbe {0}%. Il massimo è 100%.",
    "dungeon.xp_set_to": "{0} impostato a {1}% PE.",
    "dungeon.invalid_percentage": "Percentuale non valida.",
    "dungeon.party_full_allies": "Il tuo gruppo è al completo (massimo 4 alleati)!",
    "dungeon.make_room": "{0} vorrebbe unirsi a te, ma devi fare posto.",
    "dungeon.current_party_members": "Membri attuali del gruppo:",
    "dungeon.remove_make_room": "[R] Rimuovi qualcuno per fare posto",
    "dungeon.cancel_recruitment": "[C] Annulla il reclutamento",
    "dungeon.who_should_leave": "Chi deve lasciare il gruppo?",
    "dungeon.companions_readd": "(I compagni possono essere riaggiunti dalla Gestione del Gruppo)",
    "dungeon.enter_remove_number": "Inserisci il numero (1-{0}): ",
    "dungeon.invalid_cancelled": "Selezione non valida. Reclutamento annullato.",
    "dungeon.recruitment_cancelled": "Reclutamento annullato.",
    "dungeon.use_potion_self": "Usa Pozione Curativa su te stesso (cura ~{0} PV)",
    "dungeon.buy_potions_monk": "Compra Pozioni dal Monaco (Curative {0}m, Mana {1}m)",
    "dungeon.use_antidote": "Usa Antidoto (cura il veleno, {0} rimanenti)",
    "dungeon.use_antidote_not_poisoned": "Usa Antidoto ({0} rimanenti) - non avvelenato",
    "dungeon.no_potions_potion_menu": "Usa Pozione Curativa - NESSUNA POZIONE!",
    "dungeon.antidote_cure_poison": "Bevi l'antidoto — il veleno defluisce dal tuo corpo!",
    "dungeon.not_poisoned": "Non sei avvelenato!",
    "dungeon.no_antidotes": "Non hai antidoti!",
    "dungeon.select_teammate_heal": "Seleziona il compagno da curare:",
    "dungeon.cancel": "Annulla",
    "dungeon.choose": "Scegli: ",
    "dungeon.already_full_health_name": "{0} è già al massimo della salute!",
    "dungeon.missing_hp": "{0} ha perso {1} PV.",
    "dungeon.each_potion_heals": "Ogni pozione cura circa {0} PV.",
    "dungeon.use_1_potion": "Usa 1 pozione",
    "dungeon.fully_heal_potions": "Guarigione completa (usa fino a {0} pozioni)",
    "dungeon.give_potion_one": "Dai una pozione curativa a {0}!",
    "dungeon.give_potions_many": "Dai {0} pozioni curative a {1}!",
    "dungeon.recovers_hp": "{0} recupera {1} PV!",
    "dungeon.fully_healed_name": "{0} è completamente guarito!",
    "dungeon.everyone_full_health": "Sono tutti già al massimo della salute!",
    "dungeon.heal_party_requires": "Curare l'intero gruppo richiede circa {0} pozioni.",
    "dungeon.you_have_potions": "Hai {0} pozioni.",
    "dungeon.not_enough_potions_warning": "Attenzione: Non abbastanza pozioni per la guarigione completa. Verranno usate tutte le {0}.",
    "dungeon.yes_heal_party": "Sì, cura il gruppo (usa {0} pozioni)",
    "dungeon.distributing_potions": "Distribuzione delle pozioni al gruppo...",
    "dungeon.you_recover_hp": "Recuperi {0} PV!",
    "dungeon.teammate_recovers": "{0} recupera {1} PV!",
    "dungeon.used_potions_total": "Usate {0} pozioni. PV totali ripristinati: {1}",
    "dungeon.potions_remaining": "Pozioni rimanenti: {0}/{1}",
    "dungeon.no_healing_potions": "Non hai pozioni curative!",
    "dungeon.already_full_health": "Sei già al massimo della salute!",
    "dungeon.drink_potion_recover": "Bevi una pozione curativa e recuperi {0} PV!",
    "dungeon.will_use_potions": "Verranno usate {0} pozione/i. Continuare? (S/N)",
    "dungeon.drink_potions_recover": "Bevi {0} pozione/i curativa/e e recuperi {1} PV!",
    "dungeon.monk_appears": "Un monaco errante si materializza dalle ombre...",
    "dungeon.monk_greeting": "\"Salve, viaggiatore. Ho provviste per il corpo e per la mente.\"",
    "dungeon.monk_your_gold": "Il tuo oro: {0}",
    "dungeon.monk_another_time": "\"Forse un'altra volta, allora.\"",
    "dungeon.monk_fades": "Il monaco si inchina e svanisce nelle ombre...",
    "dungeon.monk_max_potions": "\"Porti già il massimo di {0} pozioni che puoi trasportare!\"",
    "dungeon.monk_no_gold": "\"Temo che ti manchino le monete, amico mio.\"",
    "dungeon.monk_how_many": "Quante pozioni di {0}? (Max: {1}, 0 per annullare)",
    "dungeon.monk_cancel": "\"Forse un'altra volta, allora.\"",
    "dungeon.monk_only_provide": "\"Posso fornirti soltanto {0}.\"",
    "dungeon.monk_purchased": "Acquisti {0} pozione/i di {1} per {2} monete d'oro.",
    "dungeon.monk_gold_remaining": "Oro rimanente: {0}",
    "dungeon.no_floor_map": "Nessun piano da mappare.",
    "dungeon.map_unavailable": "Mappa non disponibile.",
    "dungeon.no_floor_data": "Nessun dato sul piano.",
    "dungeon.guide_title": "Guida al Sotterraneo - Livello {0}, {1}",
    "dungeon.you_are_in": "Ti trovi in: {0}",
    "dungeon.guide_exits": "Uscite: {0}",
    "dungeon.boss_defeated": "Boss sconfitto.",
    "dungeon.no_known_destinations": "Nessuna destinazione nota. Esplora per scoprire le stanze.",
    "dungeon.directions_to": "Indicazioni per:",
    "dungeon.map_legend_you": "Tu",
    "dungeon.map_legend_cleared": "Liberata",
    "dungeon.map_legend_monsters": "Mostri",
    "dungeon.map_legend_stairs": "Scale",
    "dungeon.map_legend_boss": "Boss",
    "dungeon.map_legend_safe": "Sicuro",
    "dungeon.map_legend_unknown": "Sconosciuto",
    "dungeon.help_title": "Aiuto Sotterraneo",
    "dungeon.help_explore": "E - Esplora il livello attuale",
    "dungeon.help_descend": "D - Discendi a un livello più profondo e pericoloso",
    "dungeon.help_ascend": "A - Risali a un livello più sicuro o torna in città",
    "dungeon.help_team": "T - Gestisci i membri della tua squadra",
    "dungeon.help_status": "S - Visualizza il tuo stato",
    "dungeon.help_potions": "P - Compra pozioni dal monaco errante",
    "dungeon.help_map": "M - Visualizza la mappa del sotterraneo",
    "dungeon.help_guide": "G - Guida (indicazioni per scale, inesplorato, non liberato, boss)",
    "dungeon.help_quit": "Q - Esci e torna in città",
    "dungeon.steel_nerves": "Rafforzi il tuo coraggio. Il sotterraneo ora sembra di livello {0}!",
    "dungeon.beggar_appears": "Una figura lacera si rannicchia contro il muro del sotterraneo, con le mani tese.",
    "dungeon.beggar_plea": "\"Per favore... un po' d'oro per un'anima perduta? Sono intrappolato qui sotto da giorni.\"",
    "dungeon.beggar_give": "Porgi {0} monete d'oro. Gli occhi del mendicante si riempiono di lacrime.",
    "dungeon.beggar_bless": "\"Che gli dèi vi benedicano... vi benedicano, anima gentile.\"",
    "dungeon.beggar_bonus": "Il mendicante ti preme qualcosa in mano prima di allontanarsi trascinando i piedi.",
    "dungeon.beggar_bonus_gold": "È una borsa nascosta con {0} monete d'oro!",
    "dungeon.beggar_test": "\"Stavo mettendo alla prova il tuo cuore. Hai superato la prova.\"",
    "dungeon.beggar_rob": "Spingi il mendicante e frughi tra i suoi stracci.",
    "dungeon.beggar_rob_gold": "Trovi {0} monete d'oro nascoste nel suo mantello.",
    "dungeon.beggar_fights_back": "Il mendicante ringhia e ti colpisce con una lama nascosta!",
    "dungeon.beggar_damage": "Subisci {0} danni!",
    "dungeon.beggar_ignore": "Passi oltre il mendicante senza una parola.",
    "dungeon.beggar_eyes": "I suoi occhi vuoti ti seguono nell'oscurità.",
    "dungeon.enter_dungeon_label": "ntra nel sotterraneo    ",
    "dungeon.journal_label": "iario - Progressi missioni",
    "dungeon.party_mgmt_label": "estione del gruppo      ",
    "dungeon.status_label": "tato",
    "dungeon.level_change_label": "ivello cambia (+/- 10)  ",
    "dungeon.return_town_label": "itorna in città",
    "dungeon.wounded_adventurer": "Un avventuriero ferito giace contro il muro!",
    "dungeon.wounded_adventurer_map": "\"Per favore... prendi la mia mappa... vendicami...\"",
    "dungeon.gain_knowledge": "Acquisisci conoscenza della struttura del sotterraneo!",
    "dungeon.rival_blocks": "Un avventuriero rivale ti blocca il cammino!",
    "dungeon.rival_mine": "\"Questo tesoro è MIO! Vattene!\"",
    "dungeon.rival_bribe": "Paghi {0} monete d'oro per passare.",
    "dungeon.rival_no_gold": "\"Niente oro? Allora combatti!\"",
    "dungeon.lost_explorer": "Un esploratore smarrito barcolla verso di te!",
    "dungeon.lost_explorer_thanks": "\"Oh, grazie agli dèi! Sono perso da giorni!\"",
    "dungeon.guide_to_safety": "Guidalo in salvo",
    "dungeon.rob_and_leave": "Derubalo e vattene",
    "dungeon.leave_them": "Lascialo stare",
    "dungeon.rob_explorer": "Spingi l'esploratore contro il muro e gli porti via i suoi averi.",
    "dungeon.rob_explorer_cry": "\"No! Vi prego! È tutto quello che ho!\"",
    "dungeon.rob_explorer_gold": "Gli rubi {0} monete d'oro.",
    "dungeon.darkness_increases": "La tua oscurità aumenta...",
    "dungeon.guide_explorer": "Lo guidi in salvo.",
    "dungeon.explorer_reward": "Ti ricompensa con {0} monete d'oro!",
    "dungeon.chivalry_increases": "La tua cavalleria aumenta!",
    "dungeon.leave_explorer": "Passi oltre senza una parola.",
    "dungeon.explorer_plea": "\"Aspettate! Per favore, non lasciatemi qui!\"",
    "dungeon.explorer_fades": "La sua voce si affievolisce dietro di te.",
    "dungeon.cloaked_figure": "Una figura incappucciata emerge dalle ombre...",
    "dungeon.cloaked_figure_fate": "\"Il destino ci ha fatti incontrare...\"",
    "dungeon.cloaked_blessing": "Ti offre una benedizione!",
    "dungeon.cloaked_revitalized": "Ti senti rinvigorito!",
    "dungeon.cloaked_beware": "\"Guardati dall'oscurità che ti attende...\"",
    "dungeon.cloaked_vanish": "Svanisce misteriosamente così com'è apparsa.",
    "dungeon.mechanism_unlocks": "L'antico meccanismo si sblocca!",
    "dungeon.puzzle_gold_xp": "Ricevi {0} monete d'oro e {1} punti esperienza!",
    "dungeon.riddle_truth": "Risolvendo l'enigma, una verità più profonda risuona dentro di te...",
    "dungeon.ocean_wisdom": "Hai ottenuto un frammento della saggezza dell'Oceano...",
    "dungeon.gate_sealed": "Il portale resta sigillato.",
    "dungeon.trap_activates": "Una trappola si attiva! Subisci {0} danni!",
    "dungeon.attempts_remaining": "Tentativi rimanenti: {0}",
    "dungeon.not_quite_right": "Non è del tutto corretto...",
    "dungeon.puzzle_gain_gold_xp": "Guadagni {0} monete d'oro e {1} punti esperienza!",
    "dungeon.puzzle_failed": "Il rompicapo si resetta. Non sei riuscito a risolverlo.",
    "dungeon.trap_springs": "Una trappola scatta! Subisci {0} danni!",
    "dungeon.lever_puzzle": "Ci sono {0} leve. Inserisci la sequenza (es. 1,2,3):",
    "dungeon.symbol_puzzle": "Simboli disponibili: {0}",
    "dungeon.symbol_enter": "Inserisci {0} simboli separati da virgole:",
    "dungeon.number_target": "Somma obiettivo: {0}",
    "dungeon.number_available": "Numeri disponibili: {0}",
    "dungeon.number_enter": "Inserisci i numeri che danno la somma obiettivo:",
    "dungeon.memorize": "Memorizza questa sequenza:",
    "dungeon.enter_sequence": "Inserisci la sequenza che hai visto:",
    "dungeon.careful_thought": "Questo rompicapo richiede attenta riflessione...",
    "dungeon.examine_carefully": "Esamina con attenzione e deduci la risposta",
    "dungeon.try_random": "Tenta un approccio casuale",
    "dungeon.give_up": "Rinuncia",
    "dungeon.stone_door": "Un'imponente porta di pietra ti sbarra il cammino.",
    "dungeon.stone_face": "Scolpito sulla sua superficie: un volto, antico e sapiente.",
    "dungeon.stone_riddle": "Le labbra di pietra si muovono: 'Rispondi al mio enigma per passare.'",
    "dungeon.stone_correct": "Il volto di pietra sorride. 'La saggezza apre ogni porta.'",
    "dungeon.stone_open": "Il portale si apre con un rombo.",
    "dungeon.riddle_xp": "Guadagni {0} punti esperienza!",
    "dungeon.riddle_deeper": "Il significato più profondo dell'enigma risuona dentro di te...",
    "dungeon.gate_guardian": "Il guardiano del portale si manifesta per punire la tua ignoranza!",
    "dungeon.sense_power": "Avverti che un grande potere risiedeva qui un tempo.",
    "dungeon.moved_on": "Ma qualunque cosa dimorasse in questo luogo... se n'è andata.",
    "dungeon.perhaps_deeper": "Forse più in profondità nel sotterraneo troverai ciò che cerchi.",
    "dungeon.sanctuary_discover": "Scopri un santuario nascosto!",
    "dungeon.sanctuary_calm": "L'aria qui è calma, protetta da magia antica.",
    "dungeon.sanctuary_camp": "Ti accampi e recuperi le forze.",
    "dungeon.sanctuary_hp": "Recuperi {0} PV!",
    "dungeon.sanctuary_mana": "Recuperi {0} mana!",
    "dungeon.sanctuary_stamina": "Recuperi {0} resistenza!",
    "dungeon.sanctuary_cure_poison": "La magia del santuario cura il tuo veleno!",
    "dungeon.sanctuary_close_eyes": "Chiudi gli occhi...",
    "dungeon.sanctuary_sleep_deep": "Dormi profondamente sotto la protezione del santuario...",
    "dungeon.sanctuary_new_day": "Ti risvegli rinvigorito. Un nuovo giorno è sorto. (Giorno {0})",
    "dungeon.sanctuary_already_rested": "Ti sei già riposato su questo piano.",
    "dungeon.sanctuary_no_benefit": "Il santuario non offre ulteriori benefici.",
    "dungeon.vision_overtakes": "Una strana visione ti sopraffà...",
    "dungeon.vision_layout": "Vedi la struttura di questo piano!",
    "dungeon.rooms_revealed": "Tutte le stanze sono ora rivelate sulla tua mappa!",
    "dungeon.reality_warps": "La realtà si distorce intorno a te!",
    "dungeon.feel_stronger": "Quando si dirada, ti senti più giovane, più forte!",
    "dungeon.ghost_appears_room": "Una figura spettrale appare!",
    "dungeon.ghost_seek_chamber": "\"Cerca la camera delle ossa...\"",
    "dungeon.ghost_find_seek": "\"Là troverai ciò che cerchi...\"",
    "dungeon.ghost_points": "Lo spettro indica una direzione e svanisce.",
    "dungeon.portal_opens": "Un portale magico si apre improvvisamente sotto di te!",
    "dungeon.transported_to": "Vieni trasportato a: {0}!",
    "dungeon.gold_rains": "Monete d'oro piovono dal soffitto!",
    "dungeon.gather_gold": "Raccogli {0} monete d'oro!",
    "dungeon.lore_library_1": "Granelli di polvere danzano nella luce pallida di una fonte ignota.",
    "dungeon.lore_library_2": "Tomi antichi rivestono pareti che si estendono oltre la vista.",
    "dungeon.lore_library_tome": "Un tomo fluttua giù dagli scaffali, aprendosi davanti a te...",
    "dungeon.lore_library_burns": "Le parole si imprimono nella tua memoria...",
    "dungeon.lore_library_stirs": "Qualcosa si agita nelle profondità della tua coscienza...",
    "dungeon.lore_library_nothing": "Consulti i testi antichi, ma non trovi nulla di nuovo.",
    "dungeon.lore_library_known": "La conoscenza qui custodita vive già dentro di te.",
    "dungeon.memory_mirrors_1": "Le pareti qui sono specchi, ma non mostrano il tuo riflesso.",
    "dungeon.memory_mirrors_2": "Mostrano... qualcun altro. Qualcuno di familiare.",
    "dungeon.memory_surfaces": "Un ricordo affiora: \"{0}\"",
    "dungeon.memory_fades": "La visione svanisce, ma la sensazione rimane.",
    "dungeon.memory_fragments": "Gli specchi mostrano frammenti di una vita non del tutto tua.",
    "dungeon.memory_not_yet": "Senti che c'è altro da ricordare, ma non qui. Non ancora.",
    "dungeon.settlement_poison_cured": "Il veleno nelle tue vene viene estratto.",
    "dungeon.settlement_hp_restored": "Ripristinati {0} PV.",
    "dungeon.settlement_mana_restored": "Ripristinati {0} Mana.",
    "dungeon.settlement_no_heal_needed": "\"Mi sembri abbastanza in forma. Risparmia le tue monete.\"",
    "dungeon.settlement_your_gold": "Il tuo Oro: {0}",
    "dungeon.settlement_purchased": "Acquistato {0}!",
    "dungeon.battle_breaks_open": "Mentre la battaglia finisce, qualcosa si apre nella tua mente...",
    "dungeon.explore_1": "Avanzi con cautela attraverso i corridoi in penombra...",
    "dungeon.explore_2": "I tuoi passi riecheggiano nei passaggi di pietra antica...",
    "dungeon.explore_3": "La luce tremolante delle torce rivela misteriose porte più avanti...",
    "dungeon.explore_4": "L'aria si fa più fredda mentre ti addentri nel sotterraneo...",
    "dungeon.explore_5": "Suoni inquietanti riecheggiano dall'oscurità oltre...",
    "dungeon.terrain_underground": "Antichi Tunnel Sotterranei",
    "dungeon.terrain_mountains": "Passaggi tra le Montagne Rocciose",
    "dungeon.terrain_desert": "Rovine e Tombe del Deserto",
    "dungeon.terrain_forest": "Grotte della Foresta Rigogliosa",
    "dungeon.terrain_caves": "Caverne Naturali Profonde",
    "dungeon.terrain_unknown": "Territorio Sconosciuto",
    "dungeon.bbs_fight": "Combatti",
    "dungeon.bbs_treasure": "Tesoro",
    "dungeon.bbs_investigate": "Indaga",
    "dungeon.bbs_examine": "Esamina",
    "dungeon.bbs_descend": "Discendi",
    "dungeon.bbs_camp": "Accampamento",
    "dungeon.bbs_map_label": "Mappa",
    "dungeon.bbs_guide_label": "Guida",
    "dungeon.bbs_inv": "Inv",
    "dungeon.bbs_potions_label": "Pozioni",
    "dungeon.bbs_status_label": "Stato",
    "dungeon.bbs_leave": "Esci",
    "dungeon.bbs_enter": "Entra",
    "dungeon.bbs_journal": "Diario",
    "dungeon.bbs_party": "Gruppo",
    "dungeon.bbs_level_change": "Livello(+/-10)",
    "dungeon.bbs_return": "Ritorna",
    "dungeon.ask_join_yn": "Chiederle di unirsi a te? (S/N): ",
    "dungeon.companion_warning": "ATTENZIONE: I compagni possono morire permanentemente. Proteggila bene.",
    "dungeon.personal_quest": "Missione Personale: {0}",
    "dungeon.pixie_appears": "Una piccola folletta luminosa sfreccia nel corridoio!",
    "dungeon.pixie_giggles": "Svolazza lasciando scie di scintille, ridacchiando con malizia.",
    "dungeon.pixie_catch": "Cerca di catturarla",
    "dungeon.pixie_leave": "Lasciala stare",
    "dungeon.pixie_caught": "Afferri delicatamente la folletta dall'aria!",
    "dungeon.pixie_eyes": "Ti guarda con occhi scintillanti...",
    "dungeon.pixie_kiss_quote": "\"Oh! Sei veloce! E va bene, un bacio per il furbo!\"",
    "dungeon.pixie_restored": "Il bacio della folletta ti riempie di calore. Ti senti completamente ristabilito!",
    "dungeon.pixie_blessing": "Una benedizione fatata ti avvolge! (+15% danni/difesa per 5 combattimenti)",
    "dungeon.pixie_blessing_stronger": "La tua benedizione si rafforza! (+3 turni bonus di combattimento)",
    "dungeon.pixie_gold": "Cosparge polvere fatata che si trasforma in oro! (+{0} monete d'oro)",
    "dungeon.pixie_vanish": "La folletta fa l'occhiolino e svanisce in una pioggia di scintille.",
    "dungeon.pixie_dodge": "La folletta schiva la tua presa!",
    "dungeon.pixie_clumsy": "\"Mortale maldestro! Te ne pentirai!\"",
    "dungeon.pixie_dust": "Ti soffia in faccia una nube di polvere scintillante!",
    "dungeon.pixie_poisoned": "La polvere fatata ti dà la nausea... sei stato avvelenato!",
    "dungeon.pixie_steals": "Ti ruba {0} monete d'oro dalla borsa mentre vola via!",
    "dungeon.pixie_cackles": "La folletta sghignazza e scompare in una nuvola di brillantini.",
    "dungeon.pixie_watch": "Guardi la folletta svolazzare via, le sue risate riecheggiano sulle pareti.",
    "dungeon.pixie_alone": "Forse certe cose è meglio lasciarle stare.",
    "dungeon.rival_fight_prompt": "(C)ombatti, (N)egozia, o (L)ascia? ",
    "dungeon.riddle_header": "*** PORTALE DELL'ENIGMA ***",
    "dungeon.puzzle_header": "*** ROMPICAPO ANTICO ***",
    "dungeon.puzzle_solved_header": "*** ROMPICAPO RISOLTO! ***",
    "dungeon.mystery_header": "*** EVENTO MISTERIOSO ***",
    "dungeon.mystery_xp_plus": "+{0} esperienza!",
    "dungeon.riddle_gate_header": "IL PORTALE DELL'ENIGMA",
    "dungeon.riddle_solved_header": "ENIGMA RISOLTO",
    "dungeon.riddle_failed_header": "ENIGMA FALLITO",
    "dungeon.riddle_foolish_mortal": "Sciocco mortale. C'è un prezzo per il fallimento.",
    "dungeon.lore_library_header": "ANTICA BIBLIOTECA DEL SAPERE",
    "dungeon.lore_library_always_did": "...o forse lo è sempre stata.",
    "dungeon.memory_chamber_header": "CAMERA DELLA MEMORIA",
    "dungeon.hidden_chamber_header": "CAMERA NASCOSTA",
    "dungeon.memory_puzzle_header": "*** ROMPICAPO DI MEMORIA ***",
    "dungeon.beggar_header": "☂ INCONTRO COL MENDICANTE ☂",
    "dungeon.beggar_give_label": "  (D) Dona oro              (+Cavalleria)",
    "dungeon.beggar_rob_label": "  (R) Deruba il mendicante  (+Oscurità)",
    "dungeon.beggar_ignore_label": "  (I) Ignora e prosegui",
    "dungeon.beggar_chivalry": "+5 Cavalleria",
    "dungeon.beggar_darkness": "+10 Oscurità",
    "dungeon.seal_ancient_power": "       Mentre esplori la stanza, un potere antico si risveglia...",
    "dungeon.seal_stone_tablet": "  Nascosta sotto la polvere dei secoli, trovi una tavola di pietra.",
    "dungeon.seal_divine_energy": "  Pulsa di energia divina, calda al tatto.",
    "dungeon.seal_seven_seals": "  Questo è uno dei Sette Sigilli — la verità degli Antichi Dèi.",
    "dungeon.seal_press_enter": "  Premi Invio per continuare...",
    "dungeon.artifact_header": "      UN ARTEFATTO DIVINO PULSA DI POTERE!",
    "dungeon.wave_fragment_collected": "(Frammento d'Onda raccolto: {0})",
    "dungeon.group_leader_not_entered": "  Il tuo capo gruppo non è ancora entrato nel sotterraneo.",
    "dungeon.wait_for_leader": "  Aspetta che il tuo capo entri per primo, poi seguilo.",
    "dungeon.sr_title": "  I SOTTERRANEI",
    "dungeon.sr_subtitle": "  Lasciate ogni speranza o voi ch'entrate",
    "dungeon.continuing": "  [Riprendi da dove avevi interrotto...]",
    "dungeon.respawned": "  [La magia oscura del sotterraneo ha richiamato nuove creature dagli abissi...]",
    "dungeon.god_awaits_return": "  {0} attende il tuo ritorno. Hai l'artefatto.",
    "dungeon.god_awaits_rescue": "  {0} attende il soccorso. Cerca l'artefatto nei piani più profondi.",
    "dungeon.press_enter_continue": "  Premi Invio per continuare...",
    "dungeon.seal_on_floor": "[!] Questo piano contiene un Sigillo della Verità. Esplora con attenzione.",
    "dungeon.seal_rooms_available": "    Stanze di scoperta dei Sigilli disponibili: {0}",
    "dungeon.seal_already_collected": "[i] Il sigillo di questo piano è già stato raccolto.",
    "dungeon.story_depths_title": "Le Profondità Cominciano",
    "dungeon.story_depths_1": "Mentre scendi al livello 10, l'aria si fa più pesante.",
    "dungeon.story_depths_2": "Le pareti qui sono più antiche, scolpite da mani che precedono la memoria.",
    "dungeon.story_depths_3": "Noti strani simboli ripetuti ovunque — sette cerchi intrecciati.",
    "dungeon.story_depths_4": "Un disegno che richiama qualcosa nel profondo del tuo essere...",
    "dungeon.story_depths_5": "Da qualche parte più avanti, le risposte ti attendono.",
    "dungeon.story_battlefield_title": "Campo di Battaglia Antico",
    "dungeon.story_battlefield_1": "Le pietre qui sono macchiate di qualcosa di antico.",
    "dungeon.story_battlefield_2": "Non ruggine. Non sangue mortale. Qualcosa... dorato.",
    "dungeon.story_battlefield_3": "Armi di fattura impossibile giacciono sparse al suolo.",
    "dungeon.story_battlefield_4": "Troppo grandi per mani umane. Troppo pesanti per braccia mortali.",
    "dungeon.story_battlefield_5": "Qualcosa di terribile è accaduto qui, molto prima che la storia avesse inizio.",
    "dungeon.story_battlefield_6": "Un SIGILLO DELLA VERITÀ giace nascosto su questo piano.",
    "dungeon.story_battlefield_7": "Cerca un santuario, una biblioteca o una camera sacra per trovarlo.",
    "dungeon.story_whispers_title": "I Sussurri Cominciano",
    "dungeon.story_whispers_1": "La senti ora — una voce al confine della percezione.",
    "dungeon.story_whispers_2": "Non ti parla. Parla COME te.",
    "dungeon.story_whispers_5": "La voce conosce il tuo vero nome.",
    "dungeon.story_whispers_6": "Il nome che hai dimenticato.",
    "dungeon.story_shrine_title": "Santuario Corrotto",
    "dungeon.story_shrine_1": "Sette statue sono disposte in cerchio, i volti consumati dal tempo.",
    "dungeon.story_shrine_2": "Ma qualcosa non va in loro.",
    "dungeon.story_shrine_3": "La pietra stessa sembra... malata. Contorta.",
    "dungeon.story_shrine_4": "Come se le sculture fossero state alterate dopo la loro creazione.",
    "dungeon.story_shrine_5": "Forme splendide deformate in qualcosa di grottesco.",
    "dungeon.story_shrine_6": "Quale forza potrebbe corrompere la pietra stessa?",
    "dungeon.story_shrine_7": "Un SIGILLO DELLA VERITÀ attende chi cerca risposte qui.",
    "dungeon.veloura_warmth": "Senti un calore familiare quando metti piede su questo piano...",
    "dungeon.veloura_senses": "Veloura avverte il tuo ritorno — e ciò che porti con te.",
    "dungeon.story_prison_title": "Prigione dei Secoli",
    "dungeon.story_prison_1": "Celle vuote si estendono nell'oscurità.",
    "dungeon.story_prison_2": "Non celle per mortali — queste sono vaste. Grandi come cattedrali.",
    "dungeon.story_prison_3": "Le sbarre sono fatte di qualcosa che non è metallo.",
    "dungeon.story_prison_4": "Qualcosa che vibra di potere ancora adesso.",
    "dungeon.story_prison_5": "Qualunque cosa fosse rinchiusa qui era immensa. E furiosa.",
    "dungeon.story_prison_6": "Segni di artigli solcano le pareti, più profondi di qualsiasi lama.",
    "dungeon.story_prison_7": "Un SIGILLO DELLA VERITÀ custodisce la risposta su chi fu imprigionato qui.",
    "dungeon.story_oracle_title": "Tomba dell'Oracolo",
    "dungeon.story_oracle_1": "Uno scheletro siede su un trono d'ossa.",
    "dungeon.story_oracle_2": "In morte, stringe ancora un globo di cristallo.",
    "dungeon.story_oracle_3": "L'Oracolo. L'ultimo mortale a parlare con gli dèi.",
    "dungeon.story_oracle_4": "Vide il futuro prima di morire.",
    "dungeon.story_oracle_5": "E ciò che vide la fece piangere.",
    "dungeon.story_oracle_6": "Parole sono incise nella pietra ai suoi piedi:",
    "dungeon.story_oracle_8": "Un SIGILLO DELLA VERITÀ ti attende. Custodisce la sua ultima profezia.",
    "dungeon.ground_trembles": "Il suolo trema. Una presenza antica si risveglia...",
    "dungeon.face_maelketh": "Vuoi affrontare Maelketh, la Lama Spezzata? (S/N)",
    "dungeon.god_retreats": "Senti il dio ritirarsi nel sonno... per ora.",
    "dungeon.story_soulweaver_title": "La Camera del Tessitore di Anime",
    "dungeon.story_soulweaver_1": "Nel profondo di questa camera dimenticata, qualcosa di antico ti chiama...",
    "dungeon.story_soulweaver_2": "Un congegno di delicatezza impossibile poggia su un piedistallo di pietra.",
    "dungeon.story_soulweaver_3": "Fili di luce si librano come ragnatele nella brezza.",
    "dungeon.story_soulweaver_4": "Questo è il Telaio del Tessitore di Anime — l'artefatto che può annullare la corruzione divina.",
    "dungeon.story_soulweaver_5": "Proprio ciò che hai promesso di trovare.",
    "dungeon.remember_veloura": "  Ricordi la tua promessa a Veloura al piano 40.",
    "dungeon.return_veloura_loom": "  Torna da lei con il Telaio per completare il salvataggio.",
    "dungeon.story_soulweaver_price_title": "Il Prezzo del Tessitore di Anime",
    "dungeon.story_soulweaver_price_1": "Il Telaio del Tessitore di Anime pulsa di potere nelle tue mani.",
    "dungeon.story_soulweaver_price_2": "E davanti a te c'è qualcuno che non ti aspettavi di rivedere...",
    "dungeon.story_echoes_title": "Camera degli Echi",
    "dungeon.story_echoes_1": "Vedi te stesso nelle pareti.",
    "dungeon.story_echoes_2": "Non un riflesso — un ricordo.",
    "dungeon.story_echoes_3": "Sei già stato qui.",
    "dungeon.story_echoes_4": "Mille volte. Un milione.",
    "dungeon.story_echoes_5": "Il ciclo si ripete.",
    "dungeon.story_echoes_6": "Manwe invia un frammento di sé per sperimentare la mortalità.",
    "dungeon.story_echoes_7": "Per imparare. Per crescere. Per ricordare cosa significa essere piccoli.",
    "dungeon.story_echoes_8": "E alla fine, il frammento ritorna...",
    "dungeon.story_echoes_9": "A meno che questa volta non lo faccia.",
    "dungeon.story_mourning_title": "Camera del Lutto",
    "dungeon.story_mourning_1": "Le pareti qui sono di cristallo.",
    "dungeon.story_mourning_2": "Grigio-azzurre. Fredde. E bagnate.",
    "dungeon.story_mourning_3": "Non acqua. Qualcosa di più denso. Più salato.",
    "dungeon.story_mourning_4": "Come se questi cristalli si fossero formati dalle lacrime.",
    "dungeon.story_mourning_5": "Oceani di lacrime, versate per millenni.",
    "dungeon.story_mourning_6": "Congelate nella pietra. Un monumento al dolore.",
    "dungeon.story_mourning_7": "Di chi è il dolore che potrebbe riempire una montagna?",
    "dungeon.story_mourning_8": "Il SIGILLO DELLA VERITÀ su questo piano custodisce la risposta.",
    "dungeon.story_purging_title": "La Luce Purificatrice",
    "dungeon.story_purging_1": "Aurelion si erge davanti a te, radioso di luce divina.",
    "dungeon.story_purging_2": "La Lama Forgiata dal Sole arde luminosa nelle tue mani.",
    "dungeon.story_purging_3": "'Hai meritato questo momento,' parla il Dio della Luce.",
    "dungeon.story_purging_4": "Ti offro il potere di annientare ogni oscurità per sempre.",
    "dungeon.story_threshold_title": "La Soglia",
    "dungeon.story_threshold_1": "Ti trovi al confine della comprensione.",
    "dungeon.story_threshold_2": "Un piano sopra, Manwe attende.",
    "dungeon.story_threshold_3": "Il Creatore. Il tuo creatore.",
    "dungeon.story_threshold_4": "O forse... te stesso?",
    "dungeon.story_threshold_5": "Sei l'onda che ha ricordato di essere l'oceano.",
    "dungeon.story_threshold_6": "E ora l'oceano deve rispondere di ciò che ha fatto.",
    "dungeon.story_threshold_7": "Raccogli l'ultimo sigillo se non l'hai ancora fatto.",
    "dungeon.story_threshold_8": "Poi affronta la verità.",
    "dungeon.story_end_title": "La Fine di Ogni Cosa",
    "dungeon.story_end_1": "Ci siamo.",
    "dungeon.story_end_2": "Oltre questa soglia, Manwe sogna.",
    "dungeon.story_end_3": "Il Creatore che ha creato ogni cosa.",
    "dungeon.story_end_4": "Il dio che ha spezzato i propri figli.",
    "dungeon.story_end_5": "L'oceano che ha dimenticato di essere acqua.",
    "dungeon.story_end_6": "Hai tre scelte:",
    "dungeon.story_end_7": "  - DISTRUGGILO e prendi il suo potere (Usurpatore)",
    "dungeon.story_end_8": "  - SALVALO e restaura gli dèi (Salvatore)",
    "dungeon.story_end_9": "  - SFIDALO e forgia il tuo cammino (Ribelle)",
    "dungeon.story_end_10": "Oppure, se hai raccolto tutti e Sette i Sigilli...",
    "dungeon.story_end_11": "Forse qualcos'altro è possibile.",
    "dungeon.story_end_12": "Scegli saggiamente. Questa è l'unica scelta che conta.",
    "dungeon.allies_rejoin": "{0} alleato/i si riuniscono al tuo gruppo dal tuo ultimo accesso.",
    "dungeon.allies_skipped": "{0} alleato/i non hanno potuto rientrare — il gruppo è al completo (massimo {1}).",
    "dungeon.use_party_management": "Usa la Gestione del Gruppo per modificare la composizione.",
    "dungeon.not_on_team": "  {0} non fa più parte della tua squadra.",
    "dungeon.echo_materializes": "  L'eco di {0} si materializza al tuo fianco!",
    "dungeon.echoes_info": "  Gli echi dei giocatori combattono come alleati IA con le loro statistiche reali.",
    "dungeon.bodyguards_join": "  Le tue guardie del corpo reali si uniscono a te ({0}):",
    "dungeon.merc_level_class": " - Livello {0} {1}",
    "dungeon.need_gold_fee": "Ti servono {0} monete d'oro ma ne hai solo {1}!",
    "dungeon.allies_too_expensive": "Questi alleati chiedono più oro di quello che possiedi:",
    "dungeon.pay_affordable": "Pagare {0} monete d'oro per gli alleati che puoi permetterti? (S/N): ",
    "dungeon.paid_gold": "Pagate {0} monete d'oro.",
    "dungeon.staying_behind": "Restano indietro:",
    "dungeon.waits_at_entrance": "  {0} attende all'ingresso.",
    "dungeon.pay_all_allies": "Pagare {0} monete d'oro per portare i tuoi alleati? (S/N): ",
    "dungeon.paid_allies_prepare": "Pagate {0} monete d'oro. I tuoi alleati si preparano per il sotterraneo.",
    "dungeon.remaining_gold": "Oro rimanente: {0}",
    "dungeon.decline_pay": "Decidi di non pagare. I tuoi alleati non ti accompagneranno questa volta.",
    "dungeon.stays_behind": "  {0} resta indietro.",
    "dungeon.how_respond": "  Come rispondi?",
    "dungeon.your_response": "La tua risposta: ",
    "dungeon.god_fallen": "L'Antico Dio è caduto. Il suo potere fluisce dentro di te.",
    "dungeon.obtained_artifact": "Hai ottenuto: {0}!",
    "dungeon.xp_gained": "Esperienza ottenuta: {0}",
    "dungeon.gold_gained": "Oro ottenuto: {0}",
    "dungeon.darkness_deepens": "La tua oscurità si approfondisce. Stai diventando l'Usurpatore.",
    "dungeon.god_corruption_lifts": "La corruzione dell'Antico Dio si dissolve. Ricorda chi era.",
    "dungeon.divine_gratitude": "Un frammento di gratitudine divina riempie il tuo cuore.",
    "dungeon.chivalry_grows": "La tua cavalleria cresce. Stai diventando il Salvatore.",
    "dungeon.god_alliance": "L'Antico Dio vede qualcosa in te. Una comprensione.",
    "dungeon.forged_alliance": "Hai forgiato un'alleanza oltre la comprensione mortale.",
    "dungeon.god_spared_hope": "Gli occhi dell'Antico Dio si spalancano per qualcosa di dimenticato da tempo — la speranza.",
    "dungeon.god_spared_lingers": "Svaniscono da questo luogo, ma la loro presenza permane nel tuo cuore.",
    "dungeon.promised_loom": "Hai promesso di trovare il Telaio del Tessitore di Anime e tornare.",
    "dungeon.artifact_deeper": "L'artefatto giace da qualche parte più in profondità nel sotterraneo...",
    "dungeon.chivalry_mercy": "+75 Cavalleria — La tua misericordia parla più forte di qualsiasi lama.",
    "dungeon.quest_started_loom": "  [MISSIONE INIZIATA] Trova il Telaio del Tessitore di Anime e torna a salvare questo dio.",
    "dungeon.god_fled_retreat": "Ti ritiri dalla presenza divina.",
    "dungeon.god_fled_wait": "L'Antico Dio ti guarda andare. Può attendere.",
    "dungeon.god_slayer_buff": "  Il potere divino ti attraversa! (+20% danni, +10% difesa per {0} combattimenti)",
    "dungeon.emerge_steps": "  Risali gli ultimi gradini dall'oscurità.",
    "dungeon.emerge_sunlight": "  La luce del sole ti acceca. L'aria qui ha un sapore diverso — pulita, viva.",
    "dungeon.word_spread": "  La voce si è già sparsa.",
    "dungeon.outcome_slain": "ucciso",
}
