translations = {
    "dungeon.outcome_saved": "salvato",
    "dungeon.outcome_allied": "alleato con",
    "dungeon.outcome_mercy": "risparmiato",
    "dungeon.outcome_faced": "affrontato",
    "dungeon.they_know": "  Sanno cosa hai fatto laggiù. Hai {0} {1}.",
    "dungeon.closing_defeated": "La folla si apre al tuo passaggio verso la piazza. Nessuno sostiene il tuo sguardo a lungo.",
    "dungeon.closing_saved": "Cammini verso la piazza e, per la prima volta da tempo, la città sembra più leggera.",
    "dungeon.closing_allied": "Cammini verso la piazza. La gente mormora, ma nessuno osa parlare contro di te.",
    "dungeon.closing_spared": "Cammini verso la piazza. Alcuni annuiscono con quieto rispetto. Altri distolgono lo sguardo.",
    "dungeon.closing_default": "Cammini verso la piazza.",
    "dungeon.breadcrumb_old_woman": "  Mentre la folla si disperde, una vecchia ti afferra il braccio.",
    "dungeon.breadcrumb_next_god": "  \\",
    "dungeon.react_maelketh_def_agg_1": "La folla si apre davanti a te. Un veterano borbotta sottovoce.",
    "dungeon.react_maelketh_def_agg_3": "I bambini vengono portati in casa di fretta. Le imposte si chiudono.",
    "dungeon.react_maelketh_def_hum_1": "I bambini sbirciano da dietro le madri mentre emergi.",
    "dungeon.react_maelketh_def_hum_3": "Un vecchio soldato ti saluta — il primo vero saluto da anni.",
    "dungeon.react_maelketh_def_def_1": "La folla fissa incredula. Il dio della guerra non c'è più.",
    "dungeon.react_maelketh_def_def_2": "Un fabbro posa il martello. \\",
    "dungeon.react_maelketh_sav_1": "Un vecchio soldato piange apertamente per strada.",
    "dungeon.react_maelketh_sav_3": "Qualcuno intona un inno. Altri si uniscono, esitanti all'inizio, poi con convinzione.",
    "dungeon.react_maelketh_other_1": "La folla ti osserva con cauto rispetto.",
    "dungeon.react_veloura_def_agg_1": "Una coppia si stringe forte al tuo passaggio.",
    "dungeon.react_veloura_def_agg_3": "La fioraia all'angolo raccoglie in silenzio la sua bancarella.",
    "dungeon.react_veloura_def_merc_1": "La folla è silenziosa. Una donna depone un fiore all'ingresso del dungeon.",
    "dungeon.react_veloura_def_merc_2": " dice qualcuno. Nessuno obietta. Nessuno concorda.",
    "dungeon.react_veloura_def_def_1": "La città sembra più fredda in qualche modo, anche alla luce del sole.",
    "dungeon.react_veloura_def_def_2": "Un bardo si ferma a metà canzone, incapace di ricordare le parole di una ballata d'amore.",
    "dungeon.react_veloura_sav_1": "Le campane del tempio risuonano per tutta la città.",
    "dungeon.react_veloura_sav_2": " grida qualcuno da un tetto.",
    "dungeon.react_veloura_sav_3": "Sconosciuti si abbracciano per strada. Vecchi rancori sembrano addolcirsi.",
    "dungeon.react_veloura_other_1": "La gente sembra più calorosa mentre attraversi la città.",
    "dungeon.react_veloura_other_2": "Una giovane coppia incrocia il tuo sguardo e china il capo in segno di gratitudine.",
    "dungeon.react_thorgrim_def_defy_1": "Il magistrato osserva dalla finestra, il volto pallido.",
    "dungeon.react_thorgrim_def_defy_2": "Le guardie stringono la presa sulle lance al tuo passaggio.",
    "dungeon.react_thorgrim_def_hon_1": "Il giudice della città si toglie il cappello al tuo passaggio.",
    "dungeon.react_thorgrim_def_def_1": "La bandiera del tribunale sventola a mezz'asta.",
    "dungeon.react_thorgrim_def_def_2": "Avvocati e giudici mormorano nervosamente. La legge sembra meno certa oggi.",
    "dungeon.react_thorgrim_sav_1": "La città si allinea in file ordinate per inchinarsi al tuo arrivo.",
    "dungeon.react_thorgrim_sav_3": "Un senso d'ordine si posa sulla città come una coperta calda.",
    "dungeon.react_thorgrim_other_1": "La guardia cittadina si raddrizza un po' di più al tuo passaggio.",
    "dungeon.react_noctura_ally_1": "La gente evita il tuo sguardo mentre attraversi la piazza.",
    "dungeon.react_noctura_ally_2": "Le ombre che proietti sembrano... più lunghe del dovuto.",
    "dungeon.react_noctura_ally_3": "La gilda dei ladri lascia una singola piuma nera sulla tua soglia.",
    "dungeon.react_noctura_def_agg_1": "Le lanterne ardono in ogni finestra stanotte.",
    "dungeon.react_noctura_def_agg_2": " Ma la celebrazione sembra vuota.",
    "dungeon.react_noctura_def_agg_3": "Alcuni si chiedono in silenzio: chi sorveglia l'oscurità adesso?",
    "dungeon.react_noctura_def_def_1": "I lampioni sembrano più luminosi. I vicoli meno profondi.",
    "dungeon.react_noctura_def_def_2": " dice un guardiano notturno, sollevato.",
    "dungeon.react_noctura_sav_1": "La gilda dei ladri alza un brindisi discreto a porte chiuse.",
    "dungeon.react_noctura_sav_2": "I mercanti controllano due volte le serrature stanotte.",
    "dungeon.react_noctura_sav_3": "Ma le ombre sembrano... vigili. Protettive, persino.",
    "dungeon.react_noctura_other_1": "La città è più silenziosa stanotte. Più calma.",
    "dungeon.react_noctura_other_2": "L'oscurità cala come sempre, ma sembra più gentile in qualche modo.",
    "dungeon.react_aurelion_def_comp_1": "Il coro del tempio intona un canto funebre mentre la notizia si diffonde.",
    "dungeon.react_aurelion_def_comp_2": "Ma la somma sacerdotessa incrocia il tuo sguardo e annuisce. Lei capisce.",
    "dungeon.react_aurelion_def_comp_3": " dice sommessamente.",
    "dungeon.react_aurelion_def_def_1": "Il sacerdote cade in ginocchio per strada.",
    "dungeon.react_aurelion_def_def_3": "Nubi temporalesche si addensano in cielo. La città non è mai sembrata così cupa.",
    "dungeon.react_aurelion_sav_1": "Una luce dorata squarcia le nubi mentre emergi.",
    "dungeon.react_aurelion_sav_2": "La folla cade in ginocchio, le lacrime rigano i volti.",
    "dungeon.react_aurelion_sav_3": " Il grido echeggia da tetto a tetto.",
    "dungeon.react_aurelion_sav_4": "Le campane del tempio suonano con un ritmo che non si udiva da mille anni.",
    "dungeon.react_aurelion_other_1": "Il sole del pomeriggio sembra più caldo del solito.",
    "dungeon.react_aurelion_other_2": "La gente si ripara gli occhi, scrutando verso l'alto, percependo qualcosa di cambiato.",
    "dungeon.react_terravok_def_resp_1": "I muratori si inchinano al tuo passaggio. Conoscono la pietra meglio di chiunque.",
    "dungeon.react_terravok_def_def_1": "Il terreno trema sotto i tuoi piedi mentre emergi.",
    "dungeon.react_terravok_def_def_2": "Gli edifici scricchiolano. La polvere cade dalle travi.",
    "dungeon.react_terravok_def_def_3": " mormora qualcuno. Nessuno ha una risposta.",
    "dungeon.react_terravok_sav_1": "La terra stessa sembra sospirare di sollievo.",
    "dungeon.react_terravok_sav_2": "Le crepe nelle mura della città si richiudono davanti ai tuoi occhi.",
    "dungeon.react_terravok_sav_3": "Il vecchio pozzo, arido da decenni, ricomincia a zampillare.",
    "dungeon.react_terravok_other_1": "I ciottoli sembrano più saldi sotto i tuoi piedi.",
    "dungeon.react_terravok_other_2": "I minatori ti salutano dall'altra parte della piazza. Lo sentono nella pietra.",
    "dungeon.react_default_1": "La città ti guarda emergere dal dungeon in silenzio.",
    "dungeon.react_default_2": "Qualcosa è cambiato. Tutti lo percepiscono.",
    "dungeon.ambient_drips": "L'acqua gocciola da qualche parte nell'oscurità davanti a te.",
    "dungeon.ambient_torch": "La tua torcia vacilla in una corrente invisibile.",
    "dungeon.ambient_skitters": "Qualcosa scalpita debolmente dietro le pareti.",
    "dungeon.ambient_draft": "Una corrente fredda filtra attraverso le pietre.",
    "dungeon.ambient_groan": "Il pavimento si assesta con un gemito sommesso.",
    "dungeon.ambient_clang": "Un clangore lontano di metallo riecheggia dal profondo.",
    "dungeon.ambient_shadows": "Le ombre ai margini della tua luce sembrano muoversi.",
    "dungeon.breadcrumb_1": "Le pareti qui sembrano più antiche del resto del dungeon. Strani simboli sono incisi nella pietra.",
    "dungeon.breadcrumb_2": "Hai la sgradevole sensazione che qualcosa ti stia osservando. Non un mostro. Qualcos'altro.",
    "dungeon.breadcrumb_3": "Le ombre quaggiù sembrano muoversi da sole a volte. Probabilmente è solo la luce della torcia.",
    "dungeon.breadcrumb_4": "Puoi sentire qualcosa come un respiro lento e pesante dalle profondità. Probabilmente è solo il vento.",
    "dungeon.breadcrumb_5": "L'aria quaggiù sa vagamente di sale, come l'oceano. Non dovrebbe essere possibile così in profondità.",
    "dungeon.breadcrumb_6": "Cogli un suono debole, quasi un sussurro, ma non riesci a distinguere le parole.",
    "dungeon.breadcrumb_7": "La tua torcia tremola e noti qualcosa inciso nel muro. Sembra un'onda.",
    "dungeon.breadcrumb_8": "Passi accanto a una pozzanghera e il tuo riflesso sembra sbagliato in qualche modo. Quando guardi di nuovo, è normale.",
    "dungeon.danger_of": "Pericolo {0} di 3",
    "dungeon.tag_cleared": "[LIBERATO]",
    "dungeon.tag_danger": "[LIBERATO]",
    "dungeon.tag_boss": " [BOSS]",
    "dungeon.bbs_boss_presence": " >> Una presenza possente domina questa stanza! <<",
    "dungeon.bbs_hostile_creatures": " >> Creature ostili si annidano nelle ombre! <<",
    "dungeon.bbs_treasure_glints": " >> Qualcosa di prezioso luccica nell'oscurità! <<",
    "dungeon.bbs_stairs_down": " >> Le scale conducono più in basso <<",
    "dungeon.bbs_notice": " Avviso: ",
    "dungeon.bbs_exits": " Uscite:",
    "dungeon.bbs_party_count": " Gruppo({0}): ",
    "dungeon.bbs_potions": " Pozioni:",
    "dungeon.bbs_gold": " Oro:",
    "dungeon.bbs_mana": " Mana:",
    "dungeon.bbs_lv": " Lv:",
    "dungeon.guide_seal_2": "SAPERE: Il Secondo Sigillo attende qui",
    "dungeon.guide_maelketh": "BOSS: Maelketh, Dio della Guerra attende!",
    "dungeon.guide_seal_3": "SAPERE: Il Terzo Sigillo attende qui",
    "dungeon.guide_veloura": "BOSS: Veloura, Dea del Desiderio attende!",
    "dungeon.guide_seal_4": "SAPERE: Il Quarto Sigillo attende qui",
    "dungeon.guide_thorgrim": "BOSS: Thorgrim, Dio della Legge attende!",
    "dungeon.guide_seal_5": "SAPERE: Il Quinto Sigillo attende qui",
    "dungeon.guide_noctura": "BOSS: Noctura, Dea dell'Ombra attende!",
    "dungeon.guide_seal_6": "SAPERE: Il Sesto Sigillo attende qui",
    "dungeon.guide_aurelion": "BOSS: Aurelion, Dio della Luce attende!",
    "dungeon.guide_terravok": "BOSS: Terravok, Dio della Terra dorme qui!",
    "dungeon.guide_seal_final": "SAPERE: Il Sigillo Finale attende qui",
    "dungeon.guide_manwe": "FINALE: Manwe attende. Le tue scelte determinano il finale.",
    "dungeon.bbs_level": "Livello",
    "dungeon.bbs_danger": "Pericolo: ",
    "dungeon.room_boss_presence": ">> Una presenza possente domina questa stanza! <<",
    "dungeon.monster_hint_1": "Le ombre si muovono ai margini della luce della torcia...",
    "dungeon.monster_hint_2": "Senti suoni ostili dall'oscurità...",
    "dungeon.monster_hint_3": "Qualcosa ti osserva dalle ombre...",
    "dungeon.monster_hint_4": "L'aria è densa di minaccia...",
    "dungeon.room_treasure_glints": ">> Qualcosa di prezioso luccica nell'oscurità! <<",
    "dungeon.trap_detect_assassin": ">> Il tuo occhio esperto individua un meccanismo trappola! <<",
    "dungeon.trap_detect_ranger": ">> Il tuo istinto ti avverte di un pericolo nascosto! <<",
    "dungeon.trap_detect_general": ">> Percepisci un pericolo nascosto... <<",
    "dungeon.room_stairs_down": ">> Le scale conducono a un livello più profondo <<",
    "dungeon.you_notice": "Noti:",
    "dungeon.event_hint_chest": ">> Un vecchio forziere giace nell'angolo <<",
    "dungeon.event_hint_merchant": ">> Vedi una figura accanto a un piccolo fuoco da campo <<",
    "dungeon.event_hint_shrine": ">> Uno strano altare irradia energia <<",
    "dungeon.event_hint_npc": ">> C'è qualcun altro qui <<",
    "dungeon.event_hint_puzzle": ">> Strani meccanismi ricoprono una parete <<",
    "dungeon.event_hint_rest": ">> Quest'area sembra relativamente sicura <<",
    "dungeon.event_hint_mystery": ">> Qualcosa di insolito attira la tua attenzione <<",
    "dungeon.event_hint_settlement": ">> Luci e voci avanti — un insediamento! <<",
    "dungeon.event_hint_default": ">> Qualcosa di interessante è qui <<",
    "dungeon.theme_catacombs": "Antiche camere sepolcrali piene di morti inquieti",
    "dungeon.theme_sewers": "Tunnel fetidi brulicanti di parassiti e peggio",
    "dungeon.theme_caverns": "Caverne naturali scavate da fiumi sotterranei",
    "dungeon.theme_ruins": "Resti fatiscenti di una civiltà dimenticata",
    "dungeon.theme_demon": "Corridoi infernali che puzzano di zolfo",
    "dungeon.theme_frozen": "Sale ricoperte di ghiaccio dove il freddo stesso caccia",
    "dungeon.theme_volcanic": "Fiumi di lava e calore rovente attendono",
    "dungeon.theme_abyssal": "La realtà stessa si distorce in queste profondità maledette",
    "dungeon.theme_unknown": "Passaggi oscuri si snodano verso l'ignoto",
    "dungeon.flavor_catacombs": "Antiche tombe si stendono davanti a te. I morti non riposano in pace qui.",
    "dungeon.flavor_sewers": "Il fetore è opprimente. Creature si annidano nelle acque putride sotto di te.",
    "dungeon.flavor_caverns": "Caverne naturali si contorcono nell'oscurità. Vita bioluminescente proietta ombre inquietanti.",
    "dungeon.flavor_ruins": "Le rovine di una civiltà dimenticata. La magia aleggia ancora in queste pietre.",
    "dungeon.flavor_demon": "L'inferno è sconfinato in questo luogo. Urla strazianti riecheggiano senza fine.",
    "dungeon.flavor_frozen": "Freddo impossibile. Il tuo respiro gela. Cose sono conservate nel ghiaccio.",
    "dungeon.flavor_volcanic": "Fiumi di magma illuminano il cammino. Il calore è quasi insopportabile.",
    "dungeon.flavor_abyssal": "La realtà si dissolve qui. Cosa si annida oltre la sanità stessa?",
    "dungeon.flavor_default": "L'oscurità attende.",
    "dungeon.hint_seal_2": "SAPERE: Il Secondo Sigillo attende — narra della prima guerra tra gli dèi.",
    "dungeon.hint_paradox_child": "EVENTO: Il paradosso del Bambino Posseduto potrebbe apparire qui. Scegli con saggezza.",
    "dungeon.hint_maelketh": "BOSS: Maelketh, Dio della Guerra, attende nelle profondità di questo piano!",
    "dungeon.hint_seal_3": "SAPERE: Il Terzo Sigillo rivela come Manwe corruppe i propri figli.",
    "dungeon.hint_veloura": "BOSS: Veloura, Dea del Desiderio, chiama da questo piano!",
    "dungeon.hint_seal_4": "SAPERE: Il Quarto Sigillo narra delle catene eterne che imprigionano gli dèi.",
    "dungeon.hint_thorgrim": "BOSS: Thorgrim, Dio della Legge, tiene corte su questo piano!",
    "dungeon.hint_seal_5": "SAPERE: Il Quinto Sigillo contiene una profezia sul tuo arrivo.",
    "dungeon.hint_loom_discovery": "EVENTO: Il Telaio del Tessitore di Anime attende di essere scoperto in questa camera.",
    "dungeon.hint_soulweaver_price": "EVENTO: Il Prezzo del Tessitore di Anime — una scelta morale attende.",
    "dungeon.hint_noctura": "BOSS: Noctura, Dea dell'Ombra, si cela nell'oscurità di questo piano!",
    "dungeon.hint_memory": "MEMORIA: Il tuo passato dimenticato riemergerà qui. Presta attenzione ai sogni.",
    "dungeon.hint_seal_6": "SAPERE: Il Sesto Sigillo mostra il rimpianto di Manwe — le sue lacrime cristallizzate.",
    "dungeon.hint_aurelion": "BOSS: Aurelion, Dio della Luce, irradia da questo piano!",
    "dungeon.hint_destroy_darkness": "EVENTO: Il paradosso Distruggi l'Oscurità attende chi possiede la Lama Forgiata dal Sole.",
    "dungeon.hint_terravok": "BOSS: Terravok, Dio della Terra, dorme qui. Lo risveglierai?",
    "dungeon.hint_seal_final": "SAPERE: Il Sigillo Finale attende — la verità della Filosofia dell'Oceano.",
    "dungeon.hint_manwe": "FINALE: Manwe attende. Le tue scelte determineranno il finale.",
    "dungeon.hint_something_stirs": "SUGGERIMENTO: Qualcosa di potente si agita nelle profondità sottostanti...",
    "dungeon.hint_ancient_power": "SUGGERIMENTO: Un potere antico attende chi osa scendere più in basso...",
    "dungeon.breadcrumb_room": "Dungeon > Livello {0} > {1}",
    "dungeon.breadcrumb_floor": "Via Principale > Dungeon > Livello {0}",
    "dungeon.entering_dungeon": "Entri nel dungeon...",
    "dungeon.confirm_leave": "Lasciare il dungeon e tornare in città? (S/N): ",
    "dungeon.invalid_choice": "Scelta non valida.",
    "dungeon.current_chapter": "Capitolo Attuale: ",
    "dungeon.seals_header": "SIGILLI DEGLI ANTICHI DÈI ({0}/7)",
    "dungeon.seal_collected_sr": "  Raccolto: {0} - {1}",
    "dungeon.seal_hidden_town": "Nascosto nelle profondità del dungeon",
    "dungeon.seal_hidden_dungeon": "Nascosto nelle profondità del dungeon",
    "dungeon.seal_not_collected_sr": "  Non raccolto: {0} - {1}",
    "dungeon.chapter_awakening": "Il Risveglio — Uno straniero a Dorashire",
    "dungeon.chapter_first_blood": "Primo Sangue — Imparare a combattere",
    "dungeon.chapter_stranger": "Lo Straniero — Incontrare la guida misteriosa",
    "dungeon.chapter_faction": "Scelta della Fazione — Scegliere la tua alleanza",
    "dungeon.chapter_rising": "Potere Crescente — Costruire la tua forza",
    "dungeon.chapter_whispers": "I Sussurri — Gli dèi cominciano ad agitarsi",
    "dungeon.chapter_first_god": "Primo Dio — Affrontare il potere divino",
    "dungeon.chapter_god_war": "Guerra Divina — Gli Antichi Dèi si risvegliano",
    "dungeon.chapter_choice": "La Scelta — Decidere il tuo destino",
    "dungeon.chapter_ascension": "Ascensione — Gli ultimi preparativi",
    "dungeon.chapter_final": "Scontro Finale — Affrontare il Creatore",
    "dungeon.chapter_epilogue": "Epilogo — Le conseguenze",
    "dungeon.chapter_unknown": "Capitolo Sconosciuto",
    "dungeon.objective_explore": "Esplora i dungeon e diventa più forte. Qualcosa attende nelle profondità...",
    "dungeon.objective_find_seals": "Trova i Sigilli degli Antichi Dèi nascosti nel dungeon. Custodiscono la verità.",
    "dungeon.objective_more_seals": "Continua a raccogliere Sigilli. Ognuno rivela di più della storia divina.",
    "dungeon.objective_deeper": "Scendi più in profondità. I Sigilli rimanenti attendono di essere scoperti nell'abisso.",
    "dungeon.objective_face_manwe": "Tutti i Sigilli raccolti. Affronta Manwe, il Creatore. Scegli il tuo finale.",
    "dungeon.objective_ending": "La storia finisce dove è iniziata. Cerca il tuo finale.",
    "dungeon.lore_seals": "- Sette Sigilli contengono la storia degli Antichi Dèi",
    "dungeon.lore_wave": "- Una voce ti chiama 'onda' — come se fossi parte di qualcosa di più grande",
    "dungeon.lore_prophecy": "- La profezia parla di 'uno da oltre il velo' che deciderà il destino degli dèi",
    "dungeon.lore_corruption": "- Manwe corruppe i propri figli — gli Antichi Dèi — per fermare la loro guerra",
    "dungeon.lore_imprisonment": "- Gli dèi sono stati imprigionati per diecimila anni, impazzendo lentamente",
    "dungeon.lore_ocean": "- La 'Filosofia dell'Oceano': Non sei un'onda che combatte l'oceano — TU SEI l'oceano",
    "dungeon.lore_all_seals": "- TUTTI I SIGILLI RACCOLTI — Il vero finale è ora possibile!",
    "dungeon.lore_none_1": "  Non hai ancora scoperto le verità più profonde...",
    "dungeon.lore_none_2": "  Esplora i dungeon. Trova i Sigilli. Ricorda chi sei.",
    "dungeon.step_seal_town": "- Trova il {0} (nascosto da qualche parte in città)",
    "dungeon.step_seal_dungeon": "- Cerca il {0} nelle profondità del dungeon",
    "dungeon.step_grow": "- Diventa più forte per scendere più in profondità nel dungeon",
    "dungeon.step_level": "- Continua a salire di livello per accedere ai piani più profondi",
    "dungeon.step_descend": "- Scendi più in profondità. Poteri antichi attendono nell'abisso.",
    "dungeon.step_stranger": "- Cerca 'Lo Straniero' — un PNG misterioso che sa più di quanto riveli",
    "dungeon.step_all_seals": "- Raccogli tutti e 7 i Sigilli per sbloccare il vero finale",
    "dungeon.step_ready": "- Sei pronto. Affronta il Creatore nelle profondità più remote.",
    "dungeon.ocean_header": "IL SUSSURRO DELL'OCEANO (Risveglio: {0}/7)",
    "dungeon.awakening_0": "Il mondo sembra solido e separato. Conosci solo il fisico.",
    "dungeon.awakening_1": "Nei momenti di quiete, i confini sembrano sottili...",
    "dungeon.awakening_2": "Cos'è un'onda se non l'oceano in movimento?",
    "dungeon.awakening_3": "Quando l'acqua incontra l'acqua, quale perde la propria identità?",
    "dungeon.awakening_4": "Alcune anime sono più antiche dei corpi che indossano.",
    "dungeon.awakening_5": "Figlio delle acque profonde, stai iniziando a ricordare.",
    "dungeon.awakening_6": "I confini sfumano. Il sé e l'altro si fondono ai margini.",
    "dungeon.awakening_7": "L'onda ricorda di essere acqua. Bentornato, Sognatore.",
    "dungeon.awakening_unknown": "Stato sconosciuto",
    "dungeon.wave_fragments": "  Frammenti d'Onda raccolti: {0}/{1}",
    "dungeon.god_name_maelketh": "Maelketh, Dio del Caos",
    "dungeon.god_name_veloura": "Veloura, Dea dell'Amore",
    "dungeon.god_name_thorgrim": "Thorgrim, Dio della Legge",
    "dungeon.god_name_noctura": "Noctura, Dea dell'Ombra",
    "dungeon.god_name_aurelion": "Aurelion, Dio della Luce",
    "dungeon.god_name_terravok": "Terravok, Dio della Terra",
    "dungeon.god_name_manwe": "Manwe, il Creatore",
    "dungeon.god_status_imprisoned": "Imprigionato",
    "dungeon.god_status_dormant": "Dormiente",
    "dungeon.god_status_dying": "Morente",
    "dungeon.god_status_corrupted": "Corrotto",
    "dungeon.god_status_neutral": "Neutrale",
    "dungeon.god_status_awakened": "Risvegliato",
    "dungeon.god_status_hostile": "Ostile",
    "dungeon.god_status_allied": "Alleato",
    "dungeon.god_status_saved": "Salvato",
    "dungeon.god_status_defeated": "Sconfitto",
    "dungeon.god_status_consumed": "Consumato",
    "dungeon.god_status_unknown": "Sconosciuto",
    "dungeon.god_floor_status": "  Piano {0}: {1} - {2}",
    "dungeon.god_unknown_stirs": "  ???: Qualcosa si agita nelle profondità...",
    "dungeon.story_complete_sr": "  Completato: {0} - Storia Completa",
    "dungeon.story_complete": "  [✓] {0} - Storia Completa",
    "dungeon.story_failed_sr": "  Non iniziato: {0} - Storia Fallita",
    "dungeon.story_failed": "  [X] {0} - Storia Fallita",
    "dungeon.story_in_progress_sr": "  In corso: {0} - Capitolo {1}/{2}",
    "dungeon.story_in_progress": "  [~] {0} - Capitolo {1}/{2}",
    "dungeon.no_story_progress": "  Non hai ancora fatto progressi in nessuna storia della città.",
    "dungeon.explore_town_hint": "  Esplora la città e parla con i PNG memorabili per iniziare le loro storie.",
    "dungeon.no_companions": "  Nessun compagno reclutato ancora.",
    "dungeon.visit_inn_hint": "  Visita la Locanda per incontrare potenziali alleati.",
    "dungeon.active_party": "  Gruppo Attivo:",
    "dungeon.companion_hp": "    {0} - PV: {1}/{2}",
    "dungeon.at_the_inn": "  Alla Locanda:",
    "dungeon.fallen_companions": "  Caduti:",
    "dungeon.move_passage": "Avanzi attraverso il passaggio...",
    "dungeon.you_enter_room": "Entri in: {0}",
    "dungeon.you_return_room": "Ritorni a: {0}",
    "dungeon.ambush": "IMBOSCATA! I mostri attaccano!",
    "dungeon.vision_memory_stirs": "  (Qualcosa si agita nella tua memoria...)",
    "dungeon.vision_fragment_settles": "  (Un frammento di verità si insedia nella tua coscienza...)",
    "dungeon.rare_material_found": "    MATERIALE RARO TROVATO!",
    "dungeon.trap_evade_reflexes": "I tuoi riflessi pronti ti salvano!",
    "dungeon.trap_evade_agility": "Eviti agilmente la trappola! (Agilità: {0})",
    "dungeon.trap_no_react": "Non sei riuscito a reagire in tempo!",
    "dungeon.trap_pit": "Il pavimento cede! Cadi in una fossa e subisci {0} danni!",
    "dungeon.trap_darts": "Dardi avvelenati! Subisci {0} danni e sei avvelenato!",
    "dungeon.trap_fire": "Una fiammata! Subisci {0} danni da fuoco!",
    "dungeon.trap_acid": "L'acido spruzza i tuoi averi! Perdi {0} monete d'oro!",
    "dungeon.trap_curse_resist": "Una maledizione oscura ti investe, ma la tua saggezza protegge la mente! (Saggezza: {0})",
    "dungeon.trap_curse_drain": "Una maledizione ti prosciuga! Perdi {0} esperienza! (Resisti con Saggezza/Costituzione)",
    "dungeon.trap_broken": "Il meccanismo della trappola è rotto. Non succede nulla!",
    "dungeon.trap_salvage": "Recuperi {0} monete d'oro dai pezzi della trappola.",
    "dungeon.chamber_empty": "La camera è vuota. L'antica presenza è già stata affrontata.",
    "dungeon.ancient_presence_sealed": "Percepisci un'antica presenza sigillata in questa camera...",
    "dungeon.prove_yourself_hint": "Forse devi dimostrare il tuo valore altrove prima che si riveli.",
    "dungeon.straggler_appears": "Un ritardatario dai piani superiori si avventura alla vista...",
    "dungeon.monster_attacks": "Un {0} attacca!",
    "dungeon.face_monsters": "Affronti {0} {1}!",
    "dungeon.you_face_prefix": "Affronti ",
    "dungeon.and_separator": " e ",
    "dungeon.awaken_temple": "Ti risvegli al Tempio della Luce...",
    "dungeon.room_cleared": "La stanza è liberata!",
    "dungeon.boss_bonus_share": "Bonus: {0} oro, {1} PE (la tua parte: {2}o, {3} PE)",
    "dungeon.boss_bonus": "Bonus: {0} oro, {1} esperienza!",
    "dungeon.boss_phrase_catacombs": "I morti non riposano qui...",
    "dungeon.boss_phrase_sewers": "Non avresti dovuto scendere qui...",
    "dungeon.boss_phrase_caverns": "Queste profondità sono sotto il mio dominio!",
    "dungeon.boss_phrase_ruins": "Disturbi poteri al di là della tua comprensione!",
    "dungeon.boss_phrase_demon": "La tua anima alimenterà l'inferno!",
    "dungeon.boss_phrase_frozen": "Il freddo ti reclamerà, come reclama ogni cosa...",
    "dungeon.boss_phrase_volcanic": "Brucia nei fuochi degli abissi!",
    "dungeon.boss_phrase_abyssal": "Il vuoto brama la tua essenza...",
    "dungeon.boss_phrase_default": "Osi sfidarmi?",
    "dungeon.god_intro_maelketh_1": "L'aria si fa densa del profumo di antichi campi di battaglia...",
    "dungeon.god_intro_maelketh_2": "MAELKETH, LA LAMA SPEZZATA, si erge davanti a te!",
    "dungeon.god_intro_maelketh_3": "Il Dio della Guerra parla:",
    "dungeon.god_intro_maelketh_4": "\"Un altro guerriero cerca gloria nel mio dominio.\"",
    "dungeon.god_intro_veloura_1": "Il profumo di rose morenti riempie l'aria...",
    "dungeon.god_intro_veloura_2": "VELOURA, IL CUORE SFIORITO, appare davanti a te!",
    "dungeon.god_intro_veloura_3": "La Dea dell'Amore piange:",
    "dungeon.god_intro_veloura_4": "\"L'amore è la ferita più crudele di tutte... e la più profonda.\"",
    "dungeon.god_intro_veloura_5": "\"Guarirai ciò che è spezzato, o lo frantumerai ulteriormente?\"",
    "dungeon.god_intro_thorgrim_1": "Il peso del giudizio grava sulla tua anima...",
    "dungeon.god_intro_thorgrim_2": "THORGRIM, IL GIUDICE INGIUSTO, discende!",
    "dungeon.god_intro_thorgrim_3": "Il Dio della Legge pronuncia:",
    "dungeon.god_intro_thorgrim_4": "\"Ti trovi davanti al tribunale dell'eternità. Come ti dichiari?\"",
    "dungeon.god_intro_thorgrim_5": "\"Ogni anima deve rispondere di ciò che ha fatto.\"",
    "dungeon.god_intro_noctura_1": "Le ombre si coalizzano, formando sagome che osservano...",
    "dungeon.god_intro_noctura_2": "NOCTURA, LA REGINA DELLE OMBRE, emerge dall'oscurità!",
    "dungeon.god_intro_noctura_3": "La Dea delle Ombre sussurra:",
    "dungeon.god_intro_noctura_4": "\"L'oscurità ricorda ogni segreto che hai sepolto.\"",
    "dungeon.god_intro_noctura_5": "\"Vieni... lascia che ti mostri cosa si nasconde nella tua stessa ombra.\"",
    "dungeon.god_intro_aurelion_1": "Una luce fioca tremola nell'oscurità, lottando per persistere...",
    "dungeon.god_intro_aurelion_2": "AURELION, LA LUCE MORENTE, si manifesta debolmente!",
    "dungeon.god_intro_aurelion_3": "Il Dio della Luce parla fiocamente:",
    "dungeon.god_intro_aurelion_4": "\"La mia luce svanisce... ma anche una stella morente può bruciare.\"",
    "dungeon.god_intro_aurelion_5": "\"Porterai questa fiamma, o la lascerai spegnersi per sempre?\"",
    "dungeon.god_intro_terravok_1": "La montagna stessa sembra respirare. La pietra si muove come carne...",
    "dungeon.god_intro_terravok_2": "TERRAVOK, IL DISTRUTTORE DI MONDI, si risveglia!",
    "dungeon.god_intro_terravok_3": "Il Dio della Terra tuona:",
    "dungeon.god_intro_terravok_4": "\"Le montagne non si inchinano. E neppure io.\"",
    "dungeon.god_intro_manwe_1": "La realtà stessa trema. Il sogno sa di essere osservato...",
    "dungeon.god_intro_manwe_2": "MANWE, IL CREATORE DI TUTTO, si manifesta!",
    "dungeon.god_intro_manwe_3": "Il Creatore parla con una voce che è tutte le voci:",
    "dungeon.god_title_maelketh": "Maelketh, la Lama Spezzata",
    "dungeon.god_title_veloura": "Veloura, il Cuore Sfiorito",
    "dungeon.god_title_thorgrim": "Thorgrim, il Giudice Ingiusto",
    "dungeon.god_title_noctura": "Noctura, la Regina delle Ombre",
    "dungeon.god_title_aurelion": "Aurelion, la Luce Morente",
    "dungeon.god_title_terravok": "Terravok, il Distruttore di Mondi",
    "dungeon.god_title_manwe": "Manwe, il Creatore",
    "dungeon.god_title_default": "l'Antico Dio",
    "dungeon.face_god_prompt": "Desideri affrontare {0}? (S/N)",
    "dungeon.god_retreat_maelketh": "Percepisci il dio ritirarsi nel sonno... per ora.",
    "dungeon.god_retreat_terravok": "La montagna si placa. Terravok continua a dormire.",
    "dungeon.god_retreat_manwe": "La presenza del Creatore svanisce, ma senti ancora il suo sguardo su di te...",
    "dungeon.god_retreat_default": "Il dio si ritira... per ora.",
    "dungeon.boss_room_unconquered": "La stanza del boss resta inespugnata.",
    "dungeon.treasure_found_sr": "  TESORO TROVATO!",
    "dungeon.treasure_party_finds": "Il gruppo trova {0} oro e {1} PE!",
    "dungeon.treasure_your_share": "La tua parte: {0} oro, {1} PE",
    "dungeon.treasure_gold_found": "Trovi {0} monete d'oro!",
    "dungeon.treasure_exp_found": "Guadagni {0} esperienza!",
    "dungeon.treasure_potions": "Trovi anche {0} pozioni curative!",
    "dungeon.event_desc_treasure": "scopre un forziere del tesoro",
    "dungeon.event_desc_merchant": "incontra un mercante errante",
    "dungeon.event_desc_shrine": "trova un santuario misterioso",
    "dungeon.event_desc_npc": "incontra qualcuno nell'oscurità",
    "dungeon.event_desc_puzzle": "scopre un meccanismo enigmatico",
    "dungeon.event_desc_rest": "trova un accampamento sicuro",
    "dungeon.event_desc_mystery": "percepisce qualcosa di insolito",
    "dungeon.event_desc_riddle": "incontra un cancello enigmatico",
    "dungeon.event_desc_lore": "scopre antichi scritti",
    "dungeon.event_desc_memory": "ha una strana visione",
    "dungeon.event_desc_secret_boss": "disturba qualcosa di potente",
    "dungeon.event_desc_default": "scopre qualcosa di interessante",
    "dungeon.examine_what": "Cosa vuoi esaminare?",
    "dungeon.floor_recleared": "Hai ri-liberato questo piano.",
    "dungeon.first_clear_only": "(Il bonus di completamento si ottiene solo alla prima liberazione)",
    "dungeon.proven_sacred_floor": "Hai dimostrato il tuo valore su questo piano sacro!",
    "dungeon.vanquished_all_foes": "Hai annientato tutti i nemici su questo livello!",
    "dungeon.bonus_xp_share": "  PE Bonus: +{0} (la tua parte: {1})",
    "dungeon.bonus_gold_share": "  Oro Bonus: +{0} (la tua parte: {1})",
    "dungeon.bonus_xp": "  PE Bonus: +{0}",
    "dungeon.bonus_gold": "  Oro Bonus: +{0}",
    "dungeon.presence_blocks_descent": "Una presenza possente blocca la tua discesa.",
    "dungeon.defeat_old_god_first": "Devi sconfiggere l'Antico Dio su questo piano prima di scendere più in profondità.",
    "dungeon.may_ascend": "Puoi ancora risalire per prepararti.",
    "dungeon.cannot_venture_deeper": "Non puoi avventurarti oltre il livello {0} con la tua forza attuale.",
    "dungeon.level_up_hint": "Sali di livello per accedere ai piani più profondi.",
    "dungeon.nowhere_descend": "Non c'è più nessun luogo dove scendere.",
    "dungeon.darkness_deeper": "L'oscurità si fa più profonda.",
    "dungeon.air_colder": "L'aria si fa più fredda.",
    "dungeon.arrive_at_level": "Arrivi al Livello {0}",
    "dungeon.theme_display": "Tema: {0}",
    "dungeon.continuing_where_left_off": "[Continui da dove avevi interrotto...]",
    "dungeon.new_creatures_emerged": "[Nuove creature sono emerse dalle profondità...]",
    "dungeon.recover_hp": "Recuperi {0} punti vita.",
    "dungeon.recover_mana": "Recuperi {0} mana.",
    "dungeon.recover_stamina": "Recuperi {0} stamina.",
    "dungeon.troubled_rest": "Il tuo riposo è turbato da oscuri ricordi...",
    "dungeon.fatigue_reduced": "Ti senti un po' riposato. (Fatica -{0})",
    "dungeon.dream_takes_shape": "Mentre sonnecchi, un sogno prende forma...",
    "dungeon.break_camp": "Levi il campo, sentendoti riposato ma guardingo.",
    "dungeon.current_level": "Livello attuale: {0}",
    "dungeon.your_level": "Il tuo livello: {0}",
    "dungeon.deepest_accessible": "Più profondo accessibile: {0} (il tuo livello + 10)",
    "dungeon.enter_target_level": "Inserisci il livello desiderato (o +/- per relativo): ",
    "dungeon.presence_blocks": "Una presenza possente blocca la tua discesa.",
    "dungeon.must_defeat_god_floor": "Devi sconfiggere {0} al piano {1} prima di scendere oltre.",
    "dungeon.may_still_ascend": "Puoi ancora risalire per prepararti.",
    "dungeon.must_defeat_old_god_this_floor": "Devi sconfiggere l'Antico Dio su questo piano prima di scendere oltre.",
    "dungeon.level_set_to": "Livello del dungeon impostato a {0}.",
    "dungeon.no_level_change": "Nessun cambiamento al livello del dungeon.",
    "dungeon.monster_encounter_sr": "-- INCONTRO CON MOSTRO --",
    "dungeon.monster_encounter_visual": "-- INCONTRO CON MOSTRO --",
    "dungeon.boss_blocks_path_sr": "ATTENZIONE: Un potente [{0}]{1}[/] blocca il tuo cammino!",
    "dungeon.boss_blocks_path_visual": "⚠ Un potente [{0}]{1}[/] blocca il tuo cammino! ⚠",
    "dungeon.monster_appears": "Un [{0}]{1}[/] appare!",
    "dungeon.encounter_group_family": " dalla famiglia dei {0}!",
    "dungeon.you_encounter": "Incontri ",
    "dungeon.difficulty_trivial": "Banale",
    "dungeon.xp_hint_not_worth": "~{0} PE (non vale il tuo tempo)",
    "dungeon.difficulty_easy": "Facile",
    "dungeon.difficulty_fair": "Equo",
    "dungeon.difficulty_challenging": "Impegnativo",
    "dungeon.xp_hint_bring_potions": "~{0} PE (porta pozioni)",
    "dungeon.difficulty_dangerous": "Pericoloso",
    "dungeon.xp_hint_high_risk": "~{0} PE (alto rischio)",
    "dungeon.difficulty_deadly": "LETALE",
    "dungeon.xp_hint_flee": "~{0} PE (fuga consigliata!)",
    "dungeon.threat_label": "  Minaccia: ",
    "dungeon.scroll_found": "Hai trovato una pergamena! Dice:",
    "dungeon.scroll_blessing_words": "Pronuncia: 'XAVARANTHE JHUSULMAX VASWIUN'",
    "dungeon.scroll_blessing_hint": "E riceverai una benedizione.",
    "dungeon.scroll_undead_words": "Pronuncia: 'ZASHNIVANTHE ULIPMAN NO SEE'",
    "dungeon.scroll_undead_hint": "E vedrai risorgere un antico potere.",
    "dungeon.scroll_secret_words": "Pronuncia: 'RANTVANTHI SHGELUUIM VARTHMIOPLXH'",
    "dungeon.scroll_secret_hint": "E ti saranno date opportunità.",
    "dungeon.recite_scroll_prompt": "Recitare la pergamena? (S/N): ",
    "dungeon.scroll_stored": "Riponi con cura la pergamena per dopo.",
    "dungeon.scroll_words_resonate": "Le parole antiche risuonano di potere...",
    "dungeon.scroll_divine_light": "La luce divina ti avvolge!",
    "dungeon.scroll_chivalry_gain": "La tua cavalleria aumenta di {0}!",
    "dungeon.scroll_ground_trembles": "Il terreno trema mentre un antico male si risveglia!",
    "dungeon.scroll_summoned_undead": "Hai evocato un {0}!",
    "dungeon.scroll_hidden_passage": "Un passaggio segreto si apre davanti a te!",
    "dungeon.scroll_secret_gold": "Scopri {0} monete d'oro nella camera segreta!",
    "dungeon.fallen_adventurer_header": "=== AVVENTURIERO CADUTO ===",
    "dungeon.fallen_adventurer_remains": "Ti imbatti nei resti di un {0} caduto.",
    "dungeon.fallen_adventurer_journal": "Il suo diario consunto giace aperto accanto a lui.",
    "dungeon.fallen_adventurer_choice": "(P)erquisire i suoi averi o (R)ispettare i morti? ",
    "dungeon.find_gold_coins": "Trovi {0} monete d'oro.",
    "dungeon.find_healing_potions": "Trovi {0} pozioni curative.",
    "dungeon.notes_teach_something": "Leggere i suoi appunti ti insegna qualcosa! (+{0} PE)",
    "dungeon.corpse_animates": "Il cadavere si anima! Guardiano non-morto!",
    "dungeon.pray_for_fallen": "Reciti una preghiera silenziosa per l'avventuriero caduto.",
    "dungeon.chivalry_increases_slightly": "La tua cavalleria aumenta leggermente.",
    "dungeon.echoing_voices_header": "=== VOCI ECHEGGIANTI ===",
    "dungeon.whispers_echo": "Strani sussurri echeggiano nei corridoi...",
    "dungeon.encounter_wiser": "L'incontro ti rende più saggio. (+{0} PE)",
    "dungeon.portal_header": "=== PORTALE MISTERIOSO ===",
    "dungeon.portal_description_1": "Un portale scintillante fluttua davanti a te, crepitante di energia.",
    "dungeon.portal_description_2": "Pulsa di una luce ultraterrena.",
    "dungeon.portal_choice": "(E)ntrare nel portale, (S)tudiarlo, o (I)gnorarlo? ",
    "dungeon.portal_whisks_deeper": "Il portale ti trasporta più in profondità nel dungeon!",
    "dungeon.portal_emerge_floor": "Emergi al piano {0}!",
    "dungeon.portal_carries_upward": "Il portale ti trasporta verso l'alto!",
    "dungeon.portal_treasure_dimension": "Ti ritrovi in una dimensione del tesoro!",
    "dungeon.portal_grab_gold": "Afferri {0} monete d'oro prima di essere risucchiato indietro!",
    "dungeon.portal_hostile_dimension": "Il portale conduce a una dimensione ostile!",
    "dungeon.portal_guardian_crystal": "Il guardiano lascia cadere un cristallo raro!",
    "dungeon.portal_study": "Studi i motivi magici del portale...",
    "dungeon.portal_learn_magic": "Impari qualcosa sulla magia dimensionale. (+{0} PE)",
    "dungeon.portal_avoid": "Eviti saggiamente il portale instabile. Si dissolve.",
    "dungeon.duelist_header": "=== IL DUELLANTE ===",
    "dungeon.duelist_emerges": "Un guerriero emerge dalle ombre: {0}",
    "dungeon.duelist_first_1": "\"Ben incontrato, {0}! Sono un duellante errante.\"",
    "dungeon.duelist_first_2": "\"Mi chiamano {0}. Cerco avversari degni in queste profondità.\"",
    "dungeon.duelist_first_3": "\"Mettiamo alla prova le nostre lame?\"",
    "dungeon.duelist_record": "  Incontri: {0} | Tue Vittorie: {1} | Tue Sconfitte: {2}",
    "dungeon.duelist_strength": "  Forza attuale di {0}: Livello {1}",
    "dungeon.duelist_choice": "(A)ccettare la sfida, (D)eclinare cortesemente, o (I)nsultarlo? ",
    "dungeon.duelist_accept": "Accetti la sfida di {0}!",
    "dungeon.duelist_steel_clashes": "L'acciaio si scontra contro l'acciaio!",
    "dungeon.duelist_win1_1": "{0} si inginocchia davanti a te, offrendo la spada in saluto.",
    "dungeon.duelist_win1_2": "\"Una vittoria degna! Me la ricorderò.\"",
    "dungeon.duelist_win3_1": "{0} ride nonostante la sconfitta!",
    "dungeon.duelist_win3_2": "\"Tre volte, {0}! Hai il mio rispetto.\"",
    "dungeon.duelist_win3_3": "\"Mi allenerò più duramente per il nostro prossimo incontro.\"",
    "dungeon.duelist_win5_1": "{0} si inchina profondamente, un gesto di massimo rispetto.",
    "dungeon.duelist_win5_2": "\"Mi hai superato. È un onore essere il tuo rivale.\"",
    "dungeon.duelist_win_default_1": "{0} accetta la sconfitta con grazia.",
    "dungeon.duelist_win_default_2": "\"Ben combattuto. Alla prossima.\"",
    "dungeon.duelist_rewards": "+{0} oro, +{1} PE, +5 Cavalleria",
    "dungeon.duelist_loss1_1": "{0} ti risparmia la vita!",
    "dungeon.duelist_loss1_2": "\"Ben combattuto... tornerò più forte.\"",
    "dungeon.duelist_loss3_1": "{0} sospira con disappunto.",
    "dungeon.duelist_loss3_2": "\"Tre sconfitte... ma imparo da ognuna.\"",
    "dungeon.duelist_loss_default_1": "{0} rinfodera la spada.",
    "dungeon.duelist_loss_default_2": "\"Non è finita tra noi.\"",
    "dungeon.duelist_decline": "Declini cortesemente la sfida.",
    "dungeon.duelist_decline_known_1": "{0} sembra deluso ma comprensivo.",
    "dungeon.duelist_decline_known_2": "\"Forse la prossima volta, amico.\"",
    "dungeon.duelist_decline_new_1": "{0} annuisce con rispetto.",
    "dungeon.duelist_decline_new_2": "\"Forse ci incontreremo di nuovo.\"",
    "dungeon.duelist_insult": "Scagli insulti contro il duellante!",
    "dungeon.duelist_insult_known_1": "Gli occhi di {0} fiammeggiano di furia!",
    "dungeon.duelist_insult_known_2": "\"Come OSI?! Dopo tutti i nostri duelli?!\"",
    "dungeon.duelist_insult_known_3": "\"Ti insegnerò un po' di buone maniere!\"",
    "dungeon.duelist_insult_new_1": "Il volto di {0} si contorce di rabbia!",
    "dungeon.duelist_insult_new_2": "\"Ti pentirai di quelle parole!\"",
    "dungeon.duelist_slain": "Hai ucciso {0} in un combattimento disonorevole.",
    "dungeon.duelist_spirit_haunts": "Il suo spirito ti perseguiterà...",
    "dungeon.duelist_walk_away": "{0} ti guarda allontanarti.",
    "dungeon.treasure_chest_header": "* FORZIERE DEL TESORO *",
    "dungeon.treasure_chest_discover": "Scopri un antico forziere nascosto nelle ombre!",
    "dungeon.treasure_chest_choice": "(A)prire il forziere o (L)asciarlo stare? ",
    "dungeon.chest_opens_treasure": "Il forziere si apre rivelando un tesoro scintillante!",
    "dungeon.chest_party_finds": "Il gruppo trova {0} oro e {1} PE!",
    "dungeon.chest_your_share": "La tua parte: {0} oro, {1} PE",
    "dungeon.chest_find_gold": "Trovi {0} monete d'oro!",
    "dungeon.chest_gain_exp": "Guadagni {0} esperienza!",
    "dungeon.chest_discover_material": "Tra il tesoro, scopri un {0}!",
    "dungeon.chest_trap": "CLIC! È una trappola!",
    "dungeon.chest_leap_back": "Balzi indietro appena in tempo!",
    "dungeon.chest_reflexes_saved": "I tuoi riflessi ti hanno salvato! (Agilità: {0})",
    "dungeon.chest_no_react": "Non sei riuscito a reagire in tempo!",
    "dungeon.chest_poison_gas": "Gas velenoso! Subisci {0} danni!",
    "dungeon.chest_poisoned": "Sei stato avvelenato!",
    "dungeon.chest_spikes": "Spuntoni scattano fuori! Subisci {0} danni!",
    "dungeon.chest_acid": "L'acido spruzza la tua borsa delle monete! Perdi {0} oro!",
    "dungeon.chest_mimic": "Il forziere si MUOVE! È un MIMIC!",
    "dungeon.chest_leave_alone": "Saggiamente lasci il forziere e prosegui.",
    "dungeon.strangers_header": "=== STRANIERI SI AVVICINANO ===",
    "dungeon.strangers_orcs": "orchi",
    "dungeon.strangers_orcs_desc": "Un gruppo di orchi emerge dalle ombre!",
    "dungeon.strangers_orcs_arms": "Sono scarsamente armati con bastoni e clave.",
    "dungeon.strangers_trolls": "troll",
    "dungeon.strangers_trolls_desc": "Una banda di troll blocca il tuo cammino!",
    "dungeon.strangers_trolls_arms": "Portano clave e lance.",
    "dungeon.strangers_rogues": "furfanti",
    "dungeon.strangers_rogues_desc": "Una banda di furfanti ti circonda!",
    "dungeon.strangers_rogues_arms": "Brandiscono coltelli e stocchi.",
    "dungeon.strangers_dwarves": "nani",
    "dungeon.strangers_dwarves_desc": "Un gruppo di nani armati si avvicina!",
    "dungeon.strangers_dwarves_arms": "Portano spade e asce.",
    "dungeon.strangers_demand_gold": "Il loro capo pretende il tuo oro!",
    "dungeon.strangers_choice": "(C)ombattere, (P)agare il riscatto, o tentare la (F)uga? ",
    "dungeon.strangers_draw_weapon": "Sguaini la tua arma e ti prepari alla battaglia!",
    "dungeon.strangers_pay_bribe": "A malincuore consegni {0} monete d'oro.",
    "dungeon.strangers_leave_peace": "I {0} ti lasciano in pace.",
    "dungeon.strangers_attack_anyway": "Attaccano comunque!",
    "dungeon.strangers_escape_success": "Riesci a sgattaiolare via nelle ombre!",
    "dungeon.strangers_escape_fail": "Ti sorprendono mentre tenti la fuga!",
    "dungeon.strangers_steal_gold": "Ti picchiano e rubano {0} monete d'oro!",
    "dungeon.damsel_header_sr": "-- DAMIGELLA IN PERICOLO --",
    "dungeon.damsel_header_visual": "-- DAMIGELLA IN PERICOLO --",
    "dungeon.damsel_screams": "Senti urla echeggiare nel corridoio!",
    "dungeon.damsel_harassed": "Una donna è molestata da una banda di teppisti.",
    "dungeon.damsel_choice": "(A)iutarla, (I)gnorare la situazione, o (U)nirti ai teppisti? ",
    "dungeon.damsel_rush_defense": "Corri in sua difesa!",
    "dungeon.damsel_unhand_her": "Corri in sua difesa!",
    "dungeon.damsel_thanks": "La donna ti ringrazia profusamente!",
    "dungeon.damsel_reward": "Ti ricompensa con {0} monete d'oro!",
    "dungeon.chivalry_increase": "La tua cavalleria aumenta di {0}!",
    "dungeon.damsel_join_ruffians": "Ti unisci ai teppisti nella loro viltà!",
    "dungeon.damsel_shameful": "Questo è un atto vergognoso!",
    "dungeon.damsel_steal": "Rubi {0} monete d'oro alla donna.",
    "dungeon.darkness_increase": "La tua oscurità aumenta di {0}!",
    "dungeon.damsel_ignore_1": "Ti volti e fingi di non notare nulla.",
    "dungeon.damsel_ignore_2": "Le sue grida svaniscono mentre prosegui il viaggio...",
    "dungeon.wounded_header_sr": "-- STRANIERO FERITO --",
    "dungeon.wounded_header_visual": "-- STRANIERO FERITO --",
    "dungeon.wounded_find": "Trovi un uomo ferito appoggiato al muro.",
    "dungeon.wounded_bleeding": "Sta sanguinando copiosamente e implora aiuto.",
    "dungeon.wounded_begs": "Trovi un uomo ferito appoggiato al muro.",
    "dungeon.wounded_choice": "(A)iutarlo, (D)erubarlo, o (L)asciarlo? ",
    "dungeon.wounded_heal_potion": "Usi una pozione curativa sullo straniero ferito.",
    "dungeon.wounded_recovers": "Si riprende abbastanza da alzarsi in piedi.",
    "dungeon.wounded_reward": "La tua cavalleria aumenta di {0}!",
    "dungeon.wounded_bandage": "Cerchi di fasciare le sue ferite con della stoffa...",
    "dungeon.wounded_helps": "Sembra aiutare un poco.",
    "dungeon.wounded_dies": "Sfortunatamente, muore per le sue ferite.",
    "dungeon.wounded_rob": "Frughi tra gli averi dell'uomo morente...",
    "dungeon.wounded_rob_gold": "Trovi {0} monete d'oro nella sua borsa.",
    "dungeon.wounded_dies_cursing": "Muore maledicendo il tuo nome...",
    "dungeon.wounded_leave_1": "Scavalchi l'uomo morente e prosegui.",
    "dungeon.wounded_leave_2": "I suoi gemiti svaniscono alle tue spalle...",
    "dungeon.shrine_header_sr": "-- SANTUARIO MISTERIOSO --",
    "dungeon.shrine_header_visual": "-- SANTUARIO MISTERIOSO --",
    "dungeon.shrine_discover": "Scopri un antico santuario che emana una strana luce.",
    "dungeon.shrine_offerings": "Offerte d'oro e ossa circondano un altare di pietra.",
    "dungeon.shrine_choice": "(P)regare al santuario, (D)issacrarlo, o (L)asciare? ",
    "dungeon.shrine_kneel": "Ti inginocchi davanti all'antico santuario...",
    "dungeon.shrine_divine_light": "La luce divina ti pervade!",
    "dungeon.shrine_fully_healed": "Sei completamente guarito!",
    "dungeon.shrine_stronger": "Ti senti più forte! +{0} Forza!",
    "dungeon.shrine_wisdom": "Antica saggezza fluisce in te! +{0} PE!",
    "dungeon.shrine_silent": "Il santuario è silenzioso...",
    "dungeon.shrine_nothing": "Non succede nulla.",
    "dungeon.shrine_drains": "Il santuario prosciuga la tua forza vitale!",
    "dungeon.shrine_lose_hp": "Perdi {0} PV!",
    "dungeon.shrine_gold_dissolves": "Il tuo oro si dissolve nell'altare!",
    "dungeon.shrine_lose_gold": "Perdi {0} monete d'oro!",
    "dungeon.shrine_desecrate": "Distruggi il santuario e rubi le offerte!",
    "dungeon.shrine_desecrate_gold": "Trovi {0} monete d'oro tra le offerte!",
    "dungeon.shrine_angry_spirit": "Uno spirito adirato emerge dal santuario distrutto!",
    "dungeon.shrine_leave": "Saggiamente lasci in pace il misterioso santuario.",
    "dungeon.trap_header_sr": "ATTENZIONE: TRAPPOLA!",
    "dungeon.trap_header_visual": "ATTENZIONE: TRAPPOLA!",
    "dungeon.trap_reflexes_save": "I tuoi riflessi pronti ti salvano!",
    "dungeon.trap_dodge_entirely": "Eviti completamente la trappola! (Agilità: {0})",
    "dungeon.trap_floor_gives_way": "Il pavimento cede sotto di te!",
    "dungeon.trap_fall_damage": "Cadi in una fossa e subisci {0} danni!",
    "dungeon.trap_poison_darts": "Dardi avvelenati scattano dalle pareti!",
    "dungeon.trap_dart_damage_poisoned": "Subisci {0} danni e sei avvelenato!",
    "dungeon.trap_rune_explodes": "Una runa magica esplode sotto i tuoi piedi!",
    "dungeon.trap_magic_damage": "Subisci {0} danni magici!",
    "dungeon.trap_net_falls": "Una rete cade dall'alto, intrappolandoti!",
    "dungeon.trap_struggle_free": "Ti liberi a fatica, ma perdi tempo...",
    "dungeon.trap_tripwire": "Fai scattare un filo teso!",
    "dungeon.trap_broken_nothing": "Ma non succede nulla... la trappola è rotta.",
    "dungeon.trap_find_gold": "Trovi dell'oro nascosto vicino al meccanismo.",
    "dungeon.ancient_scroll_header": "📜 PERGAMENA ANTICA 📜",
    "dungeon.ancient_scroll_discover": "Scopri una pergamena antica infilata in una fessura del muro.",
    "dungeon.ancient_scroll_symbols": "Strani simboli brillano debolmente sulla pergamena.",
    "dungeon.ghost_header": "=== FANTASMA GIOCATORE D'AZZARDO ===",
    "dungeon.ghost_appears": "Una figura spettrale si materializza davanti a te!",
    "dungeon.ghost_greeting": "Una figura spettrale si materializza davanti a te!",
    "dungeon.ghost_dice": "Il fantasma produce un paio di dadi eterei.",
    "dungeon.ghost_no_gold": "Il fantasma svanisce con disappunto.",
    "dungeon.ghost_fades_disappointed": "Il fantasma svanisce con disappunto.",
    "dungeon.ghost_place_bet": "La tua puntata (o 0 per rifiutare): ",
    "dungeon.ghost_bet_prompt": "La tua puntata (o 0 per rifiutare): ",
    "dungeon.ghost_coward": "Il fantasma svanisce.",
    "dungeon.ghost_fades": "Il fantasma svanisce.",
    "dungeon.ghost_you_bet": "Scommetti {0} monete d'oro!",
    "dungeon.ghost_rolls": "Il fantasma lancia i dadi...",
    "dungeon.ghost_roll_result": "Il fantasma ottiene: {0}",
    "dungeon.ghost_your_turn": "Il tuo turno di lanciare...",
    "dungeon.ghost_player_roll": "Ottieni: {0}",
    "dungeon.ghost_you_win": "HAI VINTO!",
    "dungeon.ghost_pays": "Il fantasma ti paga a malincuore {0} monete d'oro!",
    "dungeon.ghost_you_lose": "HAI PERSO!",
    "dungeon.ghost_cackles": "Il fantasma ghigna mentre il tuo oro svanisce!",
    "dungeon.ghost_tie": "PAREGGIO!",
    "dungeon.ghost_tie_msg": "PAREGGIO!",
    "dungeon.ghost_fades_shadows": "Il fantasma svanisce nelle ombre...",
    "dungeon.status_boss_uncleared": "Stanza del boss, non liberata",
    "dungeon.status_boss_cleared": "Stanza del boss, liberata",
    "dungeon.status_monsters": "Mostri presenti",
    "dungeon.status_stairs_cleared": "Scale verso il basso, liberata",
    "dungeon.status_stairs": "Scale verso il basso, liberata",
    "dungeon.status_safe": "Stanza sicura",
    "dungeon.status_cleared": "Liberata",
    "dungeon.status_explored": "Esplorata",
    "dungeon.duelist_even_3": "\"È ora di rompere il pareggio!\"",
    "dungeon.duelist_even_1": "\"Ah, {0}! Sempre alla pari come sempre!\"",
    "dungeon.react_thorgrim_sav_2": "\"La legge di Thorgrim è ristabilita. I tribunali ricorderanno questo giorno.\"",
    "dungeon.react_aurelion_def_def_2": "\"Il dio della luce... scomparso. Chi ci guiderà attraverso l'oscurità?\"",
    "dungeon.react_veloura_def_agg_2": "\"Hanno ucciso la dea dell'amore. Cosa ne sarà di noi adesso?\"",
    "dungeon.duelist_losing_1": "\"Beh, beh... {0} torna per un'altra lezione!\"",
    "dungeon.duelist_winning_3": "\"Ma oggi sono più forte! En garde!\"",
    "dungeon.react_maelketh_def_hum_2": "\"Dicono che ti sei inchinato davanti al dio della guerra... e hai vinto comunque.\"",
    "dungeon.duelist_winning_1": "\"Ah, {0}! Il mio rivale è tornato! Mi hai battuto prima...\"",
    "dungeon.story_whispers_3": "Perché scendi, onda?",
    "dungeon.react_thorgrim_def_hon_2": "\"La giustizia è stata servita oggi, da chi la comprende.\"",
    "dungeon.duelist_losing_3": "\"Forse oggi la tua fortuna cambia!\"",
    "dungeon.god_intro_manwe_4": "Sei giunto infine, mio figlio smarrito.",
    "dungeon.duelist_losing_2": "\"Ti ho sconfitto {0} volte ormai. Vuoi riprovare?\"",
    "dungeon.god_intro_manwe_5": "Il Creatore parla:",
    "dungeon.story_whispers_4": "Cosa cerchi nel profondo?",
    "dungeon.react_terravok_def_resp_2": "\"Cosa è costato spezzare l'infrangibile... solo la montagna lo sa.\"",
    "dungeon.react_thorgrim_def_defy_3": "\"Se possono sfidare il dio della legge... cosa impedirà loro di sfidare la nostra?\"",
    "dungeon.react_maelketh_def_agg_2": "\"Ha ucciso un dio della guerra con pura furia. Cosa li rende?\"",
    "dungeon.story_oracle_7": "Il Sigillo del Destino rivela ciò che non potevo dire.",
    "dungeon.duelist_winning_2": "\"Il punteggio è {0} a {1} a tuo favore.\"",
    "dungeon.encounter_group": "{0}",
    "dungeon.react_maelketh_sav_2": "\"Maelketh ricorda l'onore. Le guerre infinite possono finalmente terminare.\"",
    "dungeon.duelist_even_2": "\"Siamo pari con {0} vittorie ciascuno.\"",
    "dungeon.duelist_coward": "Il duellante si volta e fugge!",
    "dungeon.react_maelketh_other_2": "\"Hanno affrontato il dio della guerra e se ne sono andati. Alle loro condizioni.\"",
    "dungeon.god_intro_manwe_6": "IO SONO l'inizio. E forse... la fine.",
    "dungeon.react_thorgrim_other_2": "\"Trattative eque con il dio della legge. Ci vuole fegato.\"",
}
