translations = {
    "encounter.reward_chivalry": "+{0} Cavalleria!",
    "encounter.reward_darkness": "+{0} Oscurità!",
    "encounter.reward_gold_exp": "+{0} oro, +{1} esperienza!",
    "encounter.tavern.title": "La Taverna Nascosta",
    "encounter.tavern.subtitle": "Un'Oasi nel Sotterraneo",
    "encounter.tavern.desc_1": "Spingi da parte un muro fatiscente e scopri una taverna nascosta,",
    "encounter.tavern.desc_2": "illuminata da candele tremolanti e impregnata di odore di birra e tabacco da pipa.",
    "encounter.tavern.desc_3": "Un burbero oste lucida un bicchiere dietro il bancone.",
    "encounter.tavern.bartender_greet": "L'oste alza lo sguardo quando entri.",
    "encounter.tavern.bartender_ask": "\"Che cosa sarà, avventuriero?\"",
    "encounter.tavern.option_drink": "Compra da Bere (50o) - Cura il 33% dei PV",
    "encounter.tavern.option_gamble": "Gioca a Carte",
    "encounter.tavern.option_talk": "Parla con uno Sconosciuto",
    "encounter.tavern.option_rest": "Riposa nella Stanza sul Retro (200o) - Cura completa + rimuovi veleno",
    "encounter.tavern.ale_heal": "La birra ti scalda lo stomaco e lenisce le ferite. (+{0} PV)",
    "encounter.tavern.no_coin": "\"Niente monete, niente birra. Così funziona quaggiù.\"",
    "encounter.tavern.rest_sleep": "Ti lasci cadere su un materasso di paglia nella stanza sul retro...",
    "encounter.tavern.rest_refreshed": "Ti svegli riposato, le ferite guarite e il veleno eliminato.",
    "encounter.tavern.rest_no_gold": "\"La stanza sul retro non è gratis, avventuriero.\"",
    "encounter.tavern.leave_msg": "Sgattaioli di nuovo nel sotterraneo, il calore della taverna svanisce alle tue spalle.",
    "encounter.tavern.shortcut_menu": "[B]ere [G]iocare [P]arlare [R]iposare [U]scire",
    "encounter.tavern.gamble_intro_1": "Un uomo sfregiato nell'angolo ti fa cenno al suo tavolo.",
    "encounter.tavern.gamble_intro_2": "\"Gioco semplice. Carta più alta vince. Ci stai?\"",
    "encounter.tavern.gamble_bet_prompt": "Scommetti {0} oro? (S/N): ",
    "encounter.tavern.gamble_you_draw": "Tu peschi: {0}",
    "encounter.tavern.gamble_dealer_draw": "Il mazziere pesca: {0}",
    "encounter.tavern.gamble_win": "Vinci {0} oro!",
    "encounter.tavern.gamble_lose": "Perdi! Il mazziere spazza via l'oro.",
    "encounter.tavern.gamble_tie": "Pareggio! La tua scommessa viene restituita.",
    "encounter.tavern.gamble_nothing": "Non hai nulla che valga la pena scommettere.",
    "encounter.tavern.card_ace": "Asso",
    "encounter.tavern.card_jack": "Fante",
    "encounter.tavern.card_queen": "Regina",
    "encounter.tavern.card_king": "Re",
    "encounter.tavern.stranger_intro_1": "Una figura incappucciata al bancone ti fa cenno di avvicinarti.",
    "encounter.tavern.stranger_intro_2": "\"Psst... ho qualcosa per te.\"",
    "encounter.tavern.stranger_potion_1": "\"Le ho trovate addosso a un avventuriero morto. A lui non servono più.\"",
    "encounter.tavern.stranger_potion_2": "Lo sconosciuto ti fa scivolare tre pozioni curative sul tavolo.",
    "encounter.tavern.stranger_potion_reward": "Ricevute 3 pozioni curative!",
    "encounter.tavern.stranger_map": "Lo sconosciuto ti porge un frammento di mappa logoro con segni criptici.",
    "encounter.tavern.stranger_map_reward": "Studiando la mappa scopri segreti del sotterraneo. (+{0} PE)",
    "encounter.tavern.stranger_tip": "\"Fai attenzione alle ombre che non si muovono. È lì che si nascondono.\"",
    "encounter.tavern.stranger_tip_nod": "Annuisci, annotando mentalmente il consiglio.",
    "encounter.tavern.stranger_deal_1": "Lo sconosciuto si avvicina. \"Ho una proposta per te.\"",
    "encounter.tavern.stranger_deal_2": "\"Posso potenziare la tua abilità in combattimento... a un prezzo.\"",
    "encounter.tavern.stranger_deal_3": "\"Nulla di materiale. Solo un... favore, da riscuotere in seguito.\"",
    "encounter.tavern.stranger_deal_prompt": "Accetti l'accordo? (S/N): ",
    "encounter.tavern.stranger_deal_accept": "Energia oscura fluisce in te. Lo sconosciuto sorride.",
    "encounter.tavern.stranger_deal_stats": "+5 Forza, +5 Difesa!",
    "encounter.tavern.stranger_deal_refuse": "\"Peggio per te.\" Lo sconosciuto si dissolve nelle ombre.",
    "encounter.tavern.stranger_drunk_1": "Lo sconosciuto è completamente ubriaco e farnetica in modo incoerente.",
    "encounter.tavern.stranger_drunk_2": "Annuisci cortesemente e indietreggi lentamente.",
    "encounter.minstrel.title": "Menestrello Errante",
    "encounter.minstrel.desc_1": "Un menestrello siede a gambe incrociate nel corridoio, accordando un liuto.",
    "encounter.minstrel.desc_2": "\"Una canzone per il valoroso avventuriero? Ogni melodia porta con sé potere.\"",
    "encounter.minstrel.song_valor": "Canto del Valore (bonus Forza)",
    "encounter.minstrel.song_warding": "Canto di Protezione (bonus Difesa)",
    "encounter.minstrel.song_healing": "Melodia Curativa (Ripristina PV)",
    "encounter.minstrel.song_ballad": "Ballata della Gloria (Fama - 100o)",
    "encounter.minstrel.song_listen": "Ascolta e Basta (pochi PE)",
    "encounter.minstrel.valor_play": "Il menestrello suona una trascinante marcia di guerra!",
    "encounter.minstrel.valor_effect": "Il tuo sangue ribolle di furore bellico!",
    "encounter.minstrel.plus_strength": "+3 Forza!",
    "encounter.minstrel.warding_play": "Una melodia ipnotica ti avvolge come un'armatura eterea.",
    "encounter.minstrel.plus_defence": "+3 Difesa!",
    "encounter.minstrel.healing_play": "Note dolci e lenitive lavano le tue ferite...",
    "encounter.minstrel.hp_restored": "PV ripristinati a {0}/{1}",
    "encounter.minstrel.ballad_title": "Il menestrello compone \"La Ballata di {0}\"!",
    "encounter.minstrel.ballad_compose": "La canzone sarà cantata nelle taverne di tutto il regno!",
    "encounter.minstrel.ballad_fame": "+50 Cavalleria! La tua leggenda cresce!",
    "encounter.minstrel.ballad_no_gold": "\"Una ballata richiede monete per inchiostro e pergamena, amico.\"",
    "encounter.minstrel.listen_leave": "Ascolti una melodia piacevole e ti senti leggermente più saggio.",
    "encounter.fairy.title": "Cerchio delle Fate",
    "encounter.fairy.desc_1": "Un anello di funghi luminescenti circonda una radura.",
    "encounter.fairy.desc_2": "Piccole luci danzano nell'aria e odi risate lontane.",
    "encounter.fairy.desc_3": "La regina delle fate appare in una pioggia di scintille!",
    "encounter.fairy.option_blessing": "Chiedi una Benedizione",
    "encounter.fairy.option_steal": "Ruba la Polvere Fatata",
    "encounter.fairy.option_dance": "Danza con le Fate",
    "encounter.fairy.option_leave": "Allontanati con Rispetto",
    "encounter.fairy.blessing_good": "La regina delle fate sorride e ti tocca la fronte...",
    "encounter.fairy.blessing_hp": "Le tue ferite si rimarginano! PV completamente ripristinati!",
    "encounter.fairy.blessing_mana": "Energia magica ti attraversa! Mana completamente ripristinato!",
    "encounter.fairy.blessing_potions": "Le tue bottiglie di pozioni si riempiono magicamente!",
    "encounter.fairy.blessing_exp": "La conoscenza ti inonda la mente! +{0} PE!",
    "encounter.fairy.blessing_bad_1": "La regina delle fate aggrotta la fronte.",
    "encounter.fairy.blessing_bad_2": "\"Non sei degno dei nostri doni quest'oggi.\"",
    "encounter.fairy.blessing_bad_gold": "Una manciata d'oro svanisce dalla tua borsa! (-10% oro)",
    "encounter.fairy.steal_success": "Afferri una manciata di polvere fatata luminescente!",
    "encounter.fairy.steal_value": "Vale {0} oro per il compratore giusto!",
    "encounter.fairy.steal_darkness": "+20 Oscurità. Il popolo fatato non dimenticherà.",
    "encounter.fairy.steal_fail": "Le fate ti sorprendono con la mano nel sacco!",
    "encounter.fairy.steal_damage": "Minuscole frecce ti pungono da ogni direzione! (-{0} PV)",
    "encounter.fairy.steal_curse": "Una fata ti maledice! -2 Forza!",
    "encounter.fairy.dance_join": "Ti unisci alla danza delle fate, volteggiando nel cerchio di funghi...",
    "encounter.fairy.dance_spin": "Il mondo gira e i colori si confondono...",
    "encounter.fairy.dance_blur": "Il tempo stesso sembra piegarsi intorno a te...",
    "encounter.fairy.dance_younger": "Ti senti ringiovanito! PV, Mana e PE guadagnati!",
    "encounter.fairy.dance_gold": "Le tue tasche improvvisamente si fanno più pesanti di oro fatato!",
    "encounter.fairy.dance_queen_kiss": "La regina delle fate ti bacia sulla guancia!",
    "encounter.fairy.dance_plus_cha": "+5 Carisma!",
    "encounter.fairy.dance_time_1": "Danzi per quelli che sembrano pochi minuti...",
    "encounter.fairy.dance_time_2": "Ma giorni potrebbero essere trascorsi nel mondo di sopra.",
    "encounter.fairy.dance_language": "Improvvisamente comprendi la lingua del popolo fatato!",
    "encounter.fairy.dance_plus_int": "+3 Intelligenza!",
    "encounter.fairy.leave_1": "Ti inchini rispettosamente alla regina delle fate.",
    "encounter.fairy.leave_2": "Lei saluta con la mano e il cerchio svanisce dalla vista.",
    "encounter.damsel.title": "Donzella in Pericolo",
    "encounter.damsel.rescue_desc_1": "Una giovane donna è messa all'angolo da un gruppo di teppisti del sotterraneo!",
    "encounter.damsel.rescue_desc_2": "Urla per chiedere aiuto mentre si avvicinano!",
    "encounter.damsel.option_rescue": "Corri in Soccorso!",
    "encounter.damsel.option_watch": "Osserva dall'Ombra",
    "encounter.damsel.option_ignore": "Ignora e Prosegui",
    "encounter.damsel.rescue_charge": "Ti lanci in avanti con l'arma sguainata!",
    "encounter.damsel.rescue_scatter": "I teppisti si disperdono davanti alla tua furia!",
    "encounter.damsel.rescue_thanks_1": "\"Grazie, valoroso avventuriero! Mi hai salvato la vita!\"",
    "encounter.damsel.rescue_thanks_2": "Ti preme un sacchetto d'oro tra le mani.",
    "encounter.damsel.rescue_blush": "Arrossisce e ti bacia sulla guancia prima di andarsene.",
    "encounter.damsel.watch_hide": "Ti nascondi nelle ombre e osservi...",
    "encounter.damsel.watch_kick": "La donna improvvisamente sferra un calcio al capo tra le gambe!",
    "encounter.damsel.watch_dispatch": "Elimina i teppisti con pugnali nascosti!",
    "encounter.damsel.watch_wink": "Ti fa l'occhiolino nell'ombra.",
    "encounter.damsel.watch_thanks": "\"Grazie per non aver interferito. Tieni, per la tua discrezione.\"",
    "encounter.damsel.ignore_walk": "Te ne vai mentre le urla svaniscono alle tue spalle.",
    "encounter.damsel.trap_desc_1": "Una bella donna giace legata sul bordo di una fossa.",
    "encounter.damsel.trap_desc_2": "\"Per favore, aiutami! Sono intrappolata qui da giorni!\"",
    "encounter.damsel.trap_option_help": "Aiutala",
    "encounter.damsel.trap_option_caution": "Avvicinati con Cautela",
    "encounter.damsel.trap_grab": "Mentre afferri le corde, lei ti afferra il braccio!",
    "encounter.damsel.trap_grin": "Il suo volto si trasforma in un ghigno demoniaco!",
    "encounter.damsel.trap_fool": "\"Sciocco!\" sibila mentre energia oscura ti viene prosciugata!",
    "encounter.damsel.trap_succubus_damage": "La succube ti prosciuga {0} PV!",
    "encounter.damsel.trap_succubus_steal": "Ti ruba {0} oro prima di svanire!",
    "encounter.damsel.trap_caution_1": "Ti avvicini con cautela, saggiando ogni passo...",
    "encounter.damsel.trap_caution_2": "Noti il tremolio dell'illusione e fai un passo indietro!",
    "encounter.damsel.trap_caution_saved": "La tua prudenza ti salva dalla trappola! +PE per la saggezza!",
    "encounter.damsel.trap_leave": "Qualcosa non va. Te ne vai in silenzio.",
    "encounter.damsel.princess_desc_1": "Trovi una giovane donna riccamente vestita nascosta dietro un pilastro.",
    "encounter.damsel.princess_desc_2": "Indossa un diadema d'oro: è una nobile!",
    "encounter.damsel.princess_desc_3": "\"Per favore, sono stata rapita! Aiutami a tornare al castello!\"",
    "encounter.damsel.princess_option_escort": "Scortala in Salvo",
    "encounter.damsel.princess_option_ransom": "Chiedi un Riscatto",
    "encounter.damsel.princess_option_leave": "Lasciala",
    "encounter.damsel.princess_escort_1": "Guidi la principessa attraverso i corridoi del sotterraneo...",
    "encounter.damsel.princess_escort_2": "Dopo un viaggio insidioso, raggiungi la superficie in salvo!",
    "encounter.damsel.princess_escort_reward": "La corte reale ti ricompensa generosamente!",
    "encounter.damsel.princess_ransom_1": "Invii una richiesta di riscatto al castello.",
    "encounter.damsel.princess_ransom_2": "L'oro arriva... ma anche la tua reputazione ne risente.",
    "encounter.damsel.princess_ransom_gold": "+{0} oro dal riscatto!",
    "encounter.damsel.princess_ransom_penalty": "+100 Oscurità. Il regno non dimenticherà.",
    "encounter.damsel.princess_ransom_rep": "-100 Cavalleria. Sei bollato come un furfante.",
    "encounter.damsel.princess_leave_1": "Lasci la principessa alle sue spalle.",
    "encounter.damsel.princess_leave_2": "\"Per favore! Non lasciarmi qui!\" Le sue grida echeggiano dietro di te.",
    "encounter.damsel.warrior_desc_1": "Una fiera guerriera combatte contro un gruppo di scheletri!",
    "encounter.damsel.warrior_desc_2": "Combatte con abilità incredibile ma è in inferiorità numerica!",
    "encounter.damsel.warrior_option_join": "Unisciti alla Battaglia!",
    "encounter.damsel.warrior_option_watch": "Osserva il Combattimento",
    "encounter.damsel.warrior_join_1": "Ti lanci nella mischia al suo fianco!",
    "encounter.damsel.warrior_join_2": "Insieme fate piazza pulita dei non-morti!",
    "encounter.damsel.warrior_join_3": "\"Ben combattuto!\" ride, pulendo l'icor dalla lama.",
    "encounter.damsel.warrior_join_4": "\"Sono Sera. Combatto quaggiù da settimane.\"",
    "encounter.damsel.warrior_join_5": "\"Prendi questo — ne ho trovato più di quanto possa trasportare.\"",
    "encounter.damsel.warrior_team_hint": "\"Se mai avessi bisogno di un compagno d'armi, vieni a cercarmi alla Locanda.\"",
    "encounter.damsel.warrior_watch_1": "Osservi mentre combatte da sola...",
    "encounter.damsel.warrior_watch_2": "Trionfa, ma a malapena.",
    "encounter.damsel.warrior_watch_3": "Ti vede osservare e ti lancia un'occhiataccia. \"Grazie di niente.\"",
    "encounter.ghost.title": "Il Fantasma dell'Usurper",
    "encounter.ghost.desc_1": "Una figura scintillante si materializza davanti a te.",
    "encounter.ghost.desc_2": "Indossa la corona e l'armatura di un antico re.",
    "encounter.ghost.greet_1": "\"Sono il fantasma di un antico Usurper...\"",
    "encounter.ghost.greet_2": "\"Un tempo regnavo su queste terre, molto tempo fa.\"",
    "encounter.ghost.greet_3": "\"Ma il potere è effimero, e ora vago senza meta.\"",
    "encounter.ghost.greet_4": "\"Che cosa chiederesti a chi ha visto tutto?\"",
    "encounter.ghost.option_lore": "Chiedi del Vecchio Mondo",
    "encounter.ghost.option_advice": "Cerca Consigli di Combattimento",
    "encounter.ghost.option_friend": "Offri Amicizia",
    "encounter.ghost.lore_1": "\"Ah, i bei vecchi tempi... quando Usurper era solo un gioco su BBS.\"",
    "encounter.ghost.lore_2": "\"I giocatori si collegavano con i loro modem a 2400 baud...\"",
    "encounter.ghost.lore_3": "\"Combattevano mostri, rubavano il trono e lasciavano messaggi sgarbati.\"",
    "encounter.ghost.lore_4": "\"Jakob Dangarden creò il nostro mondo nel 1993.\"",
    "encounter.ghost.lore_5": "\"E siamo ancora qui, a combattere dopo tutti questi anni.\"",
    "encounter.ghost.lore_nostalgia": "Il fantasma sorride con nostalgia.",
    "encounter.ghost.lore_reward": "Il racconto ti ispira! +{0} PE",
    "encounter.ghost.advice_1": "\"Ascolta bene, avventuriero...\"",
    "encounter.ghost.advice_2": "\"Più scendi in profondità, più diventi forte.\"",
    "encounter.ghost.advice_3": "\"Ma non combattere mai ciò che non puoi sconfiggere.\"",
    "encounter.ghost.advice_4": "\"Equipaggia il miglior equipaggiamento che riesci a trovare.\"",
    "encounter.ghost.advice_5": "\"E tieni sempre delle pozioni curative di riserva.\"",
    "encounter.ghost.advice_reward": "+2 Intelligenza, +2 Saggezza!",
    "encounter.ghost.friend_1": "\"Un amico? Quanto tempo è passato...\"",
    "encounter.ghost.friend_2": "\"Mi ricordi me stesso, tanto tempo fa.\"",
    "encounter.ghost.friend_3": "\"Prendi questo, da un avventuriero all'altro.\"",
    "encounter.ghost.friend_gold": "Il fantasma materializza {0} monete d'oro!",
    "encounter.ghost.friend_str": "+3 Forza dalla benedizione del fantasma!",
    "encounter.ghost.fade": "Il fantasma comincia a dissolversi...",
    "encounter.ghost.farewell_1": "\"Ricorda... ogni Usurper un tempo era solo un avventuriero.\"",
    "encounter.ghost.farewell_2": "Il fantasma svanisce con un sorriso consapevole.",
    "encounter.demons.title": "Demoni Giocatori d'Azzardo",
    "encounter.demons.desc_1": "Tre demoni siedono attorno a un tavolo fluttuante di ossa e fiamme.",
    "encounter.demons.desc_2": "Lanciano dadi fatti con i denti di angeli caduti.",
    "encounter.demons.greet_1": "\"Ahh, carne fresca! Ti va una partita?\"",
    "encounter.demons.greet_2": "\"La posta è... negoziabile.\"",
    "encounter.demons.option_play": "Gioca al Loro Gioco",
    "encounter.demons.option_leave": "Rifiuta e Vattene",
    "encounter.demons.play_1": "\"Eccellente! Scegli la tua posta...\"",
    "encounter.demons.play_2": "Gli occhi dei demoni brillano di anticipazione.",
    "encounter.demons.play_3": "\"Tre dadi a testa. Il totale più alto vince.\"",
    "encounter.demons.wager_gold": "Scommetti Oro (1000o)",
    "encounter.demons.wager_soul": "Scommetti un Frammento della Tua Anima",
    "encounter.demons.wager_years": "Scommetti Anni di Esperienza",
    "encounter.demons.wager_prompt": "La tua posta: ",
    "encounter.demons.roll_demons": "I demoni ottengono: {0}",
    "encounter.demons.roll_player": "Tu ottieni: {0}",
    "encounter.demons.gold_win": "\"Bah! Prendi le tue vincite, mortale.\"",
    "encounter.demons.gold_win_amount": "+1000 oro!",
    "encounter.demons.gold_lose": "\"Il tuo oro è nostro adesso!\"",
    "encounter.demons.gold_lose_amount": "-1000 oro!",
    "encounter.demons.soul_win": "\"Impossibile! Il mortale ha vinto!\"",
    "encounter.demons.soul_win_stats": "+10 Forza, +10 Intelligenza! Il potere fluisce in te!",
    "encounter.demons.soul_lose": "\"La tua anima è deliziosa...\"",
    "encounter.demons.soul_lose_stats": "-5 Forza, -5 Carisma, +50 Oscurità!",
    "encounter.demons.years_win": "\"Il tempo ti favorisce oggi, mortale.\"",
    "encounter.demons.years_lose": "\"I tuoi anni appartengono a noi adesso...\"",
    "encounter.demons.years_lose_amount": "-{0} esperienza!",
    "encounter.demons.leave_1": "\"Codardo! Torna quando avrai più fegato!\"",
    "encounter.demons.leave_2": "Le risate dei demoni ti seguono nell'oscurità.",
    "encounter.hermit.title": "Il Vecchio Eremita",
    "encounter.hermit.desc_1": "Un vecchio siede accanto a un piccolo fuoco in un'alcova.",
    "encounter.hermit.desc_2": "I suoi occhi sono gentili ma antichi, vedono cose invisibili.",
    "encounter.hermit.desc_3": "Una pentola di zuppa bolle sul fuoco.",
    "encounter.hermit.option_sit": "Siediti Accanto al Fuoco",
    "encounter.hermit.option_ask": "Chiedi Saggezza",
    "encounter.hermit.option_give": "Donagli dell'Oro (50o)",
    "encounter.hermit.sit_1": "Ti siedi accanto all'eremita in un silenzio confortevole...",
    "encounter.hermit.sit_2": "Il fuoco scoppietta sommessamente...",
    "encounter.hermit.sit_3": "Il tempo scorre pacificamente...",
    "encounter.hermit.sit_peace": "Una pace profonda ti pervade.",
    "encounter.hermit.sit_restore": "PV e Mana completamente ripristinati!",
    "encounter.hermit.ask_1": "\"Saggezza, eh? Molto bene...\"",
    "encounter.hermit.ask_2": "\"Il sotterraneo riflette la tua anima. Combatti con onore.\"",
    "encounter.hermit.ask_3": "\"E non fidarti mai di una porta che si apre troppo facilmente.\"",
    "encounter.hermit.ask_reward": "+1 Intelligenza!",
    "encounter.hermit.give_1": "Gli occhi dell'eremita si illuminano.",
    "encounter.hermit.give_2": "\"Generosità nelle profondità... davvero rara.\"",
    "encounter.hermit.give_3": "\"Lascia che ti dia qualcosa in cambio.\"",
    "encounter.hermit.give_amulet": "Ti dona un amuleto luminescente! +5 Forza!",
    "encounter.hermit.give_potions": "Ti riempie tutte le bottiglie di pozione!",
    "encounter.hermit.give_nothing": "Non hai nulla da dare. L'eremita annuisce comprensivo.",
    "encounter.hermit.leave_msg": "Saluti l'eremita con un cenno e prosegui per la tua strada.",
    "encounter.merchant.title": "Mercante Misterioso",
    "encounter.merchant.desc_1": "Un mercante avvolto in un mantello scuro ha aperto bottega in un corridoio cieco.",
    "encounter.merchant.desc_2": "Strani oggetti brillano su un tappeto volante davanti a lui.",
    "encounter.merchant.desc_3": "\"Benvenuto, benvenuto! Merci rare per l'avventuriero esigente!\"",
    "encounter.merchant.item_potion": "Pozione Curativa ({0}o) - Cura completa",
    "encounter.merchant.item_elixir": "Elisir di Attributi ({0}o) - +5 casuale a un attributo",
    "encounter.merchant.item_mystery": "Scatola Misteriosa ({0}o) - ???",
    "encounter.merchant.item_info": "Compra Informazioni (100o)",
    "encounter.merchant.your_gold": "Il tuo oro: {0}",
    "encounter.merchant.potion_drink": "La pozione guarisce tutte le tue ferite! PV completamente ripristinati!",
    "encounter.merchant.elixir_str": "L'elisir ti pervade! +5 Forza!",
    "encounter.merchant.elixir_int": "La tua mente si espande! +5 Intelligenza!",
    "encounter.merchant.elixir_wis": "Saggezza ancestrale ti pervade! +5 Saggezza!",
    "encounter.merchant.elixir_dex": "I tuoi riflessi si acuiscono! +5 Destrezza!",
    "encounter.merchant.elixir_con": "Il tuo corpo si tempra! +5 Costituzione!",
    "encounter.merchant.elixir_cha": "Risplendi di luce interiore! +5 Carisma!",
    "encounter.merchant.mystery_open": "Apri la scatola misteriosa...",
    "encounter.merchant.mystery_jackpot": "COLPO GROSSO! {0} monete d'oro ne fuoriescono!",
    "encounter.merchant.mystery_power": "Potere puro ti attraversa! +10 For, +10 Dif!",
    "encounter.merchant.mystery_empty": "La scatola è vuota! Sei stato truffato!",
    "encounter.merchant.mystery_tome": "Un tomo di conoscenza! +{0} PE!",
    "encounter.merchant.mystery_elixirs": "Elisir di ristoro! PV, Mana e Pozioni completamente ripristinati!",
    "encounter.merchant.info_1": "\"I piani più profondi custodiscono antichi sigilli di potere.\"",
    "encounter.merchant.info_2": "\"Raccoglili tutti per svelare la verità sugli Antichi Dei.\"",
    "encounter.merchant.info_3": "\"Ma attento... gli dei stessi sorvegliano i livelli più profondi.\"",
    "encounter.merchant.no_gold_info": "\"Le informazioni non sono gratis, amico.\"",
    "encounter.merchant.leave_msg": "Il mercante si inchina. \"Alla prossima, avventuriero.\"",
    "encounter.timewarp.title": "Distorsione Temporale",
    "encounter.timewarp.desc_1": "L'aria trema e si distorce intorno a te!",
    "encounter.timewarp.desc_2": "Senti di essere trascinato attraverso il tempo...",
    "encounter.timewarp.future_1": "Intravedi una versione futura di te stesso!",
    "encounter.timewarp.future_2": "Il tuo io futuro ti lancia un sacchetto d'oro!",
    "encounter.timewarp.future_reward": "+{0} oro dal futuro!",
    "encounter.timewarp.battle_1": "Vieni trascinato in una battaglia leggendaria del passato!",
    "encounter.timewarp.battle_2": "Combattendo al fianco di eroi antichi, acquisisci esperienza!",
    "encounter.timewarp.battle_reward": "+{0} PE, +2 Forza dai ricordi di battaglia!",
    "encounter.timewarp.age_1": "Il tempo accelera intorno a te!",
    "encounter.timewarp.age_2": "Invecchi rapidamente prima che l'effetto svanisca!",
    "encounter.timewarp.age_penalty": "PV dimezzati! Esperienza persa!",
    "encounter.timewarp.young_1": "Il tempo si inverte! Ti senti ringiovanito!",
    "encounter.timewarp.young_2": "Il tuo corpo ritorna in perfetta forma!",
    "encounter.timewarp.young_reward": "PV e Mana pieni! +3 Costituzione!",
    "encounter.timewarp.death_1": "Assisti alla tua stessa morte in un futuro possibile...",
    "encounter.timewarp.death_2": "La visione è terrificante ma istruttiva.",
    "encounter.timewarp.death_3": "Impari a difenderti dalle tecniche del tuo futuro assassino.",
    "encounter.timewarp.death_reward": "+5 Difesa dalla premonizione!",
    "encounter.timewarp.end": "La distorsione temporale svanisce. Sei tornato nel presente.",
    "encounter.library.title": "Biblioteca Antica",
    "encounter.library.desc_1": "Imponenti scaffali di libri si innalzano nell'oscurità soprastante.",
    "encounter.library.desc_2": "Tomi polverosi e pergamene ricoprono ogni superficie.",
    "encounter.library.desc_3": "Una luce magica tremola, preservando questa conoscenza per ere.",
    "encounter.library.option_combat": "Studia Tecniche di Combattimento",
    "encounter.library.option_arcane": "Studia Conoscenze Arcane",
    "encounter.library.option_history": "Studia la Storia Antica",
    "encounter.library.option_maps": "Cerca Mappe del Tesoro",
    "encounter.library.combat_study": "Studi antiche forme di combattimento...",
    "encounter.library.combat_reward": "+3 Forza, +2 Destrezza!",
    "encounter.library.arcane_study": "Decifri formule arcane...",
    "encounter.library.arcane_reward": "+3 Intelligenza, +10 Mana Massimo!",
    "encounter.library.history_study": "Leggi racconti di eroi antichi...",
    "encounter.library.history_reward": "+{0} PE, +2 Saggezza!",
    "encounter.library.map_found": "Trovi una mappa del tesoro!",
    "encounter.library.map_reward": "Seguendo la mappa, trovi {0} oro!",
    "encounter.library.map_nothing": "Le mappe sono troppo sbiadite per essere lette. Non trovi nulla di utile.",
    "encounter.library.leave_msg": "Chiudi con cura l'ultimo libro e lasci la biblioteca.",
    "encounter.well.title": "Il Pozzo dei Desideri",
    "encounter.well.desc_1": "Un antico pozzo si erge in una grotta, l'acqua brilla debolmente.",
    "encounter.well.desc_2": "Monete luccicano sul fondo — offerte di avventurieri passati.",
    "encounter.well.desc_3": "Un cartello recita: \"Getta una moneta, esprimi un desiderio.\"",
    "encounter.well.option_throw": "Getta una Moneta (100o)",
    "encounter.well.option_dive": "Tuffati per le Monete",
    "encounter.well.throw_coin": "Getti una moneta d'oro nel pozzo...",
    "encounter.well.wish_granted": "Il pozzo si illumina! Il tuo desiderio è esaudito!",
    "encounter.well.wish_restore": "PV e Mana completamente ripristinati!",
    "encounter.well.wish_gold": "Monete d'oro fluttuano dalle profondità!",
    "encounter.well.wish_gold_amount": "+500 oro!",
    "encounter.well.wish_strength": "Il potere pervade le tue braccia!",
    "encounter.well.wish_str_amount": "+3 Forza!",
    "encounter.well.wish_nothing": "La moneta affonda... non succede nulla.",
    "encounter.well.wish_wisdom": "Visioni di saggezza ancestrale ti riempiono la mente!",
    "encounter.well.wish_reject": "Il pozzo respinge il tuo desiderio...",
    "encounter.well.wish_returned": "Ma rigetta più monete di quante ne avessi gettate! +150 oro!",
    "encounter.well.dive": "Ti tuffi nell'acqua gelida...",
    "encounter.well.dive_success": "Riemergi con le mani piene di monete! +{0} oro!",
    "encounter.well.dive_rich": "Gli altri avventurieri sono stati generosi!",
    "encounter.well.dive_angry": "Uno spirito dell'acqua si infuria per la tua avidità!",
    "encounter.well.dive_damage": "Ti colpisce con un getto d'acqua gelida! (-{0} PV)",
    "encounter.well.dive_escape": "Sgattaioli fuori dal pozzo, ansimando!",
    "encounter.well.leave_msg": "Lasci il pozzo indisturbato.",
    "encounter.arena.title": "Portale per l'Arena",
    "encounter.arena.desc_1": "Un portale rosso scintillante si erge davanti a te.",
    "encounter.arena.desc_2": "Attraverso di esso, puoi vedere un'arena dei gladiatori!",
    "encounter.arena.desc_3": "La folla ruggisce chiedendo sangue!",
    "encounter.arena.option_enter": "Entra nell'Arena",
    "encounter.arena.enter_portal": "Varchi il portale...",
    "encounter.arena.crowd_roars": "La folla ruggisce alla tua comparsa!",
    "encounter.arena.opponent": "Il tuo avversario: {0}!",
    "encounter.arena.victory_1": "VITTORIA! La folla impazzisce!",
    "encounter.arena.victory_2": "Vieni ricoperto di gloria!",
    "encounter.arena.defeat": "Vieni portato via dall'arena, a malapena vivo.",
    "encounter.arena.fled": "Fuggi dall'arena. La folla fischia.",
    "encounter.arena.empty": "L'arena è stranamente vuota oggi.",
    "encounter.arena.leave_1": "Ti allontani dal portale.",
    "encounter.arena.leave_2": "Le acclamazioni della folla svaniscono mentre il portale si chiude.",
    "encounter.bone_oracle.title": "L'Oracolo d'Ossa",
    "encounter.bone_oracle.desc_1": "Una figura fatta interamente di ossa siede su un trono di teschi.",
    "encounter.bone_oracle.desc_2": "Le sue orbite vuote brillano di una pallida luce blu.",
    "encounter.bone_oracle.option_future": "Chiedi del Tuo Futuro",
    "encounter.bone_oracle.option_dungeon": "Chiedi del Sotterraneo",
    "encounter.bone_oracle.prophecy_0": "\"La morte viene per tutti noi... ma non oggi per te.\"",
    "encounter.bone_oracle.prophecy_1": "\"I tuoi scudi reggeranno quando quelli degli altri si spezzeranno.\"",
    "encounter.bone_oracle.prophecy_2": "\"L'onore ti servirà bene nelle battaglie a venire.\"",
    "encounter.bone_oracle.prophecy_3": "\"Cerca la saggezza, e il potere seguirà.\"",
    "encounter.bone_oracle.dungeon_1": "\"I morti sussurrano i segreti di queste sale...\"",
    "encounter.bone_oracle.dungeon_2": "\"Guardati dalle camere sigillate. Custodiscono potere antico.\"",
    "encounter.bone_oracle.dungeon_3": "\"Gli Antichi Dei si agitano nei luoghi più profondi.\"",
    "encounter.spirits.title": "Spiriti Inquieti",
    "encounter.spirits.desc_1": "Figure traslucide attraversano le pareti, gemendo sommessamente.",
    "encounter.spirits.desc_2": "Questi spiriti sembrano intrappolati tra i mondi.",
    "encounter.spirits.option_help": "Aiutali a trovare pace",
    "encounter.spirits.option_attack": "Attacca gli spiriti",
    "encounter.spirits.option_ignore": "Ignorali",
    "encounter.spirits.help_1": "Pronunci parole di conforto agli spiriti...",
    "encounter.spirits.help_2": "Uno dopo l'altro, cominciano a brillare di luce calda.",
    "encounter.spirits.help_3": "\"Grazie...\" sussurrano mentre svaniscono in pace.",
    "encounter.spirits.help_reward": "+50 Cavalleria, +{0} PE!",
    "encounter.spirits.attack_1": "Colpisci gli spiriti, ma la tua arma li attraversa!",
    "encounter.spirits.attack_2": "Gli spiriti si vendicano con urla agghiaccianti!",
    "encounter.spirits.attack_penalty": "-{0} PV, +20 Oscurità!",
    "encounter.crypt.title_icon": "Il Custode della Cripta",
    "encounter.crypt.desc_1": "Una figura avvizzita in vesti lacere si prende cura di antiche bare.",
    "encounter.crypt.desc_2": "\"Ah, uno dei vivi. Come... rinfrescante.\"",
    "encounter.crypt.option_trade": "Commercia per Provviste (150o)",
    "encounter.crypt.option_info": "Chiedi Informazioni",
    "encounter.crypt.trade_1": "\"Facciamo affari...\"",
    "encounter.crypt.trade_success": "Il Custode della Cripta ti porge due fiale di pozione curativa.",
    "encounter.crypt.hint_seal_1": "\"Percepisco un antico sigillo nelle vicinanze... il piano {0} custodisce potere.\"",
    "encounter.crypt.hint_seal_2": "\"Rivendicalo prima che l'oscurità lo faccia.\"",
    "encounter.crypt.hint_god_1": "\"{0} si agita al piano {1}...\"",
    "encounter.crypt.hint_god_2": "\"Preparati bene prima di cercare quell'udienza.\"",
    "encounter.crypt.hint_low_1": "\"I piani superiori sono solo l'inizio.\"",
    "encounter.crypt.hint_low_2": "\"Il vero potere giace più in profondità. Molto più in profondità.\"",
    "encounter.crypt.hint_mid_1": "\"Sei arrivato lontano, ma le vere sfide ti attendono.\"",
    "encounter.crypt.hint_mid_2": "\"Oltre il piano {0}, il sotterraneo cambia.\"",
    "encounter.crypt.hint_deep_1": "\"Cammini tra le leggende ormai.\"",
    "encounter.crypt.hint_deep_2": "\"Gli Antichi Dei conoscono il tuo nome.\"",
    "encounter.crypt.hint_generic_1": "\"I morti vedono molto di ciò che ai vivi sfugge.\"",
    "encounter.crypt.hint_generic_2": "\"Scendi più in profondità. Il tuo destino ti attende di sotto.\"",
    "encounter.tomb.title_icon": "Tomba Antica",
    "encounter.tomb.desc_1": "Un massiccio sarcofago di pietra domina questa camera.",
    "encounter.tomb.desc_2": "Offerte d'oro lo circondano, lasciate da antichi dolenti.",
    "encounter.tomb.desc_3": "Il coperchio è sigillato ma sembra spostabile con uno sforzo.",
    "encounter.tomb.option_open": "Apri il Sarcofago",
    "encounter.tomb.option_take": "Prendi le Offerte",
    "encounter.tomb.option_leave": "Lascialo Indisturbato",
    "encounter.tomb.open_push": "Spingi con fatica il pesante coperchio di pietra...",
    "encounter.tomb.open_mummy": "Una mummia balza fuori e ti artigila!",
    "encounter.tomb.open_mummy_treasure": "Ma il tesoro all'interno vale il dolore!",
    "encounter.tomb.open_dust_1": "Il sarcofago contiene solo polvere e un amuleto d'oro.",
    "encounter.tomb.open_dust_2": "L'amuleto pulsa di potere antico!",
    "encounter.tomb.open_dust_reward": "+{0} oro, +2 Forza!",
    "encounter.tomb.take_careful": "Intaschi con cura le offerte d'oro.",
    "encounter.ratking.title_icon": "Il Re dei Ratti",
    "encounter.ratking.desc_1": "Un enorme ratto, grande come un cane, siede in cima a un mucchio di rifiuti.",
    "encounter.ratking.desc_2": "Centinaia di ratti più piccoli gli sciamano intorno in modo protettivo.",
    "encounter.ratking.desc_3": "Il Re dei Ratti squittisce imperiosamente. Vuole un tributo!",
    "encounter.ratking.option_pay": "Paga il Tributo (500o)",
    "encounter.ratking.option_fight": "Combatti lo Sciame",
    "encounter.ratking.option_run": "Fuggi",
    "encounter.ratking.pay_accept": "Il Re dei Ratti accetta la tua offerta.",
    "encounter.ratking.pay_pass": "I ratti si aprono, rivelando un deposito nascosto dietro di loro!",
    "encounter.ratking.pay_cache": "Il tesoro del Re dei Ratti è impressionante!",
    "encounter.ratking.fight_swarm": "I ratti ti travolgono, mordendo e graffiando!",
    "encounter.ratking.fight_damage": "-{0} PV da migliaia di piccoli morsi!",
    "encounter.ratking.fight_slay": "Uccidi il Re dei Ratti! Il suo tesoro è tuo!",
    "encounter.ratking.run_flee": "Fuggi dai ratti, i loro squittii echeggiano dietro di te.",
    "encounter.child.title_icon": "Bambino Smarrito",
    "encounter.child.desc_1": "Un bambino piccolo è rannicchiato nell'angolo, piangendo sommessamente.",
    "encounter.child.desc_2": "\"Mi sono perso... non riesco a trovare la via di casa...\"",
    "encounter.child.option_help": "Aiuta il Bambino",
    "encounter.child.option_check": "Controlla Prima le Trappole",
    "encounter.child.help_guide": "Guidi il bambino attraverso i tunnel fino in salvo.",
    "encounter.child.help_thanks": "I genitori del bambino sono al settimo cielo!",
    "encounter.child.help_reward": "+{0} oro di ricompensa, +100 Cavalleria!",
    "encounter.child.check_trap_1": "Il bambino è un'illusione! È una trappola!",
    "encounter.child.check_trap_2": "Dardi avvelenati volano dalle pareti!",
    "encounter.child.check_safe": "Sembra essere un vero bambino. Lo aiuti in sicurezza.",
    "encounter.child.ignore_walk": "Te ne vai, ignorando il bambino in lacrime.",
    "encounter.alchemy.title": "Laboratorio Alchemico Abbandonato",
    "encounter.alchemy.title_icon": "Laboratorio Alchemico Abbandonato",
    "encounter.alchemy.desc_1": "Fiale di vetro e calderoni gorgoglianti riempiono questo laboratorio nascosto.",
    "encounter.alchemy.desc_2": "Pozioni colorate rivestono gli scaffali. La maggior parte sembra instabile.",
    "encounter.alchemy.option_drink": "Bevi una Pozione a Caso",
    "encounter.alchemy.option_read": "Leggi gli Appunti di Ricerca",
    "encounter.alchemy.option_steal": "Ruba le Provviste",
    "encounter.alchemy.drink_gulp": "Afferri una fiala a caso e la mandi giù d'un fiato...",
    "encounter.alchemy.drink_power": "Potere puro ti pervade! +5 Forza!",
    "encounter.alchemy.drink_health": "Le tue ferite si rimarginano! PV completamente ripristinati!",
    "encounter.alchemy.drink_poison": "Veleno! La pozione ti brucia le viscere!",
    "encounter.alchemy.drink_enlighten": "La tua mente si espande! +5 Intelligenza!",
    "encounter.alchemy.drink_invisible": "Diventi visibile e invisibile a intermittenza! +3 Destrezza!",
    "encounter.alchemy.read_notes": "Gli appunti contengono preziose conoscenze alchemiche.",
    "encounter.alchemy.read_reward": "+2 Intelligenza, +{0} PE!",
    "encounter.alchemy.steal_grab": "Afferri pozioni e oro dal laboratorio!",
    "encounter.alchemy.steal_reward": "+{0} oro, +2 pozioni curative!",
    "encounter.hoard.title": "Tesoro Ammassato!",
    "encounter.hoard.desc_1": "Un'enorme catasta di oro e gemme riempie questa camera!",
    "encounter.hoard.desc_2": "Luccica in modo invitante alla luce delle torce.",
    "encounter.hoard.desc_3": "Ma è una trappola?",
    "encounter.hoard.option_take_all": "Prendi Tutto!",
    "encounter.hoard.option_take_some": "Prendine un Po' con Cautela",
    "encounter.hoard.option_leave": "Lascialo (Sospetto)",
    "encounter.hoard.trap_thieves": "TRAPPOLA! Dei banditi sbucano da dietro la catasta!",
    "encounter.hoard.trap_grab": "Li respingi ma riesci ad afferrare un po' d'oro!",
    "encounter.hoard.jackpot": "Nessuna trappola! È tutto tuo!",
    "encounter.hoard.some_pocket": "Intaschi con cautela un po' d'oro e gemme.",
    "encounter.hoard.leave_caution": "La tua prudenza ti serve bene. Lasci l'esca intoccata.",
    "encounter.crystal.title": "Grotta di Cristallo",
    "encounter.crystal.desc_1": "Cristalli massicci sporgono da ogni superficie, vibrando di energia.",
    "encounter.crystal.desc_2": "L'aria crepita di potenziale magico.",
    "encounter.crystal.good_1": "I cristalli risuonano con la tua aura magica!",
    "encounter.crystal.good_2": "Mana ripristinato! +3 Intelligenza!",
    "encounter.crystal.bad": "Un cristallo si frantuma, lanciandoti schegge addosso! Ahia!",
    "encounter.dragon_hoard.title": "Tesoro del Drago",
    "encounter.dragon_hoard.desc_1": "Un drago addormentato sorveglia un'immensa catasta d'oro.",
    "encounter.dragon_hoard.desc_2": "Con molta, MOLTA cautela, allunghi la mano verso il tesoro...",
    "encounter.dragon_hoard.grab": "Afferri {0} oro e CORRI!",
    "encounter.dwarven.title_icon": "Avamposto Nanico",
    "encounter.dwarven.desc_1": "Un piccolo accampamento nanico, completo di forgia e barile di birra.",
    "encounter.dwarven.desc_2": "I nani ti accolgono calorosamente e condividono le loro provviste.",
    "encounter.dwarven.reward_1": "I nani condividono le loro provviste curative!",
    "encounter.dwarven.reward_2": "+3 Pozioni Curative!",
    "encounter.lake.title_icon": "Lago Sotterraneo",
    "encounter.lake.desc_1": "Un vasto lago sotterraneo si estende davanti a te.",
    "encounter.lake.desc_2": "L'acqua risplende di una tenue luce blu.",
    "encounter.lake.reward": "Le acque magiche ti ristabiliscono completamente! PV e Mana ripristinati!",
    "encounter.golem.title_icon": "Golem Antico",
    "encounter.golem.desc_1": "Un massiccio golem di pietra ti blocca il cammino.",
    "encounter.golem.desc_2": "\"Rispondi al mio indovinello per passare.\"",
    "encounter.golem.riddle": "\"Ho tasti ma non apro serrature. Ho spazio ma non stanze. Puoi premere Invio ma non puoi entrare. Cosa sono?\"",
    "encounter.golem.prompt": "La tua risposta: ",
    "encounter.golem.correct": "\"Corretto! Puoi passare.\" Il golem si fa da parte.",
    "encounter.golem.wrong": "\"Sbagliato!\" Il golem ti colpisce!",
    "encounter.capsule.title_icon": "Capsula del Tempo",
    "encounter.capsule.desc_1": "Un contenitore metallico sigillato di un'altra era.",
    "encounter.capsule.desc_2": "All'interno trovi monete antiche e una pergamena di conoscenza.",
    "encounter.fountain.title_icon": "Fontana Magica",
    "encounter.fountain.desc": "Una fontana di acqua luminescente sgorga dal pavimento del sotterraneo.",
    "encounter.fountain.reward": "Le acque curative guariscono ogni male! PV, Mana ripristinati! Veleno curato!",
    "encounter.civilization.title_icon": "Civiltà Perduta",
    "encounter.civilization.desc_1": "Le rovine di un'antica civiltà si estendono davanti a te.",
    "encounter.civilization.desc_2": "La conoscenza dei loro costumi ti inonda la mente.",
    "encounter.civilization.reward": "+5 Intelligenza, +{0} PE!",
    "encounter.demon_bargain.title_icon": "Patto Demoniaco",
    "encounter.demon_bargain.desc_1": "Un demone ti offre un patto oscuro.",
    "encounter.demon_bargain.desc_2": "\"Potere in cambio della tua anima... uno scambio equo, no?\"",
    "encounter.demon_bargain.option_accept": "Accetta il Patto",
    "encounter.demon_bargain.option_refuse": "Rifiuta",
    "encounter.demon_bargain.accept_result": "+10 Forza, ma +100 Oscurità corrompe la tua anima!",
    "encounter.demon_bargain.refuse_result": "Rifiuti l'offerta del demone. La tua anima resta tua.",
    "encounter.tortured.title_icon": "Anime Tormentate",
    "encounter.tortured.desc": "Anime si contorcono nel tormento. Offri loro parole di conforto.",
    "encounter.tortured.reward": "+30 Cavalleria! La tua compassione porta loro la pace.",
    "encounter.forge.title": "Forgia Infernale",
    "encounter.forge.title_icon": "Forgia Infernale",
    "encounter.forge.desc_1": "Una massiccia forgia arde di fuoco infernale.",
    "encounter.forge.desc_2": "Fabbri demoniaci martellano armi di oscuro potere.",
    "encounter.forge.desc_3": "Uno di loro ti nota e ti fa cenno.",
    "encounter.forge.desc_4": "\"Lascia che migliori la tua arma, mortale. Gratis... questa volta.\"",
    "encounter.forge.reward": "La tua arma risplende di potere infernale! +5 Potenza dell'Arma!",
    "encounter.succubus.title_icon": "Incontro con una Succube",
    "encounter.succubus.desc_1": "Una bellissima figura emerge dalle ombre.",
    "encounter.succubus.desc_2": "\"Avvicinati, tesoro... lascia che lenisca il tuo dolore.\"",
    "encounter.succubus.option_resist": "Resisti alla Tentazione",
    "encounter.succubus.option_succumb": "Cedi",
    "encounter.succubus.resist_result": "La tua forza di volontà regge! +5 Saggezza!",
    "encounter.succubus.succumb_result": "La succube ti prosciuga la forza vitale! -PV, -20% Oro!",
    "encounter.frozen.title_icon": "Avventuriero Congelato",
    "encounter.frozen.desc_1": "I resti congelati di un avventuriero contengono provviste utili.",
    "encounter.frozen.desc_2": "Il suo viaggio è finito, ma il tuo continua.",
    "encounter.frozen.reward": "Recuperi oro e pozioni curative dai resti.",
    "encounter.ice_queen.title": "La Regina dei Ghiacci",
    "encounter.ice_queen.desc_1": "Una bellissima regina fatta di ghiaccio vivente ti osserva con freddezza.",
    "encounter.ice_queen.desc_2": "\"Mi intrighi, mortale. Accetta la mia benedizione.\"",
    "encounter.ice_queen.reward": "+3 Carisma! Mana completamente ripristinato!",
    "encounter.yeti.title_icon": "Tana dello Yeti",
    "encounter.yeti.desc_1": "Inciampi nella tana di uno yeti!",
    "encounter.yeti.desc_2": "L'enorme creatura ruggisce!",
    "encounter.yeti.mauled": "Lo yeti ti malmena prima che tu riesca a fuggire! Ma trovi il suo tesoro!",
    "encounter.yeti.back_away": "Indietreggi lentamente... lo yeti ti lascia andare.",
    "encounter.aurora.title": "Visione d'Aurora",
    "encounter.aurora.desc_1": "Impossibili aurore boreali danzano nel cielo sotterraneo.",
    "encounter.aurora.desc_2": "La bellezza ti riempie di meraviglia e pace.",
    "encounter.aurora.reward": "PV e Mana ripristinati! +3 Saggezza!",
    "encounter.fire_elemental.title": "Elementale di Fuoco",
    "encounter.fire_elemental.title_icon": "Elementale di Fuoco",
    "encounter.fire_elemental.desc_1": "Un essere di pura fiamma danza davanti a te.",
    "encounter.fire_elemental.desc_2": "Condivide la sua conoscenza della magia del fuoco prima di svanire.",
    "encounter.fire_elemental.reward": "+3 Intelligenza, +20 Mana Massimo!",
    "encounter.lava_boat.title_icon": "Barca sulla Lava",
    "encounter.lava_boat.desc_1": "Un barcaiolo offre di traghettarti attraverso un fiume di lava.",
    "encounter.lava_boat.desc_2": "\"500 oro, e ti porto dall'altra parte.\"",
    "encounter.lava_boat.cross": "Il viaggio rivela conoscenze nascoste del sotterraneo! +{0} PE!",
    "encounter.lava_boat.no_gold": "\"Niente oro, niente passaggio. Nuota, se ne hai il coraggio.\"",
    "encounter.phoenix.title_icon": "Nido della Fenice",
    "encounter.phoenix.desc_1": "Una magnifica fenice siede su un nido di braci.",
    "encounter.phoenix.desc_2": "Ti sfiora con una piuma ardente.",
    "encounter.phoenix.reward": "Il fuoco della fenice ti guarisce! PV pieni, +5 Costituzione!",
    "encounter.mirror.title_icon": "Specchio d'Ossidiana",
    "encounter.mirror.desc_1": "Uno specchio di ossidiana levigata mostra il tuo riflesso.",
    "encounter.mirror.desc_2": "Ma il tuo riflesso è più forte, più intelligente, più veloce...",
    "encounter.mirror.reward": "Assorbi il potere del tuo riflesso! +2 FOR, +2 INT, +2 DES!",
    "encounter.void.title_icon": "Sussurro del Vuoto",
    "encounter.void.desc": "Il vuoto tra le realtà sussurra conoscenze proibite.",
    "encounter.void.reward": "+5 Intelligenza, +5 Saggezza, +30 Oscurità!",
    "encounter.reality.title": "Strappo nella Realtà",
    "encounter.reality.title_icon": "Strappo nella Realtà",
    "encounter.reality.desc_1": "Uno strappo nel tessuto della realtà pulsa davanti a te.",
    "encounter.reality.desc_2": "Oggetti cadono da altre dimensioni...",
    "encounter.reality.good": "Tesori da un'altra dimensione! Colpo grosso!",
    "encounter.reality.bad": "Energia del vuoto ti colpisce! Ahia!",
    "encounter.cosmic.title_icon": "Entità Cosmica",
    "encounter.cosmic.desc_1": "Un essere di dimensioni incomprensibili ti osserva.",
    "encounter.cosmic.desc_2": "Ti impartisce una frazione della sua conoscenza cosmica.",
    "encounter.cosmic.reward": "PE e Saggezza guadagnati!",
    "encounter.madness.title_icon": "Pozza della Follia",
    "encounter.madness.desc_1": "Una pozza di liquido vorticoso e iridescente gorgoglia davanti a te.",
    "encounter.madness.desc_2": "Fissandola, vedi geometrie impossibili.",
    "encounter.madness.option_look": "Guarda più a Fondo",
    "encounter.madness.option_avoid": "Distogli lo Sguardo",
    "encounter.madness.look_good": "La follia rivela verità nascoste! +10 INT, +50 Oscurità!",
    "encounter.madness.look_bad": "Le visioni frantumano la tua mente! -5 Intelligenza!",
    "encounter.madness.avoid": "Saggiamente distogli lo sguardo. Certa conoscenza non vale il prezzo.",
}
