translations = {
    "street.blocks_path": "  {0} ti blocca la strada!",
    "street.hostile_level_info": "  Livello {0} {1} - PV: {2}/{3}",
    "street.menu_fight": "]ombatti  [",
    "street.menu_run": "]uggi  [",
    "street.menu_bribe": "]orrompi  [",
    "street.menu_talk": "]arla",
    "street.pickpocket_noticed": "  Senti una mano che fruga nella tua borsa!",
    "street.menu_grab": "]fferrali  [",
    "street.menu_shout_guards": "]hiama le guardie  [",
    "street.menu_ignore": "]gnora",
    "street.grab_thief": "  Afferri il {0}!",
    "street.shout_guards": "  \"Guardie! Guardie!\" gridi.",
    "street.thief_flees": "  Il ladro fugge tra la folla.",
    "street.ignore_thief": "  Fingi di non accorgerti. Il ladro sgattaiola via.",
    "street.bumped_street": "  Qualcuno ti urta per strada...",
    "street.gold_missing": "  Più tardi, ti accorgi che mancano {0} monete d'oro!",
    "street.bumped_nothing": "  Qualcuno ti urta, ma non trova nulla da rubare.",
    "street.brawl_reason_1": "Un ubriaco ti rovescia la birra addosso!",
    "street.brawl_reason_2": "Qualcuno ti accusa di barare ai dadi!",
    "street.brawl_reason_3": "Un avventore insulta il tuo aspetto!",
    "street.brawl_reason_4": "Ti ritrovi nel mezzo di una rissa da taverna!",
    "street.brawl_reason_5": "Un mercenario cerca rissa con te!",
    "street.brawl_reason_6": "Qualcuno sostiene che stai seduto al suo posto!",
    "street.menu_duck": "]chiva e fuggi  [",
    "street.menu_buy_drink": "]ffrì da bere",
    "street.brawler_squares_up": "  {0} si mette in guardia contro di te!",
    "street.duck_escape": "  Ti abbassi sotto una sedia volante e scappi dalla rissa!",
    "street.duck_fail": "  Cerchi di scappare ma vieni colpito da un boccale volante!",
    "street.buy_drinks_success": "  Offri un giro di bevute e calmi gli animi!",
    "street.buy_drinks_toast": "  I rissosi brindano alla tua salute!",
    "street.buy_drinks_no_gold": "  Non hai abbastanza oro! La rissa continua!",
    "street.challenge_approach": "  {0} ti si avvicina con aria di sfida.",
    "street.challenge_info": "  {0} - Livello {1} {2}",
    "street.menu_accept": "]ccetta la sfida  [",
    "street.menu_decline": "]eclina  [",
    "street.menu_insult": "]nsultali",
    "street.accept_fight": "  \"Combattiamo con onore!\" dichiari.",
    "street.decline_reply": "  \"Non oggi,\" rispondi.",
    "street.decline_scoff": "  {0} sogghigna ma ti lascia passare.",
    "street.insult_honor": "  Insulti il loro onore!",
    "street.insult_reply": "  {0}: \"Me la pagherai!\"",
    "street.muggers_emerge": "  {0} teppisti emergono dalle ombre!",
    "street.muggers_demand": "  \"La borsa o la vita!\"",
    "street.menu_surrender": "]onsegna l'oro  [",
    "street.menu_run_for_it": "]uggi a gambe levate",
    "street.draw_weapon": "  Sguaini la tua arma e ti prepari a combattere!",
    "street.defeated_muggers": "  Hai sconfitto i rapinatori e trovato {0} monete d'oro sui loro corpi!",
    "street.surrender_gold": "  Consegni {0} monete d'oro.",
    "street.thugs_disappear": "  I teppisti prendono il tuo oro e svaniscono nelle ombre.",
    "street.escape_muggers": "  Corri via e li semini tra le strade!",
    "street.caught_muggers": "  Ti acciuffano e ti pestano a dovere!",
    "street.damage_and_gold_loss": "  Subisci {0} danni e perdi {1} monete d'oro.",
    "street.gang_block_path": "  Membri dei {0} ti bloccano la strada!",
    "street.gang_team_taunt": "  \"Abbiamo sentito che stai con i {0}...\"",
    "street.gang_territory": "  \"Questo è il nostro territorio!\"",
    "street.menu_fight_territory": "]ombatti per il territorio  [",
    "street.menu_negotiate": "]ratta  [",
    "street.menu_leave": "]attene",
    "street.gang_recruit": "  \"Sembri uno che ha bisogno di amici...\"",
    "street.menu_join": "]nisciti  [",
    "street.menu_refuse": "]ifiuta  [",
    "street.menu_fight_short": "]ombatti",
    "street.gang_wrong_answer": "  \"Risposta sbagliata!\" gridano.",
    "street.gang_victory_fame": "  La voce della tua vittoria sui {0} si diffonde!",
    "street.gang_fame_bonus": "  (+20 Fama)",
    "street.gang_looks_over": "  La banda ti scruta...",
    "street.gang_welcome": "  \"Benvenuto nei {0}!\"",
    "street.gang_too_weak": "  \"Torna quando sarai più forte, debole!\"",
    "street.gang_not_recruiting": "  I membri della banda si scambiano occhiate e indietreggiano...",
    "street.gang_not_recruiting_2": "  \"In realtà, non stiamo reclutando adesso.\"",
    "street.gang_let_pass": "  Ti lasciano passare... questa volta.",
    "street.gang_nobody_refuses": "  \"Nessuno ci rifiuta!\"",
    "street.admirer_approaches": "  Un {0} cattura il tuo sguardo e si avvicina...",
    "street.admirer_drink": "  \"Ehi. Mi offri da bere?\"",
    "street.menu_yes": "]ì  [",
    "street.menu_no_thanks": "]o grazie  [",
    "street.menu_flirt": "]lirta",
    "street.romantic_time": "  Passate un momento piacevole insieme...",
    "street.romantic_friend": "  Fate una splendida conversazione e stringi una nuova amicizia!",
    "street.romantic_wake_lighter": "  Ti svegli più tardi scoprendo la borsa più leggera...",
    "street.romantic_stolen": "  Ti hanno rubato {0} monete d'oro!",
    "street.romantic_token": "  Ti lasciano un piccolo pegno d'affetto.",
    "street.romantic_decline": "  \"Forse un'altra volta,\" dici.",
    "street.romantic_walk_away": "  Sorridono e se ne vanno.",
    "street.merchant_shady_beckon": "  Una figura incappucciata ti fa cenno dalle ombre...",
    "street.merchant_shady_offer": "  \"Psst! Vuoi comprare qualcosa di... speciale?\"",
    "street.merchant_wave": "  Un mercante ambulante ti fa cenno.",
    "street.merchant_pitch": "  \"Merce pregiata! Oggetti rari! I migliori prezzi in città!\"",
    "street.merchant_no_thanks": "] No grazie",
    "street.merchant_buy_prompt": "Quale oggetto vuoi comprare? ",
    "street.merchant_purchased": "  Acquisti il {0}!",
    "street.merchant_no_gold": "  Non hai abbastanza oro!",
    "street.merchant_farewell": "  \"Torna quando vuoi!\" grida il mercante.",
    "street.beggar_approach": "  Un mendicante cencioso ti si avvicina...",
    "street.beggar_plea": "  \"Per favore, gentile avventuriero, qualche moneta per un povero?\"",
    "street.menu_give_gold": "]ai dell'oro (10)  [",
    "street.menu_large_donation": "]rande donazione (50)  [",
    "street.menu_rob": "]apina",
    "street.beggar_thanks": "  Il mendicante ti ringrazia calorosamente!",
    "street.beggar_chivalry_5": "  (+5 Cavalleria)",
    "street.beggar_weeps": "  \"Che gli dei ti benedicano, anima generosa!\" il mendicante piange di gioia.",
    "street.beggar_chivalry_20": "  (+20 Cavalleria)",
    "street.beggar_amulet": "  Il mendicante ti porge uno strano amuleto...",
    "street.beggar_amulet_luck": "  \"Questo un tempo mi portò fortuna. Possa servirti bene.\"",
    "street.beggar_rob_msg": "  Frugi tra i miseri averi del mendicante...",
    "street.beggar_rob_result": "  Trovi {0} monete d'oro. (+15 Oscurità, -10 Cavalleria)",
    "street.beggar_walk_past": "  Passi oltre senza dire una parola.",
    "street.rumor_overhear": "  Cogli una conversazione interessante...",
    "street.guard_approach": "  Una pattuglia di guardie cittadine si avvicina...",
    "street.guard_crown_notice": "  Il capo pattuglia ti scruta, poi nota le tue insegne della Corona.",
    "street.guard_crown_pass": "  \"...Circolare. Affari della Corona.\"",
    "street.guard_crown_aside": "  Le guardie si fanno da parte senza aggiungere altro.",
    "street.guard_halt": "  \"Alt! Vi stavamo cercando!\"",
    "street.guard_darkness_note": "  (Ti stanno cercando — Oscurità: {0})",
    "street.menu_surrender_arrest": "]rrenditi  [",
    "street.menu_bribe_100": "]orrompi (100 oro)",
    "street.guard_arrest": "  Le guardie ti arrestano e ti portano in prigione...",
    "street.guard_confiscate": "  Le guardie ti confiscano {0} monete d'oro!",
    "street.guard_sentence": "  Sei condannato a {0} giorn{1} di prigione.",
    "street.guard_darkness_attack": "  (+30 Oscurità per aver attaccato le guardie)",
    "street.guard_overpower": "  Le guardie ti sopraffanno e ti mettono in catene!",
    "street.guard_sentence_resist": "  Sei condannato a {0} giorni di prigione per aver resistito all'arresto.",
    "street.guard_bribe_success": "  Le guardie intascano il tuo oro e girano lo sguardo...",
    "street.guard_escape_crowd": "  Fuggi tra la folla!",
    "street.guard_caught": "  Le guardie ti acciuffano!",
    "street.guard_running_extra": "  \"Fuggi dalla legge, eh? Questo ti costerà caro!\"",
    "street.guard_sentence_run": "  Sei condannato a {0} giorni di prigione.",
    "street.guard_stay_out": "  \"State fuori dai guai, cittadino.\"",
    "street.guard_continue_patrol": "  Le guardie proseguono la ronda.",
    "street.ambush_assassins": "  Assassini balzano dalle ombre!",
    "street.ambush_paid": "  \"Qualcuno ha pagato bene per vederti morto!\"",
    "street.ambush_first_strike": "  Il primo colpo dell'assassino infligge {0} danni!",
    "street.ambush_note": "  Trovi un biglietto sul corpo dell'assassino...",
    "street.ambush_contract": "  \"Contratto: Eliminare colui che si chiama {0}\"",
    "street.ambush_signature": "  La firma è illeggibile.",
    "street.attack_target": "  Attacchi {0}!",
    "street.flee_attempt": "  Cerchi di fuggire...",
    "street.flee_success": "  Riesci a scappare!",
    "street.flee_caught": "  {0} ti acciuffa!",
    "street.flee_back_turned": "  Ti attaccano mentre hai le spalle voltate!",
    "street.flee_damage": "  Subisci {0} danni!",
    "street.bribe_offer": "  \"Che ne dici di {0} monete d'oro e dimentichiamo tutto?\"",
    "street.bribe_no_gold": "  Non hai abbastanza oro!",
    "street.bribe_npc_attacks": "  {0} attacca!",
    "street.menu_yes_pay": "]ì, paga {0}  [",
    "street.menu_no_fight": "]o, combatti",
    "street.bribe_accepted": "  {0} prende il tuo oro e se ne va.",
    "street.bribe_rejected": "  {0} prende il tuo oro e attacca comunque!",
    "street.talk_attempt": "  Cerchi di ragionare con loro...",
    "street.talk_success": "  {0} ci ripensa e se ne va.",
    "street.talk_fail": "  {0} non è interessato a parlare!",
    "street.hostile_phrase_1": "La borsa o la vita!",
    "street.hostile_phrase_2": "Questo è il tuo ultimo giorno!",
    "street.hostile_phrase_3": "Ti farò a pezzi!",
    "street.hostile_phrase_4": "Preparati a morire!",
    "street.hostile_phrase_5": "Nessuno mi sfugge!",
    "street.hostile_phrase_6": "È ora di sanguinare!",
    "street.hostile_phrase_7": "Recita le tue preghiere!",
    "street.hostile_phrase_8": "Hai scelto la strada sbagliata!",
    "street.hostile_phrase_9": "Aspettavo qualcuno come te!",
    "street.hostile_phrase_10": "Per te è la fine!",
    "street.challenge_phrase_1": "Ti sfido, {0}! Vediamo chi è il più forte!",
    "street.challenge_phrase_2": "Ho sentito parlare di te. Combatti con me!",
    "street.challenge_phrase_3": "Dicono che sei tosto. Vediamo se è vero!",
    "street.challenge_phrase_4": "Credi di essere forte? Scopriamolo!",
    "street.challenge_phrase_5": "La mia spada ha sete di sangue. Tu andrai bene.",
    "street.challenge_phrase_6": "Avanti, allora. A meno che tu non abbia paura.",
    "street.rumor_1": "Dicono che i sotterranei siano diventati più pericolosi ultimamente...",
    "street.rumor_2": "Ho sentito che il Re cerca avventurieri coraggiosi.",
    "street.rumor_3": "Strane creature sono state avvistate vicino al Vicolo Oscuro.",
    "street.rumor_4": "I sacerdoti del tempio offrono benedizioni a chi fa offerte.",
    "street.rumor_5": "C'è una fortuna da guadagnare cacciando mostri!",
    "street.rumor_6": "I capigilda sono sempre alla ricerca di nuove reclute.",
    "street.rumor_7": "Attento le spalle nei vicoli di notte...",
    "street.rumor_8": "Il negozio d'armi ha appena ricevuto un nuovo carico di lame pregiate.",
    "street.rumor_9": "C'è chi dice che esista un passaggio segreto nei sotterranei...",
    "street.rumor_10": "I mercanti del mercato hanno merci esotiche da terre lontane.",
    "street.rumor_npc_seen": "Ho visto {0} al {1} poco fa.",
    "street.rumor_npc_team": "Dicono che {0} cerchi di formare una squadra.",
    "street.admirer_female_1": "Leggiadra fanciulla",
    "street.admirer_female_2": "Bella sconosciuta",
    "street.admirer_female_3": "Donna misteriosa",
    "street.admirer_female_4": "Dama affascinante",
    "street.admirer_male_1": "Bello sconosciuto",
    "street.admirer_male_2": "Affascinante mascalzone",
    "street.admirer_male_3": "Uomo misterioso",
    "street.admirer_male_4": "Gentiluomo affascinante",
    "street.bounty_collected": "  *** TAGLIA RISCOSSA! +{0} oro ***",
    "street.grudge_steps_out": "  {0} emerge dalle ombre, pugni serrati...",
    "street.grudge_hesitates": "  ...poi ti vede bene e esita.",
    "street.grudge_thinks_better": "  Il livello {0} {1} ci ripensa e si dilegua tra la folla.",
    "street.grudge_self_preservation": "  (L'istinto di sopravvivenza prevale sul rancore — {0} livelli di differenza)",
    "street.murder_revenge_emerges": "  {0} emerge dalle ombre, ardente di furia.",
    "street.murder_revenge_quote_1": "  \"Credevi di potermi assassinare e farla franca?!\"",
    "street.murder_revenge_quote_2": "  \"Sono tornato dalla morte per QUESTO momento!\"",
    "street.murder_revenge_level_info": "  Livello {0} {1} — PV: {2}/{3} (INFEROCITO)",
    "street.murder_revenge_prompt": "\n  La tua risposta? ",
    "street.murder_revenge_flee_success": "\n  Sfuggi a malapena all'ira di {0}!",
    "street.murder_revenge_flee_fail": "\n  {0} ti taglia la via di fuga! \"Stavolta non scappi!\"",
    "street.murder_revenge_defeated": "\n  {0} cade di nuovo. Tanto per la vendetta.",
    "street.murder_revenge_lost_standing": "\n  {0} ti sovrasta, soddisfatto.",
    "street.murder_revenge_even": "  \"Adesso siamo pari. Ma non dimenticherò.\"",
    "street.murder_revenge_gold_taken": "  Ti prendono {0} monete d'oro.",
    "street.witness_steps_in": "  {0} ti si para davanti, con sguardo minaccioso.",
    "street.witness_saw_victim": "  \"Ho visto cosa hai fatto a {0}. La pagherai.\"",
    "street.witness_saw_murder": "  \"Ho visto cosa hai fatto. Assassino. La pagherai.\"",
    "street.witness_level_info": "  Livello {0} {1} — PV: {2}/{3}",
    "street.witness_fight_victory": "\n  {0} cade. Un testimone in meno.",
    "street.witness_fight_loss": "\n  {0} prende {1} monete d'oro. \"Giustizia è fatta.\"",
    "street.witness_bribe_success": "\n  {0} prende le {1} monete d'oro e distoglie lo sguardo.",
    "street.witness_bribe_memory": "  \"Non ho visto niente. Ma la memoria potrebbe tornarmi...\"",
    "street.witness_bribe_rejected": "\n  \"Credi che l'oro possa comprarmi il silenzio?!\" Prendono l'oro E attaccano!",
    "street.witness_bribe_no_gold": "\n  Non hai abbastanza oro! {0} attacca!",
    "street.witness_flee_success": "\n  Sgattaioli via da {0}. Per ora...",
    "street.witness_flee_fail": "\n  {0} ti acciuffa! \"Fuggire ti fa sembrare colpevole!\"",
    "street.grudge_waiting": "  {0} ti sta aspettando. Non sembra contento.",
    "street.grudge_quote": "  \"Credevi che avrei dimenticato cosa mi hai fatto? Ripensaci.\"",
    "street.grudge_level_info": "  Livello {0} {1} — PV: {2}/{3}",
    "street.grudge_fight_victory": "\n  {0} cade. Questione risolta.",
    "street.grudge_fight_loss": "\n  {0} prende {1} monete d'oro e se ne va soddisfatto.",
    "street.grudge_apology_success": "\n  {0} esita... poi abbassa i pugni.",
    "street.grudge_apology_accept": "  \"Va bene. Ma non provocarmi di nuovo.\"",
    "street.grudge_apology_fail": "\n  \"Le SCUSE non bastano!\"",
    "street.grudge_apology_attacks": "  {0} attacca con furia! (+15% FOR)",
    "street.grudge_bribe_accepted": "\n  {0} intasca le {1} monete d'oro.",
    "street.grudge_bribe_even": "  \"Siamo pari. Per ora.\"",
    "street.grudge_bribe_rejected": "\n  {0} prende l'oro E attacca!",
    "street.grudge_bribe_no_gold": "\n  Non hai abbastanza oro! {0} attacca!",
    "street.grudge_flee_success": "\n  Sgattaioli via prima che {0} possa reagire!",
    "street.grudge_flee_fail": "\n  {0} ti acciuffa! Colpisce per primo!",
    "street.spouse_storms": "  {0} ti marcia incontro, il volto contratto dalla rabbia...",
    "street.spouse_stops_short": "  ...poi si ferma di colpo, ricordando con chi ha a che fare.",
    "street.spouse_retreats": "  \"Non è finita,\" sibila, ritirandosi per trovare un altro modo.",
    "street.spouse_standing": "  {0} è in piedi davanti a te. Pugni serrati.",
    "street.spouse_knows": "  \"So cosa hai fatto con {0}.\"",
    "street.spouse_find_out": "  \"Credevi che non l'avrei scoperto?\"",
    "street.spouse_deny_success": "\n  \"Non so di cosa stai parlando. Siamo solo amici.\"",
    "street.spouse_uncertain": "  {0} sembra incerto e si calma.",
    "street.spouse_deny_fail": "\n  \"BUGIARDO! Ho visto come vi guardate!\"",
    "street.spouse_deny_attacks": "  {0} attacca in preda alla rabbia!",
    "street.spouse_admit": "\n  \"Hai ragione. Mi dispiace. Ho sbagliato.\"",
    "street.spouse_punch": "  {0} ti colpisce con un pugno! (-{1} PV)",
    "street.spouse_warning": "  \"Stai lontano da {0}. Questo è il tuo unico avvertimento.\"",
    "street.spouse_taunt": "\n  \"Forse se fossi un coniuge migliore, {0} non avrebbe bisogno di cercare altrove.\"",
    "street.spouse_fury": "  {0} RUGGISCE di furia! (+25% FOR)",
    "street.spouse_fight": "\n  \"Se è così che vuoi risolvere la cosa...\"",
    "street.throne_confronts": "  {0}, Livello {1} {2}, ti affronta.",
    "street.throne_quote": "  \"Il tuo tempo è scaduto. Prenderò quel trono.\"",
    "street.throne_prompt": "\n  Il vostro decreto, Maestà? ",
    "street.throne_accept": "\n  \"Accetto la tua sfida. Che sia l'acciaio a decidere!\"",
    "street.throne_victory": "\n  {0} cade! Sei ancora re.",
    "street.throne_imprisoned": "  {0} viene imprigionato per 7 giorni.",
    "street.throne_defeated": "\n  Sei sconfitto! {0} si impossessa del trono!",
    "street.throne_guards_order": "\n  \"Guardie! Togliete questo sciocco dalla mia vista!\"",
    "street.throne_guards_drag": "  Le tue guardie fedeli trascinano via {0}.",
    "street.throne_guards_hesitate": "\n  Le tue guardie esitano... la loro lealtà vacilla!",
    "street.throne_face_alone": "  Devi affrontare {0} da solo!",
    "street.throne_no_guards": "\n  Non hai guardie! Devi affrontare {0} da solo!",
    "street.throne_negotiate_offer": "\n  \"Forse c'è un ruolo per qualcuno del vostro talento nella mia corte.\"",
    "street.throne_negotiate_accept": "  {0} riflette... \"Un posto a corte? Potrebbe andare.\"",
    "street.throne_negotiate_refuse": "\n  \"Non voglio un POSTO. Voglio il TRONO!\"",
    "street.throne_negotiate_attacks": "  {0} attacca!",
    "street.throne_imprison_order": "\n  \"Prendetelo! 14 giorni nelle segrete per tradimento!\"",
    "street.throne_imprison_uneasy": "  {0} viene trascinato via. Le tue guardie si scambiano sguardi inquieti.",
    "street.throne_no_guards_imprison": "\n  Senza guardie, non puoi imprigionare nessuno!",
    "street.throne_laughs_attacks": "  {0} ride e attacca!",
    "street.turf_surround": "  Membri dei '{0}' ti circondano.",
    "street.turf_quote": "  {0}: \"Il dominio della tua squadra su questa città finisce ora!\"",
    "street.turf_fight_champion": "\n  \"Combatterò il vostro migliore. Fatevi avanti!\"",
    "street.turf_victory": "\n  {0} cade! I '{1}' si ritirano.",
    "street.turf_loss": "\n  I '{0}' esultano. Hai perso.",
    "street.turf_pay_gold": "\n  Consegni {0} monete d'oro.",
    "street.turf_pay_reply": "  {0}: \"Scelta saggia. Ti lasceremo in pace... per ora.\"",
    "street.turf_no_gold": "\n  Non hai abbastanza oro!",
    "street.turf_hard_way": "  {0}: \"Allora la risolviamo nel modo duro!\"",
    "street.turf_surrender": "\n  \"Va bene. Prendetelo. È vostro.\"",
    "street.turf_surrender_result": "  I '{0}' prendono il controllo della zona. La tua reputazione ne risente.",
    "street.turf_flee_success": "\n  Ti fai largo tra la folla e scappi!",
    "street.turf_flee_fail": "\n  Ti tagliano la via di fuga! {0} attacca!",
    "street.guard_royal_aid": "  Una guardia reale accorre in tuo aiuto!",
    "street.guard_royal_strike": "  La guardia colpisce {0} infliggendo {1} danni prima di essere respinta.",
    "street.guard_royal_wounded": "  {0} è ferito ma ancora in piedi. ({1}/{2} PV)",
    "street.murder_witnesses": "  {0} testimon{1} hanno visto l'omicidio!",
    "street.murder_witness_plural": "i",
    "street.murder_witness_singular": "e",
    "street.sanctioned_kill": "  (Uccisione autorizzata — la tua coscienza è pulita.)",
    "street.shadow_clean_job": "  (Lavoro pulito. Nessun testimone, nessun rimorso.)",
    "street.shadow_still_see": "  (Contratto o no, vedi ancora il loro volto...)",
    "street.faction_standing_drop": "  La tua reputazione con {0} è crollata drasticamente!",
    "street.backstab_assassin": "  Il tuo addestramento da assassino ti dona un primo colpo devastante! (-{0}% PV nemici)",
    "street.backstab_generic": "  Li cogli di sorpresa! (-{0}% PV nemici)",
    "street.merchant_desc_poison": "Avvelena la tua arma per il prossimo combattimento",
    "street.merchant_desc_smoke": "Fuga garantita dal prossimo combattimento",
    "street.merchant_desc_heal3": "Tre pozioni curative a prezzo scontato",
    "street.merchant_desc_dark_tonic": "Ripristina il {0}% dei tuoi PV massimi adesso",
    "street.merchant_desc_heal1": "+1 pozione curativa",
    "street.merchant_desc_heal5": "Cinque pozioni — compra all'ingrosso e risparmia!",
    "street.merchant_desc_antidote": "Cura immediatamente il veleno",
    "street.merchant_desc_elixir": "Ripristina il {0}% dei tuoi PV massimi adesso",
    "street.merchant_name_poison": "Fiala di veleno",
    "street.merchant_name_smoke": "Bomba fumogena",
    "street.merchant_name_heal3": "Pozioni curative (x3)",
    "street.merchant_name_dark_tonic": "Tonico oscuro",
    "street.merchant_name_heal1": "Pozione curativa",
    "street.merchant_name_heal5": "Pozioni curative (x5)",
    "street.merchant_name_antidote": "Antidoto",
    "street.merchant_name_elixir": "Elisir corroborante",
    "engine.welcome": "Benvenuto, {0}!",
    "engine.immortal_tag": " [IMMORTALE]",
    "engine.char_slot": "  [{0}] {1} — Livello {2} {3}{4}",
    "engine.last_played": "      Ultima partita: {0}",
    "engine.menu_play": "Gioca {0}",
    "engine.menu_new_char": "Nuovo personaggio",
    "engine.menu_new_overwrite": "Nuovo (Sovrascrive!)",
    "engine.menu_create_alt": "Crea alternativo",
    "engine.menu_delete_alt": "Elimina alternativo",
    "engine.menu_online": "Multigiocatore online",
    "engine.menu_story": "Trama",
    "engine.menu_history": "Storia di Usurper",
    "engine.menu_bbs_list": "Lista BBS",
    "engine.menu_credits": "Riconoscimenti",
    "engine.menu_sr_on": "Lettore schermo: ON",
    "engine.menu_sr_off": "Lettore schermo: OFF",
    "engine.menu_compact_on": "Compatto: ON",
    "engine.menu_compact_off": "Compatto: OFF",
    "engine.menu_spectate": "Osserva",
    "engine.menu_password": "Password",
    "engine.menu_sysop": "SysOp",
    "engine.menu_admin": "Admin",
    "engine.menu_support": "Supporto",
    "engine.menu_quit": "Esci",
    "engine.menu_create_mortal_alt": "Crea personaggio alternativo mortale",
    "engine.menu_delete_alt_full": "Elimina personaggio alternativo",
    "engine.menu_create_new": "Crea nuovo personaggio",
    "engine.menu_new_overwrite_full": "Nuovo personaggio (ATTENZIONE: Sovrascrive il principale!)",
    "engine.menu_online_full": "Multigiocatore online - Mondo condiviso",
    "engine.menu_story_full": "La storia finora...",
    "engine.menu_history_full": "Storia di Usurper",
    "engine.menu_bbs_full": "Lista BBS e server online",
    "engine.menu_support_full": "Supporta lo sviluppatore",
    "engine.menu_spectate_full": "Osserva un giocatore",
    "engine.menu_change_password": "Cambia password",
    "engine.menu_sysop_console": "Console SysOp",
    "engine.menu_admin_console": "Console Admin",
    "engine.section_play": "  GIOCA",
    "engine.section_info": "  INFO",
    "engine.section_accessibility": "  ACCESSIBILITÀ",
    "engine.immortal_required": "  Devi essere un immortale per creare un personaggio alternativo.",
    "engine.delete_main_warning": "ATTENZIONE: Questo ELIMINERÀ il tuo personaggio principale!",
    "engine.delete_alt_unaffected": "Il tuo personaggio alternativo NON sarà toccato.",
    "engine.delete_confirm_prompt": "Digita 'DELETE' per confermare: ",
    "engine.delete_cancelled": "Eliminazione personaggio annullata.",
    "engine.sr_enabled": "Modalità lettore schermo ATTIVATA",
    "engine.sr_enabled_desc": "I menu useranno un formato di testo semplificato.",
    "engine.sr_disabled": "Modalità lettore schermo DISATTIVATA",
    "engine.sr_disabled_desc": "I menu useranno il formato grafico ASCII.",
    "engine.compact_enabled": "Modalità compatta ATTIVATA",
    "engine.compact_enabled_desc": "Menu ottimizzati per dispositivi mobili e schermi piccoli.",
    "engine.compact_disabled": "Modalità compatta DISATTIVATA",
    "engine.compact_disabled_desc": "Menu a dimensione piena ripristinati.",
    "engine.goodbye": "Addio! Alla prossima...",
    "engine.delete_alt_warning": "  ATTENZIONE: Questo eliminerà permanentemente {0}!",
    "engine.delete_alt_confirm": "  Digita 'DELETE' per confermare: ",
    "engine.delete_alt_done": "  {0} è stato eliminato.",
    "engine.delete_alt_cancelled": "  Eliminazione annullata.",
    "engine.title": "USURPER REBORN - Sale dell'Avarizia",
    "engine.title_version": "v{0} \"{1}\"",
    "engine.title_original": "1993 - Originale di Jakob Dangarden",
    "engine.title_reborn": "2025 - Rinato per mano di Jason Knight",
    "engine.alpha_compact": "  [!] ALPHA - Bug previsti. I dati potrebbero essere cancellati. /bug per segnalare.",
    "engine.alpha_sr": "  BUILD ALPHA - Aspettati bug, problemi di bilanciamento e contenuti mancanti.",
    "engine.alpha_wipe": "  I dati dei personaggi potrebbero essere cancellati in qualsiasi momento (reset completo previsto per la Beta).",
    "engine.alpha_report": "  Segnala i bug tramite /bug nel gioco o unisciti al nostro Discord:",
    "engine.alpha_box_title": "[!] BUILD ALPHA - Aspettati bug, problemi di bilanciamento e contenuti mancanti. [!]",
    "engine.alpha_box_wipe": "I dati dei personaggi potrebbero essere cancellati (reset completo alla Beta).  ",
    "engine.alpha_box_report": "Segnala i bug tramite /bug nel gioco o unisciti al nostro Discord:             ",
    "engine.main_title_sr": "  USURPER REBORN - Sale dell'Avarizia",
    "engine.main_single_player": "Giocatore singolo",
    "engine.main_online_sr": "  O. Multigiocatore online, Mondo condiviso",
    "engine.main_story_sr": "  I. La storia finora",
    "engine.main_history_sr": "  H. Storia di Usurper",
    "engine.main_bbs_sr": "  B. Lista BBS e server online",
    "engine.main_credits_sr": "  C. Riconoscimenti",
    "engine.main_support_sr": "  @. Supporta lo sviluppatore",
    "engine.main_sr_on": "  A. Lettore schermo: ON",
    "engine.main_compact_on_sr": "  Z. Modalità compatta: ON",
    "engine.main_compact_off_sr": "  Z. Modalità compatta: OFF",
    "engine.main_font_sr": "  F. Font terminale: {0}",
    "engine.main_quit_sr": "  Q. Esci",
    "engine.main_sysop_sr": "  %. Console SysOp",
    "engine.main_sr_off_visual": "Lettore schermo: OFF",
    "engine.main_compact_on_visual": "Modalità compatta: ON (Mobile/Schermo piccolo)",
    "engine.main_compact_off_visual": "Modalità compatta: OFF",
    "engine.main_font_visual": "Font terminale: {0}",
    "engine.font_set": "Font del terminale impostato su: {0}",
    "engine.font_update": "  Il font si aggiornerà nel terminale a breve.",
    "engine.admin_requires_online": "La console admin richiede la modalità online con backend SQL.",
    "engine.password_requires_online": "Il cambio password richiede la modalità online.",
    "engine.change_password_title": "CAMBIA PASSWORD",
    "engine.change_password_title_visual": "═══ CAMBIA PASSWORD ═══",
    "engine.no_username": "Nessun nome utente trovato.",
    "engine.account_label": "Account: {0}",
    "engine.current_password_prompt": "Password attuale: ",
    "engine.new_password_prompt": "Nuova password (min 4 caratteri): ",
    "engine.password_min_length": "La password deve essere di almeno 4 caratteri.",
    "engine.confirm_password_prompt": "Conferma nuova password: ",
    "engine.passwords_no_match": "Le password non corrispondono.",
    "engine.spectator_title": "Modalità spettatore",
    "engine.no_players_to_watch": "  Nessun giocatore è attualmente in partita da osservare.",
    "engine.players_to_watch": "  Giocatori disponibili da osservare:",
    "engine.watching_count": " ({0} stanno guardando)",
    "engine.spectator_consent": "  Il giocatore selezionato deve accettare la tua richiesta prima che tu possa osservare.",
    "engine.spectator_select": "  Seleziona giocatore # (o Q per annullare): ",
    "engine.spectator_invalid": "  Selezione non valida.",
    "engine.spectator_pending": "  Quel giocatore ha già una richiesta in sospeso. Riprova più tardi.",
    "engine.spectator_sent": "  Richiesta di osservazione inviata a {0}.",
    "engine.spectator_waiting": "  In attesa della risposta (timeout 60 secondi)...",
    "engine.spectator_denied": "  Richiesta negata o scaduta.",
    "engine.spectator_accepted": "  {0} ha accettato la tua richiesta!",
    "engine.spectating_label": "  OSSERVANDO: {0}",
    "engine.spectator_quit_hint": "  Digita Q + Invio per smettere di guardare.",
    "engine.spectator_disconnected": "  Il giocatore che stavi osservando si è disconnesso.",
    "engine.spectator_ended": "  Modalità spettatore terminata.",
    "engine.save_management_title": "GESTIONE SALVATAGGI",
    "engine.no_saves_found": "Nessun salvataggio trovato.",
    "engine.create_character_prompt": "Creiamo un nuovo personaggio!",
    "engine.existing_saves": "Slot di salvataggio esistenti:",
    "engine.new_character": "Nuovo personaggio",
    "engine.back_to_menu": "Torna al menu principale",
    "engine.select_save_prompt": "Seleziona slot o opzione: ",
    "engine.enter_name_prompt": "Inserisci il nome del nuovo personaggio: ",
    "engine.name_exists": "Quel nome esiste già! Scegli un nome diverso.",
    "engine.invalid_choice": "Scelta non valida!",
    "engine.save_slots_for": "Slot di salvataggio per: {0}",
    "engine.no_saves_for_char": "Nessun salvataggio trovato per questo personaggio.",
    "engine.available_saves": "Salvataggi disponibili:",
    "engine.save_detail": " - Giorno {0}, Livello {1}, {2} turni",
    "engine.delete_all_saves": "Elimina questo personaggio (tutti i salvataggi)",
    "engine.back": "Indietro",
    "engine.select_save_load": "Seleziona salvataggio da caricare: ",
    "engine.delete_saves_confirm": "Eliminare TUTTI i salvataggi di '{0}'? Digita 'DELETE' per confermare: ",
    "engine.all_saves_deleted": "Tutti i salvataggi eliminati.",
    "engine.loading_save": "Caricamento salvataggio...",
    "engine.load_failed": "Impossibile caricare il salvataggio!",
    "engine.load_corrupted": "Il file di salvataggio potrebbe essere corrotto o non valido.",
    "engine.starting_new_instead": "Creazione nuovo personaggio in corso...",
    "engine.missing_player_data": "Dati del giocatore mancanti nel salvataggio!",
    "engine.restoring_player": "Ripristino di {0}...",
    "engine.restore_failed": "Impossibile ripristinare i dati del giocatore!",
    "engine.team_no_longer_exists": "La tua squadra '{0}' non esiste più. Sei stato rimosso.",
    "engine.save_loaded": "Salvataggio caricato con successo!",
    "engine.session_incomplete": "La sessione precedente si è interrotta prima del completamento del ciclo.",
    "engine.session_resuming": "Ripresa da dove eri rimasto...",
    "engine.error_loading": "Errore nel caricamento: {0}",
    "engine.load_game_failed": "Impossibile caricare il salvataggio!",
    "engine.game_loaded": "Partita caricata con successo! Giorno {0}, {1} turni rimanenti",
    "engine.new_game_saved": "Nuova partita salvata con successo!",
    "engine.save_warning": "Attenzione: Impossibile salvare la partita!",
    "engine.world_stirs": "Il mondo si agita con fervore...",
    "engine.history_written": "La storia è stata scritta. La tua avventura ha inizio!",
    "engine.not_allowed": "Non ti è permesso giocare oggi!",
    "engine.turns_used": "Hai esaurito tutti i turni di oggi! ({0} rimasti)",
    "engine.save_failed": "Impossibile salvare la partita!",
    "engine.creation_cancelled": "Creazione personaggio annullata.",
    "engine.must_create": "Devi creare un personaggio per giocare a Usurper.",
    "engine.retry_prompt": "Vuoi riprovare? (S/N): ",
    "engine.creation_aborted": "Creazione personaggio interrotta dall'utente.",
    "engine.creation_error": "Si è verificato un errore durante la creazione del personaggio: {0}",
    "engine.please_try_again": "Riprova.",
    "engine.you_have_died": "SEI MORTO!",
    "engine.death_vision": "La vista ti si offusca mentre la morte ti reclama...",
    "engine.resurrections_available": "Hai {0} resurrezione/i disponibile/i!",
    "engine.use_resurrection_prompt": "Usare una resurrezione per evitare le penalità? (S/N): ",
    "engine.divine_light": "Una luce divina ti avvolge!",
    "engine.resurrected_no_penalty": "Sei stato resuscitato completamente senza penalità!",
    "engine.death_penalties": "Penalità di morte applicate:",
    "engine.lost_exp": "  - Persi {0} punti esperienza",
    "engine.lost_gold": "  - Persi {0} monete d'oro (cadute alla morte)",
    "engine.monster_defeats": "  - Mostri sconfitti: {0}",
    "engine.wake_at_inn": "Ti risvegli alla Locanda, curato dal locandiere.",
    "engine.wounds_healed": "Le tue ferite sono parzialmente guarite. (PV: {0}/{1})",
    "engine.innkeeper_quote": "\"Sei fortunato ad essere vivo, amico. Riposati e riprova.\"",
    "engine.adventure_continues": "La tua avventura continua...",
    "engine.in_prison": "Sei in PRIGIONE!",
    "engine.days_remaining": "Giorni rimanenti: {0}",
    "engine.prison_wait": "1. Aspetta",
    "engine.prison_escape": "2. Tenta la fuga",
    "engine.prison_quit": "3. Esci",
    "engine.wait_patiently": "Aspetti pazientemente...",
    "engine.attempt_escape": "Tenti la fuga...",
    "engine.escape_success": "Riesci a fuggire!",
    "engine.escape_caught": "Sei stato sorpreso a fuggire!",
    "engine.save_not_completed": "Attenzione: Il salvataggio potrebbe non essere completato.",
    "engine.save_error": "Errore di salvataggio: {0}",
    "engine.sleep_inn": "STANZA DELLA LOCANDA",
    "engine.sleep_home": "CASA",
    "engine.sleep_castle": "CASTELLO",
    "engine.sleep_dormitory": "DORMITORIO",
    "engine.sleep_report_title": "RAPPORTO DEL SONNO  ({0})",
    "engine.guard_fought_off": "  La tua {0} ha respinto {1}!",
    "engine.guard_defeated": "  La tua {0} è stata sconfitta da {1}!",
    "engine.attacker_won": "  {0} ti ha attaccato nel sonno e ha vinto!",
    "engine.gold_stolen": "  Ti hanno rubato {0} monete d'oro!",
    "engine.item_stolen": "  Ti hanno rubato il tuo {0}!",
    "engine.xp_lost": "  Hai perso {0} esperienza!",
    "engine.defender_won": "  {0} ha cercato di attaccarti nel sonno ma li hai respinti!",
    "engine.guards_repelled": "  Le tue guardie hanno scacciato {0}!",
    "engine.killed_sleeping": "  Sei stato UCCISO nel sonno!",
    "engine.wake_temple": "  Ti svegli al Tempio, coperto di lividi e derubato.",
    "engine.survived_night": "  Sei sopravvissuto alla notte.",
    "engine.while_you_were_gone": "MENTRE ERI VIA",
    "engine.arena_attacks": "  -- Attacchi nell'Arena --",
    "engine.pvp_shadow_won": "  * {0} ti ha attaccato ma la tua ombra li ha sconfitti!{1}",
    "engine.pvp_you_gained_gold": " Hai guadagnato {0} monete d'oro.",
    "engine.pvp_attacker_won": "  * {0} ti ha attaccato e ha vinto!{1}",
    "engine.pvp_they_stole_gold": " Ti hanno rubato {0} del tuo oro.",
    "engine.messages_section": "  -- Messaggi ({0} non letti) --",
    "engine.read_mailbox": "  Digita /mail per leggere la tua casella completa.",
    "engine.mail_section": "  -- Posta ({0} non letta) --",
    "engine.read_mail": "  Digita /mail per leggere la tua casella.",
    "engine.trade_section": "  -- Pacchi commerciali ({0} in attesa) --",
    "engine.trade_waiting": "  Hai {0} pacc{1} in attesa!",
    "engine.trade_hint": "  Digita /trade per visualizzare e accettare.",
    "engine.world_news": "  -- Notizie dal mondo --",
    "engine.support_title": "SUPPORTA USURPER REBORN",
    "engine.support_desc_1": "  Usurper Reborn è un gioco gratuito e open-source rilasciato sotto licenza",
    "engine.support_desc_2": "  GPL v2. È sviluppato da un singolo sviluppatore nel suo tempo libero come",
    "engine.support_desc_3": "  omaggio ai classici giochi BBS door dei primi anni '90.",
    "engine.support_how_sr": "  Come puoi aiutare",
    "engine.support_how_visual": "  ─── Come puoi aiutare ───",
    "engine.support_sponsor": "  Sponsorizza lo sviluppatore",
    "engine.support_sponsor_desc": "  Se ti piace il gioco e vuoi supportarne lo",
    "engine.support_sponsor_desc2": "  sviluppo continuo, considera una sponsorizzazione su GitHub:",
    "engine.support_star": "  Metti una stella al repository",
    "engine.support_star_desc": "   Se non vuoi donare, va benissimo!",
    "engine.support_star_desc2": "  Una stella sul repo GitHub aiuta molto e permette ad altri",
    "engine.support_star_desc3": "  di scoprire il gioco:",
    "engine.support_steam": "  Compra su Steam",
    "engine.support_steam_desc": "           Quando il gioco sarà lanciato su Steam nel marzo 2026,",
    "engine.support_steam_desc2": "  acquistare una copia è un altro ottimo modo per mostrare il tuo supporto.",
    "engine.support_thanks_1": "  Grazie per giocare. Ogni forma di supporto — che sia una sponsorizzazione,",
    "engine.support_thanks_2": "  una stella, una segnalazione bug, o semplicemente giocare — significa tantissimo.",
    "engine.bbs_list_title": "LISTA BBS - Gioca a Usurper Reborn online!",
    "engine.bbs_list_desc_1": "  Le seguenti BBS hanno Usurper Reborn come gioco door.",
    "engine.bbs_list_desc_2": "  Connettiti via telnet o SSH per giocare online!",
    "engine.bbs_list_header": "  Nome BBS                        Software    Indirizzo",
    "engine.bbs_sysop_question": "  Sei un SysOp che gestisce Usurper Reborn sulla tua BBS?",
    "engine.bbs_get_listed": "  Fatti aggiungere qui! Apri una issue o discussione su:",
    "engine.bbs_include_info": "  Includi il nome della tua BBS, indirizzo e software. Saremo felici di aggiungerti!",
    "engine.press_enter_return": "[Premi Invio per tornare]",
    "engine.credits_title": "RICONOSCIMENTI",
    "engine.credits_subtitle": "USURPER REBORN",
    "engine.credits_tagline": "Un tributo moderno a un classico",
    "engine.credits_original_game": "  Gioco originale:",
    "engine.credits_original_name": "    Usurper: Halls of Avarice (1993)",
    "engine.credits_original_creators": "  CREATORI ORIGINALI:",
    "engine.credits_jakob": "    Jakob Dangarden          - Creatore del gioco originale (1993)",
    "engine.credits_rick": "    Rick Parrish             - Preservazione e porting del codice sorgente",
    "engine.credits_daniel": "    Daniel Zingaro           - Correzione bug e qualità del codice",
    "engine.credits_reborn": "  USURPER REBORN:",
    "engine.credits_jason": "    Jason Knight             - Creatore di Usurper Reborn",
    "engine.credits_built_with": "    Sviluppato con C# / .NET 8.0",
    "engine.credits_ansi_art": "  ARTE ANSI:",
    "engine.credits_xbit": "    xbit (x-bit.org)          - Arte ritratti di razze e classi",
    "engine.credits_sudden_death": "    Sudden Death              - Strumento di conversione ANSI rez2ans",
    "engine.credits_cozmo": "    Cozmo / Lunatics Unleashed - Conoscenza e guida arte ANSI",
    "engine.credits_contributors": "  COLLABORATORI:",
    "engine.credits_fastfinge": "    fastfinge                 - Contributi al codice",
    "engine.credits_special_thanks": "  RINGRAZIAMENTI SPECIALI:",
    "engine.credits_bbs_community": "    La comunità BBS degli anni '80 e '90",
    "engine.credits_sysops": "    Tutti i SysOp che hanno mantenuto attive le board",
    "engine.credits_players": "    Ogni giocatore che si è collegato per esplorare Durunghins",
    "engine.credits_wiki": "    Il wiki Break Into Chat per aver preservato la storia delle BBS",
    "engine.credits_license": "  LICENZA:",
    "engine.credits_license_1": "    L'Usurper originale è stato rilasciato sotto GNU GPL",
    "engine.credits_license_2": "    Questo remake onora quella tradizione open source",
    "engine.credits_community": "  COMUNITÀ:",
    "engine.credits_discord": "    Unisciti a noi su Discord: https://discord.gg/EZhwgDT6Ta",
    "engine.story_title": "LA STORIA FINORA...",
    "engine.story_golden_age": "~ L'Età dell'Oro ~",
    "engine.story_golden_1": "  Tanto tempo fa, in un'era ormai persa nella memoria, il mondo era vegliato dai",
    "engine.story_golden_2": "  Sette Divini - dèi di immenso potere che guidavano i mortali con saggezza e",
    "engine.story_golden_3": "  grazia. Sotto il loro benevolo sguardo, le civiltà fiorirono. Il dio della",
    "engine.story_golden_4": "  guerra insegnava l'onore in battaglia. La dea dell'amore benediceva ogni unione.",
    "engine.story_golden_5": "  Il dio della luce faceva sì che la verità prevalesse sull'inganno.",
    "engine.story_golden_6": "  Era un'era di miracoli. Un'era di eroi. Un'era di speranza.",
    "engine.story_sundering": "~ La Frattura ~",
    "engine.story_sundering_1": "  Poi venne la Frattura - un cataclisma la cui causa resta ignota. C'è chi dice",
    "engine.story_sundering_2": "  che i mortali divennero troppo superbi e voltarono le spalle agli dèi. Altri",
    "engine.story_sundering_3": "  sussurrano di un tradimento tra i Divini stessi. Qualunque sia la verità, il",
    "engine.story_sundering_4": "  risultato fu catastrofico.",
    "engine.story_sundering_5": "  I Sette furono corrotti. Distorti. Imprigionati in reami da loro stessi creati.",
    "engine.story_sundering_6": "  Il dio della guerra divenne la rabbia incarnata, annegando in un massacro",
    "engine.story_sundering_7": "  senza fine. La dea dell'amore avvizzì in gelosia e ossessione. Il dio della",
    "engine.story_sundering_8": "  luce si affievolì fino a un sussurro, la verità morendo con ogni menzogna.",
    "engine.story_avarice": "~ L'Era dell'Avarizia ~",
    "engine.story_avarice_1": "  Secoli sono passati. I Vecchi Dèi sono ormai mere leggende - racconti",
    "engine.story_avarice_2": "  ammonitori per spaventare i bambini. In loro assenza, i mortali hanno creato",
    "engine.story_avarice_3": "  nuovi dèi da adorare, pallidi echi dei Divini che furono.",
    "engine.story_avarice_4": "  E in questa era senza dèi, un nuovo potere è sorto: L'AVARIZIA.",
    "engine.story_avarice_5": "  Le Sale dell'Avarizia - un vasto complesso sotterraneo dove gli avventurieri",
    "engine.story_avarice_6": "  cercano fortuna, gloria e potere. Dove i forti predano i deboli. Dove",
    "engine.story_avarice_7": "  l'oro è l'unico dio che conta.",
    "engine.story_avarice_8": "  Alcuni vengono in cerca di tesori. Alcuni in cerca di fama. Alcuni per",
    "engine.story_avarice_9": "  sfuggire al passato. E altri... altri sentono sussurri nel buio. Voci",
    "engine.story_avarice_10": "  antiche che chiamano dalle profondità. Che promettono potere. Che esigono sacrifici.",
    "engine.story_begins": "~ La tua storia ha inizio ~",
    "engine.story_begins_1": "  Arrivi alle porte del reame con poco più degli abiti che indossi e una",
    "engine.story_begins_2": "  fame di qualcosa di più. La vivace Via Principale ti attende, piena di",
    "engine.story_begins_3": "  negozi, taverne e opportunità per chi è abbastanza audace da",
    "engine.story_begins_4": "  afferrarle.",
    "engine.story_begins_5": "  Ti avventurerai nei mortali Sotterranei in cerca di tesori e gloria?",
    "engine.story_begins_6": "  Troverai l'amore sui ciottoli di questa pericolosa città?",
    "engine.story_begins_7": "  Ti eleverai a campione... o cadrai diventando un racconto ammonitore?",
    "engine.story_begins_8": "  E forse, se diventerai abbastanza forte, potresti scoprire cosa si cela",
    "engine.story_begins_9": "  davvero nelle sale più profonde. Potresti scoprire il destino dei Vecchi Dèi.",
    "engine.story_begins_10": "  Potresti persino avere l'occasione di salvarli... o distruggerli per sempre.",
    "engine.story_begins_11": "  La scelta, avventuriero, è tua.",
    "engine.press_enter": "[Premi Invio]",
    "engine.telemetry_title": "AIUTA A MIGLIORARE USURPER REBORN",
    "engine.telemetry_desc_1": "Durante questa fase di test alpha, possiamo raccogliere statistiche",
    "engine.telemetry_desc_2": "anonime di gioco per migliorare il bilanciamento e individuare bug.",
    "engine.telemetry_collect": "Cosa raccogliamo:",
    "engine.telemetry_collect_1": "  - Statistiche di combattimento (vittorie, sconfitte, danni inflitti)",
    "engine.telemetry_collect_2": "  - Traguardi del giocatore (salite di livello, boss sconfitti)",
    "engine.telemetry_collect_3": "  - Uso delle funzionalità (quali aree visiti di più)",
    "engine.telemetry_collect_4": "  - Errori e crash",
    "engine.telemetry_not_collect": "Cosa NON raccogliamo:",
    "engine.telemetry_not_1": "  - Il tuo vero nome o informazioni identificative",
    "engine.telemetry_not_2": "  - Il tuo indirizzo IP",
    "engine.telemetry_not_3": "  - Messaggi di chat o testo personalizzato",
    "engine.telemetry_disable_hint": "Puoi disattivare questa funzione in qualsiasi momento dal menu Impostazioni.",
    "engine.telemetry_prompt": "Vuoi aiutarci a migliorare il gioco? [S/N]: ",
    "engine.telemetry_thanks": "Grazie! Il tuo feedback aiuterà a rendere Usurper Reborn migliore.",
    "engine.telemetry_declined": "Nessun problema! Puoi attivare la telemetria più tardi nelle Impostazioni.",
    "engine.turns_label": "Turni: {0}",
    "street_encounter.hostile.title": "INCONTRO OSTILE!",
    "street_encounter.hostile.blocks_path": "{0} ti blocca il passaggio per strada!",
    "street_encounter.hostile.opt_fight": "ombatti",
    "street_encounter.hostile.opt_talk": "arla",
    "street_encounter.hostile.opt_bribe": "orrompi",
    "street_encounter.pickpocket.title": "BORSEGGIATORE!",
    "street_encounter.pickpocket.feel_hand": "Senti una mano nella tasca! Un ladro dalle dita svelte sta cercando di derubarti!",
    "street_encounter.pickpocket.opt_grab": "fferralo",
    "street_encounter.pickpocket.opt_shout": "hiama le guardie",
    "street_encounter.pickpocket.opt_ignore": "gnora",
    "street_encounter.brawl.title": "RISSA DI STRADA!",
    "street_encounter.brawl.reason_ale": "\"Ti sei bevuto l'ultima birra!\" Un avventore furioso ti spinge!",
    "street_encounter.brawl.reason_dice": "\"Hai barato ai dadi!\" Un giocatore rovescia il tavolo!",
    "street_encounter.brawl.reason_insult": "\"Mi hai guardato male!\" grida uno sconosciuto arrabbiato!",
    "street_encounter.brawl.reason_bar_fight": "Una rissa da taverna si riversa in strada - e tu sei nel mezzo!",
    "street_encounter.brawl.reason_mercenary": "Un mercenario annoiato cerca guai - e ha trovato te!",
    "street_encounter.brawl.reason_seat": "\"Quello è il MIO posto!\" Qualcuno ti spinge violentemente da dietro!",
    "street_encounter.brawl.opt_fight": "ombatti",
    "street_encounter.brawl.opt_duck": "chiva e scarta",
    "street_encounter.brawl.opt_buy_drink": "ffrì da bere",
    "street_encounter.brawl.squares_up": "{0} si mette in guardia, pugni alzati!",
    "street_encounter.brawl.duck_escape": "Ti abbassi schivando un pugno e scivoli via tra la folla!",
    "street_encounter.brawl.msg_escaped": "Sfuggito alla rissa illeso.",
    "street_encounter.brawl.hit_by_mug": "Un boccale lanciato ti colpisce in testa mentre cerchi di scappare!",
    "street_encounter.brawl.msg_hit_escaping": "Colpito durante la fuga dalla rissa.",
    "street_encounter.brawl.buy_round": "Offri un giro di bevute per tutti!",
    "street_encounter.brawl.toast_health": "\"Alla tua salute!\" L'avventore arrabbiato si calma e alza il boccale.",
    "street_encounter.brawl.msg_bought_drinks": "Offerto da bere per calmare la situazione.",
    "street_encounter.brawl.not_enough_gold": "Non hai abbastanza oro per le bevute! Il rissoso attacca!",
    "street_encounter.challenge.title": "SFIDA FORMALE!",
    "street_encounter.challenge.walks_up": "{0} ti si avvicina con passo sicuro.",
    "street_encounter.challenge.info": "\"{0} il {1}, ti sfido a un duello d'onore!\"",
    "street_encounter.challenge.opt_accept": "ccetta",
    "street_encounter.challenge.opt_decline": "eclina",
    "street_encounter.mugging.title": "RAPINA!",
    "street_encounter.mugging.thugs_emerge": "{0} teppisti emergono dalle ombre!",
    "street_encounter.mugging.opt_surrender": "onsegna l'oro",
    "street_encounter.mugging.opt_run": "uggi",
    "street_encounter.gang.title": "SCONTRO CON BANDA!",
    "street_encounter.gang.block_path": "Un gruppo di {0} membri della banda blocca la strada!",
    "street_encounter.romance.title": "INCONTRO ROMANTICO",
    "street_encounter.romance.approaches": "{0} ti si avvicina con un sorriso caloroso.",
    "street_encounter.romance.opt_flirt": "lirta",
    "street_encounter.merchant.title": "MERCANTE DI STRADA",
    "street_encounter.merchant.not_enough_gold": "Non hai abbastanza oro!",
    "street_encounter.beggar.title": "MENDICANTE DI STRADA",
    "street_encounter.beggar.spare_coins": "\"Per favore, qualche moneta? Non mangio da giorni...\"",
    "street_encounter.beggar.opt_give": "ai dell'oro",
    "street_encounter.beggar.opt_rob": "apina",
    "street_encounter.rumor.title": "VOCI DI STRADA",
    "street_encounter.rumor.overhear": "Cogli una conversazione interessante...",
    "street_encounter.guard.title": "PATTUGLIA DI GUARDIE!",
    "street_encounter.guard.opt_surrender": "rrenditi",
    "street_encounter.guard.opt_bribe": "orrompi",
    "street_encounter.ambush.title": "IMBOSCATA!",
    "street_encounter.ambush.assassin_appears": "Un assassino si cala dai tetti!",
    "street_encounter.ambush.first_strike": "Colpisce prima che tu possa reagire! (-{0} PV)",
    "street_encounter.ambush.victory_note": "Trovi un biglietto: \"Contratto su {0}. Compenso: {1}o.\"",
    "street_encounter.flee.try_run": "Cerchi di fuggire...",
    "street_encounter.bribe.offer": "Offri una bustarella di {0} monete d'oro.",
    "street_encounter.talk.try_reason": "Cerchi di ragionare con loro...",
    "street_encounter.attack.title": "COMBATTIMENTO!",
    "street_encounter.attack.you_attack": "Attacchi {0}!",
    "street_encounter.grudge.self_preservation": "{0} pensa di affrontarti ma ci ripensa — l'istinto di sopravvivenza prevale.",
    "street_encounter.grudge.murder_revenge_title": "VENDETTA OMICIDA!",
    "street_encounter.grudge.opt_fight": "Combatti",
    "street_encounter.grudge.opt_run": "Fuggi",
    "street_encounter.grudge.opt_apologize": "Scusati",
    "street_encounter.grudge.standard_title": "REGOLAMENTO DI CONTI!",
    "street_encounter.grudge.your_response": "La tua risposta: ",
    "street_encounter.spouse.title": "CONIUGE GELOSO!",
    "street_encounter.spouse.opt_deny": "Nega tutto",
    "street_encounter.spouse.opt_admit": "Ammetti e scusati",
    "street_encounter.spouse.opt_taunt": "Provocalo",
    "street_encounter.throne.title": "SFIDA AL TRONO!",
    "street_encounter.throne.opt_accept": "Accetta la sfida",
    "street_encounter.throne.opt_dismiss": "Congedalo",
    "street_encounter.throne.opt_negotiate": "Negozia",
    "street_encounter.throne.opt_imprison": "Fallo imprigionare",
    "street_encounter.turf.title": "GUERRA DI TERRITORIO!",
    "street_encounter.turf.opt_fight": "Combatti per il controllo",
    "street_encounter.turf.opt_pay": "Paga il tributo ({0}o)",
    "street_encounter.turf.opt_surrender": "Cedi il territorio",
    "street_encounter.turf.surrender": "La tua squadra cede il controllo della zona. Una sconfitta umiliante.",
    "street_encounter.murder.witnesses": "{0} testimoni hanno visto l'omicidio!",
    "street_encounter.murder.sanctioned": "L'uccisione era autorizzata. Nessuna conseguenza legale.",
    "street_encounter.murder.faction_drop": "  La tua reputazione con {0} è crollata drasticamente!",
    "engine.save_slot_sr_display": "{0}. {1} ({2}) - Livello {3} | {4} | {5}",
    "engine.save_slot_level": " - Livello {0}",
    "engine.main_title_box": "USURPER REBORN",
    "engine.main_subtitle_box": " - Sale dell'Avarizia",
    "engine.section_play_visual": "  ── GIOCA ",
    "engine.section_info_visual": "  ── INFO ",
    "engine.section_accessibility_visual": "  ── ACCESSIBILITÀ ",
    "engine.bbs_entry_header": "  Nome BBS                         Software    Indirizzo",
    "engine.save_complete": "Partita salvata!",
    "engine.load_complete": "Partita caricata!",
    "engine.autosave": "Salvataggio automatico...",
    "engine.welcome_back": "Bentornato, {0}!",
    "engine.new_game_created": "Nuova partita creata!",
    "engine.confirm_quit": "Sei sicuro di voler uscire? (S/N): ",
    "street_encounter.hostile.opt_run": "uggi",
    "street_encounter.hostile.stats": "  {0} - Livello {1} {2} (PV: {3}/{4})",
    "street_encounter.pickpocket.grab_thief": "  Afferri il ladro — è {0}!",
    "street_encounter.pickpocket.shout_guards": "  Gridi per chiamare le guardie!",
    "street_encounter.pickpocket.thief_flees": "  Il ladro fugge tra la folla!",
    "street_encounter.pickpocket.msg_scared_away": "Spaventato un borseggiatore.",
    "street_encounter.pickpocket.pretend_not_notice": "  Fingi di non accorgerti e prosegui.",
    "street_encounter.pickpocket.msg_avoided": "Evitato un incontro con un borseggiatore.",
    "street_encounter.pickpocket.bumps_into": "  Qualcuno ti urta tra la folla...",
    "street_encounter.pickpocket.gold_missing": "  Ti accorgi che mancano {0} monete d'oro!",
    "street_encounter.pickpocket.msg_stolen": "Un borseggiatore ha rubato {0} monete d'oro!",
    "street_encounter.pickpocket.nothing_to_steal": "  Qualcuno ti urta ma non trova nulla che valga la pena rubare.",
    "street_encounter.pickpocket.msg_found_nothing": "Un borseggiatore ci ha provato ma non ha trovato nulla.",
    "street_encounter.challenge.accept_honor": "  Accetti la sfida con onore!",
    "street_encounter.challenge.decline_reply": "  \"Non oggi,\" rispondi.",
    "street_encounter.challenge.scoffs": "  {0} sogghigna alla tua codardia.",
    "street_encounter.challenge.msg_declined": "Rifiutata una sfida. (-5 Fama)",
    "street_encounter.challenge.opt_insult": "nsultali",
    "street_encounter.challenge.insult_honor": "  Insulti il loro onore e la loro madre!",
    "street_encounter.challenge.pay_for_that": "  \"Me la pagherai!\" ruggisce {0}!",
    "street_encounter.mugging.gold_or_life": "  \"La borsa o la vita!\"",
    "street_encounter.mugging.draw_weapon": "  Sguaini la tua arma!",
    "street_encounter.mugging.defeated_found_gold": "  Hai sconfitto i rapinatori e trovato {0} monete d'oro!",
    "street_encounter.mugging.msg_defeated": "Sconfitti {0} rapinatori!",
    "street_encounter.mugging.msg_lost": "Perso contro i rapinatori...",
    "street_encounter.mugging.hand_over": "  Consegni {0} monete d'oro.",
    "street_encounter.mugging.thugs_disappear": "  I teppisti svaniscono nelle ombre.",
    "street_encounter.mugging.msg_surrendered": "Consegnate {0} monete d'oro ai rapinatori.",
    "street_encounter.mugging.sprint_escape": "  Corri via e li semini tra i vicoli!",
    "street_encounter.mugging.msg_escaped": "Sfuggito ai rapinatori!",
    "street_encounter.mugging.caught_beaten": "  Ti acciuffano e ti pestano!",
    "street_encounter.mugging.damage_and_gold": "  Subisci {0} danni e ti rubano {1} monete d'oro!",
    "street_encounter.mugging.msg_caught": "Catturato e pestato dai rapinatori.",
    "street_encounter.gang.heard_team": "  \"Abbiamo sentito parlare della tua squadra, '{0}'.\"",
    "street_encounter.gang.our_territory": "  \"Questo è il nostro territorio. Fatti da parte.\"",
    "street_encounter.gang.opt_fight_territory": "ombatti per il territorio",
    "street_encounter.gang.opt_negotiate": "ratta",
    "street_encounter.gang.opt_leave": "attene in pace",
    "street_encounter.gang.need_friends": "  \"Sembri uno che ha bisogno di amici.\"",
    "street_encounter.gang.opt_join": "nisciti alla banda",
    "street_encounter.gang.opt_refuse": "ifiuta",
    "street_encounter.gang.wrong_answer": "  \"Risposta sbagliata.\"",
    "street_encounter.gang.victory_spreads": "  La voce della tua vittoria sui '{0}' si diffonde per le strade!",
    "street_encounter.gang.plus_fame": "  (+20 Fama)",
    "street_encounter.gang.looks_you_over": "  Il capo della banda ti scruta...",
    "street_encounter.gang.welcome": "  \"Benvenuto nei '{0}', amico.\"",
    "street_encounter.gang.msg_joined": "Entrato nella banda '{0}'!",
    "street_encounter.gang.too_weak": "  \"Torna quando sarai più forte, debole.\"",
    "street_encounter.gang.msg_too_weak": "Troppo debole per unirsi alla banda.",
    "street_encounter.gang.not_recruiting_1": "  Il capo della banda scuote la testa.",
    "street_encounter.gang.not_recruiting_2": "  \"Non stiamo reclutando. Circola.\"",
    "street_encounter.gang.msg_not_recruiting": "La banda non sta reclutando.",
    "street_encounter.gang.let_you_pass": "  Ti lasciano passare a malincuore.",
    "street_encounter.gang.msg_avoided": "Evitato scontro con la banda.",
    "street_encounter.gang.nobody_refuses": "  \"Nessuno ci rifiuta!\"",
    "street_encounter.romance.buy_drink": "  \"Posso offrirti da bere?\"",
    "street_encounter.romance.opt_yes": "ì, prego",
    "street_encounter.romance.opt_no": "o grazie",
    "street_encounter.romance.pleasant_time": "  Passate un momento piacevole insieme...",
    "street_encounter.romance.wonderful_conversation": "  Una splendida conversazione! Ti senti più affascinante. (+1 Carisma)",
    "street_encounter.romance.msg_connection": "Stretto un legame sincero.",
    "street_encounter.romance.purse_lighter": "  ...ma la borsa sembra più leggera dopo.",
    "street_encounter.romance.stole_gold": "  Ti hanno rubato {0} monete d'oro!",
    "street_encounter.romance.msg_scam": "L'incontro romantico era una truffa!",
    "street_encounter.romance.token_affection": "  Ti lasciano un piccolo pegno d'affetto. (+5 Fama)",
    "street_encounter.romance.msg_fame": "Guadagnata fama da un incontro romantico.",
    "street_encounter.romance.another_time": "  \"Forse un'altra volta,\" dici cortesemente.",
    "street_encounter.romance.smile_walk_away": "  Sorridono e se ne vanno.",
    "street_encounter.romance.msg_declined": "Rifiutato cortesemente un incontro romantico.",
    "street_encounter.merchant.cloaked_figure": "  Una figura incappucciata ti fa cenno dalle ombre.",
    "street_encounter.merchant.buy_special": "  \"Psst... vuoi comprare qualcosa di speciale?\"",
    "street_encounter.merchant.waves_over": "  Un mercante ambulante ti fa cenno.",
    "street_encounter.merchant.fine_wares": "  \"Merce pregiata per l'avventuriero esigente!\"",
    "street_encounter.merchant.no_thanks": "No grazie",
    "street_encounter.merchant.buy_prompt": "Quale oggetto vuoi comprare? ",
    "street_encounter.merchant.purchased": "  Hai acquistato {0}!",
    "street_encounter.merchant.msg_bought": "Comprato {0} da un mercante ambulante.",
    "street_encounter.merchant.come_back": "  \"Torna quando vuoi!\"",
    "street_encounter.merchant.msg_declined": "Dato un'occhiata alla merce del mercante.",
    "street_encounter.beggar.approaches": "  Un mendicante cencioso ti si avvicina.",
    "street_encounter.beggar.thanks": "  \"Che gli dei ti benedicano, anima gentile!\" (+5 Cavalleria)",
    "street_encounter.beggar.plus_chivalry": "  (+{0} Cavalleria)",
    "street_encounter.beggar.msg_gave": "Dato dell'oro a un mendicante.",
    "street_encounter.beggar.bless_you": "  \"Gli dei ti benedicano, anima generosa!\"",
    "street_encounter.beggar.strange_amulet": "  Il mendicante ti preme uno strano amuleto nelle mani.",
    "street_encounter.beggar.luck_amulet": "  \"Per la fortuna,\" sussurra.",
    "street_encounter.beggar.msg_large_donation": "Fatta una grande donazione a un mendicante.",
    "street_encounter.beggar.opt_large": "rande donazione (50)",
    "street_encounter.beggar.rob_possessions": "  Frugi tra i miseri averi del mendicante...",
    "street_encounter.beggar.rob_result": "  Trovate {0} monete d'oro. (+15 Oscurità, -10 Cavalleria)",
    "street_encounter.beggar.msg_robbed": "Derubato un mendicante.",
    "street_encounter.beggar.walk_past": "  Passi oltre senza dire una parola.",
    "street_encounter.beggar.msg_ignored": "Ignorato un mendicante.",
    "street_encounter.rumor.dungeons_dangerous": "I sotterranei sono diventati più pericolosi ultimamente...",
    "street_encounter.rumor.king_adventurers": "Il re cerca avventurieri coraggiosi.",
    "street_encounter.rumor.strange_creatures": "Strane creature sono state avvistate vicino ai confini.",
    "street_encounter.rumor.temple_blessings": "Il tempio offre benedizioni speciali questa settimana.",
    "street_encounter.rumor.fortune_hunting": "C'è una fortuna da guadagnare cacciando nelle profondità dei sotterranei.",
    "street_encounter.rumor.guild_recruits": "La gilda cerca attivamente nuove reclute.",
    "street_encounter.rumor.watch_back": "Attento le spalle nei vicoli bui di notte.",
    "street_encounter.rumor.weapon_shipment": "Un nuovo carico di armi è arrivato all'armeria.",
    "street_encounter.rumor.secret_passage": "Dicono che ci sia un passaggio segreto nei livelli più profondi.",
    "street_encounter.rumor.exotic_goods": "Un mercante con merci esotiche è stato visto vicino al mercato.",
    "street_encounter.rumor.saw_npc": "Ho visto {0} dirigersi verso il {1} poco fa.",
    "street_encounter.rumor.npc_team": "Ho sentito che {0} cerca nuovi alleati.",
    "street_encounter.rumor.msg_heard": "Sentita una voce interessante.",
    "street_encounter.guard.patrol_approaches": "  Una pattuglia di guardie cittadine si avvicina.",
    "street_encounter.guard.crown_insignia": "  Le guardie notano le tue insegne della fazione Corona.",
    "street_encounter.guard.crown_business": "  \"Affari della Corona, compreso.\"",
    "street_encounter.guard.step_aside": "  Si fanno da parte e ti lasciano passare.",
    "street_encounter.guard.halt": "  \"Alt! Voi là!\"",
    "street_encounter.guard.looking_for_you": "  \"Vi stavamo cercando. Livello di oscurità: {0}\"",
    "street_encounter.guard.arrested": "  Le guardie ti arrestano!",
    "street_encounter.guard.confiscate": "  Ti confiscano {0} monete d'oro!",
    "street_encounter.guard.sentenced": "  Sei condannato a {0} giorni di prigione.",
    "street_encounter.guard.msg_arrested": "Arrestato dalla guardia cittadina.",
    "street_encounter.guard.darkness_guards": "  Sconfiggere le guardie aumenta solo la tua infamia! (+30 Oscurità)",
    "street_encounter.guard.overpowered": "  Le guardie ti sopraffanno!",
    "street_encounter.guard.sentenced_resisting": "  Condannato a {0} giorni per resistenza violenta all'arresto!",
    "street_encounter.guard.msg_defeated_arrested": "Sconfitto dalle guardie e arrestato.",
    "street_encounter.guard.bribed": "  Il capitano delle guardie intasca l'oro discretamente. \"Circolare.\"",
    "street_encounter.guard.msg_bribed": "Corrotte le guardie.",
    "street_encounter.guard.escape_crowd": "  Scompari tra la folla!",
    "street_encounter.guard.catch_you": "  Le guardie ti raggiungono!",
    "street_encounter.guard.running_extra": "  \"Fuggi dalla legge, eh? Un giorno in più!\"",
    "street_encounter.guard.sentenced_days": "  Condannato a {0} giorni di prigione!",
    "street_encounter.guard.msg_caught": "Catturato in fuga dalle guardie.",
    "street_encounter.guard.stay_out_trouble": "  \"State fuori dai guai, cittadino.\"",
    "street_encounter.guard.continue_patrol": "  Le guardie proseguono la ronda.",
    "street_encounter.guard.msg_questioned": "Interrogato da una pattuglia di guardie.",
    "street_encounter.ambush.assassins_leap": "  Assassini balzano dalle ombre!",
    "street_encounter.ambush.paid_gold": "  \"Qualcuno ha pagato bene per vederti morto!\"",
    "street_encounter.ambush.find_note": "  Trovi un biglietto sul corpo dell'assassino...",
    "street_encounter.ambush.contract": "  \"Contratto: Eliminare {0}\"",
    "street_encounter.ambush.unreadable": "  Il nome del mandante è illeggibile.",
    "street_encounter.flee.escape_success": "  Riesci a fuggire!",
    "street_encounter.flee.msg_fled": "Fuggito da un incontro.",
    "street_encounter.flee.catches_you": "  {0} ti raggiunge!",
    "street_encounter.flee.attack_back_turned": "  Ti attaccano mentre hai le spalle voltate!",
    "street_encounter.flee.take_damage": "  Subisci {0} danni!",
    "street_encounter.bribe.npc_attacks": "  {0} attacca comunque!",
    "street_encounter.bribe.opt_yes": "ì, paga {0} oro",
    "street_encounter.bribe.opt_no": "o, combatti",
    "street_encounter.bribe.takes_gold_leaves": "  {0} prende l'oro e se ne va.",
    "street_encounter.bribe.msg_bribed": "Corrotto {0} con {1} monete d'oro.",
    "street_encounter.bribe.takes_gold_attacks": "  {0} prende l'oro... e attacca comunque!",
    "street_encounter.talk.reconsiders": "  {0} ci ripensa e si calma.",
    "street_encounter.talk.msg_talked_down": "Calmato un incontro ostile con le parole.",
    "street_encounter.talk.not_interested": "  {0} non è interessato a parlare!",
    "street_encounter.grudge.steps_out": "  {0} emerge dalle ombre davanti a te.",
    "street_encounter.grudge.hesitates": "  Esita, squadrandoti...",
    "street_encounter.grudge.thinks_better": "  Il livello {0} {1} ci ripensa.",
    "street_encounter.grudge.guard_rushes": "  Una guardia della Corona accorre in tuo aiuto!",
    "street_encounter.grudge.guard_strikes": "  La guardia colpisce {0}, infliggendo {1} danni!",
    "street_encounter.grudge.wounded_standing": "  {0} è ferito ma ancora in piedi. (PV: {1}/{2})",
    "street_encounter.grudge.emerges_fury": "{0} emerge dalla folla, la furia che gli arde negli occhi!",
    "street_encounter.grudge.murder_quote_1": "\"Mi hai ucciso una volta. Sono strisciato via dalla morte stessa.\"",
    "street_encounter.grudge.murder_quote_2": "\"Adesso tocca a TE sanguinare!\"",
    "street_encounter.grudge.enraged_stats": "INFEROCITO! Livello {0} {1} (PV: {2}/{3})",
    "street_encounter.grudge.barely_escape": "  Sfuggi a malapena all'ira di {0}!",
    "street_encounter.grudge.cuts_off_escape": "  {0} ti taglia la via di fuga!",
    "street_encounter.grudge.murder_goes_down": "  {0} cade di nuovo!",
    "street_encounter.grudge.stands_over": "  {0} ti sovrasta.",
    "street_encounter.grudge.now_even": "  \"Adesso siamo pari.\"",
    "street_encounter.grudge.take_gold": "  Ti prendono {0} monete d'oro.",
    "street_encounter.grudge.waiting_unhappy": "{0} ti sta aspettando, e non è contento.",
    "street_encounter.grudge.think_again": "\"Credevi di potermi battere e andartene? Ripensaci.\"",
    "street_encounter.grudge.settles_that": "  Questo chiude la questione! {0} non ti darà più fastidio.",
    "street_encounter.grudge.takes_gold_satisfied": "  {0} prende {1} monete d'oro e sembra soddisfatto.",
    "street_encounter.grudge.lowers_fists": "  {0} abbassa i pugni.",
    "street_encounter.grudge.dont_cross": "  \"Non provocarmi di nuovo.\"",
    "street_encounter.grudge.sorry_not_enough": "  \"Le scuse non bastano!\"",
    "street_encounter.grudge.attacks_fury": "  {0} attacca con furia!",
    "street_encounter.grudge.even_for_now": "  \"Siamo pari. Per ora.\"",
    "street_encounter.grudge.pockets_gold": "  {0} intasca le {1} monete d'oro.",
    "street_encounter.grudge.takes_gold_attacks": "  {0} prende l'oro... poi attacca comunque!",
    "street_encounter.grudge.not_enough_attacks": "  Non hai abbastanza oro! {0} attacca!",
    "street_encounter.grudge.slip_away": "  Riesci a sgattaiolare via da {0}.",
    "street_encounter.grudge.catches_first_strike": "  {0} ti acciuffa e colpisce per primo!",
    "street_encounter.witness.title": "Confronto con testimone!",
    "street_encounter.witness.steps_in_front": "{0} ti si para davanti, bloccandoti il passo.",
    "street_encounter.witness.saw_victim": "\"Ho visto cosa hai fatto a {0}. La pagherai.\"",
    "street_encounter.witness.saw_murder": "\"Ho visto cosa hai fatto. Assassino.\"",
    "street_encounter.witness.stats": "Livello {0} {1} (PV: {2}/{3})",
    "street_encounter.witness.opt_bribe": "Corrompi ({0}o)",
    "street_encounter.witness.one_less": "  Un testimone in meno. {0} non parlerà più.",
    "street_encounter.witness.justice_served": "  {0} ha ottenuto giustizia. Prende {1} monete d'oro.",
    "street_encounter.witness.takes_bribe": "  {0} prende {1} monete d'oro e distoglie lo sguardo.",
    "street_encounter.witness.didnt_see": "  \"Non ho visto niente.\"",
    "street_encounter.witness.gold_buy_silence": "  \"Il tuo oro non può comprarmi il silenzio!\"",
    "street_encounter.witness.not_enough_attacks": "  Non hai abbastanza oro! {0} attacca!",
    "street_encounter.witness.slip_away": "  Sgattaioli via prima che {0} possa reagire.",
    "street_encounter.witness.catches_guilty": "  {0} acciuffa il colpevole! Non si sfugge alla giustizia!",
    "street_encounter.spouse.storms_toward": "  {0} ti marcia incontro con la morte negli occhi.",
    "street_encounter.spouse.stops_short": "  Si ferma di colpo, tremante di rabbia, ma non attacca.",
    "street_encounter.spouse.not_over": "  \"Non è finita,\" sibila, e se ne va.",
    "street_encounter.spouse.fists_clenched": "{0} ti affronta, pugni serrati.",
    "street_encounter.spouse.know_doing": "\"So cosa hai fatto con {0}.\"",
    "street_encounter.spouse.find_out": "\"Credevi che non l'avrei scoperto?\"",
    "street_encounter.spouse.just_friends": "  \"Siamo solo amici, lo giuro!\"",
    "street_encounter.spouse.looks_uncertain": "  {0} sembra incerto...",
    "street_encounter.spouse.liar": "  \"BUGIARDO!\"",
    "street_encounter.spouse.attacks_rage": "  {0} attacca in preda alla furia cieca!",
    "street_encounter.spouse.admit_sorry": "  \"Mi dispiace. Non significava nulla.\"",
    "street_encounter.spouse.punches_you": "  {0} ti sferra un pugno in pieno volto! ({1} danni)",
    "street_encounter.spouse.stay_away": "  \"Stai lontano da {0}. Ultimo avvertimento.\"",
    "street_encounter.spouse.taunt_better": "  \"Il tuo {0} merita di meglio!\"",
    "street_encounter.spouse.roars_fury": "  {0} ruggisce di furia!",
    "street_encounter.spouse.settle_this": "  \"Chiudiamo la questione.\"",
    "street_encounter.throne.confronts": "{0} (Livello {1} {2}) ti affronta!",
    "street_encounter.throne.times_up": "\"Il tuo tempo sul trono è scaduto, Vostra Maestà.\"",
    "street_encounter.throne.your_decree": "Il vostro decreto: ",
    "street_encounter.throne.accept_steel": "  \"Che sia l'acciaio a decidere!\"",
    "street_encounter.throne.still_king": "  Hai sconfitto {0}! Il trono è ancora tuo!",
    "street_encounter.throne.imprisoned": "  {0} viene imprigionato per {1} giorni!",
    "street_encounter.throne.defeated_claims": "  {0} ti sconfigge e si impossessa del trono!",
    "street_encounter.throne.guards_remove": "  Fai cenno alle guardie di rimuovere l'arrogante.",
    "street_encounter.throne.guards_drag": "  Le guardie trascinano via {0}!",
    "street_encounter.throne.guards_hesitate": "  Le tue guardie esitano... la loro lealtà vacilla!",
    "street_encounter.throne.face_yourself": "  Dovrai affrontare {0} da solo!",
    "street_encounter.throne.no_guards": "  Non hai guardie! {0} ride e attacca!",
    "street_encounter.throne.offer_role": "  Offri loro un ruolo a corte.",
    "street_encounter.throne.considers_seat": "  {0} riflette... e accetta un posto nel tuo consiglio.",
    "street_encounter.throne.want_throne": "  \"Non voglio un posto — voglio il trono!\"",
    "street_encounter.throne.challenger_attacks": "  {0} attacca!",
    "street_encounter.throne.seize_treason": "  \"Prendetelo! Questo è alto tradimento!\"",
    "street_encounter.throne.dragged_away": "  {0} viene trascinato nelle segrete!",
    "street_encounter.throne.no_guards_imprison": "  Non hai guardie per eseguire l'arresto!",
    "street_encounter.throne.laughs_attacks": "  {0} ride della tua minaccia vuota e attacca!",
    "street_encounter.turf.surround": "Membri dei '{0}' ti circondano!",
    "street_encounter.turf.hold_ends": "\"Il vostro dominio su questo territorio finisce ora,\" dice {0}.",
    "street_encounter.turf.fight_best": "  \"Mandate il vostro migliore!\"",
    "street_encounter.turf.backs_off": "  {0} indietreggia! I '{1}' si ritirano dal tuo territorio!",
    "street_encounter.turf.cheers_lost": "  I '{0}' esultano mentre cadi!",
    "street_encounter.turf.hand_over": "  Consegni {0} monete d'oro.",
    "street_encounter.turf.smart_move": "  \"Scelta saggia,\" dice {0}.",
    "street_encounter.turf.hard_way": "  \"Allora facciamo nel modo duro,\" dice {0}.",
    "street_encounter.turf.takes_control": "  I '{0}' prendono il controllo della zona.",
    "street_encounter.turf.dodge_escape": "  Ti fai largo tra la folla e scappi!",
    "street_encounter.turf.cut_off": "  {0} ti taglia la via di fuga!",
    "street_encounter.murder.assassin_strike": "  Il tuo istinto da assassino guida un primo colpo devastante! (-{0}% PV nemici)",
    "street_encounter.murder.off_guard": "  Li cogli di sorpresa! (-{0}% PV nemici)",
    "street_encounter.murder.clean_job": "  Lavoro pulito. Le Ombre sono soddisfatte.",
    "street_encounter.murder.see_face": "  Vedrai il loro volto nei tuoi incubi.",
    "street_encounter.romance.admirer_maiden": "Leggiadra fanciulla",
    "street_encounter.romance.admirer_beautiful": "Bella sconosciuta",
    "street_encounter.romance.admirer_mysterious_w": "Donna misteriosa",
    "street_encounter.romance.admirer_charming_w": "Dama affascinante",
    "street_encounter.romance.admirer_handsome": "Bello sconosciuto",
    "street_encounter.romance.admirer_dashing": "Affascinante mascalzone",
    "street_encounter.romance.admirer_mysterious_m": "Uomo misterioso",
    "street_encounter.romance.admirer_charming_m": "Gentiluomo affascinante",
}
