translations = {
    "dark_alley.header": "IL VICOLO OSCURO",
    "dark_alley.drug_palace": "Palazzo delle Droghe",
    "dark_alley.steroid_shop": "Bottega degli Steroidi",
    "dark_alley.orbs_club": "Club Salute delle Sfere",
    "dark_alley.magic_services": "Servizi Magici di Groggo",
    "dark_alley.beer_hut": "La Bettola di Bob",
    "dark_alley.alchemist": "Paradiso dell'Alchimista",
    "dark_alley.tribute": "Pagare Tributo alle Ombre",
    "dark_alley.join_shadows": "Unirsi alle Ombre",
    "dark_alley.black_market": "Mercato Nero",
    "dark_alley.informant": "Informatore",
    "dark_alley.evil_deeds": "Atti Malvagi",
    "dark_alley.return": "Torna alla Via Principale",
    "dark_alley.drug_palace_header": "IL PALAZZO DELLE DROGHE",
    "dark_alley.shadows_header": "LE OMBRE",
    "dark_alley.initiation_header": "L'INIZIAZIONE",
    "dark_alley.joined_shadows": "TI SEI UNITO ALLE OMBRE",
    "dark_alley.black_market_header": "IL MERCATO NERO",
    "dark_alley.informant_header": "L'INFORMATORE",
    "dark_alley.gambling_den_header": "LA BISCA",
    "dark_alley.pickpocketing_header": "BORSEGGIO",
    "dark_alley.pit_header": "LA FOSSA",
    "dark_alley.loan_shark_header": "LO STROZZINO",
    "dark_alley.fence_header": "RICETTAZIONE",
    "dark_alley.safe_house_header": "IL RIFUGIO",
    "dark_alley.tribute_header": "PAGA TRIBUTO",
    "dark_alley.enforcer_header": "L'ESATTORE TI HA TROVATO",
    "dark_alley.evil_deeds_header": "ATTI MALVAGI",
    "dark_alley.pit_monster": "Combatti un mostro (generato al tuo livello, 2x oro)",
    "dark_alley.pit_npc": "Combatti un PNG (il vincitore prende il 20% dell'oro del perdente)",
    "dark_alley.changed_mind": "Ho cambiato idea",
    "dark_alley.back_out": "Torna indietro",
    "dark_alley.game_monte": "Tre Carte Monte - Trova la carta giusta. Vittoria = 2,5x la posta",
    "dark_alley.game_skull": "Teschio & Ossa - Scegli il rischio. Vincita 2x/3x/5x",
    "dark_alley.dice_over": "Sopra 7",
    "dark_alley.dice_under": "Sotto 7",
    "dark_alley.card_left": "Carta sinistra",
    "dark_alley.card_middle": "Carta centrale",
    "dark_alley.card_right": "Carta destra",
    "dark_alley.skull_safe": "Scommessa sicura - vincita 2x (45% di probabilit\u00e0)",
    "dark_alley.skull_risky": "Scommessa rischiosa - vincita 3x (30% di probabilit\u00e0)",
    "dark_alley.skull_all": "Tutto o niente - vincita 5x (15% di probabilit\u00e0)",
    "dark_alley.bet_safe": "1,5x (sicura)",
    "dark_alley.bet_risky": "2x (rischiosa)",
    "dark_alley.bet_reckless": "3x (spericolata)",
    "dark_alley.no_bet": "Nessuna scommessa",
    "dark_alley.partial_payment": "Effettua un pagamento parziale",
    "dark_alley.take_loan": "Richiedi un prestito",
    "dark_alley.game_dice": "Dadi Truccati - Indovina sopra/sotto 7. Vittoria = 1,8x la posta",
    "dark_alley.leave_pit": "Lascia la fossa",
    "dark_alley.benefits_shadows": "Vantaggi delle Ombre",
    "dark_alley.requirements_not_met": "Requisiti non soddisfatti",
    "dark_alley.requirements_met": "Requisiti soddisfatti",
    "dark_alley.wealthiest_marks": "Bersagli pi\u00f9 ricchi",
    "dark_alley.wanted_darkness": "Ricercato (Oscurit\u00e0 > 200)",
    "dark_alley.active_targets": "I tuoi bersagli attivi",
    "dark_alley.outstanding_loan": "Prestito in sospeso",
    "dark_alley.access_denied": "ACCESSO NEGATO",
    "dark_alley.guards_block": "Le guardie bloccano l'ingresso al Vicolo Oscuro.",
    "dark_alley.return_martial_law": "Devi tornare quando la legge marziale sar\u00e0 revocata.",
    "dark_alley.press_enter_return": "Premi Invio per tornare...",
    "dark_alley.rejection_hand": "Una mano pesante si posa sulla tua spalla. Ti giri e trovi occhi freddi che ti fissano.",
    "dark_alley.rejection_kind": "\"Non serviamo quelli come te. Le Ombre hanno lunga memoria,",
    "dark_alley.rejection_enemies": " e ti sei fatto troppi nemici in questo vicolo.\"",
    "dark_alley.rejection_standing": "  Reputazione presso le Ombre: {0} \u2014 ti serve almeno -50 per accedere ai servizi sotterranei.",
    "dark_alley.rejection_try_paying": "  Prova a pagare ",
    "dark_alley.rejection_tribute": "tributo per migliorare la tua reputazione.",
    "dark_alley.sr_title": "Vicolo Oscuro",
    "dark_alley.sr_desc": "Le torce crepitano nell'aria umida. Sussurri di commerci illeciti echeggiano tra le porte storte.",
    "dark_alley.sr_shady": "Locali loschi:",
    "dark_alley.sr_underground": "Servizi Sotterranei",
    "dark_alley.sr_other": "Altro:",
    "dark_alley.sr_shadow_member": "  Sei un membro delle Ombre.",
    "dark_alley.visual_desc": "Le torce crepitano nell'aria umida e l'odore di spazzatura si mescola con spezie esotiche. Sussurri di commerci illeciti echeggiano tra le porte storte.",
    "dark_alley.visual_virtuous": "I venditori ti osservano con sospetto. La tua aura virtuosa non appartiene a questo luogo.",
    "dark_alley.visual_shadow_member": "I loschi mercanti annuiscono in segno di riconoscimento. Sei uno di loro.",
    "dark_alley.visual_shady": "Locali loschi:",
    "dark_alley.menu_drug_palace": "alazzo delle Droghe      ",
    "dark_alley.menu_steroid_shop": "teroidi",
    "dark_alley.menu_orbs_club": "lub Salute delle Sfere  ",
    "dark_alley.menu_groggo": "roggo Servizi Magici",
    "dark_alley.menu_bob_beer": "ettola di Bob           ",
    "dark_alley.menu_alchemist": "aradiso dell'Alchimista",
    "dark_alley.menu_pickpocket": "orseggio                ",
    "dark_alley.menu_fence": "icettazione",
    "dark_alley.menu_gambling": " Bisca                   ",
    "dark_alley.menu_pit": " La Fossa (Arena)",
    "dark_alley.menu_loan_shark": "trozzino                ",
    "dark_alley.menu_safe_house": " Rifugio",
    "dark_alley.menu_join_shadows": "Unirsi alle Ombre ",
    "dark_alley.figure_watches": "(una figura osserva dall'oscurit\u00e0...)",
    "dark_alley.serve_another": "(servi un altro...)",
    "dark_alley.shadow_member_tag": " Sei un membro delle Ombre.",
    "dark_alley.menu_black_market": " Mercato Nero",
    "dark_alley.menu_informant": "nformatore",
    "dark_alley.menu_evil_deeds": "tti Malvagi ",
    "dark_alley.evil_deeds_desc": "- Commetti atti oscuri (+Oscurit\u00e0)",
    "dark_alley.menu_return": "orna alla Via Principale",
    "dark_alley.bbs_desc": " Le torce crepitano nell'aria umida. Sussurri di commerci illeciti echeggiano nell'oscurit\u00e0.",
    "dark_alley.bbs_shady": " Locali loschi:",
    "dark_alley.bbs_underground": " Sotterranei",
    "dark_alley.bbs_locked": " [BLOCCATO]",
    "dark_alley.drug_enter": "Entri in un antro fumoso foderato di tende di velluto. Un mercante incappucciato",
    "dark_alley.drug_enter2": "dispone un assortimento di fiale colorate e pacchetti sul tavolo.",
    "dark_alley.drug_available": "Sostanze disponibili:",
    "dark_alley.drug_no_gold": "Il mercante ride. \"Torna quando avrai dei soldi veri!\"",
    "dark_alley.drug_back_away": "Ti allontani dal tavolo.",
    "dark_alley.drug_shadow_boost": "  Le Ombre hanno notato le tue... attivit\u00e0. (+5 reputazione Ombre)",
    "dark_alley.steroid_enter": "Un nano muscoloso sorveglia casse di fiale sospette.",
    "dark_alley.steroid_limit": "Il nano scuote la testa. \"Il tuo corpo non ne regge di pi\u00f9, amico.\"",
    "dark_alley.steroid_no_gold": "Non puoi permettertelo!",
    "dark_alley.steroid_muscles": "I tuoi muscoli si gonfiano in modo innaturale!",
    "dark_alley.orbs_enter": "Un chierico incappucciato ti guida verso sfere luminose che fluttuano in una vasca.",
    "dark_alley.orbs_no_gold": "Oro insufficiente.",
    "dark_alley.orbs_healed": "Una luce calda ricuce le tue ferite \u2013 sei completamente guarito!",
    "dark_alley.groggo_enter": "Il famigerato gnomo Groggo sorride ampiamente dietro una scrivania ingombra.",
    "dark_alley.groggo_enter2": "\"Segreti, incantesimi e conoscenze proibite! Cosa desideri?\"",
    "dark_alley.groggo_menu_header": "Servizi di Groggo:",
    "dark_alley.groggo_intel": "  (1) Informazioni sul Dungeon - 100 oro (rivela i mostri del piano attuale)",
    "dark_alley.groggo_fortune": "  (2) Lettura del Destino - 250 oro (indizi sugli eventi futuri)",
    "dark_alley.groggo_blessing": "  (3) Benedizione delle Ombre - 500 oro (bonus furtivit\u00e0 temporaneo)",
    "dark_alley.groggo_nevermind": "  (0) Non importa",
    "dark_alley.groggo_no_coin": "Groggo sbuffa. \"Torna con delle monete!\"",
    "dark_alley.groggo_whispers": "Groggo sussurra segreti del dungeon:",
    "dark_alley.groggo_no_fortune": "Groggo sbuffa. \"Il futuro costa, amico!\"",
    "dark_alley.groggo_crystal": "Groggo scruta una torbida sfera di cristallo:",
    "dark_alley.groggo_no_shadow": "Groggo sbuffa. \"La magia d'ombra non \u00e8 a buon mercato!\"",
    "dark_alley.groggo_already_blessed": "Hai gi\u00e0 la Benedizione delle Ombre attiva!",
    "dark_alley.groggo_traces": "Groggo traccia simboli arcani nell'aria...",
    "dark_alley.groggo_shadows_wrap": "Le ombre ti avvolgono come un mantello!",
    "dark_alley.groggo_dex_bonus": "  Destrezza +3 (fino al prossimo riposo)",
    "dark_alley.groggo_comeback": "\"Torna quando avrai bisogno di qualcosa.\"",
    "dark_alley.bob_mug": "Bob ti porge un boccale schiumoso che puzza vagamente di sudore di goblin.",
    "dark_alley.bob_no_gold": "Bob ride, \"Prima paghi, amico!\"",
    "dark_alley.bob_warmth": "Il calore si diffonde in te. (+10 PV)",
    "dark_alley.bob_brave": "Ti senti coraggioso! (Non \u00e8 successo nulla, ma ti senti bene.)",
    "dark_alley.bob_coins": "Bob fa l'occhiolino e ti restituisce qualche moneta. \"Per un amico.\" (+5 oro)",
    "dark_alley.bob_burns": "Brucia scendendo! Senti... qualcosa.",
    "dark_alley.alchemist_enter": "Scaffali di intrugli gorgoglianti ricoprono le pareti.",
    "dark_alley.alchemist_price": "Una pozione sperimentale casuale costa {0:N0} {1}.",
    "dark_alley.alchemist_buy_prompt": "Comprare? (S/N): ",
    "dark_alley.alchemist_no_gold": "L'alchimista scuote la testa \u2013 niente credito.",
    "dark_alley.alchemist_limit": "La tua mente ha raggiunto il limite del potenziamento alchemico.",
    "dark_alley.alchemist_int_boost": "La tua mente si fa pi\u00f9 acuta! (+2 INT, {0} potenziamenti rimanenti)",
    "dark_alley.alchemist_heal": "Un caldo bagliore guarisce alcune ferite. (+20 PV)",
    "dark_alley.alchemist_fizzle": "La pozione friz\u00adza malamente\u2026 ti senti a disagio. (+2 Oscurit\u00e0)",
    "dark_alley.shadows_intro1": "Senti degli occhi su di te. Le ombre nell'angolo del vicolo sembrano",
    "dark_alley.shadows_intro2": "infittirsi, solidificarsi in qualcosa di quasi umano...",
    "dark_alley.shadows_figure1": "Una figura emerge. Non puoi vederne il volto \u2013 \u00e8 avvolto in un'oscurit\u00e0",
    "dark_alley.shadows_figure2": "che sembra muoversi e mutare come fumo. Solo la voce \u00e8 chiara.",
    "dark_alley.shadows_noticed": "\"Sei stato notato,\" sussurra la voce, n\u00e9 maschile n\u00e9 femminile.",
    "dark_alley.shadows_attention": "\"Non tutti quelli che percorrono questi vicoli attirano la nostra attenzione.\"",
    "dark_alley.shadows_study": "La figura senza volto inclina la testa, studiandoti.",
    "dark_alley.shadows_carry_mark": "\"Porti il marchio di {0}.\"",
    "dark_alley.shadows_no_share": "\"Le Ombre non condividono. Non competono.\"",
    "dark_alley.shadows_find_us": "\"Quando sarai pronto a camminare libero da catene... cercaci.\"",
    "dark_alley.shadows_dissolves": "La figura si dissolve nell'oscurit\u00e0.",
    "dark_alley.shadows_beckons": "La figura ti fa cenno di seguirla pi\u00f9 a fondo nelle ombre.",
    "dark_alley.shadows_crown": "\"La Corona esige obbedienza. La Fede esige devozione.\"",
    "dark_alley.shadows_demand": "\"Noi non esigiamo nulla. Offriamo... opportunit\u00e0.\"",
    "dark_alley.shadows_currency": "\"L'informazione \u00e8 valuta. I segreti sono potere.\"",
    "dark_alley.shadows_know": "\"Le Ombre sanno ci\u00f2 che la Corona nasconde. Ci\u00f2 che la Fede teme.\"",
    "dark_alley.shadows_unseen": "\"Ci muoviamo inosservati. Guadagniamo mentre gli altri combattono.\"",
    "dark_alley.shadows_benefit1": "\u2022 Prezzi migliori del 20% quando vendi oggetti (bonus ricettatore)",
    "dark_alley.shadows_benefit2": "\u2022 Accesso a merci esclusive del mercato nero",
    "dark_alley.shadows_benefit3": "\u2022 Trattamento amichevole da ladri e assassini PNG",
    "dark_alley.shadows_benefit4": "\u2022 La rete informativa rivela opportunit\u00e0 nascoste",
    "dark_alley.shadows_require": "Le Ombre richiedono:",
    "dark_alley.shadows_req_level": "\u2022 Livello 10 o superiore",
    "dark_alley.shadows_req_darkness": "\u2022 Oscurit\u00e0 200+ (o completare un favore per le Ombre)",
    "dark_alley.shadows_your_darkness": "  La tua Oscurit\u00e0: {0}",
    "dark_alley.shadows_too_light": "\"Cammini troppo nella luce,\" osserva la voce.",
    "dark_alley.shadows_embrace": "\"Abbraccia l'oscurit\u00e0. Fa' ci\u00f2 che va fatto.\"",
    "dark_alley.shadows_prove": "\"Oppure... dimostra il tuo valore con un favore. Ricordiamo chi ci aiuta.\"",
    "dark_alley.shadows_nods": "La figura senza volto annuisce \u2013 in qualche modo lo percepisci, anche senza vedere.",
    "dark_alley.shadows_understand": "\"Comprendi come funziona il mondo. Bene.\"",
    "dark_alley.shadows_step_in": "\"Entrerai nelle ombre con noi?\"",
    "dark_alley.shadows_warning_header": "ATTENZIONE: Unirsi alle Ombre comporter\u00e0:",
    "dark_alley.shadows_warning1": "\u2022 L'esclusione dalla Corona e dalla Fede",
    "dark_alley.shadows_warning2": "\u2022 La diminuzione della reputazione con le fazioni rivali di 100",
    "dark_alley.shadows_join_prompt": "Unirsi alle Ombre? (S/N) ",
    "dark_alley.shadows_shrug": "La figura alza le spalle \u2013 o sembra farlo.",
    "dark_alley.shadows_patient": "\"L'offerta rimane. Le ombre sono pazienti.\"",
    "dark_alley.shadows_watching": "\"Ti terremo d'occhio.\"",
    "dark_alley.shadows_gone": "Tra un battito di ciglia e l'altro, la figura \u00e8 scomparsa.",
    "dark_alley.shadows_ritual1": "La figura ti conduce pi\u00f9 in profondit\u00e0 nell'oscurit\u00e0.",
    "dark_alley.shadows_ritual2": "Il vicolo si torce e si snoda in modi che non dovrebbero essere possibili.",
    "dark_alley.shadows_ritual3": "Perdi ogni senso dell'orientamento.",
    "dark_alley.shadows_ritual4": "Infine, ti trovi in una camera di oscurit\u00e0 assoluta.",
    "dark_alley.shadows_ritual5": "Non riesci a vedere le pareti. Non riesci a vedere il pavimento.",
    "dark_alley.shadows_ritual6": "Puoi vedere solo la figura, delineata dall'ombra.",
    "dark_alley.shadows_no_oath": "\"Non c'\u00e8 giuramento,\" dice la voce. \"Nessun voto. Nessun rituale.\"",
    "dark_alley.shadows_understanding": "\"C'\u00e8 solo comprensione.\"",
    "dark_alley.shadows_coin1": "Qualcosa di freddo ti tocca la mano. Una moneta, pi\u00f9 pesante dell'oro.",
    "dark_alley.shadows_coin2": "Non puoi vederne la faccia, ma senti il simbolo inciso su di essa.",
    "dark_alley.shadows_keep": "\"Tienila. Mostrala quando ne avrai bisogno.\"",
    "dark_alley.shadows_know_you": "\"Chi la vedr\u00e0 sapr\u00e0 che cammini con noi.\"",
    "dark_alley.shadows_welcome": "\"Benvenuto nell'oscurit\u00e0. Usala bene.\"",
    "dark_alley.shadows_receive": "Come membro delle Ombre, riceverai:",
    "dark_alley.shadows_perk1": "\u2022 Prezzi di vendita migliori del 20% al mercato nero",
    "dark_alley.shadows_perk2": "\u2022 Accesso a merci esclusive delle Ombre",
    "dark_alley.shadows_perk3": "\u2022 Riconoscimento da parte di ladri e assassini",
    "dark_alley.shadows_perk4": "\u2022 La rete informativa ora lavora per te",
    "dark_alley.shadows_back_alley": "Quando sbatti le palpebre, ti ritrovi nel Vicolo Oscuro.",
    "dark_alley.shadows_coin_pocket": "La figura \u00e8 sparita. Ma senti la moneta d'ombra in tasca.",
    "dark_alley.easter_squint": "Strizzi gli occhi nelle ombre pi\u00f9 profonde del vicolo...",
    "dark_alley.easter_nothing": "All'inizio non vedi altro che oscurit\u00e0.",
    "dark_alley.easter_adjust": "Ma quando i tuoi occhi si abituano, le forme cominciano a prendere vita...",
    "dark_alley.easter_letters": "Lettere. Lettere antiche, incise nelle ombre stesse.",
    "dark_alley.easter_shift": "Sembrano muoversi e danzare, ma riesci a distinguere le parole:",
    "dark_alley.easter_wave": "   \"L'Onda ritorna all'Oceano.\"",
    "dark_alley.easter_shadow": "   \"L'Ombra ricorda ci\u00f2 che la Luce dimentica.\"",
    "dark_alley.easter_jakob": "   \"Jakob era qui. 1993.\"",
    "dark_alley.easter_discovered": "Hai scoperto qualcosa di nascosto in questo luogo oscuro!",
    "dark_alley.easter_fade": "Le ombre si muovono, e le parole svaniscono dalla vista.",
    "dark_alley.easter_waiting": "Ma sai che sono ancora l\u00ec, in attesa di un'altra",
    "dark_alley.easter_curious": "anima curiosa che le trovi nell'oscurit\u00e0.",
    "dark_alley.bm_no_access": "  Non hai accesso al Mercato Nero.",
    "dark_alley.bm_join_first": "  Unisciti prima alle Ombre.",
    "dark_alley.bm_enter": "  Una figura incappucciata ti fa cenno dietro un muro finto.",
    "dark_alley.bm_enter2": "  Casse di contrabbando riempiono la stanza stretta.",
    "dark_alley.bm_forged_papers": "Documenti Falsi, {0:N0}o - Riduci l'Oscurit\u00e0 di 100",
    "dark_alley.bm_poison_vials": "Fiale di Veleno (x3), {0:N0}o - Avvelena la lama in combattimento",
    "dark_alley.bm_smoke_bomb": "Bomba Fumogena, {0:N0}o - Fuga garantita (max 3)",
    "dark_alley.bm_rank_discount": "  Sconto di grado: {0:F0}%",
    "dark_alley.bm_gold": "  Oro: {0:N0}",
    "dark_alley.bm_purchase_prompt": "  Acquistare? ",
    "dark_alley.bm_no_gold": "  Oro insufficiente.",
    "dark_alley.bm_forged_result": "  Il falsario ti consegna nuovi documenti. Oscurit\u00e0 ridotta di {0}.",
    "dark_alley.bm_poison_vial_limit": "  Non puoi trasportare altre fiale. ({0}/{1})",
    "dark_alley.bm_poison_result": "  Hai acquisito {0} fiale di veleno. (Totale: {1})",
    "dark_alley.bm_poison_use": "  Usa [B] Avvelena Lama durante il combattimento per applicare il veleno.",
    "dark_alley.bm_poison_limit": "  Non puoi trasportarne di pi\u00f9. Tre \u00e8 il limite.",
    "dark_alley.bm_smoke_result": "  Bomba fumogena acquisita. Ne possiedi {0}.",
    "dark_alley.informant_no_access": "  Non hai accesso alla rete informativa.",
    "dark_alley.informant_join_first": "  Unisciti prima alle Ombre.",
    "dark_alley.informant_enter": "  Una figura esile in un angolo buio tamburella con impazienza sul tavolo.",
    "dark_alley.informant_cost": "  \"Le informazioni costano {0} oro. Prendere o lasciare.\"",
    "dark_alley.informant_pay_prompt": "  Pagare per le informazioni? (S/N): ",
    "dark_alley.informant_no_gold": "  \"Torna quando potrai permettertelo.\"",
    "dark_alley.informant_quiet": "  \"Niente da segnalare. La citt\u00e0 \u00e8 morta.\"",
    "dark_alley.informant_nobody_rich": "  Nessuno ha granch\u00e9 addosso al momento.",
    "dark_alley.informant_no_wanted": "  Nessuno nella lista dei ricercati al momento.",
    "dark_alley.gambling_enter": "Il fumo si arriccia nella stanza dal soffitto basso. Un mezzo-orco sfregiato",
    "dark_alley.gambling_enter2": "gestisce i tavoli mentre occhi nervosi osservano da ogni angolo.",
    "dark_alley.gambling_limit": "Il mezzo-orco ti fa cenno di andartene. \"Ne hai avuto abbastanza per oggi.\"",
    "dark_alley.gambling_limit_count": "(10/10 turni giornalieri usati)",
    "dark_alley.gambling_min_gold": "\"Ti servono almeno 10 monete d'oro per giocare, miserabile.\"",
    "dark_alley.gambling_no_coin": "\"Non hai quel tipo di soldi.\"",
    "dark_alley.dice_rattles": "Il mezzo-orco agita due dadi in un bossolo di cuoio.",
    "dark_alley.dice_betray": "I dadi ti tradiscono.",
    "dark_alley.cards_intro": "Tre carte a faccia in gi\u00f9. Una \u00e8 la Regina delle Ombre.",
    "dark_alley.cards_shuffle": "Le mani del mazziere si muovono rapide mentre le mescola.",
    "dark_alley.cards_flip": "Il mazziere gira le carte...",
    "dark_alley.skull_intro": "Un teschio ghignante siede sul tavolo. Scegli il tuo rischio.",
    "dark_alley.skull_jaw": "La mascella del teschio si spalanca...",
    "dark_alley.skull_golden": "Un dente d'oro brilla all'interno! La fortuna favorisce gli audaci!",
    "dark_alley.skull_empty": "Vuoto. Il teschio ride silenziosamente della tua sfortuna.",
    "dark_alley.pick_used_up": "Hai esaurito tutti i tentativi di furto per oggi.",
    "dark_alley.pick_streets_hot": "Le strade sono troppo sorvegliate ora. Torna domani.",
    "dark_alley.pick_scan": "Abbassi il cappuccio e scruti la folla in cerca di bersagli...",
    "dark_alley.pick_empty": "Le strade sono deserte. Nessun bersaglio in vista.",
    "dark_alley.pick_marks": "Bersagli potenziali:",
    "dark_alley.pick_slip_away": "Scivoli di nuovo nelle ombre.",
    "dark_alley.pick_caught": "\"FERMO! AL LADRO!\"",
    "dark_alley.pick_guards": "Le guardie spuntano da ogni vicolo. Non c'\u00e8 via di fuga.",
    "dark_alley.pick_prison": "Sei trascinato in prigione!",
    "dark_alley.pick_dark_rep": "+3 Oscurit\u00e0, +2 Reputazione",
    "dark_alley.pit_enter": "Una folla ruggente circonda una fossa da combattimento macchiata di sangue.",
    "dark_alley.pit_enter2": "L'aria puzza di sudore, birra e disperazione.",
    "dark_alley.pit_limit": "Il capo della fossa scuote la testa. \"Tre combattimenti \u00e8 il limite. Le regole sono regole.\"",
    "dark_alley.pit_limit_count": "(3/3 combattimenti giornalieri usati)",
    "dark_alley.pit_bare": "Tutti i combattimenti nella fossa sono a mani nude \u2014 niente armatura!",
    "dark_alley.pit_victory": "La folla esulta! Sei vittorioso!",
    "dark_alley.pit_defeat": "Cadi nella polvere. La folla ti schernisce.",
    "dark_alley.pit_no_fighters": "Nessun combattente si fa avanti nella fossa stasera.",
    "dark_alley.pit_fighters": "Combattenti nella fossa stasera:",
    "dark_alley.pit_no_mercy": "Niente armatura. Nessuna piet\u00e0.",
    "dark_alley.pit_side_bet": "Piazzare una scommessa laterale sul combattimento?",
    "dark_alley.loan_enter": "Un uomo emaciato con denti d'oro siede dietro una scrivania rinforzata.",
    "dark_alley.loan_enter2": "Due enormi esattori fiancheggiano l'ingresso.",
    "dark_alley.loan_overdue": "  ** SCADUTO \u2014 Gli esattori ti stanno cercando! **",
    "dark_alley.loan_paid": "Lo strozzino conta l'oro e annuisce.",
    "dark_alley.loan_clean": "\"Piacere fare affari. Sei in regola.\"",
    "dark_alley.loan_not_enough": "\"Non ne hai abbastanza. Non farmi perdere tempo.\"",
    "dark_alley.loan_fully_paid": "Debito saldato! \"Sei in regola.\"",
    "dark_alley.loan_changed_mind": "\"Hai cambiato idea? Non farmi aspettare troppo.\"",
    "dark_alley.loan_forward": "Lo strozzino si sporge in avanti con un sorriso predatorio.",
    "dark_alley.loan_five_days": "\"Cinque giorni per restituirli. Gli interessi maturano ogni giorno.\"",
    "dark_alley.loan_deadline": "\"Manca la scadenza... e i miei ragazzi riscuoteranno in altri modi.\"",
    "dark_alley.loan_interest": "(L'interesse matura al 10% giornaliero. Restituisci allo Strozzino.)",
    "dark_alley.loan_wasting": "\"Mi fai perdere tempo? Fuori dai piedi.\"",
    "dark_alley.fence_enter": "Un uomo dal viso da donnola esamina la merce con una lente crepata.",
    "dark_alley.fence_enter2": "\"Compro tutto. Nessuna domanda.\"",
    "dark_alley.fence_shadow_bonus": "(Membro delle Ombre: 80% del valore invece del 70%)",
    "dark_alley.fence_nothing": "\"Non hai niente che valga il mio tempo. Vattene.\"",
    "dark_alley.fence_items": "Oggetti che puoi ricettare:",
    "dark_alley.fence_cursed": "\"Maledetto, eh? Ho un compratore per tutto.\"",
    "dark_alley.safe_locked": "Una porta pesante ti sbarra la strada. Uno sportello si apre e degli occhi ti scrutano.",
    "dark_alley.safe_locked2": "\"Non sei dei nostri, pelle pulita. Torna quando avrai",
    "dark_alley.safe_locked3": " un po' di vera oscurit\u00e0 nell'anima.\"",
    "dark_alley.safe_enter": "Una stanza angusta con una branda lurida e una porta chiusa a chiave.",
    "dark_alley.safe_enter2": "Almeno nessuno ti trover\u00e0 qui... probabilmente.",
    "dark_alley.safe_no_gold": "\"Niente oro, niente letto. Dormi nel rigagnolo.\"",
    "dark_alley.safe_shadow_coin": "La tua moneta d'Ombra tiene a bada i ladri.",
    "dark_alley.safe_shadow_watch": "Le Ombre vegliano su di te. Nessuno ti trover\u00e0 qui.",
    "dark_alley.tribute_already": "Le Ombre ti tollerano gi\u00e0. Nessun tributo necessario.",
    "dark_alley.tribute_figure": "Una figura ammantata emerge dalle ombre.",
    "dark_alley.tribute_back": "\"Si dice che tu voglia tornare nelle nostre grazie. Si pu\u00f2 arrangiare...\"",
    "dark_alley.tribute_price": "\"...per il giusto prezzo.\"",
    "dark_alley.tribute_no_gold": "\"Torna quando potrai permettertelo. Non facciamo la carit\u00e0.\"",
    "dark_alley.tribute_open": "  \"Il sotterraneo \u00e8 di nuovo aperto per te. Non farcene pentire.\"",
    "dark_alley.evil_darkness": "  Oscurit\u00e0: ",
    "dark_alley.evil_deeds_remaining": "    Atti oscuri rimanenti: ",
    "dark_alley.evil_filled": "  L'oscurit\u00e0 ha avuto abbastanza di te per oggi.",
    "dark_alley.evil_return": "  Torna domani per continuare la tua opera oscura.",
    "dark_alley.evil_caught": "  *** SCOPERTO! ***",
    "dark_alley.evil_slink": "  Sgattaioli di nuovo nelle ombre, leccandoti le ferite.",
    "dark_alley.evil_done": "  L'atto \u00e8 compiuto.",
    "dark_alley.evil_chiv_loss": "  Cavalleria -5",
    "dark_alley.evil_altar_cold": "  L'altare \u00e8 freddo. La Lama Spezzata \u00e8 frantumata.",
    "dark_alley.evil_altar_linger": "  Ma l'oscurit\u00e0 ancora persiste, e il tuo sangue ha ancora potere.",
    "dark_alley.evil_awakening": "  +Intuizione del Risveglio",
    "dark_alley.evil_seal_echo": "  Energia antica ti pervade. L'eco del sigillo si frantuma.",
    "dark_alley.gambling_win": "Intaschi {0:N0} monete d'oro!",
    "dark_alley.gambling_loss": "Hai perso {0:N0} monete d'oro. Il banco vince sempre... alla fine.",
    "dark_alley.gambling_rounds_left": "Turni rimanenti: {0}/10",
    "dark_alley.gambling_rounds": "Turni rimanenti oggi: {0}/10",
    "dark_alley.gambling_gold": "Oro disponibile: {0:N0}",
    "dark_alley.gambling_your_game": "Il tuo gioco: ",
    "dark_alley.gambling_bet_prompt": "Piazza la tua scommessa (min {0}, max {1:N0}, 0 per uscire): ",
    "dark_alley.gambling_min_wager": "\"La posta minima \u00e8 {0} oro.\"",
    "dark_alley.gambling_max_wager": "\"La posta massima \u00e8 {0:N0} oro.\"",
    "dark_alley.dice_result": "I dadi rotolano... {0} + {1} = {2}!",
    "dark_alley.dice_actually": "Aspetta... in realt\u00e0 \u00e8 {0}!",
    "dark_alley.dice_favor": "Hai indovinato! I dadi ti favoriscono.",
    "dark_alley.cards_queen_win": "La Regina ti sorride dalla carta {0}. Occhio fine!",
    "dark_alley.cards_queen_lose": "La Regina si nascondeva nella carta {0}. Sar\u00e0 per la prossima volta.",
    "dark_alley.pick_attempts": "Tentativi di furto rimanenti: {0}",
    "dark_alley.pick_heavy_purse": "borsa pesante",
    "dark_alley.pick_decent_coin": "buone monete",
    "dark_alley.pick_light_pockets": "tasche leggere",
    "dark_alley.pick_target_prompt": "Bersaglio: ",
    "dark_alley.pick_approach": "Ti avvicini a {0} da dietro...",
    "dark_alley.pick_success": "Le tue dita trovano la borsa... presa!",
    "dark_alley.pick_stolen": "Rubato: {0:N0} oro da {1}",
    "dark_alley.pick_catches": "{0} ti afferra la mano!",
    "dark_alley.pick_rob_me": "\"Pensi di poter derubare ME?!\"",
    "dark_alley.pick_gutter": "{0} ti lascia sanguinante nel rigagnolo.",
    "dark_alley.pit_fights_remaining": "Combattimenti rimanenti oggi: {0}/3",
    "dark_alley.pit_released": "Un {0} viene rilasciato nella fossa!",
    "dark_alley.pit_monster_stats": "Livello {0} \u2014 PV: {1}",
    "dark_alley.pit_bet_payout": "La scommessa da spettatore paga: +{0:N0} oro!",
    "dark_alley.pit_bet_lost": "Persa la scommessa da spettatore di {0:N0} oro.",
    "dark_alley.pit_challenge_prompt": "Sfida: ",
    "dark_alley.pit_square_off": "Ti metti in guardia contro {0}!",
    "dark_alley.pit_crowd_wild": "La folla impazzisce! Reclami {0:N0} oro da {1}!",
    "dark_alley.pit_stumble_out": "Barcollando esci dalla fossa, {0:N0} monete d'oro pi\u00f9 povero.",
    "dark_alley.pit_side_bet_prompt": "Piazzare una scommessa laterale sul combattimento?",
    "dark_alley.pit_wager_prompt": "Quanto scommettere? (max {0:N0}): ",
    "dark_alley.pit_bet_placed": "Scommessa piazzata: {0:N0} oro a {1}x",
    "dark_alley.loan_principal": "  Capitale:     {0:N0} oro",
    "dark_alley.loan_interest_amt": "  Interessi:    {0:N0} oro",
    "dark_alley.loan_total": "  Totale dovuto: {0:N0} oro",
    "dark_alley.loan_days": "  Giorni rimanenti: {0}",
    "dark_alley.loan_gold_hand": "Oro disponibile: {0:N0}",
    "dark_alley.loan_repay_full": "Salda per intero ({0:N0} oro)",
    "dark_alley.loan_partial_how": "Quanto? (max {0:N0}): ",
    "dark_alley.loan_payment_accepted": "Pagamento accettato. Rimanente: {0:N0} oro.",
    "dark_alley.loan_offer": "\"Hai bisogno di monete? Posso offrirti fino a {0:N0} oro.\"",
    "dark_alley.loan_how_much": "Quanto? (max {0:N0}): ",
    "dark_alley.loan_count_out": "Lo strozzino conta {0:N0} monete d'oro.",
    "dark_alley.loan_dont_forget": "\"Cinque giorni. Non dimenticarlo.\"",
    "dark_alley.fence_sell_prompt": "Vendere quale oggetto? ",
    "dark_alley.fence_confirm": "Vendere {0} per {1:N0} oro? (S/N)",
    "dark_alley.fence_sold": "Il ricettatore intasca {0} e ti fa scivolare {1:N0} oro.",
    "dark_alley.safe_darkness_req": "(Richiede Oscurit\u00e0 50+. La tua: {0})",
    "dark_alley.safe_rest_cost": "Riposare qui per {0} oro? (ripristina il 50% dei PV)",
    "dark_alley.safe_rest_prompt": "Riposare? (S/N): ",
    "dark_alley.safe_healed": "Riesci a riposare un po'. (+{0} PV)",
    "dark_alley.safe_robbed": "Ti svegli e trovi la borsa pi\u00f9 leggera. Qualcuno ti ha borseggiato!",
    "dark_alley.safe_gold_lost": "Persi {0:N0} oro nel sonno.",
    "dark_alley.tribute_standing": "  Reputazione attuale presso le Ombre: {0:N0}",
    "dark_alley.tribute_cost": "  Costo tributo: {0:N0} oro  (+{1} reputazione)",
    "dark_alley.tribute_needed": "  ~{0} tributi per sbloccare i servizi sotterranei",
    "dark_alley.tribute_your_gold": "  Il tuo oro: {0:N0}",
    "dark_alley.tribute_pay_prompt": "Pagare tributo? (S/N): ",
    "dark_alley.tribute_accepted": "La figura intasca il tuo oro e annuisce.",
    "dark_alley.tribute_standing_change": "  Reputazione Ombre: {0:N0} \u2192 {1:N0} (+{2})",
    "dark_alley.enc_mugger_appear": "Una figura esce dalle ombre, la lama luccicante!",
    "dark_alley.enc_mugger_demand": "\"Consegna 50 monete d'oro o ti squarcio come un pesce!\"",
    "dark_alley.enc_mugger_pay": "Paga 50 oro",
    "dark_alley.enc_mugger_fight": "Combatti!",
    "dark_alley.enc_mugger_vanish": "Consegni l'oro. Il rapinatore svanisce nell'oscurit\u00e0.",
    "dark_alley.enc_mugger_wrong": "\"Risposta sbagliata!\"",
    "dark_alley.enc_beggar_tug": "Un mendicante cencioso ti tira la manica.",
    "dark_alley.enc_beggar_away": "Il mendicante si allontana trascinando i piedi.",
    "dark_alley.enc_beggar_tip1": "\"I mostri nei piani pi\u00f9 profondi portano armi incantate, gi\u00e0...\"",
    "dark_alley.enc_beggar_tip2": "\"Attento agli esattori dello strozzino. Rompono le ginocchia per divertimento.\"",
    "dark_alley.enc_beggar_tip3": "\"Ho sentito dire che le guardie stanno pianificando una retata nel vicolo domani...\"",
    "dark_alley.enc_beggar_tip4": "\"C'\u00e8 un passaggio segreto nel dungeon. Cerca il muro crepato.\"",
    "dark_alley.enc_beggar_tip5": "\"Il ricettatore paga di pi\u00f9 per gli oggetti maledetti di quelli normali, se sai come chiedere.\"",
    "dark_alley.enc_beggar_tip6": "\"I combattimenti nella fossa sono truccati, ma se sei abbastanza forte non importa.\"",
    "dark_alley.enc_guard_halt": "\"ALT! Guardia Cittadina! Sei in arresto!\"",
    "dark_alley.enc_guard_badge": "Una guardia sotto copertura rivela un distintivo. Altre guardie accorrono.",
    "dark_alley.enc_guard_prison": "Sei trascinato in prigione!",
    "dark_alley.enc_guard_watching": "Noti qualcuno che ti osserva con troppa insistenza...",
    "dark_alley.enc_guard_slip": "Guardia sotto copertura? Sgattaioli via prima che possa agire.",
    "dark_alley.enc_guard_bump": "Un uomo ben vestito ti urta, borbotta delle scuse e prosegue.",
    "dark_alley.enc_guard_official": "Qualcosa in lui sembrava... ufficiale.",
    "dark_alley.enc_merchant_sidle": "Una figura ammantata ti si avvicina furtivamente.",
    "dark_alley.enc_merchant_potion": "\"Psst... pozione curativa. Roba buona. Solo {0} oro.\"",
    "dark_alley.enc_merchant_buy": "Compra",
    "dark_alley.enc_merchant_pass": "Passa",
    "dark_alley.enc_merchant_pocket": "Intaschi la pozione. Ha un odore accettabile... probabilmente.",
    "dark_alley.enc_merchant_no_gold": "\"Niente oro? Sparisci.\"",
    "dark_alley.enc_merchant_elixir": "\"Elisir speciale. Ti rende... migliore. {0} oro.\"",
    "dark_alley.enc_merchant_str": "Un'ondata di potere ti pervade. (+1 FOR)",
    "dark_alley.enc_merchant_dex": "Le tue dita si fanno pi\u00f9 agili. (+1 DES)",
    "dark_alley.enc_merchant_con": "Ti senti pi\u00f9 resistente. (+1 COS)",
    "dark_alley.enc_merchant_no_gold2": "\"Niente oro? Non farmi perdere tempo.\"",
    "dark_alley.enforcer_appear": "Una figura massiccia ti sbarra la strada. Nocche sfregiato scrocchiano.",
    "dark_alley.enforcer_demand": "\"Hai un debito col capo. \u00c8 ora di pagare... in un modo o nell'altro.\"",
    "dark_alley.enforcer_crumple": "L'esattore crolla a terra.",
    "dark_alley.enforcer_settled": "Si dice in giro che lo strozzino consideri il debito saldato.",
    "dark_alley.enforcer_forgiven": "Il tuo prestito \u00e8 stato condonato!",
    "dark_alley.enforcer_beaten": "L'esattore ti pesta a sangue e prende tutto.",
    "dark_alley.enforcer_lost": "Perso tutto l'oro ({0:N0}). Subiti {1} PV di danni.",
    "dark_alley.enforcer_extension": "\"Il capo ti d\u00e0 altri 3 giorni. Non sprecarli.\"",
    "dark_alley.evil_tier_petty": "Crimini Minori",
    "dark_alley.evil_tier_serious": "Crimini Gravi",
    "dark_alley.evil_tier_dark": "Rituali Oscuri",
    "dark_alley.evil_tier_serious_req": "  (Lv{0}+, Osc {1}+)",
    "dark_alley.evil_tier_dark_req": "  (Lv{0}+, Osc {1}+)",
    "dark_alley.evil_choose_deed": "Scegli un atto (0 per annullare): ",
    "dark_alley.evil_commit_prompt": "Commettere questo atto? (S/N): ",
    "dark_alley.evil_need_gold": "Ti servono {0} oro. Ne hai solo {1:N0}.",
    "dark_alley.evil_cost": "  Costo: {0} oro",
    "dark_alley.evil_blood_price": "  Prezzo di sangue: ~{0} PV",
    "dark_alley.evil_risk": "  Rischio di fallimento: {0}%",
    "dark_alley.evil_blood_cut": "La lama affonda. Perdi {0} PV mentre il sangue si sparge sull'altare.",
    "dark_alley.evil_damage": "  Subisci {0} danni!",
    "dark_alley.evil_gold_loss": "  Perdi {0:N0} oro!",
    "dark_alley.evil_darkness_gain": "  Oscurit\u00e0 +{0}",
    "dark_alley.evil_gold_gain": "  Oro +{0:N0}",
    "dark_alley.evil_xp_gain": "  Esperienza +{0:N0}",
    "dark_alley.evil_shadows_gain": "  Reputazione Ombre {0}",
    "dark_alley.evil_crown_gain": "  Reputazione Corona {0}",
    "dark_alley.evil_dark_pact": "  Patto Oscuro attivo: +{0}% danni per {1} combattimenti!",
    "dark_alley.evil_void_whisper": "  Il Vuoto sussurra in risposta. Intravedi qualcosa di vasto sotto la realt\u00e0.",
    "dark_alley.deed_rob_beggar_name": "Derubare un Mendicante",
    "dark_alley.deed_rob_beggar_desc": "Un vecchio mendicante sonnecchia contro il muro del vicolo, poche monete\ndi rame sparse nella sua ciotola. Non si accorgerebbe mai della loro scomparsa.",
    "dark_alley.deed_vandalize_shrine_name": "Vandalizzare un Santuario",
    "dark_alley.deed_vandalize_shrine_desc": "Un piccolo santuario ai Sette lungo la strada \u00e8 incustodito, le sue candele\nancora tremolanti. Lo rovesci e spargi le offerte nel rigagnolo.",
    "dark_alley.deed_spread_rumors_name": "Spargere Voci Velenose",
    "dark_alley.deed_spread_rumors_desc": "Le pettegole vicino al pozzo sono sempre affamate di scandali. Una bugia\nben piazzata sui debiti di un mercante potrebbe rovinare qualcuno \u2014 e divertirti.",
    "dark_alley.deed_poison_well_name": "Avvelenare il Pozzo",
    "dark_alley.deed_poison_well_desc": "Il pozzo pubblico serve decine di famiglie. Poche gocce di amara\nbelladonna, e al mattino i guaritori avranno il loro bel da fare.",
    "dark_alley.deed_extort_shopkeeper_name": "Estorcere un Bottegaio",
    "dark_alley.deed_extort_shopkeeper_desc": "Il vecchio ciabattino di Anchor Road evade le tasse del Re.\nLo sai perch\u00e9 l'hai visto farlo. Una parola sussurrata, uno sguardo significativo...",
    "dark_alley.deed_desecrate_dead_name": "Profanare i Morti",
    "dark_alley.deed_desecrate_dead_desc": "Il cimitero custodisce pi\u00f9 che ricordi. I sepolti di recente a volte\nvengono interrati con i gioielli. Il becchino guarda dall'altra parte \u2014 per un prezzo.",
    "dark_alley.deed_arson_market_name": "Incendio al Mercato",
    "dark_alley.deed_arson_market_desc": "Le bancarelle in legno del mercato basso sono secche come esca. Una scintilla\ne il caos terr\u00e0 le guardie impegnate per ore \u2014 copertura perfetta.",
    "dark_alley.deed_blackmail_noble_name": "Ricattare un Nobile",
    "dark_alley.deed_blackmail_noble_desc": "Hai spiato le visite notturne di Lord Aldric nel Vicolo Oscuro.\nUn uomo della sua posizione ha molto da perdere. Il tuo silenzio ha un prezzo.",
    "dark_alley.deed_whisper_noctura_name": "Sussurrare il Nome di Noctura",
    "dark_alley.deed_whisper_noctura_desc": "Dicono che se pronunci il vero nome della Regina delle Ombre tre volte\nnell'oscurit\u00e0 assoluta, lei ti ascolta. Nell'angolo pi\u00f9 profondo del vicolo,\ndove nessuna torcia arriva, sussurri: 'Noctura... Noctura... Noctura...'\nLe ombre si infittiscono. Qualcosa risponde.",
    "dark_alley.deed_sabotage_wagons_name": "Sabotare i Carri della Corona",
    "dark_alley.deed_sabotage_wagons_desc": "La carovana di rifornimenti della Corona passa per le strade strette all'alba.\nUn perno dell'asse allentato, un cavallo spaventato \u2014 i soldati del Re restano\na digiuno mentre i ribelli banchettano.",
    "dark_alley.deed_blood_maelketh_name": "Offerta di Sangue a Maelketh",
    "dark_alley.deed_blood_maelketh_desc": "In una cantina sotto il vicolo, i fanatici della Lama Spezzata mantengono\nun altare nascosto macchiato di rosso ruggine. Ti accolgono con occhi vuoti.\nLa lama che offrono \u00e8 affilata. Il tuo sangue sazier\u00e0 la fame di un dio.",
    "dark_alley.deed_dark_pact_name": "Stringere un Patto Oscuro",
    "dark_alley.deed_dark_pact_desc": "Una figura nel vicolo offre qualcosa che nessun mercante vende: certezza.\nFirma il tuo nome col sangue e inchiostro pi\u00f9 nero della mezzanotte, e per dieci\ncombattimenti la tua lama colpir\u00e0 nel segno. Il prezzo \u00e8 scritto in lettere\ntroppo piccole per essere lette.",
    "dark_alley.deed_thorgrim_law_name": "Invocare la Legge di Thorgrim",
    "dark_alley.deed_thorgrim_law_desc": "Esiste una legge pi\u00f9 antica di quella del Re. Nel tribunale sotterraneo sotto\nil vicolo, ti presenti davanti a una parodia di giustizia e pronunci sentenza\ncontro i deboli. Le ombre applaudono.",
    "dark_alley.deed_void_sacrifice_name": "Sacrificio al Vuoto",
    "dark_alley.deed_void_sacrifice_desc": "Oltre il vicolo, oltre la cantina, oltre tunnel che non dovrebbero esistere,\nc'\u00e8 un luogo dove il pavimento di pietra sprofonda nel nulla. I cultisti\nlo chiamano la Bocca. Gettaci qualcosa di prezioso, e il Vuoto\nrestituisce potere in cambio.",
    "dark_alley.deed_shatter_seal_name": "Frantumare un Frammento di Sigillo",
    "dark_alley.deed_shatter_seal_desc": "I Sette Sigilli non sono solo leggenda. Frammenti del loro potere echeggiano in\nluoghi nascosti. Nella parte pi\u00f9 profonda del vicolo, trovi un tale\nframmento \u2014 una scheggia ronzante di legge antica. Potresti studiarla...\no potresti romperla e bere il potere che ne fuoriesce.",
    "dark_alley.ambient_footstep": "Un passo lontano echeggia e poi si ferma.",
    "dark_alley.ambient_skitter": "Qualcosa di piccolo sgambetta sulle pietre del selciato.",
    "dark_alley.ambient_drip": "L'acqua gocciola costantemente da una grondaia rotta sopra di te.",
    "dark_alley.ambient_voices": "Voci sommesse giungono da un portone nell'ombra.",
    "dark_alley.ambient_shadow": "Un'ombra si muove in fondo al vicolo.",
    "dark_alley.ambient_laughter": "Una risata lontana, bassa e breve, giunge da qualche parte non visibile.",
    "dark_alley.sr_prices_higher": "Prezzi {0}% pi\u00f9 alti per allineamento {1}.",
    "dark_alley.sr_discount": "Sconto del {0}% per allineamento {1}.",
    "dark_alley.sr_locked_standing": " (Bloccato, reputazione: {0:N0}, richiesta -50+)",
    "dark_alley.locked_suffix": " (bloccato)",
    "dark_alley.sr_pickpocket": "Borseggio",
    "dark_alley.sr_fence": "Ricettazione",
    "dark_alley.sr_gambling_den": "Bisca",
    "dark_alley.sr_the_pit": "La Fossa, Arena",
    "dark_alley.sr_loan_shark": "Strozzino",
    "dark_alley.sr_safe_house": "Rifugio",
    "dark_alley.visual_prices_higher": "  I prezzi sono {0}% pi\u00f9 alti per chi ha allineamento {1}.",
    "dark_alley.visual_discount": "  Ricevi uno sconto del {0}% come anima affine {1}.",
    "dark_alley.visual_no_trust": "  Le Ombre non si fidano di te. (Reputazione: {0:N0}, richiesta -50+)",
    "dark_alley.menu_pay_tribute": " Pagare Tributo alle Ombre",
    "dark_alley.bbs_drug": "PalazzoDroghe",
    "dark_alley.bbs_steroids": "Steroidi",
    "dark_alley.bbs_orbs": "ClubSfere",
    "dark_alley.bbs_groggo": "Groggo",
    "dark_alley.bbs_beer": "Bettola",
    "dark_alley.bbs_alchemist": "Alchimista",
    "dark_alley.bbs_pickpocket": "Borseggio",
    "dark_alley.bbs_fence": "Ricettatore",
    "dark_alley.bbs_gamble": "Bisca",
    "dark_alley.bbs_the_pit": "LaFossa",
    "dark_alley.bbs_loan": "Strozzino",
    "dark_alley.bbs_safe": "Rifugio",
    "dark_alley.bbs_tribute": "Tributo",
    "dark_alley.bbs_join": "UnisciOmbre",
    "dark_alley.bbs_black_mkt": "MrcNero",
    "dark_alley.bbs_informant": "Informatore",
    "dark_alley.bbs_evil": "AttiMalvagi",
    "dark_alley.bbs_return": "Torna",
    "dark_alley.drug_under_influence": "Sei gi\u00e0 sotto l'effetto di {0}!",
    "dark_alley.drug_wear_off": "Gli effetti svaniranno tra {0} giorno/i.",
    "dark_alley.drug_addiction_level": "Livello di dipendenza: {0}/100",
    "dark_alley.drug_name_steroids": "Steroidi",
    "dark_alley.drug_desc_steroids": "+FOR, +DAN (3 giorni)",
    "dark_alley.drug_name_berserker": "Furia del Berserker",
    "dark_alley.drug_desc_berserker": "+FOR, +ATT, -DIF (1 giorno)",
    "dark_alley.drug_name_haste": "Polvere di Velocit\u00e0",
    "dark_alley.drug_desc_haste": "+AGI, +Attacchi, perdita PV (2 giorni)",
    "dark_alley.drug_name_quicksilver": "Argento Vivo",
    "dark_alley.drug_desc_quicksilver": "+DES, +Critico (2 giorni)",
    "dark_alley.drug_name_mana_boost": "Potenziamento Mana",
    "dark_alley.drug_desc_mana_boost": "+Mana, +Potere Magico (3 giorni)",
    "dark_alley.drug_name_third_eye": "Terzo Occhio",
    "dark_alley.drug_desc_third_eye": "+SAG, +Resistenza Magica (3 giorni)",
    "dark_alley.drug_name_ironhide": "Pellediferro",
    "dark_alley.drug_desc_ironhide": "+COS, +DIF, -AGI (2 giorni)",
    "dark_alley.drug_name_stoneskin": "Pelledipietra",
    "dark_alley.drug_desc_stoneskin": "+Armatura, -Velocit\u00e0 (2 giorni)",
    "dark_alley.drug_name_dark_essence": "Essenza Oscura",
    "dark_alley.drug_desc_dark_essence": "+Tutte le Stat, ALTA DIPENDENZA (1 giorno)",
    "dark_alley.drug_name_demon_blood": "Sangue Demoniaco",
    "dark_alley.drug_desc_demon_blood": "+DAN, +Oscurit\u00e0, MOLTO ASSUEFACENTE (2 giorni)",
    "dark_alley.drug_buy_confirm": "Comprare {0} per {1:N0} oro? (S/N)",
    "dark_alley.drug_eff_str": "  +{0} Forza",
    "dark_alley.drug_eff_dex": "  +{0} Destrezza",
    "dark_alley.drug_eff_agi": "  +{0} Agilit\u00e0",
    "dark_alley.drug_eff_con": "  +{0} Costituzione",
    "dark_alley.drug_eff_wis": "  +{0} Saggezza",
    "dark_alley.drug_eff_mana": "  +{0} Mana",
    "dark_alley.drug_eff_dmg": "  +{0}% Danni",
    "dark_alley.drug_eff_def": "  +{0} Difesa",
    "dark_alley.drug_eff_attacks": "  +{0} Attacchi Extra",
    "dark_alley.drug_pen_def": "  -{0} Difesa",
    "dark_alley.drug_pen_agi": "  -{0} Agilit\u00e0",
    "dark_alley.drug_pen_speed": "  -{0} Velocit\u00e0",
    "dark_alley.drug_pen_hp_drain": "  -{0} PV/turno perdita",
    "dark_alley.steroid_max_reached": "(Raggiunto il massimo di {0} acquisti a vita)",
    "dark_alley.steroid_cost": "Il siero per i muscoli costa {0:N0} {1}.",
    "dark_alley.steroid_purchases": "(Acquisti: {0}/{1})",
    "dark_alley.steroid_inject_prompt": "Iniettare? (S/N): ",
    "dark_alley.steroid_remaining": "({0} acquisti rimanenti)",
    "dark_alley.orbs_cost": "Ripristinare la vitalit\u00e0 costa {0:N0} {1}.",
    "dark_alley.orbs_pay_prompt": "Pagare? (S/N): ",
    "dark_alley.groggo_floor_hint": "  \"Per uno delle tue capacit\u00e0, il piano {0} dovrebbe essere gestibile...\"",
    "dark_alley.groggo_monster_hint": "  \"I mostri l\u00ec sono circa di livello {0}.\"",
    "dark_alley.groggo_potion_hint": "  \"Porta pozioni. Molte pozioni.\"",
    "dark_alley.fortune_1": "\"Vedo oro nel tuo futuro... ma anche pericolo.\"",
    "dark_alley.fortune_2": "\"Un nemico potente ti osserva dalle ombre.\"",
    "dark_alley.fortune_3": "\"Pi\u00f9 scendi in profondit\u00e0, pi\u00f9 grandi saranno le ricompense.\"",
    "dark_alley.fortune_4": "\"Non fidarti dello straniero sorridente alla Locanda.\"",
    "dark_alley.fortune_5": "\"Il tuo destino \u00e8 intrecciato con i Sette Sigilli.\"",
    "dark_alley.fortune_6": "\"Gli antichi d\u00e8i si agitano nelle loro prigioni...\"",
    "dark_alley.bob_price": "\"Solo {0} oro per un po' di coraggio liquido!\" Bob sorride.",
    "dark_alley.bob_drink_prompt": "Bere? (S/N): ",
    "dark_alley.lvl_label": "Lvl",
    "dark_alley.darkness_label": "Oscurit\u00e0",
    "dark_alley.fence_cursed_tag": " (MALEDETTO)",
    "dark_alley.news_shadow_joins": "Una nuova ombra si muove per Dorashire...",
    "encounter.option_leave": "Vai via",
    "encounter.reward_gold": "+{0} oro!",
    "encounter.reward_exp": "+{0} esperienza!",
}
