translations = {
    "inn.trouble": "PROBLEMI ALLA LOCANDA!",
    "inn.drinking_contest": "GARA DI BEVUTE ALLA LOCANDA",
    "inn.contest_results": "RISULTATI DELLA GARA",
    "inn.companions": "Compagni",
    "inn.notifications": "NOTIFICHE",
    "inn.party_management": "GESTIONE DEL GRUPPO",
    "inn.select_companions": "SELEZIONA COMPAGNI ATTIVI",
    "inn.master_trainer": "IL MAESTRO D'ARMI",
    "inn.gambling_den": "BISCA",
    "inn.rent_room": "Affitta una stanza e disconnettiti",
    "inn.header": "LA LOCANDA - 'Il Drago Ubriaco'",
    "inn.activities": "Attività della Locanda:",
    "inn.rest": "Riposati al tavolo",
    "inn.drink": "Compra una bevanda",
    "inn.talk": "Parla con gli avventori",
    "inn.fight_seth": "Sfida Seth Able",
    "inn.drinking_game": "Gioca alla gara di bevute",
    "inn.gossip": "Ascolta i pettegolezzi",
    "inn.order_food": "Ordina da mangiare",
    "inn.train": "Allenati col Maestro",
    "inn.gambling": "Bisca",
    "inn.attack_sleeper": "Attacca un dormiente",
    "inn.return": "Torna indietro",
    "inn.stranger_noticed": "Un misterioso straniero attira il tuo sguardo da un angolo in ombra...",
    "inn.companions_resting": "I tuoi compagni ({0}) riposano a un tavolo vicino.",
    "inn.special_areas": "Aree Speciali:",
    "inn.approach_stranger": "Avvicinati allo straniero ({0} disponibili)",
    "inn.manage_party": "Gestisci il tuo gruppo ({0} compagni)",
    "inn.rent_room_logout": "Affitta una Stanza e Disconnettiti ({0}g, protetto)",
    "castle.header": "IL CASTELLO REALE",
    "castle.header_outside": "FUORI DAL CASTELLO REALE",
    "castle.prison_cells": "Celle della Prigione",
    "castle.orders": "Ordini",
    "castle.royal_mail": "POSTA REALE",
    "castle.sleep": "Vai a Dormire",
    "castle.security": "Controlla la Sicurezza",
    "castle.history": "Storia dei Monarchi",
    "castle.abdicate": "Abdica",
    "castle.magic": "Magia",
    "castle.fiscal": "Questioni Fiscali",
    "castle.status": "Stato",
    "castle.quests": "Missioni",
    "castle.orphanage": "L'Orfanotrofio Reale",
    "castle.wedding": "Matrimonio",
    "castle.court": "Politica di Corte",
    "castle.estate": "Patrimonio (Successione)",
    "castle.bodyguards": "Guardie del Corpo (Mercenari del Dungeon)",
    "castle.return": "Torna in Città",
    "castle.royal_guard": "LA GUARDIA REALE",
    "castle.prison": "Prigione",
    "castle.donate": "Dona alla Cassa Reale",
    "castle.seek_audience": "CHIEDI UDIENZA",
    "castle.apply_guard": "Candidati per la Guardia Reale",
    "castle.besiege": "Assedia il Castello (Assedio di Squadra)",
    "castle.join_service": "Unisciti al Servizio Reale",
    "castle.armory": "Armeria Reale",
    "castle.imprison": "Imprigiona qualcuno",
    "castle.pardon": "Grazia un prigioniero",
    "castle.execute": "Giustizia un prigioniero",
    "castle.set_bail": "Stabilisci la cauzione",
    "castle.hire_guard": "Assumi una guardia PNG",
    "castle.monster_guard": "Guardia mostro",
    "castle.fire_guard": "Licenzia guardia",
    "castle.pay_bonus": "Paga un bonus",
    "castle.dismiss_monster": "Congeda mostro",
    "castle.bless_kingdom": "Benedici il Regno - 1.000 oro - Aumenta il morale del regno",
    "castle.detect_threats": "Rileva Minacce - 500 oro - Rivela pericoli potenziali",
    "castle.protection_spell": "Incantesimo di Protezione - 2.000 oro - Rafforza le difese del castello",
    "castle.scry_enemy": "Scrutare il Nemico - 1.500 oro - Scopri informazioni sui rivali",
    "castle.tax_policy": "Politica Fiscale",
    "castle.budget": "Dettagli del Bilancio",
    "castle.treasury_withdraw": "Preleva dal Tesoro",
    "castle.treasury_deposit": "Deposita nel Tesoro",
    "castle.establishments": "Stabilimenti",
    "castle.proclamation": "Proclamazione",
    "castle.bounty": "Taglia su qualcuno",
    "castle.view_orphan": "Vedi dettagli orfano",
    "castle.give_gifts": "Fai regali (aumenta la felicità)",
    "castle.return_royal": "Torna al Menu Reale",
    "castle.dismiss_plotter": "Congeda",
    "castle.arrest_plotter": "Arresta il Cospiratore",
    "castle.bribe_plotter": "Corrompi",
    "castle.promote_plotter": "Promuovi",
    "castle.designate_heir": "Designa un erede",
    "castle.name_heir": "Nomina un nuovo erede (adotta/legittima)",
    "castle.dismiss_guard": "Congeda",
    "castle.request_quest": "RICHIEDI UNA MISSIONE REALE",
    "castle.request_knighthood": "RICHIEDI IL CAVALIERATO",
    "castle.request_pardon": "RICHIEDI LA GRAZIA",
    "castle.request_loan": "RICHIEDI UN PRESTITO",
    "castle.report_crime": "DENUNCIA UN CRIMINE",
    "castle.request_blessing": "RICHIEDI UNA BENEDIZIONE",
    "castle.tax_relief": "Petizione per Sgravio Fiscale (Riduci le tasse del regno)",
    "castle.return_castle": "Torna al Castello",
    "castle.royal_greeting_1": "Siete entrati nella Sala Grande. Al vostro arrivo siete",
    "castle.royal_greeting_2": "immediatamente circondati da uno stuolo di servi e consiglieri.",
    "castle.royal_greeting_3": "Salutate il vostro seguito con un sottile cenno del capo.",
    "castle.treasury_label": "La Cassa Reale",
    "castle.treasury_has": " contiene ",
    "castle.treasury_gold": " monete d'oro.",
    "castle.guards_label": "Guardie Reali: ",
    "castle.prisoners_label": "Prigionieri: ",
    "castle.unread_mail": "Avete {0} messaggi non letti!",
    "castle.approach_desc_1": "Percorrete la strada tortuosa fino ai cancelli del Castello.",
    "castle.approach_desc_2": "Massicce mura di pietra si ergono sopra di voi, e le guardie reali",
    "castle.approach_desc_3": "osservano il vostro avvicinamento con vivo interesse.",
    "castle.the_mighty": "Il possente ",
    "castle.rules_from": " governa dall'interno di queste mura.",
    "castle.reign_treasury": "Regno: {0} giorni | Tesoro: {1:N0} oro",
    "castle.kingdom_disarray": "Il regno sembra essere nel caos!",
    "castle.no_monarch": "Nessun monarca siede sul trono...",
    "castle.royal_commands": "Comandi Reali:",
    "castle.menu_prison_cells": "elle della Prigione",
    "castle.menu_orders": "rdini              ",
    "castle.menu_royal_mail": " Posta Reale",
    "castle.menu_go_sleep": "ai a Dormire       ",
    "castle.menu_check_security": "ontrolla Sicurezza ",
    "castle.menu_history": "toria dei Monarchi ",
    "castle.menu_abdicate": "bdica              ",
    "castle.menu_magic": "agia               ",
    "castle.menu_fiscal": "uestioni Fiscali",
    "castle.menu_status": "tato               ",
    "castle.menu_quests": "issioni            ",
    "castle.menu_orphanage": "'Orfanotrofio Reale",
    "castle.menu_wedding": "atrimonio          ",
    "castle.menu_court": "Politica di Corte  ",
    "castle.menu_estate": "atrimonio (Success.)",
    "castle.menu_bodyguards": "uardie del Corpo (Mercenari Dungeon)",
    "castle.menu_return_town": "orna in Città",
    "castle.options_label": "Opzioni:",
    "castle.menu_ext_royal_guard": "a Guardia Reale    ",
    "castle.menu_ext_prison": "rigione            ",
    "castle.menu_ext_donate": "ona alla Cassa Reale",
    "castle.menu_ext_history": "toria dei Monarchi ",
    "castle.menu_ext_audience": "hiedi Udienza      ",
    "castle.menu_ext_apply_guard": "andidati Guardia Reale",
    "castle.menu_infiltrate_challenge": "nfiltrati nel Castello (Sfida per il Trono)",
    "castle.menu_infiltrate_level_req": "nfiltrati nel Castello (Richiede Livello {0})",
    "castle.menu_infiltrate_king_level": "nfiltrati nel Castello (Re Lv{0}, serve Lv{1}+)",
    "castle.menu_infiltrate_unavailable": "nfiltrati nel Castello (Non Disponibile)",
    "castle.menu_claim_throne": "eclama il Trono Vacante",
    "castle.menu_claim_throne_level": "eclama il Trono Vacante (Richiede Livello {0})",
    "castle.menu_besiege": "ssedia il Castello (Assedio di Squadra)",
    "castle.menu_join_service": "nisciti al Servizio Reale",
    "castle.swear_loyalty": "(giura fedeltà alla Corona...)",
    "castle.serve_another": "(servi un altro...)",
    "castle.loyal_servant": " Sei un fedele servitore della Corona.",
    "castle.menu_royal_armory": " Armeria Reale",
    "castle.claim_empty_throne_sr": "Reclama il Trono Vacante",
    "castle.claim_throne_requires_sr": "Reclama il Trono Vacante (Richiede Livello {0})",
    "castle.bbs_majesty_treasury": " Vostra Maestà! Tesoro: ",
    "castle.bbs_guards": "  Guardie: {0}/{1}",
    "castle.bbs_prisoners": "  Prigionieri: {0}",
    "castle.bbs_rules": " governa. Regno: {0}g | Tesoro: {1}o",
    "castle.bbs_infiltrate_challenge": "Infiltrati (Sfida per il Trono)",
    "castle.bbs_infiltrate_level": "Infiltrati (Lv{0}+)",
    "castle.bbs_claim_throne": "Reclama il Trono Vacante",
    "castle.bbs_claim_level": "Reclama Trono (Lv{0}+)",
    "castle.bbs_besiege": "Assedia il Castello",
    "castle.bbs_join_crown": "Unisciti alla Corona",
    "castle.invalid_choice": "Scelta non valida! Riprova.",
    "castle.level_req_throne": "Devi essere almeno di livello {0} per sfidare per il trono!",
    "castle.king_level_challenge": "Il {0} è di livello {1}. Devi essere almeno di livello {2} per sfidare!",
    "castle.not_worthy": "Non sei degno di sfidare per il trono!",
    "castle.throne_occupied": "Il trono è già occupato!",
    "castle.siege_online_only": "L'assedio del castello è disponibile solo in modalità online!",
    "castle.guard_disbanded": "Senza un monarca sul trono, la Guardia Reale si è sciolta.",
    "castle.castle_undefended": "Il castello è in gran parte indifeso...",
    "castle.no_royal_guards": "{0} {1} non ha Guardie Reali!",
    "castle.walls_only": "Il castello si affida solo alle sue mura per la difesa.",
    "castle.guard_of": "La Guardia Reale di {0} {1}:",
    "castle.guard_rank": "Guardia",
    "castle.total_guards": "Guardie Totali: {0}/{1}",
    "castle.prison_bars": "Scrutate attraverso le sbarre di ferro le lugubri celle della prigione.",
    "castle.prison_smell": "L'odore di pietra umida vi riempie le narici...",
    "castle.prison_empty": "Le celle della prigione sono vuote.",
    "castle.dungeons_empty": "Le segrete sono vuote. La giustizia regna nel vostro regno!",
    "castle.prison_commands": "Comandi:",
    "castle.prison_menu_text_1": "(I)mprigiona qualcuno  (G)razia prigioniero  (E)secuzione prigioniero",
    "castle.prison_menu_text_2": "(C)auzione stabilisci  (T)orna indietro",
    "castle.your_decree": "Il vostro decreto: ",
    "castle.no_one_imprison": "Non c'è nessuno da imprigionare.",
    "castle.imprison_prompt": "# da imprigionare (o 0 per annullare): ",
    "castle.crime_committed": "Crimine commesso: ",
    "castle.general_misconduct": "Cattiva condotta generale",
    "castle.sentence_days": "Condanna (giorni): ",
    "castle.imprisoned_confirm": "{0} è stato imprigionato per {1} giorni!",
    "castle.no_prisoners_pardon": "Non ci sono prigionieri da graziare.",
    "castle.pardon_prompt": "Prigioniero # da graziare: ",
    "castle.pardoned_confirm": "{0} è stato graziato e rilasciato!",
    "castle.not_in_dungeon": "Quella persona non è nelle segrete.",
    "castle.no_prisoners_execute": "Non ci sono prigionieri da giustiziare.",
    "castle.execution_warning": "ATTENZIONE: Le esecuzioni aumentano notevolmente la tua Oscurità!",
    "castle.execute_prompt": "Prigioniero # da giustiziare: ",
    "castle.execute_confirm_prompt": "Giustiziare {0}? Sei SICURO? (S/N): ",
    "castle.executed_confirm": "{0} è stato giustiziato!",
    "castle.darkness_increases": "La tua oscurità aumenta significativamente...",
    "castle.execution_cancelled": "Esecuzione annullata.",
    "castle.no_prisoners_bail": "Non ci sono prigionieri.",
    "castle.bail_prompt": "Prigioniero # per stabilire la cauzione: ",
    "castle.bail_amount_prompt": "Importo della cauzione per {0} (0 per nessuna cauzione): ",
    "castle.bail_set": "Cauzione fissata a {0} oro per {1}.",
    "castle.no_bail": "Nessuna cauzione consentita per {0}.",
    "castle.inbox_empty": "La vostra casella è vuota.",
    "castle.mail_status_read": "Letto",
    "castle.mail_status_new": "NUOVO",
    "castle.read_message_prompt": "Leggi messaggio # (0 per tornare): ",
    "castle.mail_from": "Da: {0}",
    "castle.mail_subject": "Oggetto: {0}",
    "castle.mail_sender_advisor": "Consigliere Reale",
    "castle.mail_sender_steward": "Castellano",
    "castle.mail_sender_priest": "Sommo Sacerdote",
    "castle.mail_sender_guild": "Maestro di Gilda",
    "castle.mail_sender_merchant": "Signore dei Mercanti",
    "castle.mail_sender_elder": "Anziano della Città",
    "castle.mail_subj_treasury": "Rapporto del Tesoro",
    "castle.mail_subj_affairs": "Affari del Regno",
    "castle.mail_subj_audience": "Richiesta di Udienza",
    "castle.mail_subj_trade": "Proposta Commerciale",
    "castle.mail_subj_security": "Questioni di Sicurezza",
    "castle.mail_subj_festival": "Pianificazione Festival",
    "castle.mail_body_1": "Vostra Maestà,\n\nIl rapporto del tesoro per questo trimestre mostra una crescita costante.\nLa nostra situazione finanziaria rimane stabile.\n\nIl vostro umile servitore.",
    "castle.mail_body_2": "Vostra Altezza,\n\nIl popolo parla bene del vostro governo.\nIl morale nel regno è alto.\n\nLunga vita alla Corona!",
    "castle.mail_body_3": "Nobilissimo Sovrano,\n\nUna delegazione da una terra lontana richiede udienza.\nPortano doni e proposte commerciali.\n\nIn attesa della vostra decisione.",
    "castle.mail_body_4": "Mio Signore,\n\nLe mura del castello necessitano di manutenzione.\nRaccomando di stanziare fondi per le riparazioni.\n\nIl vostro fedele castellano.",
    "castle.mail_body_5": "Vostra Reale Maestà,\n\nTutto è tranquillo nel reame.\nLe guardie non segnalano incidenti.\n\nPossa il vostro regno essere lungo e prospero.",
    "castle.retire_chambers": "Vi ritirate nelle vostre opulente camere reali.",
    "castle.servants_bath": "I servitori preparano un bagno caldo e il vostro letto.",
    "castle.shadow_blessing_fades": "La Benedizione delle Ombre svanisce mentre riposate...",
    "castle.rest_peacefully": "Riposate serenamente nelle camere reali...",
    "castle.hp_restored": "PV ripristinati a {0}!",
    "castle.mana_restored": "Mana ripristinato a {0}!",
    "castle.kingdom_status": "=== Stato del Regno ===",
    "castle.treasury_balance": "Saldo del Tesoro: {0} oro",
    "castle.days_reign": "Giorni di Regno: {0}",
    "castle.guards_watch": "Le vostre guardie reali vegliano fuori dalle camere... (disconnessione)",
    "castle.rest_night": "Riposate serenamente per tutta la notte...",
    "castle.daily_report": "=== Rapporto Giornaliero del Regno ===",
    "castle.daily_income_label": "Entrate Giornaliere: {0} oro",
    "castle.daily_expenses_label": "Spese Giornaliere: {0} oro",
    "castle.guard_status_header": "=== Stato della Guardia Reale ===",
    "castle.npc_guards": "Guardie PNG: {0}/{1}",
    "castle.loyalty_excellent": "Eccellente",
    "castle.loyalty_good": "Buona",
    "castle.loyalty_fair": "Discreta",
    "castle.loyalty_poor": "Scarsa",
    "castle.avg_loyalty": "Lealtà Media: {0}% ({1})",
    "castle.daily_guard_costs": "Costi Giornalieri Guardie: {0} oro",
    "castle.guard_active": "Attiva",
    "castle.guard_inactive": "Inattiva",
    "castle.no_npc_guards": "Nessuna guardia PNG attualmente impiegata.",
    "castle.monster_guards_header": "=== Guardie Mostro ===",
    "castle.monster_guards_count": "Guardie Mostro: {0}/{1}",
    "castle.daily_feeding_costs": "Costi Giornalieri di Nutrimento: {0} oro",
    "castle.no_monster_guards": "Nessuna guardia mostro protegge attualmente il castello.",
    "castle.security_assessment_header": "=== Valutazione della Sicurezza ===",
    "castle.overall_security": "Sicurezza Complessiva: {0}%",
    "castle.total_guards_info": "Guardie Totali: {0} (Gli sfidanti combattono prima i mostri, poi le guardie PNG)",
    "castle.castle_vulnerable": "Il vostro castello è vulnerabile agli attacchi!",
    "castle.guard_commands": "Comandi Guardia:",
    "castle.guard_menu_text_1": "(A)ssumi guardia PNG  (M)ostro guardia     (L)icenzia guardia",
    "castle.guard_menu_text_2": "(B)onus paga          (C)ongeda mostro     (T)orna",
    "castle.command_prompt": "Comando: ",
    "castle.max_monster_guards": "Avete già il numero massimo di guardie mostro!",
    "castle.beast_master_desc": "Il Domatore di Bestie presenta creature temibili per la difesa del fossato.",
    "castle.challengers_must_defeat": "Gli sfidanti devono sconfiggere TUTTE le guardie mostro prima di affrontare le guardie PNG!",
    "castle.treasury_display": "Tesoro: {0} oro",
    "castle.current_monsters": "Mostri Attuali: {0}/{1}",
    "castle.monster_cost_note": "Nota: Ogni mostro aggiuntivo costa +500o in più rispetto al prezzo base.",
    "castle.purchase_monster": "Quale mostro acquistare? (0 per annullare): ",
    "castle.monster_added": "Un {0} è stato aggiunto alle difese del castello!",
    "castle.beast_lurks": "La bestia ora si aggira nel fossato, in attesa di intrusi...",
    "castle.insufficient_treasury": "Fondi insufficienti nel tesoro!",
    "castle.no_monster_dismiss": "Non avete guardie mostro da congedare.",
    "castle.monster_dismiss_prompt": "Nome del mostro da congedare: ",
    "castle.monster_released": "Il {0} è stato congedato dal servizio.",
    "castle.no_monster_found": "Nessun mostro con quel nome trovato.",
    "castle.max_guards": "Avete già il numero massimo di guardie!",
    "castle.insufficient_guard_funds": "Fondi insufficienti! Servono {0} oro.",
    "castle.hire_guard_confirm": "Assumere {0}? Costo: {1} oro (S/N): ",
    "castle.guard_joined": "{0} si è unito alla Guardia Reale!",
    "castle.no_guards_dismiss": "Non avete guardie da congedare.",
    "castle.guard_dismiss_prompt": "Nome della guardia da congedare: ",
    "castle.guard_dismissed": "{0} è stato congedato dalla Guardia Reale.",
    "castle.no_guard_found": "Nessuna guardia con quel nome trovata.",
    "castle.no_guards_pay": "Non avete guardie a cui pagare un bonus.",
    "castle.bonus_per_guard": "Importo bonus per guardia: ",
    "castle.insufficient_treasury_bonus": "Fondi insufficienti nel tesoro!",
    "castle.bonus_paid": "Pagato un bonus di {0} oro a ogni guardia!",
    "castle.loyalty_increased": "La lealtà delle guardie è aumentata!",
    "castle.history_empty": "I libri di storia sono vuoti. Il vostro regno potrebbe essere il primo!",
    "castle.current_monarch_header": "=== MONARCA ATTUALE ===",
    "castle.reign_days": "Regno: {0} giorni",
    "castle.coronation_date": "Incoronazione: {0}",
    "castle.wizard_approaches": "Un anziano mago in vesti fluenti si avvicina a voi.",
    "castle.wizard_greeting": "\"Salve, Vostra Maestà. Come posso servire la Corona?\"",
    "castle.magic_budget": "Budget Magico: {0} oro",
    "castle.available_services": "Servizi Disponibili:",
    "castle.bless_menu": "(B)enedici il Regno    - 1.000 oro - Aumenta il morale del regno",
    "castle.detect_menu": "(R)ileva Minacce       - 500 oro   - Rivela pericoli potenziali",
    "castle.protection_menu": "(P)rotezione Magica    - 2.000 oro - Rafforza le difese del castello",
    "castle.scry_menu": "(S)cruta il Nemico     - 1.500 oro - Scopri informazioni sui rivali",
    "castle.return_menu": "(T)orna",
    "castle.your_wish": "Il vostro desiderio: ",
    "castle.insufficient_magic": "Budget magico insufficiente!",
    "castle.wizard_incants": "Il mago alza il suo bastone e intona parole antiche...",
    "castle.golden_light": "Una luce dorata si diffonde per tutto il regno!",
    "castle.people_blessed": "Il popolo si sente benedetto! La vostra cavalleria aumenta!",
    "castle.wizard_gazes": "Il mago scruta in una sfera di cristallo...",
    "castle.no_threats": "\"Non percepisco minacce significative per il vostro reame, Maestà.\"",
    "castle.sense_darkness": "\"Percepisco oscurità in questi individui...\"",
    "castle.threat_entry": "  - {0} (Livello {1}) - Oscurità: {2}",
    "castle.wizard_enchants": "Il mago tesse incantesimi protettivi...",
    "castle.castle_glows": "Il castello risplende di protezione magica!",
    "castle.guard_loyalty_up": "La lealtà delle guardie è aumentata!",
    "castle.wizard_peers": "Il mago scruta attraverso le nebbie del tempo...",
    "castle.scry_see": "\"Vedo {0}...\"",
    "castle.scry_level": "  Livello: {0}",
    "castle.scry_location": "  Posizione: {0}",
    "castle.mists_nothing": "\"Le nebbie non rivelano nulla di rilevante, Maestà.\"",
    "castle.royal_treasury": "Tesoro Reale: {0} oro",
    "castle.daily_citizen_tax": "Tassa Giornaliera sui Cittadini: {0} oro per cittadino",
    "castle.tax_alignment_label": "Allineamento Fiscale: {0}",
    "castle.king_sales_tax": "Tassa sulle Vendite del Re: {0}% su tutte le vendite",
    "castle.city_team_tax": "Tassa della Squadra Cittadina: {0}% su tutte le vendite",
    "castle.sales_tax_revenue": "Entrate Tasse sulle Vendite Oggi: {0} oro",
    "castle.financial_summary": "=== Riepilogo Finanziario ===",
    "castle.daily_income": "Entrate Giornaliere: {0} oro",
    "castle.daily_expenses": "Spese Giornaliere:   {0} oro",
    "castle.net_daily": "Netto Giornaliero:   {0} oro",
    "castle.fiscal_menu_1": "(T)asse              (B)ilancio Dettagli   (P)releva dal Tesoro",
    "castle.fiscal_menu_2": "(D)eposita nel Tesoro                      (R)itorna",
    "castle.decision_prompt": "Decisione: ",
    "castle.tax_alignments": "Allineamenti Fiscali:",
    "castle.tax_all": "1. Tutti i cittadini",
    "castle.tax_good": "2. Solo allineamento buono",
    "castle.tax_evil": "3. Solo allineamento malvagio",
    "castle.tax_neutral": "4. Solo neutrali",
    "castle.new_tax_alignment": "Nuovo allineamento fiscale (1-4): ",
    "castle.new_citizen_tax": "Nuova tassa giornaliera sui cittadini (oro per cittadino, 0-1000): ",
    "castle.citizen_tax_set": "Tassa sui cittadini fissata a {0} oro per cittadino.",
    "castle.high_tax_warning": "Attenzione: Tasse elevate possono causare disordini!",
    "castle.king_sales_tax_prompt": "Tassa sulle vendite del Re (0-25%, attualmente {0}%): ",
    "castle.king_sales_tax_set": "Tassa sulle vendite del Re fissata al {0}%.",
    "castle.high_sales_warning": "Attenzione: Tasse sulle vendite elevate possono scoraggiare il commercio!",
    "castle.city_tax_prompt": "Tassa della squadra cittadina (0-10%, attualmente {0}%): ",
    "castle.city_tax_set": "Tassa della squadra cittadina fissata al {0}%.",
    "castle.income_breakdown": "=== Dettaglio Entrate ===",
    "castle.citizen_tax_income": "Tassa Cittadini:     {0} oro ({1} x {2} cittadini)",
    "castle.sales_tax_income": "Entrate Vendite:     {0} oro ({1}% delle vendite)",
    "castle.total_income": "Entrate Totali:      {0} oro",
    "castle.expense_breakdown": "=== Dettaglio Spese ===",
    "castle.guard_salaries": "Stipendi Guardie:    {0} oro ({1} guardie)",
    "castle.orphanage_costs": "Costi Orfanotrofio:  {0} oro ({1} orfani)",
    "castle.castle_maintenance": "Manutenzione Castello: {0} oro",
    "castle.total_expenses": "Spese Totali:        {0} oro",
    "castle.withdraw_prompt": "Quanto prelevare? (Max: {0}): ",
    "castle.treasury_not_enough": "Il tesoro non contiene abbastanza!",
    "castle.withdrew_gold": "Prelevato {0} oro dal tesoro.",
    "castle.deposit_prompt": "Quanto depositare? (Possiedi: {0}): ",
    "castle.not_enough_gold": "Non hai abbastanza oro!",
    "castle.deposited_gold": "Depositato {0} oro nel tesoro.",
    "castle.issue_decrees": "Emanate decreti e governate il regno.",
    "castle.last_proclamation": "Ultimo Proclama:",
    "castle.commands_label": "Comandi:",
    "castle.orders_menu_1": "(S)tabilimenti      (P)roclama          (T)aglia su qualcuno",
    "castle.orders_menu_2": "(R)itorna",
    "castle.orders_prompt": "Ordini: ",
    "castle.establishment_status": "=== Stato degli Stabilimenti ===",
    "castle.est_open": "APERTO",
    "castle.est_closed": "CHIUSO",
    "castle.toggle_establishment": "Quale stabilimento cambiare? (0 per tornare): ",
    "castle.est_opened": "aperto",
    "castle.est_closed_verb": "chiuso",
    "castle.est_toggled": "Il {0} è ora {1}!",
    "castle.issue_proclamation": "Emanate un Proclama Reale a tutti i cittadini.",
    "castle.your_decree_prompt": "Il vostro decreto: ",
    "castle.hear_ye": "UDITE, UDITE!",
    "castle.by_royal_decree": "Per decreto reale di {0} {1}:",
    "castle.criminal_name": "Nome del criminale: ",
    "castle.bounty_amount": "Importo della taglia: ",
    "castle.bounty_placed": "Una taglia di {0} oro è stata posta su {1}!",
    "castle.visit_orphans": "Visitate i fanciulli sotto protezione reale.",
    "castle.orphan_count": "Orfani: {0}/{1}   Costo giornaliero: {2} oro ({3} per bambino)",
    "castle.orphanage_empty": "L'orfanotrofio è vuoto. Potreste accogliere un bambino bisognoso.",
    "castle.orphan_boy": "Maschio",
    "castle.orphan_girl": "Femmina",
    "castle.orphan_orphaned": "Orfano",
    "castle.orphan_adopted": "{0}, un {2} di {1} anni, è stato accolto nell'Orfanotrofio Reale.",
    "castle.orphan_adult": "  ADULTO",
    "castle.orphan_ready": "  Stato: Pronto per l'incarico (età {0}+)",
    "castle.adopt_option": "Adotta nuovo orfano ({0} oro dal tesoro)",
    "castle.view_orphan_details": "Vedi dettagli orfano",
    "castle.commission_option": "Incarica orfano (recluta età {0}+, {1} oro)",
    "castle.give_gifts_option": "Fai regali (aumenta la felicità)",
    "castle.return_royal_menu": "Torna al Menu Reale",
    "castle.action_prompt": "Azione: ",
    "castle.no_orphans_view": "Nessun orfano da visualizzare.",
    "castle.orphan_number": "Numero orfano: ",
    "castle.orphan_age_sex": "  Età: {0}   Sesso: {1}   Felicità: {2}%",
    "castle.orphan_type_real": "  Tipo: Orfano (entrambi i genitori deceduti)",
    "castle.orphan_mother": "  Madre: {0}",
    "castle.orphan_father": "  Padre: {0}",
    "castle.orphan_race": "  Razza: {0}",
    "castle.orphan_unknown": "Sconosciuto",
    "castle.soul_pure": "Cuore puro",
    "castle.soul_good": "Buon'indole",
    "castle.soul_dark": "Anima oscura",
    "castle.soul_troubled": "Tormentato",
    "castle.soul_neutral": "Neutrale",
    "castle.orphan_temperament": "  Temperamento: {0} ({1})",
    "castle.orphan_commission_ready": "  Stato: Pronto per l'incarico (età {0}+)",
    "castle.orphan_type_adopted": "  Tipo: Adottato (accolto dalla corona)",
    "castle.king": "Re",
    "castle.queen": "Regina",
    "castle.victory": "              VITTORIA!",
    "castle.defeated_king": "Avete sconfitto {0} {1}!",
    "castle.throne_is_yours": "Il trono è vostro!",
    "castle.you_defeated": "Siete stati sconfitti!",
    "castle.guards_drag_out": "Le guardie vi trascinano fuori dal castello...",
    "castle.remain_loyal_team": "Decidete di restare fedeli alla vostra squadra.",
    "castle.min_level_throne": "Devi essere almeno di livello {0} per reclamare il trono!",
    "castle.your_current_level": "Il tuo livello attuale: {0}",
    "castle.disarray_1": "Il Castello sembra essere nel caos!",
    "castle.disarray_2": "Nessun Re o Regina si trova da nessuna parte. La gente corre",
    "castle.disarray_3": "qua e là in modo disorganizzato.",
    "castle.must_abandon_team": "Per reclamare il trono, devi abbandonare la tua squadra.",
    "castle.currently_member_of": "Sei attualmente membro di '{0}'.",
    "castle.leave_team_claim_yn": "Lasciare la squadra per reclamare la corona? (S/N): ",
    "castle.left_team_for_crown": "Hai lasciato '{0}' per reclamare la corona.",
    "castle.proclaim_self_yn": "Proclamarti {0}? (S/N): ",
    "castle.decide_not_claim": "Decidi di non reclamare il trono.",
    "castle.congratulations_castle": "Congratulazioni, il Castello è Tuo!",
    "castle.interregnum_over": "L'Interregno è finito, lunga vita al {0}!",
    "castle.cannot_be_undone": "Questa azione non può essere annullata!",
    "castle.lose_privileges_1": "Perderai tutti i privilegi reali e il regno",
    "castle.lose_privileges_2": "piomberà nel caos finché non emergerà un nuovo sovrano.",
    "castle.abdicate_confirm_prompt": "Abdicare al trono? (scrivi 'si' per confermare): ",
    "castle.pack_belongings_1": "Raccogliete i vostri pochi effetti personali e lasciate la Corona",
    "castle.pack_belongings_2": "al tesoriere reale. Vi vestite con abiti semplici",
    "castle.pack_belongings_3": "e uscite dal Castello, per non farvi mai più ritorno (?).",
    "castle.has_abdicated": "Il {0} ha ABDICATO!",
    "castle.land_disarray": "La terra è nel caos! Chi reclamerà il Trono?",
    "castle.kingdom_relief": "Uff! Il regno tira un sospiro di sollievo.",
    "castle.no_monarch_audience": "Senza un monarca sul trono, non c'è nessuno che possa concedervi udienza.",
    "castle.throne_room_empty": "La sala del trono è vuota e riecheggia...",
    "castle.guards_block_path": "Le guardie vi sbarrano il cammino!",
    "castle.begone_player": "\"Via di qui, {0}! Il {1} non ha tempo",
    "castle.prove_worth": "per gente come voi. Dimostrate il vostro valore prima!\"",
    "castle.increase_chivalry_fame": "(Aumenta la tua Cavalleria e Fama per ottenere udienza)",
    "castle.king_sits_throne": "{0} {1} siede sul trono.",
    "castle.your_standing": "Il Tuo Rango: {0} (Rep: {1})",
    "castle.your_gold_chiv_dark": "Il Tuo Oro: {0:N0} | Cavalleria: {1} | Oscurità: {2}",
    "castle.greeting_high_rep": "\"Benvenuto, nobile {0}! Il reame è onorato dalla vostra presenza.\"",
    "castle.greeting_mid_rep": "\"Ah, {0}. Il vostro servizio alla corona è stato notato.\"",
    "castle.greeting_low_rep": "\"Esponete il vostro caso, {0}.\"",
    "castle.petition_crown_for": "Per cosa desiderate petizionare la Corona?",
    "castle.req_chiv_fame": " (Richiede Cavalleria 200+, Fama 100+)",
    "castle.req_clear_darkness": " (Ripulisci l'Oscurità per oro)",
    "castle.req_borrow_treasury": " (Prendi in prestito dal Tesoro)",
    "castle.req_temp_stat_boost": " (Potenziamento temporaneo delle statistiche)",
    "castle.req_reduce_taxes": " (Riduci le tasse del regno)",
    "castle.rep_legendary_hero": "Eroe Leggendario",
    "castle.rep_champion_realm": "Campione del Reame",
    "castle.rep_honored_noble": "Nobile Onorato",
    "castle.rep_trusted_ally": "Alleato Fidato",
    "castle.rep_respected_citizen": "Cittadino Rispettato",
    "castle.rep_known_adventurer": "Avventuriero Conosciuto",
    "castle.rep_common_petitioner": "Petizionario Comune",
    "castle.rep_unknown": "Sconosciuto",
    "castle.requires_rep": "(Richiede reputazione di {0}+)",
    "castle.quest_waves_dismiss": "{0} {1} fa un gesto di congedo.",
    "castle.quest_not_proven": "\"Non avete ancora dimostrato di essere degno di un incarico reale.\"",
    "castle.quest_raises_eyebrow": "{0} {1} inarca un sopracciglio.",
    "castle.quest_already_active": "\"Avete già un incarico reale da completare.\"",
    "castle.quest_active_title": "Missione Attiva: {0}",
    "castle.quest_days_remaining": "Giorni Rimanenti: {0}",
    "castle.quest_complete_first": "Completate o abbandonate la vostra missione attuale prima.",
    "castle.quest_considers": "{0} {1} considera la vostra richiesta...",
    "castle.quest_task_worthy": "\"Ho un incarico degno delle vostre capacità...\"",
    "castle.quest_desc": "Missione: {0}",
    "castle.quest_difficulty": "Difficoltà: {0}",
    "castle.quest_reward": "    Ricompensa: {0}",
    "castle.quest_time_limit": "Limite di Tempo: {0} giorni",
    "castle.quest_accept_yn": "Accettare questa missione reale? (S/N): ",
    "castle.quest_excellent": "\"Eccellente! La Corona ripone la sua fiducia in voi.\"",
    "castle.quest_advance_gold": "Ricevete {0:N0} oro come anticipo.",
    "castle.quest_advance_xp": "Guadagnate {0:N0} esperienza per questo onore.",
    "castle.quest_added": "Missione aggiunta alle vostre missioni attive!",
    "castle.quest_check_hall": "Controllate la Sala delle Missioni per vedere i progressi e consegnare quando completata.",
    "castle.quest_another_time": "\"Forse un'altra volta, allora.\"",
    "castle.knight_smiles": "{0} {1} sorride.",
    "castle.knight_already_titled": "\"Portate già un titolo nobiliare, {0} {1}.\"",
    "castle.knight_serve_honor": "\"Continuate a servire il reame con onore.\"",
    "castle.knight_shakes_head": "{0} {1} scuote la testa.",
    "castle.knight_not_ready": "\"Non siete ancora pronti per tale onore.\"",
    "castle.knight_requirements": "Requisiti per il Cavalierato:",
    "castle.knight_req_chivalry": "  Cavalleria 200+: {0}",
    "castle.knight_req_fame": "  Fama 100+: {0}",
    "castle.knight_req_level": "  Livello 10+: {0}",
    "castle.knight_req_honorable": "  Onorevole (Cavalleria > Oscurità): {0}",
    "castle.knight_rises": "{0} {1} si alza dal trono!",
    "castle.knight_kneel": "\"Inginocchiatevi dinanzi a me, valoroso guerriero.\"",
    "castle.knight_draws_sword": "*Il {0} sguaina la Spada Reale*",
    "castle.knight_by_power": "\"Per il potere conferitomi dal reame e dagli dei,\"",
    "castle.knight_dub_thee": "\"Vi nomino {0} {1}!\"",
    "castle.knight_rise": "\"Alzatevi, e servite il regno con onore!\"",
    "castle.knight_you_are_now": "Ora siete {0} {1}!",
    "castle.knight_bonus": "+50 Cavalleria, +25 Fama",
    "castle.pardon_puzzled": "{0} {1} sembra perplesso.",
    "castle.pardon_no_sins": "\"Non avete peccati da perdonare, anima nobile. La vostra fedina è pulita.\"",
    "castle.pardon_current_darkness": "La Tua Oscurità Attuale: {0}",
    "castle.pardon_considers": "{0} {1} considera la vostra richiesta...",
    "castle.pardon_absolution_price": "\"La Corona può offrire l'assoluzione, ma tale misericordia ha un prezzo.\"",
    "castle.pardon_cost": "Costo per la Grazia Completa: {0:N0} oro",
    "castle.your_gold": "Il Tuo Oro: {0:N0}",
    "castle.pardon_cannot_afford": "Non puoi permetterti una grazia completa.",
    "castle.pardon_partial_yn": "Accetti una grazia parziale? (-{0} Oscurità per {1:N0} oro) (S/N): ",
    "castle.pardon_some_forgiven": "\"Alcuni dei vostri peccati sono perdonati. Andate e non peccate più.\"",
    "castle.pardon_darkness_reduced": "Oscurità ridotta di {0}. Nuova Oscurità: {1}",
    "castle.pardon_full_yn": "Pagare {0:N0} oro per una grazia completa? (S/N): ",
    "castle.pardon_hand_blessing": "{0} {1} alza una mano in benedizione.",
    "castle.pardon_sins_forgiven": "\"I vostri peccati passati sono perdonati. La vostra fedina è pulita.\"",
    "castle.pardon_darkness_to_zero": "Oscurità ridotta da {0} a 0!",
    "castle.loan_outstanding": "Avete un prestito in sospeso dalla Corona.",
    "castle.loan_principal": "Capitale: {0:N0} oro",
    "castle.loan_with_interest": "Con Interessi (10%): {0:N0} oro",
    "castle.loan_days_remaining": "Giorni Rimanenti: {0}",
    "castle.loan_overdue": "IL VOSTRO PRESTITO È SCADUTO!",
    "castle.loan_demands_repayment": "La Corona esige il rimborso immediato!",
    "castle.loan_repay_yn": "Rimborsare il prestito di {0:N0} oro? (S/N): ",
    "castle.loan_nods_approvingly": "{0} {1} annuisce con approvazione.",
    "castle.loan_debt_paid": "\"Il vostro debito è saldato. La Corona è soddisfatta.\"",
    "castle.loan_chivalry_bonus": "+10 Cavalleria per aver onorato i vostri obblighi.",
    "castle.loan_gather_funds": "Raccogliete più fondi e tornate quando potrete pagare.",
    "castle.loan_skeptical": "{0} {1} appare scettico.",
    "castle.loan_uncertain_rep": "\"La Corona non concede prestiti a chi ha una... reputazione incerta.\"",
    "castle.loan_sighs": "{0} {1} sospira pesantemente.",
    "castle.loan_coffers_empty": "\"Le casse reali sono quasi vuote. Non abbiamo nulla da prestare.\"",
    "castle.loan_treasury": "Tesoro Reale: {0:N0} oro",
    "castle.loan_max_available": "Prestito Massimo Disponibile: {0:N0} oro",
    "castle.loan_terms": "Condizioni del Prestito: 10% di interessi, scadenza in 30 giorni",
    "castle.loan_failure_warning": "(Il mancato rimborso danneggerà gravemente la vostra reputazione)",
    "castle.loan_how_much": "Quanto desiderate prendere in prestito? (0-{0:N0}): ",
    "castle.loan_nods": "{0} {1} annuisce.",
    "castle.loan_grants": "\"La Corona vi concede un prestito di {0:N0} oro.\"",
    "castle.loan_repay_days": "\"Avete 30 giorni per rimborsare {0:N0} oro (con interessi).\"",
    "castle.loan_received": "Avete ricevuto {0:N0} oro.",
    "castle.loan_offer_stands": "\"Molto bene. L'offerta resta valida se ne avrete bisogno.\"",
    "castle.loan_invalid_amount": "\"Non è un importo valido.\"",
    "castle.crime_listens": "{0} {1} ascolta con attenzione.",
    "castle.crime_who_wronged": "\"Chi ha fatto torto a voi o al reame?\"",
    "castle.crime_no_criminals": "\"Non ci sono criminali noti in libertà in questo momento.\"",
    "castle.crime_suspicious": "Individui sospetti noti:",
    "castle.crime_enter_number": "Inserisci il numero da denunciare (o 0 per annullare): ",
    "castle.crime_bounty_cost": "Per mettere una taglia su {0}, dovete contribuire con {1:N0} oro.",
    "castle.crime_pay_bounty_yn": "Pagare {0:N0} oro per mettere una taglia? (S/N): ",
    "castle.crime_nods_grimly": "{0} {1} annuisce gravemente.",
    "castle.crime_bounty_placed": "\"Una taglia è stata posta su {0}.\"",
    "castle.crime_justice_served": "\"Giustizia sarà fatta.\"",
    "castle.crime_cannot_afford": "Non potete permettervi di affiggere questa taglia.",
    "castle.blessing_considers": "{0} {1} considera la vostra richiesta.",
    "castle.blessing_not_earned": "\"Non avete ancora meritato un tale favore dalla Corona.\"",
    "castle.blessing_smiles": "{0} {1} sorride calorosamente.",
    "castle.blessing_freely_given": "\"Per un campione del vostro calibro, questa benedizione è data liberamente.\"",
    "castle.blessing_nods": "{0} {1} annuisce con approvazione.",
    "castle.blessing_for_gold": "\"Per {0:N0} oro, la Corona vi concederà la sua benedizione.\"",
    "castle.blessing_considers_2": "{0} {1} riflette.",
    "castle.blessing_donation_req": "\"Una tale benedizione richiede una donazione di {0:N0} oro al reame.\"",
    "castle.blessing_grants": "La Benedizione Reale concede:",
    "castle.blessing_attack_defense": "  +10% ad attacco e difesa in combattimento",
    "castle.blessing_accuracy": "  Precisione migliorata contro i nemici",
    "castle.blessing_need_gold": "Servono {0:N0} oro. Possiedi {1:N0}.",
    "castle.blessing_hand_raised": "{0} {1} alza una mano in benedizione.",
    "castle.blessing_golden_light": "*Una calda luce dorata vi avvolge*",
    "castle.blessing_strengthened": "Vi sentite rafforzati dal favore della Corona!",
    "castle.blessing_combat_stats": "  +10% alle statistiche di combattimento (attacco/difesa)",
    "castle.blessing_restored": "  Ripristinati {0} PV e {1} Mana",
    "castle.blessing_lasts": "  (La benedizione dura per diversi combattimenti)",
    "castle.tax_current_rate": "Aliquota Fiscale Attuale del Regno: {0}%",
    "castle.tax_amused": "{0} {1} sembra divertito.",
    "castle.tax_who_are_you": "\"E voi chi sareste per petizionare su questioni di stato?\"",
    "castle.tax_requires_rep": "(Richiede reputazione 150+ per influenzare la politica fiscale)",
    "castle.tax_spreads_hands": "{0} {1} allarga le braccia.",
    "castle.tax_already_low": "\"Le tasse sono già al minimo ragionevolmente possibile.\"",
    "castle.tax_realm_needs_gold": "\"Il reame ha comunque bisogno di oro per funzionare.\"",
    "castle.tax_considers_words": "{0} {1} considera le vostre parole.",
    "castle.tax_reduction_arranged": "\"Una riduzione delle tasse potrebbe essere accordata... con adeguata compensazione.\"",
    "castle.tax_cost_reduce": "Costo per ridurre le tasse del 5%: {0:N0} oro",
    "castle.tax_pay_yn": "Pagare {0:N0} oro per ridurre le tasse? (S/N): ",
    "castle.tax_nods_solemnly": "{0} {1} annuisce solennemente.",
    "castle.tax_hereby_reduced": "\"Molto bene. Sia noto che le tasse sono state ridotte.\"",
    "castle.tax_rate_reduced": "Aliquota fiscale del regno ridotta dal {0}% al {1}%!",
    "castle.tax_fame_chivalry": "+20 Fama, +10 Cavalleria per aver aiutato il popolo.",
    "castle.tax_cannot_afford": "Non potete permettervi di presentare questa petizione.",
    "castle.donate_no_monarch": "Non c'è nessun monarca a ricevere la vostra donazione!",
    "castle.donate_purse_contains": "La Cassa Reale contiene attualmente {0:N0} oro.",
    "castle.donate_you_have": "Possedete {0:N0} oro.",
    "castle.donate_how_much": "Quanto oro desiderate donare? ",
    "castle.donate_cancelled": "Donazione annullata.",
    "castle.donate_not_enough": "Non avete abbastanza oro!",
    "castle.donate_gold": "Donate {0:N0} oro alla Cassa Reale.",
    "castle.donate_chivalry": "La vostra cavalleria aumenta di {0} per questo nobile gesto!",
    "castle.donate_invalid": "Importo non valido.",
    "castle.guard_no_monarch": "Senza un monarca sul trono, la Guardia Reale si è sciolta.",
    "castle.guard_no_accept": "Non c'è nessuno che possa accettare la vostra candidatura.",
    "castle.guard_full_capacity": "La Guardia Reale è al completo.",
    "castle.guard_no_positions": "Non ci sono posizioni disponibili in questo momento.",
    "castle.guard_already_serving": "State già servendo nella Guardia Reale!",
    "castle.guard_looks_over": "Il capitano della guardia vi squadra da capo a piedi...",
    "castle.guard_come_back": "\"Tornate quando avrete dato prova di voi, avventuriero.\"",
    "castle.guard_min_level": "\"Richiediamo guardie almeno di livello {0}.\"",
    "castle.guard_narrows_eyes": "Il capitano della guardia socchiude gli occhi...",
    "castle.guard_bad_rep": "\"La vostra reputazione vi precede, e non in senso positivo.\"",
    "castle.guard_seek_redemption": "\"La Guardia Reale serve il reame con onore. Cercate prima la redenzione.\"",
    "castle.guard_reviews": "Il capitano della guardia esamina le vostre credenziali...",
    "castle.guard_impressive": "\"Notevole, {0}! Livello {1}, con imprese degne di nota.\"",
    "castle.guard_position": "Posizione: Guardia Reale",
    "castle.guard_salary": "Stipendio Giornaliero: {0:N0} oro",
    "castle.guard_current_count": "Guardie Attuali: {0}/{1}",
    "castle.guard_as_guard": "Come Guardia Reale, dovrete:",
    "castle.guard_defend": "  - Difendere il trono dagli usurpatori",
    "castle.guard_receive_salary": "  - Ricevere uno stipendio giornaliero dal tesoro",
    "castle.guard_gain_prestige": "  - Guadagnare prestigio e il favore del re",
    "castle.guard_join_yn": "Desiderate unirvi alla Guardia Reale? (S/N): ",
    "castle.guard_captain_smiles": "Il capitano sorride e tende la mano.",
    "castle.guard_welcome": "\"Benvenuto nella Guardia Reale, {0}!\"",
    "castle.guard_now_member": "Siete ora un membro della Guardia Reale di {0} {1}!",
    "castle.guard_nods_understand": "Il capitano annuisce comprensivo.",
    "castle.guard_offer_stands": "\"L'offerta resta valida, se doveste cambiare idea.\"",
    "castle.armory_restricted": "L'Armeria Reale è riservata ai membri della Corona.",
    "castle.armory_desc_1": "  Rastrelliere di armi lucide e armature scintillanti adornano le pareti.",
    "castle.armory_desc_2": "  Un Quartiermastro Reale sta sull'attenti.",
    "castle.armory_header": "  #  Oggetto                Prezzo       Statistiche",
    "castle.armory_cant_afford": "Non potete permettervi {0}.",
    "castle.armory_presents": "Il Quartiermastro vi presenta {0}.",
    "castle.armory_wear_honor": "  \"Portatelo con onore.\"",
    "castle.crown_herald_leads_1": "Un araldo reale vi conduce attraverso corridoi dorati fino a un'elegante",
    "castle.crown_herald_leads_2": "camera dove il Cancelliere Reale attende a una grande scrivania di quercia.",
    "castle.crown_chancellor_says_1": "\"Ah, un aspirante servitore del reame,\" dice il Cancelliere,",
    "castle.crown_chancellor_says_2": "aggiustando il suo monocolo per studiarvi attentamente.",
    "castle.crown_expression_hardens": "L'espressione del Cancelliere si indurisce.",
    "castle.crown_sworn_allegiance": "\"I nostri registri mostrano che avete giurato fedeltà a {0}.\"",
    "castle.crown_divided_loyalties": "\"La Corona non accetta chi ha lealtà divise.\"",
    "castle.crown_renounce_return": "\"Se mai rinuncerete ai vostri attuali padroni, tornate qui.\"",
    "castle.crown_tapestries": "Il Cancelliere indica gli arazzi che raffigurano la storia del regno.",
    "castle.crown_order_justice": "\"La Corona rappresenta ordine, stabilità e giustizia.\"",
    "castle.crown_old_gods_fell": "\"Quando gli Antichi Dei caddero nella corruzione, fu la Corona\"",
    "castle.crown_law_structure": "\"a tenere unito il regno. Legge. Struttura. Scopo.\"",
    "castle.crown_no_kneel": "\"Non ci inginocchiamo dinanzi a dei che ci hanno abbandonato.\"",
    "castle.crown_no_skulk": "\"Non ci aggiriamo nell'ombra come volgari ladri.\"",
    "castle.crown_build_protect": "\"Noi COSTRUIAMO. Noi PROTEGGIAMO. Noi GOVERNIAMO.\"",
    "castle.crown_benefit_discount": "• 10% di sconto in tutti i negozi legittimi",
    "castle.crown_benefit_guard": "• Accesso a posizioni nella Guardia Reale e risorse militari",
    "castle.crown_benefit_friendly": "• Trattamento amichevole da guardie e nobili PNG",
    "castle.crown_benefit_audience": "• Udienza prioritaria con il monarca regnante",
    "castle.crown_requires": "La Corona richiede:",
    "castle.crown_req_level": "• Livello 10 o superiore",
    "castle.crown_req_chivalry": "• Cavalleria 500+ (dimostrate il vostro onore con nobili imprese)",
    "castle.crown_req_darkness": "• Oscurità inferiore a 500 (nessuna fedina penale)",
    "castle.crown_your_chivalry": "  La Tua Cavalleria: {0}",
    "castle.crown_your_darkness": "  La Tua Oscurità: {0}",
    "castle.crown_rep_precedes": "\"La vostra reputazione vi precede,\" dice freddamente il Cancelliere.",
    "castle.crown_no_criminals": "\"La Corona non si associa con i criminali.\"",
    "castle.crown_prove_worth": "\"Dimostrate il vostro valore. Compite gesta onorevoli. Poi tornate.\"",
    "castle.crown_extends_scroll": "Il Cancelliere si alza e porge una pergamena sigillata con il sigillo reale.",
    "castle.crown_record_speaks": "\"La vostra fedina parla bene di voi. Onorevole. Disciplinato.\"",
    "castle.crown_swear_oath": "\"Volete giurare il Giuramento di Servizio e unirvi alla Corona?\"",
    "castle.crown_warning": "ATTENZIONE: Unirsi alla Corona comporterà:",
    "castle.crown_lock_out": "• Esclusione dalla Fede e dalle Ombre",
    "castle.crown_decrease_standing": "• Diminuzione della reputazione con le fazioni rivali di 100",
    "castle.crown_nods_curtly": "Il Cancelliere annuisce brevemente.",
    "castle.crown_wise_soul": "\"Un'anima saggia impiega tempo per considerare tali giuramenti.\"",
    "castle.crown_gates_open": "\"I cancelli della Corona restano aperti a chi ha cuore nobile.\"",
    "castle.oath_led_throne_1": "Venite condotti nella sala del trono, dove si sono radunati i dignitari.",
    "castle.oath_led_throne_2": "Lo stendardo reale pende dall'alto — una corona dorata su campo cremisi.",
    "castle.oath_kneel_seal": "Vi inginocchiate dinanzi al grande sigillo del regno.",
    "castle.oath_chancellor_stands": "Il Cancelliere sta dinanzi a voi, pergamena alla mano.",
    "castle.oath_repeat": "\"Ripetete il Giuramento di Servizio:\"",
    "castle.oath_line_1": "\"Giuro la mia spada, il mio onore e la mia vita alla Corona.\"",
    "castle.oath_line_2": "\"Manterrò la legge e l'ordine in ogni mia azione.\"",
    "castle.oath_line_3": "\"Difenderò il reame dal caos e dalla corruzione.\"",
    "castle.oath_line_4": "\"Al servizio del regno, non vacillerò.\"",
    "castle.oath_seal_placed": "Il Cancelliere appone il sigillo reale sul vostro giuramento.",
    "castle.oath_trumpets": "Squillano le trombe. I dignitari radunati applaudono.",
    "castle.oath_rise_servant": "\"Alzatevi, servitore della Corona,\" dichiara il Cancelliere.",
    "castle.oath_loyalty_rewarded": "\"La vostra lealtà sarà ricompensata. Il vostro servizio, ricordato.\"",
    "castle.oath_as_member": "Come membro della Corona, riceverete:",
    "castle.oath_benefit_1": "• 10% di sconto in tutti i negozi del regno",
    "castle.oath_benefit_2": "• Riconoscimento da guardie e funzionari reali",
    "castle.oath_benefit_3": "• Accesso a opportunità e risorse riservate alla Corona",
    "castle.siege_no_backend": "Backend online non disponibile.",
    "castle.siege_need_team": "Devi far parte di una squadra per assediare il castello!",
    "castle.siege_visit_team_corner": "Visita l'Angolo delle Squadre per creare o unirti a una squadra.",
    "castle.siege_no_king": "Non c'è nessun re da rovesciare! Il trono è vacante.",
    "castle.siege_use_claim": "Usa [R]eclama il Trono Vacante invece.",
    "castle.siege_own_castle": "Non puoi assediare il tuo stesso castello!",
    "castle.siege_cooldown_1": "La tua squadra ha già tentato un assedio nelle ultime 24 ore.",
    "castle.siege_cooldown_2": "Le difese del castello sono in stato di massima allerta. Riprova più tardi.",
    "castle.siege_min_level": "Devi essere almeno di livello {0} per guidare un assedio.",
    "castle.siege_team_prepares": "La tua squadra '{0}' si prepara ad assaltare il castello!",
    "castle.siege_your_force": "La tua forza d'assedio:",
    "castle.siege_launch_yn": "Lanciare l'assedio? (S/N): ",
    "castle.siege_stands_down": "La tua squadra si ritira. Forse un altro giorno...",
    "castle.siege_team_retreats": "La tua squadra malconcia si ritira dalle mura del castello.",
    "castle.siege_guards_defeated": "          GUARDIE SCONFITTE — LA SALA DEL TRONO ATTENDE!",
    "castle.siege_lost_half_hp": "Hai perso metà dei tuoi PV nell'assalto fallito.",
    "castle.siege_storms_throne": "La tua squadra irrompe nella sala del trono. {0} {1}",
    "castle.siege_draws_weapon": "si alza dal trono, sguainando la sua arma...",
    "castle.siege_face_single": "Come capo dell'assedio, devi affrontare il re in combattimento singolo.",
    "castle.siege_team_holds_back": "(La tua squadra trattiene i servitori rimasti.)",
    "castle.siege_hp_after": "I tuoi PV dopo l'assalto: {0}/{1}",
    "castle.siege_face_king_yn": "Affrontare il re? (S/N): ",
    "castle.siege_declined_king": "La tua squadra ha messo in sicurezza le guardie ma hai rifiutato di affrontare il re.",
    "castle.siege_loyalists_rally": "I lealisti rimasti del re si radunano e la tua squadra si ritira.",
    "castle.siege_king_defeated_you": "{0} ti ha sconfitto!",
    "castle.siege_stalemate": "La battaglia raggiunge una situazione di stallo! {0} tiene duro.",
    "castle.siege_failed_final": "L'assedio è fallito all'ultimo ostacolo.",
    "castle.siege_king_falls": "{0} cade a terra, sconfitto.",
    "castle.siege_crown_tumbles": "La corona rotola dalla sua testa fino ai tuoi piedi...",
    "castle.siege_leave_team": "Lasci '{0}' per prendere la corona.",
    "castle.siege_all_hail": "LUNGA VITA A {0}, IL NUOVO SOVRANO!",
    "castle.siege_remembered": "L'assedio della tua squadra sarà ricordato negli annali della storia.",
    "inn.sleep_morning": "Dormi (avanza fino al mattino)",
    "inn.wait_night": "Aspetta fino al calar della notte",
    "inn.drink_ale": "Birra - Leggera, più round da sopravvivere",
    "inn.drink_stout": "Birra Scura - Una scelta solida per bevitori seri",
    "inn.drink_bomber": "Il Bomba di Seth - Carburante puro! Solo i coraggiosi osano...",
    "inn.game_dice": "Dadi Alto-Basso (Indovina più alto o più basso, vincita 1.8x)",
    "inn.game_bones": "Teschi e Ossa (Blackjack con tessere d'osso, vincita 2x)",
    "castle.infiltrate": "Infiltrati nel Castello (Sfida per il Trono)",
    "castle.infiltrate_unavailable": "Infiltrati nel Castello (Non Disponibile)",
    "castle.royal_prison": "LA PRIGIONE REALE",
    "castle.prison_mgmt": "GESTIONE CELLE DELLA PRIGIONE",
    "castle.royal_chambers": "LE CAMERE REALI",
    "castle.security_report": "RAPPORTO DI SICUREZZA",
    "castle.monster_market": "MERCATO GUARDIE MOSTRO",
    "castle.history_monarchs": "STORIA DEI MONARCHI",
    "castle.court_magician": "IL MAGO DI CORTE",
    "castle.fiscal_matters": "QUESTIONI FISCALI",
    "castle.royal_orders": "ORDINI REALI",
    "castle.royal_orphanage": "L'ORFANOTROFIO REALE",
    "castle.royal_marriage": "MATRIMONIO REALE",
    "castle.royal_court": "LA CORTE REALE",
    "castle.royal_succession": "SUCCESSIONE REALE",
    "castle.royal_bodyguards": "GUARDIE DEL CORPO REALI",
    "castle.royal_bounty": "ALBO DELLE TAGLIE REALI",
    "castle.throne_challenge": "SFIDA PER IL TRONO",
    "castle.claiming_throne": "RECLAMO DEL TRONO",
    "castle.abdication": "ABDICAZIONE",
    "castle.audience_crown": "UDIENZA CON LA CORONA",
    "castle.guard_recruitment": "RECLUTAMENTO GUARDIA REALE",
    "castle.royal_armory": "L'ARMERIA REALE",
    "castle.the_crown": "LA CORONA",
    "castle.oath_service": "IL GIURAMENTO DI SERVIZIO",
    "castle.joined_crown": "VI SIETE UNITI ALLA CORONA",
    "castle.castle_siege": "ASSEDIO DEL CASTELLO",
    "castle.siege_victory": "L'ASSEDIO È VITTORIOSO!",
    "castle.petition_tax": "PETIZIONE PER SGRAVIO FISCALE",
    "castle.benefits_crown": "Benefici della Corona",
    "castle.requirements_not_met": "Requisiti Non Soddisfatti",
    "castle.requirements_met": "Requisiti Soddisfatti",
    "inn.challenging_seth": "SFIDA A SETH ABLE",
    "inn.mingle_patrons": "Mescolarsi tra gli Avventori",
    "inn.tavern_gossip": "Pettegolezzi della Taverna",
    "inn.quiet_moment": "Un Momento di Quiete",
    "inn.give_gift": "Fai un Regalo",
    "inn.high_low_dice": "DADI ALTO-BASSO",
    "inn.skull_bones": "TESCHI E OSSA",
    "inn.arm_wrestling": "BRACCIO DI FERRO",
    "inn.ambient_brawl": "Scoppia una rissa in un angolo, ma il locandiere la ferma subito.",
    "inn.ambient_bard": "Un bardo suona una melodia malinconica su un liuto consunto.",
    "inn.ambient_merchant": "Un mercante conta monete d'oro a un tavolo vicino.",
    "inn.ambient_guard": "Una guardia sorseggia una bevanda, gli occhi che scrutano la sala.",
    "inn.ambient_cloaked": "Una figura incappucciata sguscia dalla porta sul retro.",
    "inn.ambient_barkeep": "Il barista pulisce il bancone con uno straccio sporco.",
    "inn.ambient_dice": "Qualcuno sta vincendo grosso al tavolo dei dadi, a giudicare dalle grida.",
    "inn.aldric_event_title": "ATTACCO DEI BANDITI!",
    "inn.aldric_event_crash": "Le porte della taverna si spalancano con un fracasso di tuono!",
    "inn.aldric_event_bandits_rush": "Tre banditi armati irrompono, armi sguainate!",
    "inn.aldric_event_leader_shout": "\"Nessuno si muova! Consegnate il vostro oro!\" ringhia il capo.",
    "inn.aldric_event_patrons_cower": "Gli avventori si rannicchiano mentre i banditi avanzano...",
    "inn.aldric_event_suddenly": "All'improvviso, una figura si alza dall'ombra di un tavolo d'angolo.",
    "inn.aldric_event_aldric_intro": "Un guerriero alto in armatura ammaccata si fa avanti, la mano sulla spada.",
    "inn.aldric_event_aldric_speaks": "\"Credo dovreste andarvene, signori,\" dice con calma.",
    "inn.aldric_event_leader_laughs": "Il capo dei banditi ride. \"E chi ce lo impedirà? Tu?\"",
    "inn.aldric_event_fight_desc": "Ciò che segue è una magistrale esibizione di maestria con la spada.",
    "inn.aldric_event_disarms_first": "Il guerriero disarma il primo bandito con un solo colpo,",
    "inn.aldric_event_pins_second": "inchioda il secondo contro il muro,",
    "inn.aldric_event_knocks_leader": "e manda il capo a barcollare indietro con un calcio ben piazzato.",
    "inn.aldric_event_bandits_flee": "I banditi sgattaiolano fuori dalla porta, lasciando le loro armi.",
    "inn.aldric_event_warrior_sits": "Il guerriero rinfodera la spada e si risiede,",
    "inn.aldric_event_resumes_drink": "riprendendo la sua bevanda come se nulla fosse accaduto.",
    "inn.aldric_event_crowd_erupts": "La folla esplode in applausi!",
    "inn.aldric_event_innkeeper_thanks": "Il locandiere accorre: \"Aldric, vecchia canaglia! Si beve a spese della casa!\"",
    "inn.aldric_event_aldric_nods": "Il guerriero — Aldric — annuisce e alza il suo boccale.",
    "inn.aldric_event_approach_prompt": "Noti Aldric che ti guarda. Avvicinarsi a lui? (S/N): ",
    "inn.aldric_event_approaches": "Ti avvicini al tavolo di Aldric.",
    "inn.aldric_event_aldric_greeting": "\"Non male come tempismo, amico. Mi chiamo Aldric. Offrimi da bere\"",
    "inn.aldric_event_aldric_gesture": "\"e ti racconterò qualche storia.\"",
    "inn.aldric_event_aldric_nods_menu": "Indica con un cenno il menù della locanda.",
    "inn.aldric_event_aldric_hint": "\"Sono qui quasi tutte le sere. Se mai avessi bisogno di un braccio armato...\"",
    "inn.aldric_event_aldric_wink": "Si interrompe con un occhiolino eloquente.",
    "inn.aldric_event_relationship_up": "La tua relazione con Aldric è migliorata!",
    "inn.aldric_event_watches": "Osservi dal tuo tavolo mentre Aldric torna alla sua bevanda.",
    "inn.aldric_event_remember": "Te lo ricorderai se mai avrai bisogno di un combattente capace.",
    "inn.desc_smoky": "La locanda è fumosa e piena di avventurieri.",
    "inn.desc_flickering": "La luce tremolante delle torce proietta lunghe ombre sulle pareti.",
    "inn.desc_seth_corner": "Seth Able siede in un angolo buio, affilando la sua lama.",
    "inn.desc_seth_look": "Alza lo sguardo al tuo ingresso, un bagliore pericoloso negli occhi.",
    "inn.desc_seth_desc": "Seth Able — il guerriero più temuto del reame.",
    "inn.desc_seth_legends": "Le leggende narrano che un tempo sconfisse da solo un intero piano del dungeon.",
    "inn.aldric_teaser_booth": "In un tavolo d'angolo, un guerriero dalle spalle larghe in armatura ammaccata",
    "inn.aldric_teaser_drink": "sorseggia una bevanda da solo, osservando la sala con occhio esperto.",
    "inn.aldric_teaser_scars": "Vecchie cicatrici gli attraversano le braccia, e la sua spada — appoggiata al tavolo —",
    "inn.aldric_teaser_blade": "ha visto più battaglie di quante ne vedano la maggior parte dei soldati in una vita.",
    "inn.aldric_teaser_notice": "Nota che lo stai guardando e alza brevemente il boccale prima di tornare",
    "inn.aldric_teaser_attention": "a osservare la sala. Qualcosa in lui dice 'vale la pena conoscerlo.'",
    "inn.menu_visual_rest": "iposati al tavolo  ",
    "inn.menu_visual_drink": "ompra una bevanda  ",
    "inn.menu_visual_talk": "arla agli avventori",
    "inn.menu_visual_seth": "fida Seth          ",
    "inn.menu_visual_drinking_game": "ara di bevute      ",
    "inn.menu_visual_gossip": "scolta pettegolezzi",
    "inn.menu_visual_food": "rdina da mangiare  ",
    "inn.menu_visual_train": "llenati col Maestro",
    "inn.menu_visual_gambling": "isca               ",
    "inn.menu_visual_companions": "ompagni            ",
    "inn.menu_visual_rent": "ffitta stanza      ",
    "inn.menu_visual_attack": "ttacca dormiente   ",
    "inn.menu_visual_return": "orna indietro      ",
    "inn.bbs_rest": "Riposo",
    "inn.bbs_drink": "Bevanda",
    "inn.bbs_talk": "Parla",
    "inn.bbs_seth": "Seth",
    "inn.bbs_drinking_game": "GaraBevute",
    "inn.bbs_gossip": "Pettegolezzi",
    "inn.bbs_food": "Cibo",
    "inn.bbs_train": "Allenamento",
    "inn.bbs_gambling": "Bisca",
    "inn.bbs_companions": "Compagni",
    "inn.bbs_rent": "Affitto",
    "inn.bbs_attack": "Attacco",
    "inn.bbs_return": "Ritorno",
    "inn.invalid_choice": "Scelta non valida. Scrivi 'look' per ridisegnare il menu.",
    "inn.drink_menu_title": "MENU BEVANDE",
    "inn.drink_cost": "Una bevanda costa {0} oro. Hai {1} oro.",
    "inn.drink_buy_prompt": "Comprare una bevanda? (S/N): ",
    "inn.drink_cant_afford": "Non puoi permetterti una bevanda!",
    "inn.drink_orders": "{0} ordina una bevanda...",
    "inn.drink_refreshed": "Ti senti rinvigorito! (+{0} PV)",
    "inn.drink_mana_restored": "L'intruglio magico rigenera la tua mente. (+{0} PM)",
    "inn.drink_stamina_restored": "La birra corposa ti rinvigorisce. (+{0} Stamina)",
    "inn.drink_gossip_heard": "Ascolti qualche pettegolezzo utile...",
    "inn.seth_title": "SETH ABLE",
    "inn.seth_level": "Guerriero Livello {0}",
    "inn.seth_hp": "PV: {0}",
    "inn.seth_warning_low": "Seth ti ride in faccia. \"Torna quando sarai cresciuto un po', ragazzino.\"",
    "inn.seth_warning_mid": "Seth ti guarda diffidente. \"Sei sicuro, amico?\"",
    "inn.seth_warning_high": "Seth annuisce con rispetto. \"Un degno sfidante si avvicina.\"",
    "inn.seth_stats_str": "  FOR: {0}",
    "inn.seth_stats_def": "  DIF: {0}",
    "inn.seth_stats_agi": "  AGI: {0}",
    "inn.seth_challenge_prompt": "Sfidare Seth Able a duello? (S/N): ",
    "inn.seth_ready": "Seth si alza, facendo scrocchiare le nocche...",
    "inn.seth_too_low": "Seth è troppo potente per te adesso. Torna più forte!",
    "inn.seth_victory_title": "VITTORIA SU SETH ABLE!",
    "inn.seth_victory_impressed": "Seth si asciuga il sangue dal labbro e sogghigna.",
    "inn.seth_victory_quote": "\"Ben combattuto! Ti sei guadagnato il mio rispetto.\"",
    "inn.seth_victory_xp": "Hai guadagnato {0} PE!",
    "inn.seth_victory_gold": "Seth ti paga {0} oro come scommessa!",
    "inn.seth_victory_teaches": "Seth ti insegna una tecnica di combattimento!",
    "inn.seth_defeat_title": "SCONFITTO DA SETH ABLE",
    "inn.seth_defeat_quote": "Seth rinfodera la spada e ti aiuta ad alzarti.",
    "inn.seth_defeat_advice": "\"Non male, ma non abbastanza. Allenati di più.\"",
    "inn.seth_defeat_cost": "Perdi {0} oro dalla scommessa.",
    "inn.seth_fled_title": "FUGGITO DA SETH ABLE",
    "inn.seth_fled_quote": "Seth scuote la testa mentre ti ritiri.",
    "inn.seth_fled_taunt": "\"Scappi già? Mi aspettavo di più da te.\"",
    "inn.patrons_title": "AVVENTORI DELLA LOCANDA",
    "inn.patrons_none": "La locanda è vuota. Non un'anima in vista.",
    "inn.patrons_count": "Vedi {0} avventori nella locanda:",
    "inn.patrons_npc_entry": "  {0} — {1} (Livello {2})",
    "inn.patrons_interact_prompt": "Parlare con qualcuno? (Inserisci il nome o premi Invio per uscire): ",
    "inn.interact_title": "CONVERSAZIONE CON {0}",
    "inn.interact_alignment": "Allineamento: {0}",
    "inn.interact_mood": "Umore: {0}",
    "inn.interact_relationship": "Relazione: {0}",
    "inn.interact_option_chat": "Chiacchiera",
    "inn.interact_option_challenge": "Sfida a duello",
    "inn.interact_option_gift": "Fai un regalo",
    "inn.interact_option_intimidate": "Intimidisci",
    "inn.interact_option_flirt": "Corteggia",
    "inn.interact_option_leave": "Vai via",
    "inn.challenge_npc_title": "DUELLO CON {0}",
    "inn.challenge_npc_accepts": "{0} accetta la tua sfida!",
    "inn.challenge_npc_declines": "{0} rifiuta la tua sfida.",
    "inn.challenge_npc_afraid": "\"Preferirei non combattere oggi.\"",
    "inn.challenge_npc_victory": "Hai sconfitto {0} in duello!",
    "inn.challenge_npc_xp_gained": "Hai guadagnato {0} PE!",
    "inn.challenge_npc_gold_gained": "Hai vinto {0} oro dal duello!",
    "inn.challenge_npc_defeat": "{0} ti ha sconfitto!",
    "inn.challenge_npc_gold_lost": "Hai perso {0} oro.",
    "inn.challenge_npc_fled": "Sei fuggito da {0}!",
    "inn.gift_prompt": "Fare un regalo a {0}?",
    "inn.gift_option_gold": "Dai {0} oro",
    "inn.gift_option_potion": "Dai una pozione",
    "inn.gift_option_cancel": "Annulla",
    "inn.gift_gold_prompt": "Quanto oro? (Possiedi {0}): ",
    "inn.gift_cant_afford": "Non hai abbastanza oro!",
    "inn.gift_gold_given": "Dai {0} oro a {1}.",
    "inn.gift_reaction_grateful": "{0} è molto riconoscente!",
    "inn.gift_reaction_thanks": "{0} annuisce in segno di ringraziamento.",
    "inn.gift_reaction_suspicious": "{0} accetta con sospetto.",
    "inn.gift_potion_given": "Dai una pozione a {0}.",
    "inn.gift_no_potions": "Non hai pozioni!",
    "inn.mood_ecstatic": "Estatico",
    "inn.mood_happy": "Felice",
    "inn.mood_content": "Soddisfatto",
    "inn.mood_neutral": "Neutrale",
    "inn.mood_annoyed": "Seccato",
    "inn.mood_angry": "Irato",
    "inn.mood_hostile": "Ostile",
    "inn.relationship_enemy": "Nemico",
    "inn.relationship_disliked": "Sgradito",
    "inn.relationship_stranger": "Sconosciuto",
    "inn.relationship_acquaintance": "Conoscente",
    "inn.relationship_friend": "Amico",
    "inn.relationship_close_friend": "Amico Intimo",
    "inn.relationship_best_friend": "Migliore Amico",
    "inn.relationship_lover": "Amante",
    "inn.relationship_spouse": "Consorte",
    "inn.drinking_game_title": "GARA DI BEVUTE",
    "inn.drinking_game_desc": "La gara di bevute è un test di costituzione e fortuna!",
    "inn.drinking_game_rules": "Bevi alla pari col tuo avversario. L'ultimo in piedi vince!",
    "inn.drinking_game_wager_prompt": "Piazza la tua scommessa (da {0} a {1} oro): ",
    "inn.drinking_game_cant_afford": "Non puoi permetterti quella scommessa!",
    "inn.drinking_game_wager_invalid": "Importo della scommessa non valido!",
    "inn.drinking_game_opponent": "Il tuo avversario è {0}, un bevitore navigato.",
    "inn.drinking_game_round": "--- Round {0} ---",
    "inn.drinking_game_you_drink": "Bevi un bel sorso...",
    "inn.drinking_game_opponent_drinks": "{0} beve un bel sorso...",
    "inn.drinking_game_you_steady": "Sei ancora saldo in piedi!",
    "inn.drinking_game_you_wobbly": "Cominci a barcollare...",
    "inn.drinking_game_you_dizzy": "La stanza gira...",
    "inn.drinking_game_you_barely": "Riesci a malapena a tenere gli occhi aperti...",
    "inn.drinking_game_opponent_steady": "{0} sembra impassibile.",
    "inn.drinking_game_opponent_wobbly": "{0} comincia a ondeggiare.",
    "inn.drinking_game_opponent_dizzy": "{0} sta diventando verde.",
    "inn.drinking_game_opponent_barely": "{0} riesce a malapena a stare seduto.",
    "inn.drinking_game_continue": "Continuare a bere? (S/N): ",
    "inn.drinking_game_you_pass_out": "Crolli faccia in giù sul tavolo!",
    "inn.drinking_game_opponent_passes_out": "{0} crolla dallo sgabello!",
    "inn.drinking_game_you_win": "Hai vinto la gara di bevute!",
    "inn.drinking_game_you_lose": "Hai perso la gara di bevute!",
    "inn.drinking_game_gold_won": "Hai vinto {0} oro!",
    "inn.drinking_game_gold_lost": "Hai perso {0} oro!",
    "inn.drinking_game_draw": "Pareggio! Crollate entrambi nello stesso momento.",
    "inn.drinking_game_wager_returned": "La tua scommessa è restituita.",
    "inn.drinking_game_con_bonus": "La tua costituzione è migliorata dalla prova! (+1 COS)",
    "inn.drinking_game_no_opponents": "Non c'è nessuno disposto a bere con te.",
    "inn.soberness_sober": "Sobrio",
    "inn.soberness_tipsy": "Brillo",
    "inn.soberness_drunk": "Ubriaco",
    "inn.soberness_wasted": "Sfatto",
    "inn.soberness_blackout": "Svenuto",
    "inn.drunk_comment_1": "\"Ti ho mai raccontato di quella volta che...\" *hic*",
    "inn.drunk_comment_2": "\"Shei il mio migliore amico, lo shapi?\"",
    "inn.drunk_comment_3": "\"Mi sha che la shtanza gira...\"",
    "inn.drunk_comment_4": "\"Un altro giro! Ce la posso fare!\"",
    "inn.drunk_comment_5": "\"Chi ha messo il pavimento così vicino alla mia faccia?\"",
    "inn.gossip_title": "PETTEGOLEZZI DELLA TAVERNA",
    "inn.gossip_prefix_old_man": "Un vecchio sussurra:",
    "inn.gossip_prefix_barmaid": "La cameriera menziona:",
    "inn.gossip_prefix_merchant": "Un mercante dice:",
    "inn.gossip_prefix_guard": "Una guardia confida:",
    "inn.gossip_prefix_drunk": "Un ubriaco borbotta:",
    "inn.gossip_static_1": "\"Dicono che il dungeon scenda per cento piani...\"",
    "inn.gossip_static_2": "\"Gli antichi dei dormono ancora sotto la terra.\"",
    "inn.gossip_static_3": "\"Mai fidarsi di chi beve da solo alla locanda.\"",
    "inn.gossip_static_4": "\"L'armaiolo ha nuova merce ogni tot livelli.\"",
    "inn.gossip_static_5": "\"C'è un passaggio segreto nel dungeon, dicono.\"",
    "inn.gossip_static_6": "\"Il guaritore chiede troppo, a parer mio.\"",
    "inn.gossip_static_7": "\"Stai lontano dal vicolo buio di notte.\"",
    "inn.gossip_static_8": "\"Il re osserva sempre dal suo castello.\"",
    "inn.gossip_no_rumors": "Nessuno sembra avere pettegolezzi oggi.",
    "inn.rest_title": "RIPOSO AL TAVOLO",
    "inn.rest_lean_back": "Ti appoggi allo schienale e chiudi gli occhi...",
    "inn.rest_hp_recovered": "Hai recuperato {0} PV. (PV: {1}/{2})",
    "inn.rest_mp_recovered": "Hai recuperato {0} PM. (PM: {1}/{2})",
    "inn.rest_sta_recovered": "Hai recuperato {0} Stamina. (Stamina: {1}/{2})",
    "inn.rest_no_recovery": "Non hai bisogno di riposarti adesso.",
    "inn.rest_dream_header": "Ti addormenti e fai uno strano sogno...",
    "inn.sleep_title": "DORMIRE ALLA LOCANDA",
    "inn.sleep_cost": "Una stanza costa {0} oro a notte.",
    "inn.sleep_afford_prompt": "Affittare una stanza? (S/N): ",
    "inn.sleep_cant_afford": "Non puoi permetterti una stanza!",
    "inn.sleep_settle_in": "Ti sistemi sul materasso di paglia e chiudi gli occhi.",
    "inn.sleep_well_rested": "Ti svegli riposato e rigenerato!",
    "inn.sleep_full_hp": "PV completamente ripristinati! ({0}/{1})",
    "inn.sleep_full_mp": "PM completamente ripristinati! ({0}/{1})",
    "inn.sleep_full_sta": "Stamina completamente ripristinata! ({0}/{1})",
    "inn.sleep_fatigue_reduced": "La tua stanchezza si è alleviata.",
    "inn.sleep_new_day": "Un nuovo giorno sorge. (Giorno {0})",
    "inn.sleep_advance_time": "Il tempo scorre mentre riposi...",
    "inn.food_title": "ORDINA DA MANGIARE",
    "inn.food_menu_prompt": "Scegli un pasto:",
    "inn.food_option_stew": "Stufato Sostanzioso ({0}o) - Ripristina {1} PV",
}
