translations = {
    "love_street.beauty_nest": "Nido di Bellezza",
    "love_street.hall_dreams": "Sala dei Sogni",
    "love_street.mingle": "Socializza",
    "love_street.date": "Porta a un Appuntamento",
    "love_street.gift_shop": "NEGOZIO DI REGALI DI VIA DELL'AMORE",
    "love_street.gossip": "Pettegolezzi",
    "love_street.love_potions": "Pozioni d'Amore",
    "love_street.flirt": "Flirta",
    "love_street.flirt_tried": "Flirta (già provato)",
    "love_street.return": "Torna alla Via Principale",
    "love_street.compliment": "Complimenta",
    "love_street.ask_date": "Chiedi un Appuntamento",
    "love_street.talk": "Parla",
    "love_street.romance_stats": "Le Mie Statistiche Romantiche - Consulta la tua storia d'amore",
    "love_street.date_dinner": "Cena Romantica (500o) - Alta cucina e conversazione",
    "love_street.date_walk": "Passeggiata al Chiaro di Luna (gratis) - Una passeggiata mano nella mano",
    "love_street.date_theater": "Spettacolo a Teatro (1000o) - Assistete insieme a uno spettacolo",
    "love_street.date_picnic": "Picnic al Lago (200o) - Momenti tranquilli nella natura",
    "love_street.date_dancing": "Ballo alla Locanda (300o) - Ballate tutta la notte",
    "love_street.header": "VIA DELL'AMORE",
    "love_street.header_visual": "<3 VIA DELL'AMORE <3",
    "love_street.pleasure": "IL PIACERE VI ATTENDE",
    "love_street.beauty_nest_header": "IL NIDO DI BELLEZZA",
    "love_street.hall_dreams_header": "SALA DEI SOGNI",
    "love_street.night_passion": "UNA NOTTE DI PASSIONE",
    "love_street.something_wrong": "QUALCOSA NON VA!",
    "love_street.mingle_header": "SOCIALIZZA",
    "love_street.take_date_header": "PORTA QUALCUNO A UN APPUNTAMENTO",
    "love_street.gossip_header": "PETTEGOLEZZI DI MADAME SUSSURRI",
    "love_street.potions_header": "POZIONI D'AMORE DI MADAME ZARA",
    "love_street.romantic_life": "LA TUA VITA ROMANTICA",
    "love_street.sr_title": "Via dell'Amore",
    "love_street.sr_desc": "L'aria è densa di profumo e promesse. Creature bellissime vi invitano dalle soglie.",
    "love_street.sr_pleasure": "Case del Piacere:",
    "love_street.sr_social": "Socialità:",
    "love_street.potion_charm": "Fascino",
    "love_street.potion_allure": "Seduzione",
    "love_street.potion_passion": "Passione",
    "love_street.active_potions": "Pozioni Attive: {0}",
    "love_street.desc1": "L'aria è densa di profumo e promesse. Le lanterne proiettano un bagliore caldo e invitante",
    "love_street.desc2": "sul selciato. Creature bellissime di ogni razza vi invitano dalle soglie,",
    "love_street.desc3": "mentre clienti ben vestiti si muovono tra i vari locali.",
    "love_street.menu_beauty": " Nido di Bellezza ",
    "love_street.menu_hall": " Sala dei Sogni",
    "love_street.menu_mingle": " Socializza       ",
    "love_street.menu_date": " Appuntamento",
    "love_street.menu_gift": " Negozio Regali   ",
    "love_street.menu_gossip": " Pettegolezzi",
    "love_street.menu_potions": " Pozioni d'Amore ",
    "love_street.menu_return": " Torna alla Via Principale",
    "love_street.potions_label": "  Pozioni:",
    "love_street.potion_charm_tag": " [Fascino]",
    "love_street.potion_allure_tag": " [Seduzione]",
    "love_street.potion_passion_tag": " [Passione]",
    "love_street.bbs_desc": " Profumo e promesse riempiono l'aria. Creature bellissime vi invitano dalle soglie.",
    "love_street.beauty_run_by": "  Gestito da Clarissa la Mezzelfa",
    "love_street.beauty_desc1": "Entrando nel vecchio locale malandato in fondo alla Via dell'Amore,",
    "love_street.beauty_desc2": "notate creature di ogni tipo salire e scendere le scale,",
    "love_street.beauty_desc3": "ciascuna in compagnia di splendidi accompagnatori.",
    "love_street.beauty_madam": "Una grossa e brutta donna troll appare - Clarissa, la maîtresse.",
    "love_street.beauty_looking": "\"Cercate un po' di piacere, bello?\"",
    "love_street.beauty_introduces": "Clarissa vi presenta le cortigiane:",
    "love_street.choose_companion": "Scegliete un accompagnatore (1-9, 0 per uscire): ",
    "love_street.shrug_loss": "{0} alza le spalle. \"Peggio per te, tesoro.\"",
    "love_street.cant_afford_courtesan": "\"Torna quando potrai permettertelo, plebeo!\"",
    "love_street.slink_away": "Ve ne andate via imbarazzati...",
    "love_street.hall_run_by": "  Sotto la supervisione di Giovanni lo Gnomo",
    "love_street.hall_desc1": "Entrate nella hall di questo locale elegante e alla moda.",
    "love_street.hall_desc2": "L'arredamento è costoso, dandovi l'impressione di un albergo di lusso.",
    "love_street.hall_desc3": "Una musica sommessa contribuisce alla piacevole atmosfera.",
    "love_street.hall_giovanni": "Un uomo snello vestito di nero si avvicina.",
    "love_street.hall_hello": "\"Salve, sono Giovanni. Cosa posso fare per voi oggi?\"",
    "love_street.hall_introduces": "Giovanni vi presenta i cicisbei:",
    "love_street.gigolo_bow": "{0} si inchina educatamente. \"Forse un'altra volta.\"",
    "love_street.gigolo_lack_funds": "\"Temo che vi manchino i fondi,\" dice {0} con un sospiro.",
    "love_street.gigolo_heavier": "\"Tornate quando la vostra borsa sarà più pesante.\"",
    "love_street.leave_disappointed": "Ve ne andate, delusi...",
    "love_street.xp_gained": " Esperienza guadagnata: {0}",
    "love_street.dark_points": " Punti oscurità: +{0}",
    "love_street.disease_pain": "Mentre uscite, cominciate a sentire dolore nelle parti intime!",
    "love_street.disease_infected": "Per gli dèi! Siete stati infettati da una malattia venerea!",
    "love_street.disease_rush": "Correte dal Guaritore, implorando aiuto...",
    "love_street.disease_treatments": "I monaci vi somministrano pozioni maleodoranti e trattamenti dolorosi.",
    "love_street.disease_contracted": "Avete contratto il 'Flagello dell'Amante'!",
    "love_street.disease_hp_halved": "I vostri PV sono stati dimezzati! Visitate il Guaritore per curare questa afflizione.",
    "love_street.mingle_nobody": "Non c'è nessuno con cui socializzare in questo momento.",
    "love_street.mingle_try_later": "Provate a tornare più tardi.",
    "love_street.mingle_people": "Gente in Via dell'Amore:\n",
    "love_street.mingle_others": "Altri in giro per la città:\n",
    "love_street.mingle_level_info": " - Livello {0} {1} {2}, Età {3}",
    "love_street.mingle_already_flirted": "\nAvete già provato a flirtare con loro durante questa visita.",
    "love_street.allure_surges": "L'Elisir di Seduzione vi pervade...",
    "love_street.relation_improved": "Il vostro rapporto con {0} è migliorato!",
    "love_street.need_drink_gold": "\nVi servono {0} monete d'oro per offrire da bere.",
    "love_street.buy_drinks": "Fate un cenno al barista e due bevande appaiono. {0} accetta con gratitudine.",
    "love_street.over_drinks": "Bevendo insieme, scoprite che {0} è {1}.",
    "love_street.no_date_partner": "Non avete nessuno da portare a un appuntamento.",
    "love_street.no_date_hint": "Provate prima a socializzare e a migliorare le vostre relazioni!",
    "love_street.who_date": "Con chi vorreste uscire?\n",
    "love_street.could_not_find": "Non è stato possibile trovare {0} in città. Potrebbe essersene andato.",
    "love_street.where_take": "Dove vorreste portarlo?",
    "love_street.maybe_another_time": "Magari un'altra volta...",
    "love_street.need_date_gold": "Vi servono {0} monete d'oro per questa attività!",
    "love_street.date_dinner_title": "* Cena Romantica *",
    "love_street.date_walk_title": "* Passeggiata al Chiaro di Luna *",
    "love_street.date_theater_title": "* Spettacolo a Teatro *",
    "love_street.date_picnic_title": "* Picnic al Lago *",
    "love_street.date_dancing_title": "* Ballo alla Locanda *",
    "love_street.date_relation_improved": "Il vostro rapporto con {0} è migliorato!",
    "love_street.date_kiss": "Alla fine dell'appuntamento, {0} si avvicina per un tenero bacio.",
    "love_street.date_magical": "Il momento è magico...",
    "love_street.passion_warmth": "\nIl calore della Pozione di Passione si diffonde in entrambi...",
    "love_street.gaze_meaningful": "{0} vi guarda in modo significativo...",
    "love_street.accept_invitation": "(Y) Accettate il suo invito",
    "love_street.perhaps_another": "(N) Forse un'altra volta",
    "love_street.gift_welcome": "\"Benvenuti, benvenuti! Cercate qualcosa di speciale per qualcuno di speciale?\"\n",
    "love_street.gift_your_gold": " Il vostro oro: {0}",
    "love_street.gift_who_receive": "Chi dovrebbe ricevere {0}?\n",
    "love_street.gift_no_one": "Non conoscete nessuno abbastanza bene per fare regali.",
    "love_street.gift_meet_people": "Provate prima a incontrare e parlare con la gente!",
    "love_street.gift_would_love": "  (Pensate che {0} ne sarebbe entusiasta!)",
    "love_street.gift_appreciate": "  (Pensate che {0} lo apprezzerebbe.)",
    "love_street.gift_not_romantic": "  ({0} potrebbe non vederlo come romantico...)",
    "love_street.gift_not_accept": "  ({0} potrebbe non accettarlo da voi...)",
    "love_street.gift_purchase": "\nAcquistate {0} e lo presentate a {1}.",
    "love_street.gift_eyes_light": "Gli occhi di {0} si illuminano di gioia!",
    "love_street.gift_accepts_politely": "{0} accetta il regalo con cortesia.",
    "love_street.gift_uncomfortable": "{0} sembra a disagio.",
    "love_street.gift_walks_away": "Se ne va, lasciando il regalo a terra.",
    "love_street.gossip_crone": "Un'antica megera vi fa cenno di avvicinarvi in un'alcova in ombra.",
    "love_street.gossip_no_gold": "\"Niente oro, niente pettegolezzi!\" gracchia Madame Sussurri.",
    "love_street.gossip_tangled": "\n\"Ah, le intricate trame dell'amore...\"\n",
    "love_street.gossip_marriages": "I vostri matrimoni:",
    "love_street.gossip_marriage_line": " <3 {0} & {1} ({2} giorni, {3} figli)",
    "love_street.gossip_npc_couples": "Coppie PNG:",
    "love_street.gossip_npc_couple": " <3 {0} & {1}",
    "love_street.gossip_juicy": "\n\"Oh, volete le cose SUCCOSE...\"\n",
    "love_street.gossip_affair": "Si dice che {0} sia stato visto con {1}",
    "love_street.gossip_recent": "Voci recenti:",
    "love_street.gossip_rumor": " - {0}",
    "love_street.gossip_available": "\n\"Cercate l'amore? Lasciatemi vedere chi è disponibile...\"\n",
    "love_street.gossip_who_investigate": "\n\"Su chi volete che indaghi?\"\n",
    "love_street.gossip_dig_up": "\n\"Ah, {0}... lasciatemi scavare quel che so...\"\n",
    "love_street.gossip_name": " Nome: {0}",
    "love_street.gossip_level_info": " Livello {0} {1} {2}, Età {3}",
    "love_street.gossip_personality": " Segreti della Personalità:",
    "love_street.gossip_married_to": "Sposato con {0}",
    "love_street.gossip_single": "Single",
    "love_street.gossip_not_interested": "Non interessato al vostro tipo",
    "love_street.gossip_excellent": "Corrispondenza eccellente!",
    "love_street.gossip_good": "Buon potenziale",
    "love_street.gossip_needs_work": "Richiede impegno",
    "love_street.potion_crone": "Una vecchia strega sghignazza mentre vi avvicinate al suo calderone ribollente.",
    "love_street.potion_your_gold": " Il vostro oro: {0}",
    "love_street.potion_already_charm": "\n\"Il fascino scorre già in voi, caro!\"",
    "love_street.potion_charm_cost": "\n\"Costa {0} monete d'oro, caro.\"",
    "love_street.potion_charm_drink": "\nBevete il liquido rosa luccicante. Un calore si diffonde in voi.",
    "love_street.potion_charm_effect": "Vi sentite irresistibilmente affascinanti! (+{0} CAR per questa visita)",
    "love_street.potion_already_allure": "\n\"Avete già la magia della seduzione, caro!\"",
    "love_street.potion_allure_cost": "\n\"Costa {0} monete d'oro, caro.\"",
    "love_street.potion_allure_drink": "\nBevete l'elisir dorato. I vostri occhi sembrano brillare di magia.",
    "love_street.potion_allure_effect": "Il vostro prossimo tentativo di flirt sarà assolutamente irresistibile!",
    "love_street.potion_forget_cost": "\n\"Costa {0} monete d'oro, caro.\"",
    "love_street.potion_forget_drink": "\nVersate il liquido azzurro e nebbioso nelle bevande dei vostri partner.",
    "love_street.potion_forget_effect": "La gelosia di {0} partner è stata placata!",
    "love_street.potion_forget_wasted": "Nessuno dei vostri partner era geloso. La pozione è stata sprecata.",
    "love_street.potion_already_passion": "\n\"Avete già la magia della passione, caro!\"",
    "love_street.potion_passion_cost": "\n\"Costa {0} monete d'oro, caro.\"",
    "love_street.potion_passion_drink": "\nBevete la pozione rosso intenso. Il fuoco vi scorre nelle vene.",
    "love_street.potion_passion_effect": "Il vostro prossimo appuntamento si concluderà con un invito garantito all'intimità!",
    "love_street.summary_spouses": " <3 CONIUGI: {0}",
    "love_street.summary_spouse_line": "   - {0} (sposati da {1} giorni, {2} figli)",
    "love_street.summary_lovers": " <3 AMANTI: {0}",
    "love_street.summary_lover_line": "   - {0} (insieme da {1} giorni)",
    "love_street.summary_fwb": " ~ AMICI CON BENEFICI: {0}",
    "love_street.summary_exes": " X RELAZIONI PASSATE: {0}",
    "love_street.summary_encounters": " Incontri intimi totali: {0}",
    "love_street.summary_married_times": " Volte sposati: {0}",
    "love_street.summary_children": " Figli: {0}",
    "love_street.summary_darkness": " Punti oscurità: {0}",
    "team.desc_line1": "Una stanza sul retro piena di fumo con tavoli di legno grezzo. Stendardi delle squadre",
    "team.desc_line2": "pendono dalle travi, e le pareti sono coperte di taglie, sfide e archivi di squadra.",
    "team.your_team": "La Tua Squadra: {0}",
    "team.turf_control_yes": "Controllo del Territorio: SÌ - Questa città è vostra!",
    "team.turf_control_no": "Controllo del Territorio: No",
    "team.no_team_hint": "Non fate parte di nessuna squadra. Createne o unitevi a una per ottenere potere!",
    "team.sr_title": "Angolo delle Squadre Avventuriere",
    "team.sr_turf_yes": "Controllo del Territorio: Sì",
    "team.sr_turf_no": "Controllo del Territorio: No",
    "team.sr_no_team": "Non fate parte di una squadra.",
    "team.sr_info_section": "Informazioni Squadra:",
    "team.sr_actions_section": "Azioni Squadra:",
    "team.sr_comm_section": "Comunicazione:",
    "team.sr_online_section": "Funzioni Online:",
    "team.bbs_team_label": " Squadra: {0}",
    "team.bbs_controls_town": " *CONTROLLA LA CITTÀ*",
    "team.bbs_no_team": " Non fate parte di una squadra. Createne o unitevi a una!",
    "team.bbs_info": " Info:",
    "team.bbs_actions": " Azioni:",
    "team.invalid_choice": "Scelta non valida! Il capo della banda scuote la testa.",
    "team.no_teams_yet": "Non sono ancora state formate squadre.",
    "team.be_first": "Siate i primi a creare una squadra!",
    "team.turf_legend": "* = Controlla il territorio cittadino",
    "team.which_team_info": "Di quale squadra volete informazioni? ",
    "team.info_header": "Informazioni Squadra: {0}",
    "team.not_in_team": "Non appartenete a nessuna squadra.",
    "team.status_header": "Stato Squadra: {0}",
    "team.team_name_label": "Nome Squadra: {0}",
    "team.town_control_yes": "Controllo Città: SÌ - La vostra squadra domina questa città!",
    "team.town_control_no": "Controllo Città: NO",
    "team.team_record": "Archivio Squadra: {0} giorni",
    "team.no_other_members": "Nessun altro membro trovato nella squadra '{0}'.",
    "team.only_member": "(Siete l'unico membro!)",
    "team.status_online": "Online",
    "team.status_offline": "Offline",
    "team.status_alive": "Vivo",
    "team.status_gone": "Scomparso",
    "team.status_dead_label": "Morto",
    "team.total_members": "Totale: {0} membri ({1} giocatori, {2} PNG)",
    "team.online_tag": " [ONLINE]",
    "team.member_dead_tag": " (Morto)",
    "team.already_in_team": "Fate già parte di {0}!",
    "team.quit_current_first": "Dovete prima lasciare la vostra squadra attuale.",
    "team.creation_cost": "Creare una banda costa {0} monete d'oro!",
    "team.you_only_have": "Avete solo {0} monete d'oro.",
    "team.creating_gang": "Creazione di una nuova banda...",
    "team.registration_fee": "Tassa di registrazione: {0} monete d'oro",
    "team.enter_gang_name": "Inserite il nome della banda (max 40 caratteri): ",
    "team.invalid_team_name": "Nome della squadra non valido!",
    "team.team_name_exists": "Una squadra con quel nome esiste già!",
    "team.player_team_exists": "Una squadra di giocatori con quel nome esiste già!",
    "team.enter_gang_password": "Inserite la password della banda (max 20 caratteri): ",
    "team.invalid_password": "Password non valida!",
    "team.gang_created": "Banda '{0}' creata con successo!",
    "team.now_leader": "Siete ora il capo di {0}!",
    "team.paid_registration": "Pagate {0} monete d'oro di tassa di registrazione.",
    "team.which_gang_join": "A quale banda vorreste unirvi? ",
    "team.enter_password": "Inserite la password: ",
    "team.joined_team": "Corretto! Ora fate parte di {0}!",
    "team.wrong_password": "Password errata! Accesso negato.",
    "team.no_active_team": "Nessuna squadra attiva trovata con quel nome!",
    "team.not_in_team_excl": "Non appartenete a nessuna squadra!",
    "team.confirm_quit": "Volete davvero lasciare {0}? (Y/N): ",
    "team.left_team": "Avete lasciato la squadra!",
    "team.must_be_in_team_recruit": "Dovete far parte di una squadra per reclutare membri!",
    "team.create_first_hint": "Create prima una squadra con l'opzione (C)rea squadra.",
    "team.team_full": "La vostra squadra è al completo! (Max {0} membri)",
    "team.team_label": "Squadra: {0}",
    "team.current_size": "Dimensione Attuale: {0}/{1}",
    "team.no_npcs_available": "Nessun PNG disponibile per il reclutamento al momento.",
    "team.try_again_later": "Riprovate più tardi - i PNG si spostano per il mondo!",
    "team.available_recruits": "Reclute Disponibili:",
    "team.your_gold": "Il Vostro Oro: {0}",
    "team.enter_number_recruit": "Inserite un numero per reclutare (0 per annullare): ",
    "team.need_gold_recruit": "Vi servono {0} monete d'oro, ma ne avete solo {1}.",
    "team.npc_joined": "{0} si è unito alla vostra squadra!",
    "team.paid_recruitment": "Avete pagato {0} monete d'oro per il reclutamento.",
    "team.daily_wage": "Paga giornaliera: {0} oro/giorno (detratta automaticamente)",
    "team.recruit_quote": "\"{0} dice: 'Combatterò al vostro fianco, capo!'\"",
    "team.invalid_choice_generic": "Scelta non valida.",
    "team.examine_prompt": "Esaminare quale membro della squadra? (inserite ? per vedere la vostra squadra)",
    "team.member_not_found": "Nessun membro della squadra di nome '{0}' trovato.",
    "team.status_label_alive": "Stato: Vivo",
    "team.status_label_dead": "Stato: Morto",
    "team.enter_current_password": "Inserite la password attuale: ",
    "team.wrong_password_short": "Password errata!",
    "team.enter_new_password": "Inserite la nuova password: ",
    "team.password_changed": "Password cambiata con successo!",
    "team.message_prompt": "Messaggio ai membri della squadra:",
    "team.message_sent": "Messaggio inviato alla squadra!",
    "team.your_message": "Il vostro messaggio: \"{0}\"",
    "team.sack_prompt": "Chi deve essere CACCIATO? (inserite ? per vedere la vostra squadra)",
    "team.confirm_sack": "Volete davvero cacciare {0}? (Y/N): ",
    "team.member_sacked": "{0} è stato cacciato dalla squadra!",
    "team.no_resurrectables": "Nessun membro della squadra può essere resuscitato.",
    "team.permadead_reason_age": "morto di vecchiaia",
    "team.permadead_reason_slain": "ucciso permanentemente",
    "team.all_alive": "Tutti i membri della vostra squadra sono vivi!",
    "team.dead_members_header": "Membri della Squadra Caduti:",
    "team.enter_number_resurrect": "Inserite un numero per resuscitare (0 per annullare): ",
    "team.need_gold_resurrect": "Vi servono {0} monete d'oro per resuscitare {1}!",
    "team.member_resurrected": "{0} è stato resuscitato!",
    "team.resurrect_cost": "Costo: {0} monete d'oro",
    "team.must_be_in_team_allies": "Dovete far parte di una squadra per reclutare alleati giocatori!",
    "team.create_join_first": "Create o unitevi prima a una squadra.",
    "team.no_other_players": "Nessun altro giocatore trovato nella vostra squadra.",
    "team.recruit_players_first": "Reclutate prima altri giocatori nella vostra squadra!",
    "team.available_player_allies": "Alleati Giocatori Disponibili:",
    "team.echo_description": "Il loro eco combatte al vostro fianco nel dungeon.",
    "team.select_ally": "Selezionate un alleato (0 per annullare): ",
    "team.echo_already_in_party": "L'eco di {0} è già nel vostro gruppo!",
    "team.echo_will_join": "L'eco di {0} si unirà alla vostra prossima spedizione nel dungeon!",
    "team.echo_ai_note": "Combatteranno come alleati controllati dall'IA con le loro vere statistiche.",
    "team.no_living_members": "La vostra squadra non ha membri PNG viventi da equipaggiare.",
    "team.team_members_label": "Membri della Squadra:",
    "team.select_member_equip": "Selezionate un membro da equipaggiare (0 per annullare): ",
    "team.equip_header_label": "EQUIPAGGIAMENTO: {0}",
    "team.current_equipment": "Equipaggiamento Attuale:",
    "team.options_label": "Opzioni:",
    "team.offhand_2h": "(usa arma a 2 mani)",
    "team.offhand_empty": "(vuoto)",
    "team.equip_to_header": "EQUIPAGGIA OGGETTO A {0}",
    "team.available_equipment": "Equipaggiamento disponibile:",
    "team.select_item": "Selezionate un oggetto (0 per annullare): ",
    "team.cannot_use_item": "{0} non può usare questo oggetto: {1}",
    "team.which_hand_sr": "Quale mano? M per Mano principale, O per Mano secondaria.",
    "team.equipped_success": "{0} ha equipaggiato {1}!",
    "team.equip_failed": "Equipaggiamento fallito: {0}",
    "team.unequip_header": "RIMUOVI DA {0}",
    "team.no_equipment_unequip": "{0} non ha equipaggiamento da rimuovere.",
    "team.equipped_items": "Oggetti equipaggiati:",
    "team.select_slot_unequip": "Selezionate lo slot da liberare (0 per annullare): ",
    "team.cursed_cannot_remove": "{0} è maledetto e non può essere rimosso!",
    "team.took_item": "Preso {0} da {1}.",
    "team.item_added_inventory": "Oggetto aggiunto al vostro inventario.",
    "team.unequip_failed": "Rimozione dell'oggetto fallita.",
    "team.take_all_confirm": "Prendere TUTTO l'equipaggiamento da {0}?",
    "team.take_all_warning": "Questo lo lascerà senza nulla. Confermate (Y/N): ",
    "team.took_items_count": "Presi {0} oggetto/i da {1}.",
    "team.no_equipment_take": "{0} non aveva equipaggiamento da prendere.",
    "team.cursed_not_removed": "Non è stato possibile rimuovere gli oggetti maledetti: {0}",
    "team.war_must_be_in_team": "Dovete far parte di una squadra per dichiarare guerra!",
    "team.your_team_war_label": "  La Vostra Squadra: {0}",
    "team.active_war_exists": "La vostra squadra ha già una guerra in corso!",
    "team.no_other_teams": "Nessun'altra squadra da sfidare.",
    "team.challenge_team_num": "  Sfida squadra #: ",
    "team.war_wager": "  Posta di guerra: {0} monete d'oro (il vincitore prende tutto)",
    "team.confirm_war": "  Confermate la guerra contro {0}? (Y/N): ",
    "team.not_enough_gold_wager": "  Oro insufficiente per la posta di guerra!",
    "team.no_members_war": "  Una delle squadre non ha membri!",
    "team.war_title": "GUERRA DI SQUADRA: {0} contro {1}",
    "team.round_label": "  Round {0}: ",
    "team.fighter_wins": "- {0} VINCE!",
    "team.war_score": "  Punteggio: {0} - {1}",
    "team.war_spoils": "  Bottino di guerra: {0} monete d'oro!",
    "team.war_lost_gold": "  Persi {0} monete d'oro nella posta di guerra.",
    "team.no_wars_yet": "  Nessuna guerra combattuta finora.",
    "team.hq_must_be_in_team": "Dovete far parte di una squadra per accedere al quartier generale!",
    "team.hq_title": "QUARTIER GENERALE - {0}",
    "team.vault_display": "  Forziere della Squadra: {0} / {1} oro",
    "team.choice_label": "\n  Scelta: ",
    "team.upgrade_num_prompt": "\n  Potenziamento # (1-5): ",
    "team.max_level_reached": "  Livello massimo raggiunto!",
    "team.upgrade_cost_info": "  Potenziare {0} al Lv {1} costa {2} monete d'oro.",
    "team.vault_and_gold": "  Il forziere ha {0}o, voi avete {1}o.",
    "team.vault_not_enough": "  Oro insufficiente nel forziere!",
    "team.personal_not_enough": "  Oro personale insufficiente!",
    "team.facility_upgraded": "\n  {0} potenziato al Livello {1}!",
    "team.vault_full": "\n  Il forziere è pieno! Potenziatelo per più capienza.",
    "team.deposit_prompt": "\n  Quanto depositare? (max {0}): ",
    "team.deposited": "  Depositati {0} monete d'oro nel forziere della squadra!",
    "team.vault_empty": "\n  Il forziere è vuoto.",
    "team.withdraw_prompt": "\n  Quanto prelevare? (il forziere ha {0}): ",
    "team.withdrew": "  Prelevati {0} monete d'oro dal forziere della squadra!",
    "team.withdrawal_failed": "  Prelievo fallito.",
    "team.failed_generic": "  Fallito!",
    "team.menu_rankings": "Classifiche Squadre",
    "team.menu_password": "Cambio Password",
    "team.menu_info": "Info sulle Squadre",
    "team.menu_examine": "Esamina Membro",
    "team.menu_your_status": "Stato della Tua Squadra",
    "team.menu_create": "Crea Squadra",
    "team.menu_join": "Unisciti a una Squadra",
    "team.menu_quit": "Lascia la Squadra",
    "team.menu_apply": "Fai Domanda di Adesione",
    "team.menu_recruit_npc": "Recluta PNG",
    "team.menu_sack": "Caccia Membro",
    "team.menu_equip": "Equipaggia Membro",
    "team.menu_message": "Messaggio ai Compagni",
    "team.menu_resurrect": "Resuscita Compagno",
    "team.menu_recruit_player": "Recluta Alleato Giocatore",
    "team.menu_battle": "Battaglia tra Squadre (Guerra)",
    "team.menu_hq": "Quartier Generale",
    "team.menu_return": "Torna alla Via Principale",
    "team.menu_status": "Stato",
    "team.section_info": "Informazioni Squadra:",
    "team.section_actions": "Azioni Squadra:",
    "team.section_comm": "Comunicazione:",
    "team.section_online": "Funzioni Online:",
    "team.section_nav": "Navigazione:",
    "love_street.risk": "Rischio",
    "love_street.risk_high": "ALTO",
    "love_street.risk_medium": "Medio",
    "love_street.risk_low": "Basso",
    "love_street.risk_very_low": "Molto Basso",
    "love_street.courtesan_wants_gold": "\"{0} vuole vedere {1} monete d'oro prima di qualsiasi cosa.\"",
    "love_street.gigolo_wants_gold": "\"{0} richiede {1} monete d'oro per la serata.\"",
    "love_street.pay_confirm": "Pagare {0} {1} monete d'oro? (Y/N): ",
    "love_street.tag_spouse": "Coniuge",
    "love_street.tag_lover": "Amante",
    "love_street.tag_fwb": "Amicizia+",
    "love_street.tag_friend": "Amico",
    "love_street.tag_wary": "Diffidente",
    "love_street.who_catches_eye": "Chi attira il vostro sguardo? ",
    "love_street.spending_time": "Trascorrere del tempo con {0}",
    "love_street.level_info": "Livello {0} {1} {2}, Età {3}",
    "love_street.relationship": "Relazione",
    "love_street.traits": "Tratti",
    "love_street.buy_drink": "Offri da Bere ({0}o)",
    "love_street.what_do": "Cosa fate? ",
    "love_street.choose_date_activity": "Scegliete un'attività: ",
    "love_street.continue_private": "(Y) Continuate in un luogo più appartato",
    "love_street.another_time": "{0} sorride con comprensione. \"Un'altra volta, allora.\"",
    "love_street.what_buy": "Cosa vorreste comprare? (1-6, 0 per uscire): ",
    "love_street.come_back_shop": "Tornate quando volete!",
    "love_street.gift_too_expensive": "Costa {0} monete d'oro. Non potete permettervelo!",
    "love_street.give_to": "A chi donarlo? (inserite il nome, 0 per annullare): ",
    "love_street.changed_mind": "Avete cambiato idea.",
    "love_street.gift_buy_confirm": "Comprare {0} per {1} per {2} monete d'oro? (Y/N): ",
    "love_street.maybe_next_time": "Magari la prossima volta.",
    "love_street.gift_reaction_love": "\"Oh, che meraviglioso {0}! Lo adoro!\"",
    "love_street.gift_reaction_polite": "\"Grazie, è molto gentile da parte vostra.\"",
    "love_street.gift_reaction_reject": "\"Io... non credo di poter accettare.\"",
    "love_street.gossip_welcome": "\"Che tipo di pettegolezzi cercate, caro?\"",
    "love_street.gossip_menu_together": "Chi sta insieme? ({0}o) - Scoprite coppie e matrimoni",
    "love_street.gossip_menu_scandals": "Scandali! ({0}o) - Tradimenti, inganni e voci succose",
    "love_street.gossip_menu_available": "Chi è disponibile? ({0}o) - Trovate single idonei",
    "love_street.gossip_menu_investigate": "Indaga su qualcuno ({0}o) - Indagine approfondita su chiunque",
    "love_street.gossip_seek": "Quali pettegolezzi cercate? ",
    "love_street.gossip_no_couples": "\"Nessuno si sta corteggiando al momento. Che noia!\"",
    "love_street.gossip_no_scandals": "\"Nessuno scandalo oggi. Che deludente noia!\"",
    "love_street.gossip_behind": "alle spalle di",
    "love_street.gossip_back": "!",
    "love_street.gossip_suspicious": "(Attività sospette)",
    "love_street.gossip_full_affair": "(Una vera e propria tresca!)",
    "love_street.gossip_no_singles": "\"Sembrano tutti impegnati! Che sfortuna.\"",
    "love_street.gossip_eligible_count": "Trovati {0} single idonei:",
    "love_street.gossip_nobody": "\"Non conosco nessuno con quel nome, caro.\"",
    "love_street.investigate_who": "Inserite un nome da investigare: ",
    "love_street.night_pleasure_with": "Una Notte di Piacere con {0}",
    "love_street.label_orientation": "Orientamento",
    "love_street.label_romance": "Romanticismo",
    "love_street.label_commitment": "Impegno",
    "love_street.label_passion": "Passione",
    "love_street.label_flirtiness": "Civetteria",
    "love_street.label_status": "Stato",
    "love_street.label_thinks_of_you": "Pensa di voi",
    "love_street.label_compatibility": "Compatibilità",
    "love_street.trait_hopeless_romantic": "Romantico senza speranza",
    "love_street.trait_enjoys_romance": "Ama il romanticismo",
    "love_street.trait_pragmatic": "Pragmatico in amore",
    "love_street.trait_deeply_loyal": "Profondamente leale",
    "love_street.trait_open_commitment": "Aperto all'impegno",
    "love_street.trait_values_freedom": "Apprezza la libertà",
    "love_street.trait_intensely_passionate": "Intensamente appassionato",
    "love_street.trait_warm_affectionate": "Caloroso e affettuoso",
    "love_street.trait_reserved": "Riservato",
    "love_street.trait_very_flirtatious": "Molto civettuolo",
    "love_street.trait_somewhat_coy": "Un po' schivo",
    "love_street.trait_shy": "Timido e riservato",
    "love_street.potion_welcome": "\"Cercate un po' di... aiuto magico in questioni di cuore?\"",
    "love_street.potion_menu_charm": "Pozione del Fascino ({0}o) - +{1} CAR per questa visita",
    "love_street.potion_menu_allure": "Elisir di Seduzione ({0}o) - Flirt garantito con successo",
    "love_street.potion_menu_forget": "Pozione dell'Oblio ({0}o) - Riduce la gelosia del partner di {1}",
    "love_street.potion_menu_passion": "Pozione della Passione ({0}o) - Intimità garantita all'appuntamento",
    "love_street.active": "ATTIVA",
    "love_street.what_catches_eye": "Cosa attira il vostro sguardo? ",
    "love_street.rel_deeply_in_love": "Profondamente innamorato",
    "love_street.rel_very_fond": "Molto affezionato",
    "love_street.rel_friendly": "Amichevole",
    "love_street.rel_neutral": "Neutrale",
    "love_street.rel_wary": "Diffidente",
    "love_street.rel_dislikes": "Vi detesta",
    "love_street.rel_hostile": "Ostile",
    "love_street.hint_flirtatious": "civettuolo",
    "love_street.hint_romantic": "romantico",
    "love_street.hint_passionate": "appassionato",
    "love_street.hint_gentle": "gentile",
    "love_street.hint_devoted": "devoto",
    "love_street.hint_free_spirited": "spirito libero",
    "love_street.seems_trait": "Sembra {0}",
    "love_street.seems_reserved": "Difficile da decifrare",
    "love_street.orient_straight": "Preferisce il sesso opposto",
    "love_street.orient_same_sex": "Preferisce lo stesso sesso",
    "love_street.orient_all": "Attratto da tutti",
    "love_street.orient_asexual": "Non interessato all'intimità fisica",
    "love_street.orient_demisexual": "Necessita prima di un profondo legame emotivo",
    "love_street.orient_unknown": "Sconosciuto",
    "love_street.date_with": "APPUNTAMENTO CON {0}",
    "team.bbs_rankings": "Classifiche",
    "team.bbs_password": "Password",
    "team.bbs_examine": "Esamina",
    "team.bbs_your_team": "TuaSquadra",
    "team.bbs_create": "Crea",
    "team.bbs_join": "Unisciti",
    "team.bbs_quit_team": "Lascia",
    "team.bbs_apply": "Domanda",
    "team.bbs_recruit_npc": "ReclutaPNG",
    "team.bbs_sack_member": "CacciaMbr",
    "team.bbs_equip_mbr": "EquipMbr",
    "team.bbs_message": "Messaggio",
    "team.bbs_resurrect": "Resuscita",
    "team.bbs_recruit_ally": "ReclutaAll",
    "team.bbs_team_battle": "Battaglia",
    "team.bbs_hq": "QG",
    "team.bbs_main_street": "ViaPrincip",
    "team.col_num": "#",
    "team.col_name": "Nome",
    "team.col_class": "Classe",
    "team.col_level": "Liv",
    "team.col_cost": "Costo",
    "team.col_wage": "Paga/Giorno",
    "team.col_level_full": "Livello",
    "team.col_status": "Stato",
    "team.col_team": "Squadra",
    "team.col_members": "Membri",
    "team.slot_main_hand": "Mano Principale",
    "team.slot_off_hand": "Mano Secondaria",
    "team.slot_head": "Testa",
    "team.slot_body": "Corpo",
    "team.slot_arms": "Braccia",
    "team.slot_hands": "Mani",
    "team.slot_legs": "Gambe",
    "team.slot_feet": "Piedi",
    "team.slot_cloak": "Mantello",
    "team.slot_neck": "Collo",
    "team.slot_left_ring": "Anello Sinistro",
    "team.slot_right_ring": "Anello Destro",
    "team.which_hand_visual": "Quale mano? [",
    "team.which_hand_main": "]ano principale o [",
    "team.which_hand_off": "]ano secondaria?",
    "team.examine_level": "  Livello: {0}  Classe: {1}  Razza: {2}",
    "team.examine_hp": "  PV: {0}/{1}  Mana: {2}/{3}",
    "team.examine_stats1": "  FOR: {0}  DES: {1}  AGI: {2}  COS: {3}",
    "team.examine_stats2": "  INT: {0}  SAG: {1}  CAR: {2}  DIF: {3}",
    "team.war_win": "VITTORIA",
    "team.war_loss": "SCONFITTA",
    "team.war_vs": "contro {0} ",
    "team.war_record": "({0}-{1}) {2}o",
    "team.pay_from_prompt": "  Pagare dal [",
    "team.pay_vault": "]orziere o dall'oro [",
    "team.pay_personal": "]ersonale? ",
    "team.facility_lv": "Lv {0}",
    "team.facility_upgrade_cost": "[Potenziamento: {0}o]",
    "team.news_war_result": "La squadra {0} ha vinto la guerra tra {1} e {2}! ({3}-{4})",
    "team.upgrade_armory": "Armeria",
    "team.upgrade_armory_desc": "+5% attacco per livello",
    "team.upgrade_barracks": "Caserma",
    "team.upgrade_barracks_desc": "+5% difesa per livello",
    "team.upgrade_training": "Campo di Addestramento",
    "team.upgrade_training_desc": "+5% bonus PE per livello",
    "team.upgrade_vault": "Forziere",
    "team.upgrade_vault_desc": "+50.000 capienza forziere/lv",
    "team.upgrade_infirmary": "Infermeria",
    "team.upgrade_infirmary_desc": "+10% guarigione per livello",
    "team.rank_col_rank": "Pos",
    "team.rank_col_name": "Nome Squadra",
    "team.rank_col_mbrs": "Mbri",
    "team.rank_col_power": "Potenza",
    "team.rank_col_avg_lvl": "Liv Med",
    "team.rank_col_turf": "Territ",
    "team.you_suffix": "(Voi)",
    "team.detail_col_name": "Nome",
    "team.detail_col_class": "Classe",
    "team.detail_col_lvl": "Livello",
    "team.detail_col_hp": "PV",
    "team.detail_col_location": "Posizione",
    "team.detail_col_status": "Stato",
}
