translations = {
    "main_street.header": "VIA PRINCIPALE",
    "main_street.hall_fame": "ALBO D'ONORE",
    "main_street.citizens": "CITTADINI DEL REAME",
    "main_street.statistics": "STATISTICHE DEL GIOCATORE",
    "main_street.achievements": "IMPRESE",
    "main_street.attack": "ATTACCA QUALCUNO",
    "main_street.session_summary": "RIEPILOGO SESSIONE",
    "main_street.settings": "IMPOSTAZIONI E SALVATAGGIO",
    "main_street.preferences": "PREFERENZE DI GIOCO",
    "main_street.help": "AIUTO E COMANDI",
    "main_street.journey": "IL TUO VIAGGIO",
    "main_street.section_players": "GIOCATORI",
    "main_street.section_combat": "COMBATTIMENTO",
    "main_street.section_economy": "ECONOMIA",
    "main_street.section_experience": "ESPERIENZA",
    "main_street.section_exploration": "ESPLORAZIONE",
    "main_street.section_survival": "SOPRAVVIVENZA",
    "main_street.section_time": "TEMPO",
    "main_street.section_combat_speed": "VELOCITÀ COMBATTIMENTO",
    "main_street.section_daily_cycle": "MODALITÀ CICLO GIORNALIERO",
    "main_street.section_autosave": "IMPOSTAZIONI SALVATAGGIO AUTOMATICO",
    "main_street.section_delete_saves": "ELIMINA FILE DI SALVATAGGIO",
    "main_street.section_save_info": "INFORMAZIONI FILE DI SALVATAGGIO",
    "main_street.section_force_reset": "FORZARE RESET GIORNALIERO",
    "main_street.section_seals": "I SETTE SIGILLI",
    "main_street.section_old_gods": "GLI ANTICHI DÈI",
    "main_street.section_ocean": "FILOSOFIA DELL'OCEANO",
    "main_street.section_alignment": "ALLINEAMENTO",
    "main_street.menu_title": "Menu Via Principale",
    "main_street.menu_dungeons_suffix": "otterranei  ",
    "main_street.menu_weapon_suffix": "rmi         ",
    "main_street.menu_armor_suffix": "rmature     ",
    "main_street.menu_magic_suffix": "agia        ",
    "main_street.menu_inn_suffix": "ocanda      ",
    "main_street.menu_healer": "Guaritore  ",
    "main_street.menu_quest_hall": "Sala Missioni",
    "main_street.menu_master": "Maestro",
    "main_street.menu_castle": "Castello   ",
    "main_street.menu_home_suffix": "asa",
    "main_street.menu_dark_alley": "Vicolo Buio",
    "main_street.menu_love_st": "Via Amore  ",
    "main_street.menu_church_suffix": "hiesa Antica",
    "main_street.menu_auction": "Asta",
    "main_street.menu_challenges_suffix": "fide       ",
    "main_street.menu_lodging_suffix": "lloggio    ",
    "main_street.menu_stats": "Statistiche",
    "main_street.menu_progress_suffix": "rogressi",
    "main_street.menu_team_corner": "Angolo Squadra",
    "main_street.menu_outskirts": "Periferia",
    "main_street.menu_bank_suffix": "anca       ",
    "main_street.menu_temple_suffix": "empio      ",
    "main_street.menu_news_suffix": "otizie     ",
    "main_street.menu_fame_suffix": "ama        ",
    "main_street.menu_explore_suffix": "splora Terre",
    "main_street.menu_status_suffix": "tato  ",
    "main_street.menu_quit_suffix": "sci        ",
    "main_street.menu_settings": "Impostazioni",
    "main_street.menu_chat_short": "Chat ",
    "main_street.menu_news_short": "Notizie ",
    "main_street.menu_arena_short": "Arena ",
    "main_street.menu_boss_short": "Boss",
    "main_street.menu_chat_padded": "Chat         ",
    "main_street.menu_news_padded": "Notizie      ",
    "main_street.menu_arena_padded": "Arena (PvP)  ",
    "main_street.menu_inv": "Inv ",
    "main_street.menu_help_short": "Aiuto ",
    "main_street.menu_prefs": "Pref  ",
    "main_street.menu_bug": "Bug",
    "main_street.menu_dormitory_padded": "Dormitorio  ",
    "main_street.menu_inn": "Locanda",
    "main_street.menu_home_padded": "Casa        ",
    "main_street.menu_cancel": "Annulla",
    "main_street.section_locations": "Luoghi:",
    "main_street.section_shops": "Negozi:",
    "main_street.section_services": "Servizi:",
    "main_street.section_info": "Informazioni:",
    "main_street.section_exploration_label": "Esplorazione:",
    "main_street.section_other": "Altro:",
    "main_street.players_online": "Giocatori online",
    "main_street.to_chat": "per chattare",
    "main_street.for_player_list": "per la lista giocatori",
    "main_street.online_label": "Online:",
    "main_street.online_header": "Online",
    "main_street.whos_online": "Chi è Online",
    "main_street.chat": "Chat",
    "main_street.news_feed": "Notizie",
    "main_street.arena_pvp": "Arena (PvP)",
    "main_street.world_boss": "Boss Mondiale",
    "main_street.broadcast_chat": "Messaggio globale",
    "main_street.private_message": "Messaggio privato",
    "main_street.see_online": "Vedi giocatori online",
    "main_street.recent_news": "Notizie recenti",
    "main_street.ambient_merchant": "Un mercante sbraita il prezzo delle sue merci.",
    "main_street.ambient_crowd": "La folla si muove e mormora attorno a te.",
    "main_street.ambient_bell": "Una campana lontana batte le ore.",
    "main_street.ambient_cart": "Le ruote dei carri risuonano sul selciato.",
    "main_street.ambient_bread": "Il vento porta il profumo di pane fresco da una bancarella vicina.",
    "main_street.ambient_dog": "Un cane abbaia da qualche parte in un vicolo.",
    "main_street.ambient_guards": "Due guardie si scambiano parole al passaggio.",
    "main_street.desc_standing": "Ti trovi sulla via principale di {0}.",
    "main_street.desc_air": "L'aria {0} è {1}.",
    "main_street.bbs_desc": " Le strade {0} di {1}. L'aria è {2}.",
    "main_street.you_notice": " Noti: ",
    "main_street.and_others": ", e {0} altr{1}",
    "main_street.new_adventurer_prefix": "Nuovo avventuriero? Premi ",
    "main_street.new_adventurer_key": "[D]",
    "main_street.new_adventurer_suffix": " per entrare nei Sotterranei!",
    "main_street.training_points": "Hai {0} punti addestramento! Visita il Maestro per spenderli!",
    "main_street.vex_teaser1": "  Uno sconosciuto dalle dita veloci si fa strada tra la folla.",
    "main_street.vex_teaser2": "  Incrocia il tuo sguardo, ti fa l'occhiolino e svanisce nella folla.",
    "main_street.lyris_teaser1": "  Una donna incappucciata attraversa la folla, le labbra che si muovono in una preghiera silenziosa.",
    "main_street.lyris_teaser2": "  Ti lancia un'occhiata fugace. Qualcosa nei suoi occhi ti inquieta.",
    "main_street.god_slayer_buff": "Il potere divino scorre in te. ({0} combattimenti rimanenti)",
    "main_street.bbs_main_street": "VIA PRINCIPALE",
    "main_street.numpad_hint": " Tastierino: 1=Guaritore 2=Missioni 3=Armi 4=Armature 5=Tempio 6=Castello 7=Casa 8=Maestro",
    "main_street.level_eligible_sr": "Puoi avanzare di livello! Visita il tuo Maestro per progredire!",
    "main_street.level_eligible": "     * Puoi avanzare di livello! Visita il tuo Maestro per progredire! *    ",
    "main_street.team_corner_level_req": "Devi essere almeno livello 5 per accedere all'Angolo Squadra.",
    "main_street.nav_temple": "Entri nel Tempio degli Dèi...",
    "main_street.nav_love_street": "Ti dirigi verso Via Amore...",
    "main_street.nav_dark_alley": "Ti dirigi verso il Vicolo Buio...",
    "main_street.nav_settlement": "Ti dirigi oltre le porte verso l'insediamento...",
    "main_street.nav_team_corner": "Ti dirigi verso l'Angolo degli Avventurieri...",
    "main_street.invalid_choice": "Scelta non valida! Digita ? per l'aiuto.",
    "main_street.good_deeds_title": "Buone Azioni",
    "main_street.good_deeds_divider": "============",
    "main_street.your_chivalry": "La tua Cavalleria: {0}",
    "main_street.deeds_left": "Buone azioni rimaste oggi: {0}",
    "main_street.available_deeds": "Buone azioni disponibili:",
    "main_street.deed_give_gold": "1. Dona oro ai poveri",
    "main_street.deed_help_temple": "2. Aiuta al tempio",
    "main_street.deed_orphanage": "3. Volontariato all'orfanotrofio",
    "main_street.deed_prompt": "Scegli un'azione (1-3, 0 per annullare): ",
    "main_street.deed_done_today": "Hai fatto abbastanza bene per oggi.",
    "main_street.deed_giving_gold": "donando oro ai poveri",
    "main_street.deed_helping_temple": "aiutando al tempio",
    "main_street.deed_volunteering": "facendo volontariato all'orfanotrofio",
    "main_street.deed_generic": "compiendo una buona azione",
    "main_street.deed_chivalry_gain": "Guadagni cavalleria {0}!",
    "main_street.fame_subtitle": "  I Più Grandi Eroi del Reame",
    "main_street.fame_your_rank": "  Il Tuo Rango: #{0} di {1} - {2} (Livello {3})",
    "main_street.fame_page": "  Pagina {0}/{1}",
    "main_street.citizens_adventurers": "AVVENTURIERI ({0} attivi) - Pagina {1}/{2}",
    "main_street.citizens_no_adventurers": "  Nessun avventuriero trovato nel reame.",
    "main_street.citizens_fallen": "CADUTI ({0}) - Pagina {1}/{2}",
    "main_street.citizens_no_fallen": "  Nessun avventuriero caduto.",
    "main_street.citizens_you_tag": "(Tu)",
    "main_street.achieve_unlocked": "  Sbloccate: {0}/{1} ({2}%)",
    "main_street.achieve_points": "  Punti Impresa: {0}",
    "main_street.achieve_categories_label": "Categorie:",
    "main_street.achieve_combat": "  1 - Combattimento",
    "main_street.achieve_progression": "  2 - Progressione",
    "main_street.achieve_economy": "  3 - Economia",
    "main_street.achieve_exploration": "  4 - Esplorazione",
    "main_street.achieve_social": "  5 - Sociale",
    "main_street.achieve_challenge": "  6 - Sfida",
    "main_street.achieve_secret": "  7 - Segreto",
    "main_street.achieve_all": "  A - Tutte",
    "main_street.achieve_categories_visual": "  [1] Combattimento [2] Progressione [3] Economia  [4] Esplorazione",
    "main_street.achieve_categories_visual2": "  [5] Sociale    [6] Sfida       [7] Segreto    [A] Tutte",
    "main_street.achieve_select_prompt": "Seleziona categoria (o premi Invio per Tutte): ",
    "main_street.achieve_unlocked_date": "     Sbloccata: {0}   +{1} pti",
    "main_street.achieve_more_prompt": "Premi Invio per altre, o Q per uscire...",
    "main_street.achieve_header": "IMPRESE: {0}",
    "main_street.attack_no_targets": "  Non c'è nessuno da attaccare qui intorno.",
    "main_street.attack_who_question": "  Chi vuoi attaccare?",
    "main_street.attack_npc_info": " - Livello {0} {1}",
    "main_street.attack_cancel": "  [0] Annulla",
    "main_street.attack_prompt": "Attacca chi? ",
    "main_street.attack_approach": "  Ti avvicini a {0} con intenzioni ostili!",
    "main_street.attack_warning": "  Attenzione: Attaccare i cittadini aumenta la tua Oscurità!",
    "main_street.attack_confirm": "  Sei sicuro? (S/N)",
    "main_street.attack_victory": "  Hai sconfitto {0}!",
    "main_street.attack_defeat": "  {0} ha avuto la meglio su di te...",
    "main_street.attack_cancel_decision": "  Decidi di non farlo.",
    "main_street.attack_change_mind": "  Cambi idea.",
    "main_street.quit_where_sleep": "  Dove dormirai stanotte?",
    "main_street.quit_dormitory_desc": "  Dormitorio: 10 monete d'oro, vulnerabile agli attacchi.",
    "main_street.quit_inn_desc": "  Locanda: sonno protetto con +50% ATT/DIF se attaccato.",
    "main_street.quit_home_desc": "  Casa: al sicuro dietro la tua porta rinforzata.",
    "main_street.quit_home_sleep": "  Sbarri la porta rinforzata e ti addormenti al sicuro...",
    "main_street.quit_street_sleep": "  Ti raggomitoli in strada e ti addormenti...",
    "main_street.quit_dormitory_sleep": "  Ti dirigi al dormitorio e ti addormenti...",
    "main_street.session_duration": "  Durata Sessione: ",
    "main_street.session_monsters": "  Mostri Uccisi: ",
    "main_street.session_damage": "  Danni Inflitti:  ",
    "main_street.session_levels": "  Livelli Guadagnati: ",
    "main_street.session_xp": "  XP Guadagnati:     ",
    "main_street.session_gold": "  Oro Guadagnato:    ",
    "main_street.session_items": "  Oggetti Scambiati: ",
    "main_street.session_items_detail": "{0} comprati, {1} venduti",
    "main_street.session_rooms": "  Stanze Esplorate: ",
    "main_street.saving_progress": "  Salvataggio in corso...",
    "main_street.thanks_playing": "  Grazie per aver giocato a Usurper Reborn!",
    "main_street.press_exit": "  Premi un tasto per uscire...",
    "main_street.settings_current": "Impostazioni Attuali:",
    "main_street.settings_daily_cycle": "  Modalità Ciclo Giornaliero: {0}",
    "main_street.settings_time_of_day": "  Ora del Giorno: {0} ({1})",
    "main_street.settings_autosave": "  Salvataggio automatico: {0}",
    "main_street.settings_current_day": "  Giorno Attuale: {0}",
    "main_street.settings_options": "Opzioni:",
    "main_street.settings_change_cycle": "1. Cambia Modalità Ciclo Giornaliero",
    "main_street.settings_time_note": "1. (Il tempo avanza con le tue azioni; riposa al calar della sera)",
    "main_street.settings_configure_autosave": "2. Configura Salvataggio Automatico",
    "main_street.settings_save_now": "3. Salva Partita Ora",
    "main_street.settings_load_save": "4. Carica un Salvataggio Diverso",
    "main_street.settings_delete_saves": "5. Elimina File di Salvataggio",
    "main_street.settings_view_info": "6. Vedi Informazioni File di Salvataggio",
    "main_street.settings_force_reset": "7. Forza Reset Giornaliero",
    "main_street.settings_game_prefs": "8. Preferenze di Gioco (Velocità Combattimento, Impostazioni Contenuti)",
    "main_street.settings_back": "9. Torna alla Via Principale",
    "main_street.settings_prompt": "Inserisci la tua scelta (1-9): ",
    "main_street.settings_invalid": "Scelta non valida!",
    "main_street.prefs_current": "Impostazioni Attuali:",
    "main_street.prefs_speed_instant": "Istantanea (nessun ritardo)",
    "main_street.prefs_speed_fast": "Veloce (ritardi al 50%)",
    "main_street.prefs_speed_normal": "Normale (ritardi completi)",
    "main_street.prefs_combat_speed": "  Velocità Combattimento: {0}",
    "main_street.prefs_auto_heal": "  Auto-cura in Battaglia: {0}",
    "main_street.prefs_skip_intimate": "  Salta Scene Intime: {0}",
    "main_street.prefs_skip_enabled": "Attivo (Dissolvenza in Nero)",
    "main_street.prefs_skip_disabled": "Disattivo (Scene Complete)",
    "main_street.prefs_enabled": "Attivo",
    "main_street.prefs_disabled": "Disattivo",
    "main_street.prefs_options": "Opzioni:",
    "main_street.prefs_change_speed": "1. Cambia Velocità Combattimento",
    "main_street.prefs_toggle_heal": "2. Attiva/Disattiva Auto-cura in Battaglia",
    "main_street.prefs_toggle_intimate": "3. Attiva/Disattiva Salta Scene Intime",
    "main_street.prefs_back": "4. Torna alle Impostazioni",
    "main_street.prefs_prompt": "Inserisci la tua scelta (1-4): ",
    "main_street.prefs_autoheal_toggled": "L'auto-cura è ora {0}",
    "main_street.prefs_intimate_fade": "Le scene intime ora mostreranno una 'dissolvenza in nero' - un breve riassunto",
    "main_street.prefs_intimate_fade2": "al posto del contenuto romantico dettagliato.",
    "main_street.prefs_intimate_full": "Le scene intime mostreranno ora il contenuto romantico completo.",
    "main_street.speed_choose": "Scegli la velocità del testo di combattimento:",
    "main_street.speed_normal_title": "1. Normale (Consigliata)",
    "main_street.speed_normal_desc1": "   - Ritardi completi tra le azioni di combattimento",
    "main_street.speed_normal_desc2": "   - Migliore per leggere e immergersi",
    "main_street.speed_fast_title": "2. Veloce",
    "main_street.speed_fast_desc1": "   - 50% dei ritardi normali",
    "main_street.speed_fast_desc2": "   - Combattimento più rapido, ancora leggibile",
    "main_street.speed_instant_title": "3. Istantanea",
    "main_street.speed_instant_desc1": "   - Nessun ritardo",
    "main_street.speed_instant_desc2": "   - Velocità massima, il combattimento sfreccia",
    "main_street.speed_prompt": "Seleziona velocità (1-3) o 0 per annullare: ",
    "main_street.speed_changed": "Velocità combattimento cambiata a: {0}",
    "main_street.cycle_available": "Modalità disponibili:",
    "main_street.cycle_session_title": "1. A Sessione (Predefinita)",
    "main_street.cycle_session_desc1": "   - Un nuovo giorno inizia quando esaurisci i turni o scegli di riposare",
    "main_street.cycle_session_desc2": "   - Perfetta per sessioni di gioco casuali",
    "main_street.cycle_realtime_title": "2. Tempo Reale (24 ore)",
    "main_street.cycle_realtime_desc1": "   - Reset giornaliero classico in stile BBS a mezzanotte",
    "main_street.cycle_realtime_desc2": "   - I PNG continuano ad agire mentre sei assente",
    "main_street.cycle_accel4_title": "3. Accelerato (4 ore)",
    "main_street.cycle_accel4_desc1": "   - Nuovo giorno ogni 4 ore reali",
    "main_street.cycle_accel4_desc2": "   - Progressione più rapida per giocatori attivi",
    "main_street.cycle_accel8_title": "4. Accelerato (8 ore)",
    "main_street.cycle_accel8_desc1": "   - Nuovo giorno ogni 8 ore reali",
    "main_street.cycle_accel8_desc2": "   - Progressione bilanciata",
    "main_street.cycle_accel12_title": "5. Accelerato (12 ore)",
    "main_street.cycle_accel12_desc1": "   - Nuovo giorno ogni 12 ore reali",
    "main_street.cycle_accel12_desc2": "   - Progressione più lenta ma costante",
    "main_street.cycle_endless_title": "6. Senza Fine",
    "main_street.cycle_endless_desc1": "   - Nessun limite di turni, gioca quanto vuoi",
    "main_street.cycle_endless_desc2": "   - Perfetta per esplorazione e sperimentazione",
    "main_street.cycle_prompt": "Seleziona modalità (1-6) o 0 per annullare: ",
    "main_street.cycle_changed": "Modalità ciclo giornaliero cambiata a: {0}",
    "main_street.cycle_desc_session": "A Sessione (reset quando i turni si esauriscono)",
    "main_street.cycle_desc_realtime": "Tempo Reale 24 Ore (reset a mezzanotte)",
    "main_street.cycle_desc_accel4": "Accelerato 4 Ore (reset ogni 4 ore)",
    "main_street.cycle_desc_accel8": "Accelerato 8 Ore (reset ogni 8 ore)",
    "main_street.cycle_desc_accel12": "Accelerato 12 Ore (reset ogni 12 ore)",
    "main_street.cycle_desc_endless": "Senza Fine (nessun limite di turni)",
    "main_street.cycle_desc_unknown": "Sconosciuta",
    "main_street.autosave_current": "Salvataggio automatico attuale: {0}",
    "main_street.autosave_enable": "1. Attiva salvataggio automatico",
    "main_street.autosave_disable": "2. Disattiva salvataggio automatico",
    "main_street.autosave_change_interval": "3. Cambia intervallo salvataggio automatico",
    "main_street.autosave_back": "4. Indietro",
    "main_street.autosave_prompt": "Inserisci la tua scelta (1-4): ",
    "main_street.autosave_enabled": "Salvataggio automatico attivato (ogni 5 minuti)",
    "main_street.autosave_disabled": "Salvataggio automatico disattivato",
    "main_street.autosave_interval_prompt": "Inserisci l'intervallo di salvataggio automatico in minuti (1-60): ",
    "main_street.autosave_interval_set": "Intervallo salvataggio automatico impostato a {0} minuti",
    "main_street.autosave_interval_invalid": "Intervallo non valido!",
    "main_street.save_available": "File di salvataggio disponibili:",
    "main_street.save_select": "Seleziona file di salvataggio (1-{0}) o 0 per annullare: ",
    "main_street.save_loading": "Caricamento {0}...",
    "main_street.save_load_note1": "Nota: Caricare un salvataggio diverso richiede il riavvio del gioco.",
    "main_street.save_load_note2": "Esci e riavvia, poi inserisci il nome del personaggio da caricare.",
    "main_street.delete_warning": "ATTENZIONE: Questa azione non può essere annullata!",
    "main_street.delete_select": "Seleziona file da eliminare (1-{0}) o 0 per annullare: ",
    "main_street.delete_success": "File di salvataggio eliminato con successo!",
    "main_street.delete_fail": "Eliminazione del file di salvataggio fallita!",
    "main_street.delete_cancelled": "Eliminazione annullata.",
    "main_street.reset_description1": "Questo attiverà immediatamente un reset giornaliero, ripristinando i",
    "main_street.reset_description2": "limiti giornalieri e avanzando il giorno di gioco.",
    "main_street.reset_completed": "Reset giornaliero completato!",
    "main_street.reset_cancelled": "Reset annullato.",
    "main_street.mail_checking": "Controllo della posta...",
    "main_street.mail_return": "Premi INVIO per tornare alla Via Principale.",
    "main_street.help_return": "Premi Invio per tornare alla Via Principale...",
    "main_street.story_seals_desc": "  Antichi manufatti che rivelano la verità della creazione",
    "main_street.story_seals_collected": "  Sigilli Raccolti: {0}/7   ",
    "main_street.story_seal_found": "Trovato",
    "main_street.story_seal_hidden": "Celato nelle profondità...",
    "main_street.story_seal_name": "    {0} Sigillo di {1} - {2}",
    "main_street.story_gods_desc": "  Esseri antichi che puoi sfidare per potere o saggezza",
    "main_street.story_god_defeated": "SCONFITTO",
    "main_street.story_god_encountered": "Incontrato",
    "main_street.story_god_unknown": "Sconosciuto",
    "main_street.story_god_conquered": "Conquistato",
    "main_street.story_god_known": "Conosciuto",
    "main_street.story_god_hidden": "Da qualche parte nelle profondità...",
    "main_street.story_ocean_desc": "  Il tuo risveglio spirituale attraverso dolore, sacrificio e comprensione",
    "main_street.story_awakening_level": "  Livello di Risveglio: {0}/5",
    "main_street.story_awakening_0": "Non Risvegliato - Vedi solo la superficie delle cose",
    "main_street.story_awakening_1": "Fremito - Qualcosa nel profondo inizia a muoversi",
    "main_street.story_awakening_2": "Increspature - Percepisci connessioni tra tutte le cose",
    "main_street.story_awakening_3": "Correnti - Le profondità ti chiamano con sussurri antichi",
    "main_street.story_awakening_4": "Abissi - Comprendi il dolore dell'oceano",
    "main_street.story_awakening_5": "Illuminato - Sei uno con la marea eterna",
    "main_street.story_grief_none": "In Pace",
    "main_street.story_grief_denial": "In Negazione - La perdita sembra irreale",
    "main_street.story_grief_anger": "Irato - Perché è successo?",
    "main_street.story_grief_bargaining": "Contrattazione - Se solo...",
    "main_street.story_grief_depression": "Depresso - Il peso della perdita",
    "main_street.story_grief_acceptance": "Accettazione - Trovare la pace",
    "main_street.story_grief_label": "  Lutto: {0}",
    "main_street.story_combat_effects": "    Effetti in Combattimento: {0}",
    "main_street.story_align_paragon": "Paladino della Virtù",
    "main_street.story_align_noble": "Nobile Eroe",
    "main_street.story_align_good": "Cuore Buono",
    "main_street.story_align_neutral": "Neutrale",
    "main_street.story_align_questionable": "Discutibile",
    "main_street.story_align_villain": "Malvagio",
    "main_street.story_align_usurper": "Usurper - Incarnazione delle Tenebre",
    "main_street.story_chivalry": "  Cavalleria: {0}  -  {1}",
    "main_street.story_dark_wanted": "RICERCATO dalla Guardia Reale!",
    "main_street.story_dark_suspicious": "Reputazione sospetta",
    "main_street.story_dark_rumored": "Misfatti presunti",
    "main_street.story_dark_clean": "Fedina pulita",
    "main_street.story_darkness": "  Oscurità: {0}  -  {1}",
    "main_street.story_hint_seals": "  Gli antichi sigilli attendono di essere scoperti nelle profondità del sotterraneo...",
    "main_street.story_hint_creator": "  Tutti i sigilli raccolti. Il Creatore attende nelle profondità più remote...",
    "main_street.story_hint_ending": "  Hai completato il tuo viaggio. Cerca il tuo destino.",
    "main_street.story_return": "Premi Invio per tornare alla Via Principale...",
    "main_street.micro_married_walk": "{0} e {1} camminano insieme, condividendo una conversazione tranquilla.",
    "main_street.micro_lovers_walk": "{0} e {1} camminano vicini, parlando a bassa voce.",
    "main_street.micro_fight_won": "{0} cammina con passo baldanzoso. Sembra che abbia avuto la meglio su {1} di recente.",
    "main_street.micro_saw_death": "{0} ha lo sguardo perso nel vuoto, come se avesse visto qualcosa che preferirebbe dimenticare.",
    "main_street.micro_was_attacked": "{0} mostra lividi freschi. Qualcuno ha cercato rissa.",
    "main_street.micro_angry": "{0} ha la mascella serrata. Sembra pronto a colpire qualcosa.",
    "main_street.micro_joyful": "{0} canticchia allegramente mentre passa.",
    "main_street.micro_sad": "{0} siede solo su una panchina, con l'aria di chi avrebbe bisogno di un bicchiere.",
    "main_street.micro_fearful": "{0} continua a guardarsi alle spalle, nervoso per qualcosa.",
    "main_street.micro_gang_huddle": "Un gruppo di membri di una banda si stringe, parlando a bassa voce.",
    "main_street.micro_enemies_wary": "{0} e {1} si squadrano con diffidenza dall'altro lato della strada.",
    "main_street.micro_role_defender": "{0} monta la guardia vicino al cancello, tenendo d'occhio la situazione.",
    "main_street.micro_role_merchant": "{0} sta contrattando rumorosamente con un venditore ambulante.",
    "main_street.micro_role_healer": "{0} sta curando un graffio sul ginocchio di un bambino.",
    "main_street.micro_role_explorer": "{0} sta studiando una mappa consunta, pianificando il prossimo viaggio.",
    "main_street.time_morning": "mattina",
    "main_street.time_afternoon": "pomeriggio",
    "main_street.time_evening": "sera",
    "main_street.time_night": "notte",
    "main_street.weather_clear": "limpida",
    "main_street.weather_cloudy": "nuvolosa",
    "main_street.weather_misty": "nebbiosa",
    "main_street.weather_cool": "fresca",
    "main_street.weather_warm": "calda",
    "main_street.weather_breezy": "ventosa",
    "main_street.dev_access_denied": "  Accesso negato.",
    "main_street.dev_shimmer": "  Noti uno strano luccichio nell'aria...",
    "main_street.dev_reality": "  La realtà sembra piegarsi attorno a te...",
    "main_street.say_prompt": "  Dì: ",
    "main_street.say_you": "  [Tu] {0}",
    "main_street.combat_test_header": "=== TEST COMBATTIMENTO ===",
    "main_street.combat_test_intro": "Un delinquente di strada sbuca fuori e ti blocca il cammino!",
    "main_street.combat_test_weapon": "Il {0} brandisce un {1}!",
    "main_street.combat_test_confirm": "Combatti il delinquente? (S/N): ",
    "main_street.combat_test_temple": "Ti risvegli al Tempio della Luce...",
    "main_street.combat_test_summary": "=== RIEPILOGO COMBATTIMENTO ===",
    "main_street.combat_test_outcome": "Esito Finale: {0}",
    "main_street.combat_test_victory": "Il delinquente fugge nell'ombra!",
    "main_street.combat_test_escaped": "Sfuggi all'incontro pericoloso.",
    "main_street.combat_test_avoided": "Eviti saggiamente lo scontro.",
    "main_street.online_separator": " ── Online ── ",
    "main_street.who_count": "Chi({0}) ",
    "main_street.talk_count": "Parla({0}) ",
    "main_street.status_hp": " PV:",
    "main_street.status_gold": " Oro:",
    "main_street.status_mana": " Mana:",
    "main_street.status_lv": " Lv:",
    "main_street.whos_online_label": "Chi è Online ",
    "main_street.player_count": " giocator{0})",
    "main_street.player_plural": "i",
    "main_street.fame_rank": "Rango",
    "main_street.fame_name": "Nome",
    "main_street.fame_lv": "Lv",
    "main_street.fame_class": "Classe",
    "main_street.fame_location": "Luogo",
    "main_street.fame_experience": "Esperienza",
    "main_street.rip": "R.I.P.",
    "main_street.stat_monsters_slain": "Mostri Uccisi:",
    "main_street.stat_bosses_killed": "Boss Uccisi:",
    "main_street.stat_unique_monsters": "Mostri Unici:",
    "main_street.stat_combat_win_rate": "Tasso Vittorie:",
    "main_street.stat_combats_won": "Combattimenti Vinti:",
    "main_street.stat_combats_lost": "Combattimenti Persi:",
    "main_street.stat_times_fled": "Volte Fuggito:",
    "main_street.stat_player_kills": "Uccisioni PvP:",
    "main_street.stat_damage_dealt": "Danni Totali Inflitti:",
    "main_street.stat_damage_taken": "Danni Subiti:",
    "main_street.stat_highest_hit": "Colpo Singolo Più Alto:",
    "main_street.stat_critical_hits": "Colpi Critici:",
    "main_street.stat_gold_earned": "Oro Totale Guadagnato:",
    "main_street.stat_gold_monsters": "Oro dai Mostri:",
    "main_street.stat_gold_spent": "Oro Speso:",
    "main_street.stat_peak_gold": "Oro Massimo Posseduto:",
    "main_street.stat_items_bought": "Oggetti Comprati:",
    "main_street.stat_items_sold": "Oggetti Venduti:",
    "main_street.stat_xp_earned": "XP Totali Guadagnati:",
    "main_street.stat_level_ups": "Avanzamenti di Livello:",
    "main_street.stat_highest_level": "Livello Più Alto:",
    "main_street.stat_current_level": "Livello Attuale:",
    "main_street.stat_deepest_dungeon": "Sotterraneo Più Profondo:",
    "main_street.stat_floors_explored": "Piani Esplorati:",
    "main_street.stat_chests_opened": "Forzieri Aperti:",
    "main_street.stat_secrets_found": "Segreti Trovati:",
    "main_street.stat_traps_triggered": "Trappole Attivate:",
    "main_street.stat_traps_disarmed": "Trappole Disinnescate:",
    "main_street.stat_deaths_monster": "Morti (Mostri):",
    "main_street.stat_deaths_pvp": "Morti (PvP):",
    "main_street.stat_potions_used": "Pozioni Usate:",
    "main_street.stat_health_restored": "Salute Ripristinata:",
    "main_street.stat_resurrections": "Resurrezioni:",
    "main_street.stat_diseases_cured": "Malattie Curate:",
    "main_street.stat_play_time": "Tempo di Gioco Totale:",
    "main_street.stat_sessions": "Sessioni Giocate:",
    "main_street.stat_created": "Personaggio Creato:",
    "main_street.stat_current_streak": "Serie Attuale:",
    "main_street.stat_longest_streak": "Serie Più Lunga:",
    "main_street.stat_days": "giorni",
    "main_street.stat_difficulty": "  Difficoltà: {0}",
    "main_street.save_entry": "{0}. {1} (Livello {2}, Giorno {3}, {4} turni)",
    "main_street.save_entry_short": "{0}. {1} (Livello {2}, Giorno {3})",
    "main_street.save_saved_at": "   Salvato: {0}",
    "main_street.seal_creation": "Creazione",
    "main_street.seal_first_war": "Prima Guerra",
    "main_street.seal_corruption": "Corruzione",
    "main_street.seal_imprisonment": "Prigionia",
    "main_street.seal_prophecy": "Profezia",
    "main_street.seal_regret": "Rimpianto",
    "main_street.seal_truth": "Verità",
    "main_street.seal_display": "    {0} Sigillo di {1} - {2}",
    "main_street.god_maelketh_title": "Dio della Guerra",
    "main_street.god_terravok_title": "Dio della Terra",
    "main_street.god_manwe_title": "Signore dell'Aria",
    "main_street.grief_damage": "Danno {0}{1}%",
    "main_street.grief_defense": "Difesa {0}{1}%",
    "main_street.grief_combat": "Combattimento {0}{1}%",
    "main_street.grief_all_stats": "Tutte le Stat {0}{1}%",
    "main_street.grief_wisdom": "+{0} Saggezza",
    "main_street.grief_combat_effects": "    Effetti in Combattimento: {0}",
    "home.header": "LA TUA CASA",
    "home.activities": "Attività Domestiche",
    "home.rest": "Riposa e Recupera",
    "home.upgrades": "RISTRUTTURAZIONI DEL MASTRO ARTIGIANO",
    "home.deposit": "Deposita Oggetto",
    "home.withdraw": "Preleva Oggetto",
    "home.list_chest": "Contenuto Baule",
    "home.gather_herbs": "Raccogli Erbe",
    "home.use_herb": "Usa Erba",
    "home.trophies": "Trofei",
    "home.family": "FAMIGLIA E PERSONE CARE",
    "home.partner": "Tempo col Partner",
    "home.bedroom": "Camera da Letto",
    "home.resurrect": "Resurrezione",
    "home.gear_partner": "Equipaggia Partner",
    "home.heal_potion": "Cura (Pozione)",
    "home.sleep": "Dormi (avanza al mattino)",
    "home.wait_night": "Attendi il calar della notte",
    "home.sleep_safe": "Dormi (al sicuro, esci)",
    "home.later_that_night": "PIÙ TARDI QUELLA NOTTE...",
    "home.later": "PIÙ TARDI...",
    "home.equip_partner": "EQUIPAGGIA IL TUO PARTNER",
    "home.herb_garden": "GIARDINO DELLE ERBE",
    "home.relationship_discussion": "DISCUSSIONE SULLA RELAZIONE",
    "home.difficult_conversation": "UNA CONVERSAZIONE DIFFICILE",
    "home.intimate_fantasies": "FANTASIE INTIME",
    "home.alternative_arrangements": "ACCORDI ALTERNATIVI",
    "home.night_to_remember": "UNA NOTTE DA RICORDARE",
    "home.reclamation": "RICONQUISTA",
    "home.the_arrangement": "L'ACCORDO",
    "home.knock_at_door": "Un'ora dopo, qualcuno bussa alla porta...",
    "home.take_your_place": "Prendi il tuo posto...",
    "home.terrible_silence": "UN TERRIBILE SILENZIO",
    "home.marriage_ended": "IL TUO MATRIMONIO È FINITO",
    "home.master_bedroom": "LA CAMERA PADRONALE",
    "main_street.load_save": "CARICA UN SALVATAGGIO DIVERSO",
    "home.stat_hp": "PV: ",
    "home.stat_mana": "Mana: ",
    "home.stat_stamina": "Vigore: ",
    "home.stat_gold": "Oro: ",
    "home.stat_potions": "Pozioni: ",
    "home.stat_rest": "Riposo: ",
    "home.stat_chest": "Baule: ",
    "home.desc_level0": "Ti trovi in una baracca fatiscente e piena di spifferi. Le pareti sono sottili e il tetto perde.",
    "home.desc_level1": "La tua casa ha subito qualche riparazione. Le pareti sono rattoppate, tenendo fuori il peggio del vento.",
    "home.desc_level2": "Una solida casetta con mura robuste e una porta vera. Sembra una vera casa.",
    "home.desc_level3": "Una casa confortevole con buoni mobili e luce calda.",
    "home.desc_level4": "Un bel maniero con arredi di qualità e decorazioni eleganti.",
    "home.desc_level5": "Una grande tenuta degna di un eroe, splendidamente arredata in ogni stanza.",
    "home.bed_level0": " Un mucchio di paglia tarlata ti serve da letto.",
    "home.bed_level1": " Una semplice branda sta nell'angolo.",
    "home.bed_level2": " Un robusto telaio di legno sorregge un materasso sottile.",
    "home.bed_level3": " Un soffice materasso di piume promette un sonno riposante.",
    "home.bed_level4": " Un ornato letto a baldacchino domina la camera.",
    "home.bed_level5": " Un magnifico letto a baldacchino drappeggiato di seta ti attende.",
    "home.hearth_level0": " Un freddo focolare giace inutilizzato.",
    "home.hearth_level1": " Un semplice camino scoppietta con calore.",
    "home.hearth_level2": " Un camino in pietra irradia un calore costante.",
    "home.hearth_level3": " Una stufa in ferro riempie la stanza di un calore confortante.",
    "home.hearth_level4": " Un grande camino ruggisce con fiamme invitanti.",
    "home.hearth_level5": " Una fiamma eterna arde senza combustibile, riempiendo ogni stanza di calore.",
    "home.extra_study": "uno studio pieno di libri",
    "home.extra_servants": "alloggi per la servitù",
    "home.you_also_have": "Hai anche {0}.",
    "home.no_chest": "Non hai ancora un baule. Visita [U]Migliorie per comprarne uno.",
    "home.no_trophy_room": "Non hai ancora una Sala Trofei. Visita le Migliorie per acquistarne una!",
    "home.no_herb_garden": "Non hai un giardino delle erbe. Visita [U]Migliorie per costruirne uno.",
    "home.herbs_gathered_today": "Hai già raccolto tutte le erbe che il tuo giardino può produrre oggi.",
    "home.herb_pouch_empty": "La tua borsa delle erbe è vuota. Raccogli erbe dal tuo giardino a casa.",
    "home.rest_straw_uncomfort": "Il tuo mucchio di paglia è troppo scomodo per riposarci ancora oggi.",
    "home.rest_maxed": "Hai già riposato quanto possibile oggi.",
    "home.rest_straw": "Ti raggomitoli sul mucchio di paglia tarlata...",
    "home.rest_cot": "Ti sdrai sulla tua semplice branda...",
    "home.rest_wooden": "Ti riposi nel tuo letto di legno...",
    "home.rest_comfort": "Ti rilassi nel comfort del tuo letto...",
    "home.rest_grief": "Riposi, ma oscuri ricordi tormentano il tuo sonno...",
    "home.rest_rejuvenated": "Ti senti completamente rinvigorito!",
    "home.sleep_dreams": "Mentre il sonno ti prende, i sogni si dispiegano...",
    "home.sleep_reinforced": "Sbarri la porta rinforzata e ti addormenti al sicuro...",
    "home.sleep_not_evening": "Non è abbastanza tardi per dormire. Prova ad aspettare fino a sera.",
    "home.sleep_straw": "Ti infili nel mucchio di paglia per la notte...",
    "home.sleep_cot": "Ti distendi sulla branda e chiudi gli occhi...",
    "home.sleep_wooden": "Ti arrampichi nel letto di legno e ti copri con la coperta...",
    "home.sleep_comfort": "Ti sistemi nel comfort del tuo letto per un'intera notte di sonno...",
    "home.sleep_grief": "Oscuri ricordi invadono i tuoi sogni, lasciandoti meno che riposato...",
    "home.sleep_refreshed": "Ti svegli sentendoti completamente riposato!",
    "home.sleep_drift": "Ti addormenti...",
    "home.herb_which": "Quale erba vorresti raccogliere?",
    "home.herb_done": "Raccolta terminata",
    "home.herb_done_msg": "Ti spolveri le mani dalla terra e rientri.",
    "home.herb_pouch_title": "BORSA DELLE ERBE",
    "home.herb_select": "Seleziona un'erba da usare:",
    "home.herb_cancel": "Annulla",
    "home.potion_mastery_enhance": "La Maestria nelle Pozioni potenzia l'effetto!",
    "home.potion_mastery_extend": "La Maestria nelle Pozioni prolunga la durata!",
    "home.chest_empty": "Il tuo baule è vuoto.",
    "home.chest_select_withdraw": "Seleziona il numero dell'oggetto da prelevare (o 0 per annullare):",
    "home.chest_items": "Oggetti nel tuo baule:",
    "home.chest_empty_label": "  (vuoto)",
    "home.chest_upgrade": "Migliora il tuo baule per conservare più oggetti.",
    "home.trophies_title": "Trofei e Imprese",
    "home.no_items_equip": "Nessun oggetto da equipaggiare.",
    "home.equip_which_finger": "Equipaggia a quale dito?",
    "home.equip_onehand_where": "Questa è un'arma a una mano. Dove vuoi equipaggiarla?",
    "home.equip_main_hand": "Mano Principale: ",
    "home.equip_off_hand": "Mano Secondaria: ",
    "home.bed_cold_empty": "Il tuo letto sembra freddo e vuoto...",
    "home.bed_find_someone": "Forse dovresti trovare qualcuno di speciale con cui condividerlo.",
    "home.partner_not_home": "Il tuo partner non è a casa in questo momento.",
    "home.partner_elsewhere": "Potrebbe essere alla Via Principale o altrove in città.",
    "home.join_in_bed": "Raggiungi {0} a letto",
    "home.leave_bedroom": "Lascia la camera da letto",
    "home.leave_bedroom_msg": "Lasci silenziosamente la camera da letto.",
    "home.multiple_partners": "Diversi partner ti aspettano...",
    "home.upgrade_room_title": "--- Migliorie Stanza ---",
    "home.upgrade_special_title": "--- Acquisti Speciali ---",
    "home.upgrade_return": "Torna",
    "home.upgrade_success": "*** {0} ACQUISTATO! ***",
    "home.upgrade_craftsmen": "Gli artigiani si mettono subito al lavoro...",
    "home.upgrade_home_done": "La tua casa è stata migliorata!",
    "home.upgrade_cancelled": "Acquisto annullato.",
    "home.upgrade_max_level": "{0} è già al livello massimo!",
    "home.upgrade_need_gold": "Ti servono {0} monete d'oro per {1}!",
    "home.upgrade_only_have": "Hai solo {0} monete d'oro.",
    "home.upgrade_confirm": "Acquistare {0} per {1} monete d'oro?",
    "home.upgraded_to": "Migliorato a {0}!",
    "home.fertility_removed": "Penalità di fertilità rimossa!",
    "home.fertility_bonus": "Bonus fertilità: +{0}%",
    "home.study_desc": "Un magnifico studio pieno di antichi tomi!",
    "home.study_bonus": "+{0}% XP da tutti i combattimenti.",
    "home.servants_desc": "Un servizio fedele si trasferisce negli alloggi della servitù!",
    "home.reinforced_door_desc": "Una pesante porta cerchiata di ferro viene installata!",
    "home.reinforced_door_safe": "Ora puoi dormire al sicuro a casa nella modalità online.",
    "home.training_room_upgrade": "Sala d'Addestramento migliorata al livello {0}!",
    "home.training_room_bonus": "+1 a TUTTE le statistiche base!",
    "home.armory_installed": "Armeria Leggendaria installata!",
    "home.armory_bonus": "+5% danno e +5% difesa permanentemente!",
    "home.fountain_installed": "Fontana della Vitalità costruita!",
    "home.no_lovers": "Non hai amanti o partner.",
    "home.all_alive": "Tutti i tuoi alleati sono in vita!",
    "home.dead_team_members": "Membri della Squadra Caduti:",
    "home.resurrect_need_gold": "Ti servono {0} monete d'oro per resuscitare {1}!",
    "home.resurrect_success": "{0} è stato resuscitato!",
    "home.resurrect_cost": "Costo: {0} monete d'oro",
    "home.upgrade_sr_maxed": "  {0}. {1} MASSIMO - {2} Lv {3}, {4}",
    "home.upgrade_sr_next": "  {0}. {1} Lv {2}{3}, {4}o, {5}",
    "home.upgrade_maxed_label": " MASSIMO - {0} (Lv {1}) [{2}]",
    "home.upgrade_otp_sr_owned": "  {0}. {1} - POSSEDUTO",
    "home.upgrade_otp_sr_buy": "  {0}. {1}, {2}o - {3}",
    "home.upgrade_otp_owned": "  [{0}] {1} - POSSEDUTO",
    "home.no_spouse_equip": "Non hai un coniuge o amante da equipaggiare.",
    "home.no_spouse_find_love": "Trova prima l'amore, poi equipaggiali per l'avventura!",
    "home.your_partners": "I Tuoi Partner:",
    "home.select_partner": "Seleziona partner da equipaggiare (0 per annullare): ",
    "home.current_equipment": "Equipaggiamento Attuale:",
    "home.options": "Opzioni:",
    "home.equip_from_inventory": "Equipaggia oggetto dall'inventario",
    "home.unequip_item": "Rimuovi oggetto equipaggiato",
    "home.take_all_equipment": "Prendi tutto il loro equipaggiamento",
    "home.done_return": "Fatto / Torna",
    "home.using_2h": "(usa arma a 2M)",
    "home.slot_empty": "(vuoto)",
    "home.available_equipment": "Equipaggiamento disponibile:",
    "home.cannot_use_item": "{0} non può usare questo oggetto: {1}",
    "home.which_hand": "Quale mano? ",
    "home.main_or_off": "ano principale o ",
    "home.off_hand_q": "econdaria?",
    "home.equipped_item": "{0} ha equipaggiato {1}!",
    "home.equipped_items": "Oggetti equipaggiati:",
    "home.select_unequip": "Seleziona slot da rimuovere (0 per annullare): ",
    "home.cursed_no_remove": "Il {0} è maledetto e non può essere rimosso!",
    "home.took_item": "Preso {0} da {1}.",
    "home.item_to_inventory": "Oggetto aggiunto al tuo inventario.",
    "home.unequip_failed": "Rimozione dell'oggetto fallita.",
    "home.take_all_confirm": "Prendere TUTTO l'equipaggiamento da {0}?",
    "home.take_all_warning": "Rimarranno senza niente. Conferma (S/N): ",
    "home.took_items": "Presi {0} oggetto/i da {1}.",
    "home.no_equipment_take": "{0} non aveva equipaggiamento da prendere.",
    "home.cursed_not_removed": "Impossibile rimuovere oggetti maledetti: {0}",
    "home.partners_here": "{0} {1} qui con te",
    "home.partners_is": "è",
    "home.partners_are": "sono",
    "home.children_count": " ({0} figli{1})",
    "home.children_ren": "",
    "home.children_here": "I tuoi {0} figli{1} qui.",
    "home.children_ren_are": " sono",
    "home.children_is": " è",
    "home.partner_at_location": "  {0} è a {1}.",
    "home.bbs_desc_level0": " Una baracca piena di spifferi con un tetto che perde e paglia tarlata.",
    "home.bbs_desc_level1": " Una casa rattoppata. Le pareti tengono fuori il peggio del vento.",
    "home.bbs_desc_level2": " Una solida casetta con mura robuste. Sembra una vera casa.",
    "home.bbs_desc_level3": " Una casa confortevole con buoni mobili e luce calda.",
    "home.bbs_desc_level4": " Un bel maniero con decorazioni eleganti. L'invidia dei cittadini.",
    "home.bbs_desc_level5": " Una grande tenuta degna di un eroe. Lusso e serenità ovunque.",
    "home.bbs_partners_here": " {0} qui",
    "home.bbs_children": " {0} figli{1}",
    "home.bbs_rest_label": " Riposo:{0}/{1}({2}%)",
    "home.bbs_chest_label": "  Baule:{0}/{1}",
    "home.bbs_potions_label": "  Pozioni:",
    "home.rest_used_today": "Riposi usati: {0}/{1}. Riprova domani.",
    "home.rest_recovered_mana": "Recuperati {0} PV e {1} mana. ({2}% recupero)",
    "home.rest_recovered_hp": "Recuperati {0} PV. ({1}% recupero)",
    "home.rest_fatigue_refreshed": "Ti senti rinvigorito. (Fatica -{0})",
    "home.rest_hearth_buff": "Il calore del tuo focolare ti rinvigorisce! (+{0}% danno/difesa per {1} combattimenti)",
    "home.rest_remaining": "Riposi rimanenti oggi: {0}/{1}",
    "home.sleep_recovered_mana": "Recuperati {0} PV, {1} mana. ({2}% recupero)",
    "home.sleep_recovered_stamina": "Recuperati {0} PV, {1} vigore. ({2}% recupero)",
    "home.sleep_new_day": "Un nuovo giorno sorge. (Giorno {0})",
    "home.herb_gathers_remaining": "Raccolte rimanenti oggi: {0}",
    "home.herb_gathered_count": "Erbe raccolte: {0}/{1}. Riprova domani.",
    "home.herb_pouch_full": "La tua borsa è piena di {0}! ({1}/{2})",
    "home.herb_gathered": "Raccolta una {0}! ({1}/{2})",
    "home.herb_active_buff": "Potenziamento attivo: {0} ({1} combattimenti rimanenti)",
    "home.herb_healing_use": "Schiacchi una {0} e ne bevi l'estratto. Ripristinati {1} PV! ({2}/{3})",
    "home.herb_ironbark_use": "Mastichi una dura {0}. La tua pelle si indurisce! (+{1}% difesa per {2} combattimenti)",
    "home.herb_firebloom_use": "Inali il profumo ardente di un {0}. I tuoi colpi bruciano di potere! (+{1}% danno per {2} combattimenti)",
    "home.herb_swift_use": "Il {0} invia energia attraverso le tue membra! (+{1} attacco extra per {2} combattimenti)",
    "home.herb_starbloom_use": "L'essenza di fiore stellare inonda la tua mente di chiarezza arcana! Ripristinati {0} mana. (+{1}% danno magico per {2} combattimenti)",
    "home.chest_full": "Il tuo baule è pieno! ({0}/{1} oggetti)",
    "home.chest_deposit_select": "Seleziona oggetto da depositare ({0}/{1} conservati, o 0 per annullare):",
    "home.chest_stored": "{0} conservato nel baule. ({1}/{2})",
    "home.chest_retrieved": "{0} prelevato dal baule.",
    "home.trophies_total_unlocked": "  Totale Sbloccati: {0} / {1}",
    "home.trophies_points": "  Punti Impresa: {0}",
    "home.trophies_completion": "  Completamento: {0}%",
    "home.trophies_none": "  Nessuna impresa sbloccata ancora.",
    "home.trophies_hint1": "  Esplora il sotterraneo, sconfiggi mostri e completa",
    "home.trophies_hint2": "  sfide per ottenere imprese e ricompense!",
    "home.potion_full_health": "Sei già in piena salute!",
    "home.potion_none": "Non hai pozioni curative!",
    "home.potion_buy_hint": "Visita il Guaritore o il Negozio di Magia per comprarne.",
    "home.potion_drink": "Bevi una pozione curativa...",
    "home.potion_restored": "Ripristinati {0} PV! ({1}/{2})",
    "home.potion_remaining": "Pozioni rimanenti: {0}",
    "home.inventory_title": "=== IL TUO INVENTARIO ===",
    "home.inventory_empty": "  Il tuo inventario è vuoto.",
    "home.inventory_value": " (Valore: {0} oro)",
    "home.inventory_options": "Opzioni: ",
    "home.inventory_deposit": "eposita nel baule, ",
    "home.inventory_equip": "quipaggia, ",
    "home.inventory_quit": "sci",
    "home.equip_select_item": "\nSeleziona numero oggetto da usare/equipaggiare (o 0 per annullare):",
    "home.equip_used": "Usato {0}!",
    "home.equip_equipped": "Equipaggiato {0}!",
    "home.equip_cannot": "Impossibile equipaggiare: {0}",
    "home.equip_left_finger": "  (L) Dito sinistro",
    "home.equip_right_finger": "  (R) Dito destro",
    "home.equip_cancel_option": "  (C) Annulla",
    "home.equip_main_hand_label": "  (M) Mano Principale: ",
    "home.equip_off_hand_label": "  (O) Mano Secondaria: ",
    "home.equip_cancel_label": "  (C) Annulla",
    "home.family_spouses_label": "  <3 CONIUG{0} <3",
    "home.family_married_days": " - Sposati da {0} giorn{1}",
    "home.family_children_together": "      Figli insieme: {0}",
    "home.family_polyamory": "      (Aperto alla poliamoria)",
    "home.family_lovers_label": "  AMANTI",
    "home.family_together_days": " - Insieme da {0} giorn{1}",
    "home.family_exclusive": " [Esclusivo]",
    "home.family_fwb_label": "  AMICI CON BENEFICI",
    "home.family_children_label": "  FIGLI: {0}",
    "home.family_child_age": " - {0} ann{1}, {2}",
    "home.family_child_boy": "ragazzo",
    "home.family_child_girl": "ragazza",
    "home.family_child_health": "        Salute: {0}",
    "home.family_teens_coming": "    ({0} raggiungeranno presto la maggiore età e diventeranno PNG adulti!)",
    "home.family_ex_spouses": "  EX-CONIUGI: {0}",
    "home.family_ex_marriage_info": " (sposati {0} giorni, divorziati {1} giorni fa da {2})",
    "home.family_ex_by_you": "te",
    "home.family_ex_by_them": "loro",
    "home.family_ex_children": "      ^ {0} figli insieme",
    "home.family_past_label": "  RELAZIONI PASSATE: {0}",
    "home.family_and_more": "    ... e {0} altre",
    "home.family_alone": "  Vivi solo... per ora.",
    "home.family_tip": "  Suggerimento: Incontra qualcuno di speciale alla Via Principale o Via Amore!",
    "home.partner_no_one": "Non hai un coniuge o amante con cui passare del tempo.",
    "home.partner_go_meet": "Forse dovresti uscire e conoscere qualcuno?",
    "home.partner_who": "Con chi vorresti passare del tempo?",
    "home.partner_cancel": " Annulla",
    "home.partner_not_available": "{0} non è disponibile in questo momento.",
    "home.partner_time_alone": "Decidi di passare del tempo da solo.",
    "home.discuss_sit": "Ti siedi con {0} per discutere della vostra relazione.",
    "home.discuss_duration": "  Durata del matrimonio: {0} giorni",
    "home.discuss_children": "  Figli insieme: {0}",
    "home.discuss_polyamory": "  Stato poliamoria: {0}",
    "home.discuss_polyamory_open": "Aperto",
    "home.discuss_polyamory_mono": "Monogamo",
    "home.discuss_what": "Di cosa vorresti parlare?",
    "home.discuss_talk_else": "Decidi di parlare d'altro.",
    "home.love_bond_deepens": "Il vostro legame si rafforza.",
    "home.divorce_ended": "Il tuo matrimonio è finito.",
    "home.divorce_finality": "La porta si chiude con una terribile definitività.",
    "home.fountain_hp_bonus": "+{0} PV massimi permanentemente!",
    "home.select_upgrade": "Seleziona miglioria: ",
    "home.upgrade_rest_stats": "Il riposo ora recupera {0}% PV/Mana, {1}x al giorno.",
    "home.upgrade_chest_holds": "Il baule ora contiene fino a {0} oggetti.",
    "home.upgrade_hearth_buff": "Potenziamento Riposato: +{0}% danno/difesa per {1} combattimenti dopo il riposo.",
    "home.upgrade_herbs_day": "Raccogli fino a {0} erbe al giorno.",
    "home.upgrade_new_herb": "Nuova erba sbloccata: {0} — {1}",
    "home.upgrade_servants_collect": "Raccoglieranno {0} + (tuo livello * {1}) oro al giorno.",
    "home.your_gold": "  Il tuo oro: {0}",
    "home.resurrect_select": "Inserisci il numero per resuscitare (0 per annullare): ",
    "home.resurrect_entry": "{0}. {1} (Livello {2}) - Costo: {3} oro",
    "home.select_item_cancel": "Seleziona oggetto (0 per annullare): ",
    "home.equip_failed": "Equipaggiamento fallito: {0}",
    "home.equip_no_equipment": "{0} non ha equipaggiamento da rimuovere.",
    "home.equip_header": "EQUIPAGGIAMENTO: {0}",
    "home.equip_to_header": "EQUIPAGGIA OGGETTO A {0}",
    "home.unequip_header": "RIMUOVI DA {0}",
    "home.return_label": "Torna",
    "home.partner_no_spouse": "\nNon hai un coniuge o amante con cui passare del tempo.",
    "home.partner_go_meet_msg": "Forse dovresti uscire e conoscere qualcuno?",
    "home.partner_who_spend": "Con chi vorresti passare del tempo?",
    "home.partner_cancel_label": " Annulla",
    "home.partner_not_available_msg": "{0} non è disponibile in questo momento.",
    "home.partner_time_alone_msg": "Decidi di passare del tempo da solo.",
    "home.partner_quality_time": "Passi del tempo di qualità con {0}...",
    "home.partner_dinner": " Cenare romanticamente insieme",
    "home.partner_walk": " Fare una passeggiata mano nella mano",
    "home.partner_cuddle": " Coccolarsi accanto al fuoco",
    "home.partner_conversation": " Avere una conversazione profonda",
    "home.partner_bedroom_option": " Ritirarsi in camera da letto...",
    "home.partner_discuss_option": " Discutere della nostra relazione...",
    "home.partner_dinner_prepare": "Prepari una cena deliziosa per {0}.",
    "home.partner_dinner_candlelight": "La luce delle candele tremola mentre condividete storie e risate.",
    "home.partner_dinner_gaze": "{0} ti guarda con affetto.",
    "home.partner_bond_xp": "Il vostro legame si rafforza! (+{0} XP)",
    "home.partner_walk_garden": "Tu e {0} camminate mano nella mano nel giardino.",
    "home.partner_walk_evening": "L'aria della sera è fresca e rinfrescante.",
    "home.partner_walk_head": "{0} appoggia la testa sulla tua spalla.",
    "home.partner_walk_restores": "Il momento di pace ti ristora leggermente.",
    "home.partner_cuddle_fire": "Vi accomodate insieme accanto al fuoco scoppiettante.",
    "home.partner_cuddle_nestle": "{0} si accoccola vicino a te per il calore.",
    "home.partner_cuddle_peace": "Ti senti completamente in pace in questo momento.",
    "home.partner_cuddle_renewed": "La vostra connessione spirituale si rinnova.",
    "home.discuss_sit_msg": "Ti siedi con {0} per discutere della vostra relazione.",
    "home.discuss_duration_msg": "  Durata del matrimonio: {0} giorni",
    "home.discuss_children_msg": "  Figli insieme: {0}",
    "home.discuss_polyamory_msg": "  Stato poliamoria: {0}",
    "home.discuss_polyamory_open_msg": "Aperto",
    "home.discuss_polyamory_mono_msg": "Monogamo",
    "home.discuss_what_msg": "Di cosa vorresti parlare?",
    "home.discuss_express_love": " Esprimere il tuo amore",
    "home.discuss_polyamory_option": " Discutere di poliamoria...",
    "home.discuss_close_option": " Discutere di chiudere il matrimonio...",
    "home.discuss_divorce_option": " Discutere di divorzio...",
    "home.discuss_fantasies_option": " Parlare di fantasie...",
    "home.discuss_talk_else_msg": "Decidi di parlare d'altro.",
    "home.love_take_hands": "Prendi le mani di {0} nelle tue e li guardi negli occhi.",
    "home.love_words_devotion": "Pronunci parole di devozione e impegno.",
    "home.love_tear": "Una lacrima brilla nei loro occhi.",
    "home.love_bond_deepens_msg": "Il vostro legame si rafforza.",
    "home.poly_broach": "Affronti un argomento difficile con {0}...",
    "home.poly_been_thinking": "Spieghi che hai riflettuto su un accordo aperto.",
    "home.poly_request_open": " Chiedere di aprire il matrimonio",
    "home.poly_close": " Chiedere di chiudere il matrimonio",
    "home.poly_nevermind": " Non importa",
    "home.poly_open_success": "Il vostro matrimonio è ora aperto alla poliamoria!",
    "home.poly_high_rel": "Dopo lunga discussione, acconsentono. Il vostro legame è abbastanza forte per provare.",
    "home.poly_tense": "La conversazione diventa tesa...",
    "home.poly_reluctant": "Acconsentono con riluttanza, ma percepisci disagio.",
    "home.poly_warning": "Attenzione: Questo potrebbe influire sulla vostra relazione nel tempo.",
    "home.poly_not_ready": "Non sono pronti per quella conversazione.",
    "home.poly_need_stronger": "Forse quando il vostro legame sarà più forte...",
    "home.poly_close_approach": "Affronti con {0} il tema del vostro matrimonio aperto...",
    "home.poly_want_exclusive": "Esprimi il desiderio di tornare all'esclusività.",
    "home.poly_now_mono": "Il vostro matrimonio è ora monogamo.",
    "home.poly_relieved": "Sembrano sollevati. Il vostro legame si rafforza.",
    "home.divorce_breath": "Fai un respiro profondo prima di parlare a {0}...",
    "home.divorce_ask": " Chiedere il divorzio",
    "home.divorce_nevermind": " Non importa, ti amo",
    "home.divorce_warning_children": "Attenzione: Avete {0} figli insieme.",
    "home.divorce_lose_custody": "Perderai la custodia dei tuoi figli!",
    "home.divorce_reconsider": "Sei sicuro? Non potrai tornare indietro.",
    "home.divorce_confirm": " Sì, voglio il divorzio",
    "home.divorce_stay": " No, proviamo a risolvere le cose",
    "home.divorce_reach_hand": "Allunghi la mano e prendi quella di {0}.",
    "home.divorce_work_it_out": "\"Superiamo questo insieme.\"",
    "home.divorce_relief": "Il sollievo si dipinge sul loro volto.",
    "home.divorce_bond_repair": "Il vostro legame inizia a ripararsi.",
    "home.divorce_ended_msg": "Il tuo matrimonio è finito.",
    "home.divorce_finality_msg": "La porta si chiude con una terribile definitività.",
    "home.fantasies_curl": "Ti rannicchi accanto a {0} e sussurri...",
    "home.fantasies_share": "\"Voglio condividere qualcosa con te... una fantasia.\"",
    "home.fantasies_what_discuss": "Di cosa vuoi parlare?",
    "home.fantasies_group": " Incontri di gruppo...",
    "home.fantasies_voyeurism": " Voyeurismo...",
    "home.fantasies_exhibitionism": " Esibizionismo...",
    "home.fantasies_alternative": " Accordi alternativi...",
    "home.fantasies_nevermind": " Non importa",
    "home.fantasies_not_pursue": "Decidi di non proseguire questa conversazione per ora.",
    "home.group_explain": "Spieghi con cautela il tuo interesse a condividere esperienze intime con un'altra persona.",
    "home.group_agree_conditions": "Ci riflettono attentamente...",
    "home.group_open_idea": "Sono aperti all'idea a certe condizioni.",
    "home.group_boundaries": "Discutete insieme di limiti e regole.",
    "home.group_upset": "La conversazione li ha profondamente turbati...",
    "home.group_not_interested": "Non sono interessati a incontri di gruppo.",
    "home.group_damage_rel": "Questo ha danneggiato la vostra relazione.",
    "home.voyeur_open": "Sono aperti a esplorare fantasie voyeuristiche!",
    "home.voyeur_curious": "Sono curiosi ma cauti.",
    "home.voyeur_prefer_trad": "Preferiscono l'intimità tradizionale.",
    "home.exhibit_share": "Condividono i tuoi interessi esibizionisti!",
    "home.exhibit_understanding": "Sono comprensivi ma non personalmente interessati.",
    "home.exhibit_prefer_privacy": "Preferiscono fortemente la privacy.",
    "home.alt_broach": "Affronti un argomento delicato con {0}...",
    "home.alt_deep_trust": "\"Questo richiede una profonda fiducia tra noi...\"",
    "home.alt_what_arrangement": "Che tipo di accordo vuoi discutere?",
    "home.alt_hotwife": " Hotwifing / Cuckolding (loro vanno, tu guardi)",
    "home.alt_stag": " Stag & Vixen (loro vanno, tu godi del potere)",
    "home.alt_cuckold": " Cuckolding (loro vanno, tu ti sottometti)",
    "home.alt_nevermind": " Non importa",
    "home.alt_not_pursue": "Decidi di non proseguire questa conversazione.",
    "home.alt_slow_smile": "Un lento sorriso attraversa il loro volto.",
    "home.alt_hw_interested": "\"Ci ho pensato anch'io...\"",
    "home.alt_hw_tonight": "Vuoi che provino stasera?",
    "home.alt_hw_yes": " Sì",
    "home.alt_hw_not_yet": " Non ancora",
    "home.alt_hw_need_time": "Hanno bisogno di tempo per rifletterci.",
    "home.alt_hw_upset": "Il suggerimento li ha turbati.",
    "home.alt_no_one_tonight": "Purtroppo, non c'è nessuno di adatto disponibile stasera.",
    "home.alt_hw_find_later": "Forse riprova più tardi quando ci saranno più PNG in città.",
    "home.hw_prepares": "Guardi con un misto di eccitazione e nervosismo mentre {0} si prepara.",
    "home.hw_leaves": "{0} esce per la serata...",
    "home.hw_hours_pass": "Le ore passano lentamente. Immagini cosa potrebbe succedere...",
    "home.hw_anticipation": "L'anticipazione è quasi insopportabile.",
    "home.hw_returns": "La porta si apre. {0} ritorna, accaldato e senza fiato.",
    "home.hw_tells_everything": "{0} ti racconta tutto.",
    "home.hw_details": "Come si sentivano le mani di {0}. Il primo bacio. La passione.",
    "home.hw_whispered": "Ogni dettaglio, sussurrato nel tuo orecchio mentre {0} ti stringe.",
    "home.hw_reclaim": "E poi fate l'amore. Appassionato, possessivo, riconquistante.",
    "home.hw_the_fire": "Il fuoco tra voi si accende come mai prima.",
    "home.hw_electric": "Ogni tocco è elettrico, possessivo, appassionato.",
    "home.hw_claim_yours": "Rivendichi ciò che è tuo, e {0} si arrende completamente.",
    "home.hw_night_unlike": "La notte che segue è diversa da ogni altra.",
    "home.hw_stories_fuel": "Le storie che {0} racconta alimentano solo la passione.",
    "home.hw_morning_exhausted": "Al mattino, siete entrambi esausti... e più vicini che mai.",
    "home.hw_bond_deepened": "Il vostro legame si è approfondito attraverso questa esperienza condivisa.",
    "home.cuck_shift": "Qualcosa cambia nel loro atteggiamento.",
    "home.cuck_interested": "\"Sono incuriosita dalla dinamica di potere...\"",
    "home.cuck_tonight": "Vuoi provare stasera?",
    "home.cuck_yes": " Sì",
    "home.cuck_not_yet": " Non ancora",
    "home.cuck_not_understand": "Non capiscono o non si collegano a questa dinamica.",
    "home.cuck_upset": "Questo li ha profondamente turbati.",
    "home.cuck_no_one": "Purtroppo, non c'è nessuno di adatto disponibile stasera.",
    "home.cuck_first_kiss": "Il primo bacio è esitante, poi diventa più appassionato.",
    "home.cuck_watch_chair": "Guardi dalla tua sedia, col cuore in gola.",
    "home.cuck_power_gaze": "C'è potere nello sguardo di {0}. Controllo. Dominio.",
    "home.cuck_owns_it": "Questo è ciò che hai chiesto, e {0} se ne impossessa completamente.",
    "home.cuck_clothing_falls": "I vestiti cadono. I corpi si intrecciano.",
    "home.cuck_looks_at_you": "A volte {0} ti guarda. A volte {1} ti ignora del tutto.",
    "home.cuck_both_intense": "Entrambe le cose sono ugualmente intense.",
    "home.cuck_sounds": "I suoni. I movimenti. Il modo in cui si muovono insieme.",
    "home.cuck_told_you": "Siedi lì, esattamente dove {0} ti ha detto di stare.",
    "home.cuck_watching": "Guardando tutto svolgersi nella tua stessa camera da letto.",
    "home.cuck_nod_out": "Un cenno complice verso di te mentre esce.",
    "home.cuck_dynamic_shifted": "La dinamica tra voi è cambiata per sempre.",
    "home.cuck_gave_power": "E hai dato loro quel potere volontariamente.",
    "home.cuck_new_chapter": "Un nuovo capitolo nella vostra relazione è iniziato.",
    "home.stag_mischievous": "Un sorriso malizioso si forma sulle loro labbra.",
    "home.stag_thrill": "\"Il brivido di guardare... capisco il fascino.\"",
    "home.stag_not_ready": "Sono lusingati ma non pronti.",
    "home.stag_prefer_mono": "Preferiscono la monogamia.",
    "home.reject_cold_voice": "Quando {0} finalmente parla, la voce di {1} è fredda.",
    "home.reject_crossed_line": "\"{0}... hai oltrepassato il limite.\"",
    "home.reject_divorce_ask": "Il tuo coniuge ha chiesto il divorzio.",
    "home.reject_fight_or_accept": "Lotti per il tuo matrimonio o accetti?",
    "home.reject_fight": " Supplica di riconsiderare",
    "home.reject_accept": " Accetta il divorzio",
    "home.reject_saved": "Il tuo matrimonio è stato salvato... a malapena.",
    "home.reject_damage_heal": "Ma il danno richiederà tempo per guarire.",
    "home.reject_accept_silence": "Accetti la loro decisione in silenzio.",
    "home.reject_strained": "Senti che la vostra relazione si sta logorando.",
    "home.reject_careful": "Forse è meglio essere più cauti con argomenti delicati.",
    "home.equip_npc_level": "Lv {0} {1}",
    "home.divorce_custody": "{0} ha ottenuto la custodia dei figli.",
    "home.divorce_packs": "{0} prepara le valigie e se ne va.",
    "home.bedroom_here_inviting": "{0} è qui, con uno sguardo invitante...",
    "home.equip_stats_level": "  Livello: {0}  Classe: {1}  Razza: {2}",
    "home.equip_stats_hp": "  PV: {0}/{1}  Mana: {2}/{3}",
    "home.equip_stats_str": "  FOR: {0}  DES: {1}  AGI: {2}  COS: {3}",
    "home.equip_stats_int": "  INT: {0}  SAG: {1}  CAR: {2}  DIF: {3}",
    "main_street.align_good": "Cuore Buono",
    "main_street.align_neutral": "Neutrale",
    "main_street.align_noble": "Nobile Eroe",
    "main_street.align_paragon": "Paladino della Virtù",
    "main_street.align_questionable": "Discutibile",
    "main_street.align_usurper": "Usurper - Incarnazione delle Tenebre",
    "main_street.align_villain": "Malvagio",
    "main_street.awakening_0": "Non Risvegliato - Vedi solo la superficie delle cose",
    "main_street.awakening_1": "Fremito - Qualcosa nel profondo inizia a muoversi",
    "main_street.awakening_2": "Increspature - Percepisci connessioni tra tutte le cose",
    "main_street.awakening_3": "Correnti - Le profondità ti chiamano con sussurri antichi",
    "main_street.awakening_4": "Abissi - Comprendi il dolore dell'oceano",
    "main_street.awakening_5": "Illuminato - Sei uno con la marea eterna",
    "main_street.awakening_level": "Livello di Risveglio: {0}/5",
    "main_street.awakening_unknown": "Sconosciuto",
    "main_street.chivalry_label": "Cavalleria:",
    "main_street.dark_clean": "Fedina pulita",
    "main_street.dark_rumored": "Misfatti presunti",
    "main_street.dark_suspicious": "Reputazione sospetta",
    "main_street.dark_wanted": "RICERCATO dalla Guardia Reale!",
    "main_street.darkness_label": "Oscurità:",
    "main_street.god_conquered": "Conquistato",
    "main_street.god_defeated": "SCONFITTO",
    "main_street.god_encountered": "Incontrato",
    "main_street.god_known": "Conosciuto",
    "main_street.god_somewhere": "Da qualche parte nelle profondità...",
    "main_street.god_unknown": "Sconosciuto",
    "main_street.gods_desc": "Esseri antichi che puoi sfidare per potere o saggezza",
    "main_street.grief_acceptance": "Accettazione - Trovare la pace",
    "main_street.grief_anger": "Irato - Perché è successo?",
    "main_street.grief_bargaining": "Contrattazione - Se solo...",
    "main_street.grief_denial": "In Negazione - La perdita sembra irreale",
    "main_street.grief_depression": "Depresso - Il peso della perdita",
    "main_street.grief_label": "Lutto:",
    "main_street.grief_none": "In Pace",
    "main_street.hint_creator": "Tutti i sigilli raccolti. Il Creatore attende nelle profondità più remote...",
    "main_street.hint_ending": "Hai completato il tuo viaggio. Cerca il tuo destino.",
    "main_street.hint_seals": "Gli antichi sigilli attendono di essere scoperti nelle profondità del sotterraneo...",
    "main_street.ocean_desc": "Il tuo risveglio spirituale attraverso dolore, sacrificio e comprensione",
    "main_street.press_return": "Premi Invio per tornare alla Via Principale...",
    "main_street.seals_collected": "Sigilli Raccolti: {0}/7",
    "main_street.seals_desc": "Antichi manufatti che rivelano la verità della creazione",
}
