translations = {
    "_comment": "Italiano — Tutte le chiavi devono esistere qui. Le lingue mancanti usano l'inglese come fallback.",
    "lang.name": "Italiano",
    "ui.press_any_key": "Premi un tasto per continuare...",
    "ui.press_enter": "Premi Invio per continuare...",
    "ui.choice": "Scelta: ",
    "ui.your_choice": "La tua scelta: ",
    "ui.enter_to_cancel": "o premi Invio per annullare",
    "ui.yes": "Sì",
    "ui.no": "No",
    "ui.confirm": "Sei sicuro? (S/N): ",
    "ui.confirm_yes_no": "Sei sicuro? (sì/no): ",
    "ui.confirm_fight": "Sei sicuro di voler combattere? (s/N): ",
    "ui.confirm_cannot_undo": "Sei sicuro? Non si può annullare!",
    "ui.confirm_divorce": "Sei sicuro di voler divorziare? (S/N): ",
    "ui.confirm_divorce_ask": "Sei sicuro di voler chiedere il divorzio?",
    "ui.confirm_abdicate": "Sei sicuro di voler abdicare al trono?",
    "ui.confirm_abandon_control": "Sei sicuro di voler abbandonare il controllo della città?",
    "ui.confirm_choose": "Sei sicuro di voler scegliere {0}? (S/N) ",
    "ui.confirm_delete": "Sei sicuro di voler eliminare '{0}'? Scrivi 'ELIMINA' per confermare: ",
    "ui.confirm_proceed": "Sei sicuro di voler procedere? (S/N): ",
    "ui.not_enough_gold": "Non hai abbastanza oro!",
    "ui.not_enough_gold_friend": "\"Non hai abbastanza oro, amico.\"",
    "ui.not_enough_gold_amount": "Non hai abbastanza oro. ({0}/{1})",
    "ui.not_enough_gold_repay": "Non hai abbastanza oro per ripagare l'intero importo.",
    "ui.not_enough_gold_identify": "Non hai abbastanza oro per l'identificazione!",
    "ui.not_enough_gold_drink": "Non hai abbastanza oro per un drink!",
    "ui.not_enough_gold_gift": "Non hai abbastanza oro per un regalo (servono 50 monete d'oro).",
    "ui.not_enough_gold_gift_need": "Non hai abbastanza oro per un regalo degno. (Servono 50mo)",
    "ui.not_enough_gold_meal": "Non hai abbastanza oro per un pasto!",
    "ui.not_enough_gold_performance": "Non hai abbastanza oro per questa esibizione.",
    "ui.not_enough_gold_spare": "Non hai abbastanza oro da spendere.",
    "ui.not_enough_gold_recruit": "Non hai abbastanza oro per reclutare {0}!",
    "ui.not_enough_gold_plain": "Non hai abbastanza oro.",
    "ui.not_enough_gold_courtesan": "\"Non hai abbastanza oro!\" {0} ride crudelmente.",
    "ui.settlement_buff_active": "Hai già un potenziamento dell'insediamento attivo!",
    "ui.no_equipment_to_give": "Non hai equipaggiamento da cedere.",
    "ui.no_healing_potions": "Non hai pozioni curative!",
    "ui.no_usable_potions": "Non hai pozioni utilizzabili!",
    "ui.no_poison_vials": "Non hai fiale di veleno!",
    "ui.no_mana_potions": "Non hai pozioni di mana!",
    "ui.no_mana_for_spells": "Non hai mana per lanciare incantesimi!",
    "ui.no_trained_skills": "Non hai abilità addestrate da resettare!",
    "ui.no_active_quests": "Non hai missioni attive.",
    "ui.no_active_quests_turn_in": "Non hai missioni attive da consegnare.",
    "ui.no_active_quests_abandon": "Non hai missioni attive da abbandonare.",
    "ui.no_intimacy_acts": "Non hai più atti d'intimità disponibili oggi!",
    "ui.no_mail": "Non hai posta.",
    "ui.no_healing_potions_spare": "Non hai pozioni curative da condividere!",
    "ui.no_weapons_to_sell": "Non hai armi o scudi da vendere.",
    "ui.no_armor_to_sell": "Non hai armature da vendere.",
    "ui.no_items_to_store": "Non hai oggetti da riporre.",
    "ui.no_gold_to_contribute": "Non hai oro da contribuire.",
    "ui.no_unidentified_items": "Non hai oggetti non identificati.",
    "ui.no_escape_attempts": "Non hai più tentativi di fuga!",
    "ui.game_saved": "Partita salvata.",
    "ui.gold": "Oro",
    "ui.level": "Livello",
    "ui.experience": "Esperienza",
    "ui.stat_str": "For",
    "ui.stat_dex": "Des",
    "ui.stat_con": "Cos",
    "ui.stat_int": "Int",
    "ui.stat_wis": "Sag",
    "ui.stat_cha": "Car",
    "ui.stat_agi": "Agi",
    "ui.stat_sta": "Res",
    "ui.stat_strength": "Forza",
    "ui.stat_dexterity": "Destrezza",
    "ui.stat_constitution": "Costituzione",
    "ui.stat_intelligence": "Intelligenza",
    "ui.stat_wisdom": "Saggezza",
    "ui.stat_charisma": "Carisma",
    "ui.stat_agility": "Agilità",
    "ui.stat_stamina": "Resistenza",
    "ui.stat_hp": "PV",
    "ui.stat_mana": "Mana",
    "ui.stat_defense": "Difesa",
    "ui.stat_attack": "Attacco",
    "ui.stat_damage": "Danno",
    "ui.stat_pow": "Pot",
    "ui.stat_wp": "PA",
    "ui.stat_ac": "CA",
    "ui.stat_def": "Dif",
    "ui.stat_block": "Blocco",
    "ui.stat_mp": "PM",
    "ui.stat_mr": "RM",
    "ui.stat_crit": "Crit",
    "ui.stat_ls": "RV",
    "ui.no_bonuses": "Nessun bonus",
    "ui.requires_level": "Richiede livello {0}",
    "ui.requires_strength": "Richiede {0} Forza",
    "ui.requires_good": "Richiede allineamento buono",
    "ui.requires_evil": "Richiede allineamento malvagio",
    "ui.requires_str_heavy": "Richiede {0} Forza per armatura pesante",
    "ui.cannot_use_class": "Non può essere usato da {0}",
    "ui.cannot_wear_weight": "La tua classe non può indossare armatura {0}",
    "ui.race_too_small_heavy": "La tua razza è troppo piccola per l'armatura pesante",
    "ui.requires_label": "Requisiti:",
    "ui.page": "Pagina {0} di {1}",
    "ui.next_page": "[N]ext",
    "ui.prev_page": "[P]rec",
    "ui.back": "[B]ack",
    "ui.quit": "[Q]uit",
    "ui.cancelled": "Annullato.",
    "ui.invalid_selection": "Selezione non valida.",
    "ui.quick_commands": "Comandi Rapidi",
    "ui.return": "Ritorna",
    "ui.talk": "Parla",
    "ui.commands": "Comandi",
    "ui.empty": "Vuoto",
    "ui.none": "Nessuno",
    "ui.team": "Squadra",
    "ui.location": "Luogo",
    "ui.alignment": "Allineamento",
    "ui.good": "Buono",
    "ui.evil": "Malvagio",
    "ui.neutral": "Neutrale",
    "ui.bail": "Cauzione",
    "ui.wealth_status": "Ricchezza e Stato:",
    "ui.main_hand": "Mano Principale",
    "ui.off_hand": "Mano Secondaria",
    "ui.head": "Testa",
    "ui.body": "Corpo",
    "ui.arms": "Braccia",
    "ui.hands": "Mani",
    "ui.legs": "Gambe",
    "ui.feet": "Piedi",
    "ui.waist": "Vita",
    "ui.cloak": "Mantello",
    "ui.neck": "Collo",
    "ui.neck_2": "Collo 2",
    "ui.face": "Volto",
    "ui.left_ring": "Anello Sinistro",
    "ui.right_ring": "Anello Destro",
    "menu.main.single_player": "Giocatore Singolo",
    "menu.main.online_play": "Gioco Online",
    "menu.main.help": "Aiuto",
    "menu.main.quit": "Esci",
    "menu.main.terminal_font": "Font del Terminale",
    "menu.main.screen_reader": "Modalità Screen Reader",
    "menu.main.compact_mode": "Modalità Compatta",
    "location.main_street": "Via Principale",
    "location.dungeon": "Il Dungeon",
    "location.weapon_shop": "Armeria",
    "location.armor_shop": "Bottega delle Armature",
    "location.magic_shop": "Bottega Magica",
    "location.music_shop": "Bottega della Musica",
    "location.inn": "La Locanda",
    "location.healer": "Il Guaritore",
    "location.quest_hall": "Sala delle Missioni",
    "location.temple": "Il Tempio",
    "location.church": "La Chiesa",
    "location.bank": "La Banca",
    "location.castle": "Il Castello",
    "location.home": "Casa",
    "location.dark_alley": "Vicolo Oscuro",
    "location.arena": "L'Arena",
    "location.marketplace": "Mercato",
    "location.prison": "Prigione",
    "location.level_master": "Maestro dei Livelli",
    "location.wilderness": "Le Terre Selvagge",
    "location.settlement": "I Sobborghi",
    "location.love_corner": "Angolo dell'Amore",
    "location.love_street": "Via dell'Amore",
    "location.dormitory": "Dormitorio",
    "location.anchor_road": "Via dell'Ancora",
    "menu.action.dungeon": "Dungeon",
    "menu.action.weapon_shop": "Armeria",
    "menu.action.armor_shop": "Bottega Armature",
    "menu.action.magic_shop": "Bottega Magica",
    "menu.action.music_shop": "Bottega Musica",
    "menu.action.inn": "Locanda",
    "menu.action.healer": "Guaritore",
    "menu.action.quest_hall": "Sala Missioni",
    "menu.action.temple": "Tempio",
    "menu.action.church": "Chiesa",
    "menu.action.bank": "Banca",
    "menu.action.castle": "Castello",
    "menu.action.home": "Casa",
    "menu.action.dark_alley": "Vicolo Oscuro",
    "menu.action.arena": "Arena",
    "menu.action.marketplace": "Mercato",
    "menu.action.level_master": "Maestro dei Livelli",
    "menu.action.wilderness": "Le Terre Selvagge",
    "menu.action.settlement": "I Sobborghi",
    "menu.action.preferences": "Preferenze",
    "menu.action.status": "Stato",
    "menu.action.inventory": "Inventario",
    "menu.action.help": "Aiuto",
    "menu.action.quit": "Esci",
    "menu.action.news": "Notizie",
    "menu.action.lodging": "Alloggio (Dormitorio)",
    "menu.action.auction_house": "Casa d'Aste",
    "menu.action.challenges": "Sfide",
    "menu.action.team_corner": "Angolo della Squadra",
    "menu.action.fame": "Fama",
    "menu.action.stats_record": "Registro Statistiche",
    "menu.action.progress": "Progresso",
    "menu.action.love_street": "Via dell'Amore",
    "menu.action.report_bug": "Segnala un Bug",
    "death.you_died": "SEI MORTO",
    "death.nightmare_mode": "M O D A L I T À   I N C U B O",
    "death.permadeath": "M O R T E   P E R M A N E N T E",
    "death.no_resurrection": "Non c'è resurrezione. Non c'è pietà.",
    "death.journey_ends": "Il tuo viaggio finisce qui, per sempre.",
    "death.save_erased": "Il tuo salvataggio è stato cancellato dall'esistenza.",
    "death.veil_header": "IL VELO TRA I MONDI",
    "death.veil_intro": "Ti trovi sulla soglia tra la vita e la morte.",
    "death.choose_path": "Scegli il tuo cammino:",
    "death.divine_intervention": "Intervento Divino",
    "death.divine_desc": "Invoca gli dèi per la resurrezione ({0} rimanenti)",
    "death.temple_resurrection": "Resurrezione al Tempio",
    "death.temple_desc": "Paga il tempio {0} monete d'oro per la resurrezione (ritorna al Tempio)",
    "death.deal_with_death": "Patto con la Morte",
    "death.deal_desc": "Negozia con il mietitore (costa Oscurità, perdita permanente di statistiche)",
    "death.accept_fate": "Accetta il Tuo Destino",
    "death.accept_desc": "ATTENZIONE: Perdi 10-20% PE, 50-75% oro, e possibilmente un oggetto",
    "death.your_choice": "La tua scelta:",
    "death.resurrected": "Ansimi mentre la vita rifluisce nel tuo corpo!",
    "death.resurrected_hp": "Sei stato resuscitato con {0} PV!",
    "death.awaken_temple": "Ti risvegli al tempio...",
    "status.hp": "PV",
    "status.mp": "PM",
    "status.sta": "Resistenza",
    "status.str": "Forza",
    "status.dex": "Destrezza",
    "status.con": "Costituzione",
    "status.int": "Intelligenza",
    "status.wis": "Saggezza",
    "status.cha": "Carisma",
    "status.agi": "Agilità",
    "status.def": "Difesa",
    "status.class": "Classe",
    "status.race": "Razza",
    "status.alignment": "Allineamento",
    "status.gold_label": "Oro",
    "status.potions": "Pozioni",
    "status.fatigue": "Fatica",
    "status.rested": "Riposato",
    "status.tired": "Stanco",
    "status.exhausted": "Esausto",
    "status.mana": "Mana",
    "status.stamina": "Resistenza",
    "status.xp_to_next": "PE: {0}% al prossimo livello",
    "class.warrior": "Guerriero",
    "class.paladin": "Paladino",
    "class.ranger": "Ranger",
    "class.assassin": "Assassino",
    "class.bard": "Bardo",
    "class.jester": "Giullare",
    "class.alchemist": "Alchimista",
    "class.magician": "Mago",
    "class.cleric": "Chierico",
    "class.sage": "Saggio",
    "class.barbarian": "Barbaro",
    "class.tidesworn": "Tidesworn",
    "class.wavecaller": "Wavecaller",
    "class.cyclebreaker": "Cyclebreaker",
    "class.abysswarden": "Abysswarden",
    "class.voidreaver": "Voidreaver",
    "race.human": "Umano",
    "race.hobbit": "Hobbit",
    "race.elf": "Elfo",
    "race.half_elf": "Mezzelfo",
    "race.dwarf": "Nano",
    "race.troll": "Troll",
    "race.orc": "Orco",
    "race.gnome": "Gnomo",
    "race.gnoll": "Gnoll",
    "race.mutant": "Mutante",
    "shop.buy": "Compra",
    "shop.sell": "Vendi",
    "shop.sell_all": "Vendi Tutto",
    "shop.browse": "Sfoglia",
    "shop.cant_afford": "Non puoi permettertelo!",
    "shop.purchased": "Hai acquistato {0} per {1} monete d'oro!",
    "shop.sold": "Hai venduto {0} per {1} monete d'oro!",
    "shop.class_restricted": "Restrizione di classe: {0}",
    "shop.too_low_level": "Richiede livello {0}",
    "shop.identify": "Identifica Oggetto",
    "shop.return": "Torna in strada",
    "shop.gold_crowns": "monete d'oro",
    "shop.you_have": "Hai {0} monete d'oro.",
    "shop.auto_buy": "Acquisto automatico della migliore arma accessibile",
    "shop.current_weapons": "Armi Attuali:",
    "shop.main_hand": "Mano Principale:",
    "shop.off_hand": "Mano Secondaria:",
    "shop.empty": "Vuoto",
    "shop.using_2h": "(arma a due mani equipaggiata)",
    "shop.select_category": "Seleziona una categoria:",
    "shop.categories": "Categorie:",
    "weapon_shop.header": "ARMERIA",
    "weapon_shop.one_handed": "Armi a Una Mano (per doppia impugnatura o spada+scudo)",
    "weapon_shop.two_handed": "Armi a Due Mani (danno elevato, entrambe le mani occupate)",
    "weapon_shop.bows": "Archi (a distanza, due mani)",
    "weapon_shop.shields": "Scudi (difesa mano secondaria)",
    "weapon_shop.sell": "Vendi armi/scudi",
    "armor_shop.header": "BOTTEGA DELLE ARMATURE",
    "armor_shop.sell": "Vendi armature",
    "armor_shop.auto_buy": "Acquisto Automatico Migliore Armatura",
    "armor_shop.armor_slots": "Slot Armatura:",
    "armor_shop.current_armor": "Armatura Attuale:",
    "armor_shop.total_ac": "Classe Armatura Totale: {0}",
    "armor_shop.ambient_chainmail": "Una cotta di maglia tintinna dolcemente su un espositore vicino.",
    "armor_shop.ambient_leather": "L'odore di cuoio trattato riempie l'aria.",
    "armor_shop.ambient_polish": "Un vasetto di lucido per armature brilla sul bancone.",
    "armor_shop.ambient_hammer": "Un martello batte ritmicamente un'incudine nel retrobottega.",
    "armor_shop.ambient_stand": "Un'armatura a piastre scintillante è esposta su un manichino.",
    "armor_shop.kicked_out_1": "Il bottegaio blocca l'entrata!",
    "armor_shop.kicked_out_2": "\"Non sei il benvenuto qui dopo quel numero!\"",
    "armor_shop.kicked_out_3": "\"Torna quando avrai imparato le buone maniere!\"",
    "armor_shop.kicked_out_return": "Dovrai tornare un altro giorno.",
    "armor_shop.run_by": "Gestita da {0} l'elfo.",
    "armor_shop.shopkeeper_greeting": "{0} alza lo sguardo dalla corazza che sta lucidando.",
    "armor_shop.you_have": "Hai ",
    "armor_shop.gold_crowns": " monete d'oro.",
    "armor_shop.gold_suffix": " mo.",
    "armor_shop.align_discount": "Sconto per allineamento {0}: {1}% di sconto!",
    "armor_shop.align_markup": "Sovrapprezzo per allineamento {0}: {1}% in più!",
    "armor_shop.world_discount": "Surplus di mercato: {0}% di sconto su tutti i prezzi!",
    "armor_shop.world_markup": "Carenza di scorte: {0}% di sovrapprezzo su tutti i prezzi!",
    "armor_shop.total_ac_label": "CA Totale:",
    "armor_shop.bbs_sell": "Vendi",
    "armor_shop.bbs_auto_buy": "Acquisto Auto",
    "armor_shop.bbs_return": "Ritorna",
    "armor_shop.slot_armor": "Armatura {0}",
    "armor_shop.currently_equipped": "Attualmente Equipaggiato: ",
    "armor_shop.value_label": "Valore",
    "armor_shop.page_info": "Pagina {0} di {1} ({2} oggetti totali)",
    "armor_shop.item_header": "  #  Nome                       Liv    CA       Oro    Bonus",
    "armor_shop.buy_item": "Compra oggetto   ",
    "armor_shop.previous": "Precedente   ",
    "armor_shop.next": "Successivo   ",
    "armor_shop.back": "Indietro",
    "armor_shop.class_restriction": "Restrizione di classe: {0}",
    "armor_shop.requires_level": "Richiede livello {0} (sei livello {1})",
    "armor_shop.warning_cant_equip": "⚠ Non puoi equipaggiare questo: {0}",
    "armor_shop.buy_prompt_name": "Compra {0} per ",
    "armor_shop.incl_tax": " (tasse incluse)",
    "armor_shop.was_price": " (era {0})",
    "armor_shop.gold_yn": " monete d'oro? (S/N): ",
    "armor_shop.equip_or_inventory": "[E]quipaggia o [I]nventario? ",
    "armor_shop.couldnt_equip": "Impossibile equipaggiare {0} - aggiunto all'inventario.",
    "armor_shop.shadows_bonus": "★ Bonus ricettatore delle Ombre: +20% prezzi di vendita!",
    "armor_shop.equipped_header": "[ EQUIPAGGIATO ]",
    "magic_shop.header": "BOTTEGA MAGICA",
    "magic_shop.run_by": "Gestita da {0} lo gnomo.",
    "magic_shop.shopping": "Acquisti:",
    "magic_shop.rings": "Anelli",
    "magic_shop.necklaces": "Collane",
    "magic_shop.sell": "Vendi Accessori",
    "magic_shop.identify": "Identifica Oggetto",
    "magic_shop.enchanting": "Incantamenti:",
    "magic_shop.enchant": "Incanta Equipaggiamento",
    "magic_shop.remove_enchant": "Rimuovi Incantamento",
    "magic_shop.curse_removal": "Servizio di Rimozione Maledizioni",
    "magic_shop.forge": "Fucina degli Incantamenti",
    "magic_shop.potions": "Pozioni e Pergamene:",
    "magic_shop.healing_potions": "Pozioni Curative",
    "magic_shop.mana_potions": "Pozioni di Mana",
    "magic_shop.reset_scroll": "Pergamena di Reset Dungeon",
    "magic_shop.arcane": "Arti Arcane:",
    "magic_shop.love_spells": "Incantesimi d'Amore",
    "magic_shop.dark_arts": "Arti Oscure",
    "magic_shop.study_spells": "Studia Incantesimi",
    "magic_shop.scrying": "Servizio di Divinazione",
    "magic_shop.talk_to": "Parla con {0}",
    "magic_shop.no_unidentified": "Non hai oggetti non identificati.",
    "magic_shop.unidentified_items": "Oggetti Non Identificati ({0})",
    "magic_shop.identify_cost": "L'identificazione costa {0} monete d'oro per oggetto. Hai {1} monete d'oro.",
    "level_master.header": "SANCTA SANCTORUM DEL MAESTRO",
    "level_master.services": "Servizi:",
    "level_master.level_raise": "Aumento di Livello",
    "level_master.abilities": "Abilità",
    "level_master.abilities_desc": "visualizza e impara abilità di combattimento o incantesimi",
    "level_master.training": "Addestramento",
    "level_master.training_desc": "migliora le abilità ({0} punti)",
    "level_master.crystal_ball": "LA SFERA DI CRISTALLO",
    "level_master.crystal_desc": "scruta informazioni su altri personaggi",
    "level_master.help_team": "Aiuta Compagno di Squadra",
    "level_master.help_desc": "assisti un compagno nel salire di livello",
    "level_master.your_xp": "La Tua Esperienza: {0}",
    "level_master.max_level": "Hai raggiunto l'apice del potere mortale!",
    "level_master.ready_advance": "Sei pronto ad avanzare al livello {0}!",
    "level_master.xp_needed": "Esperienza necessaria per il livello {0}: {1}",
    "level_master.need_xp": "Servono {0} PE per il livello {1}",
    "level_master.training_points": "Punti Addestramento: {0}",
    "level_master.combat_abilities": "Abilità di Combattimento",
    "level_master.spell_library": "Biblioteca degli Incantesimi",
    "level_master.master_label": "Maestro: {0}",
    "level_master.menu_level_raise": "umento di Livello – avanza se hai accumulato abbastanza esperienza",
    "level_master.menu_abilities": "bilità – {0}",
    "level_master.menu_training": "ddestramento – {0}",
    "level_master.menu_crystal": "fera di Cristallo – {0}",
    "level_master.menu_help_team": "iuta Compagno – {0}",
    "level_master.menu_status": "tato – visualizza le tue statistiche",
    "level_master.menu_return": "itorna alla Via Principale",
    "level_master.sr_status_desc": "Stato - visualizza le tue statistiche",
    "level_master.bbs_max_level": " LIVELLO MASSIMO!",
    "level_master.bbs_ready": " *PRONTO AD AVANZARE!*",
    "level_master.bbs_need": "  Serve:",
    "level_master.bbs_train": "  Addestr:",
    "level_master.bbs_pts": "{0}pti",
    "level_master.bbs_level_raise": "Aumento Livello",
    "level_master.bbs_abilities": "Abilità",
    "level_master.bbs_training": "Addestramento",
    "level_master.bbs_crystal_ball": "Sfera di Cristallo",
    "level_master.bbs_help_team": "Aiuta Squadra",
    "level_master.bbs_return": "Ritorna",
    "level_master.visual_combat_abilities": "  [A] Abilità di Combattimento",
    "level_master.visual_spell_library": "  [S] Biblioteca Incantesimi",
    "level_master.greet_good": "\"Benvenuto, nobile {0}. La tua luce risplende intensamente.\"",
    "level_master.greet_evil": "\"Ah, {0}... L'oscurità dentro di te cresce sempre più forte.\"",
    "level_master.greet_neutral": "\"Saluti, cercatore di equilibrio. Cosa ti porta qui, {0}?\"",
    "level_master.hybrid_intro": "\"{0}, il tuo potere abbraccia sia le arti marziali che quelle arcane...\"",
    "level_master.ability_intro": "\"Vieni, {0}. Lascia che ti mostri la via del {1}...\"",
    "level_master.training_intro": "\"La pratica rende perfetti, {0}. Affiniamo le tue abilità...\"",
    "level_master.need_xp_remaining": "Ti servono ancora {0} punti esperienza per raggiungere il livello {1}.",
    "level_master.level_up_title": "  AUMENTO DI LIVELLO!",
    "level_master.advanced_to": "  Sei avanzato al livello {0}!",
    "level_master.advanced_multi": "  Sei avanzato di {0} livelli! ({1} -> {2})",
    "level_master.celeb_good_touch": "  {0} posa una mano gentile sulla tua spalla:",
    "level_master.celeb_good_quote": "  \"La luce dentro di te si fa sempre più forte. Usala con saggezza.\"",
    "level_master.celeb_evil_eyes": "  Gli occhi di {0} brillano con oscura approvazione:",
    "level_master.celeb_evil_quote": "  \"Sì... abbraccia il tuo potere. I deboli tremeranno al tuo cospetto.\"",
    "level_master.celeb_neutral_nod": "  {0} annuisce con quieto rispetto:",
    "level_master.celeb_neutral_quote": "  \"Equilibrio in ogni cosa. Tu cammini sul vero sentiero.\"",
    "level_master.power_surge": "  Il tuo corpo e la tua mente esplodono di nuova energia!",
    "level_master.hp_mana_restored": "  La tua salute e il tuo mana sono stati completamente ripristinati.",
    "level_master.training_earned": "  +{0} Punti Addestramento guadagnati!",
    "level_master.training_total": "  Punti Addestramento Totali: {0}",
    "level_master.training_hint": "  (Usa (A)ddestramento dal Maestro dei Livelli per migliorare le tue abilità)",
    "level_master.milestone_title_earned": "  Hai ottenuto il titolo: {0}!",
    "level_master.milestone_gold": "  BONUS: +{0} Oro!",
    "level_master.milestone_potions": "  BONUS: +{0} Pozioni Curative!",
    "level_master.milestone_adventurer": "Avventuriero",
    "level_master.milestone_adventurer_hint": "Ora puoi avventurarti più in profondità nei dungeon!",
    "level_master.milestone_veteran": "Veterano",
    "level_master.milestone_veteran_hint": "I Sette Sigilli ti attendono ai piani 15, 30, 45, 60, 80, 99 e 100!",
    "level_master.milestone_champion": "Campione",
    "level_master.milestone_champion_hint": "I mostri ora temono il tuo nome!",
    "level_master.milestone_hero": "Eroe",
    "level_master.milestone_hero_hint": "Sei pronto ad affrontare gli Antichi Dèi!",
    "level_master.milestone_legend": "Leggenda",
    "level_master.milestone_legend_hint": "Il tuo potere rivaleggia con quello degli antichi eroi!",
    "level_master.milestone_godslayer": "UCCISORE DI DÈI",
    "level_master.milestone_godslayer_hint": "Hai raggiunto l'apice del potere mortale!",
    "level_master.crystal_empty": "La sfera di cristallo mostra solo nebbie vorticanti... Nessuna anima da scrutare.",
    "level_master.crystal_gesture": "\"{0}\" indica una sfera di cristallo luminescente...",
    "level_master.crystal_who_scry": "Chi desideri scrutare? (Pagina {0} di {1})",
    "level_master.crystal_dead_tag": " [MORTO]",
    "level_master.crystal_npc_entry": "{0,3}. {1} - Livello {2} {3}{4}",
    "level_master.crystal_showing": "Mostrando {0}-{1} di {2} anime",
    "level_master.crystal_nav": "{0}[#] Seleziona per numero  [Q]uit",
    "level_master.crystal_close": "Le nebbie si richiudono attorno alla sfera...",
    "level_master.crystal_invalid": "Scelta non valida. Riprova.",
    "level_master.crystal_reveal": "Le nebbie si aprono per rivelare: {0}",
    "level_master.crystal_class": "  Classe: {0}",
    "level_master.crystal_level": "  Livello: {0}",
    "level_master.crystal_status": "  Stato: {0}",
    "level_master.crystal_location": "  Luogo: {0}",
    "level_master.crystal_alive": "Vivo",
    "level_master.crystal_dead": "Morto",
    "level_master.crystal_combat_stats": "  Statistiche di Combattimento:",
    "level_master.crystal_str_def": "    Forza: {0}   Difesa: {1}",
    "level_master.crystal_agi_dex": "    Agilità: {0}    Destrezza: {1}",
    "level_master.crystal_hp_mana": "    PV: {0}/{1}  Mana: {2}/{3}",
    "level_master.crystal_personality": "  Personalità: {0}",
    "level_master.crystal_fade": "La visione svanisce mentre le nebbie ritornano...",
    "level_master.help_master_looks": "\"{0}\" guarda in lontananza...",
    "level_master.help_no_allies": "\"Non hai alleati da assistere. Recluta compagni o unisciti a una squadra prima.\"",
    "level_master.help_nods": "\"{0}\" annuisce con approvazione...",
    "level_master.help_noble_pursuit": "\"Aiutare i tuoi alleati a diventare più forti è una nobile impresa.\"",
    "level_master.help_share_wisdom": "\"Puoi condividere la tua saggezza (esperienza) per aiutarli ad avanzare.\"",
    "level_master.help_select_ally": "Seleziona un alleato da aiutare:",
    "level_master.help_companion_tag": " [Compagno]",
    "level_master.help_spouse_tag": " [Consorte]",
    "level_master.help_ally_entry": "{0}. {1}{2} - Livello {3} ({4} PE al prossimo livello)",
    "level_master.help_select_prompt": "Seleziona alleato (0 per annullare): ",
    "level_master.help_keep_wisdom": "Decidi di tenere la tua saggezza per te...",
    "level_master.help_needs_xp": "{0} ha bisogno di {1} punti esperienza per raggiungere il livello {2}.",
    "level_master.help_you_have_xp": "Hai {0} punti esperienza.",
    "level_master.help_not_enough_xp": "Non hai abbastanza esperienza da condividere!",
    "level_master.help_how_much": "Quanti PE condividere (max {0}): ",
    "level_master.help_invalid_amount": "Quantità non valida. Nessuna esperienza condivisa.",
    "level_master.help_shared": "Condividi {0} punti esperienza con {1}!",
    "level_master.help_companion_grown": "{0} è cresciuto al livello {1}!",
    "level_master.help_effectiveness": "La loro efficacia in combattimento è aumentata!",
    "level_master.help_npc_level": "{0} ha raggiunto il livello {1}!",
    "level_master.help_npc_multi": "{0} ha guadagnato {1} livelli! ({2} -> {3})",
    "level_master.help_smiles": "\"{0}\" sorride calorosamente...",
    "level_master.help_true_strength": "\"La vera forza si trova nell'elevare gli altri.\"",
    "level_master.reached_level_news": "{0} ha raggiunto il livello {1}!",
    "level_master.advanced_level_news": "{0} è avanzato al livello {1} con l'aiuto di {2}!",
    "quest_hall.header": "LA SALA DELLE MISSIONI",
    "quest_hall.active_quests": "Missioni Attive: {0}",
    "quest_hall.available": "Disponibili: {0}",
    "quest_hall.view": "Visualizza Missioni Disponibili",
    "quest_hall.active": "Missioni Attive",
    "quest_hall.claim": "Accetta una Missione",
    "quest_hall.turn_in": "Consegna Missione",
    "quest_hall.bounty": "Tabellone delle Taglie",
    "quest_hall.abandon": "Abbandona Missione",
    "quest_hall.leave": "Lasci la Sala delle Missioni.",
    "quest_hall.cancel": "Annulla",
    "time.dawn": "alba",
    "time.morning": "mattina",
    "time.noon": "mezzogiorno",
    "time.afternoon": "pomeriggio",
    "time.evening": "sera",
    "time.night": "notte",
    "time.late_night": "notte fonda",
    "prefs.title": "PREFERENZE RAPIDE",
    "prefs.current_settings": "Impostazioni Attuali:",
    "prefs.options": "Opzioni:",
    "prefs.combat_speed": "Velocità di Combattimento",
    "prefs.combat_speed.normal": "Normale (ritardi completi)",
    "prefs.combat_speed.fast": "Veloce (50% ritardi)",
    "prefs.combat_speed.instant": "Istantanea (nessun ritardo)",
    "prefs.auto_heal": "Auto-cura in Battaglia",
    "prefs.skip_intimate": "Salta Scene Intime",
    "prefs.skip_intimate.on": "Attivato (Dissolvenza al Nero)",
    "prefs.skip_intimate.off": "Disattivato (Scene Complete)",
    "prefs.screen_reader": "Modalità Screen Reader",
    "prefs.screen_reader.on": "Attivato (Testo Semplificato)",
    "prefs.compact_mode": "Modalità Compatta",
    "prefs.compact_mode.on": "Attivato (Mobile/Schermo Piccolo)",
    "prefs.color_theme": "Tema Colore",
    "prefs.auto_level": "Aumento Livello Automatico",
    "prefs.auto_level.on": "Attivato (Sali di livello automaticamente)",
    "prefs.auto_level.off": "Disattivato (Visita il Maestro dei Livelli per salire di livello)",
    "prefs.auto_equip": "Equipaggiamento Automatico",
    "prefs.auto_equip.on": "Attivato (Equipaggia all'acquisto)",
    "prefs.auto_equip.off": "Disattivato (Gli acquisti vanno nell'inventario)",
    "prefs.telemetry": "Telemetria Alpha",
    "prefs.telemetry.on": "Attivato (Invio Statistiche Anonime)",
    "prefs.terminal_font": "Font del Terminale",
    "prefs.language": "Lingua",
    "prefs.select_language": "Seleziona Lingua:",
    "prefs.language_set": "Lingua impostata: {0}",
    "prefs.enabled": "Attivato",
    "prefs.disabled": "Disattivato",
    "prefs.on": "ON",
    "prefs.off": "OFF",
    "prefs.back": "Indietro",
    "prefs.current": "Attuale: {0}",
    "prefs.toggle": "Attiva/Disattiva {0}",
    "save.saving": "Salvataggio in corso...",
    "save.saved": "Partita salvata!",
    "save.loading": "Caricamento in corso...",
    "save.loaded": "Salvataggio caricato con successo!",
    "arena.header": "L'ARENA",
    "dormitory.header": "IL DORMITORIO",
    "dormitory.desc1": "File di brande di legno scricchiolante si allineano lungo le pareti. L'aria calda e stantia è satura ",
    "dormitory.desc2": "dell'",
    "dormitory.desc3": "odore di sudore e birra a buon mercato. ",
    "dormitory.desc4": "Qualche massa russante si agita sotto coperte sottili.",
    "dormitory.what_to_do": "Cosa desideri fare?",
    "dormitory.sleep_warning": "  ATTENZIONE: Dormire qui ti lascia vulnerabile agli attacchi!",
    "dormitory.sleeping_guests": "Ospiti Addormentati",
    "dormitory.no_sleepers": "Nessuno sta dormendo in questo momento.",
    "dormitory.sleeping_npcs": "  PNG Addormentati:",
    "dormitory.vulnerable_players": "  Giocatori Vulnerabili:",
    "dormitory.nobody_examine": "Nessuno da esaminare.",
    "dormitory.enter_sleeper": "Inserisci il numero o il nome del dormiente: ",
    "dormitory.no_such_sleeper": "Nessun dormiente trovato.",
    "dormitory.stay_night": "Restare qui per la notte? (s/N): ",
    "dormitory.claim_bunk": "Reclami una branda libera e scivoli in un sonno inquieto...",
    "dormitory.awaken_refreshed": "Ti risvegli riposato, pronto per un nuovo giorno di avventura.",
    "dormitory.cost_bunk": "  Costo: {0}mo per una branda.",
    "dormitory.sleep_vulnerable": "  ATTENZIONE: Sei vulnerabile agli attacchi mentre dormi qui!",
    "dormitory.sleep_logout": "Dormire qui stanotte e disconnettersi? (s/N): ",
    "dormitory.bank_withdrawn": "  ({0}mo prelevate dal tuo conto in banca)",
    "dormitory.cant_afford": "Non puoi permetterti nemmeno questa branda piena di pulci.",
    "dormitory.checked_gold": "  (Oro disponibile: {0} e in banca: {1})",
    "dormitory.claim_thin_blanket": "Reclami una branda e ti tiri addosso la sottile coperta...",
    "dormitory.drift_uneasy": "Scivoli in un sonno inquieto... (disconnessione)",
    "dormitory.slit_throat": "Chiunque potrebbe tagliarti la gola nella notte.",
    "dormitory.not_available": "Non disponibile.",
    "dormitory.no_vulnerable": "Nessun dormiente vulnerabile nel dormitorio.",
    "dormitory.vulnerable_title": "Dormitorio — Dormienti Vulnerabili",
    "dormitory.who_attack": "Chi vuoi attaccare? (numero o nome, vuoto per annullare): ",
    "dormitory.no_longer_here": "Non sono più qui.",
    "dormitory.creep_toward": "  Ti avvicini furtivamente alla branda di {0}, arma alla mano...",
    "dormitory.steal_gold": "Frugi tra i loro averi e rubi {0} monete d'oro!",
    "dormitory.leave_body": "Lasci il corpo di {0} sulla branda.",
    "dormitory.also_take": "Prendi anche il loro {0}!",
    "dormitory.leave_lifeless": "Lasci il corpo senza vita di {0} sulla branda.",
    "dormitory.fought_off": "{0} ti ha respinto anche nel dormiveglia!",
    "dormitory.fought_off_sleep": "{0} ti ha respinto persino nel sonno!",
    "dormitory.could_not_load": "Impossibile caricare i loro dati.",
    "dormitory.too_righteous": "Ti senti troppo retto per causare simili misfatti oggi.",
    "dormitory.no_one_disturb": "Non c'è nessuno da disturbare.",
    "dormitory.thunderous_shout": "Lanci un grido tonante!",
    "dormitory.wakes_furious": "{0} si sveglia furioso e ti attacca!",
    "dormitory.knocked_out": "Sei stato steso!",
    "dormitory.subdued": "Hai sottomesso {0}.",
    "dormitory.faction_plummeted": "La tua reputazione con {0} è precipitata! (-200)",
    "marketplace.header": "IL MERCATO",
    "marketplace.bulletin": "Consulta la bacheca",
    "marketplace.buy": "Compra oggetto",
    "marketplace.sell": "Metti in vendita un oggetto",
    "marketplace.status": "Stato",
    "marketplace.return": "Torna alla Via Principale",
    "music_shop.header": "BOTTEGA DELLA MUSICA DI MELODIA",
    "music_shop.buy_instruments": "Compra Strumenti",
    "music_shop.performance": "Ingaggia un'Esibizione, potenziamenti per 5 combattimenti",
    "music_shop.talk_melodia": "Parla con Melodia",
    "music_shop.talk_melodia_interested": "Parla con Melodia  (sembra interessata alle tue avventure)",
    "music_shop.lore_songs": "Ballate degli Antichi Dèi",
    "music_shop.lore_songs_ancient": "antiche ballate",
    "music_shop.return": "Torna alla Via Principale",
    "music_shop.instruments": "Strumenti",
    "music_shop.hire_performance": "Ingaggia un'Esibizione",
    "music_shop.atmo1": "Strumenti di ogni tipo pendono dalle pareti e dal soffitto — liuti, lire,",
    "music_shop.atmo2": "arpe, tamburi, e cose di cui non conosci il nome. L'aria stessa sembra",
    "music_shop.atmo3": "ronzare sommessamente, come se gli strumenti sussurrassero tra loro.",
    "music_shop.state_inshop1": "Melodia siede in fondo, accordando un liuto. La sua apprendista Cadence",
    "music_shop.state_inshop2": "è dietro il bancone, lucidando un flauto d'argento.",
    "music_shop.state_inshop3": "Cadence sorride. \"Benvenuto! Cerchi qualcosa da comprare, o solo da ascoltare?\"",
    "music_shop.state_adv1": "Cadence è dietro il bancone, gestendo la bottega con silenziosa",
    "music_shop.state_adv2": "sicurezza. Un cartello dipinto a mano recita: \"Melodia è in",
    "music_shop.state_adv3": "avventura. Tutti i servizi sono ancora disponibili — mi ha insegnato bene!\"",
    "music_shop.state_adv4": "\"Parla di te, lo sai,\" dice Cadence con un sorriso.",
    "music_shop.state_dead1": "Cadence è dietro il bancone, da sola. Un fiore secco riposa",
    "music_shop.state_dead2": "accanto a un ritratto incorniciato di Melodia sulla parete.",
    "music_shop.state_dead3": "\"Avrebbe voluto che la musica continuasse,\" dice Cadence a bassa voce.",
    "music_shop.state_dead4": "\"Quindi è quello che faccio. Cosa posso suonare per te?\"",
    "music_shop.gold_crowns": " monete d'oro.",
    "music_shop.bard_discount": "  Come musicista, ricevi uno sconto del 25% sulle esibizioni.",
    "music_shop.services": "Servizi:",
    "music_shop.performance_desc": "  — potenziamenti per 5 combattimenti",
    "music_shop.sr_inshop": "Melodia e la sua apprendista Cadence sono qui.",
    "music_shop.sr_adv": "Cadence gestisce la bottega. Melodia è in avventura.",
    "music_shop.sr_dead": "Cadence mantiene viva la musica in memoria di Melodia.",
    "music_shop.sr_bard_discount": "Sconto bardo: 25% sulle esibizioni.",
    "music_shop.bbs_inshop": " Cadence al bancone. Melodia accorda un liuto in fondo. ",
    "music_shop.bbs_adv": " Cadence gestisce la bottega. Melodia è in avventura. ",
    "music_shop.bbs_dead": " Cadence mantiene viva la musica in memoria di Melodia. ",
    "music_shop.bbs_gold": " mo.",
    "music_shop.no_instruments": "\"Temo di non avere strumenti adatti al tuo livello in questo momento.\"",
    "music_shop.current": "Attuale: ",
    "music_shop.page_info": "Pagina {0}/{1} - {2} strumenti disponibili",
    "music_shop.col_header": "  #   Nome                        Liv  Pot  Prezzo      Bonus",
    "music_shop.enter_buy": "Inserisci # per comprare",
    "music_shop.next_prev": ", [N]ext/[P]rec pagina",
    "music_shop.or_quit": ", o [Q]uit:",
    "music_shop.buy_confirm": "Compra {0} per ",
    "music_shop.incl_tax": " (tasse incluse)",
    "music_shop.gold_yn": " monete d'oro? [S/N]",
    "music_shop.bard_only": "Solo i Bardi possono impugnare strumenti in combattimento.",
    "music_shop.seller_approve": "{0} annuisce con approvazione. \"Un'ottima scelta! Che canti il vero in battaglia.\"",
    "music_shop.perf_intro": "{0} può suonarti una canzone il cui potere persiste per 5 combattimenti.",
    "music_shop.perf_tales": "Ogni esibizione racconta una storia diversa dalla storia del reame.",
    "music_shop.active_buff": "Potenziamento attivo: {0} ({1} combattimenti rimanenti)",
    "music_shop.replace_buff": "Una nuova esibizione sostituirà quella attuale.",
    "music_shop.song_war_march": "Marcia di Guerra",
    "music_shop.song_war_march_desc": " — +15% danno d'attacco",
    "music_shop.song_iron": "Ninna Nanna di Ferro",
    "music_shop.song_iron_desc": " — +15% difesa",
    "music_shop.song_fortune": "Melodia della Fortuna",
    "music_shop.song_fortune_desc": " — +25% oro dalle uccisioni",
    "music_shop.song_hymn": "Inno di Battaglia",
    "music_shop.song_hymn_desc": " — +10% attacco E +10% difesa",
    "music_shop.bard_discount_perf": "  * Sconto bardo: 25% su tutte le esibizioni!",
    "music_shop.song_prompt": "Inserisci # canzone o [Q]uit:",
    "music_shop.notes_fade": "Le ultime note svaniscono. La stanza resta in silenzio per un momento.",
    "music_shop.buff_gained": "La {0} risveglia qualcosa in te. (+{1}% per {2} combattimenti)",
    "music_shop.already_traveling": "Melodia sta già viaggiando con te!",
    "music_shop.cadence_handled": "Cadence saluta dal bancone. \"Qui è tutto sotto controllo!\"",
    "music_shop.cadence_portrait": "Cadence lancia uno sguardo al ritratto sulla parete e distoglie lo sguardo.",
    "music_shop.party_full": "Il tuo gruppo è al completo. Visita la Locanda per gestire i compagni.",
    "music_shop.offer_stands": "\"L'offerta resta valida quando sarai pronto. Sarò qui.\"",
    "music_shop.lore_dead": "Antiche ballate che Melodia tramandò a Cadence prima di cadere.",
    "music_shop.lore_adv": "Antiche ballate che Melodia insegnò a Cadence prima di partire per la sua avventura.",
    "music_shop.lore_inshop": "Antiche ballate sui sette dèi che plasmarono questo mondo.",
    "music_shop.lore_unlock": "Le canzoni si sbloccano man mano che ne incontri i soggetti nel dungeon.",
    "music_shop.lore_new": " (NUOVO)",
    "music_shop.lore_locked": "??? — Non hai ancora incontrato questo essere.",
    "music_shop.lore_none": "Nessuna canzone disponibile ancora. Avventurati più in profondità nel dungeon...",
    "music_shop.lore_prompt": "Inserisci # canzone per ascoltare, o [Q]uit:",
    "music_shop.lore_not_unlocked": "Questa canzone non è ancora stata sbloccata.",
    "music_shop.lore_stirs": "Qualcosa si muove dentro di te... una comprensione più profonda degli dèi.",
    "music_shop.you_have": "Hai ",
    "ui.cancel": "Annulla",
    "ui.leave": "Esci",
    "ui.leave_shop": "Esci dalla bottega",
    "ui.done_shopping": "Fine acquisti",
    "anchor_road.bounty_header": "CACCIA ALLA TAGLIA",
    "anchor_road.gang_war_header": "GUERRA TRA BANDE",
    "anchor_road.gauntlet_header": "IL GUANTO DI SFIDA",
    "anchor_road.claim_town_header": "CONQUISTA LA CITTÀ",
    "anchor_road.prison_header": "CORTILE DELLA PRIGIONE",
    "magic_shop.enchant_header": "FUCINA DEGLI INCANTAMENTI",
    "magic_shop.romance_header": "ROMANTICISMO ARCANO",
    "magic_shop.dark_arts_header": "ARTI OSCURE",
    "magic_shop.item_properties": "Proprietà Oggetto",
    "magic_shop.enchant_bless": "Servizi di Incantamento e Benedizione",
    "magic_shop.stat_enchant": "Incantamenti di Statistiche (scegli una statistica)",
    "magic_shop.special_enchant": "Incantamenti Speciali",
    "magic_shop.mythic_enchant": "Incantamenti Mitici ed Elementali",
    "magic_shop.enchant_removal": "Rimozione Incantamento",
    "magic_shop.sell_accessories": "Vendi Accessori",
    "quest.available": "Missioni Disponibili",
    "quest.active": "Le Tue Missioni Attive",
    "quest.bounty_board": "TABELLONE DELLE TAGLIE",
    "weapon_shop.sell_header": "Vendi Armi/Scudi",
    "weapon_shop.auto_buy": "Acquisto Automatico Migliore Arma",
    "weapon_shop.kicked_out1": "I grossi troll ti sollevano e ti buttano fuori!",
    "weapon_shop.kicked_out2": "Forse dovresti stare più attento a mercanteggiare la prossima volta...",
    "weapon_shop.kicked_return": "Premi Invio per tornare in strada...",
    "weapon_shop.you_have": "Hai ",
}
