translations = {
    "magic_shop.scry_dead": "MORTO",
    "magic_shop.scry_alive": "Vivo",
    "magic_shop.scry_married_to": "Sposato con:",
    "magic_shop.scry_personality": "Personalità:",
    "magic_shop.conversation_with": "Conversazione con {0}",
    "magic_shop.end_conversation": "Termina conversazione",
    "dialogue.what_to_say": "Cosa vuoi dire?",
    "dialogue.end_conversation": "Termina conversazione",
    "dialogue.not_understood": "Non hanno capito bene cosa intendevi...",
    "dialogue.decide_not_push": "Decidi di non insistere.",
    "dialogue.new_romance": "È sbocciata una nuova relazione romantica!",
    "dialogue.intimate_warning": "Questo porterà a una scena intima. Continuare? S/N",
    "dialogue.marriage_proposal": "PROPOSTA DI MATRIMONIO",
    "dialogue.age_requirement": "Devi avere almeno {0} anni per sposarti!",
    "dialogue.already_married": "Sei già sposato! Divorzia prima o discuti la poligamia con il tuo coniuge.",
    "dialogue.wedding_cost": "Una cerimonia nuziale costa {0} monete d'oro. Ne hai solo {1}.",
    "dialogue.wedding_ceremony": "<3<3<3 CERIMONIA NUZIALE <3<3<3",
    "dialogue.now_married": "ORA SEI SPOSATO CON {0}!",
    "dialogue.marriage_benefits": "Benefici del Matrimonio:",
    "dialogue.benefit_xp": "+10% bonus PE dai combattimenti finché il tuo coniuge è in vita",
    "dialogue.benefit_combat_ally": "Il tuo coniuge potrebbe unirti in combattimento come alleato",
    "dialogue.benefit_home_children": "Condividi una casa e avrai dei figli insieme",
    "dialogue.benefit_intimate": "Goditi momenti intimi speciali a casa",
    "dialogue.adopt_children": "Puoi adottare bambini al Regio Orfanotrofio!",
    "dialogue.try_for_children": "Torna a casa e prova ad avere dei figli!",
    "dialogue.press_enter_new_life": "Premi Invio per continuare la tua nuova vita...",
    "_comment_street_encounter": "=== Sistema Incontri di Strada ===",
    "_comment_street_grudge": "=== Sistema Rancori/Confronti di Strada ===",
    "_comment_opening_story": "=== Sistema Storia d'Apertura ===",
    "opening_story.skip_hint": "Premi SPAZIO per saltare avanti in qualsiasi momento",
    "opening_story.the_awakening": "IL RISVEGLIO",
    "opening_story.letter_title": "Una Lettera a Te Stesso",
    "opening_story.parchment_crumbles": "La pergamena si sgretola in polvere tra le tue mani.",
    "opening_story.words_burn": "Ma le parole bruciano nella tua mente.",
    "opening_story.journey_begins": "IL TUO VIAGGIO HA INIZIO",
    "opening_story.what_to_do": "Cosa fare per primo:",
    "opening_story.tip_explore": "Esplora la città. Visita i negozi, la locanda, il tempio.",
    "opening_story.tip_equip": "Compra equipaggiamento nei negozi di armi e armature.",
    "opening_story.tip_dungeon": "Entra nei Sotterranei per combattere mostri e diventare più forte.",
    "opening_story.tip_seals": "Cerca i Sette Sigilli nascosti nelle profondità del sotterraneo.",
    "opening_story.tip_dreams": "Presta attenzione ai tuoi sogni. Celano delle verità.",
    "opening_story.press_enter_journey": "Premi Invio per iniziare il tuo viaggio...",
    "opening_story.welcome": "Benvenuto nel mondo di Usurper.",
    "opening_story.may_you_find": "Possa tu trovare ciò che stai cercando.",
    "opening_story.remember_forgotten": "O ricordare ciò che hai dimenticato.",
    "opening_story.cycle_header": "CICLO {0}",
    "opening_story.echoes_power": "Gli echi dei cicli passati ti rafforzano:",
    "opening_story.press_enter_cycle": "Premi Invio per ricominciare il ciclo...",
    "_comment_opening_sequence": "=== Sequenza d'Apertura e Sistema dei Cicli ===",
    "opening.air_grows_cold": "L'aria si fa fredda.",
    "opening.shadows_lengthen": "Le ombre attorno a te si allungano in modo innaturale.",
    "opening.time_pauses": "Per un istante, il tempo stesso sembra fermarsi.",
    "opening.not_alone": "Non sei solo.",
    "opening.priest_approaches": "Un sacerdote del tempio si avvicina a te, con aria turbata.",
    "opening.priest_mark": "\"Tu... porti il marchio dei Sigilli,\" sussurra.",
    "opening.priest_visions": "\"I sacerdoti hanno avuto delle visioni. Devi sapere:\"",
    "opening.priest_first_seal": "\"Il primo Sigillo giace nelle profondità del sotterraneo, al 15° livello.\"",
    "opening.priest_25th_level": "\"Ma attento — al 25° livello, qualcosa di antico si agita.\"",
    "opening.priest_god_of_war": "\"Maelketh, il Dio della Guerra, si sta risvegliando.\"",
    "opening.priest_be_ready": "\"Sii pronto quando raggiungerai quelle profondità. Sii pronto.\"",
    "opening.priest_fades": "Il sacerdote si dilegua nella folla.",
    "opening.tremor": "Un tremito profondo percorre il terreno sotto i tuoi piedi.",
    "opening.tankards_rattle": "I boccali tintinnano sui tavoli. La polvere cade dalle travi.",
    "opening.veteran_turns": "Un veterano dal volto segnato al bancone si volta verso di te.",
    "opening.veteran_feel_that": "\"L'hai sentito?\" mormora.",
    "opening.veteran_god_awakens": "\"{0} si sta risvegliando. Il sotterraneo diventa più pericoloso.\"",
    "opening.veteran_dangerous": "\"Se hai intenzione di scendere in profondità, fallo presto.\"",
    "opening.veteran_do_it_soon": "\"Prima che le cose peggiorino.\"",
    "opening.eternal_cycle": "IL CICLO ETERNO",
    "opening.world_fades": "Il mondo svanisce attorno a te...",
    "opening.familiar_voice": "Una voce familiare riecheggia nel vuoto:",
    "opening.cycle_never_ends": "\"Il ciclo non finisce mai.\"",
    "opening.wheel_turns": "\"La ruota gira. L'onda ritorna all'oceano.\"",
    "opening.you_remember": "\"Ma tu... tu ricordi. Ricordi sempre qualcosa in più.\"",
    "opening.entering_cycle": "Entrando nel Ciclo {0}...",
    "opening.carry_forward": "Porti con te gli echi dei cicli passati:",
    "opening.bonus_strength": "  +{0} Forza",
    "opening.bonus_defence": "  +{0} Difesa",
    "opening.bonus_stamina": "  +{0} Vigore",
    "opening.bonus_gold": "  +{0} Oro Iniziale",
    "opening.bonus_exp": "  +{0}% Esperienza",
    "opening.bonus_artifacts": "Le posizioni degli artefatti sono rivelate fin dall'inizio",
    "opening.bonus_key": "Inizi con la Chiave Antica",
    "opening.press_enter_new_cycle": "Premi Invio per iniziare il nuovo ciclo...",
    "opening.cycle_str_bonus": "+{0} Forza (bonus ciclo)",
    "opening.cycle_def_bonus": "+{0} Difesa (bonus ciclo)",
    "opening.cycle_sta_bonus": "+{0} Vigore (bonus ciclo)",
    "opening.cycle_gold_bonus": "+{0} Oro Iniziale (bonus ciclo)",
    "opening.cycle_exp_bonus": "+{0}% Esperienza (bonus ciclo)",
    "opening.cycle_artifacts_revealed": "Posizioni degli artefatti rivelate",
    "opening.cycle_ancient_key": "Chiave Antica conservata",
    "opening.cycle_ocean_remembers": "L'Oceano ricorda il tuo vero finale",
    "_comment_old_god": "=== Sistema Boss Antichi Dèi ===",
    "old_god.save_came_back": "\"Sei tornato.\"",
    "old_god.save_brought_it": "\"E l'hai portato. L'artefatto.\"",
    "old_god.save_artifact_works": "Alzi l'artefatto. La luce erutta dal suo interno.",
    "old_god.save_corruption_peels": "La corruzione si stacca come cenere in una fiamma.",
    "old_god.save_something_clean": "Qualcosa di puro e luminoso emerge da sotto.",
    "old_god.save_staggers": "{0} barcolla, ma non cade.",
    "old_god.save_i_remember": "\"Io... ricordo. Ricordo ciò che ero.\"",
    "old_god.save_xp_reward": "  Guadagni {0} esperienza per la tua clemenza.",
    "old_god.save_chivalry": "  +100 Cavalleria — La tua clemenza viene notata dall'universo.",
    "old_god.say_nothing": "Non dici nulla. Il tuo silenzio parla per te.",
    "old_god.god_stares": "{0} ti fissa a lungo.",
    "old_god.maelketh_silence_rage": "Il tuo silenzio mi fa infuriare! E così sia!",
    "old_god.god_have_it_your_way": "Come vuoi tu, allora.",
    "old_god.god_attacks": "L'Antico Dio attacca!",
    "old_god.ground_trembles": "Il terreno trema sotto i tuoi piedi...",
    "old_god.ancient_power_stirs": "Un potere antico si agita nell'oscurità...",
    "old_god.seal_shatters": "Il sigillo si frantuma mentre {0} si risveglia!",
    "old_god.armor_divine_shield": "Scudo Divino",
    "old_god.armor_stone_skin": "Pelle di Pietra",
    "old_god.armor_creators_ward": "Protezione del Creatore",
    "old_god.armor_divine": "Armatura Divina",
    "old_god.warning_protected": "  ATTENZIONE: {0} è protetto da {1}!",
    "old_god.warning_less_damage": "  La tua arma non incantata infliggerà il {0}% di danni in meno.",
    "old_god.warning_enchant": "  Trova un'arma incantata per aggirare questa protezione!",
    "old_god.press_enter_face": "Premi Invio per affrontare l'Antico Dio...",
    "old_god.mod_fury_bright": "La tua furia arde luminosa! +25% danni, -15% difesa, +15% critico",
    "old_god.mod_maelketh_teachings": "Gli insegnamenti di Maelketh ti guidano. +20% difesa, boss -15% danni",
    "old_god.mod_veloura_hostile": "Veloura diventa ostile! +15% danni, ma anche lei combatte più duramente",
    "old_god.mod_veloura_empathy": "La tua empatia indebolisce la determinazione di Veloura. Boss -20% danni",
    "old_god.mod_veloura_mercy": "Un colpo di grazia. Veloura accetta il suo destino. Boss -30% difesa",
    "old_god.mod_thorgrim_defiant": "Thorgrim giudica duramente la tua sfida. Boss +15% danni",
    "old_god.mod_thorgrim_honor": "Combattimento onorevole! +15% difesa, +20 difesa bonus",
    "old_god.mod_thorgrim_broken": "La logica di Thorgrim è frantumata! Boss confuso, -25% danni, -15% difesa",
    "old_god.mod_noctura_teaching": "Noctura si trattiene, insegnando attraverso il combattimento.",
    "old_god.mod_noctura_teaching_stats": "  Boss al 50% della potenza, -30% difesa. I tuoi danni +15%.",
    "old_god.mod_noctura_enraged": "Noctura è infuriata dal tuo rifiuto!",
    "old_god.mod_noctura_enraged_stats": "  Boss +25% danni. I tuoi critici più difficili da ottenere.",
    "old_god.mod_noctura_reluctant": "Noctura combatte con riluttanza.",
    "old_god.mod_noctura_reluctant_stats": "  Boss -30% danni, -15% difesa. I tuoi danni +10%.",
    "old_god.mod_noctura_standard": "Noctura ti osserva con fredda indifferenza.",
    "old_god.mod_aurelion_defiant": "La tua sfida ti dà potere! +20% danni, -10% difesa",
    "old_god.mod_aurelion_humble": "La tua umiltà addolcisce Aurelion. Boss -15% danni, +15% difesa",
    "old_god.mod_aurelion_neutral": "Aurelion ti mette alla prova senza pregiudizi.",
    "old_god.mod_terravok_destructive": "Il tuo sentiero distruttivo fa adirare Terravok! +30% danni, boss +20% danni",
    "old_god.mod_terravok_respectful": "Il tuo rispetto indebolisce la volontà di combattere di Terravok. Boss -10% danni",
    "old_god.mod_terravok_neutral": "Terravok ti affronta con antica pazienza.",
    "old_god.mod_manwe_compassion": "La tua compassione scuote la convinzione di Manwe. Boss -20% danni, -15% difesa",
    "old_god.mod_manwe_righteous": "Furia giusta! +15% difesa, boss -10% danni",
    "old_god.mod_manwe_allies": "I tuoi dèi alleati prestano il loro potere! +20% danni e difesa",
    "old_god.mod_manwe_saved_gods": "Gli dèi che hai salvato indeboliscono la determinazione di Manwe. Boss -15% danni",
    "old_god.mod_manwe_destroyed": "Il potere degli dèi distrutti scorre in te! +35% danni, +20% critico",
    "old_god.mod_defiant_spirit": "Il tuo spirito ribelle aggiunge +50 danni bonus!",
    "old_god.mod_willing_hero": "L'eroe volenteroso tiene duro. +30 difesa bonus!",
    "old_god.header_saved": "{0} — SALVATO",
    "old_god.saved_darkness_lifts": "L'oscurità si dissolve dagli occhi di {0}.",
    "old_god.saved_seeing_world": "Per la prima volta in millenni, il dio vede il mondo con chiarezza.",
    "old_god.saved_xp": "  +{0} PE",
    "old_god.saved_chivalry": "  +100 Cavalleria",
    "old_god.material_left_behind": "{0} ha lasciato {2}x {1}.",
    "old_god.heart_of_ocean": "Hai trovato un Cuore dell'Oceano!",
    "old_god.header_defeated": "{0} — SCONFITTO",
    "old_god.defeated_fades": "{0} svanisce nel nulla, un ultimo sussurro nel vento.",
    "old_god.defeated_crystallizes": "L'essenza del dio si cristallizza in {1}x {0}.",
    "old_god.defeated_xp": "  +{0} PE",
    "old_god.defeated_gold": "  +{0} Oro",
    "old_god.header_defeat": "SCONFITTA",
    "old_god.defeat_hit_ground": "Cadi pesantemente a terra. {0} incombe su di te.",
    "old_god.defeat_not_good_enough": "\"Non abbastanza. Non ancora.\"",
    "old_god.defeat_goes_dark": "Tutto diventa buio...",
    "old_god.defeat_pulls_back": "Ma qualcosa ti trattiene dal precipizio.",
    "old_god.defeat_wake_up": "Ti risvegli, malconcio ma vivo. Il dio è scomparso.",
    "_comment_world_boss": "=== Sistema Boss Mondiale ===",
    "world_boss.online_only": "I boss mondiali appaiono solo nella modalità multigiocatore online.",
    "world_boss.min_level": "Devi essere almeno di livello {0} per sfidare un boss mondiale.",
    "world_boss.attack_boss": "Attacca il Boss",
    "world_boss.header": "BOSS MONDIALE",
    "world_boss.no_active": "Nessun boss mondiale è attivo al momento.",
    "world_boss.appear_when_enough": "I boss mondiali appaiono quando abbastanza eroi sono online.",
    "world_boss.spawn_info": "I boss appaiono automaticamente quando 2+ giocatori sono online.",
    "world_boss.duration_info": "Ogni boss resta per 1 ora prima di ritirarsi.",
    "world_boss.phase_label": "Fase {0}/{1}",
    "world_boss.time_remaining": "Tempo rimanente: {0}m {1}s",
    "world_boss.time_expired": "Tempo scaduto! Il boss si sta ritirando...",
    "world_boss.element": "Elemento",
    "world_boss.attacks_per_round": "Attacchi/Turno",
    "world_boss.damage_leaderboard": "Classifica Danni",
    "world_boss.death_cooldown": "Devi attendere {0} secondi prima di affrontare di nuovo il boss.",
    "world_boss.too_injured": "Sei troppo ferito per combattere. Guarisci prima!",
    "world_boss.error_load": "Errore nel caricamento dei dati del boss. Riprova più tardi.",
    "world_boss.engage": "Affronti {0}, {1} in combattimento!",
    "world_boss.prepare_yourself": "Preparati!",
    "world_boss.has_been_defeated": "{0} è stato sconfitto!",
    "world_boss.realm_celebrates": "Il reame esulta!",
    "world_boss.cannot_act": "Sei afflitto da {0} e non puoi agire!",
    "world_boss.total_round_damage": "Danni totali del turno: {0}",
    "world_boss.boss_hp_remaining": "PV boss rimanenti: {0}",
    "world_boss.killing_blow": "Hai sferrato il colpo fatale!",
    "world_boss.aura_damage": "L'aura di presenza di {0} infligge {1} danni!",
    "world_boss.struck_you_down": "{0} ti ha abbattuto!",
    "world_boss.total_damage_before_fall": "Danni totali inflitti prima di cadere: {0}",
    "world_boss.healers_safety": "I guaritori ti trascinano in salvo. PV: {0}/{1}",
    "world_boss.must_wait": "Devi attendere {0} secondi prima di rientrare in combattimento.",
    "world_boss.max_rounds": "Hai combattuto per {0} turni — durata massima della sessione raggiunta.",
    "world_boss.step_back": "Fai un passo indietro per riprendere fiato.",
    "world_boss.combat_summary": "Riepilogo Combattimento",
    "world_boss.rounds_fought": "Turni combattuti: {0}",
    "world_boss.damage_dealt": "Danni inflitti: {0}",
    "world_boss.choose_action": "Scegli la tua azione:",
    "world_boss.action_attack": "Attacco",
    "world_boss.action_cast": "Lancia Incantesimo",
    "world_boss.action_defend": "Difesa",
    "world_boss.action_item": "Oggetto",
    "world_boss.action_power": "Attacco Potente",
    "world_boss.action_precise": "Colpo Preciso",
    "world_boss.action_ability": "Abilità di Classe",
    "world_boss.action_retreat": "Ritirata",
    "world_boss.action_prompt": "Azione: ",
    "world_boss.you_strike": "Colpisci {0} per {1} danni!",
    "world_boss.raise_guard": "Alzi la guardia! Difesa raddoppiata per 2 turni.",
    "world_boss.retreat": "Ti ritiri dalla battaglia.",
    "world_boss.power_attack_miss": "Il tuo attacco potente manca!",
    "world_boss.power_attack_hit": "ATTACCO POTENTE! Colpisci {0} per {1} danni!",
    "world_boss.precise_crit": "CRITICO! Il tuo colpo preciso colpisce {0} per {1} danni!",
    "world_boss.precise_hit": "Il tuo colpo preciso colpisce {0} per {1} danni.",
    "world_boss.cannot_cast": "Non puoi lanciare incantesimi.",
    "world_boss.need_weapon_spell": "Hai bisogno di un {0} per lanciare incantesimi!",
    "world_boss.no_spells": "Non conosci alcun incantesimo.",
    "world_boss.available_spells": "Incantesimi Disponibili",
    "world_boss.not_enough_mana": "Mana insufficiente per lanciare incantesimi.",
    "world_boss.cast_which_spell": "Quale incantesimo lanciare? (# o Q): ",
    "world_boss.healed_for": "Guarito di {0}! PV: {1}/{2}",
    "world_boss.protection_increased": "Protezione aumentata di {0}!",
    "world_boss.attack_increased": "Potenza d'attacco aumentata di {0}!",
    "world_boss.drink_potion": "Bevi una pozione curativa! +{0} PV ({1}/{2})",
    "world_boss.potions_remaining": "Pozioni rimanenti: {0}",
    "world_boss.no_abilities": "Non hai abilità di classe.",
    "world_boss.class_abilities": "Abilità di Classe",
    "world_boss.all_on_cooldown": "Tutte le abilità sono in ricarica.",
    "world_boss.use_which_ability": "Quale abilità usare? (# o Q): ",
    "world_boss.boss_strikes": "{0} ti colpisce per {1} danni! PV: {2}/{3}",
    "world_boss.boss_uses_ability": "{0} usa {1}!",
    "world_boss.afflicted_with": "Sei afflitto da {0} per {1} turni!",
    "world_boss.resist_effect": "Resisti all'effetto {0}!",
    "world_boss.boss_regenerates": "{0} rigenera salute!",
    "world_boss.phase_1_desc": "La battaglia ha inizio",
    "world_boss.phase_2_desc": "Il boss diventa disperato",
    "world_boss.phase_3_desc": "Ultima resistenza — assalto totale",
    "world_boss.rewards_header": "Ricompense — {0}",
    "ui.gold_word": "oro",
    "inventory.prompt": "Inventario: ",
    "inventory.title": "INVENTARIO",
    "inventory.combat_style": "Stile di Combattimento: ",
    "inventory.style_dual_wield": "Doppia Impugnatura",
    "inventory.style_two_handed": "Arma a Due Mani",
    "inventory.style_sword_shield": "Spada e Scudo",
    "inventory.style_single_weapon": "Arma Singola",
    "inventory.section_equipped": "OGGETTI EQUIPAGGIATI",
    "inventory.section_weapons": "ARMI",
    "inventory.section_armor": "ARMATURE",
    "inventory.section_accessories": "ACCESSORI",
    "inventory.slot_main_hand": "Mano Principale",
    "inventory.slot_off_hand": "Mano Secondaria",
    "inventory.slot_body": "Corpo",
    "inventory.slot_head": "Testa",
    "inventory.slot_arms": "Braccia",
    "inventory.slot_hands": "Mani",
    "inventory.slot_legs": "Gambe",
    "inventory.slot_feet": "Piedi",
    "inventory.slot_waist": "Vita",
    "inventory.slot_face": "Volto",
    "inventory.slot_cloak": "Mantello",
    "inventory.slot_neck": "Collo",
    "inventory.slot_left_finger": "Dito Sinistro",
    "inventory.slot_right_finger": "Dito Destro",
    "inventory.using_2h": "(usa arma a 2 mani)",
    "inventory.backpack": "ZAINO",
    "inventory.backpack_empty": "  (vuoto)",
    "inventory.and_more": "  ... e altri {0} oggetti",
    "inventory.section_bonuses": "BONUS EQUIPAGGIAMENTO",
    "inventory.stats_label": "Statistiche: ",
    "inventory.other_label": "Altro: ",
    "inventory.options_line1": "[E]quipaggia  [D]rop  [M]gestisci slot  [U] rimuovi tutto",
    "inventory.options_line2": "[Q]esci dall'inventario",
    "inventory.invalid_choice": "Scelta non valida. Prova E, D, M, U o Q.",
    "inventory.invalid_item": "Numero oggetto non valido.",
    "inventory.manage_header": "GESTISCI OGGETTO",
    "inventory.item_value": "Valore: {0} oro",
    "inventory.item_type": "Tipo: {0}",
    "inventory.properties_unknown": "Proprietà sconosciute - l'oggetto non è stato identificato!",
    "inventory.option_equip": "[E]quipaggia",
    "inventory.option_drop": "[D]rop",
    "inventory.option_back": "[B]Indietro",
    "inventory.unidentified_warning": "Questo oggetto non è identificato! Le sue vere proprietà sono sconosciute.",
    "inventory.equip_anyway": "Equipaggiare comunque? (S/N): ",
    "inventory.cursed_warning": "Questo oggetto non sembra a posto... potrebbe essere maledetto!",
    "inventory.cursed_stuck": "Il {0} è MALEDETTO! Non puoi rimuoverlo!",
    "inventory.finger_select": "Quale dito? [S]inistro o [D]estro: ",
    "inventory.weapon_slot_select": "Equipaggiare nella mano [P]rincipale o [S]econdaria? ",
    "inventory.comparison_header": "CONFRONTO",
    "inventory.currently_equipped": "Attualmente equipaggiato: ",
    "inventory.equip_confirm": "Equipaggiare questo oggetto? (S/N): ",
    "inventory.equipped_result": "Equipaggiato {0}!",
    "inventory.cannot_equip": "Impossibile equipaggiare: {0}",
    "inventory.slot_currently": "Attualmente equipaggiato in {0}: {1}",
    "inventory.slot_options": "[R]imuovi  [I]ndietro",
    "inventory.slot_unequipped": "Rimosso {0}.",
    "inventory.slot_select": "Seleziona slot da gestire (numero, o Q per uscire): ",
    "inventory.unequip_all_progress": "Rimozione di tutti gli oggetti...",
    "inventory.unequip_all_result": "Rimossi {0} oggetti.",
    "inventory.unequip_all_none": "Nessun oggetto da rimuovere.",
    "inventory.requires_label": "Richiede: ",
    "inventory.req_level": "Livello",
    "inventory.req_str": "{0} FOR",
    "inventory.req_alignment": "allineamento {0}",
    "inventory.req_unique": "Oggetto unico",
    "inventory.value_line": "Valore: {0} oro  |  Tipo: {1}",
    "inventory.drop_backpack_empty": "Il tuo zaino è vuoto.",
    "inventory.drop_enter_number": "Inserisci il numero dell'oggetto da gettare (0 per annullare): ",
    "inventory.drop_cursed": "Il {0} è maledetto! Non puoi gettarlo!",
    "inventory.drop_dropped": "Gettato {0}.",
    "sysop_location.error_bbs_only": "ERRORE: La Console SysOp è disponibile solo in modalità porta BBS.",
    "sysop_location.access_denied": "ACCESSO NEGATO: Privilegi SysOp richiesti.",
    "sysop_location.logged_in_as": "  Connesso come: {0} (Livello Sicurezza: {1})",
    "sysop_location.bbs_name": "  BBS: {0}",
    "sysop_location.version_available": "  Versione {0} disponibile (attuale: {1})",
    "sysop_location.press_9_update": "  Premi 9 per scaricare e installare l'aggiornamento",
    "sysop_location.update_available_banner": "AGGIORNAMENTO DISPONIBILE: v{0} (attuale: {1})",
    "sysop_location.press_9_bracket": "Premi [9] per scaricare e installare l'aggiornamento",
    "sysop_location.update_label": "AGGIORNAMENTO DISPONIBILE:",
    "sysop_location.current_label": "attuale",
    "sysop_location.section_game_mgmt": "GESTIONE GIOCO",
    "sysop_location.section_settings": "IMPOSTAZIONI GIOCO",
    "sysop_location.section_monitoring": "MONITORAGGIO",
    "sysop_location.section_maintenance": "MANUTENZIONE SISTEMA",
    "sysop_location.menu_view_players": "Visualizza Tutti i Giocatori",
    "sysop_location.menu_delete_player": "Elimina Giocatore",
    "sysop_location.menu_reset_game": "Reimposta Gioco (Cancella Tutti i Dati)",
    "sysop_location.menu_config": "Visualizza/Modifica Configurazione",
    "sysop_location.menu_motd": "Imposta Messaggio del Giorno (MOTD)",
    "sysop_location.menu_stats": "Visualizza Statistiche di Gioco",
    "sysop_location.menu_debug_log": "Visualizza Log di Debug",
    "sysop_location.menu_npcs": "Visualizza PNG Attivi",
    "sysop_location.menu_updates": "Controlla Aggiornamenti",
    "sysop_location.update_available_tag": "AGGIORNAMENTO DISPONIBILE",
    "sysop_location.menu_return": "Torna alla Via Principale",
    "sysop_location.all_players": "TUTTI I GIOCATORI",
    "sysop_location.no_save_dir": "Nessuna directory di salvataggio trovata.",
    "sysop_location.no_saves": "Nessun salvataggio trovato.",
    "sysop_location.found_saves": "Trovati {0} file di salvataggio:",
    "sysop_location.last_played": "Ultima partita",
    "sysop_location.size": "Dimensione",
    "sysop_location.error_reading_saves": "Errore nella lettura dei salvataggi: {0}",
    "sysop_location.delete_player": "ELIMINA GIOCATORE",
    "sysop_location.delete_warning": "ATTENZIONE: Questo eliminerà permanentemente il salvataggio di un giocatore!",
    "sysop_location.enter_name_delete": "Inserisci il nome del giocatore da eliminare (o lascia vuoto per annullare): ",
    "sysop_location.error_delete_active": "ERRORE: Impossibile eliminare il giocatore attivo.",
    "sysop_location.must_logout_first": "Il giocatore deve prima disconnettersi.",
    "sysop_location.player_not_found": "Giocatore '{0}' non trovato.",
    "sysop_location.confirm_delete": "Sei SICURO di voler eliminare '{0}'? Scrivi YES per confermare: ",
    "sysop_location.deleted_file": "  Eliminato: {0}",
    "sysop_location.player_deleted": "Giocatore '{0}' eliminato ({1} file rimossi).",
    "sysop_location.error_deleting": "Errore nell'eliminazione del giocatore: {0}",
    "sysop_location.deletion_cancelled": "Eliminazione annullata.",
    "sysop_location.reset_will_delete": "Questo CANCELLERÀ PERMANENTEMENTE:",
    "sysop_location.reset_all_saves": "  - TUTTI i salvataggi dei giocatori",
    "sysop_location.reset_all_state": "  - TUTTI i dati dello stato di gioco",
    "sysop_location.reset_fresh": "  - Il gioco ripartirà come appena installato",
    "sysop_location.cannot_be_undone": "Questa azione NON PUÒ essere annullata!",
    "sysop_location.type_reset_game": "Scrivi 'RESET GAME' per confermare: ",
    "sysop_location.final_confirm": "Conferma finale - Scrivi 'YES' per procedere: ",
    "sysop_location.reset_cancelled": "Reimpostazione del gioco annullata.",
    "sysop_location.resetting_game": "Reimpostazione del gioco in corso...",
    "sysop_location.preserved_file": "  Preservato: {0} (impostazioni SysOp)",
    "sysop_location.resetting_systems": "Reimpostazione dei sistemi di gioco...",
    "sysop_location.reset_system": "  Reimpostato: sistema {0}",
    "sysop_location.reset_complete": "Il gioco è stato completamente reimpostato!",
    "sysop_location.reset_new_chars": "Tutti i giocatori dovranno creare nuovi personaggi.",
    "sysop_location.reset_config_preserved": "La configurazione SysOp è stata preservata.",
    "sysop_location.error_reset": "Errore durante la reimpostazione: {0}",
    "sysop_location.difficulty_settings": "IMPOSTAZIONI DIFFICOLTÀ",
    "sysop_location.current_settings": "Impostazioni Attuali:",
    "sysop_location.xp_mult": "Moltiplicatore PE",
    "sysop_location.gold_mult": "Moltiplicatore Oro",
    "sysop_location.monster_hp_mult": "Moltiplicatore PV Mostri",
    "sysop_location.monster_dmg_mult": "Moltiplicatore Danni Mostri",
    "sysop_location.values_higher": "  (Valori > 1.0 rendono il gioco più facile/remunerativo)",
    "sysop_location.values_lower": "  (Valori < 1.0 rendono il gioco più difficile/meno remunerativo)",
    "sysop_location.feature_toggles": "Opzioni Funzionalità:",
    "sysop_location.online_multiplayer": "Multigiocatore Online",
    "sysop_location.disabled": "DISABILITATO",
    "sysop_location.enabled": "ABILITATO",
    "sysop_location.edit_options": "Opzioni di Modifica:",
    "sysop_location.set_xp_mult": "Imposta Moltiplicatore PE",
    "sysop_location.set_gold_mult": "Imposta Moltiplicatore Oro",
    "sysop_location.set_monster_hp_mult": "Imposta Moltiplicatore PV Mostri",
    "sysop_location.set_monster_dmg_mult": "Imposta Moltiplicatore Danni Mostri",
    "sysop_location.toggle_online": "Attiva/Disattiva Multigiocatore Online",
    "sysop_location.return_sysop": "Torna al Menu SysOp",
    "sysop_location.new_xp_mult": "Nuovo moltiplicatore PE (0.1-10.0): ",
    "sysop_location.new_gold_mult": "Nuovo moltiplicatore oro (0.1-10.0): ",
    "sysop_location.new_monster_hp_mult": "Nuovo moltiplicatore PV mostri (0.1-10.0): ",
    "sysop_location.new_monster_dmg_mult": "Nuovo moltiplicatore danni mostri (0.1-10.0): ",
    "sysop_location.mult_set": "{0} impostato a {1}x (salvato)",
    "sysop_location.invalid_mult": "Input non valido '{0}'. Inserisci un numero tra 0.1 e 10.0.",
    "sysop_location.online_disabled": "Multigiocatore Online DISABILITATO — i giocatori non possono connettersi al server online.",
    "sysop_location.online_enabled": "Multigiocatore Online ABILITATO — i giocatori possono connettersi al server online.",
    "sysop_location.motd_title": "MESSAGGIO DEL GIORNO",
    "sysop_location.current_motd": "MOTD Attuale:",
    "sysop_location.no_motd": "Nessun MOTD impostato",
    "sysop_location.enter_new_motd": "Inserisci il nuovo MOTD (o lascia vuoto per cancellare):",
    "sysop_location.motd_cleared": "Il MOTD è stato cancellato (salvato).",
    "sysop_location.motd_updated": "Il MOTD è stato aggiornato (salvato).",
    "sysop_location.game_statistics": "STATISTICHE DI GIOCO",
    "sysop_location.total_players": "Giocatori Totali",
    "sysop_location.npc_statistics": "Statistiche PNG:",
    "sysop_location.active_npcs": "PNG Attivi",
    "sysop_location.dead_npcs": "PNG Morti",
    "sysop_location.married_npcs": "PNG Sposati",
    "sysop_location.story_statistics": "Statistiche della Trama:",
    "sysop_location.collected_seals": "Sigilli Raccolti",
    "sysop_location.current_chapter": "Capitolo Attuale",
    "sysop_location.awakening_level": "Livello di Risveglio",
    "sysop_location.wave_fragments": "Frammenti d'Onda",
    "sysop_location.error_stats": "Errore nella raccolta delle statistiche: {0}",
    "sysop_location.no_debug_log": "Nessun log di debug trovato.",
    "sysop_location.debug_log_empty": "Il log di debug è vuoto.",
    "sysop_location.debug_log_page": "LOG DI DEBUG (Pagina {0}/{1}, {2} righe totali)",
    "sysop_location.log_nav": "[N] Voci più recenti, [O] Voci più vecchie, [Q] Esci",
    "sysop_location.error_log": "Errore nella lettura del log: {0}",
    "sysop_location.no_active_npcs": "Nessun PNG attivo trovato.",
    "sysop_location.active_npcs_page": "PNG ATTIVI (Pagina {0}/{1})",
    "sysop_location.dead_tag": "MORTO",
    "sysop_location.married_tag": "SPOSATO",
    "sysop_location.npc_nav": "[N] Pagina successiva, [P] Pagina precedente, [Q] Esci",
    "sysop_location.check_updates": "CONTROLLA AGGIORNAMENTI",
    "sysop_location.current_version": "Versione Attuale: {0}",
    "sysop_location.steam_build": "Questa è una build Steam. Gli aggiornamenti sono gestiti automaticamente da Steam.",
    "sysop_location.check_steam": "Controlla Steam per gli aggiornamenti disponibili.",
    "sysop_location.checking_github": "Controllo aggiornamenti su GitHub...",
    "sysop_location.check_failed": "Impossibile controllare gli aggiornamenti.",
    "sysop_location.error_label": "Errore",
    "sysop_location.tls_hint1": "  Potrebbe essere un problema TLS/SSL su vecchi sistemi Windows a 32 bit,",
    "sysop_location.tls_hint2": "  un blocco del firewall o un'interruzione temporanea di GitHub.",
    "sysop_location.manual_download": "  Scarica manualmente l'ultima versione da:",
    "sysop_location.latest_version": "Stai utilizzando l'ultima versione!",
    "sysop_location.latest_label": "Ultima",
    "sysop_location.current_version_label": "Versione attuale",
    "sysop_location.latest_version_label": "Ultima versione",
    "sysop_location.release_notes": "Note di Rilascio:",
    "sysop_location.auto_update_available": "L'aggiornamento automatico è disponibile per la tua piattaforma!",
    "sysop_location.options": "Opzioni:",
    "sysop_location.download_auto": "Scarica e installa automaticamente",
    "sysop_location.open_download": "Apri la pagina di download nel browser",
    "sysop_location.skip_for_now": "Salta per ora",
    "sysop_location.opening_browser": "Apertura della pagina di download nel browser...",
    "sysop_location.update_skipped": "Aggiornamento saltato.",
    "sysop_location.download_label": "Download",
    "sysop_location.open_browser_yn": "Aprire la pagina di download nel browser? (S/N): ",
    "sysop_location.error_updates": "Errore nel controllo degli aggiornamenti: {0}",
    "sysop_location.downloading_update": "Download dell'aggiornamento in corso...",
    "sysop_location.downloading_pct": "Download",
    "sysop_location.update_close": "Il gioco si chiuderà e si aggiornerà automaticamente.",
    "sysop_location.update_disconnect": "Tutti i giocatori saranno disconnessi brevemente durante l'aggiornamento.",
    "sysop_location.press_enter_update": "Premi Invio per chiudere il gioco e applicare l'aggiornamento...",
    "sysop_location.download_failed": "Download fallito: {0}",
    "sysop_location.open_download_yn": "Vuoi aprire la pagina di download? (S/N): ",
    "_comment_encounters": "=== INCONTRI RARI ===",
    "_comment_encounter_tavern": "--- Taverna Nascosta ---",
    "_comment_encounter_minstrel": "--- Menestrello Errante ---",
    "_comment_encounter_fairy": "--- Cerchio delle Fate ---",
    "_comment_encounter_damsel": "--- Damigella in Pericolo ---",
    "_comment_encounter_ghost": "--- Fantasma dell'Usurper ---",
    "_comment_encounter_demons": "--- Demoni Giocatori d'Azzardo ---",
    "_comment_encounter_hermit": "--- Vecchio Eremita ---",
    "_comment_encounter_merchant": "--- Mercante Misterioso ---",
    "_comment_encounter_timewarp": "--- Distorsione Temporale ---",
    "_comment_encounter_library": "--- Biblioteca Antica ---",
    "_comment_encounter_well": "--- Pozzo dei Desideri ---",
    "_comment_encounter_arena": "--- Portale dell'Arena ---",
    "_comment_encounter_bone_oracle": "--- Oracolo delle Ossa ---",
    "_comment_encounter_spirits": "--- Spiriti Inquieti ---",
    "_comment_encounter_crypt": "--- Custode della Cripta ---",
    "_comment_encounter_tomb": "--- Tomba Antica ---",
    "_comment_encounter_ratking": "--- Re dei Ratti ---",
    "_comment_encounter_child": "--- Bambino Smarrito ---",
    "_comment_encounter_alchemy": "--- Laboratorio dell'Alchimista ---",
    "_comment_encounter_hoard": "--- Tesoro Nascosto ---",
    "_comment_encounter_crystal": "--- Grotta di Cristallo ---",
    "_comment_encounter_dragon_hoard": "--- Tesoro del Drago ---",
    "_comment_encounter_dwarven": "--- Avamposto Nanico ---",
    "_comment_encounter_lake": "--- Lago Sotterraneo ---",
    "_comment_encounter_golem": "--- Golem Antico ---",
    "_comment_encounter_capsule": "--- Capsula del Tempo ---",
    "_comment_encounter_fountain": "--- Fontana Magica ---",
    "_comment_encounter_civilization": "--- Civiltà Perduta ---",
    "_comment_encounter_demon_bargain": "--- Patto Demoniaco ---",
    "_comment_encounter_tortured": "--- Anime Tormentate ---",
    "_comment_encounter_forge": "--- Forgia Infernale ---",
    "_comment_encounter_succubus": "--- Succube ---",
    "_comment_encounter_frozen": "--- Avventuriero Congelato ---",
    "_comment_encounter_ice_queen": "--- Regina dei Ghiacci ---",
    "_comment_encounter_yeti": "--- Tana dello Yeti ---",
    "_comment_encounter_aurora": "--- Visione dell'Aurora ---",
    "_comment_encounter_fire_elemental": "--- Elementale del Fuoco ---",
    "_comment_encounter_lava_boat": "--- Barca sulla Lava ---",
    "_comment_encounter_phoenix": "--- Nido della Fenice ---",
    "_comment_encounter_mirror": "--- Specchio d'Ossidiana ---",
    "_comment_encounter_void": "--- Sussurro del Vuoto ---",
    "_comment_encounter_reality": "--- Strappo nella Realtà ---",
    "_comment_encounter_cosmic": "--- Entità Cosmica ---",
    "_comment_encounter_madness": "--- Pozzo della Follia ---",
    "charcreate.prestige_req_savior": "Finale del Salvatore",
    "charcreate.prestige_req_defiant": "Finale del Ribelle",
    "charcreate.prestige_req_usurper": "Finale dell'Usurper",
    "charcreate.abort": "Annulla",
    "charcreate.mana_per_level_label": "+{0}/livello",
    "arena.lb_wl_format": "{0}V/{1}S",
    "arena.notify_attack_won": "[Arena] {0} ti ha attaccato nell'Arena e ha vinto! Ti ha rubato {1} del tuo oro.",
    "arena.notify_attack_lost": "[Arena] {0} ti ha attaccato nell'Arena ma la tua ombra l'ha sconfitto! Hai guadagnato {1} oro.",
    "anchor_road.bbs_bounty": "Taglia",
    "anchor_road.bbs_gang_war": "GuerraBande",
    "anchor_road.bbs_gauntlet": "Sfida",
    "anchor_road.bbs_claim_town": "ConquistaCittà",
    "anchor_road.bbs_flee_town": "FuggiCittà",
    "anchor_road.bbs_prison": "Prigione",
    "anchor_road.bbs_return": "Torna",
    "anchor_road.gold_amount": "{0} oro",
    "charcreate.choose_name": "Scegli il tuo nome: ",
    "charcreate.name_taken": "Quel nome è già in uso!",
    "charcreate.name_invalid": "Nome non valido. Usa solo lettere, da 2 a 15 caratteri.",
    "charcreate.choose_race": "Scegli la tua razza:",
    "charcreate.choose_class": "Scegli la tua classe:",
    "charcreate.confirm_creation": "Creare questo personaggio? (S/N): ",
    "charcreate.character_created": "Personaggio creato! Benvenuto nel mondo, {0}!",
    "charcreate.reroll_stats": "Ritirare le statistiche? (S/N): ",
    "arena.challenge_prompt": "Chi sfidare? (#): ",
    "arena.bet_prompt": "Fare una scommessa? (importo o 0): ",
    "arena.bet_won": "Hai vinto la scommessa! +{0} oro!",
    "arena.bet_lost": "Hai perso la scommessa! -{0} oro!",
    "training.skill_header": "=== Addestramento Abilità ===",
    "training.points_available": "Punti Addestramento Disponibili: {0}",
    "training.skill_entry": "  {0}. {1}: {2}/{3}",
    "training.choose_skill": "Scegli l'abilità da addestrare (#, o 0 per uscire): ",
    "training.skill_maxed": "{0} è già al massimo!",
    "training.no_points": "Nessun punto addestramento disponibile!",
    "training.cost_label": "Costo: {0} punto/i",
    "location.traveling": "In viaggio verso {0}...",
    "location.cannot_travel": "Non puoi viaggiare lì in questo momento.",
    "location.arrive": "Arrivi a {0}.",
    "location.you_have_died": "SEI MORTO!",
    "location.death_vision_fades": "La tua visione sfuma nel nero mentre la morte ti reclama...",
    "location.resurrections_available": "Hai {0} resurrezione/i disponibile/i!",
    "location.use_resurrection_prompt": "Usare una resurrezione per evitare le penalità? (S/N): ",
    "location.divine_light": "Una luce divina ti avvolge!",
    "location.resurrected_no_penalty": "Sei stato completamente resuscitato senza penalità!",
    "location.death_penalties": "Penalità di Morte Applicate:",
    "location.lost_experience": "  - Persi {0} punti esperienza",
    "location.lost_gold": "  - Persi {0} monete d'oro (cadute alla morte)",
    "location.monster_defeats": "  - Sconfitte mostri: {0}",
    "location.wake_at_inn": "Ti risvegli alla Locanda, curato dall'oste.",
    "location.wounds_healed": "Le tue ferite sono parzialmente guarite. (PV: {0}/{1})",
    "location.innkeeper_quote": "\"Sei fortunato ad essere vivo, amico. Riposa e riprova.\"",
    "location.adventure_continues": "La tua avventura continua...",
    "location.returning_main_menu": "Ritorno al menu principale...",
    "location.navigating_to": "Navigazione verso {0}...",
    "location.unknown_destination": "Destinazione sconosciuta: {0}",
    "location.cannot_go": "Non puoi andare a {0} da qui!",
    "location.unknown_location": "Luogo sconosciuto '{0}'. Ritorno alla Via Principale.",
    "alignment.status_header": "STATO ALLINEAMENTO",
    "alignment.chivalry_label": "Cavalleria: ",
    "alignment.darkness_label": "Oscurità: ",
    "alignment.holy_label": "Sacro ",
    "alignment.evil_label": " Malvagio",
    "alignment.abilities_header": "Abilità di Allineamento:",
    "haggle.header": "CONTRATTAZIONE",
    "haggle.troll_already_discount": "Ehi! Ti ho già fatto uno sconto!",
    "haggle.troll_get_out": "Non aspettarti altro! Fuori di qui!",
    "haggle.give_offer": "Va bene, fammi un'offerta: ",
    "haggle.not_serious": "Non è un'offerta seria!",
    "haggle.got_deal": "D'accordo {0}! Affare fatto!",
    "haggle.accept_price": "Accetti questo prezzo? (S/N): ",
    "haggle.weapon_angry": "Mi stai facendo arrabbiare molto, {0}!",
    "haggle.accept_or_leave": "Accetta la mia offerta o vattene!",
    "haggle.weapon_face_red": "Il volto di {0} diventa di un rosso malsano...",
    "haggle.armor_damn": "Maledetto te, {0}!",
    "haggle.armor_upset": "{0} sembra piuttosto seccato dal tuo comportamento.",
    "haggle.insist_or_leave": "Cosa farai? Insistere ancora una volta o andartene?",
    "haggle.insist_prompt": "Insistere? (S/N): ",
    "haggle.kicked_out": "Sei stato cacciato fuori!",
    "haggle.kicked_news": "[NOTIZIA] {0} è stato cacciato dal {1}!",
    "haggle.end_discussion": "Fine della discussione.",
    "haggle.weapon_fail_1": "Haha! Pensi di essere spiritoso, eh!?",
    "haggle.weapon_fail_2": "Vattene prima che mi arrabbi davvero!",
    "haggle.armor_fail_1": "Smettila di scherzare e vattene, così posso",
    "haggle.armor_fail_2": "fare affari seri!",
    "feature.interact_with": "{0} il/la {1}...",
    "feature.catches_attention": "Qualcosa attira la tua attenzione:",
    "feature.knowledge_xp": "Questa conoscenza ti illumina. (+{0} PE)",
    "feature.drawn_to_light": "Ti senti attratto verso la luce... (+{0} Cavalleria)",
    "feature.drawn_to_darkness": "Ti senti attratto verso l'oscurità... (+{0} Oscurità)",
    "feature.sense_presence": "Senti la presenza di {0} in queste profondità...",
    "feature.stat_check": "[Prova di {0} - CD {1}]",
    "feature.roll_result": "Hai tirato {0} + {1} (bonus {2}) = {3}",
    "feature.success": "SUCCESSO!",
    "feature.failed": "FALLITO!",
    "feature.hidden_knowledge": "La tua perizia rivela conoscenze nascoste!",
    "feature.stat_boost": "+{0} {1} per il resto di questo piano!",
    "feature.gold_reward": "La tua abilità viene ricompensata generosamente! +{0} oro!",
    "feature.find_potions": "Trovi {0} pozione/i curativa/e nascosta/e all'interno!",
    "feature.challenge_xp": "La sfida stessa ti insegna qualcosa. +{0} PE!",
    "feature.failure_damage": "Il tuo fallimento ha un prezzo. -{0} PV",
    "feature.nothing_happens": "Non succede nulla. Forse un altro approccio funzionerebbe.",
    "feature.learn_mistake": "Impari dal tuo errore. +{0} PE",
    "feature.what_do_you_do": "Cosa fai?",
    "feature.walk_away": "Allontanati",
    "feature.not_your_concern": "Decidi che non è affar tuo.",
    "feature.wisdom_walk_away": "A volte la saggezza è sapere quando allontanarsi.",
    "feature.soul_toward_light": "La tua anima si sposta verso la luce... (+{0} Cavalleria)",
    "feature.soul_toward_darkness": "La tua anima si sposta verso l'oscurità... (+{0} Oscurità)",
    "feature.class_training_reveals": "Il tuo addestramento come {0} {1} rivela qualcosa che altri non noterebbero:",
    "feature.spot_weaknesses": "Individui dei punti deboli nelle difese del sotterraneo.",
    "feature.next_battle_easier": "La prossima battaglia sarà più facile.",
    "feature.attack_power_bonus": "+{0} Potenza d'Attacco per il prossimo combattimento!",
    "feature.magical_residue": "Residui magici si aggrappano a questo luogo.",
    "feature.absorb_magic": "Assorbi ciò che puoi.",
    "feature.mana_restored": "+{0} Mana ripristinato!",
    "feature.divine_presence": "Una presenza divina indugia qui. Offri una preghiera.",
    "feature.divine_heal": "+{0} PV dalla benedizione divina!",
    "feature.hidden_passages": "Noti passaggi nascosti che altri non vedrebbero.",
    "feature.hidden_supplies": "Qualcuno ha lasciato provviste per chi sa dove cercare.",
    "feature.poison_vials": "+{0} fiala/e di veleno! (Totale: {2})",
    "feature.coat_blade_hint": "Usa [B] Avvelena Lama durante il combattimento per applicare un veleno.",
    "feature.wilderness_resources": "Il tuo addestramento nella natura ti aiuta a trovare risorse.",
    "feature.sellable_materials": "+{0} oro in materiali vendibili!",
    "feature.herbal_remedy": "+1 rimedio erboristico!",
    "feature.old_song": "Ricordi una vecchia canzone su questo luogo...",
    "feature.melody_secrets": "La melodia rivela antichi segreti.",
    "feature.bardic_xp": "+{0} PE dalla conoscenza bardica!",
    "feature.find_useful": "Trovi qualcosa di utile.",
    "feature.plus_gold": "+{0} oro!",
    "feature.looks_dangerous": "Sembra pericoloso, ma potenzialmente remunerativo.",
    "feature.potential_reward": "Ricompensa potenziale: {0} oro",
    "feature.potential_risk": "Rischio potenziale: {0} danni",
    "feature.success_chance": "Probabilità di successo: {0}% (basata su DES/INT)",
    "feature.take_risk": "Corri il rischio? (S/N)",
    "feature.extract_treasure": "Estrai con cura il tesoro!",
    "feature.trap_springs": "Scatta una trappola!",
    "feature.minus_hp": "-{0} PV!",
    "feature.grabbed_gold": "Ma sei riuscito ad afferrare {0} oro!",
    "feature.wisdom_leave": "La saggezza è sapere quando allontanarsi.",
    "feature.leave_undisturbed": "Lasci il tesoro indisturbato.",
    "feature.feels_familiar": "Qualcosa in tutto questo sembra... familiare.",
    "feature.memory_surfaces": "Un frammento di memoria affiora:",
    "feature.memory_fades": "Il ricordo svanisce, ma qualcosa resta...",
    "feature.everything_stops": "Per un istante, tutto si ferma.",
    "feature.feel_different": "Ti senti... diverso. Più sveglio.",
    "feature.find_gold": "Trovi {0} oro!",
    "feature.learn_something": "Impari qualcosa. +{0} PE",
    "feature.nothing_interest": "Niente di interessante qui.",
    "feature.find_healing_potion": "Trovi una pozione curativa!",
    "feature.trap_damage": "Una trappola! Subisci {0} danni!",
    "feature.plus_xp": "+{0} PE",
    "common.lvl": "Liv",
    "dormitory.creep_toward_npc": "Ti avvicini furtivamente alla branda di {0}, arma in pugno...",
    "dormitory.fought_off_npc": "{0} ti ha respinto anche mezzo addormentato!",
    "dormitory.creep_toward_player": "Ti avvicini furtivamente alla branda di {0}, arma in pugno...",
    "dormitory.also_take_item": "Rubi anche il suo {0}!",
    "dormitory.fought_off_player": "{0} ti ha respinto anche nel sonno!",
    "inventory.style_sword_board": "Spada e Scudo (bilanciato, 20% probabilità blocco)",
    "inventory.style_one_handed": "Una Mano",
    "inventory.equipped_items": "=== OGGETTI EQUIPAGGIATI ===",
    "inventory.slot_left_ring": "Anello Sinistro",
    "inventory.slot_right_ring": "Anello Destro",
    "inventory.equipment_bonuses": "=== BONUS EQUIPAGGIAMENTO ===",
    "inventory.stats": "Statistiche: ",
    "inventory.other": "Altro: ",
    "inventory.manage_item": "GESTISCI OGGETTO",
    "inventory.value": "Valore",
    "inventory.type": "Tipo",
    "inventory.equip_item": "  [E] Equipaggia Oggetto",
    "inventory.equip_identify_first": "  [E] Equipaggia Oggetto (identifica prima)",
    "inventory.drop_item": "  [D] Getta Oggetto",
    "inventory.back": "  [Q] Indietro",
    "inventory.cant_equip_unidentified": "Non puoi equipaggiare un oggetto non identificato.",
    "inventory.visit_magic_shop": "Portalo al Negozio Magico per farlo identificare.",
    "inventory.cursed_cant_drop": "Il {0} è MALEDETTO! Non puoi gettarlo.",
    "inventory.visit_healer_curse": "Visita il Guaritore per far rimuovere la maledizione.",
    "inventory.dropped_item": "Getti il {0}.",
    "inventory.cant_equip": "Questo oggetto non può essere equipaggiato.",
    "inventory.which_finger": "A quale dito equipaggiare?",
    "inventory.left_finger": "  (S) Dito sinistro",
    "inventory.right_finger": "  (D) Dito destro",
    "inventory.comparison": "CONFRONTO",
    "inventory.equipped": "Equipaggiato {0}.",
    "inventory.one_handed_where": "Questa è un'arma a una mano. Dove vuoi equipaggiarla?",
    "inventory.enter_drop_number": "Inserisci il numero dell'oggetto da gettare (B1, B2, ecc.): ",
    "inventory.nothing": "Niente",
    "inventory.options": "Opzioni:",
    "inventory.unequip_item": "  [U] Rimuovi questo oggetto",
    "inventory.return_inventory": "  [Q] Torna all'inventario",
    "inventory.cursed_cant_unequip": "Il {0} è MALEDETTO! Non puoi rimuoverlo.",
    "inventory.unequipped": "Rimosso {0}.",
    "inventory.returned_backpack": "(Oggetto restituito allo zaino)",
    "inventory.req_good": "Allineamento buono",
    "inventory.req_evil": "Allineamento malvagio",
    "inventory.requires": "Richiede",
    "inventory.unequipping_all": "Rimozione di tutti gli oggetti...",
    "inventory.unequipped_count": "Rimossi {0} oggetto/i nello zaino.",
    "inventory.no_items_unequip": "Nessun oggetto da rimuovere.",
    "magic_shop.enchant_examine": "{0} esamina il tuo equipaggiamento con occhio esperto...",
    "magic_shop.enchant_offer": "\"Posso tessere incantamenti nel tuo equipaggiamento — per un prezzo.\"",
    "magic_shop.no_equipment_enchant": "Non hai equipaggiamento da incantare.",
    "magic_shop.come_back_armed": "\"Torna quando avrai qualcosa che valga la pena incantare.\"",
    "magic_shop.select_item_enchant": "Seleziona oggetto da incantare (0 per annullare): ",
    "magic_shop.cursed_no_enchant": "\"Non posso incantare un oggetto maledetto!\"",
    "magic_shop.remove_curse_first": "\"Fai rimuovere prima la maledizione.\"",
    "magic_shop.beyond_limits": "\"Anche la mia magia ha i suoi limiti.\"",
    "magic_shop.select_enchantment": "Seleziona incantamento: ",
    "magic_shop.need_gold_enchant": "\"Ti manca l'oro per questo incantamento.\"",
    "magic_shop.cures_smallpox": "Cura il vaiolo",
    "magic_shop.cures_measles": "Cura il morbillo",
}
