translations = {
    "pantheon.menu_favors": "Favori",
    "pantheon.menu_favors_desc": "Configura benedizioni per i tuoi seguaci",
    "pantheon.menu_immortals": "Immortali",
    "pantheon.menu_immortals_desc": "Visualizza gli altri dèi e le classifiche",
    "pantheon.menu_news": "Notizie",
    "pantheon.menu_news_desc": "Leggi le notizie mortali e divine",
    "pantheon.menu_comment": "Commento",
    "pantheon.menu_comment_desc": "Invia un proclama ai tuoi credenti",
    "pantheon.menu_visit_manwe": "Visita Manwe",
    "pantheon.menu_visit_manwe_desc": "Il trono del Creatore Supremo",
    "pantheon.menu_renounce": "Rinuncia",
    "pantheon.menu_renounce_desc": "Rinuncia all'immortalità e ricomincia",
    "pantheon.menu_quit": "Esci",
    "pantheon.menu_quit_desc": "Abbandona il gioco",
    "pantheon.menu_recruit": "Recluta Credente",
    "pantheon.menu_recruit_desc": "Converti un pagano o ruba da un rivale",
    "pantheon.menu_bless": "Benedici Seguace",
    "pantheon.menu_bless_desc": "Concedi un bonus in combattimento a un credente",
    "pantheon.menu_smite": "Colpisci Mortale",
    "pantheon.menu_smite_desc": "Abbatti un non credente",
    "pantheon.menu_poison": "Avvelena Relazioni",
    "pantheon.menu_poison_desc": "Peggiora i rapporti tra due mortali",
    "pantheon.menu_free": "Libera Prigioniero",
    "pantheon.menu_free_desc": "Rilascia un personaggio imprigionato",
    "pantheon.menu_proclamation": "Proclama",
    "pantheon.menu_proclamation_desc": "Invia un messaggio divino a tutti",
    "pantheon.menu_back": "Indietro",
    "pantheon.menu_back_desc": "Ritorna al Reame Divino",
    "pantheon.welcome": "  Benvenuto, ",
    "pantheon.the_title": " il {0}",
    "pantheon.status_line": "  Allineamento: {0}  |  Credenti: {1}  |  Gesta: {2}/{3}",
    "pantheon.invalid_choice": "  Il cosmo non comprende.",
    "pantheon.mortal_name_label": "  Nome Mortale:     ",
    "pantheon.alignment_label": "  Allineamento:     ",
    "pantheon.god_rank_label": "  Rango Divino:     ",
    "pantheon.god_rank_value": "Livello {0} — {1}",
    "pantheon.experience_label": "  Esperienza:       ",
    "pantheon.max_level": " (LIVELLO MASSIMO)",
    "pantheon.believers_label": "  Credenti:         ",
    "pantheon.deeds_today_label": "  Gesta Oggi:       ",
    "pantheon.ascension_date_label": "  Data Ascensione:  ",
    "pantheon.daily_exp_label": "  Esp Giornaliera:  ",
    "pantheon.daily_exp_value": "+{0} dai credenti",
    "pantheon.configured_boons": "  Benedizioni Configurate:",
    "pantheon.no_boons": "  Nessuna benedizione configurata. Usa [F] Favori per impostare benedizioni per i tuoi seguaci.",
    "pantheon.press_enter_return": "  Premi Invio per tornare...",
    "pantheon.no_believers": "  Non hai ancora credenti. Usa le Gesta Divine per reclutare seguaci.",
    "pantheon.total_believers": "  Credenti Totali: {0}",
    "pantheon.believer_player_tag": "[GIOCATORE] ",
    "pantheon.believer_online_tag": " [IN LINEA]",
    "pantheon.and_more": "  ... e altri {0}.",
    "pantheon.budget_label": "  Budget: ",
    "pantheon.budget_value": "{0}/{1} pti",
    "pantheon.budget_breakdown": "  (Base: {0} dal Livello {1}  +  Focus: {2} da {3} credenti)",
    "pantheon.active_boons_header": "  BENEDIZIONI ATTIVE:",
    "pantheon.available_boons_header": "  BENEDIZIONI DISPONIBILI:",
    "pantheon.boon_locked": " (bloccata)",
    "pantheon.boon_legend": "  * = budget insufficiente   bloccata = allineamento errato",
    "pantheon.boon_menu_help": "  [#] Aggiungi/potenzia benedizione   [R#] Rimuovi benedizione   [0] Fine",
    "pantheon.boon_removed": "  Benedizione rimossa.",
    "pantheon.boon_configured": "  {0} configurata!",
    "pantheon.favors_updated": "  Favori divini aggiornati. I tuoi seguaci sentiranno il cambiamento.",
    "pantheon.no_deeds_left": "  Il tuo potere divino è esaurito per oggi. Riposa fino al domani.",
    "pantheon.deeds_remaining": "  Gesta rimanenti: {0}",
    "pantheon.prompt_choose_deed": "\n  Scegli una gesta: ",
    "pantheon.no_mortals_to_recruit": "  Non ci sono mortali disponibili da reclutare.",
    "pantheon.recruit_success": "  {0} cade in ginocchio in adorazione!",
    "pantheon.exp_gain": "  +{0} esperienza divina.",
    "pantheon.recruit_failure": "  {0} resiste al tuo richiamo divino. Forse la prossima volta.",
    "pantheon.steal_success": "  {0} abbandona {1} e si volge a te!",
    "pantheon.steal_failure": "  La fede di {0} è salda. Non puoi convertirlo.",
    "pantheon.press_enter_continue": "  Premi Invio per continuare...",
    "pantheon.no_believers_to_bless": "  Non hai credenti da benedire.",
    "pantheon.bless_success": "  La tua luce divina fluisce in {0}!",
    "pantheon.bless_effect": "  Riceve +{0}% danni/difesa per {1} combattimenti.",
    "pantheon.no_mortals_to_smite": "  Non ci sono non credenti da colpire.",
    "pantheon.smite_strike": "  Il fulmine divino colpisce {0}!",
    "pantheon.smite_player_damage": "  Subisce ~{0} danni!",
    "pantheon.smite_npc_damage": "  Subisce {0} danni! (PV: {1}/{2})",
    "pantheon.not_enough_mortals": "  Non ci sono abbastanza mortali da manipolare.",
    "pantheon.poison_success": "  Sussurri oscuri scorrono tra {0} e {1}.",
    "pantheon.poison_weakens": "  Il loro legame si indebolisce.",
    "pantheon.poison_failure": "  La tua influenza non attecchisce. Il loro legame è troppo forte.",
    "pantheon.no_prisoners": "  Non ci sono prigionieri da liberare.",
    "pantheon.prison_days": " giorni rimanenti",
    "pantheon.free_success": "  Le mura della prigione brillano e {0} esce libero!",
    "pantheon.proclamation_header": "  PROCLAMA DIVINO",
    "pantheon.proclamation_intro": "  Le tue parole echeggeranno per tutto il reame.",
    "pantheon.proclamation_prompt": "  Il tuo proclama (max 120 caratteri): ",
    "pantheon.proclamation_success": "  Le tue parole tuonano per il reame dei mortali!",
    "pantheon.only_god": "  Sei l'unico dio nel reame.",
    "pantheon.rankings_col_num": "#",
    "pantheon.rankings_col_name": "Nome Divino",
    "pantheon.rankings_col_title": "Titolo",
    "pantheon.rankings_col_lvl": "Liv",
    "pantheon.rankings_col_exp": "Esp",
    "pantheon.rankings_col_believers": "Cred.",
    "pantheon.rankings_col_status": "Stato",
    "pantheon.ranking_you": "TU",
    "pantheon.ranking_online": "IN LINEA",
    "pantheon.ranking_offline": "NON IN LINEA",
    "pantheon.no_news": "  Nessuna notizia al momento.",
    "pantheon.comment_header": "  INVIA UN COMMENTO AI TUOI CREDENTI",
    "pantheon.comment_intro": "  Questo messaggio apparirà come notizia (nessun costo in gesta).",
    "pantheon.comment_prompt": "  Il tuo messaggio (max 120 caratteri): ",
    "pantheon.comment_success": "  Le tue parole sono state registrate negli annali.",
    "pantheon.manwe_approach": "  Ti avvicini al trono di Manwe, il Creatore Supremo.",
    "pantheon.manwe_max_1": "  \"Hai raggiunto l'apice del potere divino.\"",
    "pantheon.manwe_max_2": "  \"Non c'è più nulla che io possa insegnarti.\"",
    "pantheon.manwe_max_3": "  \"Va' e plasma il mondo come meglio credi.\"",
    "pantheon.manwe_approval": "  Gli occhi di Manwe brillano di approvazione.",
    "pantheon.manwe_power_grows": "  \"Il tuo potere cresce, {0}.\"",
    "pantheon.manwe_now_title": "  \"Ora sei un {0}.\"",
    "pantheon.god_rankup": "  RANGO DIVINO AUMENTATO! Livello {0} — {1}",
    "pantheon.deeds_increased": "  Gesta giornaliere aumentate a {0}.",
    "pantheon.manwe_not_ready": "  \"Non sei ancora pronto, {0}.\"",
    "pantheon.experience_progress": "  Esperienza: {0} / {1}",
    "pantheon.manwe_gather_more": "  \"Raduna più credenti. Compi più gesta.\"",
    "pantheon.renounce_warning": "  ATTENZIONE: Questa azione è permanente e non può essere annullata!",
    "pantheon.renounce_1": "  - Il tuo registro divino sarà cancellato",
    "pantheon.renounce_2": "  - Tutti i credenti perderanno la loro fede",
    "pantheon.renounce_3": "  - I dati del tuo personaggio saranno eliminati",
    "pantheon.renounce_4": "  - Ricomincerai da capo (bonus ciclo conservati)",
    "pantheon.renounce_confirm_yes": "  Sei sicuro? (Digita SÌ per confermare): ",
    "pantheon.renounce_confirm_name": "  Questa azione è veramente permanente. Digita il tuo nome divino per confermare: ",
    "pantheon.renounce_abdicate": "  Il trono è stato abdicato mentre rinunci al tuo potere divino.",
    "pantheon.renounce_fade": "  La luce divina svanisce dai tuoi occhi...",
    "pantheon.renounce_mortal": "  Sei di nuovo mortale.",
    "pantheon.renounce_new_life": "  La ruota gira. Una nuova vita ti attende.",
    "pantheon.renounce_begin_anew": "  Premi Invio per ricominciare...",
    "pantheon.prompt_divine_will": "\n  La tua volontà divina: ",
    "pantheon.page_format": "  Pagina {0}/{1}  |  [N]Succ.  [P]Prec.  |  {2} totale",
    "pantheon.boon_choice_prompt": "\n  Scelta: ",
    "pantheon.pagan": "Pagano",
    "pantheon.follows": "Segue {0}",
    "help.section_locations": "=== LUOGHI ===",
    "help.section_information": "=== INFORMAZIONI ===",
    "help.section_actions": "=== AZIONI ===",
    "help.section_tips": "=== CONSIGLI ===",
    "help.dungeons": "  [D] Sotterranei   - Combatti mostri, trova tesori, guadagna esperienza",
    "help.inn": "  [I] Locanda       - Riposa, socializza, gioca d'azzardo e corteggia",
    "help.weapon_shop": "  [W] Armaiolo      - Compra e vendi armi",
    "help.armor_shop": "  [A] Armatura      - Compra e vendi armature",
    "help.magic_shop": "  [M] Negozio Magico - Compra incantesimi e oggetti magici",
    "help.healer": "  [H] Guaritore     - Cura ferite, veleno e malanni",
    "help.bank": "  [B] Banca         - Deposita/preleva oro, chiedi prestiti",
    "help.temple": "  [T] Tempio        - Prega, dona, ricevi benedizioni",
    "help.castle": "  [C] Castello      - Visita la corte reale",
    "help.home": "  [Y] Casa Tua      - Riposa e gestisci i tuoi averi",
    "help.level_master": "  [*] Maestro       - Allenati per aumentare il tuo livello",
    "help.auction": "  [J] Casa d'Aste   - Compra e vendi oggetti con altri giocatori",
    "help.dark_alley": "  [X] Vicolo Oscuro - Affari loschi e attività criminali",
    "help.status": "  [S] Stato         - Visualizza le statistiche del personaggio",
    "help.news": "  [N] Notizie       - Leggi le notizie del giorno",
    "help.fame": "  [F] Fama          - Visualizza la sala della fama",
    "help.world_events": "  [$] Eventi Mondo  - Vedi gli eventi che influenzano il reame",
    "help.good_deeds": "  [G] Buone Azioni  - Compi atti di carità (+Cavalleria)",
    "help.wilderness": "  [E] Terre Selvagge - Esplora le lande oltre le porte della città",
    "help.talk_npcs": "  [0] Parla con PNG - Interagisci con i personaggi nel luogo attuale",
    "help.tip_dungeons": "  - Visita i Sotterranei per guadagnare esperienza e oro",
    "help.tip_level": "  - Quando hai abbastanza esperienza, visita il Maestro per avanzare",
    "help.tip_bank": "  - Tieni l'oro in Banca per proteggerlo dai ladri",
    "help.tip_npcs": "  - Costruisci relazioni con i PNG - possono diventare alleati o nemici",
    "help.tip_alignment": "  - Il tuo allineamento (Cavalleria vs Oscurità) influenza il trattamento dei PNG",
    "ui.stat_atk": "ATT",
    "ui.unidentified": "Non identificato",
    "ui.using_2h_weapon": "(usa arma a 2M)",
    "ui.healing_potions": "Pozioni Curative",
    "ui.potions_remaining": "Pozioni rimanenti",
    "ui.mana_label": "Mana",
    "ui.stat_critd": "DanCr",
    "ui.stat_apen": "PenA",
    "ui.stat_leech": "Ruba",
    "ui.stat_psn": "Vel",
    "ui.weapon_power": "Potenza Arma",
    "ui.armor_class": "Classe Armatura",
    "ui.shield_block": "Blocco Scudo",
    "ui.max_hp": "PV Max",
    "ui.max_mana": "Mana Max",
    "ui.magic_resist": "Resist. Magica",
    "ui.crit_chance": "Prob. Critico",
    "ui.crit_damage": "Danno Critico",
    "ui.life_steal": "Furto Vita",
    "ui.hit_points": "Punti Vita",
    "ui.attributes": "ATTRIBUTI",
    "ui.name_label": "Nome",
    "ui.value_label": "Valore",
    "ui.str_required": "Forza Richiesta",
    "prison.title": "STATO PRIGIONIERO",
    "prison.days_remaining": "Giorni rimanenti in prigione: {0}",
    "prison.escape_attempts": "Tentativi di fuga rimasti: {0}",
    "prison.released_tomorrow": "Verrai probabilmente rilasciato domani.",
    "prison.days_left": "Ti restano {0} giorni da scontare.",
    "prison.not_imprisoned": "Non sei imprigionato! Ritorno alla Via Principale.",
    "prison.guards_open": "Le guardie aprono la porta della tua cella.",
    "prison.sentence_served": "\"La tua pena è stata scontata. Sei libero di andare.\"",
    "prison.you_are_free": "Sei LIBERO!",
    "prison.darkness_reduced": "Il tempo scontato ha ridotto la tua reputazione oscura. (-{0} Oscurità)",
    "prison.cell_door_open": "La porta della cella si spalanca!",
    "prison.broke_out": " ti ha fatto evadere di prigione!",
    "prison.owe_freedom": "Gli devi la tua libertà!",
    "prison.someone_unlocked": "Qualcuno ha aperto la tua cella!",
    "prison.walk_out": "Esci dalla tua cella.",
    "prison.royal_prison": "La Prigione Reale",
    "prison.atmo1": "Ti svegli infreddolito e dolorante.",
    "prison.atmo2": "Urla terrificanti dalla camera di tortura vicina ti fanno",
    "prison.atmo3": "rabbrividire di paura.",
    "prison.atmo4": "Lo Sceriffo e i suoi sgherri si sentono chiacchierare nel",
    "prison.atmo5": "corridoio qui fuori.",
    "prison.menu_who": "Chi altro c'è qui",
    "prison.menu_demand": "Esigi di essere rilasciato!",
    "prison.menu_open": "Apri la porta della cella",
    "prison.menu_escape": "Fuggi!",
    "prison.menu_status": "Stato",
    "prison.menu_activities": "Attività - Esercitati!",
    "prison.menu_vex": "Voce nell'oscurità (Un prigioniero peculiare sussurra...)",
    "prison.menu_quit": "(Q)Esci",
    "prison.prompt": "Prigione Reale",
    "prison.prompt_expert": "Prigione Reale (W,M,N,D,O,S,E,A,Q,?) :",
    "prison.activities_header": "ATTIVITÀ IN PRIGIONE",
    "prison.activities_intro1": "Mentre sei imprigionato, puoi passare il tempo",
    "prison.activities_intro2": "con attività che migliorano il tuo corpo e la tua mente.",
    "prison.choose_activity": "Scegli attività (0 per annullare): ",
    "prison.sleep_hay": "Ti copri con del fieno e cerchi di dormire.",
    "prison.long_cold_night": "Sarà una lunga e fredda notte con i topi...",
    "prison.iron_door": "Cerchi di aprire la porta di ferro, ma è impossibile.",
    "prison.trapped": "Sei intrappolato qui dentro! Forse dovresti tentare la fuga.",
    "prison.clear_throat": "Schiarisci la voce: ",
    "prison.let_me_out": "Fatemi uscire di qui per favore....!",
    "prison.dark_voice": "Dopo un momento senti una voce cupa gridare:",
    "prison.released_probably": "(Verrai probabilmente rilasciato domani)",
    "prison.no_escapes": "Non hai più tentativi di fuga! Riprova domani.",
    "prison.escape_failed": "Hai fallito!",
    "prison.guards_heard": "Le guardie hanno sentito il tuo tentativo di fuga!",
    "prison.sentence_extended": "La tua pena è stata estesa di 1 giorno!",
    "prison.escape_success": "Riuscito! Sei LIBERO!",
    "prison.escaped_message": "Sei evaso con successo dalla prigione!",
    "prison.free_return": "Ora sei libero di tornare alle tue avventure!",
    "prison.prisoners_header": "Prigionieri",
    "prison.only_prisoner": "Sei l'unico prigioniero qui al momento!",
    "prison.days_left_info": "Ti restano {0} giorno/i in prigione.",
    "prison.awake": " (sveglio)",
    "prison.dead": " (morto)",
    "prison.sleeping": " (addormentato)",
    "prison.the_race": "il/la {0}",
    "prison.days_left_parens": " ({0} giorno/i rimasti)",
    "prison.no_one_unusual": "Non vedi nessuno di insolito nelle vicinanze.",
    "prison.prompt_prefix": "Prigione Reale (",
    "prison.prompt_suffix": " per il menù) :",
    "prison.sr_menu_who": "W. Chi altro c'è qui",
    "prison.sr_menu_demand": "D. Esigi di essere rilasciato!",
    "prison.sr_menu_open": "O. Apri la porta della cella",
    "prison.sr_menu_escape": "E. Fuggi!",
    "prison.sr_menu_status": "S. Stato",
    "prison.sr_menu_activities": "A. Attività - Esercitati!",
    "prison.sr_menu_vex": "V. Voce nell'oscurità (Un prigioniero peculiare sussurra...)",
    "prison.sr_menu_quit": "Q. Esci",
    "prison.menu_row1": "(W) Chi altro c'è qui        (D) Esigi di essere rilasciato!",
    "prison.menu_row2": "(O) Apri porta cella          (E) Fuggi!",
    "prison.menu_row3": "(S) Stato                     (A) Attività - Esercitati!",
    "prison.menu_vex_suffix": "oce nell'oscurità         (Un prigioniero peculiare sussurra...)",
    "prison.location_status": "Imprigionato - {0} giorno/i rimanenti, {1} tentativi di fuga rimasti",
    "prison.cmd_menu": "? - Mostra menù",
    "prison.cmd_who": "W - Chi altro c'è qui",
    "prison.cmd_demand": "D - Esigi di essere rilasciato",
    "prison.cmd_open": "O - Prova ad aprire la porta della cella",
    "prison.cmd_escape": "E - Tenta la fuga",
    "prison.cmd_status": "S - Mostra stato",
    "prison.cmd_quit": "Q - Esci dal gioco",
    "save.character": "Personaggio: {0}",
    "save.current_day": "Giorno Attuale: {0}",
    "save.turns_remaining": "Turni Rimanenti: {0}",
    "save.last_saved": "Ultimo Salvataggio: {0}",
    "save.file": "File: {0}",
    "save.no_saves": "Nessun file di salvataggio trovato!",
    "ui.health_label": "Salute",
    "shop.purchased_equipped": "Hai acquistato e equipaggiato {0}!",
    "shop.purchased_inventory": "Hai acquistato {0} — aggiunto all'inventario.",
    "shop.purchased_inventory_alt": "Hai acquistato {0}! (Aggiunto all'inventario)",
    "shop.sold_single": "Venduto {0} per {1} oro!",
    "shop.sold_bulk": "Venduti {0} oggetti per {1} oro!",
    "shop.sold_bulk_one": "Venduto {0} oggetto per {1} oro!",
    "shop.insufficient_gold": "Ti servono {0} oro ma ne hai solo {1}!",
    "shop.insufficient_gold_enchant": "Ti servono {0} oro per questo incantamento.",
    "shop.insufficient_gold_short": "Ti servono {0} oro.",
    "shop.item_to_inventory": "Questo oggetto andrà nel tuo inventario (per compagni/PNG).",
    "shop.cursed_cannot_sell": "Il/La {0} è MALEDETTO/A e non può essere venduto/a!",
    "shop.cursed_warning": "Il/La {0} è MALEDETTO/A!",
    "shop.cursed_tag": " [MALEDETTO]",
    "shop.cursed_no_enchant": " [MALEDETTO - impossibile incantare]",
    "shop.level_requirement": "Devi essere livello {0} per usare questo strumento.",
    "shop.enchant_level_req": "Devi essere almeno livello {0} per questo incantamento.",
    "shop.max_potions": "Hai già il numero massimo di pozioni curative!",
    "shop.max_enchantments": "Questo oggetto ha già {0} incantamenti. Un altro lo distruggerebbe.",
    "shop.enchant_warning": "  ATTENZIONE: Questo oggetto ha {0} incantamenti. Aggiungerne un altro ha il {1}% di probabilità",
    "shop.alignment_good_only": "Questo oggetto può essere usato solo da personaggi buoni.",
    "shop.alignment_evil_only": "Questo oggetto può essere usato solo da personaggi malvagi.",
    "shop.cursed_item_healer": "Il tuo {0} è MALEDETTO!",
    "shop.healing_cost": "Ti servono {0} PV per essere completamente guarito (costa {1} oro con le tasse).",
    "shop.ocean_flavor": "Questo oggetto... ricorda le profondità. I sogni dell'Oceano.",
    "shop.sold_accessories": "Venduti {0} accessori per {1} oro!",
    "shop.couldnt_equip": "Impossibile equipaggiare {0} — aggiunto all'inventario.",
    "shop.cant_afford_potions": "Non puoi permetterti nessuna pozione!",
    "shop.strip_enchant_warning": "ATTENZIONE: Questo rimuoverà TUTTI gli incantamenti, riportando l'oggetto alla forma base.",
    "ui.bounty_reward": "Ricompensa Taglia: {0} oro",
    "ui.gold_plundered": "Oro Saccheggiato: {0}",
    "ui.gold_taken": "Oro preso: {0}",
    "ui.defeated_all_members": "Hai sconfitto tutti i {0} membri di {1}!",
    "ui.invalid_choice": "Scelta non valida.",
    "training.prof_untrained": "Non addestrato",
    "training.prof_poor": "Scarso",
    "training.prof_average": "Medio",
    "training.prof_good": "Buono",
    "training.prof_skilled": "Abile",
    "training.prof_expert": "Esperto",
    "training.prof_superb": "Superbo",
    "training.prof_master": "Maestro",
    "training.prof_legendary": "Leggendario",
    "training.prof_unknown": "Sconosciuto",
    "training.center_header": "CENTRO DI ADDESTRAMENTO",
    "training.available_points": "Punti Addestramento Disponibili: {0}",
    "training.col_header": "Num  Abilità                  Livello      Progresso  Costo/Pt",
    "training.max": "MAX",
    "training.menu_prompt": "Inserisci il numero dell'abilità da addestrare, [R] Resetta addestramento, o X per uscire.",
    "training.already_legendary": "{0} è già a livello Leggendario!",
    "training.need_points": "Ti servono almeno {0} punti addestramento per addestrare questa abilità!",
    "training.only_have_points": "Hai solo {0} punti addestramento.",
    "training.training_skill": "Addestramento {0} (Attuale: {1})",
    "training.progress_toward": "Progresso: {0}/{1} verso {2}",
    "training.cost_per_point": "Costo per punto progresso: {0} punti addestramento",
    "training.spend_points": "[1] Spendi {0} punto/i addestramento (+1 progresso)",
    "training.spend_to_reach": "[M] Spendi {0} punti per raggiungere {1} (+{2} progresso)",
    "training.spend_partial": "[M] Spendi {0} punti per +{1} progresso (servono {2} totali per {3})",
    "training.cancel": "[X] Annulla",
    "training.now_level": "{0} è ora {1}!",
    "training.roll_modifier": "  Modificatore Tiro: {0}",
    "training.effect_power": "  Potenza Effetto: {0}%",
    "training.spent_points": "  (Spesi {0} punti addestramento)",
    "training.progress_update": "Addestramento {0}... Progresso: {1}/{2} (spesi {3} punto/i)",
    "training.reset_single": "[1] Resetta una singola abilità",
    "training.reset_all": "[2] Resetta TUTTE le competenze",
    "training.reset_header": "RESETTA ADDESTRAMENTO",
    "training.reset_single_header": "RESETTA SINGOLA ABILITÀ",
    "training.service_fee": "Costo del servizio: {0} oro",
    "training.your_gold": "Il tuo oro: {0}",
    "training.reset_col_header": "Num  Abilità                  Livello       Punti Investiti",
    "training.reset_skill_prompt": "Inserisci il numero dell'abilità da resettare, o X per annullare.",
    "training.need_gold": "Ti servono {0} oro ma ne hai solo {1}!",
    "training.skill_improved": "Abilità Migliorata!",
    "love_corner.you_enter": "Entri in {0}.",
    "love_corner.banner": "-=*=- {0} -=*=-",
    "love_corner.intro1": "Vieni ad allenare le tue abilità romantiche. Non c'è niente",
    "love_corner.intro2": "come una grande famiglia e una casa.",
    "love_corner.intro3": "Dovresti anche fare ammenda con le persone che hai ferito nel corso",
    "love_corner.intro4": "degli anni. Puoi anche avvelenare la vita altrui qui.",
    "love_corner.menu_a": "A. Avvicina qualcuno             C. Bambini nel Reame",
    "love_corner.menu_d": "D. Divorzio                      V. Visita {0}",
    "love_corner.menu_m": "M. Coppie Sposate                E. Esamina bambino",
    "love_corner.menu_p": "P. Relazioni Personali           G. Negozio di regali",
    "love_corner.menu_s": "S. Stato                         R. Ritorna",
    "love_corner.menu_l": "L. Storia d'amore",
    "love_corner.expert_prompt": "{0} (A,C,D,E,V,M,P,G,S,R,L) :",
    "love_corner.approach_header": "Avvicina Qualcuno",
    "love_corner.come_back_tomorrow": "Torna domani per altre opportunità romantiche.",
    "love_corner.enter_name": "Inserisci il nome della persona che desideri avvicinare: ",
    "love_corner.invalid_name": "Nome inserito non valido.",
    "love_corner.searching": "Ricerca di {0}...",
    "love_corner.dating_with": "Appuntamento con {0}",
    "love_corner.dating_menu1": "K. Bacia                         D. Cena",
    "love_corner.dating_menu2": "H. Tieniti per mano               I. Intimità",
    "love_corner.dating_menu3": "M. Matrimonio                     C. Cambia sentimenti",
    "love_corner.dating_menu4": "R. Ritorna",
    "love_corner.choose_action": "Scegli la tua azione: ",
    "love_corner.invalid_choice": "Scelta non valida.",
    "love_corner.kiss_lean": "Ti sporgi per baciare {0}...",
    "love_corner.kiss_result": "Un bacio appassionato! Entrambi guadagnate {0} punti esperienza!",
    "love_corner.acts_left": "Ti restano {0} atti d'intimità oggi.",
    "love_corner.relationship_improved": "La tua relazione con {0} è migliorata!",
    "love_corner.dinner_invite": "Inviti {0} a cena...",
    "love_corner.dinner_result": "Una cena deliziosa! Entrambi guadagnate {0} punti esperienza!",
    "love_corner.dinner_wine": "La conversazione scorre liscia come il vino!",
    "love_corner.hold_hands": "Allunghi la mano per prendere quella di {0}...",
    "love_corner.hold_result": "Un momento tenero! Entrambi guadagnate {0} punti esperienza!",
    "love_corner.hold_walk": "Camminate insieme, mano nella mano, condividendo un momento bellissimo.",
    "love_corner.intimate_embrace": "Abbracci {0} con passione...",
    "love_corner.intimate_result": "Abbraccio appassionato! Entrambi guadagnate {0} punti esperienza!",
    "love_corner.intimate_emotion": "Il momento è pieno di profonda emozione e connessione.",
    "love_corner.gods_smile": "Gli dèi sorridono alla vostra unione...",
    "love_corner.marriage_header": "Cerimonia di Matrimonio",
    "love_corner.wedding_cost": "La cerimonia nuziale costa {0} oro!",
    "love_corner.you_only_have": "Hai solo {0} oro.",
    "love_corner.wedding_with": "Cerimonia nuziale con {0}:",
    "love_corner.cost_label": "Costo: {0} oro",
    "love_corner.proceed_ceremony": "Procedere con la cerimonia? (S/N): ",
    "love_corner.wedding_cancelled": "Cerimonia nuziale annullata.",
    "love_corner.wedding_ceremony": "*** CERIMONIA NUZIALE ***",
    "love_corner.now_married": "{0} e {1} sono ora sposati!",
    "love_corner.congratulations": "Congratulazioni! (andate a casa e fate figli)",
    "love_corner.change_feelings": "Cambia i Tuoi Sentimenti",
    "love_corner.feelings_menu1": "L. Amore              P. Passione",
    "love_corner.feelings_menu2": "F. Amicizia           T. Fiducia",
    "love_corner.feelings_menu3": "R. Rispetto           N. Neutrale",
    "love_corner.feelings_menu4": "S. Sospetto           A. Rabbia",
    "love_corner.feelings_menu5": "E. Nemico             H. Odio",
    "love_corner.how_feel": "Cosa provi per loro? ",
    "love_corner.feelings_set": "I tuoi sentimenti verso {0} sono stati impostati a: {1}",
    "love_corner.love_reaction": "AMORE! AMORE! AMORE! AMORE!",
    "love_corner.hate_reaction": "ODIO! ODIO! ODIO! ODIO!",
    "love_corner.divorce_header": "Procedimenti di Divorzio",
    "love_corner.not_married": "Non sei sposato, sciocco!",
    "love_corner.find_spouse": "Vai a trovarti un coniuge prima che sia troppo tardi!",
    "love_corner.married_to": "Sei sposato con {0}.",
    "love_corner.divorce_process": "Procedura di divorzio:",
    "love_corner.divorce_custody": "- Perderai la custodia dei tuoi figli!",
    "love_corner.divorce_hostile": "- La vostra relazione diventerà ostile!",
    "love_corner.divorce_cost": "- Il divorzio costa {0} oro!",
    "love_corner.need_gold_divorce": "Ti servono {0} oro per le procedure di divorzio!",
    "love_corner.confirm_custody": "Perderai la custodia dei tuoi figli! Procedere comunque? (S/N): ",
    "love_corner.divorce_cancelled": "Divorzio annullato.",
    "love_corner.divorce_finalized": "*** DIVORZIO FINALIZZATO ***",
    "love_corner.good_riddance": "{0} se n'è andato finalmente, e buon viaggio!",
    "love_corner.lost_custody": "Hai perso la custodia dei tuoi figli!",
    "love_corner.single_life": "Vita da single! Eccomi!",
    "love_corner.children_header": "Bambini nel Reame",
    "love_corner.child_listing": "Elenco bambini:",
    "love_corner.child_view": "- Visualizza tutti i bambini nel reame",
    "love_corner.child_orphans": "- Vedi gli orfani disponibili per l'adozione",
    "love_corner.child_kidnapped": "- Controlla i bambini rapiti",
    "love_corner.future_update": "Questa funzione sarà completamente implementata in un aggiornamento futuro.",
    "love_corner.your_children": "I Tuoi Figli",
    "love_corner.no_children": "Non hai figli.",
    "love_corner.how_to_children1": "Per avere figli, sposa qualcuno del sesso opposto",
    "love_corner.how_to_children2": "e visita la tua casa per momenti intimi.",
    "love_corner.child_count": "Hai {0} figlio/i{1}:",
    "love_corner.child_count_ren": "",
    "love_corner.child_age": "    Età: {0} anno/i{1}",
    "love_corner.child_sex": "    Sesso: {0}",
    "love_corner.male": "Maschio",
    "love_corner.female": "Femmina",
    "love_corner.child_behavior": "    Comportamento: {0}",
    "love_corner.child_health": "    Salute: {0}",
    "love_corner.child_location": "    Luogo: {0}",
    "love_corner.child_status": "    Stato: {0}",
    "love_corner.child_other_parent": "    Altro Genitore: {0}",
    "love_corner.teens_coming_of_age": "{0} dei tuoi figli diventeranno presto maggiorenni!",
    "love_corner.teens_independent": "Quando i figli raggiungono i 18 anni, diventano PNG indipendenti.",
    "love_corner.visiting_gossip": "Visita a {0}",
    "love_corner.gossip_welcome": "\"Benvenuto, caro! Sei venuto a sentire gli ultimi pettegolezzi?\"",
    "love_corner.services_available": "Servizi disponibili:",
    "love_corner.gossip_spy": "- Spia le relazioni degli altri giocatori",
    "love_corner.gossip_marriages": "- Ottieni informazioni sui matrimoni",
    "love_corner.gossip_divorces": "- Scopri i divorzi recenti",
    "love_corner.gossip_children": "- Ascolta pettegolezzi sui figli",
    "love_corner.gossip_cost": "\"I miei servizi non sono gratuiti, ma valgono ogni moneta d'oro!\"",
    "love_corner.married_couples": "<3<3<3 Coppie Sposate <3<3<3",
    "love_corner.no_couples": "Nessuna coppia sposata nel reame al momento.",
    "love_corner.personal_relations": "Relazioni Personali di {0}",
    "love_corner.status_married_to": "Sposato con: {0}",
    "love_corner.marriage_count": "Numero di matrimoni: {0}",
    "love_corner.children_count": "Figli: {0}",
    "love_corner.intimacy_left": "Atti d'intimità rimasti oggi: {0}",
    "love_corner.relations_feature": "Funzione relazioni personali:",
    "love_corner.relations_view": "- Visualizza tutte le tue relazioni",
    "love_corner.relations_love_hate": "- Vedi chi ti ama/odia",
    "love_corner.relations_history": "- Controlla la storia delle relazioni",
    "love_corner.relations_network": "Questo mostrerà la tua rete relazionale completa nel sistema definitivo.",
    "love_corner.gift_shop": "Negozio di Regali",
    "love_corner.gift_welcome": "Benvenuto al Negozio di Regali dell'Angolo dell'Amore!",
    "love_corner.gift_roses": "R. Rose - {0} oro",
    "love_corner.gift_chocolates": "C. Cioccolatini - {0} oro",
    "love_corner.gift_jewelry": "J. Gioielli - {0} oro",
    "love_corner.gift_poison": "P. Avvelena qualcuno - {0} oro",
    "love_corner.gift_exit": "E. Esci dal negozio",
    "love_corner.gift_purchase_prompt": "Cosa desideri acquistare? ",
    "love_corner.gift_thank_you": "Grazie per aver visitato il negozio di regali!",
    "love_corner.gift_need_gold": "Ti servono {0} oro per comprare {1}!",
    "love_corner.gift_send_to": "A chi vorresti inviare {0}? ",
    "love_corner.gift_invalid_recipient": "Destinatario non valido.",
    "love_corner.gift_sent": "Hai inviato {0} a {1}!",
    "love_corner.gift_appreciate": "Apprezzeranno sicuramente il tuo premuroso regalo.",
    "love_corner.poison_header": "Acquisto Veleno",
    "love_corner.poison_offer": "\"Psst... cerchi qualcosa di... speciale?\"",
    "love_corner.poison_cost": "\"Ti costerà {0} oro, senza domande.\"",
    "love_corner.poison_need_gold": "Ti servono {0} oro!",
    "love_corner.poison_target": "Chi è il tuo... bersaglio? ",
    "love_corner.poison_no_target": "\"Nessun bersaglio, nessun affare.\"",
    "love_corner.poison_done": "\"Consideralo fatto. {0} avrà... un incidente.\"",
    "love_corner.poison_never": "\"Non abbiamo mai avuto questa conversazione.\"",
    "love_corner.status_header": "Stato Relazionale di {0}",
    "love_corner.age": "Età: {0} anni",
    "love_corner.sex": "Sesso: {0}",
    "love_corner.race": "Razza: {0}",
    "love_corner.marital_married": "Stato Civile: Sposato con {0}",
    "love_corner.times_married": "Volte sposato: {0}",
    "love_corner.marital_single": "Stato Civile: Celibe/Nubile",
    "love_corner.previous_marriages": "Matrimoni precedenti: {0}",
    "love_corner.intimacy_remaining": "Atti d'intimità rimasti oggi: {0}",
    "love_corner.good_hearted": "{0} ha un cuore buono.",
    "love_corner.evil_mind": "{0} ha una mente malvagia.",
    "love_corner.history_header": "Storia d'Amore",
    "love_corner.history_intro": "Guarda cos'è successo nel corso degli anni.",
    "love_corner.history_menu1": "M. Matrimoni e Divorzi          C. Nascite e Morti",
    "love_corner.history_menu2": "1. Matrimoni Attuali             H. Giocatori più odiati",
    "love_corner.history_menu3": "L. Giocatori più amati           R. Ritorna",
    "love_corner.marriage_history": "Cronaca di Matrimoni e Divorzi",
    "love_corner.marriage_history_text": "I matrimoni e divorzi recenti verranno mostrati qui.",
    "love_corner.marriage_history_log": "Questa funzione mostrerà il registro completo di matrimoni/divorzi.",
    "love_corner.child_birth_history": "Cronaca delle Nascite",
    "love_corner.child_birth_text": "Le nascite e morti recenti verranno mostrate qui.",
    "love_corner.child_birth_log": "Questa funzione mostrerà il registro completo delle nascite.",
    "love_corner.most_hated": "Giocatori Più Odiati",
    "love_corner.most_hated_text": "I 10 giocatori più odiati verranno mostrati qui.",
    "love_corner.most_loved": "Giocatori Più Amati",
    "love_corner.most_loved_text": "I 10 giocatori più amati verranno mostrati qui.",
    "love_corner.rel_married": "Sposato",
    "love_corner.rel_love": "Amore",
    "love_corner.rel_passion": "Passione",
    "love_corner.rel_friendship": "Amicizia",
    "love_corner.rel_trust": "Fiducia",
    "love_corner.rel_respect": "Rispetto",
    "love_corner.rel_neutral": "Neutrale",
    "love_corner.rel_suspicious": "Sospetto",
    "love_corner.rel_anger": "Rabbia",
    "love_corner.rel_enemy": "Nemico",
    "love_corner.rel_hate": "Odio",
    "love_corner.rel_unknown": "Sconosciuto",
    "auth.title": "USURPER REBORN - IN LINEA",
    "auth.login": "Accedi a un account esistente",
    "auth.register": "Registra un nuovo account",
    "auth.quit": "Esci",
    "auth.your_choice": "La tua scelta: ",
    "auth.invalid_choice": "Scelta non valida.",
    "auth.too_many_attempts": "Troppi tentativi falliti. Disconnessione.",
    "auth.welcome": "Benvenuto nel server online di Usurper Reborn!",
    "auth.welcome_instruction": "Accedi con il tuo account o registrane uno nuovo.",
    "auth.username": "Nome utente: ",
    "auth.password": "Password: ",
    "auth.authenticating": "Autenticazione...",
    "auth.prev_session_disconnected": "Sessione precedente disconnessa.",
    "auth.welcome_back": "Bentornato, {0}!",
    "auth.create_new_account": "Crea Nuovo Account",
    "auth.create_sr": "Crea Nuovo Account",
    "auth.username_instructions": "Scegli un nome utente (2-20 caratteri, lettere/numeri/spazi).",
    "auth.username_also_name": "Questo sarà anche il nome del tuo personaggio nel gioco.",
    "auth.confirm_password": "Conferma password: ",
    "auth.passwords_no_match": "Le password non corrispondono.",
    "auth.creating_account": "Creazione account...",
    "auth.logged_in_as": "Hai effettuato l'accesso come: {0}",
    "version.header": "NUOVA VERSIONE DISPONIBILE",
    "version.current": "Versione attuale: {0}",
    "version.latest": "Ultima versione:  {0}",
    "version.bbs_newer": "Una versione più recente di Usurper Reborn è disponibile!",
    "version.bbs_notify_sysop": "Per favore avvisa il tuo SysOp di aggiornare il gioco.",
    "version.bbs_sysop_download": "SysOp: Scarica l'ultima versione su:",
    "version.download_at": "Scarica l'ultima versione su:",
    "version.release_notes": "Note di rilascio:",
    "version.press_any_key": "Premi un tasto per continuare...",
    "version.open_download_prompt": "Vuoi aprire la pagina di download? (S/N): ",
    "version.auto_update_available": "L'aggiornamento automatico è disponibile per la tua piattaforma!",
    "version.auto_update_prompt": "Vuoi scaricare e installare automaticamente? (S/N): ",
    "version.manual_download_prompt": "Vuoi aprire invece la pagina di download? (S/N): ",
    "version.downloading": "Download dell'aggiornamento...",
    "version.progress": "Progresso: {0}%",
    "version.update_success": "Aggiornamento scaricato con successo!",
    "version.update_close": "Il gioco si chiuderà e si aggiornerà automaticamente.",
    "arena.desc1": "Le torce guizzano lungo le pareti della fossa di combattimento. La folla ruggisce",
    "arena.desc2": "mentre un altro sfidante avanza sulla sabbia macchiata di sangue.",
    "arena.attack_player": "ttacca Giocatore   ",
    "arena.leaderboard_menu": "lassifica",
    "arena.history_menu": "ronologia       ",
    "arena.stats_menu": "tatistiche   ",
    "arena.return_menu": "itorna",
    "arena.online_only": "L'Arena è disponibile solo in modalità online.",
    "arena.min_level": "Devi essere almeno livello {0} per entrare nella fossa.",
    "arena.master_waves": "Il maestro dell'arena ti manda via con un gesto.",
    "arena.max_fights": "Hai già combattuto {0} volte oggi.",
    "arena.come_back": "Il maestro dell'arena dice: \"Torna domani, guerriero.\"",
    "arena.choose_opponent": "SCEGLI IL TUO AVVERSARIO",
    "arena.choose_opponent_box": "═══ SCEGLI IL TUO AVVERSARIO ═══",
    "arena.attacks_remaining": "Attacchi rimanenti oggi: {0}",
    "arena.no_opponents": "Nessun avversario disponibile al momento.",
    "arena.level_range_note": "(Deve essere entro {0} livelli, non già combattuto oggi)",
    "arena.col_num": "#",
    "arena.col_name": "Nome",
    "arena.col_level": "Livello",
    "arena.col_class": "Classe",
    "arena.col_status": "Stato",
    "arena.lv_prefix": "Lv ",
    "arena.online_badge": "[IN LINEA]",
    "arena.choose_prompt": "Scegli avversario (numero, o Q per annullare): ",
    "arena.invalid_selection": "Selezione non valida.",
    "arena.confirm_attack": "Stai per attaccare {0} (Livello {1} {2})!",
    "arena.warning_damage": "ATTENZIONE: I danni che TU subisci persisteranno dopo il combattimento.",
    "arena.gold_steal_rule": "Il vincitore ruba il {0}% dell'oro in mano al perdente.",
    "arena.confirm_prompt": "Sei sicuro? (S/N): ",
    "arena.step_back": "Ti ritiri dalla fossa.",
    "arena.load_failed": "Impossibile caricare i dati dell'avversario. Potrebbe aver cancellato il personaggio.",
    "arena.safe_house_hiding": "{0} si nasconde nel Rifugio del Vicolo Oscuro.",
    "arena.shadows_protect": "Le Ombre proteggono i loro. Non riesci a trovarli.",
    "arena.challenges": "{0} sfida {1} nell'Arena!",
    "arena.victory": "Vittoria!",
    "arena.victory_box": "═══ VITTORIA! ═══",
    "arena.gold_stolen_from": "Oro rubato a {0}: {1}",
    "arena.bounty_collected": "TAGLIA RISCOSSA: {0} oro!",
    "arena.defeat": "Sei stato sconfitto!",
    "arena.defeat_box": "═══ SCONFITTA! ═══",
    "arena.defeated_by": "Sei stato sconfitto dall'ombra di {0} nell'Arena.",
    "arena.they_stole": "{0} ha rubato {1} del tuo oro!",
    "arena.lost_xp": "Persi {0} punti esperienza",
    "arena.lost_gold": "Persi {0} oro (penalità di morte)",
    "arena.healed_at_inn": "Guarito a {0}/{1} PV alla Locanda.",
    "arena.fled": "Sei fuggito dal combattimento!",
    "arena.leaderboard_header": "CLASSIFICA DELL'ARENA",
    "arena.leaderboard_header_box": "═══ CLASSIFICA DELL'ARENA ═══",
    "arena.no_fights_yet": "Nessun combattimento PvP è ancora avvenuto. Sii il primo a combattere!",
    "arena.lb_col_num": "#",
    "arena.lb_col_name": "Nome",
    "arena.lb_col_wl": "V/S",
    "arena.lb_col_level": "Livello",
    "arena.lb_col_gold": "Oro Rubato",
    "arena.recent_header": "COMBATTIMENTI RECENTI DELL'ARENA",
    "arena.recent_header_box": "═══ COMBATTIMENTI RECENTI DELL'ARENA ═══",
    "arena.sand_undisturbed": "La sabbia dell'arena è intatta. Nessun combattimento ancora.",
    "arena.vs": "vs",
    "arena.pvp_record": "IL TUO RECORD PVP",
    "arena.pvp_record_box": "═══ IL TUO RECORD PVP ═══",
    "arena.no_stats": "Nessuna statistica disponibile.",
    "arena.pvp_kills": "Uccisioni PvP:  {0}",
    "arena.pvp_deaths": "Morti PvP: {0}",
    "arena.win_rate": "Percentuale vittorie: {0}%",
    "arena.total_fights": "Combattimenti Totali: {0}",
    "quest_hall.desc1": "Una grande bacheca domina la parete, coperta di avvisi di taglia",
    "quest_hall.desc2": "e missioni affisse dal Consiglio Reale e dalle gilde locali.",
    "quest_hall.menu_header": "─── Sala delle Missioni ───",
    "quest_hall.active_count": "Missioni Attive: {0}, Disponibili: {1}",
    "quest_hall.active_count_visual": "Missioni Attive: {0}  |  Disponibili: {1}",
    "quest_hall.view_menu": "isualizza Missioni Disponibili    ",
    "quest_hall.active_menu": "ttive",
    "quest_hall.claim_menu": "ccetta una Missione           ",
    "quest_hall.turn_in_menu": "onsegna Missione",
    "quest_hall.bounty_menu": "acheca Taglie            ",
    "quest_hall.abandon_menu": " Abbandona Missione",
    "quest_hall.return_menu": "itorna alla Via",
    "quest_hall.invalid_choice": "Scelta non valida.",
    "quest_hall.no_quests_available": "Nessuna missione disponibile per il tuo livello.",
    "quest_hall.your_level": "(Il tuo livello: {0})",
    "quest_hall.no_quests_claim": "Nessuna missione disponibile da accettare.",
    "quest_hall.select_claim": "Seleziona una missione da accettare:",
    "quest_hall.select_prompt": "Seleziona: ",
    "quest_hall.accept_prompt": "Accettare questa missione? (S/N): ",
    "quest_hall.quest_accepted": "Missione accettata!",
    "quest_hall.days_to_complete": "Hai {0} giorni per completare questa missione.",
    "quest_hall.cannot_claim": "Impossibile accettare la missione: {0}",
    "quest_hall.quest_not_accepted": "Missione non accettata.",
    "quest_hall.select_turn_in": "Seleziona una missione da consegnare:",
    "quest_hall.quests_completed": "Missioni completate: {0}",
    "quest_hall.requirements_not_met": "Non hai ancora completato i requisiti della missione.",
    "quest_hall.cannot_complete": "Impossibile completare la missione: {0}",
    "quest_hall.select_abandon": "Seleziona una missione da abbandonare:",
    "quest_hall.abandon_confirm": "Abbandonare \"{0}\"?",
    "quest_hall.progress_lost": "Tutti i progressi andranno persi.",
    "quest_hall.quest_abandoned": "Missione abbandonata.",
    "quest_hall.bounty_desc": "Taglie affisse dalla Corona per individui pericolosi.",
    "quest_hall.no_bounties": "Nessuna taglia attualmente affissa.",
    "quest_hall.check_back": "Torna più tardi - il Re potrebbe affiggere nuove taglie.",
    "quest_hall.wanted": "RICERCATO: ",
    "quest_hall.dangerous_criminal": "Criminale pericoloso",
    "quest_hall.reward": "Ricompensa: {0}",
    "quest_hall.difficulty_posted": "Difficoltà: {0}, Affissa da: {1}",
    "quest_hall.from_levels": "Da: {0}, Livelli {1}-{2}",
    "quest_hall.difficulty_label": "Difficoltà: ",
    "quest_hall.posted_by": "Affissa da: {0}",
    "quest_hall.level_range": "Intervallo livelli: {0} - {1}",
    "quest_hall.time_limit": "Limite di tempo: {0} giorni",
    "quest_hall.quest_reward": "Ricompensa: {0}",
    "quest_hall.objectives": "Obiettivi:",
    "quest_hall.targets": "Bersagli:",
    "quest_hall.hint_dungeon": "Suggerimento: Combatti mostri nei Sotterranei per completare questa missione.",
    "quest_hall.hint_floor": "Suggerimento: Esplora più in profondità nei Sotterranei per raggiungere il piano obiettivo.",
    "quest_hall.hint_artifact": "Suggerimento: Cerca l'artefatto nelle stanze dei sotterranei.",
    "quest_hall.hint_weapon_shop": "Suggerimento: Acquista l'oggetto dall'Armaiolo.",
    "quest_hall.hint_armor_shop": "Suggerimento: Acquista l'oggetto dal Negozio di Armature.",
    "quest_hall.hint_magic_shop": "Suggerimento: Acquista l'oggetto dal Negozio Magico.",
    "quest_hall.hint_defeat": "Suggerimento: Trova e sconfiggi il bersaglio in combattimento.",
    "prison.quit_confirm": "ESCI dal gioco e riposa per la notte",
    "prison.jailbreak_confirm": "Evasione",
    "prison.vex_voice": "Una voce proviene dalla cella accanto alla tua:",
    "prison.vex_psst1": "\"Psst. Ehi. Tu. Quello con l'aria di chi",
    "prison.vex_psst2": " non appartiene a questo posto.\"",
    "prison.vex_peer1": "Sbirci attraverso le sbarre. Nella cella adiacente,",
    "prison.vex_peer2": "una figura snella se ne sta sdraiata contro il muro con improbabile comodità.",
    "prison.vex_peer3": "Sta sorridendo - davvero sorridendo - in un posto come questo.",
    "prison.vex_metal": "Tira fuori un pezzo di metallo piegato dal nulla.",
    "prison.vex_locks1": "\"Scassino serrature da prima che imparassi a camminare.\"",
    "prison.vex_locks2": "\"Il che è un bene, perché probabilmente non camminerò ancora a lungo.\"",
    "prison.vex_intro": "Questo è {0}, {1}.",
    "prison.vex_role": "Ruolo: {0}",
    "prison.vex_abilities": "Abilità: {0}",
    "prison.vex_menu_escape": "[E] Lascialo aiutarti a fuggire (e reclutalo)",
    "prison.vex_menu_talk": "[T] Parla di più della sua \"condizione\"",
    "prison.vex_menu_leave": "[L] Lascialo stare",
    "prison.vex_shake_head": "Scuoti la testa e torni alla tua cella.",
    "prison.vex_your_loss": "\"Peggio per te!\" grida allegramente.",
    "prison.vex_excellent": "\"Scelta eccellente!\" Vex sorride ancora di più.",
    "prison.vex_works_lock": "Lavora la serratura con facilità esperta.",
    "prison.vex_clicks": "*clic* *clic* *clac*",
    "prison.vex_trick1": "\"Sai qual è il trucco?\" sussurra.",
    "prison.vex_trick2": "\"Non si tratta di forzare le cose. Si tratta di ascoltare.\"",
    "prison.vex_trick3": "\"Ogni serratura vuole essere aperta. Basta chiedere gentilmente.\"",
    "prison.vex_click_loud": "*CLIC*",
    "prison.vex_door_open": "La porta della tua cella si apre silenziosamente.",
    "prison.vex_smoke": "Vex è già al tuo fianco, muovendosi come fumo.",
}
