translations = {
    "weapon_shop.gold_crowns": " corone d'oro.",
    "weapon_shop.two_handed_desc": "A Due Mani (+25% danno, -15% difesa)",
    "weapon_shop.dual_wield_desc": "Doppia Impugnatura (+1 attacco, -10% difesa)",
    "weapon_shop.sword_board_desc": "Spada e Scudo (difesa bilanciata)",
    "weapon_shop.one_handed_desc": "A Una Mano (standard)",
    "weapon_shop.unarmed_desc": "Disarmato",
    "weapon_shop.current_prefix": "Attuale: ",
    "weapon_shop.buy_item": "Compra oggetto   ",
    "weapon_shop.back": "Indietro",
    "weapon_shop.invalid_choice": "Scelta non valida!",
    "weapon_shop.invalid_item": "Numero oggetto non valido!",
    "weapon_shop.two_hand_warning": "Attenzione: le armi a due mani richiedono entrambe le mani!",
    "weapon_shop.shield_unequipped": "Il tuo scudo verrà rimosso.",
    "weapon_shop.sell_prompt": "Vendere quale? ([A] tutto lo zaino, 0 per annullare): ",
    "weapon_shop.no_sellable": "Nessuna arma o scudo vendibile nel tuo zaino.",
    "weapon_shop.purchase_cancelled": "Acquisto annullato.",
    "weapon_shop.skipped": "Saltato.",
    "weapon_shop.skipping_slot": "Salto dello slot arma.",
    "weapon_shop.auto_cancelled": "Acquisto automatico annullato.",
    "weapon_shop.auto_invalid": "Scelta non valida. Inserisci Y, N, S o C.",
    "weapon_shop.no_upgrades": "Nessun potenziamento arma accessibile disponibile.",
    "weapon_shop.press_enter": "Premi INVIO per continuare...",
    "weapon_shop.one_hand_where": "Questa è un'arma a una mano. Dove vuoi equipaggiarla?",
    "weapon_shop.main_hand_label": "  Mano Principale: ",
    "weapon_shop.off_hand_label": "  Mano Secondaria: ",
    "weapon_shop.using_2h": "(usa arma a 2M)",
    "weapon_shop.config_label": "  Configurazione: ",
    "weapon_shop.total_weapon_power": "  Potenza Arma Totale: ",
    "weapon_shop.categories": " Categorie:",
    "weapon_shop.main_label": " Princ:",
    "weapon_shop.off_label": "  Sec:",
    "weapon_shop.shield_header": "  #   Nome                        Liv  CA   Blocco Prezzo      Bonus",
    "weapon_shop.weapon_header": "  #   Nome                        Liv  Pot  Tipo      Prezzo      Bonus",
    "weapon_shop.previous": "] Precedente   ",
    "weapon_shop.next": "] Successivo   ",
    "weapon_shop.gold_prompt": " oro? (S/N): ",
    "weapon_shop.shadows_bonus": "  [Bonus Ombre: +20% prezzi di vendita]",
    "weapon_shop.equipped_label": "[ EQUIPAGGIATO ]",
    "weapon_shop.inventory_label": "[ INVENTARIO ]",
    "weapon_shop.auto_buy_yes": "  [Y] Compra quest'arma",
    "weapon_shop.auto_buy_no": "  [N] Salta, mostra prossima opzione",
    "weapon_shop.auto_buy_skip": "  [S] Salta lo slot arma",
    "weapon_shop.auto_buy_cancel": "  [C] Annulla acquisto automatico",
    "weapon_shop.one_hand_main": "  (M) Mano Principale: ",
    "weapon_shop.one_hand_off": "  (O) Mano Secondaria: ",
    "weapon_shop.one_hand_cancel": "  (C) Annulla",
    "weapon_shop.ambient_steel": "L'acciaio cozza contro l'acciaio da qualche parte nel retrobottega.",
    "weapon_shop.ambient_whetstone": "Il lento stridore di una mola riempie la stanza.",
    "weapon_shop.ambient_hammer": "Un martello batte sull'incudine nella fucina accanto.",
    "weapon_shop.ambient_oil": "L'odore pungente di olio e metallo aleggia nell'aria.",
    "weapon_shop.ambient_blade": "Una lama viene estratta dal fodero e ispezionata con un lieve fischio.",
    "weapon_shop.run_by": "Armeria, gestita da {0} il troll",
    "weapon_shop.shopkeeper_greeting": "Un troll grasso sbuca barcollando da una stanza sul retro e ti saluta.",
    "weapon_shop.gold_suffix": " oro.",
    "weapon_shop.align_discount": "  Il tuo allineamento {0} ti concede uno sconto del {1}%!",
    "weapon_shop.align_markup": "  Il tuo allineamento {0} causa un sovrapprezzo del {1}%.",
    "weapon_shop.world_discount": "  Eventi Mondiali: sconto del {0}% attivo!",
    "weapon_shop.world_markup": "  Eventi Mondiali: aumento prezzi del {0}%!",
    "weapon_shop.bbs_one_hand": "Una Mano",
    "weapon_shop.bbs_two_hand": "Due Mani",
    "weapon_shop.bbs_bows": "Archi",
    "weapon_shop.bbs_shields": "Scudi",
    "weapon_shop.bbs_sell": "endere",
    "weapon_shop.bbs_auto_buy": "cquisto-Auto",
    "weapon_shop.bbs_return": "itorno",
    "weapon_shop.stat_2h_pow": " (2M, Pot:{0})",
    "weapon_shop.stat_1h_pow": " (1M, Pot:{0})",
    "weapon_shop.stat_shield": " (Scudo, CA:{0}, Blocco:{1}%)",
    "weapon_shop.cat_one_handed": "Armi a Una Mano",
    "weapon_shop.cat_two_handed": "Armi a Due Mani",
    "weapon_shop.cat_bows": "Archi",
    "weapon_shop.cat_shields": "Scudi",
    "weapon_shop.current_shield_stats": " (CA:{0}, Blocco:{1}%, Valore:{2})",
    "weapon_shop.current_weapon_stats": " (Pot:{0}, Valore:{1})",
    "weapon_shop.page_info": "Pagina {0}/{1} - {2} oggetti totali",
    "weapon_shop.class_restriction": "Restrizione di classe: {0}",
    "weapon_shop.requires_level": "Richiede livello {0} (sei livello {1})",
    "weapon_shop.warning_cant_equip": "Attenzione: {0}",
    "weapon_shop.buy_prompt_name": "Comprare {0} per ",
    "weapon_shop.incl_tax": " (tasse incluse)",
    "weapon_shop.was_price": " (era {0})",
    "weapon_shop.equip_or_inventory": "[E]quipaggia o [I]nventario? ",
    "weapon_shop.sell_main_hand": "Mano Principale: {0}",
    "weapon_shop.sell_off_hand": "Mano Secondaria: {0}",
    "weapon_shop.sell_for_gold": " - Vendi per {0} oro",
    "weapon_shop.inv_wp": " (PA:{0})",
    "weapon_shop.inv_shield": " (Scudo)",
    "weapon_shop.bulk_sell_confirm": "Vendere {0} oggetto/i per {1} oro? (S/N): ",
    "weapon_shop.sell_confirm": "Vendere {0} per {1} oro? (S/N): ",
    "weapon_shop.autobuy_already_best": "Nessun potenziamento disponibile. La tua {0} (PA: {1}) è già",
    "weapon_shop.autobuy_best_afford": "la migliore arma che puoi permetterti con {0} oro.",
    "weapon_shop.autobuy_no_affordable": "Nessuna arma accessibile trovata. Hai {0} oro.",
    "weapon_shop.autobuy_current": "Arma attuale: {0} (PA: {1})",
    "weapon_shop.autobuy_your_gold": "Il tuo oro: {0}",
    "weapon_shop.autobuy_wp": "  Potenza Arma: {0} (attuale: {1}, +{2})",
    "weapon_shop.autobuy_price": "  Prezzo: {0} oro",
    "weapon_shop.autobuy_gold_after": "  (Oro dopo l'acquisto: {0})",
    "weapon_shop.autobuy_purchased": "Comprata e equipaggiata {0}!",
    "weapon_shop.autobuy_failed": "Fallito: {0}",
    "weapon_shop.autobuy_no_more": "Nessun altro potenziamento arma accessibile disponibile.",
    "anchor_road.header": "VIA DELL'ANCORA - Crocevia dei Destini",
    "anchor_road.bounty": "Tabellone Taglie",
    "anchor_road.gang_war": "Guerra tra Bande",
    "anchor_road.gauntlet": "La Sfida",
    "anchor_road.claim_town": "Conquista la Città",
    "anchor_road.flee_control": "Abbandona il Controllo della Città",
    "anchor_road.prison": "Terreni della Prigione",
    "anchor_road.status": "Stato",
    "anchor_road.return": "Torna in Città",
    "anchor_road.jailbreak": "Tenta un'Evasione (salva un prigioniero)",
    "anchor_road.view_prisoners": "Vedi Prigionieri",
    "team_corner.rankings": "Classifica Squadre",
    "team_corner.info": "Info sulle Squadre",
    "team_corner.your_status": "Stato della tua Squadra",
    "team_corner.password": "Cambia Password",
    "team_corner.examine": "Esamina Membro",
    "team_corner.create": "Crea Squadra",
    "team_corner.join": "Unisciti a una Squadra",
    "team_corner.quit": "Lascia la Squadra",
    "team_corner.apply": "Fai Domanda di Adesione",
    "team_corner.recruit_npc": "Recluta PNG",
    "team_corner.sack": "Espelli Membro",
    "team_corner.equip": "Equipaggia Membro",
    "team_corner.message": "Messaggio ai Compagni",
    "team_corner.resurrect": "Resuscita Compagno",
    "team_corner.recruit_player": "Recluta Alleato Giocatore",
    "team_corner.battle": "Battaglia tra Squadre (Guerra)",
    "team_corner.headquarters": "Quartier Generale",
    "team_corner.return": "Torna alla Via Principale",
    "team_corner.equip_item": "Equipaggia oggetto dal tuo inventario",
    "team_corner.unequip_item": "Rimuovi oggetto da loro",
    "team_corner.take_all": "Prendi tutto il loro equipaggiamento",
    "team_corner.done": "Fatto / Torna",
    "team_corner.challenge": "Sfida una Squadra",
    "team_corner.war_history": "Cronologia Guerre",
    "team_corner.upgrade": "Potenzia Struttura",
    "team_corner.deposit": "Deposita Oro",
    "team_corner.withdraw": "Preleva Oro",
    "settlement.header": "I  SOBBORGHI",
    "settlement.building_status": "STATO EDIFICI",
    "settlement.proposals": "PROPOSTE DELL'INSEDIAMENTO",
    "settlement.desc_small_1": "Un pugno di rifugi improvvisati si raccoglie in una radura oltre le porte.",
    "settlement.desc_small_2": "Il fumo dei fuochi da campo sale pigramente. I coloni ti osservano con cauta speranza.",
    "settlement.desc_medium_1": "Una comunità in crescita ha messo radici qui. Edifici grezzi fiancheggiano",
    "settlement.desc_medium_2": "sentieri fangosi. Il suono di martelli e conversazioni riempie l'aria.",
    "settlement.desc_large_1": "Un vivace insediamento di frontiera si estende davanti a te. Quello che era",
    "settlement.desc_large_2": "iniziato come poche tende sta diventando una vera città, viva di propositi.",
    "settlement.stats": "  Coloni: {0}/{1}    Tesoro: {2} oro",
    "settlement.buildings_label": "  Edifici:",
    "settlement.in_progress": "In Corso",
    "settlement.pct_complete": " {0}% completato",
    "settlement.building_active": " [COSTRUZIONE...]",
    "settlement.settlers_label": "  Coloni: ",
    "settlement.settlers_more": " (+{0} altri)",
    "settlement.settler_built_label": "  Costruiti dai Coloni:",
    "settlement.proposal_active": "  ** {0} propone: {1} **",
    "settlement.proposal_votes": "     Voti: {0} a favore / {1} contro ({2} turni rimanenti)",
    "settlement.menu_view_sr": "  V. Vedi Dettagli Edifici",
    "settlement.menu_contribute_sr": "  C. Contribuisci Oro",
    "settlement.menu_proposals_sr": "  P. Proposte",
    "settlement.menu_view": "  [V] Vedi Dettagli Edifici",
    "settlement.menu_contribute": "  [C] Contribuisci Oro",
    "settlement.menu_proposals": "  [P] Proposte",
    "settlement.menu_services_sr": "  S. Servizi dell'Insediamento",
    "settlement.menu_services": "  [S] Servizi dell'Insediamento",
    "settlement.menu_return_sr": "  R. Torna alla Via Principale",
    "settlement.menu_return": "  [R] Torna alla Via Principale",
    "settlement.bbs_header": "=== I SOBBORGHI ===",
    "settlement.bbs_stats": "Coloni: {0}/{1}  Tesoro: {2}o",
    "settlement.bbs_building": "  Edificio: {0} ({1}/{2})",
    "settlement.bbs_proposal": "  Proposta: {0} ({1}S/{2}N)",
    "settlement.bbs_menu": "[V]Dettagli [C]Contribuisci [P]Proposte [S]Servizi [R]Torna",
    "settlement.return_to_main": "Torni attraverso le porte verso la Via Principale.",
    "settlement.building_name_tier": "  {0} — {1}",
    "settlement.building_desc": "    {0}",
    "settlement.building_progress": "    Progresso: [{0}] {1}/{2} oro ({3}%)",
    "settlement.your_gold": "Il tuo oro: {0}",
    "settlement.contribute_prompt": "Quanto vuoi contribuire (o 0 per annullare): ",
    "settlement.not_that_much_gold": "Non hai tutto quell'oro!",
    "settlement.contribute_success": "Contribuisci {0} oro all'insediamento.",
    "settlement.total_contributions": "Contributi totali: {0} oro",
    "settlement.no_services": "Nessun servizio disponibile ancora. L'insediamento ha bisogno di più edifici!",
    "settlement.available_services": "Servizi Disponibili:",
    "settlement.cancel_sr": "  0. Annulla",
    "settlement.cancel": "  [0] Annulla",
    "settlement.tavern_desc_1": "I coloni condividono un pasto abbondante con te accanto al fuoco della taverna.",
    "settlement.tavern_desc_2": "Ti senti ispirato e pronto per la battaglia.",
    "settlement.gained_xp_buff": "  Ottenuto: +{0}% PE per {1} combattimenti!",
    "settlement.shrine_spent": "Il potere curativo del santuario è esaurito per oggi. Torna domani.",
    "settlement.already_full_hp": "Sei già a piena salute.",
    "settlement.shrine_desc_1": "Il custode del santuario ti guida in un'alcova tranquilla.",
    "settlement.shrine_desc_2": "Un calore si diffonde attraverso di te mentre le tue ferite si rimarginano.",
    "settlement.healed_hp": "  Curato {0} PV! (PV: {1}/{2})",
    "settlement.palisade_desc_1": "Le guardie dell'insediamento condividono le loro tecniche di pattuglia con te.",
    "settlement.palisade_desc_2": "Ti senti più consapevole delle minacce e meglio preparato a difenderti.",
    "settlement.gained_defense_buff": "  Ottenuto: +{0}% difesa per {1} combattimenti!",
    "settlement.workshop_desc": "L'artigiano dell'insediamento esamina il tuo oggetto con attenzione...",
    "settlement.workshop_identified": "  Identificato: {0}!",
    "settlement.watchtower_prompt": "Quale piano del dungeon esplorare? (1-100): ",
    "settlement.watchtower_report": "Gli esploratori della torre di guardia riferiscono sul Piano {0}:",
    "settlement.watchtower_creatures": "  Creature avvistate: Mostri di livello ~{0}",
    "settlement.watchtower_example": "  Esempio: {0}",
    "settlement.watchtower_special": "  Speciale: {0}",
    "settlement.special_floor_15": "Un sigillo antico irradia potere qui.",
    "settlement.special_floor_25": "La presenza di Maelketh aleggia qui.",
    "settlement.special_floor_30": "Un sigillo attende un pretendente degno.",
    "settlement.special_floor_40": "Il dominio di Veloura si estende qui.",
    "settlement.special_floor_45": "Un sigillo brilla nell'oscurità.",
    "settlement.special_floor_55": "Thorgrim sorveglia queste profondità.",
    "settlement.special_floor_60": "Un sigillo antico pulsa di energia.",
    "settlement.special_floor_70": "Le ombre di Noctura dominano.",
    "settlement.special_floor_80": "Un sigillo di tremendo potere attende.",
    "settlement.special_floor_85": "Lo splendore di Aurelion acceca.",
    "settlement.special_floor_95": "Terravok scuote la terra.",
    "settlement.special_floor_99": "L'ultimo sigillo chiama.",
    "settlement.special_floor_100": "Manwe, l'Eterno, attende.",
    "settlement.council_claimed_today": "Hai già riscosso la tua parte oggi. Torna domani.",
    "settlement.treasury_empty": "Il tesoro comune è vuoto.",
    "settlement.council_elder": "L'anziano del consiglio conta la tua parte dal tesoro.",
    "settlement.received_gold": "  Ricevuto: {0} oro!",
    "settlement.remaining_treasury": "  Tesoro rimanente: {0} oro",
    "settlement.market_desc": "I coloni espongono le loro merci su rozzi tavoli di legno.",
    "settlement.market_coming_soon": "(Commercio al mercato in arrivo in un futuro aggiornamento!)",
    "settlement.active_proposal": "  Proposta Attiva: {0}",
    "settlement.proposed_by": "  Proposta da: {0}",
    "settlement.proposal_effect": "  Effetto: {0}",
    "settlement.proposal_support_oppose": "  A favore: {0}    Contro: {1}    (Si risolve in {2} turni)",
    "settlement.endorse_sr": "  E. Appoggia ({0} oro, +2 supporto)",
    "settlement.endorse": "  [E] Appoggia ({0} oro, +2 supporto)",
    "settlement.oppose_sr": "  O. Opponi (+2 contro)",
    "settlement.oppose": "  [O] Opponi (+2 contro)",
    "settlement.no_active_proposals": "  Nessuna proposta attiva. I coloni sono concentrati su altri lavori.",
    "settlement.settler_built_structures": "  Strutture Costruite dai Coloni:",
    "settlement.back_sr": "  0. Indietro",
    "settlement.back": "  [0] Indietro",
    "settlement.already_voted": "Hai già espresso il tuo voto su questa proposta.",
    "settlement.need_gold_endorse": "Ti servono {0} oro per appoggiare una proposta.",
    "settlement.endorse_success": "Appoggi la proposta! La tua influenza convince i coloni.",
    "settlement.oppose_success": "Ti esprimi contro la proposta. I coloni riconsiderano.",
    "settlement.service_not_available": "Questo servizio non è ancora disponibile.",
    "settlement.arena_desc": "Ti alleni con i combattenti dell'arena, imparando le loro tecniche aggressive.",
    "settlement.gained_damage_buff": "  Ottenuto: +{0}% danno per {1} combattimenti!",
    "settlement.thieves_desc": "I ladri condividono i loro segreti per trovare tesori nascosti.",
    "settlement.gained_gold_buff": "  Ottenuto: +{0}% oro trovato per {1} combattimenti!",
    "settlement.mystic_depleted": "L'energia del cerchio mistico è esaurita per oggi. Torna domani.",
    "settlement.mana_already_full": "Il tuo mana è già al massimo.",
    "settlement.mystic_mana_desc": "Il cerchio mistico vibra di potere. Energia arcana fluisce in te.",
    "settlement.restored_mp": "  Ripristinato {0} PM! (PM: {1}/{2})",
    "settlement.mystic_hp_desc": "Il cerchio mistico pulsa di energia risanatrice, guarendo le tue ferite.",
    "settlement.restored_hp": "  Ripristinato {0} PV! (PV: {1}/{2})",
    "settlement.prison_desc": "I carcerieri ti insegnano come individuare e evitare le trappole.",
    "settlement.gained_trap_resist": "  Ottenuto: -{0}% danno da trappole per {1} combattimenti!",
    "settlement.scouts_prompt": "Quale piano del dungeon esplorare? (gli esploratori controlleranno 3 piani): ",
    "settlement.scouts_report": "Gli esploratori si disperdono e riferiscono:",
    "settlement.scouts_floor": "  Piano {0}: Livello ~{1} ({2})",
    "settlement.library_desc": "Passi del tempo a studiare tomi antichi nella biblioteca.",
    "settlement.gained_library_xp": "  Ottenuto: +{0}% PE per {1} combattimenti!",
    "settlement.herbalist_claimed": "L'erborista ti ha già dato un'erba oggi. Torna domani.",
    "settlement.herbalist_max_carry": "Stai già trasportando il numero massimo di {0}.",
    "settlement.herbalist_desc": "L'erborista fruga tra fasci di erbe essiccate e ti porge qualcosa.",
    "settlement.herbalist_received": "  Ricevuto: {0}!",
    "settlement.gambling_header": "La Sala da Gioco risuona di dadi e applausi.",
    "settlement.gambling_gold_info": "Il tuo oro: {0}  (Puntata massima: {1})",
    "settlement.gambling_prompt": "Quanto oro vuoi scommettere? (0 per uscire): ",
    "settlement.gambling_walk_away": "Ti allontani dai tavoli.",
    "settlement.gambling_win": "I dadi ti sorridono! Vinci {0} oro!",
    "settlement.gambling_lose": "Sfortuna! Perdi {0} oro.",
    "settlement.gambling_remaining": "Oro rimanente: {0}",
    "settlement.oracle_intro": "L'oracolo velata parla con voce distante:",
    "settlement.oracle_hint_0": "Più scendi in profondità, più grandi sono le ricompense... e i pericoli.",
    "settlement.oracle_hint_1": "Sigilli antichi attendono ai piani 15, 30, 45, 60, 80 e 99.",
    "settlement.oracle_hint_2": "Antichi Dèi sorvegliano i piani 25, 40, 55, 70, 85, 95 e 100.",
    "settlement.oracle_hint_3": "I compagni trovati alla Locanda hanno le loro missioni e storie.",
    "settlement.oracle_hint_4": "Il favore del Re può essere guadagnato... o preso con la forza.",
    "settlement.oracle_hint_5": "Alcune armi portano incantamenti che si rivelano in battaglia.",
    "settlement.oracle_hint_6": "L'insediamento diventa più forte con ogni edificio completato.",
    "settlement.oracle_hint_7": "I coloni PNG costruiscono ciò che il loro cuore desidera. Coloni diversi, città diverse.",
    "settlement.oracle_hint_8": "Le erbe raccolte dal tuo giardino possono ribaltare le sorti della battaglia.",
    "settlement.oracle_hint_9": "Ci sono molteplici finali da scoprire. Diventerai un dio?",
    "wilderness.header": "LA SELVA",
    "wilderness.intro_line1": "Oltre le porte della città, terre selvagge si estendono in ogni direzione.",
    "wilderness.intro_line2": "Pericolo e scoperta attendono chi è abbastanza audace da avventurarsi.",
    "wilderness.expeditions_remaining": "Spedizioni rimanenti: {0}/{1}",
    "wilderness.level_req": " (Livello {0}+)",
    "wilderness.any_level": " (Qualsiasi livello)",
    "wilderness.locked": " BLOCCATO",
    "wilderness.locked_bracket": " [BLOCCATO]",
    "wilderness.discoveries_sr": "  D. Scoperte ({0} trovate, {1} rivisite rimanenti)",
    "wilderness.discoveries_visual": "  [D] Scoperte ({0} trovate, {1} rivisite rimanenti)",
    "wilderness.return_sr": "  R. Torna alla Via Principale",
    "wilderness.return_visual": "  [R] Torna alla Via Principale",
    "wilderness.bbs_header": "=== LA SELVA ===",
    "wilderness.bbs_expeditions": "Spedizioni: {0}/{1}",
    "wilderness.bbs_discoveries": "[D] Scoperte ({0}, {1} rivisite)",
    "wilderness.bbs_return": "[R] Torna",
    "wilderness.return_city": "Torni attraverso le porte della città.",
    "wilderness.region_too_dangerous": "{0} è troppo pericoloso per te. (Richiede livello {1})",
    "wilderness.too_tired": "Sei troppo stanco per un'altra spedizione oggi. Riposati e riprova domani.",
    "wilderness.monster_emerges": "Un {0} emerge da {1}!",
    "wilderness.bonus_gold": "Perlustrando la zona trovi {0} oro aggiuntivo.",
    "wilderness.search_area": "Perlustra la zona con attenzione...",
    "wilderness.found_healing_herb": "Trovata: Erba Curativa (+1)",
    "wilderness.found_ironbark": "Trovata: Radice di Corteccia Ferrea (+1)",
    "wilderness.found_firebloom": "Trovato: Petalo di Fiorefiamma (+1)",
    "wilderness.found_starbloom": "Trovata: Essenza di Fiorestella (+1)",
    "wilderness.found_swiftthistle": "Trovato: Cardorapido (+1)",
    "wilderness.herb_pouch_full": "La tua borsa delle erbe è piena.",
    "wilderness.eat_foraged_food": "Mangi il cibo raccolto. (+{0} PV)",
    "wilderness.already_healthy": "Uno spuntino piacevole, ma sei già in salute.",
    "wilderness.medicinal_plant": "La pianta medicinale ristabilisce la tua salute. (+{0} PV)",
    "wilderness.worth_gold": "Vale {0} oro!",
    "wilderness.better_luck": "Più fortuna la prossima volta.",
    "wilderness.discover_ruins": "Scopri delle rovine nella natura selvaggia...",
    "wilderness.ruins_search_or_leave": "[S] Cerca tesori   [L] Lascia stare",
    "wilderness.ruins_gold_found": "Trovi {0} oro nascosto nelle rovine!",
    "wilderness.ruins_potion_found": "Trovi anche una polverosa pozione curativa!",
    "wilderness.ruins_trap": "Una trappola nascosta scatta! Subisci {0} danni!",
    "wilderness.ruins_picked_clean": "Le rovine sono già state saccheggiate.",
    "wilderness.ruins_leave": "Prosegui, lasciando le rovine indisturbate.",
    "wilderness.traveler_talk_or_leave": "[T] Parla   [L] Vai via",
    "wilderness.traveler_sell_potion": "Il {0} offre di venderti una pozione curativa per {1} oro.",
    "wilderness.traveler_buy_or_decline": "[Y] Compra   [N] Rifiuta",
    "wilderness.traveler_purchased": "Acquistata!",
    "wilderness.traveler_shares_wisdom": "Il {0} condivide la saggezza delle terre selvagge.",
    "wilderness.traveler_lore_line1": "\"I livelli più profondi del dungeon custodiscono tesori inimmaginabili,",
    "wilderness.traveler_lore_line2": " ma gli Antichi Dèi dormono laggiù. Procedi con cautela.\"",
    "wilderness.traveler_shares_food": "Il {0} condivide cibo e bevande. (+{1} PV)",
    "wilderness.traveler_nod_leave": "Annuisci e prosegui per la tua strada.",
    "wilderness.shrine_discover": "Scopri un santuario antico sul bordo della strada.",
    "wilderness.shrine_symbols": "Simboli antichi brillano debolmente nella pietra.",
    "wilderness.shrine_pray_or_leave": "[P] Prega   [L] Vai via",
    "wilderness.shrine_warm_light": "Una luce calda ti avvolge. Le tue ferite si chiudono e la tua mente si rischiara.",
    "wilderness.shrine_hp": "  +{0} PV",
    "wilderness.shrine_mana": "  +{0} Mana",
    "wilderness.shrine_str": "Il santuario ti benedice con la forza. (+1 FOR)",
    "wilderness.shrine_dex": "Il santuario ti benedice con l'agilità. (+1 DES)",
    "wilderness.shrine_wis": "Il santuario ti benedice con la saggezza. (+1 SAG)",
    "wilderness.shrine_xp": "Conoscenza antica fluisce in te. (+{0} PE)",
    "wilderness.shrine_peace": "Senti un momento di pace, ma nient'altro accade.",
    "wilderness.shrine_pass": "Passi oltre il santuario.",
    "wilderness.discovery_star": "★ SCOPERTA ★",
    "wilderness.discovery_found": "Hai trovato: {0}",
    "wilderness.discovery_revisit_hint": "(Puoi rivisitare questo luogo dal menu Scoperte)",
    "wilderness.discoveries_title": "Le tue Scoperte",
    "wilderness.discoveries_title_visual": "═══ Le tue Scoperte ═══",
    "wilderness.no_discoveries": "Non hai ancora scoperto nulla.",
    "wilderness.no_discoveries_hint": "Esplora la natura selvaggia per trovare luoghi nascosti.",
    "wilderness.discoveries_return_sr": "0. Torna",
    "wilderness.discoveries_return_visual": "[0] Torna",
    "wilderness.discoveries_visit_prompt": "Visita: ",
    "wilderness.revisits_exhausted": "Hai già rivisitato abbastanza scoperte per oggi.",
    "news.header": "BACHECA DELLE NOTIZIE",
    "news.empty": "La bacheca è vuota. Nulla da segnalare.",
    "news.items_count": "{0} notizie",
    "news.page_of": "Pagina {0} di {1} ({2} notizie)",
    "news.next_page": "[INVIO] Pagina successiva, [R] Torna: ",
    "news.breadcrumb": "Via Principale > Bacheca Notizie",
    "prison.voice_darkness": "VOCE NELL'OSCURITÀ",
    "team_corner.header": "ANGOLO DELLE SQUADRE AVVENTURIERE",
    "team_corner.rankings_header": "CLASSIFICA SQUADRE",
    "team_corner.npc_recruit_header": "RECLUTAMENTO PNG",
    "team_corner.player_recruit_header": "RECLUTA ALLEATO GIOCATORE",
    "team_corner.equip_header": "EQUIPAGGIA MEMBRO DELLA SQUADRA",
    "team_corner.wars_header": "GUERRE TRA SQUADRE",
    "team_corner.members": "Membri della Squadra",
    "team_corner.choose_opponent": "SCEGLI SQUADRA AVVERSARIA",
    "team_corner.your_team_wins": "LA TUA SQUADRA VINCE!",
    "team_corner.your_team_loses": "LA TUA SQUADRA PERDE!",
    "team_corner.war_history_header": "CRONOLOGIA GUERRE",
    "team_corner.facilities": "Strutture",
    "marketplace.header_visual": "CASA D'ASTE",
    "marketplace.listings": "CASA D'ASTE — INSERZIONI",
    "marketplace.your_status": "CASA D'ASTE — IL TUO STATO",
    "marketplace.atmo_desc1": "Un'ampia sala di pietra levigata, con vetrine e bancarelle ",
    "marketplace.atmo_desc2": "di legno",
    "marketplace.atmo_desc3": ". ",
    "marketplace.atmo_busy": "L'aria vibra di voci contrattanti e tintinnio di borse.",
    "marketplace.atmo_few": "Alcuni mercanti stanno dietro i loro banchi, richiamando i passanti.",
    "marketplace.atmo_empty": "I banchi sono perlopiù vuoti oggi, la polvere si posa sui ripiani.",
    "marketplace.grimjaw": "Grimjaw",
    "marketplace.grimjaw_desc": ", il banditore mezzorco, incombe dietro il banco delle iscrizioni. ",
    "marketplace.grimjaw_yawn": "Sbadiglia.",
    "marketplace.grimjaw_slow": "\"Giornata lenta. Vendi o mi fai solo perdere tempo?\"",
    "marketplace.grimjaw_few": "\"Ho qualcosa che vale la pena vedere. Dai un'occhiata al tabellone.\"",
    "marketplace.grimjaw_plenty": "\"Tanta merce oggi! Avanti, avanti!\"",
    "marketplace.listings_label": "  Inserzioni: ",
    "marketplace.player_count": "{0} giocatore",
    "marketplace.npc_count": "{0} PNG",
    "marketplace.total_value": "   Valore totale: ",
    "marketplace.what_to_do": "Cosa vorresti fare?",
    "marketplace.bbs_hall": " La sala d'aste di Grimjaw. ",
    "marketplace.bbs_listings": " inserzioni",
    "marketplace.bbs_worth": " valore ",
    "marketplace.bbs_empty": " La sala d'aste di Grimjaw è perlopiù vuota. \"Giornata lenta.\"",
    "marketplace.sr_title": "CASA D'ASTE",
    "marketplace.sr_listings": "Inserzioni: {0} ({1} giocatore, {2} PNG)",
    "marketplace.sr_total_value": "Valore totale: {0} {1}",
    "marketplace.sr_your_gold": "Il tuo oro: {0}",
    "marketplace.board_empty1": "  La bacheca è spoglia. Qualche vecchio chiodo sporge dal sughero.",
    "marketplace.board_empty2": "\n  Grimjaw scrolla le spalle. \"Niente in affissione. Torna dopo, o metti qualcosa tu.\"",
    "marketplace.col_num": "#",
    "marketplace.col_item": "Oggetto",
    "marketplace.col_price": "Prezzo",
    "marketplace.col_seller": "Venditore",
    "marketplace.col_age": "Tempo",
    "marketplace.age_new": "nuovo",
    "marketplace.npc_tag": "(PNG)",
    "marketplace.nothing_available": "Niente disponibile per l'acquisto.",
    "marketplace.buy_prompt": "Inserisci il numero dell'oggetto da comprare (o Q per annullare): ",
    "marketplace.cant_buy_own": "Non puoi comprare la tua stessa inserzione!",
    "marketplace.cant_afford": "Non puoi permetterti quell'oggetto!",
    "marketplace.no_longer_available": "Oggetto non più disponibile.",
    "marketplace.transaction_complete": "Transazione completata! L'oggetto è ora tuo.",
    "marketplace.equipped_weapon": "Equipaggiata {0}! (+{1} potenza arma)",
    "marketplace.equipped_armor": "Equipaggiata {0}! (+{1} potenza armatura)",
    "marketplace.transaction_failed": "Transazione fallita!",
    "marketplace.nothing_to_sell": "Non hai niente da vendere.",
    "marketplace.your_inventory": "Il tuo Inventario:",
    "marketplace.sell_prompt": "Inserisci il numero dell'oggetto da vendere (o Q per annullare): ",
    "marketplace.suggested_price": "\nPrezzo suggerito: {0} {1}",
    "marketplace.enter_price": "Inserisci il prezzo dell'oggetto (o premi Invio per il prezzo suggerito):",
    "marketplace.invalid_price": "Formato prezzo non valido.",
    "marketplace.item_listed": "Oggetto messo in vendita con successo!",
    "marketplace.your_listings": "  Le tue Inserzioni Attive:",
    "marketplace.nothing_listed": "  Non hai niente in vendita.",
    "marketplace.posted_today": "oggi",
    "marketplace.posted_ago": "{0}g fa",
    "marketplace.posted_label": "  (pubblicato {0})",
    "marketplace.market_overview": "  Panoramica del Mercato:",
    "marketplace.total_listings_label": "    Inserzioni totali: ",
    "marketplace.total_value_label": "    Valore totale:     ",
    "marketplace.your_gold_label": "    Il tuo oro:         ",
    "marketplace.menu_check": "ontrolla bacheca   ",
    "marketplace.menu_buy": "ompra oggetto        ",
    "marketplace.menu_add": "ggiungi oggetto",
    "marketplace.menu_status": "tato                 ",
    "marketplace.menu_return": "itorno",
    "marketplace.value_label": "Valore",
    "marketplace.bbs_browse": "Sfoglia",
    "marketplace.bbs_buy": "Compra",
    "marketplace.bbs_add": "Aggiungi",
    "marketplace.bbs_status": "Stato",
    "marketplace.bbs_return": "Torna",
    "quest.completed": "Missione Completata!",
    "quest.new": "Nuova Missione Disponibile!",
    "quest.reward": "Ricompensa: {0} oro, {1} PE",
    "quest.accepted": "Missione accettata!",
    "death.message": "Sei caduto in battaglia...",
    "death.xp_lost": "Perdi {0} punti esperienza!",
    "death.gold_lost": "Perdi {0} oro!",
    "death.revived": "Risorgerai al tempio con 1 PV...",
    "creation.header": "CREAZIONE PERSONAGGIO",
    "creation.welcome": "Benvenuto nel mondo medievale di Usurper...",
    "creation.enter_name": "Inserisci il nome del tuo personaggio:",
    "creation.name_known_as": "Questo è il nome con cui sarai conosciuto nel reame.",
    "creation.name_prompt": "Nome del personaggio: ",
    "creation.name_required": "Devi inserire un nome!",
    "creation.name_taken": "Quel nome è già in uso! Scegline un altro.",
    "creation.name_forbidden": "Mi dispiace, ma quel nome è già utilizzato.",
    "creation.name_confirm": "{0} è quello che vuoi? (S/n)",
    "creation.choose_display_name": "Scegli un nome per il tuo personaggio alternativo:",
    "creation.choose_display_online": "Scegli un nome per il personaggio (o premi Invio per usare il nome account):",
    "creation.creating": "Creazione personaggio: {0}",
    "creation.confirm": "Creare questo personaggio? (S/n): ",
    "creation.created": "Personaggio creato con successo!",
    "creation.entering": "Preparazione per entrare nel reame...",
    "creation.aborted": "Creazione personaggio annullata.",
    "creation.gender": "Sesso:",
    "creation.male": "(M)aschio",
    "creation.female": "(F)emmina",
    "creation.gender_prompt": "Scelta: ",
    "creation.gender_confirm_m": "Gioca un personaggio Maschile",
    "creation.gender_confirm_f": "Gioca un personaggio Femminile",
    "creation.gender_invalid": "Per favore scegli M o F.",
    "creation.choose_race": "Scegli la tua Razza:",
    "creation.choose_class": "Scegli la tua Classe (come {0}):",
    "creation.all_classes": "Tutte le classi",
    "creation.help": "Aiuto",
    "creation.abort": "Annulla",
    "creation.invalid_race": "Scelta non valida. Seleziona 0-9, H per aiuto, o A per annullare.",
    "creation.invalid_class": "Scelta non valida. Seleziona 0-{0}, H per aiuto, o A per annullare.",
    "creation.race_restricted": "Spiacente, {0} non può essere {1} {2}!",
    "creation.prestige_header": "CLASSI PRESTIGIO (NG+)",
    "creation.prestige_locked": "[Bloccata — richiede {0}]",
    "creation.preview.stats": "Statistiche:",
    "creation.preview.classes": "Classi:",
    "creation.preview.classes_all": "Tutte le classi disponibili",
    "creation.preview.special": "Speciale:",
    "creation.preview.none": "Nessuno",
    "creation.preview.regen": "Rigenerazione",
    "creation.preview.regen_desc": "Cura PV ogni turno",
    "creation.preview.poison_bite": "Morso Velenoso",
    "creation.preview.poison_desc": "Possibilità di avvelenare i nemici",
    "creation.preview.small_race": "No armatura Pesante (Piccola)",
    "creation.preview.be_race": "Essere {0}? [S]ì [N]o",
    "creation.preview.be_race_yn": "Essere {0}? (S/N): ",
    "creation.preview.be_class": "Essere {0} {1}? [S]ì [N]o",
    "creation.preview.be_class_yn": "Essere {0} {1}? (S/N): ",
    "creation.preview.mana": "Mana:",
    "creation.preview.mana_per_level": "+{0}/livello",
    "creation.preview.mana_none": "Nessuno",
    "creation.preview.mana_none_physical": "Nessuno (classe fisica)",
    "creation.preview.mana_grows": "+{0}/livello (cresce col livello)",
    "creation.preview.armor": "Armatura:",
    "creation.preview.armor_light": "Solo leggera",
    "creation.preview.armor_medium": "Leggera e Media",
    "creation.preview.armor_all": "Tutti i tipi",
    "creation.preview.strengths": "Punti di Forza:",
    "creation.preview.category.melee": "Combattente in Mischia",
    "creation.preview.category.hybrid": "Classe Ibrida",
    "creation.preview.category.magic": "Utilizzatore di Magia",
    "creation.preview.category.adventurer": "Avventuriero",
    "creation.preview.restricted": "Restrizioni:",
    "creation.difficulty.header": "SELEZIONA MODALITÀ DIFFICOLTÀ",
    "creation.difficulty.prompt": "Scegli la difficoltà (E/N/H/!): ",
    "creation.difficulty.easy_selected": "Modalità facile selezionata - goditi un'avventura rilassata!",
    "creation.difficulty.normal_selected": "Modalità normale selezionata - l'esperienza classica di Usurper!",
    "creation.difficulty.hard_selected": "Modalità difficile selezionata - preparati a una sfida!",
    "creation.difficulty.nightmare_header": "MODALITÀ INCUBO — MORTE PERMANENTE",
    "creation.difficulty.nightmare_desc1": "La morte è permanente. Il tuo salvataggio verrà",
    "creation.difficulty.nightmare_desc2": "cancellato se muori. Nessuna resurrezione.",
    "creation.difficulty.nightmare_desc3": "Nessuna pietà. Nessuna seconda possibilità.",
    "creation.difficulty.nightmare_confirm": "La morte è PERMANENTE. Sei SICURO? (s/N): ",
    "creation.difficulty.nightmare_sealed": "Il tuo destino è segnato. Che gli dèi abbiano pietà.",
    "creation.difficulty.nightmare_wise": "Una scelta saggia. Seleziona un'altra difficoltà.",
    "creation.difficulty.invalid": "Per favore scegli E, N, H o !.",
    "pantheon.divine_realm": "IL REAME DIVINO",
    "pantheon.divine_status": "STATO DIVINO",
    "pantheon.faithful_flock": "IL TUO GREGGE FEDELE",
    "pantheon.configure_favors": "CONFIGURA FAVORI DIVINI",
    "pantheon.divine_deeds": "AZIONI DIVINE",
    "pantheon.immortal_rankings": "IL PANTHEON — CLASSIFICA DEGLI IMMORTALI",
    "pantheon.divine_mortal_news": "NOTIZIE DIVINE E MORTALI",
    "pantheon.renounce_immortality": "RINUNCIA ALL'IMMORTALITÀ",
    "level_master.milestone": "* TRAGUARDO RAGGIUNTO: Livello {0} *",
    "level_master.visions": "VISIONI NEL CRISTALLO",
    "level_master.help_ally": "AIUTA ALLEATO",
    "creation.welcome_to_usurper": "B E N V E N U T O   I N   U S U R P E R",
    "creation.welcome_to_realm": "B E N V E N U T O   N E L   R E A M E !",
    "anchor_road.bounty_collected": "TAGLIA RISCOSSA!",
    "anchor_road.gang_war_victory": "VITTORIA NELLA GUERRA TRA BANDE!",
    "anchor_road.gang_war_defeat": "SCONFITTA NELLA GUERRA TRA BANDE!",
    "anchor_road.gauntlet_champion": "CAMPIONE DELLA SFIDA!",
    "anchor_road.gauntlet_summary": "RIEPILOGO DELLA SFIDA",
    "armor_shop.sell_armor": "Vendi Armatura",
    "armor_shop.sell_for_gold": " - Vendi per {0} oro",
    "armor_shop.inventory_header": "[ INVENTARIO ]",
    "armor_shop.sell_prompt": "Vendere quale pezzo? ([A] tutto lo zaino, 0 per annullare): ",
    "armor_shop.no_sellable_armor": "Nessuna armatura vendibile nel tuo zaino.",
    "armor_shop.bulk_sell_confirm": "Vendere {0} oggetto/i per {1} oro? (S/N): ",
    "armor_shop.sell_confirm": "Vendere {0} per {1} oro? (S/N): ",
    "armor_shop.autobuy_already_best": "  {0}: {1} è già la migliore accessibile",
    "armor_shop.autobuy_no_affordable": "  {0}: Nessuna armatura accessibile trovata",
    "armor_shop.autobuy_current": "  Attuale: {0} (CA: {1})",
    "armor_shop.autobuy_current_empty": "  Attuale: (vuoto)",
    "armor_shop.autobuy_upgrade": "  Potenziamento: {0}",
    "armor_shop.autobuy_ac": "    Classe Armatura: {0} (+{1})",
    "armor_shop.autobuy_price": "    Prezzo: {0} oro",
    "armor_shop.autobuy_your_gold": "    Il tuo oro: {0}",
    "armor_shop.autobuy_opt_buy": "  [Y] Compra questa armatura",
    "armor_shop.autobuy_opt_skip": "  [N] Salta, mostra prossima opzione",
    "armor_shop.autobuy_opt_skip_slot": "  [S] Salta questo slot",
    "armor_shop.autobuy_opt_cancel": "  [C] Annulla acquisto automatico",
    "armor_shop.autobuy_purchased": "  ✓ Acquistata {0}!",
    "armor_shop.autobuy_cant_equip": "  ✗ Impossibile equipaggiare: {0}",
    "armor_shop.autobuy_no_more": "  Nessuna altra opzione per {0}.",
    "armor_shop.autobuy_skipping": "  Salto {0}.",
    "armor_shop.autobuy_cancelled": "  Acquisto automatico annullato.",
    "armor_shop.autobuy_invalid": "  Scelta non valida. Inserisci Y, N, S o C.",
    "armor_shop.autobuy_summary": "Acquistati {0} pezzi di armatura per {1} oro.",
    "sysop.console_header": "C O N S O L E   S Y S O P",
    "sysop.danger_reset": "!!! PERICOLO: RESET DEL GIOCO !!!",
    "sysop.new_version": "NUOVA VERSIONE DISPONIBILE",
    "sysop.update_success": "AGGIORNAMENTO SCARICATO CON SUCCESSO",
    "sysop.update_available": "AGGIORNAMENTO DISPONIBILE",
    "devmenu.header": "* MENU SVILUPPATORE *",
    "devmenu.ascended": "SEI ASCESO ALLA DIVINITÀ!",
    "devmenu.steam_reset": "RESET STATISTICHE STEAM (DEBUG)",
    "devmenu.narrative_debug": "DEBUG SISTEMI NARRATIVI",
    "anchor_road.menu_jailbreak": "Tenta un'Evasione (salva un prigioniero)",
    "anchor_road.menu_view_prisoners": "Vedi Prigionieri",
    "anchor_road.header_title": "VIA DELL'ANCORA - Crocevia dei Destini",
    "anchor_road.desc_red_fields": "I Campi Rossi si estendono a est, dove i guerrieri mettono alla prova il loro valore.",
    "anchor_road.desc_blood_glory": "Sangue e gloria attendono chi è abbastanza coraggioso da entrare.",
    "anchor_road.menu_challenges": "Sfide:",
    "anchor_road.menu_bounty_board": "Tabellone Taglie",
    "anchor_road.menu_gang_war_label": "Guerra tra Bande",
    "anchor_road.menu_gauntlet_label": "La Sfida",
    "anchor_road.menu_town_control": "Controllo della Città:",
    "anchor_road.menu_claim_town_label": "Conquista la Città",
    "anchor_road.menu_flee_control_label": "Abbandona il Controllo della Città",
    "anchor_road.menu_other": "Altro:",
    "anchor_road.menu_prison_grounds": "Terreni della Prigione",
    "anchor_road.menu_status_label": "Stato",
    "anchor_road.menu_return_town": "Torna in Città",
    "anchor_road.player_fights": "Duelli Giocatore: ",
    "anchor_road.fights_exhausted": "0 (esauriti)",
    "anchor_road.team_fights": "Scontri di Squadra: ",
    "anchor_road.your_team": "La tua Squadra: ",
    "anchor_road.controls_town_tag": " * CONTROLLA LA CITTÀ",
    "anchor_road.town_controlled_by": "Città Controllata Da: ",
    "anchor_road.bbs_desc": " I Campi Rossi si estendono a est. Sangue e gloria attendono i coraggiosi.",
    "anchor_road.bbs_fights": " Duelli:",
    "anchor_road.bbs_team": " Squadra:",
    "anchor_road.bbs_tfights": " ScontriS:",
    "anchor_road.bbs_turf": " *TERRIT*",
    "anchor_road.bbs_town": " Città:",
    "anchor_road.bbs_challenges": " Sfide:",
    "anchor_road.bbs_town_control": " Controllo Città:",
    "anchor_road.invalid_choice": "Scelta non valida! Scrivi 'look' per ridisegnare il menu.",
    "anchor_road.no_fights_left": "Non hai più duelli giocatore rimasti oggi!",
    "anchor_road.come_back_tomorrow": "Torna domani quando sarai riposato.",
    "anchor_road.scan_bounty_board": "Esamini il tabellone delle taglie alla ricerca di criminali ricercati...",
    "anchor_road.fights_remaining": "Duelli Giocatore Rimanenti: {0}",
    "anchor_road.no_bounties": "Nessuna taglia disponibile al momento.",
    "anchor_road.wanted_header": "RICERCATO - VIVO O MORTO:",
    "anchor_road.bounty_table_header": "{0} {1} {2} {3} {4}",
    "anchor_road.bounty_col_num": "#",
    "anchor_road.bounty_col_name": "Nome",
    "anchor_road.bounty_col_level": "Livello",
    "anchor_road.bounty_col_bounty": "Taglia",
    "anchor_road.bounty_col_crime": "Crimine",
    "anchor_road.crime_murder": "Omicidio",
    "anchor_road.crime_assault": "Aggressione",
    "anchor_road.crime_troublemaker": "Piantagrane",
    "anchor_road.hunt_prompt": "Cacciare quale bersaglio? (0 per annullare): ",
    "anchor_road.tracking_target": "Insegui {0}...",
    "anchor_road.fled_bounty": "Sei fuggito dallo scontro. La taglia resta non riscossa.",
    "anchor_road.bested_by_target": "{0} ti ha sconfitto! La taglia resta non riscossa.",
    "anchor_road.no_team_gang_war": "Devi far parte di una squadra per partecipare alle guerre tra bande!",
    "anchor_road.visit_team_corner": "Visita l'Angolo delle Squadre alla Locanda per creare o unirti a una squadra.",
    "anchor_road.no_team_fights": "Non hai più scontri di squadra rimasti oggi!",
    "anchor_road.no_rival_teams": "Nessuna squadra rivale trovata da sfidare!",
    "anchor_road.your_team_label": "La tua Squadra: {0}",
    "anchor_road.team_fights_remaining": "Scontri di Squadra Rimanenti: {0}",
    "anchor_road.rival_teams": "Squadre Rivali:",
    "anchor_road.rival_table_header": "{0} {1} {2} {3} {4}",
    "anchor_road.rival_col_num": "#",
    "anchor_road.rival_col_team": "Nome Squadra",
    "anchor_road.rival_col_members": "Membri",
    "anchor_road.rival_col_power": "Potenza",
    "anchor_road.rival_col_turf": "Territorio",
    "anchor_road.challenge_prompt": "Sfidare quale squadra? (0 per annullare): ",
    "anchor_road.team_challenges": "La tua squadra sfida {0}!",
    "anchor_road.defeat_one_by_one": "Devi sconfiggere i loro membri uno a uno!",
    "anchor_road.fight_header": "SCONTRO {0}/{1}",
    "anchor_road.face_opponent": "Affronti {0} (Livello {1} {2})!",
    "anchor_road.breath_recover": "Riprendi fiato e recuperi {0} PV.",
    "anchor_road.team_controls_town": "* LA TUA SQUADRA ORA CONTROLLA LA CITTÀ! *",
    "anchor_road.defeated_after": "Sei stato sconfitto dopo aver abbattuto {0} avversario{1}.",
    "anchor_road.partial_rewards": "Ricompense Parziali: {0} oro, {1} PE",
    "anchor_road.gauntlet_desc_1": "Affronta 10 ondate di mostri sempre più pericolosi.",
    "anchor_road.gauntlet_desc_2": "La tua salute e il mana si mantengono tra le ondate.",
    "anchor_road.gauntlet_desc_3": "Sopravvivi a tutte e 10 per ottenere il titolo di Campione della Sfida!",
    "anchor_road.gauntlet_min_level": "Devi essere almeno livello {0} per entrare nella Sfida.",
    "anchor_road.gauntlet_details": "Dettagli della Sfida:",
    "anchor_road.entry_fee": "Quota d'Ingresso: ",
    "anchor_road.your_gold": "Il tuo Oro: ",
    "anchor_road.your_hp": "I tuoi PV: ",
    "anchor_road.need_gold": "Ti servono {0} oro per entrare. Ne hai solo {1}.",
    "anchor_road.enter_gauntlet_prompt": "Entrare nella Sfida per {0} oro? (S/N): ",
    "anchor_road.come_back_later": "Decidi di tornare un'altra volta.",
    "anchor_road.gates_slam": "I cancelli di ferro si chiudono alle tue spalle.",
    "anchor_road.crowd_roars": "La folla ruggisce mentre entri nell'arena...",
    "anchor_road.wave_header": "ONDATA {0}/{1}",
    "anchor_road.opponent_label": "Avversario: ",
    "anchor_road.wave_complete": "Ondata {0} completata! +{1} oro, +{2} PE",
    "anchor_road.champion_bonus": "Bonus Campione: +{0} oro, +{1} PE!",
    "anchor_road.catch_breath": "Riprendi fiato... +{0} PV, +{1} Mana",
    "anchor_road.next_wave": "Premi Invio per la prossima ondata...",
    "anchor_road.flee_disgrace": "Fuggi dall'arena in disgrazia!",
    "anchor_road.collapse_arena": "Crolli nell'arena...",
    "anchor_road.waves_survived": "Ondate Sopravvissute: ",
    "anchor_road.gold_earned": "Oro Guadagnato: {0}",
    "anchor_road.xp_earned": "PE Guadagnati: {0}",
    "anchor_road.no_team_claim": "Devi far parte di una squadra per conquistare città!",
    "anchor_road.already_controls": "La tua squadra controlla già questa città!",
    "anchor_road.no_controller": "Nessuna squadra controlla attualmente questa città.",
    "anchor_road.claim_prompt": "Conquistare la città per la tua squadra? (S/N): ",
    "anchor_road.town_claimed": "* LA TUA SQUADRA ORA CONTROLLA LA CITTÀ! *",
    "anchor_road.rule_wisely": "Governa con saggezza, poiché i rivali arriveranno...",
    "anchor_road.town_controlled_info": "La città è attualmente controllata da: {0}",
    "anchor_road.must_defeat_gang_war": "Per conquistare la città, devi sconfiggere la squadra al comando nella Guerra tra Bande!",
    "anchor_road.use_gang_war": "Usa l'opzione (G)uerra tra Bande per sfidarli.",
    "anchor_road.no_town_control": "La tua squadra non controlla nessuna città!",
    "anchor_road.leave_town_open": "Questo lascerà la città aperta alla conquista di altre squadre.",
    "anchor_road.abandon_prompt": "Abbandonare il controllo? (S/N): ",
    "anchor_road.abandoned_control": "La tua squadra ha abbandonato il controllo della città.",
    "anchor_road.town_free": "La città è ora libera per chi la vuole...",
    "anchor_road.control_maintained": "Controllo della città mantenuto.",
    "anchor_road.approach_prison": "Ti avvicini alle mura minacciose della prigione...",
    "anchor_road.guards_patrol": "Le guardie pattugliano il perimetro, attente ai problemi.",
    "anchor_road.prison_options": "Opzioni:",
    "anchor_road.jailbreak_dangerous": "Le evasioni sono estremamente pericolose!",
    "anchor_road.end_up_in_prison": "Potresti finire in prigione tu stesso se ti beccano.",
    "anchor_road.proceed_jailbreak": "Procedere con l'evasione? (S/N): ",
    "anchor_road.sneak_past_guards": "Sgattaioli oltre le guardie e trovi un prigioniero!",
    "anchor_road.help_escape": "Lo aiuti a fuggire attraverso un passaggio segreto.",
    "anchor_road.prisoner_thanks": "Il prigioniero ti ringrazia e scompare nella notte.",
    "anchor_road.caught": "BECCATO!",
    "anchor_road.guards_spotted": "Le guardie ti hanno avvistato e dato la caccia!",
    "anchor_road.barely_escaped": "Sei scappato per un pelo, perdendo {0} PV nel processo.",
    "anchor_road.peer_through_bars": "Sbirci attraverso le sbarre di ferro...",
    "anchor_road.cells_empty": "Le celle della prigione sembrano vuote.",
    "anchor_road.prisoners_label": "Prigionieri:",
    "anchor_road.prisoner_info": "  {0} - Livello {1} {2}",
    "pantheon.menu_status": "Stato",
    "pantheon.menu_status_desc": "Visualizza le tue statistiche divine",
    "pantheon.menu_believers": "Credenti",
    "pantheon.menu_believers_desc": "Visualizza e gestisci il tuo gregge",
    "pantheon.menu_deeds": "Azioni Divine",
    "pantheon.menu_deeds_desc": "Compi interventi ({0} rimanenti)",
}
