translations = {
    "prison.vex_sewers1": "\"Andiamo. Conosco una via d'uscita. Ho costruito le fogne di questo posto",
    "prison.vex_sewers2": " per un lavoro una volta. Lunga storia.\"",
    "prison.vex_passages1": "Mentre vi muovete nei passaggi bui, lui parla.",
    "prison.vex_passages2": "È compulsivo — come se non sopportasse il silenzio.",
    "prison.vex_dying1": "\"Sto morendo, tra l'altro,\" menziona con noncuranza.",
    "prison.vex_dying2": "\"Malattia consuntiva. Mi resta forse un mese.\"",
    "prison.vex_dying3": "\"Quindi mi dico — tanto vale spenderlo facendo qualcosa di divertente.\"",
    "prison.vex_glance1": "Ti lancia un'occhiata, e solo per un istante,",
    "prison.vex_glance2": "la maschera cade. Vedi qualcosa di vero sotto le battute.",
    "prison.vex_tag_along": "\"Sembri interessante. Ti dispiace se vengo con te?\"",
    "prison.vex_joined": "{0} si è unito a te come compagno!",
    "prison.vex_warning_dying": "ATTENZIONE: Vex sta morendo. Il suo tempo è limitato.",
    "prison.vex_make_most": "Sfrutta al meglio i giorni che avete insieme.",
    "prison.vex_emerge": "Emergete dalle fogne nell'aria notturna.",
    "prison.vex_free": "Sei LIBERO!",
    "prison.vex_condition": "\"La condizione?\" Ride, ma c'è una nota amara.",
    "prison.vex_born1": "\"Ci sono nato. Malattia consuntiva. Nessuna cura.\"",
    "prison.vex_born2": "\"Ogni guaritore che ho visto dice la stessa cosa:\"",
    "prison.vex_born3": "\"'Mi dispiace, non possiamo fare nulla. Va' a goderti il tempo che ti resta.'\"",
    "prison.vex_lockpick": "Fa roteare il grimaldello tra le dita.",
    "prison.vex_best_thief1": "\"E così ho fatto. Sono diventato il miglior ladro del regno.\"",
    "prison.vex_best_thief2": "\"Ho rubato ai re. Saccheggiato templi. Borseggiato al mio stesso funerale.\"",
    "prison.vex_best_thief3": "\"...Quell'ultimo era una prova generale.\"",
    "prison.vex_personal_quest": "Missione Personale: {0}",
    "prison.vex_too_short": "\"La vita è troppo breve per prenderla sul serio. Fidati, lo so bene.\"",
    "prison.vex_escape_prompt": "Lasciarlo aiutarti a fuggire? (S/N): ",
    "prison.vex_suit_yourself": "\"Come vuoi. L'offerta resta valida se cambi idea.\"",
    "dormitory.list_sleepers": "ista dormienti       ",
    "dormitory.examine_menu": "samina          ",
    "dormitory.go_sleep_online": "ormi ({0}g, disconnetti)",
    "dormitory.go_sleep": "ormi",
    "dormitory.kill_sleeper": "ccidi un dormiente      ",
    "dormitory.wake_guests": "veglia ospiti      ",
    "dormitory.wake_guests_sp": "veglia gli ospiti     ",
    "dormitory.status_menu": "tato",
    "dormitory.status_menu_sp": "tato           ",
    "dormitory.return_anchor": "itorno a Via dell'Ancora",
    "dormitory.return_short": "itorno",
    "dormitory.sleeping_npc_tag": "[PNG ADDORMENTATO]",
    "dormitory.sleeping_player_tag": "[GIOCATORE ADDORMENTATO]",
    "dormitory.sleeping_tag": "[ADDORMENTATO]",
    "dormitory.press_enter": "\nPremi Invio...",
    "_comment_endings": "=== EndingsSystem.cs ===",
    "maint.already_running": "La manutenzione è già in corso!",
    "maint.already_in_progress": "La manutenzione è già in corso!",
    "maint.type": "Tipo di Manutenzione: {0}",
    "maint.datetime": "Data/Ora: {0}",
    "maint.last_maint": "Ultima Manutenzione: {0}",
    "maint.injections": "Iniezioni di Male...",
    "maint.processing_players": "Elaborazione registri giocatori...",
    "maint.player_complete": "Elaborazione giocatori completata.",
    "maint.all_done": "TUTTE LE AZIONI SONO COMPIUTE!",
    "maint.completed": "Manutenzione completata con successo.",
    "maint.next_maint": "Prossima manutenzione: {0}",
    "duel.waiting_opponent": "In attesa che l'avversario accetti...",
    "duel.opponent_no_response": "L'avversario non ha risposto in tempo!",
    "duel.say_prompt": "Dì qualcosa: ",
    "duel.cancelled_connection": "Il duello è stato annullato per problemi di connessione.",
    "wizard.commands_title": "Comandi del Mago",
    "wizard.online_title": "Maghi Online",
    "wizard.locations_title": "Posizioni dei Giocatori",
    "wizard.audit_title": "Registro Controlli del Mago",
    "_comment_companion": "=== Sistema Compagni ===",
    "companion.not_ready": "{0} non pensa che tu sia pronto.",
    "companion.joins_party": "{0} si unisce al tuo gruppo!",
    "companion.waits_tavern": "{0} ti aspetterà alla taverna.",
    "companion.equipment_returned": "\nL'equipaggiamento di {0} ({1} oggetto/i) è stato restituito al tuo inventario.",
    "companion.equipment_returned_notify": "L'equipaggiamento di {0} ({1} oggetto/i) è stato restituito al tuo inventario.",
    "companion.grief_onset": "  Un'ondata di dolore ti travolge. (Fase: Negazione)",
    "companion.grief_combat_warning": "  Il tuo lutto influenzerà le tue prestazioni in combattimento.",
    "companion.new_companion_header": "N U O V O   C O M P A G N O",
    "companion.role_label": "  Ruolo: {0}",
    "companion.abilities_label": "  Abilità: {0}",
    "companion.press_enter_welcome": "\nPremi Invio per dargli il benvenuto...",
    "companion.fallen_header": "CADUTO",
    "companion.goes_still": "  {0} si immobilizza.",
    "companion.gone": "  È finita. Se ne sono andati.",
    "companion.is_dead": "  {0} è morto.",
    "companion.no_coming_back": "  Non si torna indietro da questa.",
    "companion.press_enter_ready": "  Premi Invio quando sei pronto...",
    "companion.xp_header": "PE Compagni (+{0} ciascuno):",
    "companion.reached_level": "  {0} ha raggiunto il livello {1}!",
    "_comment_training_extra": "=== Sistema Addestramento (chiavi aggiuntive) ===",
    "training.reset_skill_confirm": "Resettare {0} a {1}?",
    "training.reset_cost": "  Costo: {0} oro",
    "training.reset_refund": "  Rimborso: {0} punti addestramento",
    "training.confirm_prompt": "Confermi? (S/N) > ",
    "training.skill_reset_header": "RESET ABILITÀ",
    "training.skill_reset_result": "{0} è stato resettato a {1}.",
    "training.gold_spent": "  -{0} oro",
    "training.points_refunded": "  +{0} punti addestramento rimborsati",
    "training.total_points": "  Punti addestramento totali: {0}",
    "training.reset_all_header": "RESET COMPLETO ADDESTRAMENTO",
    "training.reset_all_desc": "Questo resetterà TUTTE le competenze ai valori predefiniti.",
    "training.reset_all_result": "Tutte le competenze sono state resettate.",
    "_comment_puzzle": "=== Sistema Enigmi ===",
    "puzzle.hint_or_quit": "[Scrivi 'hint' per un indizio, o 'quit' per arrenderti]",
    "puzzle.step_back": "Ti ritiri dall'enigma, incapace di risolverlo.",
    "puzzle.diff_simple": "Semplice",
    "puzzle.diff_moderate": "Moderato",
    "puzzle.diff_challenging": "Impegnativo",
    "puzzle.diff_difficult": "Difficile",
    "puzzle.diff_legendary": "Leggendario",
    "puzzle.difficulty_label": "Difficoltà: {0}",
    "puzzle.attempts_remaining": "Tentativi rimanenti: {0}",
    "puzzle.levers_label": "  Leve:",
    "puzzle.lever_pulled": "[TIRATA]",
    "puzzle.lever_empty": "[------]",
    "puzzle.enter_lever": "Inserisci il numero della leva da tirare (1-{0}):",
    "puzzle.current_alignment": "  Allineamento attuale:",
    "puzzle.panel_label": "    Pannello {0}: {1}",
    "puzzle.available_symbols": "  Simboli disponibili: {0}",
    "puzzle.enter_symbol": "Inserisci: [numero pannello] [simbolo] (es., '1 sun'):",
    "puzzle.torches_label": "  Torce:",
    "puzzle.torch_lit": "* ACCESA *  ",
    "puzzle.torch_unlit": "  SPENTA  ",
    "puzzle.torch_label": "    Torcia {0}: ",
    "puzzle.enter_torch": "Inserisci il numero della torcia da attivare (1-{0}):",
    "puzzle.available_numbers": "  Numeri disponibili:",
    "puzzle.selected": "  Selezionati: {0} = {1}",
    "puzzle.target_sum": "  Somma obiettivo: {0}",
    "puzzle.enter_number": "Inserisci un numero da aggiungere/rimuovere, o 'submit' quando sei pronto:",
    "puzzle.watch_sequence": "  Osserva la sequenza attentamente!",
    "puzzle.sequence_hidden": "  (La sequenza verrà nascosta dopo l'inizio)",
    "puzzle.press_enter_begin": "Premi Invio quando sei pronto per iniziare...",
    "puzzle.current_state": "  Stato attuale: {0}",
    "puzzle.options": "  Opzioni: {0}",
    "puzzle.hint_header": "INDIZIO:",
    "puzzle.no_hints": "Nessun indizio disponibile per questo enigma.",
    "puzzle.solved_header": "E N I G M A   R I S O L T O !",
    "puzzle.xp_gained": "Guadagni {0} punti esperienza!",
    "puzzle.whisper_echo": "Mentre il meccanismo si sblocca, un sussurro riecheggia:",
    "puzzle.wave_quote": "L'onda che smette di lottare trova la via di casa...",
    "puzzle.reset_sound": "L'enigma si resetta con un suono stridulo.",
    "puzzle.trap_damage": "Una trappola si attiva! Subisci {0} danni!",
    "puzzle.attempts_left": "{0} tentativi rimanenti.",
    "puzzle.exhausted": "Hai esaurito tutti i tentativi. L'enigma resta irrisolto.",
    "_comment_spell_learning": "=== Sistema Apprendimento Incantesimi ===",
    "spell_learning.no_magic": "Solo le professioni magiche possono apprendere incantesimi qui.",
    "spell_learning.header": "BIBLIOTECA DEGLI INCANTESIMI",
    "spell_learning.your_quickbar": "  La tua Barra Rapida:",
    "spell_learning.empty_slot": "  [{0}] --- vuoto ---",
    "spell_learning.known_unequipped": "  Incantesimi Conosciuti (non nella barra rapida):",
    "spell_learning.available_learn": "  Disponibili per l'Apprendimento:",
    "spell_learning.locked": "  Bloccati (livello troppo basso):",
    "spell_learning.locked_requires": "Richiede Lv{0}",
    "spell_learning.menu_sr": "1-9. Equipaggia o cambia slot, C. Svuota slot, A. Riempimento auto",
    "spell_learning.menu_sr_2": "L seguito da numero per apprendere (es. L5), F seguito da numero per dimenticare, X. Esci",
    "spell_learning.menu_visual": "[1-9] Equipaggia/cambia slot  [C] Svuota slot  [A] Riempimento auto",
    "spell_learning.menu_visual_2": "[L#] Apprendi incantesimo (es. L5)  [F#] Dimentica incantesimo  [X] Esci",
    "spell_learning.auto_filled": "Barra rapida riempita automaticamente!",
    "spell_learning.clear_which": "Svuotare quale slot? (1-9): ",
    "spell_learning.removed_slot": "Rimosso {0} dallo slot {1}.",
    "spell_learning.invalid_spell": "Livello incantesimo non valido!",
    "spell_learning.need_level": "Devi essere livello {0} per apprendere questo incantesimo!",
    "spell_learning.already_known": "Conosci già {0}!",
    "spell_learning.learned_slot": "Hai appreso {0}! (aggiunto allo slot {1})",
    "spell_learning.learned_full": "Hai appreso {0}! (barra rapida piena — equipaggia manualmente)",
    "spell_learning.dont_know": "Non conosci quell'incantesimo!",
    "spell_learning.forgot": "Dimentichi {0}.",
    "spell_learning.no_spells_equip": "Nessun incantesimo conosciuto da equipaggiare! Apprendi altri incantesimi prima.",
    "spell_learning.slot_has": "Lo slot {0} contiene: {1}. Scegli un sostituto:",
    "spell_learning.pick_spell": "Scegli un incantesimo per lo slot {0}:",
    "spell_learning.cancel": "Annulla",
    "spell_learning.equipped_slot": "{0} equipaggiato nello slot {1}!",
    "_comment_music_shop_extra": "=== Negozio di Musica — chiavi aggiuntive ===",
    "music_shop.bbs_buy_instruments": "cquista Strumenti",
    "music_shop.bbs_performance": "sibizione",
    "music_shop.bbs_lore_songs": "anti della Tradizione",
    "music_shop.bbs_talk_melodia": "arla con Melodia",
    "music_shop.bbs_return": "itorno",
    "music_shop.pow_value": " (Pot:{0}, Valore:{1})",
    "music_shop.song_price": "  {0} oro",
    "music_shop.melodia_own_inshop": "Melodia esita, poi suona qualcosa che non suonava da molto tempo.",
    "music_shop.melodia_own_adv": "Cadence prende il liuto con cautela. \"Melodia ha scritto questo pezzo. Me l'ha insegnato prima di partire.\"",
    "music_shop.melodia_own_dead": "Le mani di Cadence tremano leggermente. \"Era il suo. L'ultimo canto che mi ha insegnato.\"",
    "music_shop.recruit_curious_smile": "Melodia alza lo sguardo dal liuto e ti rivolge un sorriso curioso.",
    "music_shop.recruit_new1": "\"Sei nuovo da queste parti, vero? Il dungeon non ha ancora avuto",
    "music_shop.recruit_new2": "modo di lasciarti il segno.\"",
    "music_shop.recruit_new3": "Pizzica un accordo gentile.",
    "music_shop.recruit_new4": "\"Torna quando avrai visto un po' più di mondo.\"",
    "music_shop.recruit_mid1": "\"Cominci a muoverti come qualcuno che è stato",
    "music_shop.recruit_mid2": "là sotto. Lo vedo dal modo in cui cammini — un po' più",
    "music_shop.recruit_mid3": "cauto, un po' meno sicuro.\"",
    "music_shop.recruit_mid4": "Inclina la testa, studiandoti.",
    "music_shop.recruit_mid5": "\"Continua così. Hai l'aspetto di qualcuno con una storia",
    "music_shop.recruit_mid6": "che vale la pena raccontare.\"",
    "music_shop.recruit_high1": "\"Sei stato impegnato. Sai, le notizie girano — i muri hanno",
    "music_shop.recruit_high2": "orecchie, e così gli strumenti.\"",
    "music_shop.recruit_high3": "Le sue dita trovano una melodia malinconica sulle corde del liuto.",
    "music_shop.recruit_high4": "\"Facevo quello che fai tu. Una parte di me lo rimpiange terribilmente.\"",
    "music_shop.recruit_high5": "Scuote la testa. \"Non ancora. Ma presto, credo.\"",
    "music_shop.recruit_ready1": "Melodia posa il liuto e ti guarda intensamente.",
    "music_shop.recruit_ready2": "\"Ho sentito sussurri delle tue avventure nel dungeon.",
    "music_shop.recruit_ready3": "I mostri che hai affrontato, gli dèi che hai incontrato...\"",
    "music_shop.recruit_ready4": "Si sporge in avanti, gli occhi brillanti di curiosità.",
    "music_shop.recruit_ready5": "\"Viaggiavo con gli avventurieri, sai. Prima che cadessero.",
    "music_shop.recruit_ready6": "Cronacavo le loro gesta in canzoni. Ogni vittoria, ogni sconfitta.\"",
    "music_shop.recruit_ready7": "\"Dimmi — lasceresti che una barda ti accompagni? Ti prometto che sono più",
    "music_shop.recruit_ready8": "utile di quanto sembri. I miei canti possono guarire, ispirare, e... beh,",
    "music_shop.recruit_ready9": "la nota discordante giusta può frantumare la concentrazione di un mostro.\"",
    "music_shop.recruit_ready10": "Lancia un'occhiata a Cadence, che annuisce con entusiasmo.",
    "music_shop.recruit_ready11": "\"Non preoccuparti per il negozio. Cadence è pronta a gestire",
    "music_shop.recruit_ready12": "questo posto da sola da un pezzo ormai. Vero, cara?\"",
    "music_shop.recruit_ready13": "Cadence sorride. \"Vai! Terrò gli strumenti accordati.\"",
    "music_shop.recruit_join_prompt": "Vuoi che Melodia si unisca al tuo gruppo? [S/N]",
    "music_shop.recruit_success1": "Melodia si illumina e afferra il suo strumento.",
    "music_shop.recruit_success2": "\"Questa diventerà la canzone più bella di sempre! Andiamo!\"",
    "music_shop.recruit_success3": "Cadence saluta da dietro il bancone mentre uscite insieme.",
    "music_shop.recruit_decline": "Melodia annuisce comprensiva.",
    "_comment_church_extra": "=== Chiesa — chiavi aggiuntive ===",
    "_comment_online": "Sistema Gioco Online",
    "online.header": "GIOCO ONLINE",
    "online.connect_desc": "  Connettiti al server online di Usurper Reborn.",
    "online.separate_saves": "  Il tuo personaggio online è salvato sul server — separato dai salvataggi locali.",
    "online.bbs_auto_login": "  Verrai connesso automaticamente con il tuo nome utente BBS.",
    "online.login_or_create": "  Effettuerai l'accesso o creerai un account dopo la connessione.",
    "online.server_label": "Server: ",
    "online.menu_connect": "Connetti",
    "online.menu_back": "Torna al Menu Principale",
    "online.connecting_encrypted": "  Connessione a {0}:{1} (crittografata)...",
    "online.connected_ssh": "  Connesso (crittografia SSH)!",
    "online.ssh_failed": "  Connessione SSH fallita: {0}",
    "online.server_down": "  Il server potrebbe essere spento o irraggiungibile.",
    "online.connection_failed": "  Connessione fallita: {0}",
    "online.error": "  Errore: {0}",
    "online.connecting_telnet": "  Connessione a {0}:{1} (telnet)...",
    "online.connection_timed_out": "  Connessione scaduta.",
    "online.connected": "  Connesso!",
    "online.authenticating_as": "  Autenticazione come {0}...",
    "online.lost_connection": "  Connessione al server persa.",
    "online.auth_failed": "  Autenticazione fallita: {0}",
    "online.auth_failed_no_response": "  Autenticazione fallita: nessuna risposta dal server.",
    "online.auto_provision_hint": "  Il server potrebbe aver bisogno di --auto-provision abilitato per il passthrough BBS.",
    "online.authenticated": "  Autenticato!",
    "online.authenticated_prompt": "  Autenticato! ",
    "online.starting_session": "  Avvio sessione di gioco...",
    "online.logging_in_as": "  Accesso come {0}...",
    "online.logged_in": "  Accesso effettuato!",
    "online.saved_login_failed": "  Accesso salvato fallito: {0}",
    "online.login_manually": "  Effettua l'accesso manualmente.",
    "online.account_login": "  Accesso Account",
    "online.login_existing": "Accedi con account esistente",
    "online.register_new": "Registra nuovo account",
    "online.quit": "Esci",
    "online.username_prompt": "Nome utente: ",
    "online.password_prompt": "Password: ",
    "online.choose_username": "Scegli un nome utente: ",
    "online.username_length": "  Il nome utente deve essere di 2-20 caratteri.",
    "online.choose_password": "Scegli una password: ",
    "online.password_length": "  La password deve essere di almeno 4 caratteri.",
    "online.confirm_password": "Conferma password: ",
    "online.passwords_no_match": "  Le password non corrispondono.",
    "online.server_closed": "  Il server ha chiuso la connessione.",
    "online.save_credentials_prompt": "Salvare le credenziali per la prossima volta? (S/N): ",
    "online.credentials_saved": "  Credenziali salvate.",
    "online.unexpected_response": "  Risposta inattesa dal server.",
    "online.too_many_attempts": "  Troppi tentativi falliti. Ritorno al menu.",
    "online.disconnect_hint": "  Premi Ctrl+] per disconnetterti.",
    "online.disconnected": "  Disconnesso dal server.",
    "_comment_quest_rewards": "Sistema Missioni — Ricompense",
    "quest.standing_improved": "  La tua reputazione con {0} è migliorata!",
    "quest.reward_xp": "  Ricompensa: {0} punti esperienza!",
    "quest.reward_gold": "  Ricompensa: {0} oro!",
    "quest.reward_potions": "  Ricompensa: {0} pozioni curative!",
    "quest.reward_potions_capped": "  Ricompensa: {0} pozioni curative! (limite a {1})",
    "quest.reward_darkness": "  Ricompensa: {0} punti oscurità!",
    "quest.reward_chivalry": "  Ricompensa: {0} punti cavalleria!",
    "quest.hand_over_item": "  Consegni il tuo {0} alla Gilda dei Mercanti.",
    "_comment_intimacy": "Sistema Intimità",
    "intimacy.header_encounter": "INCONTRO INTIMO",
    "intimacy.header_moment": "MOMENTO INTIMO",
    "intimacy.blessed_news": "LIETA NOTIZIA!",
    "intimacy.connection_perfect": "Una connessione perfetta. Tu e {0} siete in completa armonia.",
    "intimacy.connection_strong": "Una connessione forte. Tu e {0} vi comprendete bene.",
    "intimacy.connection_pleasant": "Un incontro piacevole. Stai ancora imparando cosa piace a {0}.",
    "intimacy.connection_awkward": "Un incontro imbarazzante. Tu e {0} non siete ancora in sintonia.",
    "intimacy.lovers_bliss": "Ti senti rafforzato dal vostro legame. (Estasi degli Amanti: +10% danno/difesa per 5 combattimenti)",
    "intimacy.fade_first_time": "Tu e {0} condividete un momento intimo insieme",
    "intimacy.fade_first_time2": "Gli occhi di {0} incontrano i tuoi con nervosa eccitazione.",
    "intimacy.fade_familiar": "Tu e {0} condividete un momento tenero e intimo insieme.",
    "intimacy.fade_familiar2": "La familiarità tra voi lo rende ancora più dolce.",
    "intimacy.fade_later": "Più tardi, giacete insieme in un silenzio confortevole.",
    "intimacy.fade_later2": "{0} appoggia la {1} testa contro di te, appagato.",
    "intimacy.fade_bond_stronger": "Il vostro legame è diventato più forte.",
    "intimacy.mood_tender": "Un'atmosfera tenera e amorevole riempie l'aria...",
    "intimacy.mood_passionate": "La passione crepita tra voi come un fulmine...",
    "intimacy.mood_rough": "Il desiderio puro vi guida entrambi con urgenza...",
    "intimacy.mood_playful": "Risate e provocazioni lasciano spazio a qualcosa di più...",
    "intimacy.mood_kinky": "L'anticipazione di piaceri proibiti aleggia pesante...",
    "intimacy.mood_romantic": "Luce di candela e promesse sussurrate preparano la scena...",
    "intimacy.mood_quick": "Non c'è tempo per le formalità — solo bisogno...",
    "intimacy.mood_default": "Il momento è arrivato...",
    "intimacy.phase_anticipation": "ANTICIPAZIONE",
    "intimacy.phase_exploration": "ESPLORAZIONE",
    "intimacy.phase_escalation": "ESCALATION",
    "intimacy.phase_climax": "CULMINE",
    "intimacy.phase_afterglow": "BAGLIORE",
    "intimacy.anticipation_alone": "La porta si chiude alle tue spalle, e improvvisamente sei solo con {0}.",
    "intimacy.anticipation_turns": "{0} si volta verso di te, gli occhi scuri di desiderio.",
    "intimacy.how_begin": "Come inizi?",
    "intimacy.choice_slow": "Prendila con calma — assapora il momento",
    "intimacy.choice_pull_close": "Avvicinali subito a te",
    "intimacy.choice_let_lead": "Lascia che prendano l'iniziativa",
    "intimacy.what_whisper": "Cosa gli sussurri?",
    "intimacy.whisper_beautiful": "\"Sei così bello/a...\"",
    "intimacy.whisper_need_you": "\"Ho bisogno di te. Adesso.\"",
    "intimacy.whisper_tell_me": "\"Dimmi cosa vuoi...\"",
    "intimacy.what_say": "Cosa dici?",
    "intimacy.say_stay": "\"Resta con me stanotte.\"",
    "intimacy.say_amazing": "\"È stato incredibile.\"",
    "intimacy.say_hold_close": "*Non dire nulla, tienili stretti*",
    "intimacy.reaction_matched": "Gli occhi di {0} si illuminano. È esattamente ciò che {1} voleva.",
    "intimacy.reaction_unmatched": "{0} sorride, assecondando la tua iniziativa.",
    "intimacy.time_passes": "Il tempo scorre in un silenzio confortevole...",
    "intimacy.weeks_later": "Alcune settimane dopo...",
    "intimacy.pregnancy_partner_tells": "{0} ti prende le mani, un sorriso misterioso sul {1} volto.",
    "intimacy.pregnancy_partner_tells2": "{0}... devo dirti una cosa.",
    "intimacy.pregnancy_partner_belly": "Ti posa la mano sul {0} ventre.",
    "intimacy.pregnancy_announcement": "Avremo un bambino.",
    "intimacy.pregnancy_player_feeling": "Ti sei sentito strano ultimamente. Diverso.",
    "intimacy.pregnancy_player_sickness": "Quando {0} nota le tue nausee mattutine, {1} impallidisce.",
    "intimacy.pregnancy_partner_asks": "Sei... noi siamo...?",
    "intimacy.pregnancy_player_nods": "Annuisci, con le lacrime agli occhi. \"Avremo un bambino.\"",
    "intimacy.baby_boy": "maschietto",
    "intimacy.baby_girl": "femminuccia",
    "intimacy.baby_born": "Dopo nove mesi, un sano {0} è nato!",
    "intimacy.baby_named": "Lo/La chiami {0}: {1}",
    "intimacy.pronoun_him": "lui",
    "intimacy.pronoun_her": "lei",
    "intimacy.family_grown": "La tua famiglia è cresciuta. Visita l'Angolo dell'Amore per vedere i tuoi figli.",
    "_comment_character_creation": "Sistema Creazione Personaggio",
    "character_creation.bbs_login": "Accesso BBS",
    "character_creation.account": "Account",
    "character_creation.easy_label": "acile",
    "character_creation.normal_label": "ormale",
    "character_creation.hard_label": "ifficile",
    "character_creation.nightmare_label": "Incubo",
    "character_creation.note": "Nota",
    "character_creation.unavailable": "NON DISPONIBILE",
    "character_creation.stat_roll": "TIRO STATISTICHE",
    "character_creation.rolled_attributes": "I tuoi attributi ottenuti:",
    "character_creation.stat_desc_hp": "La tua forza vitale",
    "character_creation.stat_desc_str": "Bonus danno in mischia",
    "character_creation.stat_desc_def": "Riduce i danni subiti",
    "character_creation.stat_desc_sta": "Riserva abilità combattimento",
    "character_creation.stat_desc_agi": "Probabilità di schivata, attacchi extra",
    "character_creation.stat_desc_dex": "Probabilità di colpire, colpi critici",
    "character_creation.stat_desc_con": "PV bonus, resistenza al veleno",
    "character_creation.stat_desc_int": "Danno incantesimi, riserva mana",
    "character_creation.stat_desc_wis": "Efficienza mana, resistenza magica",
    "character_creation.stat_desc_cha": "Prezzi nei negozi, reazioni dei PNG",
    "character_creation.stat_desc_mana": "Risorsa per incantesimi",
    "character_creation.stat_desc_mana_grows": "Cresce con i livelli",
    "character_creation.total_stats": "Statistiche Totali",
    "character_creation.rerolls_remaining": "Rilanci rimanenti: {0}",
    "character_creation.accept_stats": "(A)ccetta queste statistiche",
    "character_creation.reroll_stats": "(R)ilancia per nuove statistiche",
    "character_creation.stats_accepted": "Statistiche accettate!",
    "character_creation.final_roll": "Questo è il tuo ultimo tiro!",
    "character_creation.rerolling": "Rilancio statistiche...",
    "character_creation.choose_accept_reroll": "Scegli (A)ccetta o (R)ilancia.",
    "character_creation.no_rerolls": "Nessun rilancio rimanente — queste sono le tue statistiche finali!",
    "character_creation.press_enter_accept": "Premi Invio per accettare e continuare...",
    "character_creation.summary_header": "RIEPILOGO PERSONAGGIO",
    "character_creation.sex": "Sesso",
    "character_creation.male": "Maschio",
    "character_creation.female": "Femmina",
    "character_creation.age": "Età",
    "character_creation.appearance": "ASPETTO",
    "character_creation.height": "Altezza",
    "character_creation.weight": "Peso",
    "character_creation.eyes": "Occhi",
    "character_creation.hair": "Capelli",
    "character_creation.skin": "Pelle",
    "character_creation.starting_resources": "RISORSE INIZIALI",
    "character_creation.race_info_header": "INFORMAZIONI RAZZA",
    "character_creation.class_info_header": "INFORMAZIONI CLASSE",
    "character_creation.race_desc.human": "Equilibrato in tutto. Può essere qualsiasi classe.",
    "character_creation.race_desc.hobbit": "Piccolo ma agile. Eccellenti ladri e ranger.",
    "character_creation.race_desc.elf": "Aggraziato e magico. Eccellenti maghi e chierici.",
    "character_creation.race_desc.half_elf": "Versatile come gli umani. Può essere qualsiasi classe.",
    "character_creation.race_desc.dwarf": "Forte e resistente. Ottimi guerrieri, ma diffidano della magia.",
    "character_creation.race_desc.troll": "Bruti massicci con rigenerazione naturale.",
    "character_creation.race_desc.orc": "Combattenti aggressivi con capacità magiche limitate.",
    "character_creation.race_desc.gnome": "Piccoli e astuti. Ottimi maghi, scarsi combattenti pesanti.",
    "character_creation.race_desc.gnoll": "Cacciatori in branco con morso velenoso.",
    "character_creation.race_desc.mutant": "Caotici e imprevedibili. Possono essere qualsiasi classe.",
    "character_creation.race_desc.unknown": "Lignaggio sconosciuto.",
    "character_creation.class_desc.warrior": "Combattenti forti, maestri delle armi. Equilibrati e affidabili.",
    "character_creation.class_desc.barbarian": "Combattenti selvaggi con forza e resistenza incredibili.",
    "character_creation.class_desc.paladin": "Guerrieri sacri della virtù. Forti in combattimento e nello spirito.",
    "character_creation.class_desc.ranger": "Boscaioli e segugi. Combattenti equilibrati con abilità di sopravvivenza.",
    "character_creation.class_desc.assassin": "Assassini letali, maestri della furtività e dei colpi critici.",
    "character_creation.class_desc.bard": "Supporto al gruppo con i canti. Il CAR scala il danno. I canti potenziano tutto il gruppo.",
    "character_creation.class_desc.jester": "Ingannatore caotico. Il CAR scala il danno. Fortuna del Burlone: effetti casuali in combattimento.",
    "character_creation.class_desc.magician": "Maestro dell'arcano. Maestria Arcana: +15% danno incantesimi. Miglior incantatore offensivo.",
    "character_creation.class_desc.sage": "Studiosi e saggi utilizzatori di magia. Le più profonde riserve di mana.",
    "character_creation.class_desc.cleric": "Guaritori e utilizzatori di magia sacra. Devoti alla fede e alla saggezza.",
    "character_creation.class_desc.alchemist": "Scienziati lanciatori di bombe. L'INT scala il danno. Maestria Pozioni: +50% guarigione.",
    "character_creation.class_desc.unknown": "Un avventuriero dalla vocazione sconosciuta.",
    "character_creation.class_str.warrior": "PV, FOR, DIF, COS alti. Mischia equilibrata.",
    "character_creation.class_str.barbarian": "PV, FOR, STA, COS più alti. Potenza bruta.",
    "character_creation.class_str.paladin": "PV, FOR, STA, COS alti. Resistente e onorevole.",
    "character_creation.class_str.ranger": "Buona STA, DES. Versatile in tutto.",
    "character_creation.class_str.assassin": "DES migliore. FOR e AGI alte per le imboscate.",
    "character_creation.class_str.bard": "Buon CAR, DES. Equilibrato in tutte le statistiche.",
    "character_creation.class_str.jester": "AGI e CAR migliori. Fortuna del Burlone: danno bonus, schivata o stamina.",
    "character_creation.class_str.magician": "INT migliore. Maestria Arcana +15% danno incantesimi.",
    "character_creation.class_str.sage": "SAG e INT migliori. Riserva mana più profonda (50).",
    "character_creation.class_str.cleric": "Buona SAG e CAR. Magia curativa e mana.",
    "character_creation.class_str.alchemist": "SAG e INT migliori. CAR alto per il commercio.",
    "character_creation.class_str.unknown": "Punti di forza sconosciuti.",
    "_comment_betrayal": "=== Sistema Tradimento ===",
    "betrayal.header_sacrifice": "U N   S A C R I F I C I O",
    "betrayal.header_betrayal": "T R A D I M E N T O",
    "betrayal.header_forgiveness": "P E R D O N O",
    "betrayal.header_revenge": "V E N D E T T A",
    "betrayal.turns_to_face": "{0} si volta verso di te.",
    "betrayal.eyes_changed": "Qualcosa nei loro occhi è cambiato.",
    "betrayal.understand_reasons": "[Cominci a comprendere le loro ragioni...]",
    "betrayal.sacrifice_not_malice": "Non era malizia. Era amore.",
    "betrayal.sacrifice_ultimate_price": "Un amore disposto a pagare il prezzo più alto.",
    "betrayal.perhaps_not_end": "Forse... non deve essere la fine.",
    "betrayal.understanding_bridge": "La comprensione potrebbe ancora colmare questo abisso.",
    "betrayal.wounds_too_deep": "Alcune ferite sono troppo profonde per guarire.",
    "betrayal.broken_not_mended": "Ciò che è spezzato non sempre può essere riparato.",
    "betrayal.ocean_understanding": "Una comprensione lontana si agita dentro di te...",
    "betrayal.ocean_wave_crashes": "L'onda che si infrange su di te faceva parte dello stesso oceano.",
    "betrayal.cannot_forgive": "Alcuni tradimenti non possono essere perdonati.",
    "betrayal.conditions_not_met": "Le condizioni per il perdono non sono ancora state soddisfatte.",
    "betrayal.path_to_redemption": "Via verso la redenzione: {0}",
    "betrayal.forgive_release": "Perdonando, ti liberi dal peso del risentimento.",
    "betrayal.wave_forgives_shore": "L'onda perdona la riva per averla infranta.",
    "betrayal.approach_npc": "Ti avvicini a {0}.",
    "betrayal.flinch_expecting": "Si ritraggono, aspettandosi rabbia. Aspettandosi giustizia.",
    "betrayal.forgive_understand": "Capisco perché hai fatto quello che hai fatto.",
    "betrayal.forgive_disagree": "Non sono d'accordo. Forse non lo sarò mai.",
    "betrayal.forgive_let_go": "Ma scelgo di lasciar andare questo peso.",
    "betrayal.eyes_widen": "Gli occhi di {0} si spalancano.",
    "betrayal.neither_speak": "Per un momento, nessuno dei due parla.",
    "betrayal.dont_deserve": "Io... non me lo merito.",
    "betrayal.perhaps_not": "Forse no. Ma raramente otteniamo ciò che meritiamo.",
    "betrayal.choose_to_give": "Otteniamo ciò che scegliamo di dare.",
    "betrayal.something_shifts": "Qualcosa cambia tra di voi.",
    "betrayal.not_reconciliation": "Non è riconciliazione. Non ancora.",
    "betrayal.door_now_open": "Ma una porta che era chiusa... ora è aperta.",
    "betrayal.path_vengeance": "Hai scelto il sentiero della vendetta.",
    "betrayal.eye_for_eye": "Occhio per occhio. Sangue per sangue.",
    "betrayal.falls_before_you": "{0} cade davanti a te.",
    "betrayal.no_plea_mercy": "Il loro ultimo respiro non porta alcuna supplica di pietà.",
    "betrayal.knew_coming": "Sapevano che sarebbe arrivato.",
    "betrayal.debt_paid": "Il debito è saldato.",
    "betrayal.weight_remains": "Ma il peso... il peso rimane.",
    "betrayal.violence_begets": "La violenza genera violenza. L'onda si infrange, ma l'oceano resta.",
    "_comment_grief": "=== Sistema Lutto ===",
    "grief.header_memories": "R I C O R D I",
    "grief.attempt_resurrect": "Tenti di resuscitare {0} usando {1}...",
    "grief.silence_answer": "Il silenzio è la tua unica risposta.",
    "grief.whisper_touches": "Un sussurro sfiora la tua mente:",
    "grief.cannot_unburn": "\"Non puoi disbruciare ciò che è bruciato.\"",
    "grief.ash_feeds_soil": "\"Ma la cenere nutre il terreno. Nuove cose crescono.\"",
    "grief.voice_clearer": "La voce è più chiara ora, gentile ma ferma:",
    "grief.voice_fades_echo": "\"Una voce svanisce, ma l'eco resta.\"",
    "grief.words_shaped_you": "\"Le loro parole ti hanno plasmato. Ti hanno cambiato.\"",
    "grief.you_are_echo": "\"Tu SEI il loro eco ora.\"",
    "grief.every_choice_carries": "\"Ogni scelta che fai li porta avanti.\"",
    "grief.voice_compassion": "La voce parla con infinita compassione:",
    "grief.river_not_mourn": "\"Un fiume non piange l'acqua che è passata.\"",
    "grief.river_flows_on": "\"Scorre, portando ciò che era in ciò che sarà.\"",
    "grief.grief_river_backward": "\"Il tuo dolore è il fiume che tenta di scorrere all'indietro.\"",
    "grief.rivers_one_direction": "\"Ma i fiumi si muovono in una sola direzione.\"",
    "grief.let_go_downstream": "\"Lasciali andare a valle.\"",
    "grief.waiting_at_sea": "\"Ti aspettano al mare.\"",
    "grief.voice_quiet_whisper": "La voce è quieta ora. Quasi un sussurro:",
    "grief.loved_them_hurts": "\"Li amavi. Per questo fa male.\"",
    "grief.hurt_is_price": "\"Il dolore non è un difetto. È il prezzo.\"",
    "grief.never_loved_at_all": "\"Avresti preferito non amare affatto?\"",
    "grief.change_permanent": "\"Ti hanno cambiato. Quel cambiamento è permanente.\"",
    "grief.they_are_immortal": "\"In questo senso, sono immortali.\"",
    "grief.stop_bringing_back": "\"Smetti di cercare di riportarli indietro.\"",
    "grief.start_carrying_forward": "\"Inizia a portarli avanti.\"",
    "grief.current_stage": "Fase attuale del lutto: {0}",
    "grief.days_grieving": "Giorni di lutto: {0}",
    "grief.grief_passed": "Il dolore è passato. Il ricordo resta.",
    "grief.effect_denial": "La tua negazione offusca la concentrazione.",
    "grief.effect_anger": "La rabbia potenzia i tuoi attacchi ma ti rende vulnerabile.",
    "grief.effect_bargaining": "La tua ricerca disperata ti distrae.",
    "grief.effect_depression": "Il peso della tristezza schiaccia il tuo spirito.",
    "grief.effect_acceptance": "Hai fatto pace con la perdita.",
    "grief.npc_wise_denial": "Vedo l'ombra della perdita su di te. Ma non sei ancora pronto ad affrontarla.",
    "grief.npc_wise_anger": "La tua rabbia brucia intensa. Usala, ma non lasciarti consumare.",
    "grief.npc_wise_bargaining": "Non si possono fare patti con la morte. Solo accettazione.",
    "grief.npc_wise_depression": "Il peso del dolore è pesante. Ma anche questo passerà.",
    "grief.npc_wise_acceptance": "Hai resistito alla tempesta. Ne sei uscito più forte.",
    "grief.npc_casual_denial": "Sembri... distratto. Va tutto bene?",
    "grief.npc_casual_anger": "Ehi, calma! Cos'è che ti ha fatto arrabbiare così?",
    "grief.npc_casual_bargaining": "Stai cercando qualcosa. Lo vedo. Cos'è?",
    "grief.npc_casual_depression": "Ehi... non hai un bell'aspetto. Vuoi parlarne?",
    "grief.npc_casual_acceptance": "C'è qualcosa di diverso in te. Più saggio, forse.",
    "grief.atmo_denial": "Giureresti di vedere il volto di {0} tra la folla. Ma quando guardi di nuovo, è sparito.",
    "grief.atmo_anger": "Il tuo sangue ribolle. Ogni nemico ti ricorda ciò che hai perso.",
    "grief.atmo_bargaining": "Se solo potessi tornare indietro. Cambiare le cose. Salvare {0}. Ci deve essere un modo...",
    "grief.atmo_depression": "Il mondo sembra grigio. L'assenza di {0} è un peso sul tuo petto.",
    "grief.atmo_acceptance": "Pensi a {0} e sorridi. Il dolore resta, ma non ti definisce più.",
    "_comment_moral": "=== Sistema Paradosso Morale ===",
    "moral.already_chosen": "Hai già fatto questa scelta.",
    "moral.header_choice": "U N A   S C E L T A   A T T E N D E",
    "moral.header_consequences": "C O N S E G U E N Z E",
    "moral.no_going_back": "Non si torna indietro.",
    "moral.enter_valid_choice": "Inserisci una scelta valida.",
    "moral.deeper_understanding": "[Una comprensione più profonda si agita...]",
    "_comment_seals": "=== Sistema dei Sette Sigilli ===",
    "seals.header_discovered": "* * *  S I G I L L O   S C O P E R T O  * * *",
    "seals.header_all_found": "T U T T I   I   S E T T E   S I G I L L I   T R O V A T I",
    "seals.already_found": "Hai già trovato il {0}.",
    "seals.xp_gained": "(+{0} Esperienza)",
    "seals.deep_understanding": "Una profonda comprensione si insedia nella tua anima...",
    "seals.progress": "Progresso Sigilli",
    "seals.progress_text": "Sigilli della Verità: {0}/7",
    "seals.resonate_power": "I sigilli risuonano di potere antico.",
    "seals.uncovered_history": "Hai svelato la storia completa degli dèi.",
    "seals.knowledge_understanding": "Questa conoscenza ti dona comprensione.",
    "seals.face_manwe_see_more": "Quando affronterai Manwe, vedrai più degli altri.",
    "seals.understand_choices": "Comprenderai le sue scelte. I suoi rimpianti.",
    "seals.true_ending_possible": "IL VERO FINALE È ORA POSSIBILE",
    "seals.fourth_path": "Se riesci a soddisfare certe condizioni, un quarto sentiero si apre.",
    "seals.not_destroyer": "Non distruttore. Non salvatore. Non ribelle.",
    "seals.something_new": "Qualcosa... di nuovo.",
    "_comment_artifact": "=== Sistema Artefatti ===",
    "artifact.header_acquired": "A R T E F A T T O   A C Q U I S I T O",
    "artifact.header_void_key": "L A   C H I A V E   D E L   V U O T O   A P P A R E",
    "artifact.already_possess": "Possiedi già {0}.",
    "artifact.lore": "STORIA",
    "artifact.powers_granted": "POTERI OTTENUTI",
    "artifact.special": "Speciale",
    "artifact.stirs_depths": "Qualcosa si agita nelle profondità della realtà...",
    "artifact.artifacts_resonate": "I sei artefatti che porti iniziano a risuonare.",
    "artifact.light_shadow_dance": "Luce e ombra danzano intorno a te.",
    "artifact.tear_opens": "Uno squarcio si apre nel tessuto dell'esistenza...",
    "artifact.void_key_desc1": "Dal vuoto tra i mondi, una chiave di puro nulla",
    "artifact.void_key_desc2": "si materializza davanti a te. È assenza che prende forma,",
    "artifact.void_key_desc3": "la sagoma della possibilità stessa.",
    "artifact.way_is_open": "\"La via è aperta.\"",
    "artifact.voice_whispers": "Una voce che non è voce sussurra nella tua mente.",
    "artifact.seek_prison": "\"Cerca la Prigione del Creatore al livello 100 del dungeon.\"",
    "artifact.journey_end": "\"Là, il tuo viaggio finirà. In un modo o nell'altro.\"",
    "_comment_ability": "=== Sistema Abilità di Classe ===",
    "ability.header": "ABILITÀ DI COMBATTIMENTO",
    "ability.your_quickbar": "La tua Barra Rapida",
    "ability.available": "Abilità Disponibili",
    "ability.locked": "Bloccate (livello troppo basso)",
    "ability.requires_lv": "Richiede Lv{0}",
    "ability.menu_sr": "1-9. Equipaggia o cambia slot, C. Svuota slot, A. Riempimento auto, X. Esci",
    "ability.menu_visual": "[1-9] Equipaggia/cambia slot  [C] Svuota slot  [A] Riempimento auto  [X] Esci",
    "ability.auto_filled": "Barra rapida riempita automaticamente!",
    "ability.clear_slot_prompt": "Svuotare quale slot? (1-9): ",
    "ability.removed_from_slot": "Rimosso {0} dallo slot {1}.",
    "ability.all_equipped": "Tutte le abilità sono già nella tua barra rapida!",
    "ability.slot_has_pick": "Lo slot {0} contiene: {1}. Scegli un sostituto:",
    "ability.pick_for_slot": "Scegli un'abilità per lo slot {0}:",
    "ability.cancel": "Annulla",
    "ability.equipped_to_slot": "{0} equipaggiato nello slot {1}!",
    "_comment_city": "=== Sistema Controllo Città ===",
    "city.no_control": "La città non è sotto il controllo di nessuna squadra.",
    "city.team_controls": "'{0}' controlla la città ({1} membri)",
    "city.kings_tax": "Tassa del Re ({0}%)",
    "city.city_tax": "Tassa Cittadina ({0}%)",
    "city.city_tax_to": "Tassa Cittadina ({0}% a {1})",
    "city.total": "Totale",
    "magic_shop.bbs_shopping": "Acquisti:",
    "magic_shop.bbs_sell": "endi",
    "magic_shop.bbs_identify": "dentifica",
    "magic_shop.bbs_potions_scrolls": "Pozioni e Pergamene:",
    "magic_shop.bbs_healing_pots": "ozioni Curative",
    "magic_shop.bbs_mana_pots": "ozioni Mana",
    "magic_shop.bbs_dungeon_reset": "eset Dungeon",
    "magic_shop.bbs_enchanting_arcane": "Incantamento / Arcano:",
    "magic_shop.bbs_enchant": "ncanta",
    "magic_shop.bbs_remove_ench": "Rimuovi Inc.",
    "magic_shop.bbs_curse_removal": "imuovi Maledizione",
    "magic_shop.bbs_forge": "orgia",
    "magic_shop.bbs_love_spells": "Incantesimi d'Amore",
    "magic_shop.bbs_dark_arts": "Arti Oscure",
    "magic_shop.bbs_study": "Studio",
    "magic_shop.bbs_scry": "Divinazione",
    "magic_shop.bbs_talk_to": "arla con {0}",
    "magic_shop.align_discount": "Allineamento {0}: sconto del {1}%",
    "magic_shop.align_markup": "Allineamento {0}: sovrapprezzo del {1}%",
    "magic_shop.world_discount": "Eventi Mondiali: sconto del {0}% attivo",
    "magic_shop.world_markup": "Eventi Mondiali: aumento prezzi del {0}%",
    "magic_shop.loyalty_discount": "Cliente Fedele: sconto del {0}%",
    "magic_shop.desc_1": "Scaffali di pozioni, cristalli e artefatti arcani rivestono le pareti.",
    "magic_shop.desc_2": "Oggetti incantati ronzano piano, e l'aria luccica di magia residua.",
    "magic_shop.desc_3": "Uno gnomo è appollaiato su uno sgabello alto dietro il bancone, circondato da tomi.",
    "magic_shop.desc_4": "Il profumo di erbe essiccate e ozono aleggia nell'aria.",
    "magic_shop.greeting": "Cosa sarà, {0}?",
    "magic_shop.you_have_gold": "Hai {0} monete d'oro",
    "magic_shop.visual_align_discount": "Il tuo allineamento {0} ti garantisce uno sconto del {1}%!",
    "magic_shop.visual_align_markup": "Il tuo allineamento {0} causa un sovrapprezzo del {1}%.",
    "magic_shop.visual_loyalty": "Cliente Fedele: sconto del {0}% su tutti i servizi!",
    "magic_shop.identify_prompt": "Inserisci il # dell'oggetto da identificare (0 per annullare): ",
    "magic_shop.identification_label": "Identificazione",
    "magic_shop.identify_confirm": "Identificare {0} per {1} oro? (S/N): ",
    "magic_shop.identify_ritual": "{0} fa passare l'oggetto attraverso una cortina scintillante di luce...",
    "magic_shop.identify_result": "È un {0}!",
    "magic_shop.cures_all": "Cura tutte le malattie e condizioni",
    "magic_shop.cures_blindness": "Cura la cecità",
    "magic_shop.cures_plague": "Cura la peste",
    "magic_shop.cures_leprosy": "Cura la lebbra",
    "magic_shop.cures_poison": "Cura il veleno",
    "magic_shop.cures_lycanthropy": "Cura la licantropia",
    "magic_shop.potion_price": "Prezzo: {0} oro per pozione",
    "magic_shop.potion_gold": "Hai: {0} oro",
    "magic_shop.potion_current": "Pozioni curative: {0}/{1}",
    "magic_shop.potion_how_many": "Quante? (1-{0}): ",
    "magic_shop.potion_deal": "{0} ti consegna {1} pozione/i.",
    "magic_shop.potion_total": "Costo totale: {0} oro",
    "magic_shop.potion_no_gold": "{0} guarda la tua borsa vuota e scuote la testa.",
    "magic_shop.curse_intro_1": "{0} si sporge in avanti, studiandoti attentamente.",
    "magic_shop.curse_intro_2": "Le maledizioni sono cose insidiose. Fammi vedere che fardelli porti...",
    "magic_shop.curse_intro_3": "\"Lascia che ti esamini attentamente...\"",
    "magic_shop.no_cursed_items": "Non porti oggetti maledetti.",
    "magic_shop.curse_fortunate": "Sei fortunato. Molti non lo sono.",
    "magic_shop.cursed_items_list": "Oggetti maledetti rilevati:",
    "magic_shop.cursed_item_entry": "  {0}. {1} — Costo rimozione: {2} oro",
    "magic_shop.uncurse_prompt": "Quale oggetto liberare dalla maledizione? (0 per annullare): ",
    "magic_shop.curse_no_gold": "Non hai abbastanza oro per questo servizio.",
    "magic_shop.curse_remains": "La maledizione resta. Torna quando avrai i mezzi.",
    "magic_shop.curse_confirm": "Rimuovere la maledizione da {0} per {1} oro? (S/N): ",
    "magic_shop.curse_scene_1": "{0} traccia un cerchio di sale intorno all'oggetto...",
    "magic_shop.curse_scene_2": "Energia oscura crepita e oppone resistenza...",
    "magic_shop.curse_scene_3": "Con un lampo di luce, la maledizione si frantuma!",
    "magic_shop.curse_scene_4": "L'oggetto risplende, liberato dal suo fardello oscuro.",
    "magic_shop.curse_scene_5": "L'energia oscura si dissolve nel nulla.",
    "magic_shop.curse_success": "Il {0} è stato purificato!",
    "magic_shop.curse_aftermath_1": "È fatta. L'oscurità è stata sollevata.",
    "magic_shop.curse_aftermath_2": "Fai più attenzione a cosa raccogli nel dungeon.",
    "magic_shop.curse_aftermath_3": "\"Che la fortuna ti sia favorevole nei tuoi viaggi.\"",
    "magic_shop.old_enchant_intro": "Posso infondere i tuoi oggetti con essenza magica, o cercare benedizioni dal divino.",
    "magic_shop.old_enchant_1": "(1) Incantamento Minore  - +2 a una statistica        2.000 oro",
    "magic_shop.old_enchant_2": "(2) Incantamento Standard - +4 a una statistica        5.000 oro",
    "magic_shop.old_enchant_3": "(3) Incantamento Superiore - +6 a una statistica       12.000 oro",
    "magic_shop.old_enchant_4": "(4) Benedizione Divina    - +3 a tutte le statistiche 25.000 oro",
    "magic_shop.old_enchant_5": "(5) Tocco dell'Oceano     - Bonus mana speciale      15.000 oro",
    "magic_shop.old_enchant_6": "(6) Protezione dal Male   - +20 Resistenza Magica      8.000 oro",
    "magic_shop.old_enchant_prompt": "Scegli il tipo di incantamento (0 per annullare): ",
    "magic_shop.old_no_enchantable": "Non hai oggetti adatti all'incantamento.",
    "magic_shop.old_bring_items": "'Portami anelli, amuleti o cinture,' suggerisce lo gnomo.",
    "magic_shop.old_enchantable_items": "Oggetti incantabili:",
    "magic_shop.old_choose_item": "Scegli l'oggetto da incantare (0 per annullare): ",
    "magic_shop.old_cursed_enchant": "Non posso incantare un oggetto maledetto. La magia oscura consumerebbe il mio lavoro.",
    "magic_shop.old_remove_first": "Rimuovi prima la maledizione, poi torna.",
    "magic_shop.old_choose_stat": "Scegli la statistica da potenziare:",
    "magic_shop.old_stat_options": "(1) Forza  (2) Difesa  (3) Destrezza  (4) Saggezza  (5) Attacco",
    "magic_shop.old_enchant_confirm": "Incantare {0} per {1} oro? (S/N): ",
    "magic_shop.old_enchant_complete": "L'incantamento è completo!",
    "magic_shop.enchant_col_header": "   #  Slot      Nome                              Statistiche",
    "magic_shop.enchant_tier_header": "   #  Livello          Effetto                 Costo",
    "magic_shop.enchant_tier_header_wide": "   #  Livello          Effetto                         Costo",
    "magic_shop.enchant_failure_warning": "  di FALLIMENTO — l'oro viene consumato e un incantamento esistente viene distrutto!",
    "magic_shop.choose_stat": "Scegli la statistica da potenziare:",
    "magic_shop.stat_choice_prompt": "Scelta statistica: ",
    "magic_shop.enchant_cost": "Costo: {0} oro",
    "magic_shop.proceed_yn": "Procedere? (S/N): ",
    "magic_shop.no_enchanted_equipment": "Non hai equipaggiamento incantato.",
    "magic_shop.removal_cost": "Costo: {0} oro",
    "magic_shop.select_item_cancel": "Seleziona oggetto (0 per annullare): ",
    "magic_shop.remove_enchant_confirm": "Rimuovere gli incantamenti da {0}? (S/N): ",
    "magic_shop.mana_restore": "Ogni pozione ripristina {0} mana.",
    "magic_shop.mana_price": "Prezzo: {0} oro per pozione",
    "magic_shop.mana_gold": "Hai: {0} oro",
    "magic_shop.mana_current": "Pozioni mana: {0}/{1}",
    "magic_shop.mana_max": "Stai trasportando il numero massimo di pozioni mana!",
    "magic_shop.mana_deal": "{0} ti consegna {1} pozione/i di mana.",
    "magic_shop.items_available": "{0} oggetti disponibili - Pagina {1}/{2}",
    "magic_shop.accessory_col_header": "  #   Nome                        Lv   Prezzo     Bonus",
    "magic_shop.cant_afford": "Non puoi permettertelo!",
    "magic_shop.level_warning": "Attenzione: Richiede livello {0} (sei livello {1}).",
    "magic_shop.buy_confirm": "Comprare per {0} oro? (S/N): ",
    "magic_shop.equip_or_inventory": "[E]quipaggia ora o [I]nventario? ",
    "magic_shop.now_wearing": "Ora indossi {0}!",
    "magic_shop.both_rings_occupied": "Entrambi gli slot anello sono occupati:",
    "magic_shop.replace_which_ring": "Sostituire quale? (S/D/A): ",
    "magic_shop.no_accessories_sell": "Non hai accessori da vendere.",
    "magic_shop.gold_and_mana": "Hai {0} oro, {1} mana",
    "magic_shop.love_col_header": "   #  Incantesimo               Effetto                            Costo",
    "magic_shop.dark_surcharge": "(sovrapprezzo del 20% per allineamento oscuro)",
    "magic_shop.select_spell": "Seleziona incantesimo: ",
    "magic_shop.level_required": "Devi essere almeno livello {0}.",
    "magic_shop.insufficient_mana": "Mana insufficiente.",
    "magic_shop.insufficient_gold": "Oro insufficiente.",
    "magic_shop.no_npcs": "Nessun PNG disponibile.",
    "magic_shop.relationship_label": "Relazione:",
    "magic_shop.estimated": "stimato",
    "magic_shop.cost_gold_mana": "Costo: {0} oro, {1} mana",
    "magic_shop.dark_col_header": "   #  Incantesimo       Effetto                         Prob.   Costo       Mana  Oscurità",
    "magic_shop.good_alignment_warning": "ATTENZIONE: Il tuo allineamento buono raddoppia la penalità di oscurità!",
    "magic_shop.no_valid_targets": "Nessun bersaglio valido disponibile.",
    "magic_shop.dark_target": "Bersaglio:",
    "magic_shop.dark_level": "Livello",
    "magic_shop.dark_success": "Successo:",
    "magic_shop.dark_cost_label": "Costo:",
    "magic_shop.dark_darkness": "Oscurità:",
    "magic_shop.alignment_shift": "spostamento allineamento",
    "magic_shop.doubled_good": "raddoppiato — allineamento buono",
    "magic_shop.dark_on_success": "In caso di successo: Il bersaglio muore. Tutti i PNG ti guarderanno con sospetto.",
    "magic_shop.dark_on_failure": "In caso di fallimento: Il bersaglio diventa ostile. Oro e mana comunque spesi.",
    "magic_shop.dark_proceed": "Procedere con la magia oscura? (S/N): ",
    "magic_shop.scry_cost": "Costo: {0} oro per lettura",
    "magic_shop.scry_class": "Classe:",
    "magic_shop.scry_status": "Stato:",
}
