translations = {
    "temple.header_visual": "TEMPIO DEGLI DÈI",
    "temple.ascended_gods": "Dèi Ascesi",
    "temple.altars": "Altari degli Dèi",
    "temple.holy_news": "Notizie Sacre",
    "temple.available_gods": "Dèi Disponibili",
    "temple.your_status": "Il Tuo Stato",
    "temple.prophecies": "Le Profezie degli Antichi Dèi",
    "temple.vision": "UNA VISIONE TI SOVRASTA",
    "temple.deep_temple": "IL TEMPIO PROFONDO",
    "temple.item_sacrifice": "Sacrificio di Oggetti",
    "temple.meditation": "CAPPELLA DI MEDITAZIONE",
    "temple.the_faith": "LA FEDE",
    "temple.faith_benefits": "Benefici della Fede",
    "temple.requirements_not_met": "Requisiti Non Soddisfatti",
    "temple.requirements_met": "Requisiti Soddisfatti",
    "temple.sacred_oath": "IL GIURAMENTO SACRO",
    "temple.joined_faith": "TI SEI UNITO ALLA FEDE",
    "temple.inner_sanctum": "IL SANCTA SANCTORUM",
    "temple.altars_ascended": "ALTARI DEGLI ASCESI",
    "ending.usurper_header": "L ' U S U R P A T O R E",
    "ending.usurper_line_1": "Manwe cade. Il suo corpo si spezza come vecchia pietra e",
    "ending.usurper_line_2": "qualcosa fuoriesce da lui... potere grezzo, bruciante.",
    "ending.usurper_line_3": "Ti colpisce come un muro di fuoco.",
    "ending.usurper_line_4": "\"Lo volevi,\" rantola il dio morente.",
    "ending.usurper_line_5": "\"Prendilo dunque. È tuo ora. Tutto quanto.\"",
    "ending.usurper_line_6": "Sembra quasi sollevato.",
    "ending.usurper_line_7": "Non riesci nemmeno più a sentirlo. Il potere è troppo forte.",
    "ending.usurper_line_8": "Ti attraversa come un fiume che sfonda una diga.",
    "ending.usurper_line_9": "Gli Antichi Dèi rimasti si inginocchiano. Non hanno scelta.",
    "ending.usurper_line_10": "Per un po', è tutto ciò che avevi sognato.",
    "ending.usurper_line_11": "I mortali ti adorano. Regni interi piegano il ginocchio.",
    "ending.usurper_line_12": "Nessuno osa parlare contro il nuovo dio.",
    "ending.usurper_line_13": "Ma passano i secoli.",
    "ending.usurper_line_14": "Poi i millenni.",
    "ending.usurper_line_15": "I fedeli iniziano a sembrare tutti uguali. Le preghiere",
    "ending.usurper_line_16": "si confondono. Siedi su un trono di potere divino",
    "ending.usurper_line_17": "e non provi... quasi nulla.",
    "ending.usurper_line_18": "Manwe aveva cercato di avvertirti. Non hai ascoltato.",
    "ending.usurper_line_19": "Nessuno ascolta mai.",
    "ending.usurper_line_20": "Da qualche parte laggiù, un mortale impugna una spada.",
    "ending.usurper_line_21": "Lo senti. Un altro eroe, che si arrampica verso di te.",
    "ending.usurper_line_22": "Una parte di te spera che ce la faccia.",
    "ending.usurper_the_end": "FINE",
    "ending.usurper_subtitle": "(Il Finale dell'Usurpatore)",
    "ending.press_enter": "  Premi Invio per continuare...",
    "ending.savior_header": "I L   S A L V A T O R E",
    "ending.savior_line_1": "Ti trovi davanti a Manwe. Gli artefatti bruciano nelle tue mani.",
    "ending.savior_line_2": "Potresti ucciderlo adesso. Un solo colpo.",
    "ending.savior_line_3": "Abbassi l'arma.",
    "ending.savior_line_4": "\"So cosa hai fatto,\" gli dici.",
    "ending.savior_line_5": "\"Avevi paura e hai fatto del male. A tanta gente.\"",
    "ending.savior_line_6": "\"Ma non ho fatto tutta questa strada solo per fare un altro cadavere.\"",
    "ending.savior_line_7": "Il Creatore ti fissa. Qualcosa di umido gli scorre",
    "ending.savior_line_8": "sul volto. Non sapevi che gli dèi potessero piangere.",
    "ending.savior_line_9": "\"Dopo tutto quello che ho fatto... tu vorresti--\"",
    "ending.savior_line_10": "\"Taci,\" dici, non senza gentilezza. \"Stai fermo.\"",
    "ending.savior_line_11": "Il Telaio dell'Anima compie la sua opera.",
    "ending.savior_line_12": "La corruzione brucia via come nebbia al sole del mattino.",
    "ending.savior_line_13": "Manwe ansima. Gli Antichi Dèi si agitano nelle loro prigioni.",
    "ending.savior_line_14": "Uno dopo l'altro, tornano in sé.",
    "ending.savior_line_15": "Non è un finale da favola. Gli dèi sono diminuiti,",
    "ending.savior_line_16": "umiliati. Ricordano cosa hanno fatto. Alcuni di loro",
    "ending.savior_line_17": "non riescono a guardarti negli occhi.",
    "ending.savior_line_18": "Ma sono liberi. E così il mondo.",
    "ending.savior_line_19": "Scrivono canzoni su di te. Costruiscono statue.",
    "ending.savior_line_20": "Non hai mai chiesto nulla di tutto ciò.",
    "ending.savior_line_21": "Volevi solo tornare a casa.",
    "ending.savior_line_22": "Quando la morte infine viene a prenderti, molti anni dopo,",
    "ending.savior_line_23": "gli dèi ti aspettano. Non dicono molto.",
    "ending.savior_line_24": "Non ne hanno bisogno.",
    "ending.savior_the_end": "FINE",
    "ending.savior_subtitle": "(Il Finale del Salvatore)",
    "ending.defiant_header": "I L   R I B E L L E",
    "ending.defiant_line_1": "\"No,\" dici.",
    "ending.defiant_line_2": "Manwe sbatte le palpebre. \"...No?\"",
    "ending.defiant_line_3": "\"Non voglio il tuo potere. Non voglio NIENTE di tutto questo.\"",
    "ending.defiant_line_4": "Sollevi gli artefatti. \"Queste cose? Sono catene.\"",
    "ending.defiant_line_5": "\"Catene eleganti, ma pur sempre catene.\"",
    "ending.defiant_line_6": "\"Potresti regnare per sempre,\" dice Manwe, genuinamente confuso.",
    "ending.defiant_line_7": "\"Perché rifiutare?\"",
    "ending.defiant_line_8": "\"Perché è esattamente così che è iniziato questo disastro, no?\"",
    "ending.defiant_line_9": "\"Dèi che decidono di cosa hanno bisogno i mortali. Ho chiuso.\"",
    "ending.defiant_line_10": "Getti gli artefatti a terra.",
    "ending.defiant_line_11": "E li distruggi. Fino all'ultimo.",
    "ending.defiant_line_12": "Il potere divino schizza fuori come scintille da una forgia.",
    "ending.defiant_line_13": "Gli Antichi Dèi barcollano liberi dalle loro prigioni.",
    "ending.defiant_line_14": "Sembrano... piccoli. Confusi. Quasi umani.",
    "ending.defiant_line_15": "Per la prima volta in millenni, sono mortali.",
    "ending.defiant_line_16": "Dovranno vivere tra la gente che un tempo governavano.",
    "ending.defiant_line_17": "Manwe sta svanendo. Non sembra dispiacergli.",
    "ending.defiant_line_18": "\"Forse hai ragione,\" riesce a dire.",
    "ending.defiant_line_19": "\"Forse questo è... meglio.\"",
    "ending.defiant_line_20": "Se ne va prima di finire il pensiero.",
    "ending.defiant_line_21": "Niente più dèi. Niente più piani divini.",
    "ending.defiant_line_22": "Solo gente, che commette i propri errori.",
    "ending.defiant_line_23": "Sembra giusto così.",
    "ending.defiant_line_24": "Esci nel mattino. Solo un'altra persona",
    "ending.defiant_line_25": "su una strada qualunque. In qualche modo, basta così.",
    "ending.defiant_the_end": "FINE",
    "ending.defiant_subtitle": "(Il Finale del Ribelle)",
    "ending.true_sr_title": "IL VERO FINALE - Cercatore dell'Equilibrio",
    "ending.true_line_1": "Sei già stato qui.",
    "ending.true_line_2": "Vite diverse, scelte diverse. Le ricordi tutte adesso.",
    "ending.true_line_3": "L'uccisione. La clemenza. La ribellione.",
    "ending.true_line_4": "Nulla era sbagliato, esattamente. Solo... incompleto.",
    "ending.true_line_5": "Manwe ti guarda e capisci che lo sa.",
    "ending.true_line_6": "\"Sei diverso questa volta,\" dice piano.",
    "ending.true_line_7": "\"Hai davvero capito, vero?\"",
    "ending.true_line_8": "\"Credo di sì,\" dici. \"Ci ho messo abbastanza.\"",
    "ending.true_line_9": "Ride. È un suono stanco.",
    "ending.true_line_10": "\"Lo faccio da solo da così tanto tempo. Costruire,",
    "ending.true_line_11": "riparare, guardare tutto andare in pezzi di nuovo. Mi servirebbe aiuto.\"",
    "ending.true_line_12": "Non è un inganno. Adesso lo vedi.",
    "ending.true_line_13": "L'universo è troppo grande per un solo dio.",
    "ending.true_line_14": "Lo è sempre stato. Quello era tutto il problema.",
    "ending.true_line_15": "\"Non come servo,\" precisi.",
    "ending.true_line_16": "\"Come compagno. Pari diritti.\"",
    "ending.true_line_17": "\"Non vorrei che fosse altrimenti.\"",
    "ending.true_line_18": "Gli stringi la mano.",
    "ending.true_line_19": "Gli Antichi Dèi tornano in sé, lentamente.",
    "ending.true_line_20": "Ricordano tutto -- gli anni buoni e quelli cattivi.",
    "ending.true_line_21": "Nessuno di loro è più come prima. Questo è il punto.",
    "ending.true_line_22": "Il ciclo continua a girare, ma ora va da qualche parte.",
    "ending.true_line_23": "Non solo in tondo. Verso l'alto.",
    "ending.true_line_24": "Ci sarà molto da fare.",
    "ending.true_line_25": "Va bene così. Stavolta hai aiuto.",
    "ending.true_the_end": "LA VERA FINE",
    "ending.true_subtitle": "(Equilibrio Raggiunto)",
    "ending.awakening_sr_title_1": "IL VERO RISVEGLIO",
    "ending.awakening_sr_title_2": "\"Tu sei l'Oceano, che sogna di essere un'onda\"",
    "ending.awakening_line_1": "Ti trovi davanti a Manwe. Ma questa volta è diverso.",
    "ending.awakening_line_2": "Ti guarda come se ti riconoscesse.",
    "ending.awakening_line_3": "Come se ti avesse aspettato per molto, molto tempo.",
    "ending.awakening_line_4": "\"Ti ricordi,\" dice. La voce gli si spezza.",
    "ending.awakening_line_5": "\"Dèi... ti ricordi davvero.\"",
    "ending.awakening_line_6": "E ti ricordi. Ti colpisce tutto in una volta.",
    "ending.awakening_line_7": "Non sei un avventuriero qualunque che ha avuto fortuna.",
    "ending.awakening_line_8": "Sei un pezzo di LUI. Un frammento del Creatore,",
    "ending.awakening_line_9": "spinto in un corpo mortale e mandato giù a vivere e",
    "ending.awakening_line_10": "morire e soffrire come tutti gli altri.",
    "ending.awakening_line_11": "Così che potesse finalmente capire cosa si provava.",
    "ending.awakening_line_12": "\"Ero solo,\" dice Manwe. All'improvviso sembra vecchio.",
    "ending.awakening_line_13": "\"Ho creato gli Antichi Dèi perché volevo qualcuno con cui parlare.",
    "ending.awakening_line_14": "Ma non li ho mai capiti. Come avrei potuto? Non ero mai stato",
    "ending.awakening_line_15": "mortale. Non avevo mai perso nulla. Non avevo mai avuto paura.\"",
    "ending.awakening_line_16": "\"Così hai mandato te stesso quaggiù,\" dici.",
    "ending.awakening_line_17": "\"Ancora e ancora.\"",
    "ending.awakening_line_18": "\"Ancora e ancora,\" conferma.",
    "ending.awakening_line_19": "Tutto quel dolore che hai portato. Gli amici che sono morti.",
    "ending.awakening_line_20": "Le scelte impossibili. Era anche il suo dolore.",
    "ending.awakening_line_21": "Tuo e suo. La stessa persona, da sempre.",
    "ending.awakening_line_22": "È come essere un'onda che all'improvviso si rende conto",
    "ending.awakening_line_23": "di essere stata l'intero oceano per tutto questo tempo.",
    "ending.awakening_line_24": "\"Non voglio più essere solo,\" ammette Manwe.",
    "ending.awakening_line_25": "\"E gli Antichi Dèi -- sono frammenti anche loro, vero?\"",
    "ending.awakening_line_26": "\"Abbiamo combattuto contro noi stessi per tutto questo tempo.\"",
    "ending.awakening_line_27": "Gli prendi la mano. O la tua mano. Stessa cosa, in fondo.",
    "ending.awakening_line_28": "Le barriere crollano.",
    "ending.awakening_line_29": "Tutta la separazione. Dio e mortale, creatore e creatura.",
    "ending.awakening_line_30": "Non è mai stata reale. Solo una storia che ti sei raccontato",
    "ending.awakening_line_31": "per poter imparare cosa significasse essere piccolo.",
    "ending.awakening_line_32": "Gli Antichi Dèi si agitano. Maelketh, Veloura, tutti loro.",
    "ending.awakening_line_33": "Anche loro ricordano. Non sono mai stati davvero nemici.",
    "ending.awakening_line_34": "Solo pezzi di un unico essere, intenti a recitare un dramma",
    "ending.awakening_line_35": "che è andato avanti fin troppo a lungo.",
    "ending.awakening_line_36": "Non c'è mai stato un ciclo. Non davvero.",
    "ending.awakening_line_37": "Solo l'oceano, che sognava di essere onde.",
    "ending.awakening_line_38": "Il sogno continua. Ma ora è un sogno lucido.",
    "ending.awakening_line_39": "Sei a casa.",
    "ending.awakening_line_40": "Sei sempre stato a casa.",
    "ending.awakening_the_end": "IL VERO RISVEGLIO",
    "ending.awakening_subtitle": "(L'Onda Ricorda l'Oceano)",
    "ending.dissolution_sr_title_1": "DISSOLUZIONE",
    "ending.dissolution_sr_title_2": "\"Niente più cicli. Niente più attaccamento.\"",
    "ending.dissolution_line_1": "L'hai fatto tre volte ormai. Forse di più.",
    "ending.dissolution_line_2": "Preso il trono. Mostrato clemenza. Te ne sei andato.",
    "ending.dissolution_line_3": "Ti sei svegliato e hai capito che eri l'oceano da sempre.",
    "ending.dissolution_line_4": "E adesso sei stanco.",
    "ending.dissolution_line_5": "Non il tipo cattivo di stanchezza. Il tipo in cui hai",
    "ending.dissolution_line_6": "fatto tutto ciò per cui eri venuto e non resta più",
    "ending.dissolution_line_7": "nulla da fare.",
    "ending.dissolution_line_8": "Manwe lo vede nei tuoi occhi prima che tu dica qualcosa.",
    "ending.dissolution_line_9": "\"Te ne vai,\" dice. \"Per davvero, stavolta.\"",
    "ending.dissolution_line_10": "\"Niente più cicli. Niente più ritorni.\"",
    "ending.dissolution_line_11": "\"Già.\"",
    "ending.dissolution_line_12": "\"Ma le storie -- tutto questo continua--\"",
    "ending.dissolution_line_13": "\"Andrà avanti benissimo senza di me. È un po'",
    "ending.dissolution_line_14": "tutto il senso. Non serve ogni singola onda per",
    "ending.dissolution_line_15": "far funzionare l'oceano.\"",
    "ending.dissolution_line_16": "Rimane in silenzio a lungo.",
    "ending.dissolution_line_17": "\"Non sono mai riuscito a farlo,\" dice infine.",
    "ending.dissolution_line_18": "\"Semplicemente... fermarmi. Lasciar andare tutto. Dovevo sempre",
    "ending.dissolution_line_19": "continuare a costruire, a riparare, a TENER STRETTO.\"",
    "ending.dissolution_line_20": "Ti guarda quasi con invidia.",
    "ending.dissolution_line_21": "\"Forse è questo che avrei dovuto imparare da te.\"",
    "ending.dissolution_line_22": "Gli sorridi. Sembra l'ultimo sorriso.",
    "ending.dissolution_line_23": "Tutto diventa silenzioso.",
    "ending.dissolution_line_24": "Non buio. Non vuoto. Solo... fermo.",
    "ending.dissolution_line_25": "Come lo spazio tra un respiro e l'altro.",
    "ending.dissolution_line_26": "Il mondo continua a girare da qualche parte là fuori.",
    "ending.dissolution_line_27": "Gli dèi risolvono le loro questioni.",
    "ending.dissolution_line_28": "Nuovi eroi impugnano spade e vanno in cerca di guai.",
    "ending.dissolution_line_29": "Ma tu hai finito. E sembra giusto.",
    "ending.dissolution_line_30": "Non come arrendersi. Come completare.",
    "ending.dissolution_line_31": "Pace.",
    "ending.dissolution_dots": ". . . . . . . . . .",
    "ending.dissolution_save_delete_warn": "Il tuo salvataggio verrà eliminato permanentemente.",
    "ending.dissolution_cannot_undo": "Questa azione non può essere annullata.",
    "ending.dissolution_enlightenment": "Hai raggiunto la vera illuminazione:",
    "ending.dissolution_letting_go": "Il lasciar andare definitivo.",
    "ending.dissolution_confirm": "  Digita 'DISSOLVI' per confermare, o qualsiasi altra cosa per annullare: ",
    "ending.dissolution_farewell_1": "Addio, avventuriero.",
    "ending.dissolution_farewell_2": "È stata una bella avventura.",
    "ending.dissolution_the_end": "FINE",
    "ending.dissolution_story_finished": "(La storia di questo personaggio è conclusa.)",
    "ending.dissolution_save_deleted": "(Salvataggio eliminato.)",
    "ending.dissolution_not_ready_1": "Non sei ancora pronto, eh? Va bene così.",
    "ending.dissolution_not_ready_2": "Forse la prossima volta.",
    "ending.dissolution_press_enter": "  Premi Invio...",
    "ending.credits_title": "U S U R P E R",
    "ending.credits_subtitle": "REBORN",
    "ending.credits_original_concept": "CONCETTO ORIGINALE",
    "ending.credits_original_author": "Jakob Dangarden",
    "ending.credits_original_game": "Usurper: Halls of Avarice (1993)",
    "ending.credits_reborn_by": "RICREATO DA",
    "ending.credits_reborn_author": "Jason Knight",
    "ending.credits_story_narrative": "STORIA E NARRATIVA",
    "ending.credits_story_author": "Jason Knight",
    "ending.credits_story_inspired_1": "Ispirato alla filosofia buddista:",
    "ending.credits_story_inspired_2": "Samsara, la Ruota del Divenire,",
    "ending.credits_story_inspired_3": "e l'Oceano della coscienza",
    "ending.credits_systems_design": "DESIGN DEI SISTEMI",
    "ending.credits_systems_author": "Jason Knight",
    "ending.credits_artwork": "GRAFICA",
    "ending.credits_artwork_xbit": "xbit (x-bit.org)",
    "ending.credits_artwork_xbit_desc": "Ritratti ANSI di Razze e Classi",
    "ending.credits_artwork_sd": "Sudden Death",
    "ending.credits_artwork_sd_desc": "Strumento di Conversione ANSI rez2ans",
    "ending.credits_artwork_cozmo": "Cozmo / Lunatics Unleashed",
    "ending.credits_artwork_cozmo_desc": "Conoscenza e Guida sull'Arte ANSI",
    "ending.credits_contributors": "COLLABORATORI",
    "ending.credits_contributor_1": "fastfinge - Contributi al Codice",
    "ending.credits_contributor_2": "xbit - Arte ANSI",
    "ending.credits_alpha_testers": "ALPHA TESTER E COMUNITÀ DISCORD",
    "ending.credits_testers_1": "fastfinge, Inkblot, Byte Knight,",
    "ending.credits_testers_2": "Druidah, Quent, xbit, Stettin",
    "ending.credits_testers_3": "...e molti altri",
    "ending.credits_special_thanks": "RINGRAZIAMENTI SPECIALI",
    "ending.credits_thanks_1": "A tutti gli appassionati di giochi BBS door",
    "ending.credits_thanks_2": "che mantengono vivo lo spirito",
    "ending.credits_and_to_you": "E A TE",
    "ending.credits_player": "Giocatore: {0}",
    "ending.credits_final_level": "Livello Finale: {0}",
    "ending.credits_ending": "Finale: {0}",
    "ending.credits_cycle": "Ciclo: {0}",
    "ending.credits_thank_you": "Grazie per aver giocato.",
    "ending.final_stats_header": "S T A T I S T I C H E   F I N A L I",
    "ending.final_stats_character": "Personaggio: {0} il {1}",
    "ending.final_stats_race": "Razza: {0}",
    "ending.final_stats_level": "Livello Finale: {0}",
    "ending.final_stats_monsters": "Mostri Uccisi: {0}",
    "ending.final_stats_players": "Giocatori Sconfitti: {0}",
    "ending.final_stats_gold": "Oro Accumulato: {0}",
    "ending.final_stats_chivalry": "Cavalleria: {0}",
    "ending.final_stats_darkness": "Oscurità: {0}",
    "ending.final_stats_artifacts": "Artefatti Raccolti: {0}/7",
    "ending.final_stats_seals": "Sigilli Scoperti: {0}/7",
    "ending.final_stats_choices": "Scelte Cruciali: {0}",
    "ending.final_stats_ending": "Finale Raggiunto: {0}",
    "ending.final_stats_cycle": "Ciclo Eterno: {0}",
    "ending.legacy_header": "L A   T U A   E R E D I T À",
    "ending.legacy_hero_section": "=== L'EROE ===",
    "ending.legacy_hero_desc": "{0} il {1} {2}",
    "ending.legacy_hero_stats": "Ha raggiunto il livello {0} dopo aver ucciso {1} mostri",
    "ending.legacy_align_hero": "un vero eroe, o qualcosa di molto simile",
    "ending.legacy_align_decent": "per lo più onesto, come avventurieri",
    "ending.legacy_align_neutral": "difficile da definire -- non proprio buono, non proprio cattivo",
    "ending.legacy_align_dark": "il tipo di persona da cui le madri mettono in guardia i figli",
    "ending.legacy_align_evil": "un vero figlio di puttana, francamente",
    "ending.legacy_known_as": "Conosciuto come {0}.",
    "ending.legacy_companions_section": "=== COMPAGNI ===",
    "ending.legacy_companions_active": "Coloro che erano al tuo fianco alla fine:",
    "ending.legacy_companion_entry": "- {0} (Livello {1})",
    "ending.legacy_companions_alone": "Hai affrontato la battaglia finale da solo.",
    "ending.legacy_companions_fallen": "Coloro che sono caduti lungo il cammino:",
    "ending.legacy_fallen_entry": "- {0}, perduto a causa di {1}",
    "ending.legacy_love_section": "=== AMORE E FAMIGLIA ===",
    "ending.legacy_married_to": "Sposato con {0}",
    "ending.legacy_children": "Insieme avete cresciuto {0} figli{1}.",
    "ending.legacy_children_plural": "o",
    "ending.legacy_lovers": "Mai sposato, ma ha avuto {0} partner romantici.",
    "ending.legacy_no_romance": "Il cuore dell'eroe è rimasto concentrato sulla missione.",
    "ending.legacy_divorces": "{0} matrimoni finiti in divorzio.",
    "ending.legacy_world_section": "=== IMPATTO SUL MONDO ===",
    "ending.legacy_achievements_section": "=== TRAGUARDI NOTEVOLI ===",
    "ending.legacy_archetype_section": "=== LA TUA VERA NATURA ===",
    "ending.quote_usurper": "\"Alla fine il trono è solo una prigione elegante.\"",
    "ending.quote_savior": "\"Avrei potuto ucciderlo. Non l'ho fatto. Non me ne pento.\"",
    "ending.quote_defiant": "\"Nessuno mi dice cosa fare. Nemmeno gli dèi.\"",
    "ending.quote_true": "\"Buffo come puoi cercare il mondo intero e finire proprio da dove sei partito.\"",
    "ending.quote_secret": "\"Ho finito. E va bene così.\"",
    "ending.quote_default": "\"Un'avventura di quelle, comunque.\"",
    "ending.quote_attribution": "- {0}",
    "ending.world_gods_saved": "Gli Antichi Dèi sono stati per lo più redenti ({0} salvati, {1} distrutti)",
    "ending.world_gods_saved_desc": "Le cose si mettono bene per il reame.",
    "ending.world_gods_destroyed": "Gli Antichi Dèi sono stati per lo più distrutti ({0} uccisi, {1} salvati)",
    "ending.world_gods_destroyed_desc": "Il loro potere si è disperso al vento.",
    "ending.world_gods_uncertain": "Il destino degli Antichi Dèi resta incerto.",
    "ending.world_wealth_rich": "Hai ammassato una fortuna ridicola. Buon per te.",
    "ending.world_wealth_decent": "Hai accumulato un bel gruzzolo d'oro lungo il cammino.",
    "ending.world_kills_legend": "Hai ucciso così tanti mostri che probabilmente hanno leggende su di TE laggiù.",
    "ending.world_kills_bloody": "Hai scavato un sentiero di sangue nelle profondità del dungeon.",
    "ending.world_choices": "{0} decisioni cruciali hanno plasmato il destino del reame.",
    "ending.world_usurper": "Hai preso il trono degli dèi. Il reame non ha smesso di tremare.",
    "ending.world_savior": "Il reame è in pace. Cantano ancora canzoni su ciò che hai fatto.",
    "ending.world_defiant": "Niente più dèi a dire alla gente cosa fare. Era ora.",
    "ending.world_true": "Il ciclo è spezzato. Qualunque cosa venga dopo, è qualcosa di nuovo.",
    "ending.achievement_max_level": "Raggiunto il livello massimo di 100",
    "ending.achievement_kills": "Uccisi oltre 10.000 mostri",
    "ending.achievement_seals": "Raccolti tutti e 7 i Sigilli del Potere",
    "ending.achievement_artifacts": "Trovati tutti e 7 gli Artefatti Divini",
    "ending.achievement_party": "Guidato un gruppo completo di compagni",
    "ending.achievement_family": "Fondato una famiglia nel reame",
    "ending.achievement_count": "Sbloccati {0} traguardi",
    "ending.achievement_beginning": "Il tuo viaggio era appena iniziato...",
    "ending.archetype_intro": "Nel corso del tuo viaggio, la tua vera natura è emersa:",
    "ending.archetype_secondary": "Con sfumature di: {0} ({1})",
    "ending.archetype_stats_header": "Statistiche del Viaggio:",
    "ending.archetype_combat": "Combattimento: {0} mostri, {1} boss",
    "ending.archetype_exploration": "Esplorazione: {0} piani esplorati",
    "ending.archetype_magic": "Magia: {0} incantesimi lanciati",
    "ending.archetype_romance": "Romanticismo: {0} incontri, {1} matrimoni",
    "ending.archetype_wisdom": "Saggezza: {0} sigilli, {1} artefatti",
    "ending.unlocks_header": "S B L O C C H I   O T T E N U T I",
    "ending.unlocks_intro": "Completare questo finale ha sbloccato:",
    "ending.unlocks_apply_ngplus": "Questi bonus si applicheranno in Nuova Partita+!",
    "ending.unlock_dark_lord_name": "TITOLO DI SIGNORE OSCURO",
    "ending.unlock_dark_lord_desc": "Inizia la NP+ con il titolo 'Signore Oscuro'",
    "ending.unlock_tyrant_name": "AURA DEL TIRANNO",
    "ending.unlock_tyrant_desc": "+15% danni in NP+",
    "ending.unlock_fear_name": "TEMETE IL TRONO",
    "ending.unlock_fear_desc": "I nemici hanno -10% di probabilità di fuggire",
    "ending.unlock_savior_name": "TITOLO DI SALVATORE",
    "ending.unlock_savior_desc": "Inizia la NP+ con il titolo 'Salvatore'",
    "ending.unlock_healing_name": "LUCE GUARITRICE",
    "ending.unlock_healing_desc": "+25% efficacia delle cure in NP+",
    "ending.unlock_commerce_name": "COMMERCIO BENEDETTO",
    "ending.unlock_commerce_desc": "10% di sconto in tutti i negozi",
    "ending.unlock_defiant_name": "TITOLO DI RIBELLE",
    "ending.unlock_defiant_desc": "Inizia la NP+ con il titolo 'Ribelle'",
    "ending.unlock_mortal_name": "ORGOGLIO MORTALE",
    "ending.unlock_mortal_desc": "+20% guadagno PE in NP+",
    "ending.unlock_key_name": "CHIAVE ANTICA",
    "ending.unlock_key_desc": "Inizia con la chiave scorciatoia del dungeon",
    "ending.unlock_awakened_name": "TITOLO DI RISVEGLIATO",
    "ending.unlock_awakened_desc": "Inizia la NP+ con il titolo 'Risvegliato'",
    "ending.unlock_ocean_name": "BENEDIZIONE DELL'OCEANO",
    "ending.unlock_ocean_desc": "+15% a tutte le statistiche in NP+",
    "ending.unlock_artifact_name": "MEMORIA DEGLI ARTEFATTI",
    "ending.unlock_artifact_desc": "Tutte le posizioni degli artefatti rivelate",
    "ending.unlock_seal_name": "RISONANZA DEI SIGILLI",
    "ending.unlock_seal_desc": "I sigilli danno bonus doppi",
    "ending.unlock_dissolved_name": "DISSOLTO",
    "ending.unlock_dissolved_desc": "Il tuo viaggio è completo. Non servono sblocchi.",
    "ending.unlock_veteran_name": "VETERANO",
    "ending.unlock_veteran_desc": "Inizia la NP+ al livello 5 invece che 1",
    "ending.unlock_master_name": "MAESTRO",
    "ending.unlock_master_desc": "Inizia la NP+ al livello 10 con statistiche bonus",
    "ending.unlock_slayer_name": "STERMINATORE",
    "ending.unlock_slayer_desc": "I mostri rari appaiono il 25% più spesso",
    "ending.unlock_seal_master_name": "MAESTRO DEI SIGILLI",
    "ending.unlock_seal_master_desc": "I sigilli sono visibili sulla minimappa in NP+",
    "ending.unlock_artifact_hunter_name": "CACCIATORE DI ARTEFATTI",
    "ending.unlock_artifact_hunter_desc": "Gli artefatti danno +50% effetti bonus",
    "ending.unlock_survivor_name": "SENSO DI COLPA DEL SOPRAVVISSUTO",
    "ending.unlock_survivor_desc": "I compagni caduti possono tornare come fantasmi con consigli",
    "ending.ending_name_usurper": "L'Usurpatore (Sentiero Oscuro)",
    "ending.ending_name_savior": "Il Salvatore (Sentiero della Luce)",
    "ending.ending_name_defiant": "Il Ribelle (Sentiero Indipendente)",
    "ending.ending_name_true": "Il Vero Finale (Equilibrio)",
    "ending.ending_name_unknown": "Sconosciuto",
    "ending.immortal_header": "I L   C O S M O   A T T E N D E",
    "ending.immortal_power": "Senti il potere della creazione scorrere nelle tue vene.",
    "ending.immortal_coil": "Il vincolo mortale si allenta. Il reame divino chiama.",
    "ending.immortal_manwe_1": "\"Hai dimostrato il tuo valore,\" sussurra Manwe.",
    "ending.immortal_manwe_2": "\"Pochi mortali meritano questa scelta.\"",
    "ending.immortal_manwe_3": "\"Vuoi trascendere la mortalità e diventare un dio?\"",
    "ending.immortal_as_god": "Come dio, potrai:",
    "ending.immortal_benefit_1": "- Apparire nel Tempio perché i mortali ti adorino",
    "ending.immortal_benefit_2": "- Gestire seguaci e compiere imprese divine",
    "ending.immortal_benefit_3": "- Competere con altri dèi per i credenti",
    "ending.immortal_benefit_4": "- Ottenere ranghi divini da Spirito Minore a Dio",
    "ending.immortal_renounce": "(Puoi rinunciare all'immortalità in qualsiasi momento per ricominciare)",
    "ending.immortal_ascend_prompt": "  Ascendere alla divinità? (S/N): ",
    "ending.immortal_choose_name": "Scegli il tuo nome divino (3-30 caratteri):",
    "ending.immortal_name_prompt": "  Nome Divino: ",
    "ending.immortal_name_invalid": "Il nome deve avere 3-30 caratteri.",
    "ending.immortal_ascended": "{0}, Spirito Minore di {1}",
    "ending.immortal_ascended_msg": "è asceso al Reame Divino!",
    "ending.immortal_abdicated": "Il trono è stato abdicato mentre trascendi gli affari mortali.",
    "ending.immortal_alt_blocked": "I personaggi alternativi non possono ascendere all'immortalità.",
    "ending.immortal_alt_main_only": "Solo il tuo personaggio principale può diventare un dio.",
    "ending.immortal_enter_pantheon": "Ora entrerai nel Pantheon — il tuo dominio eterno.",
    "ending.immortal_enter_prompt": "  Premi Invio per entrare nel Reame Divino...",
    "ending.ngplus_header": "L A   R U O T A   G I R A",
    "ending.ngplus_stirs": "Qualcosa si agita nell'oscurità.",
    "ending.ngplus_voice": "Una voce che quasi riconosci.",
    "ending.ngplus_again_1": "\"Allora. È successo.\"",
    "ending.ngplus_again_2": "\"Vuoi riprovare? Stavolta sarai più forte.\"",
    "ending.ngplus_again_3": "\"E ricorderai qualcosa...\"",
    "ending.ngplus_wheel": "La ruota continua a girare.",
    "ending.ngplus_current_cycle": "Ciclo Attuale: {0}",
    "ending.ngplus_next_cycle": "Prossimo Ciclo: {0}",
    "ending.ngplus_bonuses": "Bonus per la Nuova Partita+:",
    "ending.ngplus_bonus_stats": "- Bonus alle statistiche iniziali basati sul tuo finale",
    "ending.ngplus_bonus_xp": "- Guadagno esperienza aumentato",
    "ending.ngplus_bonus_artifacts": "- Conoscenza delle posizioni degli artefatti",
    "ending.ngplus_bonus_dialogue": "- Nuove opzioni di dialogo con gli dèi",
    "ending.ngplus_prestige_intro": "- Nuove classi prestigio sbloccate:",
    "ending.ngplus_begin_prompt": "  Iniziare il Ciclo Eterno? (S/N): ",
    "ending.ngplus_decline_1": "\"Giusto. Riposati un po'.\"",
    "ending.ngplus_decline_2": "\"La ruota non se ne va da nessuna parte.\"",
    "ending.ngplus_return_prompt": "  Premi Invio per tornare al menù principale...",
    "temple.enter_area": "Entri nell'Area del Tempio",
    "temple.worship_god": "Adori {0}.",
    "temple.follow_immortal": "Segui l'immortale {0}.",
    "temple.not_believer": "Non sei un credente.",
    "temple.description_line1": "L'area del Tempio è affollata di monaci, predicatori e",
    "temple.description_line2": "processioni di sacerdoti in cammino verso gli altari.",
    "temple.description_line3": "I profeti dell'apocalisse cercano di attirare la tua attenzione.",
    "temple.ancient_stones_hint1": "Nell'angolo più lontano, pietre antiche formano le fondamenta del tempio...",
    "temple.ancient_stones_hint2": "Sembrano più vecchie di qualsiasi altare qui presente.",
    "temple.services": "Servizi del Tempio:",
    "temple.sr_worship": "W. Adorazione",
    "temple.sr_desecrate": "D. Dissacrare altare",
    "temple.sr_holy_news": "H. Notizie Sacre",
    "temple.sr_altars": "A. Altari",
    "temple.sr_contribute": "C. Contribuire",
    "temple.sr_item_sacrifice": "I. Sacrificio Oggetti",
    "temple.sr_status": "S. Stato",
    "temple.sr_god_ranking": "G. Classifica dèi",
    "temple.sr_prophecies": "P. Profezie",
    "temple.sr_pray": "Y. Pregare",
    "temple.sr_prayed_today": "(Già pregato oggi)",
    "temple.sr_examine_stones": "E. Esaminare le Pietre",
    "temple.sr_deep_temple": "T. Il Tempio Profondo",
    "temple.sr_meditation_chapel": "M. Cappella di Meditazione (qualcuno prega da solo...)",
    "temple.sr_faith_seek": "F. La Fede (cerca la Somma Sacerdotessa...)",
    "temple.sr_faith_serve_another": "F. La Fede (servi un altro...)",
    "temple.sr_faith_member": "Sei un membro della Fede.",
    "temple.sr_inner_sanctum_meditated": "N. Sancta Sanctorum (meditato oggi)",
    "temple.sr_inner_sanctum_cost": "N. Sancta Sanctorum ({0}o)",
    "temple.sr_ascended_gods": "Dèi Ascesi:",
    "temple.sr_join_immortal_following": "J. Unirsi al Gregge dell'Immortale (Segui: {0})",
    "temple.sr_join_immortal_unaffiliated": "J. Unirsi al Gregge dell'Immortale (non affiliato)",
    "temple.sr_sacrifice_gold": "$. Sacrificare Oro (al tuo dio immortale)",
    "temple.sr_leave_immortal": "L. Lasciare la Fede dell'Immortale",
    "temple.sr_return": "R. Ritornare",
    "temple.menu_worship": "dorazione          ",
    "temple.menu_desecrate": "issacrare altare   ",
    "temple.menu_holy_news": "otizie Sacre",
    "temple.menu_altars": "ltari             ",
    "temple.menu_contribute": "ontribuire        ",
    "temple.menu_item_sacrifice": "acrificio Oggetti",
    "temple.menu_status": "tato              ",
    "temple.menu_god_ranking": "lassifica dèi     ",
    "temple.menu_prophecies": "rofezie           ",
    "temple.menu_pray": " Pregare",
    "temple.menu_prayed_today": "(Già pregato oggi)",
    "temple.menu_examine_stones": "saminare le Pietre",
    "temple.menu_deep_temple": "l Tempio Profondo",
    "temple.menu_meditation_chapel": "editazione        ",
    "temple.menu_meditation_hint": "(qualcuno prega da solo...)",
    "temple.menu_the_faith": " La Fede ",
    "temple.menu_faith_seek": "(cerca la Somma Sacerdotessa...)",
    "temple.menu_faith_serve_another": "(servi un altro...)",
    "temple.menu_faith_member": " Sei un membro della Fede.",
    "temple.menu_inner_sanctum": " Sancta Sanctorum",
    "temple.menu_meditated_today": "  (meditato oggi)",
    "temple.menu_inner_sanctum_cost": "  ({0}o)",
    "temple.menu_join_flock": "nirsi al Gregge      ",
    "temple.menu_following": "(Segui: {0})",
    "temple.menu_unaffiliated": "(non affiliato)",
    "temple.menu_sacrifice_gold": "acrificare Oro       ",
    "temple.menu_sacrifice_gold_hint": "(al tuo dio immortale)",
    "temple.menu_leave_faith": "asciare la Fede",
    "temple.menu_return": "itornare",
    "temple.invalid_choice": "Scelta non valida. Digita 'look' per ridisegnare il menù.",
    "temple.follow_immortal_currently": "Attualmente segui l'immortale {0}.",
    "temple.abandon_for_elder": "Abbandonare {0} per un dio antico? (S/N) ",
    "temple.renounce_immortal": "Rinunci a {0}. La loro presenza divina svanisce dalla tua mente.",
    "temple.remain_faithful": "Rimani fedele al tuo patrono immortale.",
    "temple.currently_worship": "Attualmente adori {0}.",
    "temple.lost_faith": "Hai perso la fede in {0}? (S/N) ",
    "temple.dont_believe": "Non credi più in {0}.",
    "temple.powers_diminish": "I poteri di {0} diminuiscono...",
    "temple.send_note": "Inviare un messaggio a {0}? (S/N) ",
    "temple.note_prompt": "Messaggio: ",
    "temple.done": "Fatto!",
    "temple.no_longer_believer": "Non sei più un credente.",
    "temple.gods_dont_like_apostates": "Buon per te. Gli dèi non vedono di buon occhio gli apostati.",
    "temple.choose_god_worship": "Scegli un dio da adorare",
    "temple.raise_hands_pray": "Alzi le mani e preghi l'onnipotente {0}",
    "temple.for_forgiveness": "per il perdono",
    "temple.now_believer": "Sei ora un credente in {0}!",
    "temple.bond_severed": "Il tuo legame con l'immortale {0} è reciso.",
    "temple.gods_smile": "Gli dèi sorridono alla tua fede!",
    "temple.desecration_limit": "Le guardie del tempio ti osservano troppo da vicino dopo il tuo sacrilegio.",
    "temple.wait_tomorrow": "Dovrai aspettare domani.",
    "temple.no_evil_deeds": "Non hai più azioni malvagie!",
    "temple.upset_gods": "Vuoi davvero far arrabbiare gli dèi? (S/N) ",
    "temple.good_for_you": "Buon per te!",
    "temple.select_god_desecrate": "Seleziona il dio il cui altare dissacrare",
    "temple.not_allowed_abuse_own": "Non ti è permesso profanare il tuo stesso Dio!",
    "temple.confirm_desecrate": "Sei SICURO di voler dissacrare l'altare di {0}? (S/N) ",
    "temple.wise_choice": "Scelta saggia. Gli dèi ricordano chi porta rispetto.",
    "temple.no_good_deeds": "Non hai più azioni buone!",
    "temple.who_receive_gift": "Chi riceverà il tuo dono?",
    "temple.not_your_god": "{0} non è il tuo Dio! Sei sicuro?",
    "temple.mighty_not_happy": "Il potente {0} non sarà contento.",
    "temple.continue_prompt": "Continuare? (S/N) ",
    "temple.no_gods_exist": "Non esistono dèi in questo reame.",
    "temple.altar_of": "Altare di {0} il {1}",
    "temple.believers_count": "  Credenti: {0}",
    "temple.power_count": "  Potere: {0}",
    "temple.god_ranking_header": "   Immortali                Rango               Seguaci",
    "temple.gods_watch": "Gli dèi vegliano sul reame...",
    "temple.divine_interventions": "Gli interventi divini plasmano il destino dei mortali...",
    "temple.prayers_reach": "Preghiere e sacrifici raggiungono i cieli...",
    "temple.total_gods": "Dèi Attivi Totali: {0}",
    "temple.total_believers": "Credenti Totali: {0}",
    "temple.most_powerful": "Il Più Potente: {0}",
    "temple.most_popular": "Il Più Popolare: {0}",
    "temple.no_gods_available": "Nessun dio disponibile.",
    "temple.select_prompt": "{0} (o premi Invio per annullare):",
    "temple.no_god_match": "Nessun dio trovato per '{0}'. Riprova.",
    "temple.multiple_matches": "Trovate corrispondenze multiple:",
    "temple.be_more_specific": "Sii più specifico.",
    "temple.selected_god": "Hai selezionato: {0}, {1}",
    "temple.alignment_info": "  Allineamento: {0} | Credenti: {1}",
    "temple.selection_cancelled": "Selezione annullata.",
    "temple.no_gods_accept": "Nessun dio accetta adoratori al momento.",
    "temple.type_name_hint": "(Digita parte del nome di un dio per selezionarlo, es. 'Sol' per Solarius)",
    "temple.sacrifice_to": "Sacrificare a {0}",
    "temple.sacrifice_gold_option": "(O)ro",
    "temple.sacrifice_status_option": "(S)tato",
    "temple.sacrifice_return_option": "(R)itorna",
    "temple.invalid_choice_short": "Scelta non valida.",
    "temple.gold_sacrifice_prompt": "Quantità d'oro da sacrificare: ",
    "temple.invalid_amount": "Quantità non valida.",
    "temple.not_enough_gold": "Non hai abbastanza oro!",
    "temple.confirm_sacrifice_gold": "Sacrificare {0} oro a {1}? (S/N) ",
    "temple.god_power_growing": "Il potere di {0} sta crescendo!",
    "temple.reward_will_come": "Lo senti... La tua ricompensa arriverà.",
    "temple.power_increased": "Potere aumentato di {0} punti!",
    "temple.duration_minutes": "Durata: {0} minuti",
    "temple.darkness_accepts": "L'oscurità accetta la tua offerta. (+{0} reputazione Ombre)",
    "temple.devotion_noted": "La tua devozione è stata registrata. (+{0} reputazione Fede)",
    "temple.god_seethes": "*** {0} RIBOLLE DI RABBIA! ***",
    "temple.betrayal_not_forgotten": "Il tuo tradimento non sarà dimenticato. Le segrete ti attendono.",
    "temple.god_furious": "{0} è furioso per il tuo tradimento!",
    "temple.darkness_awaits": "L'oscurità ti attende nelle profondità...",
    "temple.god_displeased": "{0} è scontento della tua infedeltà.",
    "temple.beware_shadows": "Guardati dalle ombre nel tuo futuro...",
    "temple.god_no_longer_exists": "Il tuo dio {0} non esiste più!",
    "temple.faith_shaken": "La tua fede è stata scossa...",
    "temple.good_deeds": "Azioni Buone: {0}",
    "temple.evil_deeds": "Azioni Malvagie: {0}",
    "temple.god_label": "Dio: {0}",
    "temple.god_none": "Dio: Nessuno (Pagano)",
    "temple.prophecy_maelketh_defeated": "La Lama Spezzata si è infranta. La guerra trova finalmente pace.",
    "temple.prophecy_maelketh_saved": "La Lama ricorda l'onore. La guerra serve la giustizia ancora una volta.",
    "temple.prophecy_veloura_defeated": "Il Cuore Appassito non batte più. L'amore svanisce dal mondo.",
    "temple.prophecy_veloura_saved": "L'amore fiorisce di nuovo dove la speranza fu piantata.",
    "temple.prophecy_thorgrim_defeated": "Il Giudice Vuoto è stato messo a tacere. I mortali dovranno trovare la propria giustizia.",
    "temple.prophecy_noctura_allied": "Il filo della Tessitrice ti guida attraverso le tenebre.",
    "temple.prophecy_noctura_defeated": "Le ombre si disperdono. I segreti giacciono scoperti.",
    "temple.prophecy_aurelion_defeated": "La Luce Morente si è spenta. La verità muore nell'oscurità.",
    "temple.prophecy_aurelion_saved": "La Luce arde di nuovo in un vascello mortale.",
    "temple.prophecy_terravok_defeated": "La Montagna crolla. Le fondamenta si spezzano.",
    "temple.prophecy_terravok_saved": "La Montagna si innalza. Le fondamenta resistono in eterno.",
    "temple.prophecy_manwe_resolved": "Alla domanda del Creatore è stata data risposta. Cosa verrà dopo?",
    "temple.prophecies_sealed": "Le profezie restano sigillate per coloro che non sono ancora pronti.",
    "temple.prophecies_grow_stronger": "Diventa più forte, e i sussurri ti troveranno...",
    "temple.vision_seven_figures": "Vedi sette figure in piedi in un cerchio di luce.",
    "temple.vision_faces_beautiful": "I loro volti sono belli, radiosi, divini.",
    "temple.vision_darkness_creeps": "Poi l'oscurità si insinua. Una dopo l'altra, la loro luce si affievolisce.",
    "temple.vision_beauty_twists": "La loro bellezza si distorce. I sorrisi diventano ghigni.",
    "temple.vision_meant_to_guide": "\"Dovevamo guidarvi,\" sussurra uno di loro.",
    "temple.vision_broke_hearts": "\"Ma ci avete spezzato il cuore.\"",
    "temple.vision_endless_halls": "Ti vedi camminare attraverso corridoi senza fine.",
    "temple.vision_faint_light": "Davanti a te, una debole luce tremola -- appena visibile.",
    "temple.vision_light_fades": "Una voce parla: \"La Luce si affievolisce con ogni menzogna.\"",
    "temple.vision_find_me": "\"Trovami prima che la verità muoia per sempre.\"",
    "temple.vision_from_temple": "Senti che la visione proviene da... qui. Il Tempio.",
    "temple.vision_throne_stars": "Ti trovi davanti a un trono di stelle.",
    "temple.vision_figure_older": "Su di esso siede una figura più antica del tempo stesso.",
    "temple.vision_come_far": "\"Sei arrivato lontano, figlio della polvere.\"",
    "temple.vision_final_question": "\"Ma la domanda finale resta.\"",
    "temple.vision_worth_cost": "\"La creazione valeva il prezzo?\"",
    "temple.deep_temple_sealed": "Il cammino verso il Tempio Profondo è sigillato.",
    "temple.deep_temple_prove": "Devi prima dimostrare il tuo valore contro gli altri Antichi Dèi.",
    "temple.deep_temple_descend": "Scendi gradini di pietra levigati da millenni di pellegrini.",
    "temple.deep_temple_torches": "Le torce qui ardono con fiamme pallide e tremolanti.",
    "temple.deep_temple_air_thick": "L'aria si fa densa sotto il peso di preghiere dimenticate.",
    "temple.deep_temple_watches": "Qualcosa ti osserva dalle ombre tra le luci.",
    "temple.aurelion_altar_dark": "L'altare dove un tempo dimorava Aurelion è buio e freddo.",
    "temple.aurelion_ash_remains": "Solo cenere resta dove il dio della verità un tempo brillava.",
    "temple.aurelion_sense_loss": "Provi un profondo senso di... perdita.",
    "temple.press_enter_return": "Premi Invio per tornare...",
    "temple.aurelion_warm_light": "Una luce calda riempie la stanza.",
    "temple.aurelion_presence": "Senti la presenza di Aurelion dentro di te -- verità fatta carne.",
    "temple.aurelion_thank_you": "\"Grazie,\" la sua voce echeggia nella tua mente.",
    "temple.aurelion_new_vessel": "\"Per aver dato alla verità un nuovo vascello.\"",
    "temple.aurelion_glow": "Un debole bagliore pulsa nel cuore del Tempio Profondo.",
    "temple.aurelion_weak": "È debole... appena visibile... ma inconfondibilmente divino.",
    "temple.aurelion_see_me": "\"Tu... puoi vedermi?\" sussurra una voce.",
    "temple.aurelion_few_can": "\"Pochi ci riescono ormai. Le menzogne sono diventate così fitte...\"",
    "temple.approach_light": "Avvicinarsi alla luce morente? (S/N) ",
    "temple.aurelion_flickers": "La luce tremola ma non riesce a manifestarsi del tutto.",
    "temple.aurelion_too_weak": "\"Sono... troppo debole. Devi prima affrontare gli altri.\"",
    "temple.aurelion_defeat_siblings": "\"Sconfiggi più dei miei fratelli caduti. Solo allora...\"",
    "temple.step_back": "Ti allontani dalla luce morente.",
    "temple.aurelion_understand": "\"Capisco,\" sussurra tristemente la voce.",
    "temple.aurelion_not_ready": "\"Non tutti sono pronti per la verità.\"",
    "temple.must_worship_first": "Devi adorare un dio prima di poter sacrificare oggetti!",
    "temple.visit_worship": "Visita prima l'opzione (W) Adorazione.",
    "temple.kneel_before": "Ti inginocchi davanti all'altare di {0}.",
    "temple.what_sacrifice": "Cosa sacrificherai?",
    "temple.sacrifice_weapon_option": "(W) Arma - Offri la tua arma per una benedizione divina",
    "temple.sacrifice_armor_option": "(A) Armatura - Offri la tua armatura per protezione divina",
    "temple.sacrifice_potions_option": "(H) Pozioni curative - Offri pozioni per il favore divino",
    "temple.sacrifice_return": "(R) Ritorna",
    "temple.sacrifice_prompt": "Sacrificio: ",
    "temple.no_weapon": "Non hai un'arma da sacrificare!",
    "temple.confirm_sacrifice_weapon": "Sacrificare la tua arma (Potere: {0}) a {1}? (S/N) ",
    "temple.dissolves_divine_light": "La tua arma si dissolve in luce divina!",
    "temple.god_accepts": "{0} accetta il tuo sacrificio!",
    "temple.divine_power_increased": "Potere divino aumentato di {0}!",
    "temple.blessing_strength": "{0} ti benedice con +{1} Forza!",
    "temple.no_armor": "Non hai un'armatura da sacrificare!",
    "temple.confirm_sacrifice_armor": "Sacrificare la tua armatura (Potere: {0}) a {1}? (S/N) ",
    "temple.armor_dissolves": "La tua armatura si dissolve in luce divina!",
    "temple.blessing_defence": "{0} ti benedice con +{1} Difesa!",
    "temple.no_potions": "Non hai pozioni curative da sacrificare!",
    "temple.have_potions": "Hai {0} pozioni curative.",
    "temple.how_many_sacrifice": "Quante sacrificarne? ",
    "temple.not_enough_potions": "Non hai così tante pozioni!",
    "temple.confirm_sacrifice_potions": "Sacrificare {0} pozioni curative a {1}? (S/N) ",
    "temple.potions_evaporate": "Le tue pozioni evaporano in essenza divina!",
    "temple.god_restores_health": "{0} ripristina completamente la tua salute!",
    "temple.darkness_notes_devotion": "L'oscurità nota la tua devozione. (+{0} reputazione Ombre)",
    "temple.light_notes_devotion": "La luce nota la tua devozione. (+{0} reputazione Fede)",
    "temple.desecrated_altar": "Hai dissacrato l'altare di {0}!",
    "temple.darkness_flows": "L'oscurità fluisce nella tua anima! (+{0} Oscurità)",
    "temple.xp_from_profane": "Esperienza ottenuta da conoscenze profane! (+{0} PE)",
    "temple.god_curses": "{0} ti maledice dall'aldilà!",
    "temple.divine_fury": "La furia divina è travolgente!",
    "temple.stat_diminish": "Senti la tua {0} diminuire mentre il potere divino la strappa via! (-1 {1})",
    "temple.divine_damage": "Subisci {0} danni divini!",
    "temple.ancient_stones_revealed": "Le pietre antiche sono ancora in piedi, ma il loro segreto è stato svelato.",
    "temple.remember_truth": "Ricordi la verità della creazione...",
    "temple.walk_past_altars": "Cammini oltre gli altari affollati, oltre la folla dei fedeli,",
    "temple.far_corner": "fino all'angolo più lontano del tempio dove pochi si avventurano.",
    "temple.massive_stones": "Qui, enormi pietre formano le fondamenta dell'edificio.",
    "temple.older_than_temple": "Sono più antiche del tempio stesso -- più antiche di qualsiasi dio",
    "temple.whose_altar": "il cui altare si erge sopra di esse.",
    "temple.monks_say": "I monaci dicono che queste pietre erano qui prima che la città fosse costruita.",
    "temple.before_mortals": "Prima che i mortali giungessero in questa terra.",
    "temple.before_gods": "Prima ancora che gli dèi camminassero sulla terra.",
    "temple.touch_stone": "Toccare la pietra antica? (S/N) ",
    "temple.step_back_stones": "Ti allontani dalle pietre.",
    "temple.perhaps_another_time": "Forse un'altra volta...",
    "temple.hand_touches": "La tua mano tocca la pietra fredda...",
    "temple.at_first_nothing": "All'inizio, nulla.",
    "temple.warmth_pulse": "Poi calore. Un battito, come un cuore.",
    "temple.stone_glows": "La pietra RISPLENDE sotto il tuo palmo.",
    "temple.ancient_symbols": "Simboli antichi si accendono -- un linguaggio",
    "temple.older_language": "più antico di qualsiasi lingua parlata da mortali o dèi.",
    "temple.voice_speaks": "Una voce parla direttamente nella tua mente:",
    "temple.seek_truth": "  \"Cerchi la verità. Così pochi lo fanno ormai.\"",
    "temple.first_seal": "  \"Questo è il Primo Sigillo -- la storia della creazione.\"",
    "temple.remember_well": "  \"Ricordalo bene, poiché la comprensione inizia da qui.\"",
    "temple.press_enter_continue": "  Premi Invio per continuare...",
    "temple.must_worship_to_pray": "Devi adorare un dio prima di poter pregare per benedizioni.",
    "temple.visit_worship_first": "Visita (W) Adorazione per scegliere una divinità.",
    "temple.already_prayed": "Hai già pregato oggi.",
    "temple.return_tomorrow": "Torna domani per un'altra benedizione.",
    "temple.kneel_altar": "Ti inginocchi davanti all'altare di {0}...",
    "temple.prayers_rise_immortal": "Le tue preghiere salgono fino al reame immortale...",
    "temple.divine_power_surges": "  Il potere divino di {0} ti attraversa!",
    "temple.prayer_amplifies": "  La preghiera amplifica i doni del tuo patrono:",
    "temple.combat_blessing": "  Benedizione da combattimento: +{0}% danni/difesa per {1} combattimenti",
    "temple.no_boons_configured": "  {0} non ha ancora configurato i favori divini.",
    "temple.prayer_heard_no_boons": "  La tua preghiera è stata ascoltata, ma nessun dono fluisce.",
    "temple.god_no_longer_exists_short": "Il tuo dio non esiste più...",
    "temple.prayers_rise_incense": "Le tue preghiere salgono come incenso verso i cieli...",
    "temple.warm_light_fills": "Una luce calda riempie la stanza mentre il tuo dio ti ascolta.",
    "temple.shadows_coil": "Le ombre si avvolgono intorno a te mentre il tuo dio riconosce la tua devozione.",
    "temple.balance_clarity": "Un senso di equilibrio e chiarezza ti pervade.",
    "temple.damage_bonus": "  Danni: +{0}%",
    "temple.defense_bonus": "  Difesa: +{0}%",
    "temple.xp_bonus": "  Bonus PE: +{0}%",
    "temple.duration_label": "  Durata: {0} minuti",
    "temple.blessing_upon_you": "La benedizione di {0} è su di te!",
    "temple.prayers_unanswered": "Le tue preghiere restano senza risposta oggi...",
    "temple.faith_standing_gain": "(+1 reputazione Fede)",
    "temple.shadows_standing_gain": "(+1 reputazione Ombre)",
    "temple.meditation_chapel_empty": "La cappella di meditazione è vuota.",
    "temple.only_silence": "Solo silenzio e fumo di candele riempiono la piccola stanza.",
    "temple.step_into_chapel": "Entri in una piccola e silenziosa cappella accanto al tempio principale.",
    "temple.candle_illuminates": "Una singola candela illumina una donna inginocchiata davanti a un altare vuoto.",
    "temple.faded_robes": "Indossa le vesti sbiadite di una sacerdotessa, anche se non portano alcun simbolo.",
    "temple.hands_clasped": "Le sue mani sono giunte, ma le labbra non si muovono.",
    "temple.prays_to_nothing": "Prega... il nulla. Uno spazio vuoto dove un tempo viveva la fede.",
    "temple.notices_watching": "Si accorge che la stai osservando.",
    "temple.turns_back": "Si volta di nuovo verso l'altare vuoto.",
    "temple.this_is_companion": "Questa è {0}, {1}.",
    "temple.role_label": "Ruolo: {0}",
    "temple.abilities_label": "Abilità: {0}",
    "temple.sr_ask_join": "R. Chiederle di unirti a te",
    "temple.sr_talk_past": "T. Parlare del suo passato",
    "temple.sr_leave_prayers": "L. Lasciarla alle sue preghiere",
    "temple.visual_ask_join": "[R] Chiederle di unirsi a te",
    "temple.visual_talk_past": "[T] Parlare del suo passato",
    "temple.visual_leave_prayers": "[L] Lasciarla alle sue preghiere",
    "temple.leave_silent_vigil": "La lasci alla sua veglia silenziosa.",
    "temple.speaks_without_turning": "Mentre raggiungi la porta, parla senza voltarsi:",
    "temple.dungeons_dangerous": "\"Le segrete sono pericolose,\" dici. \"Una guaritrice sarebbe preziosa.\"",
    "temple.looks_long_moment": "{0} ti guarda a lungo.",
    "temple.flickers_in_eyes": "Qualcosa guizza nei suoi occhi. Non speranza -- qualcosa di più piccolo.",
    "temple.a_question": "Una domanda, forse.",
    "temple.want_me_to_heal": "\"Vuoi che guarisca,\" dice.",
    "temple.always_been_able": "\"Posso farlo. Ho sempre potuto farlo.\"",
    "temple.will_it_matter": "\"Ma conterà qualcosa? Conterà qualcosa di tutto questo?\"",
    "temple.doesnt_wait": "Non aspetta una risposta.",
    "temple.perhaps_help": "\"Forse se ti aiuto abbastanza a lungo, lo scoprirò.\"",
    "temple.rises_from_altar": "{0} si alza dall'altare vuoto.",
    "temple.candle_flickers": "La candela dietro di lei tremola -- ma non si spegne.",
    "temple.companion_death_warning": "ATTENZIONE: I compagni possono morire permanentemente. Potrebbe trovare la sua risposta nel sacrificio.",
    "temple.sit_beside": "Ti siedi accanto a lei. Il silenzio si distende tra voi.",
    "temple.was_healer_veloura": "\"Ero una guaritrice al tempio di Veloura,\" dice infine.",
    "temple.corruption_came": "\"Quando arrivò la corruzione... le guaritrici diventarono qualcos'altro.\"",
    "temple.escaped_left_faith": "\"Sono fuggita. Ma ho lasciato la mia fede indietro.\"",
    "temple.personal_quest_label": "Missione Personale: {0}",
    "temple.keep_praying": "\"Continuo a pregare,\" sussurra.",
    "temple.to_empty_altar": "\"Davanti a un altare vuoto. Davanti al nulla.\"",
    "temple.if_i_stop": "\"Perché se mi fermo... non so più chi sono.\"",
    "temple.ask_join_prompt": "Chiederle di unirsi a te? (S/N): ",
    "temple.squeeze_shoulder": "Le stringi delicatamente la spalla e te ne vai.",
    "temple.faith_approach": "Ti avvicini al sancta sanctorum del Tempio, dove solo i più",
    "temple.faith_devoted": "devoti sono ammessi. Un'anziana sacerdotessa in vesti bianche ti accoglie.",
    "temple.mirael_intro": "\"Sono la Somma Sacerdotessa Mirael,\" dice, con voce gentile ma ferma.",
    "temple.mirael_watched": "\"Ho osservato il tuo viaggio con interesse, viaggiatore.\"",
    "temple.mirael_studies": "Ti studia con occhi consapevoli.",
    "temple.already_serve": "\"Servi già {0}.\"",
    "temple.no_divided_loyalties": "\"La Fede non accetta lealtà divise.\"",
    "temple.renounce_seek_again": "\"Se mai rinuncerai alla tua attuale alleanza, cercami di nuovo.\"",
    "temple.sacred_flames": "Indica le fiamme sacre che ardono eternamente sull'altare.",
    "temple.faith_old_gods_pure": "\"La Fede crede che gli Antichi Dèi fossero un tempo puri e buoni.\"",
    "temple.faith_guided": "\"Guidarono l'umanità con amore, saggezza e verità.\"",
    "temple.faith_corrupted": "\"Ma l'adorazione mortale li corruppe -- le nostre paure, i nostri odi,\"",
    "temple.faith_absorbed": "\"le nostre menzogne... assorbirono tutto fino a spezzarsi.\"",
    "temple.faith_healed": "\"Crediamo che gli dèi possano essere GUARITI, non distrutti.\"",
    "temple.faith_devotion": "\"Attraverso devozione, sacrificio e fede incrollabile,\"",
    "temple.faith_restore": "\"li riporteremo al loro antico splendore.\"",
    "temple.benefit_healing": "• 25% di sconto sulle cure presso tutti i guaritori",
    "temple.benefit_prayers": "• Accesso a preghiere e benedizioni di guarigione speciali",
    "temple.benefit_npcs": "• Trattamento amichevole da chierici e PNG del tempio",
    "temple.benefit_standing": "• La reputazione con la Fede cresce attraverso la devozione",
    "temple.faith_requires": "La Fede richiede:",
    "temple.faith_req_level": "• Livello 10 o superiore",
    "temple.faith_req_standing": "• Reputazione Fede 100+ (fai offerte in oro, prega ogni giorno)",
    "temple.faith_your_standing": "  La tua Reputazione Fede: {0}",
    "temple.mirael_return": "\"Torna quando la tua fede arderà più forte,\" dice Mirael con gentilezza.",
    "temple.mirael_offerings": "\"Fai offerte ai nostri altari. Prega ogni giorno. Mostra la tua devozione.\"",
    "temple.mirael_extends": "La Somma Sacerdotessa Mirael ti tende la mano.",
    "temple.mirael_noted": "\"La tua devozione è stata notata. Le tue offerte accettate.\"",
    "temple.mirael_oath": "\"Pronuncerai il giuramento sacro e ti unirai alla Fede?\"",
    "temple.join_warning": "ATTENZIONE: Unirsi alla Fede:",
    "temple.join_lock_out": "• Ti impedirà l'accesso alla Corona e alle Ombre",
    "temple.join_decrease": "• Diminuirà la reputazione con le fazioni rivali di 100",
    "temple.join_prompt": "Unirsi alla Fede? (S/N) ",
    "temple.mirael_understanding": "Mirael annuisce con comprensione.",
    "temple.mirael_not_for_everyone": "\"Il sentiero della fede non è per tutti. Ma sappi questo:\"",
    "temple.mirael_doors_open": "\"Le nostre porte restano aperte, qualora tu cercassi la luce.\"",
    "temple.kneel_sacred_flames": "Ti inginocchi davanti alle fiamme sacre.",
    "temple.mirael_stands": "La Somma Sacerdotessa Mirael si erge davanti a te, le mani alzate.",
    "temple.repeat_after_me": "\"Ripeti dopo di me:\"",
    "temple.oath_line1": "\"Impegno la mia anima nella restaurazione degli dèi.\"",
    "temple.oath_line2": "\"Guarirò ciò che è spezzato, rammenderò ciò che è lacerato.\"",
    "temple.oath_line3": "\"Attraverso la fede, sarò la luce nelle tenebre.\"",
    "temple.oath_line4": "\"Finché gli dèi non saranno puri, non troverò riposo.\"",
    "temple.flames_flare": "Le fiamme sacre divampano, avvolgendoti in una luce calda.",
    "temple.profound_peace": "Senti una profonda pace pervaderti.",
    "temple.mirael_welcome": "\"Benvenuto, figlio della luce,\" dice calorosamente Mirael.",
    "temple.mirael_never_waver": "\"Ora sei uno di noi. Che la tua fede non vacilli mai.\"",
    "temple.as_member_receive": "Come membro della Fede, riceverai:",
    "temple.receive_discount": "• 25% di sconto su tutti i servizi di cura",
    "temple.receive_recognition": "• Riconoscimento dai PNG del Tempio",
    "temple.receive_blessings": "• Accesso a benedizioni e preghiere esclusive della Fede",
    "temple.sanctum_sealed": "  Il Sancta Sanctorum è sigillato agli estranei.",
    "temple.sanctum_faith_only": "  Solo i membri della Fede possono entrare.",
    "temple.sanctum_already_meditated": "  Hai già meditato oggi.",
    "temple.sanctum_ready_tomorrow": "  Il sancta sanctorum sarà pronto di nuovo domani.",
    "temple.sanctum_stillness": "  Una stanza di perfetta quiete. L'incenso aleggia nell'aria.",
    "temple.sanctum_runes": "  Antiche rune pulsano debolmente lungo le pareti.",
    "temple.sanctum_cost": "  La meditazione profonda costa {0} oro.",
    "temple.sanctum_grant": "  Il sancta sanctorum concede un +1 permanente a un attributo casuale.",
    "temple.sanctum_gold_label": "  Oro: {0}",
    "temple.sanctum_enter_prompt": "  Entrare nel sancta sanctorum? (S/N): ",
    "temple.sanctum_cant_afford": "  Non puoi permetterti l'offerta.",
    "temple.sanctum_kneel": "  Ti inginocchi sulla fredda pietra e chiudi gli occhi...",
    "temple.sanctum_warmth": "  Il calore ti pervade. Qualcosa cambia dentro di te.",
    "temple.sanctum_stat_gain": "  +1 {0}!",
    "temple.sanctum_power_mark": "  Il potere del sancta sanctorum ha lasciato il suo segno su di te.",
    "temple.no_ascended_gods": "  Non ci sono dèi ascesi da adorare.",
    "temple.worship_which": "  Quale dio adorare? (0 per annullare): ",
    "temple.already_follow": "  Segui già {0}.",
    "temple.currently_follow": "  Attualmente segui {0}.",
    "temple.abandon_prompt": "  Abbandonarlo? (S/N): ",
    "temple.currently_worship_elder": "  Attualmente adori il dio antico {0}.",
    "temple.abandon_elder_prompt": "  Abbandonare {0} per un dio nato mortale? (S/N): ",
    "temple.renounce_elder": "  Rinunci a {0}!",
    "temple.elder_strikes": "  {0} ti colpisce per il tuo tradimento!",
    "temple.elder_damage": "  Subisci {0} danni! (PV: {1}/{2})",
    "temple.elder_watches": "  {0} ti osserva in silenzio mentre te ne vai...",
    "temple.kneel_immortal": "  Ti inginocchi davanti all'altare di {0}.",
    "temple.divine_presence": "  Senti una presenza divina riconoscerti.",
    "temple.divine_favors_flow": "  Senti i suoi favori divini fluire in te:",
    "temple.must_worship_immortal_sr": "  Devi prima adorare un dio immortale. Usa J per unirti a un gregge.",
    "temple.must_worship_immortal": "  Devi prima adorare un dio immortale. Usa [J] per unirti a un gregge.",
    "temple.sacrifice_gold_to": "  Sacrificare oro a {0}",
    "temple.gold_on_hand": "  Oro disponibile: {0}",
    "temple.amount_to_sacrifice": "  Quantità da sacrificare (0 per annullare): ",
    "temple.not_enough_gold_sacrifice": "  Non hai abbastanza oro.",
    "temple.gold_upon_altar": "  Deponi {0} oro sull'altare di {1}.",
    "temple.offering_burns": "  L'offerta arde con fuoco divino! (Potere: {0})",
    "temple.warm_glow": "  Senti un caldo bagliore di favore divino.",
    "temple.no_immortal_god": "  Non segui nessun dio immortale.",
    "temple.abandon_faith_prompt": "  Abbandonare la tua fede in {0}? (S/N): ",
    "temple.turn_away": "  Ti allontani dall'altare di {0}.",
    "temple.without_patronage": "  Sei di nuovo senza patronato divino.",
    "temple.desecrate_hack_line1": "Quando nessuno è nei paraggi inizi a",
    "temple.desecrate_hack_line2": "colpire l'altare con un piccone.",
    "temple.desecrate_hack_word": "Colpo",
    "temple.desecrate_hack_word_lower": "colpo",
    "temple.desecrate_hack_final": "colpo..!",
    "temple.desecrate_unholy_line1": "Trovi delle sostanze empie e le",
    "temple.desecrate_unholy_line2": "riversi tutte sull'altare!",
    "temple.desecrate_altar_damaged": "L'altare è gravemente danneggiato!",
    "temple.gods_remember_blasphemy": "Gli dèi ricorderanno questa blasfemia!",
    "temple.desecrate_method_smash": "Distruggi l'altare con un piccone, frantumando le sacre reliquie.",
    "temple.desecrate_method_pour": "Versi sostanze empie sui simboli sacri.",
    "temple.desecrate_method_carve": "Incidi parole blasfeme sulla superficie dell'altare.",
    "temple.desecrate_method_fire": "Dai fuoco alle offerte lasciate dai fedeli.",
    "temple.desecrate_method_topple": "Rovesci la statua del dio, guardandola andare in frantumi.",
    "temple.god_list_stats": "    Credenti: {0} | Potere: {1}",
}
