translations = {
    # === BETRAYAL (35 keys) ===
    "betrayal.approach_npc": "Te acercas a {0}.",
    "betrayal.broken_not_mended": "Lo que esta roto no siempre puede repararse.",
    "betrayal.choose_to_give": "Recibimos lo que elegimos dar.",
    "betrayal.debt_paid": "La deuda esta saldada.",
    "betrayal.dont_deserve": "Yo... no merezco esto.",
    "betrayal.door_now_open": "Pero una puerta que estaba cerrada... ahora esta abierta.",
    "betrayal.eye_for_eye": "Ojo por ojo. Sangre por sangre.",
    "betrayal.eyes_changed": "Algo en sus ojos ha cambiado.",
    "betrayal.eyes_widen": "Los ojos de {0} se abren de par en par.",
    "betrayal.falls_before_you": "{0} cae ante ti.",
    "betrayal.flinch_expecting": "Se estremecen, esperando ira. Esperando justicia.",
    "betrayal.forgive_disagree": "No estoy de acuerdo. Quiza nunca lo este.",
    "betrayal.forgive_let_go": "Pero elijo soltar este peso.",
    "betrayal.forgive_understand": "Entiendo por que hiciste lo que hiciste.",
    "betrayal.header_betrayal": "T R A I C I O N",
    "betrayal.header_sacrifice": "U N   S A C R I F I C I O",
    "betrayal.knew_coming": "Sabian que esto llegaria.",
    "betrayal.neither_speak": "Por un momento, ninguno de los dos habla.",
    "betrayal.no_plea_mercy": "Su ultimo aliento no lleva suplica de piedad.",
    "betrayal.not_reconciliation": "No es reconciliacion. Aun no.",
    "betrayal.ocean_understanding": "Una comprension distante se agita en tu interior...",
    "betrayal.ocean_wave_crashes": "La ola que se estrella contra ti fue alguna vez parte del mismo oceano.",
    "betrayal.path_vengeance": "Has elegido el camino de la venganza.",
    "betrayal.perhaps_not": "Quiza no. Pero rara vez recibimos lo que merecemos.",
    "betrayal.perhaps_not_end": "Quiza... esto no tiene que ser el final.",
    "betrayal.sacrifice_not_malice": "Esto no fue malicia. Fue amor.",
    "betrayal.sacrifice_ultimate_price": "Un amor dispuesto a pagar el precio supremo.",
    "betrayal.something_shifts": "Algo cambia entre ustedes.",
    "betrayal.turns_to_face": "{0} se vuelve para mirarte.",
    "betrayal.understand_reasons": "[Comienzas a comprender sus razones...]",
    "betrayal.understanding_bridge": "La comprension aun podria tender un puente sobre este abismo.",
    "betrayal.violence_begets": "La violencia engendra violencia. La ola se estrella, pero el oceano permanece.",
    "betrayal.wave_forgives_shore": "La ola perdona a la orilla por romperla.",
    "betrayal.weight_remains": "Pero el peso... el peso permanece.",
    "betrayal.wounds_too_deep": "Algunas heridas son demasiado profundas para sanar.",

    # === GRIEF (41 keys) ===
    "grief.ash_feeds_soil": "\"Pero la ceniza alimenta la tierra. Cosas nuevas crecen.\"",
    "grief.atmo_acceptance": "Piensas en {0} y sonries. El dolor permanece, pero ya no te define.",
    "grief.atmo_anger": "Tu sangre hierve. Cada enemigo te recuerda lo que has perdido.",
    "grief.atmo_bargaining": "Si tan solo pudieras volver atras. Cambiar las cosas. Salvar a {0}. Debe haber una forma...",
    "grief.atmo_denial": "Juras haber visto el rostro de {0} entre la multitud. Pero al mirar de nuevo, han desaparecido.",
    "grief.atmo_depression": "El mundo parece gris. La ausencia de {0} es un peso sobre tu pecho.",
    "grief.attempt_resurrect": "Intentas resucitar a {0} usando {1}...",
    "grief.cannot_unburn": "\"No puedes desquemar lo que ya ardio.\"",
    "grief.change_permanent": "\"Te cambiaron. Ese cambio es permanente.\"",
    "grief.every_choice_carries": "\"Cada decision que tomas los lleva adelante.\"",
    "grief.grief_river_backward": "\"Tu duelo es el rio intentando fluir hacia atras.\"",
    "grief.header_memories": "R E C U E R D O S",
    "grief.hurt_is_price": "\"El dolor no es un defecto. Es el precio.\"",
    "grief.let_go_downstream": "\"Dejalos ir rio abajo.\"",
    "grief.loved_them_hurts": "\"Los amaste. Por eso duele.\"",
    "grief.never_loved_at_all": "\"Preferarias no haber amado jamas?\"",
    "grief.npc_casual_acceptance": "Hay algo diferente en ti. Mas sabio, tal vez.",
    "grief.npc_casual_anger": "Eh, calma! Que te tiene tan alterado?",
    "grief.npc_casual_bargaining": "Estas buscando algo. Lo noto. Que es?",
    "grief.npc_casual_denial": "Pareces... distraido. Esta todo bien?",
    "grief.npc_casual_depression": "Oye... no te ves bien. Necesitas hablar?",
    "grief.npc_wise_acceptance": "Has resistido la tormenta. Eres mas fuerte por ello.",
    "grief.npc_wise_anger": "Tu rabia arde con fuerza. Usala, pero no dejes que te consuma.",
    "grief.npc_wise_bargaining": "No hay tratos que hacer con la muerte. Solo aceptacion.",
    "grief.npc_wise_denial": "Veo la sombra de la perdida sobre ti. Pero aun no estas listo para enfrentarla.",
    "grief.npc_wise_depression": "El peso de la tristeza es pesado. Pero esto tambien pasara.",
    "grief.river_flows_on": "\"Sigue fluyendo, llevando lo que fue hacia lo que sera.\"",
    "grief.river_not_mourn": "\"Un rio no llora el agua que ya paso.\"",
    "grief.rivers_one_direction": "\"Pero los rios solo fluyen en una direccion.\"",
    "grief.silence_answer": "El silencio es tu unica respuesta.",
    "grief.start_carrying_forward": "\"Empieza a llevarlos adelante.\"",
    "grief.stop_bringing_back": "\"Deja de intentar traerlos de vuelta.\"",
    "grief.they_are_immortal": "\"De esa forma, son inmortales.\"",
    "grief.voice_clearer": "La voz es mas clara ahora, gentil pero firme:",
    "grief.voice_compassion": "La voz habla con compasion infinita:",
    "grief.voice_fades_echo": "\"Una voz se desvanece, pero el eco permanece.\"",
    "grief.voice_quiet_whisper": "La voz es suave ahora. Casi un susurro:",
    "grief.waiting_at_sea": "\"Te esperan junto al mar.\"",
    "grief.whisper_touches": "Un susurro toca tu mente:",
    "grief.words_shaped_you": "\"Sus palabras te formaron. Te cambiaron.\"",
    "grief.you_are_echo": "\"TU ERES su eco ahora.\"",

    # === ENDING (13 keys) ===
    "ending.credits_artwork_cozmo": "Cozmo / Lunatics Unleashed",
    "ending.credits_artwork_sd": "Sudden Death",
    "ending.credits_artwork_xbit": "xbit (x-bit.org)",
    "ending.credits_original_author": "Jakob Dangarden",
    "ending.credits_original_game": "Usurper: Halls of Avarice (1993)",
    "ending.credits_reborn_author": "Jason Knight",
    "ending.credits_story_author": "Jason Knight",
    "ending.credits_systems_author": "Jason Knight",
    "ending.credits_testers_1": "fastfinge, Inkblot, Byte Knight,",
    "ending.credits_testers_2": "Druidah, Quent, xbit, Stettin",
    "ending.credits_title": "U S U R P A D O R",
    "ending.dissolution_dots": ". . . . . . . . . .",
    "ending.quote_attribution": "- {0}",

    # === ENGINE (9 keys) ===
    "engine.credits_original_name": "    Usurper: Halls of Avarice (1993)",
    "engine.credits_reborn": "  USURPER REBORN:",
    "engine.credits_subtitle": "USURPER REBORN",
    "engine.main_title_box": "USURPER REBORN",
    "engine.menu_admin": "Admin",
    "engine.menu_sysop": "SysOp",
    "engine.section_info": "  INFO",
    "engine.section_info_visual": "  -- INFO ",
    "engine.title_version": "v{0} \"{1}\"",

    # === SEALS (7 keys) ===
    "seals.face_manwe_see_more": "Cuando enfrentes a Manwe, veras mas que los demas.",
    "seals.fourth_path": "Si cumples ciertas condiciones, un cuarto camino se abre.",
    "seals.knowledge_understanding": "Este conocimiento te otorga comprension.",
    "seals.not_destroyer": "No destructor. No salvador. No desafiante.",
    "seals.true_ending_possible": "EL VERDADERO FINAL AHORA ES POSIBLE",
    "seals.uncovered_history": "Has descubierto la historia completa de los dioses.",
    "seals.understand_choices": "Comprenderas sus decisiones. Sus arrepentimientos.",

    # === ARTIFACT (11 keys) ===
    "artifact.artifacts_resonate": "Los seis artefactos que llevas comienzan a resonar.",
    "artifact.light_shadow_dance": "Luz y sombra danzan a tu alrededor.",
    "artifact.lore": "SABER",
    "artifact.seek_prison": "\"Busca la Prision del Creador en el nivel 100 de la mazmorra.\"",
    "artifact.special": "Especial",
    "artifact.tear_opens": "Una grieta se abre en el tejido de la existencia...",
    "artifact.voice_whispers": "Una voz que no es voz susurra en tu mente.",
    "artifact.void_key_desc1": "Del vacio entre mundos, una llave de pura nada",
    "artifact.void_key_desc2": "se materializa ante ti. Es la ausencia hecha forma,",
    "artifact.void_key_desc3": "la figura de la posibilidad misma.",
    "artifact.way_is_open": "\"El camino esta abierto.\"",
}
