import json

with open('Localization/en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)
with open('Localization/es.json', 'r', encoding='utf-8') as f:
    es = json.load(f)

new_en = {
    "inn.npc_level_class": "Level {0} {1}",
    "inn.npc_knocks_unconscious": "{0} knocks you unconscious!",
    "inn.giving_gift": "Giving a Gift to {0}",
    "inn.relationship_improves": "(Your relationship improves significantly!)",
    "inn.gift_cost": "(-50 gold)",
    "inn.mood_aggressive": "They look aggressive and dangerous.",
    "inn.mood_friendly": "They seem friendly and approachable.",
    "inn.mood_tired": "They look tired and worn from battle.",
    "inn.mood_relaxed": "They seem relaxed and at ease.",
    "inn.rel_married": "Married",
    "inn.rel_in_love": "In Love",
    "inn.rel_close_friend": "Close Friend",
    "inn.rel_neutral": "Neutral",
    "inn.rel_disliked": "Disliked",
    "inn.rel_hated": "Hated Enemy",
    "inn.drinking_need_gold": "You need at least 20 gold to enter the drinking contest!",
    "inn.drinking_not_enough_patrons": "There aren't enough patrons in the bar for a contest!",
    "inn.drinking_jump_bar": "  You jump up on the bar counter!",
    "inn.drinking_challenge_shout": "  \"Come on you lazy boozers! I challenge you to a drinking contest!\"",
    "inn.drinking_silence": "  There is a sudden silence in the room",
    "inn.drinking_rowdy_approach": "  Then a rowdy bunch of characters make their way toward you...",
    "inn.drinking_choose_drink": "  Choose Your Competition Drink:",
    "inn.drink_ale_desc": "Ale            - Easy going, more rounds to survive",
    "inn.drink_stout_desc": "Stout          - A solid choice for serious drinkers",
    "inn.drink_bomber_desc": "Seth's Bomber  - Rocket fuel! Only the brave dare...",
    "inn.drinking_favourite": "  Favourite in this contest is... ",
    "inn.drinking_round": "  === Beer Round #{0} ===   ({1} contestants remaining)",
    "inn.drinking_drink_name": "  Drinking: {0}",
    "inn.drinking_soberness": "  Your soberness: {0}",
    "inn.drinking_down": " Down your drink!",
    "inn.drinking_bow_out": " Try to bow out gracefully",
    "inn.drinking_what_do": "  What do you do? ",
    "inn.drinking_bow_success1": "  You stand up steadily and bow to the crowd.",
    "inn.drinking_bow_success2": "  \"I know my limits, friends. Good luck to you all!\"",
    "inn.drinking_bow_success3": "  The crowd gives a polite, if disappointed, round of applause.",
    "inn.drinking_bow_fail1": "  You try to stand up but your legs wobble...",
    "inn.drinking_bow_fail2": "  \"Sit back down! You're not going anywhere!\"",
    "inn.drinking_bow_fail3": "  The crowd pushes another drink into your hand!",
    "inn.drinking_take_beer": "  You take your beer...",
    "inn.drinking_spinning": "  The room is spinning!",
    "inn.drinking_laughter": "  You hear evil laughter as you stagger around the room...",
    "inn.drinking_fall": "  ...finally falling heavily to the floor!",
    "inn.drinking_failed": "  You didn't make it, you drunken rat!",
    "inn.drinking_takes_his": " takes his beer...",
    "inn.drinking_takes_her": " takes her beer...",
    "inn.drinking_opp_reels": " starts to reel round in a daze!",
    "inn.drinking_opp_falls": "  Everybody laughs as {0} staggers and falls to the floor!",
    "inn.drinking_bites_dust": "  Another one bites the dust!",
    "inn.drinking_soberness_eval": "  --- Round Soberness Evaluation ---",
    "inn.contest_lasted": "  The contest lasted {0} rounds of {1}.",
    "inn.contest_congrats": "  Congratulations!",
    "inn.contest_stayed_sober": "  You managed to stay sober longer than the rest!",
    "inn.contest_three_cheers": "  Three cheers for the Beer Champion! ",
    "inn.contest_xp_reward": "  You receive {0:N0} experience points!",
    "inn.contest_gold_reward": "  You win {0:N0} gold from the prize pot!",
    "inn.contest_passed_out": "  You passed out in round {0}!",
    "inn.contest_headache": "  You wake up later with a splitting headache.",
    "inn.contest_winner": "  {0} won the contest after {1} rounds!",
    "inn.contest_no_winner": "  Nobody managed to stay standing! No winner was found.",
    "inn.contest_consolation_xp": "  You earned {0:N0} experience for participating.",
    "inn.sober_sober": "Sober",
    "inn.sober_tipsy": "Tipsy",
    "inn.sober_dizzy": "Dizzy",
    "inn.sober_wasted": "Wasted",
    "inn.sober_blind_drunk": "Blind Drunk!",
}

new_es = {
    "inn.npc_level_class": "Nivel {0} {1}",
    "inn.npc_knocks_unconscious": "\u00a1{0} te deja inconsciente!",
    "inn.giving_gift": "Dando un regalo a {0}",
    "inn.relationship_improves": "(\u00a1Tu relaci\u00f3n mejora significativamente!)",
    "inn.gift_cost": "(-50 oro)",
    "inn.mood_aggressive": "Se ven agresivos y peligrosos.",
    "inn.mood_friendly": "Parecen amigables y accesibles.",
    "inn.mood_tired": "Se ven cansados y agotados.",
    "inn.mood_relaxed": "Parecen relajados y tranquilos.",
    "inn.rel_married": "Casado/a",
    "inn.rel_in_love": "Enamorado/a",
    "inn.rel_close_friend": "Amigo/a Cercano/a",
    "inn.rel_neutral": "Neutral",
    "inn.rel_disliked": "Antip\u00e1tico/a",
    "inn.rel_hated": "Enemigo/a Odiado/a",
    "inn.drinking_need_gold": "\u00a1Necesitas al menos 20 de oro para el concurso!",
    "inn.drinking_not_enough_patrons": "\u00a1No hay suficientes clientes para un concurso!",
    "inn.drinking_jump_bar": "  \u00a1Saltas sobre el mostrador del bar!",
    "inn.drinking_challenge_shout": "  \"\u00a1Vamos, vagos! \u00a1Los desaf\u00edo a un concurso de bebida!\"",
    "inn.drinking_silence": "  Hay un silencio repentino en la sala",
    "inn.drinking_rowdy_approach": "  Entonces un grupo ruidoso se acerca hacia ti...",
    "inn.drinking_choose_drink": "  Elige tu bebida de competici\u00f3n:",
    "inn.drink_ale_desc": "Cerveza        - Suave, m\u00e1s rondas para sobrevivir",
    "inn.drink_stout_desc": "Stout          - Una buena elecci\u00f3n para bebedores serios",
    "inn.drink_bomber_desc": "Bomba de Seth  - \u00a1Combustible! Solo los valientes...",
    "inn.drinking_favourite": "  El favorito en este concurso es... ",
    "inn.drinking_round": "  === Ronda #{0} ===   ({1} concursantes restantes)",
    "inn.drinking_drink_name": "  Bebiendo: {0}",
    "inn.drinking_soberness": "  Tu sobriedad: {0}",
    "inn.drinking_down": " \u00a1Bebe tu trago!",
    "inn.drinking_bow_out": " Intentar retirarse con gracia",
    "inn.drinking_what_do": "  \u00bfQu\u00e9 haces? ",
    "inn.drinking_bow_success1": "  Te levantas firmemente y haces una reverencia.",
    "inn.drinking_bow_success2": "  \"Conozco mis l\u00edmites, amigos. \u00a1Buena suerte!\"",
    "inn.drinking_bow_success3": "  La multitud da un aplauso educado.",
    "inn.drinking_bow_fail1": "  Intentas levantarte pero tus piernas tiemblan...",
    "inn.drinking_bow_fail2": "  \"\u00a1Si\u00e9ntate! \u00a1No vas a ninguna parte!\"",
    "inn.drinking_bow_fail3": "  \u00a1La multitud te pone otra bebida en la mano!",
    "inn.drinking_take_beer": "  Tomas tu cerveza...",
    "inn.drinking_spinning": "  \u00a1La habitaci\u00f3n est\u00e1 girando!",
    "inn.drinking_laughter": "  Escuchas risas malvadas mientras tambaleas...",
    "inn.drinking_fall": "  ...\u00a1finalmente cayendo al suelo!",
    "inn.drinking_failed": "  \u00a1No lo lograste, rata borracha!",
    "inn.drinking_takes_his": " toma su cerveza...",
    "inn.drinking_takes_her": " toma su cerveza...",
    "inn.drinking_opp_reels": " \u00a1empieza a tambalearse aturdido!",
    "inn.drinking_opp_falls": "  \u00a1Todos se r\u00eden mientras {0} cae al suelo!",
    "inn.drinking_bites_dust": "  \u00a1Otro que muerde el polvo!",
    "inn.drinking_soberness_eval": "  --- Evaluaci\u00f3n de Sobriedad ---",
    "inn.contest_lasted": "  El concurso dur\u00f3 {0} rondas de {1}.",
    "inn.contest_congrats": "  \u00a1Felicidades!",
    "inn.contest_stayed_sober": "  \u00a1Lograste mantenerte sobrio m\u00e1s que el resto!",
    "inn.contest_three_cheers": "  \u00a1Tres hurras por el Campe\u00f3n de la Cerveza! ",
    "inn.contest_xp_reward": "  \u00a1Recibes {0:N0} puntos de experiencia!",
    "inn.contest_gold_reward": "  \u00a1Ganas {0:N0} de oro del pozo de premios!",
    "inn.contest_passed_out": "  \u00a1Te desmayaste en la ronda {0}!",
    "inn.contest_headache": "  Te despiertas con un terrible dolor de cabeza.",
    "inn.contest_winner": "  \u00a1{0} gan\u00f3 el concurso despu\u00e9s de {1} rondas!",
    "inn.contest_no_winner": "  \u00a1Nadie logr\u00f3 mantenerse en pie!",
    "inn.contest_consolation_xp": "  Ganaste {0:N0} de experiencia por participar.",
    "inn.sober_sober": "Sobrio",
    "inn.sober_tipsy": "Achispado",
    "inn.sober_dizzy": "Mareado",
    "inn.sober_wasted": "Ebrio",
    "inn.sober_blind_drunk": "\u00a1Borracho Perdido!",
}

for k, v in new_en.items():
    en[k] = v
for k, v in new_es.items():
    es[k] = v

with open('Localization/en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, ensure_ascii=False, indent=2)
with open('Localization/es.json', 'w', encoding='utf-8') as f:
    json.dump(es, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_en)} en keys, {len(new_es)} es keys. en: {len(en)}, es: {len(es)}")
