import json

with open('Localization/en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)
with open('Localization/es.json', 'r', encoding='utf-8') as f:
    es = json.load(f)

new_en = {
    # Table headers
    "castle.header_num": "#",
    "castle.header_name": "Name",
    "castle.header_rank": "Rank",
    "castle.header_loyalty": "Loyalty",
    "castle.header_crime": "Crime",
    "castle.header_days_left": "Days Left",
    "castle.header_sentence": "Sentence",
    "castle.header_served": "Served",
    "castle.header_bail": "Bail",
    "castle.header_type": "Type",
    "castle.header_from": "From",
    "castle.header_subject": "Subject",
    "castle.header_status": "Status",
    "castle.header_salary": "Salary",
    "castle.header_level": "Level",
    "castle.header_hp": "HP",
    "castle.header_strength": "Strength",
    "castle.header_lvl": "Lvl",
    "castle.header_str": "STR",
    "castle.header_def": "DEF",
    "castle.header_cost": "Cost",
    "castle.header_feed": "Feed/Day",
    "castle.header_title": "Title",
    "castle.header_reign": "Reign",
    "castle.header_end": "End",
    "castle.header_age": "Age",
    "castle.header_sex": "Sex",
    "castle.header_claim": "Claim",
    "castle.header_race": "Race",
    "castle.header_happy": "Happy",
    "castle.header_dowry": "Dowry",
    "castle.header_faction_benefit": "Faction Benefit",
    "castle.header_faction": "Faction",
    "castle.header_influence": "Influence",
    "castle.header_role": "Role",

    # Royal decree
    "castle.royal_decree": "By royal decree of {0} {1}:",

    # Orphanage
    "castle.orphan_summary": "Orphans: {0}/{1}   Daily care cost: {2} gold ({3} per child)",
    "castle.orphan_age_sex_happy": "  Age: {0}   Sex: {1}   Happiness: {2}%",
    "castle.orphan_boy": "Boy",
    "castle.orphan_girl": "Girl",
    "castle.orphan_type_orphaned": "  Type: Orphaned (both parents deceased)",
    "castle.orphan_mother": "  Mother: {0}",
    "castle.orphan_father": "  Father: {0}",
    "castle.orphan_race": "  Race: {0}",
    "castle.orphan_temperament": "  Temperament: {0} ({1})",
    "castle.orphan_ready": "  Status: Ready for commission (age {0}+)",
    "castle.orphan_type_adopted": "  Type: Adopted (taken in by the crown)",
    "castle.orphan_arrived": "  Arrived: {0}",
    "castle.orphan_no_eligible": "No real orphans age {0}+ available for commission.",
    "castle.orphan_insuff_treasury": "Insufficient treasury! Need {0} gold for training costs.",
    "castle.orphan_entry": "  {0}. {1} (Age {2}, {3}, {4})",
    "castle.orphan_commission_as": "Commission {0} as:",
    "castle.orphan_treasury_minus": "Treasury: -{0} gold",
    "castle.orphan_merc_insuff": "Insufficient treasury! Need {0} gold.",
    "castle.orphan_full": "The orphanage is full ({0} children).",
    "castle.orphan_adopt_insuff": "Insufficient treasury funds! Need {0} gold to cover intake costs.",
    "castle.orphan_treasury_balance": "Treasury: {0} gold",
    "castle.orphan_happy_boost": "Orphan happiness increased by {0}%!",

    # Marriage
    "castle.already_married": "You are already married to {0}.",
    "castle.married_on": "Married on: {0}",
    "castle.spouse_happiness": "Spouse's happiness: {0}%",
    "castle.original_faction": "Original faction: {0}",
    "castle.send_proposal": "You send a royal proposal to {0}...",
    "castle.dowry_received": "Dowry received: {0} gold!",
    "castle.faction_loyalty_up": "The {0} faction's loyalty has increased!",
    "castle.spouse_pleased": "Your spouse is pleased! Happiness +{0}%",
    "castle.faction_turn_against": "The {0} faction will turn against you.",
    "castle.divorced": "You have divorced {0}.",
    "castle.faction_furious": "The {0} faction is furious!",

    # Politics
    "castle.foiled_plot": "FOILED: {0} plot by {1}",
    "castle.spies_report": "Your spies report {0} rumor(s) of intrigue...",
    "castle.arrested": "The conspirators have been arrested and imprisoned! (-{0}g)",
    "castle.promote_which": "Promote which court member? (Cost: {0}g from treasury)",
    "castle.current_heir": "Current designated heir: {0}",
    "castle.max_bodyguards": "Maximum bodyguards: {0}",
    "castle.max_bodyguards_already": "You already have {0} bodyguards \u2014 the maximum allowed.",
    "castle.need_gold_merc": "You need {0} gold to hire a mercenary. You have {1}g.",

    # Mercenary details
    "castle.merc_role": "  Role: {0} ({1})  Level: {2}",
    "castle.merc_hp_str_def": "  HP: {0}  STR: {1}  DEF: {2}",
    "castle.merc_weap_arm": "  Weapon Power: {0}  Armor Power: {1}",
    "castle.merc_mana_potions": "  Mana: {0}  Potions: {1}",
    "castle.merc_cost": "  Cost: {0} gold. Remaining: {1}g",
    "castle.merc_mp": " MP: {0}/{1}",

    # Bodyguard menu
    "castle.hire_merc_btn": "ire Mercenary ({0}g)   ",
    "castle.dismiss_btn": "ismiss   ",
    "castle.return_btn": "eturn",

    # Quest/bounty
    "castle.quest_reward": "    Reward: {0}",
    "castle.quest_comment": "    {0}",
    "castle.quest_objective": "Objective: {0}",
    "castle.quest_target": "Target: {0} x{1}",
    "castle.crown_standing": "The Crown appreciates your loyalty. (+{0} Crown standing)",

    # Team
    "castle.already_member": "You are currently a member of '{0}'.",
    "castle.left_team": "You have left '{0}' to pursue the crown.",
    "castle.must_defeat": "You must defeat {0} {1} in combat.",
    "castle.warn_monsters": "WARNING: You must first defeat {0} Monster Guards!",
    "castle.warn_guards": "WARNING: You must also defeat {0} Royal Guards!",

    # Solo throne fight
    "castle.strike_monster": "You strike the {0} for {1} damage! (Monster HP: {2})",
    "castle.monster_claws": "The {0} claws you for {1} damage! (Your HP: {2})",
    "castle.slain_by_monster": "You were slain by the {0}!",
    "castle.defeated_monster": "You defeated the {0}!",
    "castle.slip_past": "As a former guard, you slip past your own post...",
    "castle.guard_stats": "Level {0} | STR: {1} | DEF: {2} | Loyalty: {3}%",
    "castle.strike_guard": "You strike {0} for {1} damage! (Guard HP: {2})",
    "castle.defeated_by_guard": "You were defeated by {0}!",
    "castle.defeated_guard": "You defeated {0}!",
    "castle.king_stats": "Level {0} | STR: {1} | DEF: {2} | HP: {3}",
    "castle.strike_king": "You strike for {0} damage! (King HP: {1})",
    "castle.victory": "              VICTORY!",

    # NPC info in lists
    "castle.npc_lv": " Lv{0}",

    # Crown shop items
    "castle.crown_blade": "Crown Blade         {0}g   WeapPow {1}",
    "castle.royal_plate": "Royal Guard Plate   {0}g   ArmPow {1}",
    "castle.crown_shield": "Crown Shield        {0}g   ArmPow {1}",
    "castle.signet_ring": "Signet Ring         {0}g   +5 CHA, +5 STR",

    # Siege
    "castle.siege_king": "  King: {0} {1}",
    "castle.siege_monster_guards": "  Monster Guards: {0}",
    "castle.siege_royal_guards": "  Royal Guards: {0}",
    "castle.siege_total_defenders": "  Total Defenders: {0}",
    "castle.siege_you": "  YOU \u2014 {0} (Lv {1} {2})",
    "castle.siege_begins_sr": "THE SIEGE BEGINS!",
    "castle.siege_begins": "           THE SIEGE BEGINS!",
    "castle.team_strikes_monster": "  Your team strikes {0} for {1} damage! (HP: {2})",
    "castle.siege_overwhelmed": "Your siege force was overwhelmed by {0}!",
    "castle.team_strikes_guard": "  Your team strikes {0} for {1}! (HP: {2})",
    "castle.siege_defeated_by": "Your siege force was defeated by {0}!",
    "castle.siege_failed_sr": "THE SIEGE HAS FAILED!",
    "castle.siege_failed": "          THE SIEGE HAS FAILED!",
    "castle.siege_guards_defeated_sr": "ALL GUARDS DEFEATED - THE THRONE ROOM AWAITS!",
    "castle.siege_guards_defeated": "          ALL GUARDS DEFEATED \u2014 THE THRONE ROOM AWAITS!",
    "castle.siege_king_stats": "Level {0} | STR: {1} | DEF: {2} | HP: {3}",
    "castle.siege_strike_king": "You strike {0} for {1} damage! (King HP: {2})",
}

new_es = {
    "castle.header_num": "#",
    "castle.header_name": "Nombre",
    "castle.header_rank": "Rango",
    "castle.header_loyalty": "Lealtad",
    "castle.header_crime": "Crimen",
    "castle.header_days_left": "D\u00edas Rest.",
    "castle.header_sentence": "Sentencia",
    "castle.header_served": "Cumplido",
    "castle.header_bail": "Fianza",
    "castle.header_type": "Tipo",
    "castle.header_from": "De",
    "castle.header_subject": "Asunto",
    "castle.header_status": "Estado",
    "castle.header_salary": "Salario",
    "castle.header_level": "Nivel",
    "castle.header_hp": "PV",
    "castle.header_strength": "Fuerza",
    "castle.header_lvl": "Niv",
    "castle.header_str": "FUE",
    "castle.header_def": "DEF",
    "castle.header_cost": "Costo",
    "castle.header_feed": "Comida/D\u00eda",
    "castle.header_title": "T\u00edtulo",
    "castle.header_reign": "Reinado",
    "castle.header_end": "Fin",
    "castle.header_age": "Edad",
    "castle.header_sex": "Sexo",
    "castle.header_claim": "Derecho",
    "castle.header_race": "Raza",
    "castle.header_happy": "Feliz",
    "castle.header_dowry": "Dote",
    "castle.header_faction_benefit": "Beneficio Facci\u00f3n",
    "castle.header_faction": "Facci\u00f3n",
    "castle.header_influence": "Influencia",
    "castle.header_role": "Rol",

    "castle.royal_decree": "Por decreto real de {0} {1}:",
    "castle.orphan_summary": "Hu\u00e9rfanos: {0}/{1}   Costo diario: {2} oro ({3} por ni\u00f1o)",
    "castle.orphan_age_sex_happy": "  Edad: {0}   Sexo: {1}   Felicidad: {2}%",
    "castle.orphan_boy": "Ni\u00f1o",
    "castle.orphan_girl": "Ni\u00f1a",
    "castle.orphan_type_orphaned": "  Tipo: Hu\u00e9rfano (ambos padres fallecidos)",
    "castle.orphan_mother": "  Madre: {0}",
    "castle.orphan_father": "  Padre: {0}",
    "castle.orphan_race": "  Raza: {0}",
    "castle.orphan_temperament": "  Temperamento: {0} ({1})",
    "castle.orphan_ready": "  Estado: Listo para comisi\u00f3n (edad {0}+)",
    "castle.orphan_type_adopted": "  Tipo: Adoptado (acogido por la corona)",
    "castle.orphan_arrived": "  Llegada: {0}",
    "castle.orphan_no_eligible": "No hay hu\u00e9rfanos reales de edad {0}+ disponibles para comisi\u00f3n.",
    "castle.orphan_insuff_treasury": "\u00a1Tesorer\u00eda insuficiente! Se necesitan {0} oro para costos de entrenamiento.",
    "castle.orphan_entry": "  {0}. {1} (Edad {2}, {3}, {4})",
    "castle.orphan_commission_as": "Comisionar a {0} como:",
    "castle.orphan_treasury_minus": "Tesorer\u00eda: -{0} oro",
    "castle.orphan_merc_insuff": "\u00a1Tesorer\u00eda insuficiente! Se necesitan {0} oro.",
    "castle.orphan_full": "El orfanato est\u00e1 lleno ({0} ni\u00f1os).",
    "castle.orphan_adopt_insuff": "\u00a1Fondos insuficientes en la tesorer\u00eda! Se necesitan {0} oro para costos de ingreso.",
    "castle.orphan_treasury_balance": "Tesorer\u00eda: {0} oro",
    "castle.orphan_happy_boost": "\u00a1Felicidad del hu\u00e9rfano aumentada en {0}%!",

    "castle.already_married": "Ya est\u00e1s casado/a con {0}.",
    "castle.married_on": "Casado/a el: {0}",
    "castle.spouse_happiness": "Felicidad del c\u00f3nyuge: {0}%",
    "castle.original_faction": "Facci\u00f3n original: {0}",
    "castle.send_proposal": "Env\u00edas una propuesta real a {0}...",
    "castle.dowry_received": "\u00a1Dote recibida: {0} oro!",
    "castle.faction_loyalty_up": "\u00a1La lealtad de la facci\u00f3n {0} ha aumentado!",
    "castle.spouse_pleased": "\u00a1Tu c\u00f3nyuge est\u00e1 complacido/a! Felicidad +{0}%",
    "castle.faction_turn_against": "La facci\u00f3n {0} se volver\u00e1 en tu contra.",
    "castle.divorced": "Te has divorciado de {0}.",
    "castle.faction_furious": "\u00a1La facci\u00f3n {0} est\u00e1 furiosa!",

    "castle.foiled_plot": "FRUSTRADO: Complot {0} por {1}",
    "castle.spies_report": "Tus esp\u00edas reportan {0} rumor(es) de intriga...",
    "castle.arrested": "\u00a1Los conspiradores han sido arrestados y encarcelados! (-{0}g)",
    "castle.promote_which": "\u00bfPromover a qu\u00e9 miembro de la corte? (Costo: {0}g de la tesorer\u00eda)",
    "castle.current_heir": "Heredero designado actual: {0}",
    "castle.max_bodyguards": "M\u00e1ximo de guardaespaldas: {0}",
    "castle.max_bodyguards_already": "Ya tienes {0} guardaespaldas \u2014 el m\u00e1ximo permitido.",
    "castle.need_gold_merc": "Necesitas {0} oro para contratar un mercenario. Tienes {1}g.",

    "castle.merc_role": "  Rol: {0} ({1})  Nivel: {2}",
    "castle.merc_hp_str_def": "  PV: {0}  FUE: {1}  DEF: {2}",
    "castle.merc_weap_arm": "  Poder de Arma: {0}  Poder de Armadura: {1}",
    "castle.merc_mana_potions": "  Man\u00e1: {0}  Pociones: {1}",
    "castle.merc_cost": "  Costo: {0} oro. Restante: {1}g",
    "castle.merc_mp": " PM: {0}/{1}",

    "castle.hire_merc_btn": "ontratar Mercenario ({0}g)   ",
    "castle.dismiss_btn": "espedir   ",
    "castle.return_btn": "olver",

    "castle.quest_reward": "    Recompensa: {0}",
    "castle.quest_comment": "    {0}",
    "castle.quest_objective": "Objetivo: {0}",
    "castle.quest_target": "Objetivo: {0} x{1}",
    "castle.crown_standing": "La Corona aprecia tu lealtad. (+{0} reputaci\u00f3n Corona)",

    "castle.already_member": "Actualmente eres miembro de '{0}'.",
    "castle.left_team": "Has dejado '{0}' para perseguir la corona.",
    "castle.must_defeat": "Debes derrotar a {0} {1} en combate.",
    "castle.warn_monsters": "\u00a1ADVERTENCIA: Primero debes derrotar a {0} Guardias Monstruo!",
    "castle.warn_guards": "\u00a1ADVERTENCIA: Tambi\u00e9n debes derrotar a {0} Guardias Reales!",

    "castle.strike_monster": "\u00a1Golpeas a {0} por {1} de da\u00f1o! (PV Monstruo: {2})",
    "castle.monster_claws": "\u00a1{0} te ara\u00f1a por {1} de da\u00f1o! (Tus PV: {2})",
    "castle.slain_by_monster": "\u00a1Fuiste asesinado por {0}!",
    "castle.defeated_monster": "\u00a1Derrotaste a {0}!",
    "castle.slip_past": "Como antiguo guardia, te escabulles por tu propio puesto...",
    "castle.guard_stats": "Nivel {0} | FUE: {1} | DEF: {2} | Lealtad: {3}%",
    "castle.strike_guard": "\u00a1Golpeas a {0} por {1} de da\u00f1o! (PV Guardia: {2})",
    "castle.defeated_by_guard": "\u00a1Fuiste derrotado por {0}!",
    "castle.defeated_guard": "\u00a1Derrotaste a {0}!",
    "castle.king_stats": "Nivel {0} | FUE: {1} | DEF: {2} | PV: {3}",
    "castle.strike_king": "\u00a1Golpeas por {0} de da\u00f1o! (PV Rey: {1})",
    "castle.victory": "              \u00a1VICTORIA!",

    "castle.npc_lv": " Nv{0}",

    "castle.crown_blade": "Espada Corona       {0}g   PoderArma {1}",
    "castle.royal_plate": "Placa Guardia Real  {0}g   PoderArm {1}",
    "castle.crown_shield": "Escudo Corona       {0}g   PoderArm {1}",
    "castle.signet_ring": "Anillo Sello        {0}g   +5 CAR, +5 FUE",

    "castle.siege_king": "  Rey: {0} {1}",
    "castle.siege_monster_guards": "  Guardias Monstruo: {0}",
    "castle.siege_royal_guards": "  Guardias Reales: {0}",
    "castle.siege_total_defenders": "  Total Defensores: {0}",
    "castle.siege_you": "  T\u00da \u2014 {0} (Nv {1} {2})",
    "castle.siege_begins_sr": "\u00a1EL ASEDIO COMIENZA!",
    "castle.siege_begins": "           \u00a1EL ASEDIO COMIENZA!",
    "castle.team_strikes_monster": "  \u00a1Tu equipo golpea a {0} por {1} de da\u00f1o! (PV: {2})",
    "castle.siege_overwhelmed": "\u00a1Tu fuerza de asedio fue abrumada por {0}!",
    "castle.team_strikes_guard": "  \u00a1Tu equipo golpea a {0} por {1}! (PV: {2})",
    "castle.siege_defeated_by": "\u00a1Tu fuerza de asedio fue derrotada por {0}!",
    "castle.siege_failed_sr": "\u00a1EL ASEDIO HA FRACASADO!",
    "castle.siege_failed": "          \u00a1EL ASEDIO HA FRACASADO!",
    "castle.siege_guards_defeated_sr": "\u00a1TODOS LOS GUARDIAS DERROTADOS - \u00a1LA SALA DEL TRONO ESPERA!",
    "castle.siege_guards_defeated": "          \u00a1TODOS LOS GUARDIAS DERROTADOS \u2014 \u00a1LA SALA DEL TRONO ESPERA!",
    "castle.siege_king_stats": "Nivel {0} | FUE: {1} | DEF: {2} | PV: {3}",
    "castle.siege_strike_king": "\u00a1Golpeas a {0} por {1} de da\u00f1o! (PV Rey: {2})",
}

for k, v in new_en.items():
    en[k] = v
for k, v in new_es.items():
    es[k] = v

with open('Localization/en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, ensure_ascii=False, indent=2)
with open('Localization/es.json', 'w', encoding='utf-8') as f:
    json.dump(es, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_en)} en keys, {len(new_es)} es keys. en: {len(en)}, es: {len(es)}")
