import json

with open('Localization/en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)
with open('Localization/es.json', 'r', encoding='utf-8') as f:
    es = json.load(f)

new_en = {
    # BaseLocation (2 strings)
    "base.none_independent": "None (Independent)",
    "base.send_to_prompt": "Send to: ",

    # LocationManager - death screen (~11 strings)
    "location.you_have_died": "YOU HAVE DIED!",
    "location.death_vision_fades": "Your vision fades to black as death claims you...",
    "location.resurrections_available": "You have {0} resurrection(s) available!",
    "location.use_resurrection_prompt": "Use a resurrection to avoid penalties? (Y/N): ",
    "location.divine_light": "Divine light surrounds you!",
    "location.resurrected_no_penalty": "You have been fully resurrected with no penalties!",
    "location.death_penalties": "Death Penalties Applied:",
    "location.lost_experience": "  - Lost {0} experience points",
    "location.lost_gold": "  - Lost {0} gold (dropped upon death)",
    "location.monster_defeats": "  - Monster defeats: {0}",
    "location.wake_at_inn": "You wake up at the Inn, nursed back to health by the innkeeper.",
    "location.wounds_healed": "Your wounds have partially healed. (HP: {0}/{1})",
    "location.innkeeper_quote": "\"You're lucky to be alive, friend. Rest up and try again.\"",
    "location.adventure_continues": "Your adventure continues...",
    "location.returning_main_menu": "Returning to main menu...",
    "location.navigating_to": "Navigating to {0}...",
    "location.unknown_destination": "Unknown destination: {0}",
    "location.cannot_go": "You cannot go to {0} from here!",
    "location.unknown_location": "Unknown location '{0}'. Returning to Main Street.",

    # AlignmentSystem (~7 strings)
    "alignment.status_header": "ALIGNMENT STATUS",
    "alignment.chivalry_label": "Chivalry: ",
    "alignment.darkness_label": "Darkness: ",
    "alignment.holy_label": "Holy ",
    "alignment.evil_label": " Evil",
    "alignment.abilities_header": "Alignment Abilities:",

    # HagglingEngine (~12 strings)
    "haggle.header": "HAGGLE",
    "haggle.troll_already_discount": "Hey! I've already given you a discount!",
    "haggle.troll_get_out": "Don't expect any more! Get out!",
    "haggle.give_offer": "Alright, give me an offer: ",
    "haggle.not_serious": "That's not a serious offer!",
    "haggle.got_deal": "Alright {0}! You've got a deal!",
    "haggle.accept_price": "Accept this price? (Y/N): ",
    "haggle.weapon_angry": "You are making me very angry {0}!",
    "haggle.accept_or_leave": "Accept my offer or leave!",
    "haggle.weapon_face_red": "{0}'s face turns unhealthy red...",
    "haggle.armor_damn": "Damn you {0}!",
    "haggle.armor_upset": "{0} seems to be quite upset with your behaviour.",
    "haggle.insist_or_leave": "What are you going to do? Insist once more or leave?",
    "haggle.insist_prompt": "Insist? (Y/N): ",
    "haggle.kicked_out": "You have been kicked out!",
    "haggle.kicked_news": "[NEWS] {0} was kicked out from the {1}!",
    "haggle.end_discussion": "End of discussion.",
    "haggle.weapon_fail_1": "Haha! You think you're funny huh!?",
    "haggle.weapon_fail_2": "Get out of here before I get nasty!",
    "haggle.armor_fail_1": "Stop kidding around and get out, so I can",
    "haggle.armor_fail_2": "do some serious business!",

    # FeatureInteractionSystem (~27 strings - UI only, not lore/narrative)
    "feature.interact_with": "You {0} the {1}...",
    "feature.catches_attention": "Something catches your attention:",
    "feature.knowledge_xp": "This knowledge enlightens you. (+{0} XP)",
    "feature.drawn_to_light": "You feel drawn toward the light... (+{0} Chivalry)",
    "feature.drawn_to_darkness": "You feel drawn toward the darkness... (+{0} Darkness)",
    "feature.sense_presence": "You sense {0}'s presence in these depths...",
    "feature.stat_check": "[{0} Check - DC {1}]",
    "feature.roll_result": "You rolled {0} + {1} ({2} bonus) = {3}",
    "feature.success": "SUCCESS!",
    "feature.failed": "FAILED!",
    "feature.hidden_knowledge": "Your expertise reveals hidden knowledge!",
    "feature.stat_boost": "+{0} {1} for the rest of this floor!",
    "feature.gold_reward": "Your skill is rewarded handsomely! +{0} gold!",
    "feature.find_potions": "You find {0} healing potion{1} hidden inside!",
    "feature.challenge_xp": "The challenge itself teaches you something. +{0} XP!",
    "feature.failure_damage": "Your failure costs you. -{0} HP",
    "feature.nothing_happens": "Nothing happens. Perhaps another approach would work.",
    "feature.learn_mistake": "You learn from your mistake. +{0} XP",
    "feature.what_do_you_do": "What do you do?",
    "feature.walk_away": "Walk away",
    "feature.not_your_concern": "You decide this is not your concern.",
    "feature.wisdom_walk_away": "Sometimes wisdom is knowing when to walk away.",
    "feature.soul_toward_light": "Your soul shifts toward the light... (+{0} Chivalry)",
    "feature.soul_toward_darkness": "Your soul shifts toward the darkness... (+{0} Darkness)",
    "feature.class_training_reveals": "Your training as {0} {1} reveals something others would miss:",
    "feature.spot_weaknesses": "You spot weaknesses in the dungeon's defenses.",
    "feature.next_battle_easier": "The next battle will be easier.",
    "feature.attack_power_bonus": "+{0} Attack Power for next combat!",
    "feature.magical_residue": "Magical residue clings to this place.",
    "feature.absorb_magic": "You absorb what you can.",
    "feature.mana_restored": "+{0} Mana restored!",
    "feature.divine_presence": "Divine presence lingers here. You offer a prayer.",
    "feature.divine_heal": "+{0} HP from divine blessing!",
    "feature.hidden_passages": "You notice hidden passages others would miss.",
    "feature.hidden_supplies": "Someone left supplies for those who know where to look.",
    "feature.poison_vials": "+{0} poison vial{1}! (Total: {2})",
    "feature.coat_blade_hint": "Use [B] Coat Blade during combat to apply a poison.",
    "feature.wilderness_resources": "Your wilderness training helps you find resources.",
    "feature.sellable_materials": "+{0} gold in sellable materials!",
    "feature.herbal_remedy": "+1 herbal remedy!",
    "feature.old_song": "You remember an old song about this place...",
    "feature.melody_secrets": "The melody reveals ancient secrets.",
    "feature.bardic_xp": "+{0} XP from bardic knowledge!",
    "feature.find_useful": "You find something useful.",
    "feature.plus_gold": "+{0} gold!",
    "feature.looks_dangerous": "This looks dangerous, but potentially rewarding.",
    "feature.potential_reward": "Potential reward: {0} gold",
    "feature.potential_risk": "Potential risk: {0} damage",
    "feature.success_chance": "Success chance: {0}% (based on DEX/INT)",
    "feature.take_risk": "Do you take the risk? (Y/N)",
    "feature.extract_treasure": "You carefully extract the treasure!",
    "feature.trap_springs": "A trap springs!",
    "feature.minus_hp": "-{0} HP!",
    "feature.grabbed_gold": "But you managed to grab {0} gold!",
    "feature.wisdom_leave": "Wisdom is knowing when to walk away.",
    "feature.leave_undisturbed": "You leave the treasure undisturbed.",
    "feature.feels_familiar": "Something about this feels... familiar.",
    "feature.memory_surfaces": "A fragment of memory surfaces:",
    "feature.memory_fades": "The memory fades, but something remains...",
    "feature.everything_stops": "For a moment, everything stops.",
    "feature.feel_different": "You feel... different. More awake.",
    "feature.find_gold": "You find {0} gold!",
    "feature.learn_something": "You learn something. +{0} XP",
    "feature.nothing_interest": "Nothing of interest here.",
    "feature.find_healing_potion": "You find a healing potion!",
    "feature.trap_damage": "A trap! You take {0} damage!",
}

new_es = {
    # BaseLocation
    "base.none_independent": "Ninguno (Independiente)",
    "base.send_to_prompt": "Enviar a: ",

    # LocationManager
    "location.you_have_died": "HAS MUERTO!",
    "location.death_vision_fades": "Tu vision se desvanece en la oscuridad mientras la muerte te reclama...",
    "location.resurrections_available": "Tienes {0} resurreccion(es) disponible(s)!",
    "location.use_resurrection_prompt": "Usar una resurreccion para evitar penalizaciones? (S/N): ",
    "location.divine_light": "La luz divina te rodea!",
    "location.resurrected_no_penalty": "Has sido resucitado completamente sin penalizaciones!",
    "location.death_penalties": "Penalizaciones por muerte aplicadas:",
    "location.lost_experience": "  - Perdiste {0} puntos de experiencia",
    "location.lost_gold": "  - Perdiste {0} oro (se cayo al morir)",
    "location.monster_defeats": "  - Derrotas por monstruos: {0}",
    "location.wake_at_inn": "Despiertas en la Posada, atendido por el posadero.",
    "location.wounds_healed": "Tus heridas han sanado parcialmente. (PV: {0}/{1})",
    "location.innkeeper_quote": "\"Tienes suerte de estar vivo, amigo. Descansa e intentalo de nuevo.\"",
    "location.adventure_continues": "Tu aventura continua...",
    "location.returning_main_menu": "Regresando al menu principal...",
    "location.navigating_to": "Navegando a {0}...",
    "location.unknown_destination": "Destino desconocido: {0}",
    "location.cannot_go": "No puedes ir a {0} desde aqui!",
    "location.unknown_location": "Ubicacion desconocida '{0}'. Regresando a la Calle Principal.",

    # AlignmentSystem
    "alignment.status_header": "ESTADO DE ALINEAMIENTO",
    "alignment.chivalry_label": "Caballeria: ",
    "alignment.darkness_label": "Oscuridad: ",
    "alignment.holy_label": "Santo ",
    "alignment.evil_label": " Malvado",
    "alignment.abilities_header": "Habilidades de Alineamiento:",

    # HagglingEngine
    "haggle.header": "REGATEO",
    "haggle.troll_already_discount": "Eh! Ya te di un descuento!",
    "haggle.troll_get_out": "No esperes mas! Fuera!",
    "haggle.give_offer": "Bien, hazme una oferta: ",
    "haggle.not_serious": "Eso no es una oferta seria!",
    "haggle.got_deal": "Muy bien {0}! Trato hecho!",
    "haggle.accept_price": "Aceptar este precio? (S/N): ",
    "haggle.weapon_angry": "Me estas haciendo enojar mucho {0}!",
    "haggle.accept_or_leave": "Acepta mi oferta o vete!",
    "haggle.weapon_face_red": "La cara de {0} se pone roja...",
    "haggle.armor_damn": "Maldito seas {0}!",
    "haggle.armor_upset": "{0} parece estar bastante molesto con tu comportamiento.",
    "haggle.insist_or_leave": "Que vas a hacer? Insistir una vez mas o irte?",
    "haggle.insist_prompt": "Insistir? (S/N): ",
    "haggle.kicked_out": "Te han echado!",
    "haggle.kicked_news": "[NOTICIAS] {0} fue echado de la {1}!",
    "haggle.end_discussion": "Fin de la discusion.",
    "haggle.weapon_fail_1": "Jaja! Crees que eres gracioso!?",
    "haggle.weapon_fail_2": "Sal de aqui antes de que me ponga feo!",
    "haggle.armor_fail_1": "Deja de bromear y vete, para que pueda",
    "haggle.armor_fail_2": "hacer negocios serios!",

    # FeatureInteractionSystem
    "feature.interact_with": "Tu {0} el/la {1}...",
    "feature.catches_attention": "Algo llama tu atencion:",
    "feature.knowledge_xp": "Este conocimiento te ilumina. (+{0} XP)",
    "feature.drawn_to_light": "Te sientes atraido hacia la luz... (+{0} Caballeria)",
    "feature.drawn_to_darkness": "Te sientes atraido hacia la oscuridad... (+{0} Oscuridad)",
    "feature.sense_presence": "Sientes la presencia de {0} en estas profundidades...",
    "feature.stat_check": "[Prueba de {0} - DC {1}]",
    "feature.roll_result": "Sacaste {0} + {1} (bonus de {2}) = {3}",
    "feature.success": "EXITO!",
    "feature.failed": "FALLASTE!",
    "feature.hidden_knowledge": "Tu experiencia revela conocimiento oculto!",
    "feature.stat_boost": "+{0} {1} para el resto de este piso!",
    "feature.gold_reward": "Tu habilidad es recompensada generosamente! +{0} oro!",
    "feature.find_potions": "Encuentras {0} pocion(es) de curacion escondida(s)!",
    "feature.challenge_xp": "El desafio mismo te ensena algo. +{0} XP!",
    "feature.failure_damage": "Tu fallo te cuesta. -{0} PV",
    "feature.nothing_happens": "No pasa nada. Quizas otro enfoque funcionaria.",
    "feature.learn_mistake": "Aprendes de tu error. +{0} XP",
    "feature.what_do_you_do": "Que haces?",
    "feature.walk_away": "Alejarse",
    "feature.not_your_concern": "Decides que esto no es asunto tuyo.",
    "feature.wisdom_walk_away": "A veces la sabiduria es saber cuando alejarse.",
    "feature.soul_toward_light": "Tu alma se inclina hacia la luz... (+{0} Caballeria)",
    "feature.soul_toward_darkness": "Tu alma se inclina hacia la oscuridad... (+{0} Oscuridad)",
    "feature.class_training_reveals": "Tu entrenamiento como {0} {1} revela algo que otros no verian:",
    "feature.spot_weaknesses": "Detectas debilidades en las defensas de la mazmorra.",
    "feature.next_battle_easier": "La proxima batalla sera mas facil.",
    "feature.attack_power_bonus": "+{0} Poder de Ataque para el proximo combate!",
    "feature.magical_residue": "Residuo magico se adhiere a este lugar.",
    "feature.absorb_magic": "Absorbes lo que puedes.",
    "feature.mana_restored": "+{0} Mana restaurado!",
    "feature.divine_presence": "Presencia divina perdura aqui. Ofreces una oracion.",
    "feature.divine_heal": "+{0} PV de bendicion divina!",
    "feature.hidden_passages": "Notas pasajes ocultos que otros no verian.",
    "feature.hidden_supplies": "Alguien dejo suministros para quienes saben donde buscar.",
    "feature.poison_vials": "+{0} frasco(s) de veneno! (Total: {2})",
    "feature.coat_blade_hint": "Usa [B] Envenar Hoja durante el combate para aplicar un veneno.",
    "feature.wilderness_resources": "Tu entrenamiento en la naturaleza te ayuda a encontrar recursos.",
    "feature.sellable_materials": "+{0} oro en materiales vendibles!",
    "feature.herbal_remedy": "+1 remedio herbal!",
    "feature.old_song": "Recuerdas una vieja cancion sobre este lugar...",
    "feature.melody_secrets": "La melodia revela secretos antiguos.",
    "feature.bardic_xp": "+{0} XP de conocimiento bardico!",
    "feature.find_useful": "Encuentras algo util.",
    "feature.plus_gold": "+{0} oro!",
    "feature.looks_dangerous": "Esto parece peligroso, pero potencialmente gratificante.",
    "feature.potential_reward": "Recompensa potencial: {0} oro",
    "feature.potential_risk": "Riesgo potencial: {0} dano",
    "feature.success_chance": "Probabilidad de exito: {0}% (basado en DES/INT)",
    "feature.take_risk": "Tomas el riesgo? (S/N)",
    "feature.extract_treasure": "Extraes el tesoro con cuidado!",
    "feature.trap_springs": "Una trampa se activa!",
    "feature.minus_hp": "-{0} PV!",
    "feature.grabbed_gold": "Pero lograste agarrar {0} oro!",
    "feature.wisdom_leave": "La sabiduria es saber cuando alejarse.",
    "feature.leave_undisturbed": "Dejas el tesoro sin tocar.",
    "feature.feels_familiar": "Algo en esto se siente... familiar.",
    "feature.memory_surfaces": "Un fragmento de memoria emerge:",
    "feature.memory_fades": "El recuerdo se desvanece, pero algo permanece...",
    "feature.everything_stops": "Por un momento, todo se detiene.",
    "feature.feel_different": "Te sientes... diferente. Mas despierto.",
    "feature.find_gold": "Encuentras {0} oro!",
    "feature.learn_something": "Aprendes algo. +{0} XP",
    "feature.nothing_interest": "Nada interesante aqui.",
    "feature.find_healing_potion": "Encuentras una pocion de curacion!",
    "feature.trap_damage": "Una trampa! Recibes {0} de dano!",
}

for k, v in new_en.items():
    en[k] = v
for k, v in new_es.items():
    es[k] = v

with open('Localization/en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, ensure_ascii=False, indent=2)
with open('Localization/es.json', 'w', encoding='utf-8') as f:
    json.dump(es, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_en)} en keys, {len(new_es)} es keys")
