import json

with open('Localization/en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)
with open('Localization/es.json', 'r', encoding='utf-8') as f:
    es = json.load(f)

new_en = {
    # SleepAtInn
    "inn.sleep_not_late": "It's not late enough to sleep for the night. Try waiting until evening.",
    "inn.sleep_room_shown": "The innkeeper shows you to a small room upstairs...",
    "inn.sleep_settle_in": "You settle into the straw mattress and close your eyes.",
    "inn.sleep_dark_memories": "Dark memories invade your dreams, leaving you less than fully rested...",
    "inn.sleep_refreshed": "You wake feeling completely refreshed!",
    "inn.sleep_recover_mana": "Recovered {0} HP, {1} mana. ({2}% recovery)",
    "inn.sleep_recover_stamina": "Recovered {0} HP, {1} stamina. ({2}% recovery)",
    "inn.sleep_dreams_unfold": "As sleep takes you, dreams unfold...",
    "inn.sleep_drift_off": "You drift off to sleep...",
    "inn.sleep_new_day": "A new day dawns. (Day {0})",
    # OrderFood
    "inn.food_hearty_meal": "You order a hearty meal of roasted meat and bread.",
    "inn.food_stamina_boost": "The food fills your belly and boosts your stamina!",
    "inn.food_hp_recover": "You also recover {0} HP from the nourishing meal.",
    # ApproachCompanions
    "inn.no_companions_available": "There are no strangers looking for adventuring partners right now.",
    "inn.companions_watching": "In the shadowy corners of the inn, several figures seem to be watching you...",
    "inn.return_to_bar": "Return to the bar",
    "inn.approach_who": "Approach who? ",
    # AttemptCompanionRecruitment
    "inn.you_approach": "You approach {0}, {1}...",
    "inn.greetings_traveler": "\"Greetings, traveler. You look like someone who could use help...\"",
    "inn.background_label": "Background: {0}",
    "inn.combat_role_label": "Combat Role: {0}",
    "inn.abilities_label": "Abilities: {0}",
    "inn.recruit_companion": "Recruit this companion",
    "inn.talk_more": "Talk more to learn about them",
    "inn.leave_them_be": "Leave them be",
    "inn.companion_joined": "{0} has joined you as a companion!",
    "inn.companion_fight_by_side": "They will accompany you in the dungeons and fight by your side.",
    "inn.companion_die_warning": "WARNING: Companions can die permanently. Guard them well.",
    "inn.companion_shares_story": "{0} shares their story...",
    "inn.personal_quest_label": "Personal Quest: {0}",
    "inn.nod_return": "You nod to {0} and return to the bar.",
    # ManageParty
    "inn.no_companions_yet": "You don't have any companions yet.",
    "inn.active_companions": "ACTIVE COMPANIONS ({0}/{1}):",
    "inn.no_active_companions": "(No active companions - select from reserves below)",
    "inn.reserve_companions": "RESERVE COMPANIONS:",
    "inn.fallen_companions": "FALLEN COMPANIONS:",
    "inn.died_label": "Died: {0}",
    "inn.options": "Options:",
    "inn.talk_to": "Talk to {0}",
    "inn.switch_companions": "Switch active companions",
    # SwitchActiveCompanions
    "inn.companion_limit": "You can have up to {0} companions active in the dungeon.",
    "inn.companion_warning": "Active companions fight alongside you but can also be hurt or killed.",
    "inn.select_to_activate": "Select companions to activate (enter numbers separated by spaces):",
    "inn.example_activate": "Example: '1 3' to activate companions 1 and 3",
    "inn.enter_nothing": "Enter nothing to keep current selection",
    "inn.activate_prompt": "Activate: ",
    "inn.no_changes": "No changes made.",
    "inn.no_valid_selected": "No valid companions selected. No changes made.",
    "inn.party_updated": "Party updated!",
    "inn.now_active": "{0} is now active.",
    "inn.update_failed": "Failed to update party.",
    # TalkToRecruitedCompanion
    "inn.background": "Background:",
    "inn.stats": "Stats:",
    "inn.level_role": "Level: {0} | Role: {1}",
    "inn.hp_atk_def": "HP: {0}  |  ATK: {1}  |  DEF: {2}",
    "inn.items_equipped": "({0} item{1} equipped — stats include gear bonuses)",
    "inn.begin_quest": "Begin Personal Quest: {0}",
    "inn.discuss_progress": "Discuss Quest Progress",
    "inn.deepen_bond_today": "Deepen your bond (already visited today)",
    "inn.spend_time_max": "Spend time together (Max bond)",
    "inn.deepen_bond": "Deepen your bond...",
    "inn.give_a_gift": "Give a gift",
    "inn.view_history": "View history together",
    "inn.manage_equipment": "Manage Equipment",
    "inn.manage_skills": "Manage Combat Skills",
    "inn.return": "Return",
    # HandlePersonalQuestInteraction
    "inn.speaks_quietly": "{0} speaks quietly:",
    "inn.accept_quest": "Accept this quest",
    "inn.not_yet": "Not yet",
    "inn.will_you_help": "Will you help? ",
    "inn.quest_begun": "Quest Begun: {0}",
    "inn.nods_gratefully": "{0} nods gratefully.",
    "inn.quest_in_progress": "Quest Status: In Progress",
    "inn.seek_clues": "Seek clues in the dungeon depths...",
    # HandleRomanceInteraction
    "inn.already_spent_time": "You've already spent quality time with {0} today.",
    "inn.perhaps_tomorrow": "Perhaps tomorrow you can share another moment together.",
    "inn.quiet_corner": "You and {0} find a quiet corner to talk.",
    "inn.tavern_fades": "The noise of the tavern fades into background murmur.",
    "inn.romance_1": "You share a moment of understanding with {0}.",
    "inn.romance_2": "Your eyes meet, and something unspoken passes between you.",
    "inn.romance_3": "{0}'s hand brushes against yours.",
    "inn.romance_4": "The world seems to shrink to just the two of you.",
    "inn.romance_5": "{0} leans closer, voice soft.",
    "inn.romance_default": "The bond between you and {0} deepens.",
    "inn.bond_max": "Your bond with {0} is as deep as it can be.",
    "inn.bond_stronger": "Your bond has grown stronger.",
    "inn.seems_distracted": "You enjoy the moment, but {0} seems distracted tonight.",
    "inn.higher_cha": "(Higher Charisma improves your chances)",
    "inn.build_trust": "(Build more trust before deepening this connection)",
    # HandleGiveGift
    "inn.gift_options": "Gift Options:",
    "inn.gift_simple": "Simple Gift (50 gold) - +3 loyalty",
    "inn.gift_fine": "Fine Gift (200 gold) - +8 loyalty",
    "inn.gift_rare": "Rare Gift (500 gold) - +15 loyalty",
    "inn.cancel": "Cancel",
    "inn.choose": "Choose: ",
    "inn.give_gift_desc": "You give {0} {1}.",
    "inn.gift_smile": "{0} smiles warmly. (+{1} loyalty)",
    "inn.gift_trinket": "a thoughtful trinket",
    "inn.gift_jewelry": "a fine piece of jewelry",
    "inn.gift_artifact": "a rare artifact",
    # ShowCompanionHistory
    "inn.history_with": "History with {0}",
    "inn.journey_begun": "Your journey together has just begun...",
    "inn.days_together": "Days together: {0}",
    "inn.total_loyalty": "Total loyalty gained: {0}%",
    # Companion Equipment
    "inn.current_equipment": "Current Equipment:",
    "inn.equip_from_inventory": "Equip item from your inventory",
    "inn.unequip_item": "Unequip item from them",
    "inn.take_all_equipment": "Take all their equipment",
    "inn.done_return": "Done / Return",
    "inn.available_equipment": "Available equipment:",
    "inn.select_item": "Select item (0 to cancel): ",
    "inn.must_identify": "You must identify this item before giving it to a companion.",
    "inn.cannot_use": "{0} cannot use this item: {1}",
    "inn.which_hand": "Which hand?",
    "inn.main_hand": "Main hand",
    "inn.off_hand": "Off hand",
    "inn.equipped_item": "{0} equipped {1}!",
    "inn.failed_equip": "Failed to equip: {0}",
    "inn.equipped_items": "Equipped items:",
    "inn.select_unequip": "Select slot to unequip (0 to cancel): ",
    "inn.cursed_cannot_remove": "The {0} is cursed and cannot be removed!",
    "inn.took_from": "Took {0} from {1}.",
    "inn.added_inventory": "Item added to your inventory.",
    "inn.failed_unequip": "Failed to unequip item.",
    "inn.take_all_confirm": "Take ALL equipment from {0}?",
    "inn.leave_nothing": "This will leave them with nothing. Confirm (Y/N): ",
    "inn.took_items": "Took {0} item{1} from {2}.",
    "inn.no_equipment_to_take": "{0} had no equipment to take.",
    "inn.cursed_not_removed": "Could not remove cursed items: {0}",
    "inn.using_2h": "(using 2H weapon)",
    "inn.empty_slot": "(empty)",
    # Companion Abilities
    "inn.no_abilities": "No combat abilities available yet.",
    "inn.abilities_enabled": "{0}/{1} abilities enabled",
    "inn.toggle_ability": "Toggle ability",
    "inn.enable_all": "Enable all",
    "inn.all_enabled": "All abilities enabled!",
    "inn.enabled": "Enabled: {0}",
    "inn.disabled": "Disabled: {0}",
    # Stat Training
    "inn.trainer_intro1": "A scarred veteran sits in the corner, methodically sharpening a blade.",
    "inn.trainer_intro2": "He looks up as you approach.",
    "inn.trainer_quote1": "\"You want to get stronger? I can help — for a price.\"",
    "inn.trainer_quote2": "\"Each session pushes your body and mind beyond its natural limits.\"",
    "inn.trainer_quote3": "\"But the deeper we go, the harder it gets — and the more it costs.\"",
    "inn.train_header": "# Stat Current Trained Next Cost",
    "inn.your_gold": "Your Gold: {0}",
    "inn.train_prompt": "Choose stat to train (1-8, 0 to leave): ",
    "inn.stat_maxed_quote": "\"Your {0} has been pushed as far as training can take it.\"",
    "inn.find_other_ways": "\"You'll need to find other ways to grow stronger.\"",
    "inn.need_gold_train": "You need {0} gold but only have {1}.",
    "inn.come_back_afford": "\"Come back when you can afford my services.\"",
    "inn.need_materials": "\"This level of training requires rare materials to push past your limits.\"",
    "inn.missing_material": "Missing: {0}x {1}",
    "inn.materials_dungeon": "These materials can be found deep in the dungeon.",
    "inn.material_dissolves": "The {0} dissolves into your body, fueling the transformation...",
    "inn.pay_trainer": "You pay the Master Trainer {0} gold.",
    "inn.train_str": "Hours of lifting, pulling, and breaking things later...",
    "inn.train_dex": "Dodging thrown knives, catching falling coins, threading needles...",
    "inn.train_con": "Endurance runs, ice baths, and a truly terrible herbal tonic...",
    "inn.train_int": "Puzzles, strategy games, and ancient texts until your head throbs...",
    "inn.train_wis": "Meditation, perception drills, and learning to listen to silence...",
    "inn.train_cha": "Public speaking, negotiation exercises, and a very expensive haircut...",
    "inn.train_agi": "Obstacle courses, balance beams, and jumping over increasingly sharp things...",
    "inn.train_sta": "Running until you collapse, then running some more...",
    "inn.stat_increased": "Your {0} increased to {1}! (+1)",
    "inn.sessions_remaining": "\"Good work. You've got {0} more sessions available for {1}.\"",
    # Gambling Den
    "inn.gambling_intro1": "You descend a narrow staircase into a smoky room beneath the Inn.",
    "inn.gambling_intro2": "The clatter of dice and murmur of wagers fill the air.",
    "inn.games_available": "Games Available:",
    "inn.game_highlow": "High-Low Dice       (Guess higher or lower, 1.8x payout)",
    "inn.game_skulls": "Skull & Bones       (Blackjack with bone tiles, 2x payout)",
    "inn.game_arm_wrestling": "Arm Wrestling       (STR contest vs NPC, {0}/{1} today)",
    "inn.choose_game": "Choose a game (0 to leave): ",
    "inn.no_gold_wager": "You don't have any gold to wager!",
    "inn.gold_on_hand": "Gold on hand: {0}",
    "inn.how_much_wager": "How much will you wager? ",
    "inn.invalid_bet": "Invalid bet.",
    "inn.not_enough_gold_wager": "You don't have that much gold!",
    "inn.dealer_rolls": "The dealer rolls: [{0}]",
    "inn.next_roll_higher_lower": "Will the next roll be ",
    "inn.invalid_forfeited": "Invalid choice. Bet forfeited.",
    "inn.next_roll": "The next roll: [{0}]",
    "inn.tie_returned": "It's a tie! Your bet is returned.",
    "inn.you_win": "You win! +{0} gold!",
    "inn.double_nothing": "Double or nothing? Current pot: {0}g ",
    "inn.max_double_down": "Maximum double-downs reached. Collecting winnings!",
    "inn.you_lose": "You lose! -{0} gold.",
    "inn.gold_remaining": "Gold remaining: {0}",
    # Skull & Bones
    "inn.bones_rules1": "Rules: Draw bone tiles to reach 21 without going over.",
    "inn.bones_rules2": "Face tiles (Skull, Crown, Sword) = 10. Dealer stands on 17.",
    "inn.your_tiles": "Your tiles: {0} = {1}",
    "inn.natural_21": "SKULL & BONES! Natural 21!",
    "inn.you_drew": "You drew: {0} ({1}) — Total: {2}",
    "inn.bust": "BUST! You went over 21.",
    "inn.bust_lose": "You lose {0} gold. Remaining: {1}",
    "inn.dealer_turn": "Dealer's turn...",
    "inn.dealer_total": "Dealer's total: {0}",
    "inn.dealer_busts": "Dealer busts! You win {0} gold!",
    "inn.bones_beats": "Skull & Bones beats dealer! You win {0} gold!",
    "inn.beat_dealer": "You beat the dealer! You win {0} gold!",
    "inn.push": "Push! Bet returned.",
    "inn.dealer_wins": "Dealer wins. You lose {0} gold.",
    # Arm Wrestling
    "inn.enough_today": "\"You've had enough for today, friend. Come back tomorrow.\"",
    "inn.no_arm_wrestling": "No one seems interested in arm wrestling right now.",
    "inn.challenger_slams": "{0} (Level {1}, STR {2}) slams their",
    "inn.challenger_grins": "elbow on the table and grins at you.",
    "inn.gold_says": "\"{0} gold says I can put you down.\"",
    "inn.need_gold_challenge": "You need {0} gold to accept the challenge.",
    "inn.accept_challenge": "Accept the challenge? ({0}g) ",
    "inn.back_away": "You back away from the table.",
    "inn.clasp_hands": "You clasp hands...",
    "inn.three_two_one": "Three... two... one... GO!",
    "inn.slam_arm": "You slam {0}'s arm to the table!",
    "inn.win_gold": "You win {0} gold!",
    "inn.opponent_forces": "{0} forces your arm down with a grunt!",
    "inn.lose_gold": "You lose {0} gold.",
    "inn.draw_match": "Neither of you can budge! It's a draw.",
    "inn.matches_today": "Arm wrestling matches today: {0}/{1}",
    # Rent Room
    "inn.need_gold_room": "You need {0} gold for a room. You have {1} on hand and {2} in the bank.",
    "inn.room_cost": "Room cost: {0} gold",
    "inn.room_healed": "You will be healed fully and logged out safely.",
    "inn.room_bonus": "Sleeping at the Inn grants +50% ATK/DEF if you're attacked.",
    "inn.guards_hired": "Guards hired: {0}/{1}",
    "inn.done_hiring": "Done hiring",
    "inn.cant_afford_guard": "You can't afford that guard.",
    "inn.hired_guard": "Hired {0}! (HP: {1})",
    "inn.total_cost": "Total cost: {0} gold (Room: {1} + Guards: {2})",
    "inn.rent_confirm": "Rent this room and log out? (y/N): ",
    "inn.decide_not_rent": "You decide not to rent a room.",
    "inn.cant_afford": "You can't afford this!",
    "inn.bank_withdrawn": "({0}g withdrawn from your bank account)",
    "inn.shadow_fades": "The Blessing of Shadows fades as you rest...",
    "inn.room_private": "The innkeeper shows you to a private room upstairs.",
    "inn.room_lock": "You lock the heavy door and collapse into a real bed.",
    "inn.guards_position": "Your {0} guard{1} position outside your door.",
    "inn.deep_sleep": "You drift into a deep, protected sleep... (logging out)",
    # Attack Inn Sleeper
    "inn.no_sleepers": "No vulnerable sleepers at the Inn.",
    "inn.sleeping_guests": "Inn — Sleeping Guests",
    "inn.sleeping_npc": "SLEEPING NPC",
    "inn.sleeping_player": "SLEEPING PLAYER",
    "inn.who_attack": "Who do you attack? (number or name, blank to cancel): ",
    "inn.no_such_sleeper": "No such sleeper.",
    "inn.no_longer_here": "They are no longer here.",
    "inn.pick_lock": "You pick the lock to {0}'s room at the Inn...",
    "inn.steal_gold": "You rifle through their belongings and steal {0} gold!",
    "inn.leave_body": "You leave {0}'s body in their room.",
    "inn.fought_off": "{0} fought you off — the Inn's thick walls muffled the struggle!",
    "inn.sneak_toward": "You sneak toward {0}'s room at the Inn...",
    "inn.guard_blocks": "A {0} blocks your path!",
    "inn.cut_down_guard": "You cut down the {0}!",
    "inn.guard_drives_back": "The {0} drives you back! Attack failed!",
    "inn.reach_target": "You reach {0}...",
    "inn.steal_item": "You also take their {0}!",
    "inn.fought_off_sleep": "{0} fought you off even in their sleep!",
    "inn.standing_plummeted": "Your standing with {0} has plummeted! ({1})",
    "inn.not_available": "Not available.",
    "inn.could_not_load": "Could not load their data.",
}

new_es = {
    "inn.sleep_not_late": "No es lo suficientemente tarde para dormir. Intenta esperar hasta la noche.",
    "inn.sleep_room_shown": "El posadero te muestra una pequeña habitación arriba...",
    "inn.sleep_settle_in": "Te acomodas en el colchón de paja y cierras los ojos.",
    "inn.sleep_dark_memories": "Oscuros recuerdos invaden tus sueños, dejándote menos descansado...",
    "inn.sleep_refreshed": "¡Te despiertas sintiéndote completamente renovado!",
    "inn.sleep_recover_mana": "Recuperaste {0} PV, {1} maná. ({2}% recuperación)",
    "inn.sleep_recover_stamina": "Recuperaste {0} PV, {1} aguante. ({2}% recuperación)",
    "inn.sleep_dreams_unfold": "Mientras duermes, los sueños se desarrollan...",
    "inn.sleep_drift_off": "Te quedas dormido...",
    "inn.sleep_new_day": "Un nuevo día amanece. (Día {0})",
    "inn.food_hearty_meal": "Pides una abundante comida de carne asada y pan.",
    "inn.food_stamina_boost": "¡La comida llena tu estómago y aumenta tu aguante!",
    "inn.food_hp_recover": "También recuperas {0} PV de la comida nutritiva.",
    "inn.no_companions_available": "No hay extraños buscando compañeros de aventura ahora mismo.",
    "inn.companions_watching": "En los rincones oscuros de la posada, varias figuras parecen observarte...",
    "inn.return_to_bar": "Volver al bar",
    "inn.approach_who": "¿A quién te acercas? ",
    "inn.you_approach": "Te acercas a {0}, {1}...",
    "inn.greetings_traveler": "\"Saludos, viajero. Pareces alguien que necesita ayuda...\"",
    "inn.background_label": "Trasfondo: {0}",
    "inn.combat_role_label": "Rol de Combate: {0}",
    "inn.abilities_label": "Habilidades: {0}",
    "inn.recruit_companion": "Reclutar a este compañero",
    "inn.talk_more": "Hablar más para conocerlos",
    "inn.leave_them_be": "Dejarlos tranquilos",
    "inn.companion_joined": "¡{0} se ha unido a ti como compañero!",
    "inn.companion_fight_by_side": "Te acompañarán en las mazmorras y lucharán a tu lado.",
    "inn.companion_die_warning": "ADVERTENCIA: Los compañeros pueden morir permanentemente. Protégelos bien.",
    "inn.companion_shares_story": "{0} comparte su historia...",
    "inn.personal_quest_label": "Misión Personal: {0}",
    "inn.nod_return": "Asientes a {0} y vuelves al bar.",
    "inn.no_companions_yet": "Aún no tienes compañeros.",
    "inn.active_companions": "COMPAÑEROS ACTIVOS ({0}/{1}):",
    "inn.no_active_companions": "(Sin compañeros activos - selecciona de las reservas)",
    "inn.reserve_companions": "COMPAÑEROS DE RESERVA:",
    "inn.fallen_companions": "COMPAÑEROS CAÍDOS:",
    "inn.died_label": "Murió: {0}",
    "inn.options": "Opciones:",
    "inn.talk_to": "Hablar con {0}",
    "inn.switch_companions": "Cambiar compañeros activos",
    "inn.companion_limit": "Puedes tener hasta {0} compañeros activos en la mazmorra.",
    "inn.companion_warning": "Los compañeros activos luchan a tu lado pero también pueden ser heridos o morir.",
    "inn.select_to_activate": "Selecciona compañeros para activar (números separados por espacios):",
    "inn.example_activate": "Ejemplo: '1 3' para activar compañeros 1 y 3",
    "inn.enter_nothing": "Deja en blanco para mantener la selección actual",
    "inn.activate_prompt": "Activar: ",
    "inn.no_changes": "Sin cambios.",
    "inn.no_valid_selected": "Ningún compañero válido seleccionado. Sin cambios.",
    "inn.party_updated": "¡Grupo actualizado!",
    "inn.now_active": "{0} ahora está activo.",
    "inn.update_failed": "Error al actualizar el grupo.",
    "inn.background": "Trasfondo:",
    "inn.stats": "Estadísticas:",
    "inn.level_role": "Nivel: {0} | Rol: {1}",
    "inn.hp_atk_def": "PV: {0}  |  ATQ: {1}  |  DEF: {2}",
    "inn.items_equipped": "({0} objeto{1} equipado{1} — estadísticas incluyen bonificaciones de equipo)",
    "inn.begin_quest": "Comenzar Misión Personal: {0}",
    "inn.discuss_progress": "Discutir Progreso de Misión",
    "inn.deepen_bond_today": "Profundizar vínculo (ya visitado hoy)",
    "inn.spend_time_max": "Pasar tiempo juntos (Vínculo máximo)",
    "inn.deepen_bond": "Profundizar vínculo...",
    "inn.give_a_gift": "Dar un regalo",
    "inn.view_history": "Ver historial juntos",
    "inn.manage_equipment": "Gestionar Equipo",
    "inn.manage_skills": "Gestionar Habilidades de Combate",
    "inn.return": "Volver",
    "inn.speaks_quietly": "{0} habla en voz baja:",
    "inn.accept_quest": "Aceptar esta misión",
    "inn.not_yet": "Todavía no",
    "inn.will_you_help": "¿Ayudarás? ",
    "inn.quest_begun": "Misión Iniciada: {0}",
    "inn.nods_gratefully": "{0} asiente agradecido.",
    "inn.quest_in_progress": "Estado de la Misión: En Progreso",
    "inn.seek_clues": "Busca pistas en las profundidades de la mazmorra...",
    "inn.already_spent_time": "Ya pasaste tiempo de calidad con {0} hoy.",
    "inn.perhaps_tomorrow": "Quizás mañana puedas compartir otro momento juntos.",
    "inn.quiet_corner": "Tú y {0} encuentran un rincón tranquilo para hablar.",
    "inn.tavern_fades": "El ruido de la taberna se desvanece en un murmullo de fondo.",
    "inn.romance_1": "Compartes un momento de comprensión con {0}.",
    "inn.romance_2": "Sus miradas se cruzan y algo no dicho pasa entre ustedes.",
    "inn.romance_3": "La mano de {0} roza la tuya.",
    "inn.romance_4": "El mundo parece encogerse hasta ser solo ustedes dos.",
    "inn.romance_5": "{0} se acerca, con voz suave.",
    "inn.romance_default": "El vínculo entre tú y {0} se profundiza.",
    "inn.bond_max": "Tu vínculo con {0} es tan profundo como puede ser.",
    "inn.bond_stronger": "Tu vínculo se ha fortalecido.",
    "inn.seems_distracted": "Disfrutas el momento, pero {0} parece distraído esta noche.",
    "inn.higher_cha": "(Mayor Carisma mejora tus posibilidades)",
    "inn.build_trust": "(Construye más confianza antes de profundizar esta conexión)",
    "inn.gift_options": "Opciones de Regalo:",
    "inn.gift_simple": "Regalo Simple (50 oro) - +3 lealtad",
    "inn.gift_fine": "Regalo Fino (200 oro) - +8 lealtad",
    "inn.gift_rare": "Regalo Raro (500 oro) - +15 lealtad",
    "inn.cancel": "Cancelar",
    "inn.choose": "Elige: ",
    "inn.give_gift_desc": "Le das a {0} {1}.",
    "inn.gift_smile": "{0} sonríe cálidamente. (+{1} lealtad)",
    "inn.gift_trinket": "un detalle pensado",
    "inn.gift_jewelry": "una joya fina",
    "inn.gift_artifact": "un artefacto raro",
    "inn.history_with": "Historial con {0}",
    "inn.journey_begun": "Su viaje juntos acaba de comenzar...",
    "inn.days_together": "Días juntos: {0}",
    "inn.total_loyalty": "Lealtad total ganada: {0}%",
    "inn.current_equipment": "Equipo Actual:",
    "inn.equip_from_inventory": "Equipar objeto de tu inventario",
    "inn.unequip_item": "Desequipar objeto",
    "inn.take_all_equipment": "Tomar todo su equipo",
    "inn.done_return": "Listo / Volver",
    "inn.available_equipment": "Equipo disponible:",
    "inn.select_item": "Selecciona objeto (0 para cancelar): ",
    "inn.must_identify": "Debes identificar este objeto antes de dárselo a un compañero.",
    "inn.cannot_use": "{0} no puede usar este objeto: {1}",
    "inn.which_hand": "¿Qué mano?",
    "inn.main_hand": "Mano principal",
    "inn.off_hand": "Mano secundaria",
    "inn.equipped_item": "¡{0} equipó {1}!",
    "inn.failed_equip": "Error al equipar: {0}",
    "inn.equipped_items": "Objetos equipados:",
    "inn.select_unequip": "Selecciona ranura para desequipar (0 para cancelar): ",
    "inn.cursed_cannot_remove": "¡{0} está maldito y no se puede quitar!",
    "inn.took_from": "Tomaste {0} de {1}.",
    "inn.added_inventory": "Objeto añadido a tu inventario.",
    "inn.failed_unequip": "Error al desequipar objeto.",
    "inn.take_all_confirm": "¿Tomar TODO el equipo de {0}?",
    "inn.leave_nothing": "Los dejarás sin nada. ¿Confirmar (S/N)? ",
    "inn.took_items": "Tomaste {0} objeto{1} de {2}.",
    "inn.no_equipment_to_take": "{0} no tenía equipo para tomar.",
    "inn.cursed_not_removed": "No se pudieron quitar objetos malditos: {0}",
    "inn.using_2h": "(usando arma a 2 manos)",
    "inn.empty_slot": "(vacío)",
    "inn.no_abilities": "No hay habilidades de combate disponibles aún.",
    "inn.abilities_enabled": "{0}/{1} habilidades activadas",
    "inn.toggle_ability": "Alternar habilidad",
    "inn.enable_all": "Activar todas",
    "inn.all_enabled": "¡Todas las habilidades activadas!",
    "inn.enabled": "Activada: {0}",
    "inn.disabled": "Desactivada: {0}",
    "inn.trainer_intro1": "Un veterano con cicatrices se sienta en la esquina, afilando una hoja metódicamente.",
    "inn.trainer_intro2": "Levanta la vista cuando te acercas.",
    "inn.trainer_quote1": "\"¿Quieres ser más fuerte? Puedo ayudar — por un precio.\"",
    "inn.trainer_quote2": "\"Cada sesión empuja tu cuerpo y mente más allá de sus límites naturales.\"",
    "inn.trainer_quote3": "\"Pero cuanto más profundo vamos, más difícil se pone — y más cuesta.\"",
    "inn.train_header": "# Estad. Actual Entrenado Costo",
    "inn.your_gold": "Tu Oro: {0}",
    "inn.train_prompt": "Elige estadística para entrenar (1-8, 0 para salir): ",
    "inn.stat_maxed_quote": "\"Tu {0} ha sido llevada al límite del entrenamiento.\"",
    "inn.find_other_ways": "\"Tendrás que encontrar otras formas de ser más fuerte.\"",
    "inn.need_gold_train": "Necesitas {0} de oro pero solo tienes {1}.",
    "inn.come_back_afford": "\"Vuelve cuando puedas pagar mis servicios.\"",
    "inn.need_materials": "\"Este nivel de entrenamiento requiere materiales raros.\"",
    "inn.missing_material": "Falta: {0}x {1}",
    "inn.materials_dungeon": "Estos materiales se encuentran en las profundidades de la mazmorra.",
    "inn.material_dissolves": "El {0} se disuelve en tu cuerpo, alimentando la transformación...",
    "inn.pay_trainer": "Pagas al Maestro Entrenador {0} de oro.",
    "inn.train_str": "Horas de levantar, tirar y romper cosas después...",
    "inn.train_dex": "Esquivando cuchillos, atrapando monedas, enhebrar agujas...",
    "inn.train_con": "Carreras de resistencia, baños de hielo y un horrible tónico herbal...",
    "inn.train_int": "Puzzles, juegos de estrategia y textos antiguos hasta que duele la cabeza...",
    "inn.train_wis": "Meditación, ejercicios de percepción y aprender a escuchar el silencio...",
    "inn.train_cha": "Oratoria, ejercicios de negociación y un corte de pelo muy caro...",
    "inn.train_agi": "Circuitos de obstáculos, barras de equilibrio y saltar cosas afiladas...",
    "inn.train_sta": "Correr hasta colapsar, y luego correr más...",
    "inn.stat_increased": "¡Tu {0} aumentó a {1}! (+1)",
    "inn.sessions_remaining": "\"Buen trabajo. Te quedan {0} sesiones más para {1}.\"",
    "inn.gambling_intro1": "Desciendes una escalera estrecha a una sala llena de humo bajo la Posada.",
    "inn.gambling_intro2": "El repiqueteo de dados y el murmullo de apuestas llenan el aire.",
    "inn.games_available": "Juegos Disponibles:",
    "inn.game_highlow": "Dados Alto-Bajo    (Adivina mayor o menor, pago 1.8x)",
    "inn.game_skulls": "Calavera y Huesos  (Blackjack con fichas de hueso, pago 2x)",
    "inn.game_arm_wrestling": "Pulseadas          (Competencia de FUE vs PNJ, {0}/{1} hoy)",
    "inn.choose_game": "Elige un juego (0 para salir): ",
    "inn.no_gold_wager": "¡No tienes oro para apostar!",
    "inn.gold_on_hand": "Oro en mano: {0}",
    "inn.how_much_wager": "¿Cuánto apostarás? ",
    "inn.invalid_bet": "Apuesta inválida.",
    "inn.not_enough_gold_wager": "¡No tienes tanto oro!",
    "inn.dealer_rolls": "El crupier tira: [{0}]",
    "inn.next_roll_higher_lower": "¿La siguiente tirada será ",
    "inn.invalid_forfeited": "Opción inválida. Apuesta perdida.",
    "inn.next_roll": "La siguiente tirada: [{0}]",
    "inn.tie_returned": "¡Empate! Tu apuesta es devuelta.",
    "inn.you_win": "¡Ganaste! +{0} oro!",
    "inn.double_nothing": "¿Doble o nada? Bote actual: {0}oro ",
    "inn.max_double_down": "¡Máximo de doblajes alcanzado. Cobrando ganancias!",
    "inn.you_lose": "¡Perdiste! -{0} oro.",
    "inn.gold_remaining": "Oro restante: {0}",
    "inn.bones_rules1": "Reglas: Saca fichas de hueso para llegar a 21 sin pasarte.",
    "inn.bones_rules2": "Fichas con cara (Calavera, Corona, Espada) = 10. El crupier se planta en 17.",
    "inn.your_tiles": "Tus fichas: {0} = {1}",
    "inn.natural_21": "¡CALAVERA Y HUESOS! ¡21 natural!",
    "inn.you_drew": "Sacaste: {0} ({1}) — Total: {2}",
    "inn.bust": "¡PASASTE! Más de 21.",
    "inn.bust_lose": "Pierdes {0} oro. Restante: {1}",
    "inn.dealer_turn": "Turno del crupier...",
    "inn.dealer_total": "Total del crupier: {0}",
    "inn.dealer_busts": "¡El crupier se pasa! ¡Ganas {0} oro!",
    "inn.bones_beats": "¡Calavera y Huesos vence al crupier! ¡Ganas {0} oro!",
    "inn.beat_dealer": "¡Vences al crupier! ¡Ganas {0} oro!",
    "inn.push": "¡Empate! Apuesta devuelta.",
    "inn.dealer_wins": "El crupier gana. Pierdes {0} oro.",
    "inn.enough_today": "\"Ya tuviste suficiente por hoy, amigo. Vuelve mañana.\"",
    "inn.no_arm_wrestling": "Nadie parece interesado en pulseadas ahora mismo.",
    "inn.challenger_slams": "{0} (Nivel {1}, FUE {2}) golpea su",
    "inn.challenger_grins": "codo en la mesa y te sonríe.",
    "inn.gold_says": "\"{0} de oro dice que puedo derribarte.\"",
    "inn.need_gold_challenge": "Necesitas {0} de oro para aceptar el desafío.",
    "inn.accept_challenge": "¿Aceptar el desafío? ({0}oro) ",
    "inn.back_away": "Te alejas de la mesa.",
    "inn.clasp_hands": "Se toman de las manos...",
    "inn.three_two_one": "¡Tres... dos... uno... YA!",
    "inn.slam_arm": "¡Aplastas el brazo de {0} contra la mesa!",
    "inn.win_gold": "¡Ganas {0} oro!",
    "inn.opponent_forces": "¡{0} fuerza tu brazo hacia abajo con un gruñido!",
    "inn.lose_gold": "Pierdes {0} oro.",
    "inn.draw_match": "¡Ninguno puede moverse! Es un empate.",
    "inn.matches_today": "Pulseadas hoy: {0}/{1}",
    "inn.need_gold_room": "Necesitas {0} de oro para una habitación. Tienes {1} en mano y {2} en el banco.",
    "inn.room_cost": "Costo de habitación: {0} de oro",
    "inn.room_healed": "Serás curado completamente y desconectado de forma segura.",
    "inn.room_bonus": "Dormir en la Posada otorga +50% ATQ/DEF si te atacan.",
    "inn.guards_hired": "Guardias contratados: {0}/{1}",
    "inn.done_hiring": "Terminar de contratar",
    "inn.cant_afford_guard": "No puedes pagar ese guardia.",
    "inn.hired_guard": "¡{0} contratado! (PV: {1})",
    "inn.total_cost": "Costo total: {0} oro (Habitación: {1} + Guardias: {2})",
    "inn.rent_confirm": "¿Alquilar esta habitación y desconectarse? (s/N): ",
    "inn.decide_not_rent": "Decides no alquilar una habitación.",
    "inn.cant_afford": "¡No puedes pagarlo!",
    "inn.bank_withdrawn": "({0}oro retirado de tu cuenta bancaria)",
    "inn.shadow_fades": "La Bendición de las Sombras se desvanece mientras descansas...",
    "inn.room_private": "El posadero te muestra una habitación privada arriba.",
    "inn.room_lock": "Cierras la pesada puerta y caes en una cama de verdad.",
    "inn.guards_position": "Tus {0} guardia{1} se posicionan fuera de tu puerta.",
    "inn.deep_sleep": "Te sumes en un sueño profundo y protegido... (desconectando)",
    "inn.no_sleepers": "No hay durmientes vulnerables en la Posada.",
    "inn.sleeping_guests": "Posada — Huéspedes Durmiendo",
    "inn.sleeping_npc": "PNJ DURMIENDO",
    "inn.sleeping_player": "JUGADOR DURMIENDO",
    "inn.who_attack": "¿A quién atacas? (número o nombre, en blanco para cancelar): ",
    "inn.no_such_sleeper": "No existe tal durmiente.",
    "inn.no_longer_here": "Ya no están aquí.",
    "inn.pick_lock": "Fuerzas la cerradura de la habitación de {0} en la Posada...",
    "inn.steal_gold": "¡Revisas sus pertenencias y robas {0} oro!",
    "inn.leave_body": "Dejas el cuerpo de {0} en su habitación.",
    "inn.fought_off": "¡{0} te rechazó — las gruesas paredes de la Posada amortiguaron la lucha!",
    "inn.sneak_toward": "Te acercas sigilosamente a la habitación de {0} en la Posada...",
    "inn.guard_blocks": "¡Un {0} bloquea tu camino!",
    "inn.cut_down_guard": "¡Derribas al {0}!",
    "inn.guard_drives_back": "¡El {0} te hace retroceder! ¡Ataque fallido!",
    "inn.reach_target": "Llegas a {0}...",
    "inn.steal_item": "¡También tomas su {0}!",
    "inn.fought_off_sleep": "¡{0} te rechazó incluso dormido!",
    "inn.standing_plummeted": "¡Tu reputación con {0} se ha desplomado! ({1})",
    "inn.not_available": "No disponible.",
    "inn.could_not_load": "No se pudieron cargar sus datos.",
}

for k, v in new_en.items():
    en[k] = v
for k, v in new_es.items():
    es[k] = v

with open('Localization/en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, ensure_ascii=False, indent=2)
with open('Localization/es.json', 'w', encoding='utf-8') as f:
    json.dump(es, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_en)} en keys, {len(new_es)} es keys. en: {len(en)}, es: {len(es)}")
