import json

with open('Localization/en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)
with open('Localization/es.json', 'r', encoding='utf-8') as f:
    es = json.load(f)

new_en = {
    # Potion cache encounter
    "dungeon.potion_cache_header": "POTION CACHE",
    "dungeon.potion_cache_header_sr": "-- POTION CACHE --",
    "dungeon.potion_cache_msg_1": "You discover an abandoned healer's satchel!",
    "dungeon.potion_cache_msg_2": "A fallen adventurer's pack contains healing supplies!",
    "dungeon.potion_cache_msg_3": "You find a monk's abandoned cache of potions!",
    "dungeon.potion_cache_msg_4": "A hidden alcove reveals a stash of healing elixirs!",
    "dungeon.potion_cache_msg_5": "The corpse of a cleric clutches a bag of potions!",
    "dungeon.potion_cache_max": "You already have the maximum number of potions!",
    "dungeon.potion_cache_leave": "You leave the potions for another adventurer.",
    "dungeon.potion_cache_collect": "You collect {0} healing potion(s)!",
    "dungeon.potion_cache_count": "Potions: {0}/{1}",
    "dungeon.potion_cache_left_behind": "(You had to leave {0} potion(s) behind - at maximum capacity)",

    # Merchant encounter
    "dungeon.merchant_appears": "A traveling merchant appears from the shadows!",
    "dungeon.merchant_greeting_text": "\"Greetings, brave adventurer! Care to trade?\"",
    "dungeon.merchant_trade_or_attack": "(T)rade with merchant or (A)ttack for goods? ",
    "dungeon.merchant_rob": "You decide to rob the poor merchant!",
    "dungeon.merchant_loot_split": "You loot {0} gold and 3 healing potions from the merchant! (split {1} ways)",
    "dungeon.merchant_loot": "You loot {0} gold and 3 healing potions from the merchant!",
    "dungeon.merchant_darkness": "+10 Darkness for attacking an innocent merchant!",
    "dungeon.merchant_goodbye": "The merchant waves goodbye and vanishes into the shadows.",
    "dungeon.merchant_healing_potion": "Healing Potion ({0}g)",
    "dungeon.merchant_mega_potion": "Mega Potion ({0}g) - Full heal!",
    "dungeon.merchant_antidote": "Antidote ({0}g) - Cures poison ({1}/{2})",
    "dungeon.merchant_buy_max": "Buy Max Potions ({0}g)",
    "dungeon.merchant_buy_max_full": "Buy Max Potions (full!)",
    "dungeon.merchant_leave_shop": "Leave shop",
    "dungeon.merchant_cant_carry_potions": "\"You can't carry any more potions, friend!\"",
    "dungeon.merchant_purchased_potion": "Purchased 1 healing potion! ({0}/{1})",
    "dungeon.merchant_mega_full_heal": "You drink the mega potion - FULL HEALTH RESTORED!",
    "dungeon.merchant_cant_carry_antidotes": "\"You can't carry any more antidotes, friend!\"",
    "dungeon.merchant_antidote_cure": "You drink the antidote — the poison drains from your body!",
    "dungeon.merchant_purchased_antidote": "Purchased 1 antidote! ({0}/{1})",
    "dungeon.merchant_full_potions": "\"You're already full on potions!\"",
    "dungeon.merchant_purchased_potions": "Purchased {0} potions for {1}g!",
    "dungeon.merchant_potions_count": "Potions: {0}/{1}",
    "dungeon.merchant_afford_partial": "Could only afford {0} potions.",
    "dungeon.merchant_safe_travels": "\"Safe travels, adventurer!\"",
    "dungeon.merchant_invalid": "Invalid choice.",
    "dungeon.merchant_item_sold": "\"That item has already been sold, friend.\"",
    "dungeon.merchant_need_gold": "\"You need {0} gold for the {1}.\"",
    "dungeon.merchant_come_back": "\"Come back when you have more coin!\"",
    "dungeon.merchant_purchase_confirm": "Purchase {0} for {1} gold? (Y/N)",
    "dungeon.merchant_added_inventory": "Added to your inventory.",
    "dungeon.merchant_fine_choice": "\"A fine choice! Use it well.\"",
    "dungeon.merchant_another_time": "\"Perhaps another time.\"",
    "dungeon.merchant_current_weapon": "Your current weapon power: {0}",
    "dungeon.merchant_current_armor": "Your current armor power: {0}",

    # Witch doctor encounter
    "dungeon.witch_doctor_header": "=== WITCH DOCTOR ENCOUNTER ===",
    "dungeon.witch_doctor_meet": "You meet the evil Witch-Doctor Mbluta!",
    "dungeon.witch_doctor_demand": "He demands {0} gold or he will curse you!",
    "dungeon.witch_doctor_prompt": "(P)ay the witch doctor or (R)un away? ",
    "dungeon.witch_doctor_pay": "You reluctantly pay the witch doctor.",
    "dungeon.witch_doctor_vanish": "He vanishes into the darkness...",
    "dungeon.witch_doctor_flee": "You manage to flee the evil witch doctor!",
    "dungeon.witch_doctor_cursed": "You fail to escape and are cursed!",
    "dungeon.witch_doctor_lose_exp": "You lose {0} experience points!",
    "dungeon.witch_doctor_lose_fights": "You lose {0} dungeon fights!",
    "dungeon.witch_doctor_lose_pfights": "You lose {0} player fights!",
    "dungeon.witch_doctor_no_gold": "A witch doctor appears but sees you have no gold and leaves.",

    # Descend/ascend
    "dungeon.must_defeat_old_god": "You must defeat the Old God on this floor before descending deeper.",
    "dungeon.cant_venture_deeper": "You cannot venture deeper than level {0} at your current strength.",
    "dungeon.level_up_access": "Level up to access deeper floors.",
    "dungeon.descend_to": "You descend to dungeon level {0}.",
    "dungeon.deepest_level": "You have reached the deepest level of the dungeon.",
    "dungeon.ascend_to": "You ascend to dungeon level {0}.",

    # Team management
    "dungeon.no_one_to_bring": "You have no one to bring with you.",
    "dungeon.get_team": "Get married, recruit companions, or join a team!",
    "dungeon.team_label": "Team: {0}",
    "dungeon.team_turf": "Team controls turf: {0}",
    "dungeon.no_team_loved_ones": "You're not in a team, but your loved ones can join you.",
    "dungeon.current_dungeon_party": "Current Dungeon Party:",
    "dungeon.available_companions": "Available Companions (on standby):",
    "dungeon.available_allies": "Available Allies (not in dungeon party):",
    "dungeon.no_allies_available": "No allies available to join your dungeon party.",
    "dungeon.options": "Options:",
    "dungeon.add_companion_party": "] Add companion to party",
    "dungeon.add_ally": "]dd ally to dungeon party",
    "dungeon.remove_ally": "]emove ally from party",
    "dungeon.xp_distribution_pct": "] XP Distribution ({0}% allocated)",
    "dungeon.back_dungeon_menu": "]ack to dungeon menu",
    "dungeon.party_full_max4": "Your dungeon party is full (max 4 teammates)!",
    "dungeon.invalid_companion": "Invalid companion selection.",
    "dungeon.no_team_members": "No team members available to add.",
    "dungeon.no_teammates_remove": "No teammates to remove.",
    "dungeon.companion_role": "Role: {0}",
    "dungeon.could_not_add": "Could not add {0} to the party.",
    "dungeon.enter_team_number": "Enter number of team member to add (1-{0}): ",
    "dungeon.npc_higher_level": "{0} is {1} levels higher than you.",
    "dungeon.npc_demand_fee": "They demand {0} gold to join you in the dungeon.",
    "dungeon.your_gold": "Your gold: {0}",
    "dungeon.cannot_afford_fee": "You cannot afford this fee!",
    "dungeon.pay_fee_confirm": "Pay {0} gold? (Y/N): ",
    "dungeon.npc_shrugs": "{0} shrugs and stays behind.",
    "dungeon.paid_fee": "Paid {0} gold.",
    "dungeon.npc_joins": "{0} joins your dungeon party!",
    "dungeon.fight_alongside": "They will fight alongside you against monsters.",
    "dungeon.xp_penalty_warning": "Warning: XP penalty active ({0}% rate due to high-level ally)",
    "dungeon.team_bonus": "Team bonus: +15% XP and gold from battles!",
    "dungeon.enter_party_remove": "Enter party number to remove (2-{0}): ",
    "dungeon.grouped_player_leave": "{0} is a grouped player — they must type /leave to exit the group.",
    "dungeon.companion_steps_back": "{0} steps back from the front lines.",
    "dungeon.companion_available": "(They remain available - use Party Management to bring them back)",
    "dungeon.npc_returns_town": "{0} leaves the dungeon party and returns to town.",
    "dungeon.member_leaves_party": "{0} leaves the dungeon party.",
    "dungeon.companion_rejoins": "{0} rejoins your party!",

    # XP distribution
    "dungeon.grouped_independent": "({0} grouped player(s) earn XP independently)",
    "dungeon.current_party_xp": "Current party:",
    "dungeon.xp_unallocated": "Warning: {0}% of XP is unallocated!",
    "dungeon.xp_adjust_prompt": "Enter slot number to adjust, [E]ven split, or [B]ack:",
    "dungeon.xp_even_split": "XP split evenly: {0}% for you, {1}% per teammate.",
    "dungeon.xp_slot_empty": "That slot is empty.",
    "dungeon.xp_set_prompt": "Set XP % for {0} (0-{1}, currently {2}%): ",
    "dungeon.xp_min_self": "You must keep at least 10% XP for yourself.",
    "dungeon.xp_total_exceeded": "Total would be {0}%. Maximum is 100%.",
    "dungeon.xp_set_to": "{0} set to {1}% XP.",
    "dungeon.invalid_percentage": "Invalid percentage.",

    # Party full / recruitment
    "dungeon.party_full_allies": "Your party is full (max 4 allies)!",
    "dungeon.make_room": "{0} would like to join you, but you need to make room first.",
    "dungeon.current_party_members": "Current party members:",
    "dungeon.remove_make_room": "[R] Remove someone to make room",
    "dungeon.cancel_recruitment": "[C] Cancel recruitment",
    "dungeon.who_should_leave": "Who should leave the party?",
    "dungeon.companions_readd": "(Companions can be re-added anytime from Party Management)",
    "dungeon.enter_remove_number": "Enter number (1-{0}): ",
    "dungeon.invalid_cancelled": "Invalid selection. Recruitment cancelled.",
    "dungeon.recruitment_cancelled": "Recruitment cancelled.",

    # Potion menu
    "dungeon.use_potion_self": "Use Healing Potion on yourself (heals ~{0} HP)",
    "dungeon.buy_potions_monk": "Buy Potions from Monk (Healing {0}g, Mana {1}g)",
    "dungeon.heal_full": "Heal yourself to Full (use multiple potions)",
    "dungeon.heal_teammate": "Heal a Teammate",
    "dungeon.heal_all": "Heal ALL Party Members to Full",
    "dungeon.use_antidote": "Use Antidote (cures poison, {0} remaining)",
    "dungeon.use_antidote_not_poisoned": "Use Antidote ({0} remaining) - not poisoned",
    "dungeon.return_dungeon": "Return to Dungeon",
    "dungeon.no_potions_potion_menu": "Use Healing Potion - NO POTIONS!",
    "dungeon.antidote_cure_poison": "You drink the antidote — the poison drains from your body!",
    "dungeon.not_poisoned": "You're not poisoned!",
    "dungeon.no_antidotes": "You don't have any antidotes!",
    "dungeon.select_teammate_heal": "Select teammate to heal:",
    "dungeon.cancel": "Cancel",
    "dungeon.choose": "Choose: ",
    "dungeon.already_full_health_name": "{0} is already at full health!",
    "dungeon.missing_hp": "{0} is missing {1} HP.",
    "dungeon.each_potion_heals": "Each potion heals approximately {0} HP.",
    "dungeon.use_1_potion": "Use 1 potion",
    "dungeon.fully_heal_potions": "Fully heal (uses up to {0} potions)",
    "dungeon.give_potion_one": "You give a healing potion to {0}!",
    "dungeon.give_potions_many": "You give {0} healing potions to {1}!",
    "dungeon.recovers_hp": "{0} recovers {1} HP!",
    "dungeon.fully_healed_name": "{0} is fully healed!",
    "dungeon.everyone_full_health": "Everyone is already at full health!",
    "dungeon.heal_party_requires": "Healing entire party requires approximately {0} potions.",
    "dungeon.you_have_potions": "You have {0} potions.",
    "dungeon.not_enough_potions_warning": "Warning: Not enough potions for full heal. Will use all {0}.",
    "dungeon.yes_heal_party": "Yes, heal the party (uses {0} potions)",
    "dungeon.distributing_potions": "Distributing potions to the party...",
    "dungeon.you_recover_hp": "You recover {0} HP!",
    "dungeon.teammate_recovers": "{0} recovers {1} HP!",
    "dungeon.used_potions_total": "Used {0} potions. Total HP restored: {1}",
    "dungeon.potions_remaining": "Potions remaining: {0}/{1}",
    "dungeon.no_healing_potions": "You don't have any healing potions!",
    "dungeon.already_full_health": "You're already at full health!",
    "dungeon.drink_potion_recover": "You drink a healing potion and recover {0} HP!",
    "dungeon.will_use_potions": "This will use {0} potion(s). Continue? (Y/N)",
    "dungeon.drink_potions_recover": "You drink {0} healing potion(s) and recover {1} HP!",

    # Monk shop
    "dungeon.monk_appears": "A wandering monk materializes from the shadows...",
    "dungeon.monk_greeting": "\"Greetings, traveler. I have supplies for body and mind.\"",
    "dungeon.monk_your_gold": "Your gold: {0}",
    "dungeon.monk_another_time": "\"Perhaps another time, then.\"",
    "dungeon.monk_fades": "The monk bows and fades back into the shadows...",
    "dungeon.monk_max_potions": "\"You already carry all the {0} potions you can hold!\"",
    "dungeon.monk_no_gold": "\"I'm afraid you lack the gold, my friend.\"",
    "dungeon.monk_how_many": "How many {0} potions? (Max: {1}, 0 to cancel)",
    "dungeon.monk_cancel": "\"Perhaps another time, then.\"",
    "dungeon.monk_only_provide": "\"I can only provide you with {0}.\"",
    "dungeon.monk_purchased": "You purchase {0} {1} potion(s) for {2} gold.",
    "dungeon.monk_gold_remaining": "Gold remaining: {0}",

    # Map/guide
    "dungeon.no_floor_map": "No floor to map.",
    "dungeon.map_unavailable": "Map data unavailable.",
    "dungeon.no_floor_data": "No floor data.",
    "dungeon.guide_title": "Dungeon Guide - Level {0}, {1}",
    "dungeon.you_are_in": "You are in: {0}",
    "dungeon.guide_exits": "Exits: {0}",
    "dungeon.boss_defeated": "Boss defeated.",
    "dungeon.no_known_destinations": "No known destinations. Explore to discover rooms.",
    "dungeon.directions_to": "Directions to:",
    "dungeon.map_legend_you": "You",
    "dungeon.map_legend_cleared": "Cleared",
    "dungeon.map_legend_monsters": "Monsters",
    "dungeon.map_legend_stairs": "Stairs",
    "dungeon.map_legend_boss": "Boss",
    "dungeon.map_legend_safe": "Safe",
    "dungeon.map_legend_unknown": "Unknown",

    # Dungeon help
    "dungeon.help_title": "Dungeon Help",
    "dungeon.help_explore": "E - Explore the current level",
    "dungeon.help_descend": "D - Descend to a deeper, more dangerous level",
    "dungeon.help_ascend": "A - Ascend to a safer level or return to town",
    "dungeon.help_team": "T - Manage your team members",
    "dungeon.help_status": "S - View your character status",
    "dungeon.help_potions": "P - Buy potions from the wandering monk",
    "dungeon.help_map": "M - View the dungeon map",
    "dungeon.help_guide": "G - Guide (directions to stairs, unexplored, uncleared, boss)",
    "dungeon.help_quit": "Q - Quit and return to town",

    # Difficulty/level change
    "dungeon.steel_nerves": "You steel your nerves. The dungeon now feels like level {0}!",

    # Beggar encounter
    "dungeon.beggar_appears": "A ragged figure huddles against the dungeon wall, hands outstretched.",
    "dungeon.beggar_plea": "\"Please... spare some gold for a lost soul? I've been trapped down here for days.\"",
    "dungeon.beggar_give": "You hand over {0} gold. The beggar's eyes well with tears.",
    "dungeon.beggar_bless": "\"Bless you... bless you, kind one.\"",
    "dungeon.beggar_bonus": "The beggar presses something into your hand before shuffling away.",
    "dungeon.beggar_bonus_gold": "It's a hidden pouch with {0} gold!",
    "dungeon.beggar_test": "\"I was testing your heart. You passed.\"",
    "dungeon.beggar_rob": "You shove the beggar aside and rifle through their rags.",
    "dungeon.beggar_rob_gold": "You find {0} gold hidden in their cloak.",
    "dungeon.beggar_fights_back": "The beggar snarls and slashes at you with a hidden blade!",
    "dungeon.beggar_damage": "You take {0} damage!",
    "dungeon.beggar_ignore": "You step past the beggar without a word.",
    "dungeon.beggar_eyes": "Their hollow eyes follow you into the darkness.",

    # Floor overview menus
    "dungeon.enter_dungeon_label": "nter the dungeon      ",
    "dungeon.journal_label": "ournal - Quest progress",
    "dungeon.party_mgmt_label": "Party management      ",
    "dungeon.status_label": "tatus",
    "dungeon.level_change_label": "evel change (+/- 10)  ",
    "dungeon.return_town_label": "eturn to town",

    # Encounters
    "dungeon.wounded_adventurer": "A wounded adventurer lies against the wall!",
    "dungeon.wounded_adventurer_map": "\"Please... take my map... avenge me...\"",
    "dungeon.gain_knowledge": "You gain knowledge of the dungeon layout!",
    "dungeon.rival_blocks": "A rival adventurer blocks your path!",
    "dungeon.rival_mine": "\"This treasure is MINE! Get out!\"",
    "dungeon.rival_bribe": "You pay {0} gold to pass.",
    "dungeon.rival_no_gold": "\"No gold? Then fight!\"",
    "dungeon.lost_explorer": "A lost explorer stumbles towards you!",
    "dungeon.lost_explorer_thanks": "\"Oh thank the gods! I've been lost for days!\"",
    "dungeon.guide_to_safety": "Guide them to safety",
    "dungeon.rob_and_leave": "Rob them and leave",
    "dungeon.leave_them": "Leave them be",
    "dungeon.rob_explorer": "You shove the explorer against the wall and take their belongings.",
    "dungeon.rob_explorer_cry": "\"No! Please! That's all I have!\"",
    "dungeon.rob_explorer_gold": "You take {0} gold from them.",
    "dungeon.darkness_increases": "Your darkness increases...",
    "dungeon.guide_explorer": "You guide them to safety.",
    "dungeon.explorer_reward": "They reward you with {0} gold!",
    "dungeon.chivalry_increases": "Your chivalry increases!",
    "dungeon.leave_explorer": "You walk past without a word.",
    "dungeon.explorer_plea": "\"Wait! Please don't leave me here!\"",
    "dungeon.explorer_fades": "Their voice fades behind you.",
    "dungeon.cloaked_figure": "A cloaked figure emerges from the shadows...",
    "dungeon.cloaked_figure_fate": "\"Fate has brought us together...\"",
    "dungeon.cloaked_blessing": "They offer you a blessing!",
    "dungeon.cloaked_revitalized": "You feel revitalized!",
    "dungeon.cloaked_beware": "\"Beware the darkness ahead...\"",
    "dungeon.cloaked_vanish": "They vanish as mysteriously as they appeared.",

    # Puzzles/riddles
    "dungeon.mechanism_unlocks": "The ancient mechanism unlocks!",
    "dungeon.puzzle_gold_xp": "You receive {0} gold and {1} experience!",
    "dungeon.riddle_truth": "As you solve the riddle, a deeper truth resonates within you...",
    "dungeon.ocean_wisdom": "You've gained insight into the Ocean's wisdom...",
    "dungeon.gate_sealed": "The gate remains sealed.",
    "dungeon.trap_activates": "A trap activates! You take {0} damage!",
    "dungeon.attempts_remaining": "Attempts remaining: {0}",
    "dungeon.not_quite_right": "That's not quite right...",
    "dungeon.puzzle_gain_gold_xp": "You gain {0} gold and {1} experience!",
    "dungeon.puzzle_failed": "The puzzle resets. You failed to solve it.",
    "dungeon.trap_springs": "A trap springs! You take {0} damage!",
    "dungeon.lever_puzzle": "There are {0} levers. Enter the sequence (e.g., 1,2,3):",
    "dungeon.symbol_puzzle": "Available symbols: {0}",
    "dungeon.symbol_enter": "Enter {0} symbols separated by commas:",
    "dungeon.number_target": "Target sum: {0}",
    "dungeon.number_available": "Available numbers: {0}",
    "dungeon.number_enter": "Enter numbers that sum to the target:",
    "dungeon.memorize": "Memorize this sequence:",
    "dungeon.enter_sequence": "Enter the sequence you saw:",
    "dungeon.careful_thought": "This puzzle requires careful thought...",
    "dungeon.examine_carefully": "Examine carefully and deduce the answer",
    "dungeon.try_random": "Try a random approach",
    "dungeon.give_up": "Give up",

    # Riddle gate
    "dungeon.stone_door": "A massive stone door blocks your path.",
    "dungeon.stone_face": "Carved into its surface: a face, ancient and knowing.",
    "dungeon.stone_riddle": "The stone lips move: 'Answer my riddle to pass.'",
    "dungeon.stone_correct": "The stone face smiles. 'Wisdom opens all doors.'",
    "dungeon.stone_open": "The gate rumbles open.",
    "dungeon.riddle_xp": "You gain {0} experience!",
    "dungeon.riddle_deeper": "The riddle's deeper meaning resonates within you...",
    "dungeon.gate_guardian": "The gate guardian manifests to punish your ignorance!",

    # Old god floor
    "dungeon.sense_power": "You sense great power once resided here.",
    "dungeon.moved_on": "But whatever dwelt in this place... has moved on.",
    "dungeon.perhaps_deeper": "Perhaps deeper in the dungeon, you will find what you seek.",

    # Sanctuary
    "dungeon.sanctuary_discover": "You discover a hidden sanctuary!",
    "dungeon.sanctuary_calm": "The air here is calm, protected by ancient magic.",
    "dungeon.sanctuary_camp": "You make camp and recover your strength.",
    "dungeon.sanctuary_hp": "You recover {0} HP!",
    "dungeon.sanctuary_mana": "You recover {0} mana!",
    "dungeon.sanctuary_stamina": "You recover {0} stamina!",
    "dungeon.sanctuary_cure_poison": "The sanctuary's magic cures your poison!",
    "dungeon.sanctuary_close_eyes": "You close your eyes...",
    "dungeon.sanctuary_sleep_deep": "You sleep deeply in the sanctuary's protection...",
    "dungeon.sanctuary_new_day": "You awaken refreshed. A new day has begun. (Day {0})",
    "dungeon.sanctuary_already_rested": "You've already rested on this floor.",
    "dungeon.sanctuary_no_benefit": "The sanctuary offers no additional benefit.",

    # Mystery events
    "dungeon.vision_overtakes": "A strange vision overtakes you...",
    "dungeon.vision_layout": "You see the layout of this floor!",
    "dungeon.rooms_revealed": "All rooms are now revealed on your map!",
    "dungeon.reality_warps": "Reality warps around you!",
    "dungeon.feel_stronger": "When it clears, you feel younger, stronger!",
    "dungeon.ghost_appears_room": "A ghostly figure appears!",
    "dungeon.ghost_seek_chamber": "\"Seek the chamber of bones...\"",
    "dungeon.ghost_find_seek": "\"There you will find what you seek...\"",
    "dungeon.ghost_points": "The ghost points towards a direction and fades.",
    "dungeon.portal_opens": "A magical portal suddenly opens beneath you!",
    "dungeon.transported_to": "You are transported to: {0}!",
    "dungeon.gold_rains": "Gold coins rain from the ceiling!",
    "dungeon.gather_gold": "You gather {0} gold!",

    # Lore library
    "dungeon.lore_library_1": "Dust motes dance in pale light from an unknown source.",
    "dungeon.lore_library_2": "Ancient tomes line walls that stretch beyond sight.",
    "dungeon.lore_library_tome": "A tome floats down from the shelves, opening before you...",
    "dungeon.lore_library_burns": "The words burn into your memory...",
    "dungeon.lore_library_stirs": "Something stirs in the depths of your consciousness...",
    "dungeon.lore_library_nothing": "You browse the ancient texts, but find nothing new.",
    "dungeon.lore_library_known": "The knowledge here already lives within you.",

    # Memory chamber
    "dungeon.memory_mirrors_1": "The walls here are mirrors, but they don't show your reflection.",
    "dungeon.memory_mirrors_2": "They show... someone else. Someone familiar.",
    "dungeon.memory_surfaces": "A memory surfaces: \"{0}\"",
    "dungeon.memory_fades": "The vision fades, but the feeling remains.",
    "dungeon.memory_fragments": "The mirrors show fragments of a life not quite your own.",
    "dungeon.memory_not_yet": "You sense there is more to remember, but not here. Not yet.",

    # Settlement healer
    "dungeon.settlement_poison_cured": "The poison in your veins is drawn out.",
    "dungeon.settlement_hp_restored": "Restored {0} HP.",
    "dungeon.settlement_mana_restored": "Restored {0} Mana.",
    "dungeon.settlement_no_heal_needed": "\"You look healthy enough to me. Save your coin.\"",
    "dungeon.settlement_your_gold": "Your Gold: {0}",
    "dungeon.settlement_purchased": "Purchased {0}!",

    # Battle aftermath
    "dungeon.battle_breaks_open": "As the battle ends, something breaks open in your mind...",

    # Exploration text
    "dungeon.explore_1": "You cautiously advance through the shadowy corridors...",
    "dungeon.explore_2": "Your footsteps echo in the ancient stone passages...",
    "dungeon.explore_3": "Flickering torchlight reveals mysterious doorways ahead...",
    "dungeon.explore_4": "The air grows colder as you venture deeper into the dungeon...",
    "dungeon.explore_5": "Strange sounds echo from the darkness beyond...",

    # Terrain descriptions
    "dungeon.terrain_underground": "Ancient Underground Tunnels",
    "dungeon.terrain_mountains": "Rocky Mountain Passages",
    "dungeon.terrain_desert": "Desert Ruins and Tombs",
    "dungeon.terrain_forest": "Overgrown Forest Caves",
    "dungeon.terrain_caves": "Deep Natural Caverns",
    "dungeon.terrain_unknown": "Unknown Territory",

    # BBS menu labels
    "dungeon.bbs_fight": "Fight",
    "dungeon.bbs_treasure": "Treasure",
    "dungeon.bbs_investigate": "Investigate",
    "dungeon.bbs_examine": "Examine",
    "dungeon.bbs_descend": "Descend",
    "dungeon.bbs_camp": "Camp",
    "dungeon.bbs_map_label": "Map",
    "dungeon.bbs_guide_label": "Guide",
    "dungeon.bbs_inv": "Inv",
    "dungeon.bbs_potions_label": "Potions",
    "dungeon.bbs_status_label": "Status",
    "dungeon.bbs_leave": "Leave",
    "dungeon.bbs_enter": "Enter",
    "dungeon.bbs_journal": "Journal",
    "dungeon.bbs_party": "Party",
    "dungeon.bbs_level_change": "Level(+/-10)",
    "dungeon.bbs_return": "Return",

    # Lyris encounter (non-narrative UI strings only)
    "dungeon.ask_join_yn": "Ask her to join you? (Y/N): ",
    "dungeon.companion_warning": "WARNING: Companions can die permanently. Guard her well.",
    "dungeon.personal_quest": "Personal Quest: {0}",

    # Pixie encounter
    "dungeon.pixie_appears": "A tiny glowing pixie darts through the corridor!",
    "dungeon.pixie_giggles": "She flits about trailing sparkles of light, giggling mischievously.",
    "dungeon.pixie_catch": "Try to catch her",
    "dungeon.pixie_leave": "Leave her be",
    "dungeon.pixie_caught": "You snatch the pixie gently from the air!",
    "dungeon.pixie_eyes": "She looks up at you with sparkling eyes...",
    "dungeon.pixie_kiss_quote": "\"Oh! You're quick! Very well, a kiss for the clever one!\"",
    "dungeon.pixie_restored": "The pixie's kiss fills you with warmth. You feel completely restored!",
    "dungeon.pixie_blessing": "A pixie blessing settles over you! (+15% damage/defense for 5 combats)",
    "dungeon.pixie_blessing_stronger": "Your existing blessing grows stronger! (+3 bonus combat rounds)",
    "dungeon.pixie_gold": "She sprinkles pixie dust that turns to gold! (+{0} gold)",
    "dungeon.pixie_vanish": "The pixie winks and vanishes in a shower of sparkles.",
    "dungeon.pixie_dodge": "The pixie dodges your grasp!",
    "dungeon.pixie_clumsy": "\"Clumsy mortal! You'll regret that!\"",
    "dungeon.pixie_dust": "She blows a cloud of sparkling dust in your face!",
    "dungeon.pixie_poisoned": "The pixie dust makes you feel queasy... you've been poisoned!",
    "dungeon.pixie_steals": "She snatches {0} gold from your pouch as she flies away!",
    "dungeon.pixie_cackles": "The pixie cackles and disappears in a puff of glitter.",
    "dungeon.pixie_watch": "You watch the pixie flit away, her laughter echoing off the walls.",
    "dungeon.pixie_alone": "Perhaps some things are best left alone.",
}

new_es = {
    "dungeon.potion_cache_header": "ALIJO DE POCIONES",
    "dungeon.potion_cache_header_sr": "-- ALIJO DE POCIONES --",
    "dungeon.potion_cache_msg_1": "¡Descubres un maletín de curandero abandonado!",
    "dungeon.potion_cache_msg_2": "¡La mochila de un aventurero caído contiene suministros de curación!",
    "dungeon.potion_cache_msg_3": "¡Encuentras un alijo abandonado de pociones de un monje!",
    "dungeon.potion_cache_msg_4": "¡Un nicho oculto revela un alijo de elixires curativos!",
    "dungeon.potion_cache_msg_5": "¡El cadáver de un clérigo sostiene una bolsa de pociones!",
    "dungeon.potion_cache_max": "¡Ya tienes el número máximo de pociones!",
    "dungeon.potion_cache_leave": "Dejas las pociones para otro aventurero.",
    "dungeon.potion_cache_collect": "¡Recoges {0} poción/pociones de curación!",
    "dungeon.potion_cache_count": "Pociones: {0}/{1}",
    "dungeon.potion_cache_left_behind": "(Tuviste que dejar {0} poción/pociones atrás - capacidad máxima)",
    "dungeon.merchant_appears": "¡Un mercader ambulante aparece de las sombras!",
    "dungeon.merchant_greeting_text": "\"¡Saludos, valiente aventurero! ¿Deseas comerciar?\"",
    "dungeon.merchant_trade_or_attack": "(C)omerciar con el mercader o (A)tacar por mercancías? ",
    "dungeon.merchant_rob": "¡Decides robar al pobre mercader!",
    "dungeon.merchant_loot_split": "¡Saqueas {0} oro y 3 pociones de curación del mercader! (dividido entre {1})",
    "dungeon.merchant_loot": "¡Saqueas {0} oro y 3 pociones de curación del mercader!",
    "dungeon.merchant_darkness": "+10 Oscuridad por atacar a un mercader inocente!",
    "dungeon.merchant_goodbye": "El mercader se despide y desaparece en las sombras.",
    "dungeon.merchant_healing_potion": "Poción de Curación ({0}o)",
    "dungeon.merchant_mega_potion": "Mega Poción ({0}o) - ¡Curación completa!",
    "dungeon.merchant_antidote": "Antídoto ({0}o) - Cura veneno ({1}/{2})",
    "dungeon.merchant_buy_max": "Comprar Máx. Pociones ({0}o)",
    "dungeon.merchant_buy_max_full": "Comprar Máx. Pociones (¡lleno!)",
    "dungeon.merchant_leave_shop": "Salir de la tienda",
    "dungeon.merchant_cant_carry_potions": "\"¡No puedes llevar más pociones, amigo!\"",
    "dungeon.merchant_purchased_potion": "¡Poción de curación comprada! ({0}/{1})",
    "dungeon.merchant_mega_full_heal": "¡Bebes la mega poción - SALUD COMPLETAMENTE RESTAURADA!",
    "dungeon.merchant_cant_carry_antidotes": "\"¡No puedes llevar más antídotos, amigo!\"",
    "dungeon.merchant_antidote_cure": "¡Bebes el antídoto — el veneno se drena de tu cuerpo!",
    "dungeon.merchant_purchased_antidote": "¡Antídoto comprado! ({0}/{1})",
    "dungeon.merchant_full_potions": "\"¡Ya estás lleno de pociones!\"",
    "dungeon.merchant_purchased_potions": "¡{0} pociones compradas por {1}o!",
    "dungeon.merchant_potions_count": "Pociones: {0}/{1}",
    "dungeon.merchant_afford_partial": "Solo pudiste pagar {0} pociones.",
    "dungeon.merchant_safe_travels": "\"¡Buen viaje, aventurero!\"",
    "dungeon.merchant_invalid": "Opción inválida.",
    "dungeon.merchant_item_sold": "\"Ese artículo ya se vendió, amigo.\"",
    "dungeon.merchant_need_gold": "\"Necesitas {0} oro para {1}.\"",
    "dungeon.merchant_come_back": "\"¡Vuelve cuando tengas más monedas!\"",
    "dungeon.merchant_purchase_confirm": "¿Comprar {0} por {1} oro? (S/N)",
    "dungeon.merchant_added_inventory": "Añadido a tu inventario.",
    "dungeon.merchant_fine_choice": "\"¡Buena elección! Úsalo bien.\"",
    "dungeon.merchant_another_time": "\"Quizás en otra ocasión.\"",
    "dungeon.merchant_current_weapon": "Tu poder de arma actual: {0}",
    "dungeon.merchant_current_armor": "Tu poder de armadura actual: {0}",
    "dungeon.witch_doctor_header": "=== ENCUENTRO CON BRUJO ===",
    "dungeon.witch_doctor_meet": "¡Conoces al malvado Brujo Mbluta!",
    "dungeon.witch_doctor_demand": "¡Exige {0} oro o te maldecirá!",
    "dungeon.witch_doctor_prompt": "(P)agar al brujo o (H)uir? ",
    "dungeon.witch_doctor_pay": "Pagas al brujo de mala gana.",
    "dungeon.witch_doctor_vanish": "Desaparece en la oscuridad...",
    "dungeon.witch_doctor_flee": "¡Logras huir del malvado brujo!",
    "dungeon.witch_doctor_cursed": "¡No logras escapar y eres maldecido!",
    "dungeon.witch_doctor_lose_exp": "¡Pierdes {0} puntos de experiencia!",
    "dungeon.witch_doctor_lose_fights": "¡Pierdes {0} peleas de mazmorra!",
    "dungeon.witch_doctor_lose_pfights": "¡Pierdes {0} peleas de jugador!",
    "dungeon.witch_doctor_no_gold": "Un brujo aparece pero ve que no tienes oro y se va.",
    "dungeon.must_defeat_old_god": "Debes derrotar al Dios Antiguo en este piso antes de descender más.",
    "dungeon.cant_venture_deeper": "No puedes aventurarte más allá del nivel {0} con tu fuerza actual.",
    "dungeon.level_up_access": "Sube de nivel para acceder a pisos más profundos.",
    "dungeon.descend_to": "Desciendes al nivel {0} de la mazmorra.",
    "dungeon.deepest_level": "Has alcanzado el nivel más profundo de la mazmorra.",
    "dungeon.ascend_to": "Asciendes al nivel {0} de la mazmorra.",
    "dungeon.no_one_to_bring": "No tienes a nadie para llevar contigo.",
    "dungeon.get_team": "¡Cásate, recluta compañeros o únete a un equipo!",
    "dungeon.team_label": "Equipo: {0}",
    "dungeon.team_turf": "El equipo controla territorio: {0}",
    "dungeon.no_team_loved_ones": "No estás en un equipo, pero tus seres queridos pueden unirse.",
    "dungeon.current_dungeon_party": "Grupo de Mazmorra Actual:",
    "dungeon.available_companions": "Compañeros Disponibles (en espera):",
    "dungeon.available_allies": "Aliados Disponibles (no en el grupo):",
    "dungeon.no_allies_available": "No hay aliados disponibles para tu grupo de mazmorra.",
    "dungeon.options": "Opciones:",
    "dungeon.add_companion_party": "] Añadir compañero al grupo",
    "dungeon.add_ally": "]ñadir aliado al grupo",
    "dungeon.remove_ally": "]liminar aliado del grupo",
    "dungeon.xp_distribution_pct": "] Distribución XP ({0}% asignado)",
    "dungeon.back_dungeon_menu": "]olver al menú de mazmorra",
    "dungeon.party_full_max4": "¡Tu grupo de mazmorra está lleno (máximo 4 compañeros)!",
    "dungeon.invalid_companion": "Selección de compañero inválida.",
    "dungeon.no_team_members": "No hay miembros de equipo disponibles.",
    "dungeon.no_teammates_remove": "No hay compañeros para eliminar.",
    "dungeon.companion_role": "Rol: {0}",
    "dungeon.could_not_add": "No se pudo añadir a {0} al grupo.",
    "dungeon.enter_team_number": "Ingresa número del miembro (1-{0}): ",
    "dungeon.npc_higher_level": "{0} es {1} niveles más alto que tú.",
    "dungeon.npc_demand_fee": "Exigen {0} oro para unirse en la mazmorra.",
    "dungeon.your_gold": "Tu oro: {0}",
    "dungeon.cannot_afford_fee": "¡No puedes pagar esta tarifa!",
    "dungeon.pay_fee_confirm": "¿Pagar {0} oro? (S/N): ",
    "dungeon.npc_shrugs": "{0} se encoge de hombros y se queda atrás.",
    "dungeon.paid_fee": "Pagados {0} oro.",
    "dungeon.npc_joins": "¡{0} se une a tu grupo de mazmorra!",
    "dungeon.fight_alongside": "Lucharán a tu lado contra los monstruos.",
    "dungeon.xp_penalty_warning": "Advertencia: Penalización de XP activa ({0}% por aliado de alto nivel)",
    "dungeon.team_bonus": "¡Bonificación de equipo: +15% XP y oro en batallas!",
    "dungeon.enter_party_remove": "Ingresa número del grupo a eliminar (2-{0}): ",
    "dungeon.grouped_player_leave": "{0} es un jugador agrupado — debe escribir /leave para salir del grupo.",
    "dungeon.companion_steps_back": "{0} retrocede de la primera línea.",
    "dungeon.companion_available": "(Siguen disponibles - usa Gestión de Grupo para traerlos de vuelta)",
    "dungeon.npc_returns_town": "{0} deja el grupo de mazmorra y regresa al pueblo.",
    "dungeon.member_leaves_party": "{0} deja el grupo de mazmorra.",
    "dungeon.companion_rejoins": "¡{0} se reúne con tu grupo!",
    "dungeon.grouped_independent": "({0} jugador(es) agrupados ganan XP independientemente)",
    "dungeon.current_party_xp": "Grupo actual:",
    "dungeon.xp_unallocated": "¡Advertencia: {0}% de XP no asignado!",
    "dungeon.xp_adjust_prompt": "Ingresa número de casilla, [E]quitativo, o [V]olver:",
    "dungeon.xp_even_split": "XP dividido equitativamente: {0}% para ti, {1}% por compañero.",
    "dungeon.xp_slot_empty": "Esa casilla está vacía.",
    "dungeon.xp_set_prompt": "Establecer % XP para {0} (0-{1}, actualmente {2}%): ",
    "dungeon.xp_min_self": "Debes mantener al menos 10% de XP para ti.",
    "dungeon.xp_total_exceeded": "El total sería {0}%. El máximo es 100%.",
    "dungeon.xp_set_to": "{0} establecido a {1}% XP.",
    "dungeon.invalid_percentage": "Porcentaje inválido.",
    "dungeon.party_full_allies": "¡Tu grupo está lleno (máximo 4 aliados)!",
    "dungeon.make_room": "{0} quiere unirse, pero necesitas hacer espacio.",
    "dungeon.current_party_members": "Miembros actuales del grupo:",
    "dungeon.remove_make_room": "[R] Eliminar a alguien para hacer espacio",
    "dungeon.cancel_recruitment": "[C] Cancelar reclutamiento",
    "dungeon.who_should_leave": "¿Quién debería dejar el grupo?",
    "dungeon.companions_readd": "(Los compañeros pueden ser re-añadidos desde Gestión de Grupo)",
    "dungeon.enter_remove_number": "Ingresa número (1-{0}): ",
    "dungeon.invalid_cancelled": "Selección inválida. Reclutamiento cancelado.",
    "dungeon.recruitment_cancelled": "Reclutamiento cancelado.",
    "dungeon.use_potion_self": "Usar Poción de Curación (cura ~{0} PV)",
    "dungeon.buy_potions_monk": "Comprar Pociones al Monje (Curación {0}o, Maná {1}o)",
    "dungeon.heal_full": "Curarte completamente (usar múltiples pociones)",
    "dungeon.heal_teammate": "Curar a un Compañero",
    "dungeon.heal_all": "Curar a TODOS los Miembros del Grupo",
    "dungeon.use_antidote": "Usar Antídoto (cura veneno, {0} restantes)",
    "dungeon.use_antidote_not_poisoned": "Usar Antídoto ({0} restantes) - no envenenado",
    "dungeon.return_dungeon": "Volver a la Mazmorra",
    "dungeon.no_potions_potion_menu": "Usar Poción de Curación - ¡SIN POCIONES!",
    "dungeon.antidote_cure_poison": "¡Bebes el antídoto — el veneno se drena de tu cuerpo!",
    "dungeon.not_poisoned": "¡No estás envenenado!",
    "dungeon.no_antidotes": "¡No tienes antídotos!",
    "dungeon.select_teammate_heal": "Selecciona compañero a curar:",
    "dungeon.cancel": "Cancelar",
    "dungeon.choose": "Elige: ",
    "dungeon.already_full_health_name": "¡{0} ya tiene salud completa!",
    "dungeon.missing_hp": "A {0} le faltan {1} PV.",
    "dungeon.each_potion_heals": "Cada poción cura aproximadamente {0} PV.",
    "dungeon.use_1_potion": "Usar 1 poción",
    "dungeon.fully_heal_potions": "Curar completamente (usa hasta {0} pociones)",
    "dungeon.give_potion_one": "¡Le das una poción de curación a {0}!",
    "dungeon.give_potions_many": "¡Le das {0} pociones de curación a {1}!",
    "dungeon.recovers_hp": "¡{0} recupera {1} PV!",
    "dungeon.fully_healed_name": "¡{0} está completamente curado!",
    "dungeon.everyone_full_health": "¡Todos ya tienen salud completa!",
    "dungeon.heal_party_requires": "Curar a todo el grupo requiere aproximadamente {0} pociones.",
    "dungeon.you_have_potions": "Tienes {0} pociones.",
    "dungeon.not_enough_potions_warning": "Advertencia: No hay suficientes pociones. Se usarán todas las {0}.",
    "dungeon.yes_heal_party": "Sí, curar al grupo (usa {0} pociones)",
    "dungeon.distributing_potions": "Distribuyendo pociones al grupo...",
    "dungeon.you_recover_hp": "¡Recuperas {0} PV!",
    "dungeon.teammate_recovers": "¡{0} recupera {1} PV!",
    "dungeon.used_potions_total": "Usaste {0} pociones. PV total restaurados: {1}",
    "dungeon.potions_remaining": "Pociones restantes: {0}/{1}",
    "dungeon.no_healing_potions": "¡No tienes pociones de curación!",
    "dungeon.already_full_health": "¡Ya tienes salud completa!",
    "dungeon.drink_potion_recover": "¡Bebes una poción de curación y recuperas {0} PV!",
    "dungeon.will_use_potions": "Esto usará {0} poción/pociones. ¿Continuar? (S/N)",
    "dungeon.drink_potions_recover": "¡Bebes {0} poción/pociones de curación y recuperas {1} PV!",
    "dungeon.monk_appears": "Un monje errante se materializa de las sombras...",
    "dungeon.monk_greeting": "\"Saludos, viajero. Tengo suministros para cuerpo y mente.\"",
    "dungeon.monk_your_gold": "Tu oro: {0}",
    "dungeon.monk_another_time": "\"Quizás en otra ocasión.\"",
    "dungeon.monk_fades": "El monje se inclina y desaparece en las sombras...",
    "dungeon.monk_max_potions": "\"¡Ya llevas todas las pociones de {0} que puedes!\"",
    "dungeon.monk_no_gold": "\"Me temo que te falta oro, amigo.\"",
    "dungeon.monk_how_many": "¿Cuántas pociones de {0}? (Máx: {1}, 0 para cancelar)",
    "dungeon.monk_cancel": "\"Quizás en otra ocasión.\"",
    "dungeon.monk_only_provide": "\"Solo puedo proporcionarte {0}.\"",
    "dungeon.monk_purchased": "Compras {0} poción/pociones de {1} por {2} oro.",
    "dungeon.monk_gold_remaining": "Oro restante: {0}",
    "dungeon.no_floor_map": "No hay piso para mapear.",
    "dungeon.map_unavailable": "Datos del mapa no disponibles.",
    "dungeon.no_floor_data": "Sin datos del piso.",
    "dungeon.guide_title": "Guía de Mazmorra - Nivel {0}, {1}",
    "dungeon.you_are_in": "Estás en: {0}",
    "dungeon.guide_exits": "Salidas: {0}",
    "dungeon.boss_defeated": "Jefe derrotado.",
    "dungeon.no_known_destinations": "Sin destinos conocidos. Explora para descubrir habitaciones.",
    "dungeon.directions_to": "Direcciones a:",
    "dungeon.map_legend_you": "Tú",
    "dungeon.map_legend_cleared": "Limpio",
    "dungeon.map_legend_monsters": "Monstruos",
    "dungeon.map_legend_stairs": "Escaleras",
    "dungeon.map_legend_boss": "Jefe",
    "dungeon.map_legend_safe": "Seguro",
    "dungeon.map_legend_unknown": "Desconocido",
    "dungeon.help_title": "Ayuda de Mazmorra",
    "dungeon.help_explore": "E - Explorar el nivel actual",
    "dungeon.help_descend": "D - Descender a un nivel más profundo y peligroso",
    "dungeon.help_ascend": "A - Ascender a un nivel más seguro o volver al pueblo",
    "dungeon.help_team": "T - Gestionar miembros del equipo",
    "dungeon.help_status": "S - Ver estado del personaje",
    "dungeon.help_potions": "P - Comprar pociones al monje errante",
    "dungeon.help_map": "M - Ver el mapa de la mazmorra",
    "dungeon.help_guide": "G - Guía (direcciones a escaleras, inexplorado, sin limpiar, jefe)",
    "dungeon.help_quit": "Q - Salir y volver al pueblo",
    "dungeon.steel_nerves": "¡Te armas de valor. La mazmorra ahora se siente como nivel {0}!",
    "dungeon.beggar_appears": "Una figura andrajosa se acurruca contra la pared, con las manos extendidas.",
    "dungeon.beggar_plea": "\"Por favor... algo de oro para un alma perdida? Llevo días atrapado aquí.\"",
    "dungeon.beggar_give": "Entregas {0} oro. Los ojos del mendigo se llenan de lágrimas.",
    "dungeon.beggar_bless": "\"Bendito seas... bendito seas, alma bondadosa.\"",
    "dungeon.beggar_bonus": "El mendigo presiona algo en tu mano antes de irse arrastrando.",
    "dungeon.beggar_bonus_gold": "¡Es una bolsa oculta con {0} oro!",
    "dungeon.beggar_test": "\"Estaba probando tu corazón. Pasaste.\"",
    "dungeon.beggar_rob": "Empujas al mendigo y rebuscas entre sus harapos.",
    "dungeon.beggar_rob_gold": "Encuentras {0} oro oculto en su capa.",
    "dungeon.beggar_fights_back": "¡El mendigo gruñe y te ataca con una hoja oculta!",
    "dungeon.beggar_damage": "¡Recibes {0} de daño!",
    "dungeon.beggar_ignore": "Pasas junto al mendigo sin decir palabra.",
    "dungeon.beggar_eyes": "Sus ojos vacíos te siguen hacia la oscuridad.",
    "dungeon.enter_dungeon_label": "ntrar a la mazmorra    ",
    "dungeon.journal_label": "iario - Progreso de misiones",
    "dungeon.party_mgmt_label": "Gestión de grupo        ",
    "dungeon.status_label": "stado",
    "dungeon.level_change_label": "ivel cambiar (+/- 10)  ",
    "dungeon.return_town_label": "egresar al pueblo",
    "dungeon.wounded_adventurer": "¡Un aventurero herido yace contra la pared!",
    "dungeon.wounded_adventurer_map": "\"Por favor... toma mi mapa... véngame...\"",
    "dungeon.gain_knowledge": "¡Obtienes conocimiento del diseño de la mazmorra!",
    "dungeon.rival_blocks": "¡Un aventurero rival bloquea tu camino!",
    "dungeon.rival_mine": "\"¡Este tesoro es MÍO! ¡Fuera!\"",
    "dungeon.rival_bribe": "Pagas {0} oro para pasar.",
    "dungeon.rival_no_gold": "\"¿Sin oro? ¡Entonces pelea!\"",
    "dungeon.lost_explorer": "¡Un explorador perdido se acerca tambaleándose!",
    "dungeon.lost_explorer_thanks": "\"¡Oh, gracias a los dioses! ¡Llevo días perdido!\"",
    "dungeon.guide_to_safety": "Guiarlos a un lugar seguro",
    "dungeon.rob_and_leave": "Robarles y marcharse",
    "dungeon.leave_them": "Dejarlos",
    "dungeon.rob_explorer": "Empujas al explorador contra la pared y tomas sus pertenencias.",
    "dungeon.rob_explorer_cry": "\"¡No! ¡Por favor! ¡Es todo lo que tengo!\"",
    "dungeon.rob_explorer_gold": "Tomas {0} oro de ellos.",
    "dungeon.darkness_increases": "Tu oscuridad aumenta...",
    "dungeon.guide_explorer": "Los guías a un lugar seguro.",
    "dungeon.explorer_reward": "¡Te recompensan con {0} oro!",
    "dungeon.chivalry_increases": "¡Tu caballerosidad aumenta!",
    "dungeon.leave_explorer": "Pasas sin decir palabra.",
    "dungeon.explorer_plea": "\"¡Espera! ¡Por favor, no me dejes aquí!\"",
    "dungeon.explorer_fades": "Su voz se desvanece detrás de ti.",
    "dungeon.cloaked_figure": "Una figura encapuchada emerge de las sombras...",
    "dungeon.cloaked_figure_fate": "\"El destino nos ha reunido...\"",
    "dungeon.cloaked_blessing": "¡Te ofrecen una bendición!",
    "dungeon.cloaked_revitalized": "¡Te sientes revitalizado!",
    "dungeon.cloaked_beware": "\"Cuidado con la oscuridad que hay adelante...\"",
    "dungeon.cloaked_vanish": "Desaparecen tan misteriosamente como aparecieron.",
    "dungeon.mechanism_unlocks": "¡El antiguo mecanismo se desbloquea!",
    "dungeon.puzzle_gold_xp": "¡Recibes {0} oro y {1} experiencia!",
    "dungeon.riddle_truth": "Al resolver el acertijo, una verdad más profunda resuena en ti...",
    "dungeon.ocean_wisdom": "Has obtenido conocimiento de la sabiduría del Océano...",
    "dungeon.gate_sealed": "La puerta permanece sellada.",
    "dungeon.trap_activates": "¡Una trampa se activa! ¡Recibes {0} de daño!",
    "dungeon.attempts_remaining": "Intentos restantes: {0}",
    "dungeon.not_quite_right": "Eso no es del todo correcto...",
    "dungeon.puzzle_gain_gold_xp": "¡Ganas {0} oro y {1} experiencia!",
    "dungeon.puzzle_failed": "El rompecabezas se reinicia. No pudiste resolverlo.",
    "dungeon.trap_springs": "¡Una trampa salta! ¡Recibes {0} de daño!",
    "dungeon.lever_puzzle": "Hay {0} palancas. Ingresa la secuencia (ej., 1,2,3):",
    "dungeon.symbol_puzzle": "Símbolos disponibles: {0}",
    "dungeon.symbol_enter": "Ingresa {0} símbolos separados por comas:",
    "dungeon.number_target": "Suma objetivo: {0}",
    "dungeon.number_available": "Números disponibles: {0}",
    "dungeon.number_enter": "Ingresa números que sumen el objetivo:",
    "dungeon.memorize": "Memoriza esta secuencia:",
    "dungeon.enter_sequence": "Ingresa la secuencia que viste:",
    "dungeon.careful_thought": "Este rompecabezas requiere pensamiento cuidadoso...",
    "dungeon.examine_carefully": "Examinar cuidadosamente y deducir la respuesta",
    "dungeon.try_random": "Intentar un enfoque aleatorio",
    "dungeon.give_up": "Rendirse",
    "dungeon.stone_door": "Una enorme puerta de piedra bloquea tu camino.",
    "dungeon.stone_face": "Tallado en su superficie: un rostro, antiguo y sabio.",
    "dungeon.stone_riddle": "Los labios de piedra se mueven: 'Responde mi acertijo para pasar.'",
    "dungeon.stone_correct": "El rostro de piedra sonríe. 'La sabiduría abre todas las puertas.'",
    "dungeon.stone_open": "La puerta se abre con un estruendo.",
    "dungeon.riddle_xp": "¡Ganas {0} experiencia!",
    "dungeon.riddle_deeper": "El significado más profundo del acertijo resuena en ti...",
    "dungeon.gate_guardian": "¡El guardián de la puerta se manifiesta para castigar tu ignorancia!",
    "dungeon.sense_power": "Sientes que un gran poder residió aquí.",
    "dungeon.moved_on": "Pero lo que habitaba este lugar... se ha ido.",
    "dungeon.perhaps_deeper": "Quizás más profundo en la mazmorra encontrarás lo que buscas.",
    "dungeon.sanctuary_discover": "¡Descubres un santuario oculto!",
    "dungeon.sanctuary_calm": "El aire aquí es tranquilo, protegido por magia antigua.",
    "dungeon.sanctuary_camp": "Acampas y recuperas fuerzas.",
    "dungeon.sanctuary_hp": "¡Recuperas {0} PV!",
    "dungeon.sanctuary_mana": "¡Recuperas {0} maná!",
    "dungeon.sanctuary_stamina": "¡Recuperas {0} estamina!",
    "dungeon.sanctuary_cure_poison": "¡La magia del santuario cura tu veneno!",
    "dungeon.sanctuary_close_eyes": "Cierras los ojos...",
    "dungeon.sanctuary_sleep_deep": "Duermes profundamente bajo la protección del santuario...",
    "dungeon.sanctuary_new_day": "Despiertas renovado. Un nuevo día ha comenzado. (Día {0})",
    "dungeon.sanctuary_already_rested": "Ya descansaste en este piso.",
    "dungeon.sanctuary_no_benefit": "El santuario no ofrece beneficio adicional.",
    "dungeon.vision_overtakes": "Una extraña visión te invade...",
    "dungeon.vision_layout": "¡Ves el diseño de este piso!",
    "dungeon.rooms_revealed": "¡Todas las habitaciones están reveladas en tu mapa!",
    "dungeon.reality_warps": "¡La realidad se distorsiona a tu alrededor!",
    "dungeon.feel_stronger": "Cuando se aclara, ¡te sientes más joven y fuerte!",
    "dungeon.ghost_appears_room": "¡Una figura fantasmal aparece!",
    "dungeon.ghost_seek_chamber": "\"Busca la cámara de huesos...\"",
    "dungeon.ghost_find_seek": "\"Allí encontrarás lo que buscas...\"",
    "dungeon.ghost_points": "El fantasma señala una dirección y se desvanece.",
    "dungeon.portal_opens": "¡Un portal mágico se abre bajo tus pies!",
    "dungeon.transported_to": "¡Eres transportado a: {0}!",
    "dungeon.gold_rains": "¡Monedas de oro caen del techo!",
    "dungeon.gather_gold": "¡Recoges {0} oro!",
    "dungeon.lore_library_1": "Motas de polvo danzan en una luz pálida de fuente desconocida.",
    "dungeon.lore_library_2": "Tomos antiguos cubren paredes que se extienden más allá de la vista.",
    "dungeon.lore_library_tome": "Un tomo flota de los estantes, abriéndose ante ti...",
    "dungeon.lore_library_burns": "Las palabras se graban en tu memoria...",
    "dungeon.lore_library_stirs": "Algo se agita en las profundidades de tu consciencia...",
    "dungeon.lore_library_nothing": "Hojeas los textos antiguos, pero no encuentras nada nuevo.",
    "dungeon.lore_library_known": "El conocimiento aquí ya vive dentro de ti.",
    "dungeon.memory_mirrors_1": "Las paredes son espejos, pero no muestran tu reflejo.",
    "dungeon.memory_mirrors_2": "Muestran... a alguien más. Alguien familiar.",
    "dungeon.memory_surfaces": "Un recuerdo emerge: \"{0}\"",
    "dungeon.memory_fades": "La visión se desvanece, pero el sentimiento permanece.",
    "dungeon.memory_fragments": "Los espejos muestran fragmentos de una vida que no es del todo tuya.",
    "dungeon.memory_not_yet": "Sientes que hay más por recordar, pero no aquí. No aún.",
    "dungeon.settlement_poison_cured": "El veneno se drena de tus venas.",
    "dungeon.settlement_hp_restored": "Restaurados {0} PV.",
    "dungeon.settlement_mana_restored": "Restaurados {0} Maná.",
    "dungeon.settlement_no_heal_needed": "\"Me pareces bastante sano. Ahorra tus monedas.\"",
    "dungeon.settlement_your_gold": "Tu Oro: {0}",
    "dungeon.settlement_purchased": "¡{0} comprado!",
    "dungeon.battle_breaks_open": "Al terminar la batalla, algo se abre en tu mente...",
    "dungeon.explore_1": "Avanzas cautelosamente por los corredores sombríos...",
    "dungeon.explore_2": "Tus pasos resuenan en los antiguos pasajes de piedra...",
    "dungeon.explore_3": "La luz parpadeante de las antorchas revela misteriosas puertas...",
    "dungeon.explore_4": "El aire se enfría a medida que te aventuras más profundo...",
    "dungeon.explore_5": "Sonidos extraños resuenan desde la oscuridad...",
    "dungeon.terrain_underground": "Túneles Subterráneos Antiguos",
    "dungeon.terrain_mountains": "Pasajes de Montaña Rocosos",
    "dungeon.terrain_desert": "Ruinas y Tumbas del Desierto",
    "dungeon.terrain_forest": "Cuevas de Bosque Frondoso",
    "dungeon.terrain_caves": "Cavernas Naturales Profundas",
    "dungeon.terrain_unknown": "Territorio Desconocido",
    "dungeon.bbs_fight": "Pelear",
    "dungeon.bbs_treasure": "Tesoro",
    "dungeon.bbs_investigate": "Investigar",
    "dungeon.bbs_examine": "Examinar",
    "dungeon.bbs_descend": "Descender",
    "dungeon.bbs_camp": "Acampar",
    "dungeon.bbs_map_label": "Mapa",
    "dungeon.bbs_guide_label": "Guía",
    "dungeon.bbs_inv": "Inv",
    "dungeon.bbs_potions_label": "Pociones",
    "dungeon.bbs_status_label": "Estado",
    "dungeon.bbs_leave": "Salir",
    "dungeon.bbs_enter": "Entrar",
    "dungeon.bbs_journal": "Diario",
    "dungeon.bbs_party": "Grupo",
    "dungeon.bbs_level_change": "Nivel(+/-10)",
    "dungeon.bbs_return": "Regresar",
    "dungeon.ask_join_yn": "¿Pedirle que se una? (S/N): ",
    "dungeon.companion_warning": "ADVERTENCIA: Los compañeros pueden morir permanentemente. Protégela bien.",
    "dungeon.personal_quest": "Misión Personal: {0}",
    "dungeon.pixie_appears": "¡Un pequeño duende brillante cruza el corredor!",
    "dungeon.pixie_giggles": "Revolotea dejando destellos de luz, riendo traviesamente.",
    "dungeon.pixie_catch": "Intentar atraparla",
    "dungeon.pixie_leave": "Dejarla en paz",
    "dungeon.pixie_caught": "¡Atrapas al duende suavemente del aire!",
    "dungeon.pixie_eyes": "Te mira con ojos brillantes...",
    "dungeon.pixie_kiss_quote": "\"¡Oh! ¡Eres rápido! Bien, ¡un beso para el listo!\"",
    "dungeon.pixie_restored": "¡El beso del duende te llena de calidez. Te sientes completamente restaurado!",
    "dungeon.pixie_blessing": "¡Una bendición de duende se posa sobre ti! (+15% daño/defensa por 5 combates)",
    "dungeon.pixie_blessing_stronger": "¡Tu bendición existente se fortalece! (+3 rondas de combate extra)",
    "dungeon.pixie_gold": "¡Esparce polvo de duende que se convierte en oro! (+{0} oro)",
    "dungeon.pixie_vanish": "El duende guiña y desaparece en una lluvia de destellos.",
    "dungeon.pixie_dodge": "¡El duende esquiva tu agarre!",
    "dungeon.pixie_clumsy": "\"¡Mortal torpe! ¡Te arrepentirás de eso!\"",
    "dungeon.pixie_dust": "¡Sopla una nube de polvo brillante en tu cara!",
    "dungeon.pixie_poisoned": "¡El polvo de duende te hace sentir mal... estás envenenado!",
    "dungeon.pixie_steals": "¡Arrebata {0} oro de tu bolsa mientras vuela!",
    "dungeon.pixie_cackles": "El duende carcajea y desaparece en una nube de brillantina.",
    "dungeon.pixie_watch": "Observas al duende volar, su risa resonando en las paredes.",
    "dungeon.pixie_alone": "Quizás algunas cosas es mejor dejarlas en paz.",
}

for k, v in new_en.items():
    en[k] = v
for k, v in new_es.items():
    es[k] = v

with open('Localization/en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, ensure_ascii=False, indent=2)
with open('Localization/es.json', 'w', encoding='utf-8') as f:
    json.dump(es, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_en)} en keys, {len(new_es)} es keys. en: {len(en)}, es: {len(es)}")
