import json

with open('Localization/en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)
with open('Localization/es.json', 'r', encoding='utf-8') as f:
    es = json.load(f)

new_en = {
    # Encounter dialogue
    "base.how_respond": "  How do you respond?",
    "base.your_response": "Your response: ",
    "base.you_paid_gold": "  (You paid {0} gold)",
    "base.plus_chivalry": "  (+{0} Chivalry)",
    "base.plus_darkness": "  (+{0} Darkness)",
    "base.reward_chivalry": "  +{0} Chivalry!",
    "base.reward_wisdom": "  +{0} Wisdom!",
    "base.reward_dexterity": "  +{0} Dexterity!",
    "base.fragment_truth": "  (A fragment of truth settles into your consciousness...)",
    "base.something_shifts": "  (Something shifts in your understanding...)",
    "base.deeper_understanding": "  (A deeper understanding settles within you...)",
    "base.minus_gold": "  (-{0} gold)",

    # NPC friendly approach
    "base.npc_approaches": "{0} approaches you.",
    "base.npc_gift_dialogue": "\"I never thanked you properly. Take this - it's not much, but...\"",
    "base.received_gold": "  (Received {0} gold)",
    "base.npc_catches_eye": "{0} catches your eye and walks over.",
    "base.tip_weapons": "\"I heard there are powerful weapons hidden on the deeper dungeon floors. Be careful down there.\"",
    "base.tip_healer": "\"A word of advice - the healer offers better prices if you buy in bulk.\"",
    "base.tip_training": "\"I've been training at the gym lately. You should try it - the results are worth it.\"",
    "base.tip_temple": "\"The temple priests have been acting strange lately. Something is troubling them.\"",
    "base.tip_marketplace": "\"Keep an eye on the marketplace. Rare goods come through every now and then.\"",
    "base.npc_smiles": "{0} smiles as you pass by.",
    "base.compliment1": "\"Good to see you, friend. This town's a better place with you in it.\"",
    "base.compliment2": "\"I've heard stories about your adventures. Impressive stuff.\"",
    "base.compliment3": "\"You know, people around here look up to you. Keep it up.\"",
    "base.compliment4": "\"I was just telling someone about you the other day. All good things, of course.\"",
    "base.npc_presses": "{0} presses something into your hand.",
    "base.npc_heal_dialogue": "\"You look like you could use this. Stay safe out there.\"",
    "base.restored_hp": "  (Restored {0} HP)",
    "base.already_healthy": "  (You're already in good health.)",

    # NPC hostile approach
    "base.npc_blocks_path": "{0} blocks your path.",
    "base.threat1": "\"I know what you did. Stay away from me and mine, or next time we won't be talking.\"",
    "base.threat2": "\"You've got a lot of nerve showing your face around here.\"",
    "base.threat3": "\"Watch your back. Not everyone around here is as forgiving as I am.\"",
    "base.npc_catches_arm": "{0} catches your arm as you pass.",
    "base.warning_talking": "\"People are talking about you. And not in a good way. You might want to lay low.\"",
    "base.npc_stares_down": "{0} stares you down from across the room.",
    "base.hand_on_pommel": "Their hand rests pointedly on the pommel of their weapon.",
    "base.not_welcome": "The message is clear: you're not welcome here.",

    # Mail system
    "base.mail_unread": "Unread: {0}",
    "base.mailbox_empty": "Your mailbox is empty.",
    "base.mail_delete_menu": "]elete #  [",
    "base.mail_next_menu": "]ext Page  [",
    "base.mail_prev_menu": "]rev Page  [",
    "base.mail_deleted": "Message deleted.",
    "base.mail_message_from": "MESSAGE FROM {0}",
    "base.mail_message_from_box": "\u2550\u2550\u2550 MESSAGE FROM {0} \u2550\u2550\u2550",
    "base.mail_date": "Date: {0}",
    "base.mail_type": "Type: {0}",
    "base.mail_daily_limit": "You've reached the daily mail limit (20 messages).",
    "base.mail_send_to": "Send to: ",
    "base.mail_player_not_found": "Player '{0}' not found.",
    "base.mail_message_prompt": "Message (max 200 chars):",
    "base.mail_sent": "Message sent to {0}!",

    # Trade/package system
    "base.trade_incoming": "Incoming ({0} pending):",
    "base.trade_no_pending": "  No pending packages.",
    "base.trade_sent": "Sent ({0} pending):",
    "base.trade_no_outgoing": "  No outgoing packages.",
    "base.trade_commands": "  Commands:  Type a letter + number together, e.g. A1, D2, C3",
    "base.trade_accept": "] Accept package    ",
    "base.trade_decline": "] Decline package",
    "base.trade_send_new": "]  Send new package  ",
    "base.trade_cancel_sent": "] Cancel sent package",
    "base.trade_quit": "]  Quit",
    "base.trade_example": "  Example: Type A1 to accept package #1, D1 to decline it",
    "base.trade_received_gold": "Received {0} gold!",
    "base.trade_accepted": "Package accepted!",
    "base.trade_declined": "Package declined. Items/gold returned to sender.",
    "base.trade_cancelled": "Package cancelled. Gold returned.",
    "base.trade_too_many": "You have too many pending outgoing packages (max 10).",
    "base.trade_send_to": "Send to: ",
    "base.trade_player_not_found": "Player '{0}' not found.",
    "base.trade_no_self": "You can't send packages to yourself!",
    "base.trade_select_items": "Select items to send (up to 5). Enter 0 when done.",
    "base.trade_your_inventory": "Your inventory:",
    "base.trade_add_item": "Add item # (0 to stop): ",
    "base.trade_added": "Added {0}",
    "base.trade_gold_prompt": "Gold to send (you have {0}): ",
    "base.trade_empty": "Package is empty - nothing to send.",
    "base.trade_note": "Add a note (optional): ",

    # Bounty board
    "base.bounty_empty": "  The bounty board is empty. No active bounties.",
    "base.bounty_place_menu": "] Place Bounty    [",
    "base.bounty_my_menu": "] My Bounties    [",
    "base.bounty_back_menu": "] Back",
    "base.bounty_choice": "\n  Choice: ",
    "base.bounty_max": "\n  You already have 3 active bounties. Wait for them to be claimed.",
    "base.bounty_target_prompt": "\n  Target player name: ",
    "base.bounty_no_self": "  You can't place a bounty on yourself!",
    "base.bounty_not_found": "  Player not found.",
    "base.bounty_not_enough": "  You don't have enough gold!",
    "base.bounty_placed_header": "\n  === Bounties You Placed ===",
    "base.bounty_none": "  None.",
    "base.bounty_on_you_header": "\n  === Bounties On You ===",
    "base.bounty_clean": "  None. You're clean!",

    # Auction house
    "base.auction_hall_desc": "A cavernous hall of polished stone, lined with glass display cases and ",
    "base.auction_hall_desc2": "wooden",
    "base.auction_hall_desc3": "stalls. ",
    "base.auction_busy": "The air buzzes with haggling voices and the clink of coin purses.",
    "base.auction_moderate": "A few merchants stand behind their stalls, calling to passersby.",
    "base.auction_quiet": "The stalls stand mostly empty today, dust settling on the counters.",
    "base.auction_grimjaw": "Grimjaw",
    "base.auction_grimjaw_desc": ", the half-orc auctioneer, looms behind the registry desk. ",
    "base.auction_yawns": "He yawns.",
    "base.auction_listings": "  Listings: ",
    "base.auction_total_value": "   Total value: ",
    "base.auction_people": "  People here: ",
    "base.auction_what_do": "What would you like to do?",
    "base.auction_browse": "rowse Listings        ",
    "base.auction_sell": "ell Item       ",
    "base.auction_my_listings": "y Listings",
    "base.auction_return": "eturn to Town         ",
    "base.auction_cancel_btn": "] Cancel",
    "base.auction_no_items": "\n  No items for sale. Check back later!",
    "base.auction_listings_header": "\nAUCTION LISTINGS",
    "base.auction_listings_header_box": "\n  \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 AUCTION LISTINGS \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550",
    "base.auction_inspect": "\n  Enter # to inspect/buy, or press Enter to go back.",
    "base.auction_choice": "  Choice: ",
    "base.auction_item_header": "\nITEM DETAILS",
    "base.auction_item_header_box": "\n  \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 ITEM DETAILS \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550",
    "base.auction_no_stats": "  No stat bonuses",
    "base.auction_req_good": "  Requires Good alignment",
    "base.auction_req_evil": "  Requires Evil alignment",
    "base.auction_cursed": "  CURSED",
    "base.auction_unavailable": "  (Item details unavailable)",
    "base.auction_your_listing": "\n  This is your listing.",
    "base.auction_press_enter": "  Press Enter to go back.",
    "base.auction_already_sold": "  That item was already sold or expired!",
    "base.auction_no_items_sell": "\n  You have no items to sell!",
    "base.auction_max_listings": "\n  You already have 5 active listings. Cancel or wait for them to expire.",
    "base.auction_inv_header": "\nYOUR INVENTORY",
    "base.auction_inv_header_box": "\n  \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 YOUR INVENTORY \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550",
    "base.auction_item_num": "\n  Item # to sell: ",
    "base.auction_asking_price": "  Asking price (gold): ",
    "base.auction_invalid_price": "  Invalid price.",
    "base.auction_duration": "\n  Select listing duration:",
    "base.auction_duration_prompt": "\n  Duration (1-4): ",
    "base.auction_failed": "\n  Failed to create listing.",
    "base.auction_my_header": "\nMY LISTINGS",
    "base.auction_my_header_box": "\n  \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 MY LISTINGS \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550",
    "base.auction_no_listings": "  You have no listings.",
    "base.auction_collect_gold": "] Collect all gold    ",
    "base.auction_collect_expired": "] Collect expired items    ",
    "base.auction_cancel_collect": "] Cancel/collect listing    [Enter] Back",
    "base.auction_my_choice": "\n  Choice: ",
    "base.auction_no_gold": "\n  No gold to collect.",
    "base.auction_no_expired": "\n  No expired items to collect.",
    "base.auction_collect_failed": "  Failed to collect item.",
    "base.auction_only_active": "  Can only cancel active listings.",
    "base.auction_listing_cancelled": "  Listing cancelled. Item returned to inventory.",

    # Gear display
    "base.using_2h_weapon": "(using 2H weapon)",
    "base.totals_equipped": "  Totals ({0} items equipped):",

    # NPC personality (debug/inspect - keeping short)
    "base.no_personality": "  No personality profile found!",
    "base.identity_header": "  === IDENTITY ===",
    "base.faction_header": "  === FACTION ===",
    "base.faction_label": "  Faction:            ",
    "base.none_independent": "None (Independent)",
    "base.relationship_header": "  === RELATIONSHIP STYLE ===",
    "base.romance_header": "  === ROMANCE TRAITS (0.0-1.0) ===",
    "base.polyamory_header": "  === POLYAMORY ASSESSMENT ===",
    "base.open_polyamory": "  Open to polyamory: ",
    "base.very_likely": "VERY LIKELY",
    "base.possible": "POSSIBLE",
    "base.unlikely": "UNLIKELY",
    "base.polyamory_factors": "  Key factors: OpenRelationship/Polyamorous preference + Low Jealousy",
}

new_es = {
    "base.how_respond": "  \u00bfC\u00f3mo respondes?",
    "base.your_response": "Tu respuesta: ",
    "base.you_paid_gold": "  (Pagaste {0} oro)",
    "base.plus_chivalry": "  (+{0} Caballer\u00eda)",
    "base.plus_darkness": "  (+{0} Oscuridad)",
    "base.reward_chivalry": "  +{0} Caballer\u00eda!",
    "base.reward_wisdom": "  +{0} Sabidur\u00eda!",
    "base.reward_dexterity": "  +{0} Destreza!",
    "base.fragment_truth": "  (Un fragmento de verdad se asienta en tu conciencia...)",
    "base.something_shifts": "  (Algo cambia en tu comprensi\u00f3n...)",
    "base.deeper_understanding": "  (Una comprensi\u00f3n m\u00e1s profunda se asienta en ti...)",
    "base.minus_gold": "  (-{0} oro)",

    "base.npc_approaches": "{0} se te acerca.",
    "base.npc_gift_dialogue": "\"Nunca te agradec\u00ed como deb\u00eda. Toma esto, no es mucho, pero...\"",
    "base.received_gold": "  (Recibiste {0} oro)",
    "base.npc_catches_eye": "{0} te mira y camina hacia ti.",
    "base.tip_weapons": "\"Escuch\u00e9 que hay armas poderosas en los pisos m\u00e1s profundos. Ten cuidado all\u00ed abajo.\"",
    "base.tip_healer": "\"Un consejo - el curador ofrece mejores precios si compras en cantidad.\"",
    "base.tip_training": "\"He estado entrenando \u00faltimamente. Deber\u00edas intentarlo - vale la pena.\"",
    "base.tip_temple": "\"Los sacerdotes del templo han estado actuando extra\u00f1o. Algo les preocupa.\"",
    "base.tip_marketplace": "\"Vigila el mercado. De vez en cuando llegan art\u00edculos raros.\"",
    "base.npc_smiles": "{0} sonr\u00ede al pasar.",
    "base.compliment1": "\"Qu\u00e9 bueno verte, amigo. Este pueblo es mejor contigo.\"",
    "base.compliment2": "\"He o\u00eddo historias de tus aventuras. Impresionante.\"",
    "base.compliment3": "\"Sabes, la gente aqu\u00ed te admira. Sigue as\u00ed.\"",
    "base.compliment4": "\"Le contaba a alguien sobre ti el otro d\u00eda. Solo cosas buenas, claro.\"",
    "base.npc_presses": "{0} te pone algo en la mano.",
    "base.npc_heal_dialogue": "\"Parece que necesitas esto. Cu\u00eddate all\u00e1 afuera.\"",
    "base.restored_hp": "  (Restaurados {0} PV)",
    "base.already_healthy": "  (Ya est\u00e1s en buena salud.)",

    "base.npc_blocks_path": "{0} te bloquea el paso.",
    "base.threat1": "\"S\u00e9 lo que hiciste. Al\u00e9jate de los m\u00edos, o la pr\u00f3xima vez no hablaremos.\"",
    "base.threat2": "\"Tienes mucho descaro mostrando la cara por aqu\u00ed.\"",
    "base.threat3": "\"Cuida tu espalda. No todos aqu\u00ed son tan indulgentes como yo.\"",
    "base.npc_catches_arm": "{0} te agarra el brazo al pasar.",
    "base.warning_talking": "\"La gente habla de ti. Y no cosas buenas. Quiz\u00e1s deber\u00edas mantener perfil bajo.\"",
    "base.npc_stares_down": "{0} te mira fijamente desde el otro lado de la habitaci\u00f3n.",
    "base.hand_on_pommel": "Su mano descansa sobre el pomo de su arma.",
    "base.not_welcome": "El mensaje es claro: no eres bienvenido aqu\u00ed.",

    "base.mail_unread": "Sin leer: {0}",
    "base.mailbox_empty": "Tu buz\u00f3n est\u00e1 vac\u00edo.",
    "base.mail_delete_menu": "]liminar #  [",
    "base.mail_next_menu": "]ig P\u00e1gina  [",
    "base.mail_prev_menu": "]nt P\u00e1gina  [",
    "base.mail_deleted": "Mensaje eliminado.",
    "base.mail_message_from": "MENSAJE DE {0}",
    "base.mail_message_from_box": "\u2550\u2550\u2550 MENSAJE DE {0} \u2550\u2550\u2550",
    "base.mail_date": "Fecha: {0}",
    "base.mail_type": "Tipo: {0}",
    "base.mail_daily_limit": "Has alcanzado el l\u00edmite diario de correo (20 mensajes).",
    "base.mail_send_to": "Enviar a: ",
    "base.mail_player_not_found": "Jugador '{0}' no encontrado.",
    "base.mail_message_prompt": "Mensaje (m\u00e1x 200 caracteres):",
    "base.mail_sent": "\u00a1Mensaje enviado a {0}!",

    "base.trade_incoming": "Entrantes ({0} pendientes):",
    "base.trade_no_pending": "  No hay paquetes pendientes.",
    "base.trade_sent": "Enviados ({0} pendientes):",
    "base.trade_no_outgoing": "  No hay paquetes salientes.",
    "base.trade_commands": "  Comandos: Escribe una letra + n\u00famero, ej. A1, D2, C3",
    "base.trade_accept": "] Aceptar paquete    ",
    "base.trade_decline": "] Rechazar paquete",
    "base.trade_send_new": "]  Enviar nuevo paquete  ",
    "base.trade_cancel_sent": "] Cancelar paquete enviado",
    "base.trade_quit": "]  Salir",
    "base.trade_example": "  Ejemplo: Escribe A1 para aceptar el paquete #1, D1 para rechazarlo",
    "base.trade_received_gold": "\u00a1Recibiste {0} oro!",
    "base.trade_accepted": "\u00a1Paquete aceptado!",
    "base.trade_declined": "Paquete rechazado. Art\u00edculos/oro devueltos al remitente.",
    "base.trade_cancelled": "Paquete cancelado. Oro devuelto.",
    "base.trade_too_many": "Tienes demasiados paquetes pendientes (m\u00e1x 10).",
    "base.trade_send_to": "Enviar a: ",
    "base.trade_player_not_found": "Jugador '{0}' no encontrado.",
    "base.trade_no_self": "\u00a1No puedes enviarte paquetes a ti mismo!",
    "base.trade_select_items": "Selecciona art\u00edculos para enviar (hasta 5). Ingresa 0 cuando termines.",
    "base.trade_your_inventory": "Tu inventario:",
    "base.trade_add_item": "Agregar art\u00edculo # (0 para parar): ",
    "base.trade_added": "Agregado {0}",
    "base.trade_gold_prompt": "Oro a enviar (tienes {0}): ",
    "base.trade_empty": "El paquete est\u00e1 vac\u00edo - nada para enviar.",
    "base.trade_note": "Agregar una nota (opcional): ",

    "base.bounty_empty": "  El tabl\u00f3n de recompensas est\u00e1 vac\u00edo. No hay recompensas activas.",
    "base.bounty_place_menu": "] Poner Recompensa    [",
    "base.bounty_my_menu": "] Mis Recompensas    [",
    "base.bounty_back_menu": "] Volver",
    "base.bounty_choice": "\n  Elecci\u00f3n: ",
    "base.bounty_max": "\n  Ya tienes 3 recompensas activas. Espera a que sean reclamadas.",
    "base.bounty_target_prompt": "\n  Nombre del jugador objetivo: ",
    "base.bounty_no_self": "  \u00a1No puedes poner una recompensa sobre ti mismo!",
    "base.bounty_not_found": "  Jugador no encontrado.",
    "base.bounty_not_enough": "  \u00a1No tienes suficiente oro!",
    "base.bounty_placed_header": "\n  === Recompensas que Pusiste ===",
    "base.bounty_none": "  Ninguna.",
    "base.bounty_on_you_header": "\n  === Recompensas Sobre Ti ===",
    "base.bounty_clean": "  Ninguna. \u00a1Est\u00e1s limpio!",

    "base.auction_hall_desc": "Un sal\u00f3n cavernoso de piedra pulida, con vitrinas y ",
    "base.auction_hall_desc2": "puestos",
    "base.auction_hall_desc3": "de madera. ",
    "base.auction_busy": "El aire vibra con voces de regateo y el tintineo de monedas.",
    "base.auction_moderate": "Algunos mercaderes est\u00e1n detr\u00e1s de sus puestos, llamando a los transeuntes.",
    "base.auction_quiet": "Los puestos est\u00e1n casi vac\u00edos hoy, el polvo se asienta en los mostradores.",
    "base.auction_grimjaw": "Grimjaw",
    "base.auction_grimjaw_desc": ", el subastador semiorco, se alza detr\u00e1s del escritorio. ",
    "base.auction_yawns": "Bosteza.",
    "base.auction_listings": "  Listados: ",
    "base.auction_total_value": "   Valor total: ",
    "base.auction_people": "  Gente aqu\u00ed: ",
    "base.auction_what_do": "\u00bfQu\u00e9 te gustar\u00eda hacer?",
    "base.auction_browse": "er Listados        ",
    "base.auction_sell": "ender Art\u00edculo       ",
    "base.auction_my_listings": "is Listados",
    "base.auction_return": "olver al Pueblo         ",
    "base.auction_cancel_btn": "] Cancelar",
    "base.auction_no_items": "\n  No hay art\u00edculos en venta. \u00a1Vuelve m\u00e1s tarde!",
    "base.auction_listings_header": "\nLISTADOS DE SUBASTA",
    "base.auction_listings_header_box": "\n  \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 LISTADOS DE SUBASTA \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550",
    "base.auction_inspect": "\n  Ingresa # para inspeccionar/comprar, o Enter para volver.",
    "base.auction_choice": "  Elecci\u00f3n: ",
    "base.auction_item_header": "\nDETALLES DEL ART\u00cdCULO",
    "base.auction_item_header_box": "\n  \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 DETALLES DEL ART\u00cdCULO \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550",
    "base.auction_no_stats": "  Sin bonificaciones de estad\u00edsticas",
    "base.auction_req_good": "  Requiere alineaci\u00f3n Buena",
    "base.auction_req_evil": "  Requiere alineaci\u00f3n Malvada",
    "base.auction_cursed": "  MALDITO",
    "base.auction_unavailable": "  (Detalles no disponibles)",
    "base.auction_your_listing": "\n  Este es tu listado.",
    "base.auction_press_enter": "  Presiona Enter para volver.",
    "base.auction_already_sold": "  \u00a1Ese art\u00edculo ya fue vendido o expir\u00f3!",
    "base.auction_no_items_sell": "\n  \u00a1No tienes art\u00edculos para vender!",
    "base.auction_max_listings": "\n  Ya tienes 5 listados activos. Cancela o espera a que expiren.",
    "base.auction_inv_header": "\nTU INVENTARIO",
    "base.auction_inv_header_box": "\n  \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 TU INVENTARIO \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550",
    "base.auction_item_num": "\n  Art\u00edculo # para vender: ",
    "base.auction_asking_price": "  Precio pedido (oro): ",
    "base.auction_invalid_price": "  Precio inv\u00e1lido.",
    "base.auction_duration": "\n  Selecciona duraci\u00f3n del listado:",
    "base.auction_duration_prompt": "\n  Duraci\u00f3n (1-4): ",
    "base.auction_failed": "\n  Error al crear el listado.",
    "base.auction_my_header": "\nMIS LISTADOS",
    "base.auction_my_header_box": "\n  \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 MIS LISTADOS \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550",
    "base.auction_no_listings": "  No tienes listados.",
    "base.auction_collect_gold": "] Cobrar todo el oro    ",
    "base.auction_collect_expired": "] Recoger art\u00edculos expirados    ",
    "base.auction_cancel_collect": "] Cancelar/recoger listado    [Enter] Volver",
    "base.auction_my_choice": "\n  Elecci\u00f3n: ",
    "base.auction_no_gold": "\n  No hay oro para cobrar.",
    "base.auction_no_expired": "\n  No hay art\u00edculos expirados para recoger.",
    "base.auction_collect_failed": "  Error al recoger art\u00edculo.",
    "base.auction_only_active": "  Solo se pueden cancelar listados activos.",
    "base.auction_listing_cancelled": "  Listado cancelado. Art\u00edculo devuelto al inventario.",

    "base.using_2h_weapon": "(usando arma 2M)",
    "base.totals_equipped": "  Totales ({0} art\u00edculos equipados):",

    "base.no_personality": "  \u00a1No se encontr\u00f3 perfil de personalidad!",
    "base.identity_header": "  === IDENTIDAD ===",
    "base.faction_header": "  === FACCI\u00d3N ===",
    "base.faction_label": "  Facci\u00f3n:            ",
    "base.none_independent": "Ninguna (Independiente)",
    "base.relationship_header": "  === ESTILO DE RELACI\u00d3N ===",
    "base.romance_header": "  === RASGOS ROM\u00c1NTICOS (0.0-1.0) ===",
    "base.polyamory_header": "  === EVALUACI\u00d3N DE POLIAMOR ===",
    "base.open_polyamory": "  Abierto al poliamor: ",
    "base.very_likely": "MUY PROBABLE",
    "base.possible": "POSIBLE",
    "base.unlikely": "IMPROBABLE",
    "base.polyamory_factors": "  Factores clave: Preferencia Relaci\u00f3n Abierta/Poli\u00e1moro + Baja Celos\u00eda",
}

for k, v in new_en.items():
    en[k] = v
for k, v in new_es.items():
    es[k] = v

with open('Localization/en.json', 'w', encoding='utf-8') as f:
    json.dump(en, f, ensure_ascii=False, indent=2)
with open('Localization/es.json', 'w', encoding='utf-8') as f:
    json.dump(es, f, ensure_ascii=False, indent=2)

print(f"Added {len(new_en)} en keys, {len(new_es)} es keys. en: {len(en)}, es: {len(es)}")
