"""Remove orphaned street_encounter keys from JSON files (keys in JSON not used in code)."""
import json

orphaned_to_remove = [
    'street_encounter.bribe.accepted',
    'street_encounter.bribe.cant_afford',
    'street_encounter.bribe.opt_large',
    'street_encounter.bribe.opt_nevermind',
    'street_encounter.bribe.opt_small',
    'street_encounter.bribe.rejected',
    'street_encounter.challenge.accept_intro',
    'street_encounter.challenge.decline',
    'street_encounter.challenge.lose',
    'street_encounter.challenge.negotiate_fail',
    'street_encounter.challenge.negotiate_success',
    'street_encounter.challenge.opt_negotiate',
    'street_encounter.challenge.win',
    'street_encounter.challenge.win_reputation',
    'street_encounter.flee.fail',
    'street_encounter.flee.success',
    'street_encounter.gang.opt_pay',
    'street_encounter.gang.opt_sneak',
    'street_encounter.gang.opt_solo_fight',
    'street_encounter.gang.opt_team_fight',
    'street_encounter.gang.opt_team_negotiate',
    'street_encounter.gang.opt_team_pay',
    'street_encounter.gang.pay_toll',
    'street_encounter.gang.sneak_fail',
    'street_encounter.gang.sneak_success',
    'street_encounter.gang.solo_fight_lose',
    'street_encounter.gang.solo_fight_win',
    'street_encounter.gang.team_fight_lose',
    'street_encounter.gang.team_fight_win',
    'street_encounter.gang.team_leader_speaks',
    'street_encounter.gang.team_negotiate_fail',
    'street_encounter.gang.team_negotiate_success',
    'street_encounter.gang.team_pay',
    'street_encounter.grudge.apologize_fail',
    'street_encounter.grudge.apologize_success',
    'street_encounter.grudge.bribe_cant_afford',
    'street_encounter.grudge.bribe_fail',
    'street_encounter.grudge.bribe_success',
    'street_encounter.grudge.deny_fail',
    'street_encounter.grudge.deny_success',
    'street_encounter.grudge.guard_intervention',
    'street_encounter.grudge.murder_revenge_quote',
    'street_encounter.grudge.murder_revenge_stats',
    'street_encounter.grudge.opt_bribe',
    'street_encounter.grudge.opt_deny',
    'street_encounter.grudge.run_fail',
    'street_encounter.grudge.run_success',
    'street_encounter.grudge.standard_confronts',
    'street_encounter.grudge.standard_grievance',
    'street_encounter.grudge.standard_stats',
    'street_encounter.grudge.witness_revenge_title',
    'street_encounter.grudge.witness_saw_kill',
    'street_encounter.grudge.witness_stats',
    'street_encounter.guard.bribe_fail',
    'street_encounter.guard.bribe_success',
    'street_encounter.guard.crown_pass',
    'street_encounter.guard.fight_lose',
    'street_encounter.guard.fight_win',
    'street_encounter.guard.not_wanted_greet',
    'street_encounter.guard.not_wanted_tip',
    'street_encounter.guard.opt_fight',
    'street_encounter.guard.opt_run',
    'street_encounter.guard.run_fail',
    'street_encounter.guard.run_success',
    'street_encounter.guard.stop_wanted',
    'street_encounter.guard.surrender',
    'street_encounter.hostile.armor',
    'street_encounter.hostile.hp',
    'street_encounter.hostile.level',
    'street_encounter.hostile.opt_flee',
    'street_encounter.hostile.weapon',
    'street_encounter.merchant.bought',
    'street_encounter.merchant.decline',
    'street_encounter.merchant.haggle_fail',
    'street_encounter.merchant.haggle_success',
    'street_encounter.merchant.item_offer',
    'street_encounter.merchant.normal_approach',
    'street_encounter.merchant.normal_offer',
    'street_encounter.merchant.opt_buy',
    'street_encounter.merchant.opt_decline',
    'street_encounter.merchant.opt_haggle',
    'street_encounter.merchant.shady_approach',
    'street_encounter.merchant.shady_offer',
    'street_encounter.mugging.demand',
    'street_encounter.mugging.fight_lose',
    'street_encounter.mugging.fight_win',
    'street_encounter.mugging.opt_fight',
    'street_encounter.mugging.run_fail',
    'street_encounter.mugging.run_success',
    'street_encounter.mugging.surrender',
    'street_encounter.murder.assassin_first_strike',
    'street_encounter.murder.blood_price',
    'street_encounter.murder.first_strike',
    'street_encounter.murder.shadow_approved',
    'street_encounter.pickpocket.grab_fail',
    'street_encounter.pickpocket.grab_success',
    'street_encounter.pickpocket.ignore_loss',
    'street_encounter.pickpocket.ignore_nothing',
    'street_encounter.pickpocket.shout_flee',
    'street_encounter.pickpocket.shout_guard',
    'street_encounter.romance.admirer_female_1',
    'street_encounter.romance.admirer_female_2',
    'street_encounter.romance.admirer_female_3',
    'street_encounter.romance.admirer_female_4',
    'street_encounter.romance.admirer_male_1',
    'street_encounter.romance.admirer_male_2',
    'street_encounter.romance.admirer_male_3',
    'street_encounter.romance.admirer_male_4',
    'street_encounter.romance.flattery',
    'street_encounter.romance.flirt_gift',
    'street_encounter.romance.flirt_success',
    'street_encounter.romance.ignore',
    'street_encounter.romance.opt_ignore',
    'street_encounter.romance.opt_polite',
    'street_encounter.romance.polite_decline',
    'street_encounter.rumor.1',
    'street_encounter.rumor.10',
    'street_encounter.rumor.2',
    'street_encounter.rumor.3',
    'street_encounter.rumor.4',
    'street_encounter.rumor.5',
    'street_encounter.rumor.6',
    'street_encounter.rumor.7',
    'street_encounter.rumor.8',
    'street_encounter.rumor.9',
    'street_encounter.rumor.npc_seen',
    'street_encounter.rumor.npc_trouble',
    'street_encounter.spouse.accusation',
    'street_encounter.spouse.admit_forgive',
    'street_encounter.spouse.admit_rage',
    'street_encounter.spouse.confronts',
    'street_encounter.spouse.deny_fail',
    'street_encounter.spouse.deny_success',
    'street_encounter.spouse.opt_fight',
    'street_encounter.spouse.self_preservation',
    'street_encounter.spouse.taunt_rage',
    'street_encounter.talk.fail',
    'street_encounter.talk.success',
    'street_encounter.throne.accept',
    'street_encounter.throne.challenges',
    'street_encounter.throne.declare',
    'street_encounter.throne.dismiss_fail',
    'street_encounter.throne.dismiss_success',
    'street_encounter.throne.imprison_fail',
    'street_encounter.throne.imprison_success',
    'street_encounter.throne.negotiate_fail',
    'street_encounter.throne.negotiate_success',
    'street_encounter.turf.confronts',
    'street_encounter.turf.declare',
    'street_encounter.turf.fight_lose',
    'street_encounter.turf.fight_win',
    'street_encounter.turf.opt_run',
    'street_encounter.turf.pay',
    'street_encounter.turf.pay_cant_afford',
    'street_encounter.turf.run_fail',
    'street_encounter.turf.run_success',
    # Old brawl keys replaced by correct ones
    'street_encounter.brawl.reason_tavern',
    'street_encounter.brawl.reason_bump',
    'street_encounter.brawl.reason_mistake',
    'street_encounter.brawl.reason_bored',
    'street_encounter.brawl.reason_spill',
    'street_encounter.brawl.opt_walk_away',
    'street_encounter.brawl.opt_intimidate',
    'street_encounter.brawl.fight_win',
    'street_encounter.brawl.fight_lose',
    'street_encounter.brawl.walk_success',
    'street_encounter.brawl.walk_fail',
    'street_encounter.brawl.intimidate_success',
    'street_encounter.brawl.intimidate_fail',
    # Old beggar keys
    'street_encounter.beggar.give_info',
    'street_encounter.beggar.give_thanks',
    'street_encounter.beggar.ignore',
    'street_encounter.beggar.opt_ignore',
    'street_encounter.beggar.pleads',
    'street_encounter.beggar.rob_fail',
    'street_encounter.beggar.rob_fight',
    'street_encounter.beggar.rob_success',
]

for lang in ['en', 'es']:
    path = f'Localization/{lang}.json'
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    removed = 0
    for key in orphaned_to_remove:
        if key in data:
            del data[key]
            removed += 1

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"{lang}.json: removed {removed} orphaned keys")
