"""
Add missing street_encounter keys to en.json and es.json.
These keys are used in StreetEncounterSystem.cs but were not in the extraction.
"""
import json

# Missing keys with English values
missing_en = {
    # Hostile - missing keys
    "street_encounter.hostile.opt_run": "un",
    "street_encounter.hostile.stats": "  {0} - Level {1} {2} (HP: {3}/{4})",

    # Pickpocket - missing keys
    "street_encounter.pickpocket.grab_thief": "  You grab the thief — it's {0}!",
    "street_encounter.pickpocket.shout_guards": "  You shout for the guards!",
    "street_encounter.pickpocket.thief_flees": "  The thief flees into the crowd!",
    "street_encounter.pickpocket.msg_scared_away": "Scared away a pickpocket.",
    "street_encounter.pickpocket.pretend_not_notice": "  You pretend not to notice and move on.",
    "street_encounter.pickpocket.msg_avoided": "Avoided a pickpocket encounter.",
    "street_encounter.pickpocket.bumps_into": "  Someone bumps into you in the crowd...",
    "street_encounter.pickpocket.gold_missing": "  You notice {0} gold is missing!",
    "street_encounter.pickpocket.msg_stolen": "A pickpocket stole {0} gold!",
    "street_encounter.pickpocket.nothing_to_steal": "  Someone bumps into you but finds nothing worth stealing.",
    "street_encounter.pickpocket.msg_found_nothing": "A pickpocket tried but found nothing.",

    # Brawl - missing keys (reason keys and opt keys already fixed separately)
    "street_encounter.brawl.squares_up": "  {0} squares up against you!",
    "street_encounter.brawl.duck_escape": "  You duck under a flying chair and slip out the back!",
    "street_encounter.brawl.msg_escaped": "Escaped the tavern brawl unscathed.",
    "street_encounter.brawl.hit_by_mug": "  You try to dodge but a flying mug hits you in the head!",
    "street_encounter.brawl.msg_hit_escaping": "Hit by a mug while escaping the brawl.",
    "street_encounter.brawl.buy_round": "  You buy a round for the house!",
    "street_encounter.brawl.toast_health": "  Everyone toasts to your health! The tension fades.",
    "street_encounter.brawl.msg_bought_drinks": "Bought drinks to defuse a brawl.",
    "street_encounter.brawl.not_enough_gold": "  You don't have enough gold for that!",

    # Challenge - missing keys
    "street_encounter.challenge.accept_honor": "  You accept the challenge with honor!",
    "street_encounter.challenge.decline_reply": "  \"Not today,\" you reply.",
    "street_encounter.challenge.scoffs": "  {0} scoffs at your cowardice.",
    "street_encounter.challenge.msg_declined": "Declined a challenge. (-5 Fame)",
    "street_encounter.challenge.opt_insult": "nsult Them",
    "street_encounter.challenge.insult_honor": "  You insult their honor and their mother!",
    "street_encounter.challenge.pay_for_that": "  \"You'll pay for that!\" {0} roars!",

    # Mugging - missing keys
    "street_encounter.mugging.gold_or_life": "  \"Your gold or your life!\"",
    "street_encounter.mugging.draw_weapon": "  You draw your weapon!",
    "street_encounter.mugging.defeated_found_gold": "  You defeated the muggers and found {0} gold on them!",
    "street_encounter.mugging.msg_defeated": "Defeated {0} muggers!",
    "street_encounter.mugging.msg_lost": "Lost to the muggers...",
    "street_encounter.mugging.hand_over": "  You hand over {0} gold.",
    "street_encounter.mugging.thugs_disappear": "  The thugs disappear into the shadows.",
    "street_encounter.mugging.msg_surrendered": "Surrendered {0} gold to muggers.",
    "street_encounter.mugging.sprint_escape": "  You sprint away and lose them in the alleyways!",
    "street_encounter.mugging.msg_escaped": "Escaped from muggers!",
    "street_encounter.mugging.caught_beaten": "  They catch you and beat you down!",
    "street_encounter.mugging.damage_and_gold": "  You take {0} damage and they steal {1} gold!",
    "street_encounter.mugging.msg_caught": "Caught and beaten by muggers.",

    # Gang - missing keys
    "street_encounter.gang.heard_team": "  \"We've heard about your team, '{0}'.\"",
    "street_encounter.gang.our_territory": "  \"This is our territory. Back off.\"",
    "street_encounter.gang.opt_fight_territory": "ight for Territory",
    "street_encounter.gang.opt_negotiate": "egotiate",
    "street_encounter.gang.opt_leave": "eave Peacefully",
    "street_encounter.gang.need_friends": "  \"You look like you could use some friends.\"",
    "street_encounter.gang.opt_join": "oin Their Gang",
    "street_encounter.gang.opt_refuse": "efuse",
    "street_encounter.gang.wrong_answer": "  \"Wrong answer.\"",
    "street_encounter.gang.victory_spreads": "  Word of your victory over '{0}' spreads through the streets!",
    "street_encounter.gang.plus_fame": "  (+20 Fame)",
    "street_encounter.gang.looks_you_over": "  The gang leader looks you over...",
    "street_encounter.gang.welcome": "  \"Welcome to '{0}', friend.\"",
    "street_encounter.gang.msg_joined": "Joined the gang '{0}'!",
    "street_encounter.gang.too_weak": "  \"Come back when you're stronger, weakling.\"",
    "street_encounter.gang.msg_too_weak": "Too weak to join the gang.",
    "street_encounter.gang.not_recruiting_1": "  The gang leader shakes their head.",
    "street_encounter.gang.not_recruiting_2": "  \"We're not recruiting right now. Move along.\"",
    "street_encounter.gang.msg_not_recruiting": "The gang isn't recruiting.",
    "street_encounter.gang.let_you_pass": "  They grudgingly let you pass.",
    "street_encounter.gang.msg_avoided": "Avoided gang confrontation.",
    "street_encounter.gang.nobody_refuses": "  \"Nobody refuses us!\"",

    # Romance - missing keys
    "street_encounter.romance.buy_drink": "  \"May I buy you a drink?\"",
    "street_encounter.romance.opt_yes": "es, Please",
    "street_encounter.romance.opt_no": "o Thanks",
    "street_encounter.romance.pleasant_time": "  You spend a pleasant time together...",
    "street_encounter.romance.wonderful_conversation": "  A wonderful conversation! You feel more charming. (+1 Charisma)",
    "street_encounter.romance.msg_connection": "Made a genuine connection.",
    "street_encounter.romance.purse_lighter": "  ...but your purse feels lighter afterward.",
    "street_encounter.romance.stole_gold": "  They stole {0} gold from you!",
    "street_encounter.romance.msg_scam": "Romantic encounter was a scam!",
    "street_encounter.romance.token_affection": "  They leave you a small token of affection. (+5 Fame)",
    "street_encounter.romance.msg_fame": "Gained fame from a romantic encounter.",
    "street_encounter.romance.another_time": "  \"Perhaps another time,\" you say politely.",
    "street_encounter.romance.smile_walk_away": "  They smile and walk away.",
    "street_encounter.romance.msg_declined": "Politely declined a romantic encounter.",

    # Merchant - missing keys
    "street_encounter.merchant.cloaked_figure": "  A cloaked figure beckons you from the shadows.",
    "street_encounter.merchant.buy_special": "  \"Psst... want to buy something special?\"",
    "street_encounter.merchant.waves_over": "  A traveling merchant waves you over.",
    "street_encounter.merchant.fine_wares": "  \"Fine wares for the discerning adventurer!\"",
    "street_encounter.merchant.no_thanks": "No thanks",
    "street_encounter.merchant.buy_prompt": "Buy which item? ",
    "street_encounter.merchant.purchased": "  You purchased {0}!",
    "street_encounter.merchant.msg_bought": "Bought {0} from a traveling merchant.",
    "street_encounter.merchant.come_back": "  \"Come back anytime!\"",
    "street_encounter.merchant.msg_declined": "Browsed a merchant's wares.",

    # Beggar - missing keys
    "street_encounter.beggar.approaches": "  A ragged beggar approaches you.",
    "street_encounter.beggar.thanks": "  \"Bless you, kind soul!\" (+5 Chivalry)",
    "street_encounter.beggar.plus_chivalry": "  (+{0} Chivalry)",
    "street_encounter.beggar.msg_gave": "Gave gold to a beggar.",
    "street_encounter.beggar.bless_you": "  \"The gods bless you, generous one!\"",
    "street_encounter.beggar.strange_amulet": "  The beggar presses a strange amulet into your hand.",
    "street_encounter.beggar.luck_amulet": "  \"For luck,\" they whisper.",
    "street_encounter.beggar.msg_large_donation": "Made a large donation to a beggar.",
    "street_encounter.beggar.opt_large": "arge Donation (50)",
    "street_encounter.beggar.rob_possessions": "  You rifle through the beggar's meager possessions...",
    "street_encounter.beggar.rob_result": "  You found {0} gold. (+15 Darkness, -10 Chivalry)",
    "street_encounter.beggar.msg_robbed": "Robbed a beggar.",
    "street_encounter.beggar.walk_past": "  You walk past without a word.",
    "street_encounter.beggar.msg_ignored": "Ignored a beggar.",

    # Rumor - missing keys
    "street_encounter.rumor.dungeons_dangerous": "The dungeons have been more dangerous lately...",
    "street_encounter.rumor.king_adventurers": "The king is looking for brave adventurers.",
    "street_encounter.rumor.strange_creatures": "Strange creatures have been spotted near the outskirts.",
    "street_encounter.rumor.temple_blessings": "The temple is offering special blessings this week.",
    "street_encounter.rumor.fortune_hunting": "There's a fortune to be made hunting in the deep dungeon.",
    "street_encounter.rumor.guild_recruits": "The guild is actively looking for new recruits.",
    "street_encounter.rumor.watch_back": "Watch your back in the dark alleys at night.",
    "street_encounter.rumor.weapon_shipment": "A new weapon shipment arrived at the weapon shop.",
    "street_encounter.rumor.secret_passage": "They say there's a secret passage on the deeper floors.",
    "street_encounter.rumor.exotic_goods": "A merchant with exotic goods was seen near the marketplace.",
    "street_encounter.rumor.saw_npc": "I saw {0} heading toward the {1} earlier.",
    "street_encounter.rumor.npc_team": "I hear {0} has been looking for new allies.",
    "street_encounter.rumor.msg_heard": "Heard an interesting rumor.",

    # Guard - missing keys
    "street_encounter.guard.patrol_approaches": "  A patrol of town guards approaches.",
    "street_encounter.guard.crown_insignia": "  The guards notice your Crown faction insignia.",
    "street_encounter.guard.crown_business": "  \"Crown business, understood.\"",
    "street_encounter.guard.step_aside": "  They step aside and let you pass.",
    "street_encounter.guard.halt": "  \"Halt! You there!\"",
    "street_encounter.guard.looking_for_you": "  \"We've been looking for you. Darkness level: {0}\"",
    "street_encounter.guard.arrested": "  The guards arrest you!",
    "street_encounter.guard.confiscate": "  They confiscate {0} gold!",
    "street_encounter.guard.sentenced": "  You are sentenced to {0} days in prison.",
    "street_encounter.guard.msg_arrested": "Arrested by the town guard.",
    "street_encounter.guard.darkness_guards": "  Defeating town guards only increases your notoriety! (+30 Darkness)",
    "street_encounter.guard.overpowered": "  The guards overpower you!",
    "street_encounter.guard.sentenced_resisting": "  Sentenced to {0} days for resisting arrest with violence!",
    "street_encounter.guard.msg_defeated_arrested": "Defeated by guards and arrested.",
    "street_encounter.guard.bribed": "  The guard captain quietly pockets the gold. \"Move along.\"",
    "street_encounter.guard.msg_bribed": "Bribed the guards.",
    "street_encounter.guard.escape_crowd": "  You disappear into the crowd!",
    "street_encounter.guard.catch_you": "  The guards catch up to you!",
    "street_encounter.guard.running_extra": "  \"Running from the law, eh? That's an extra day!\"",
    "street_encounter.guard.sentenced_days": "  Sentenced to {0} days in prison!",
    "street_encounter.guard.msg_caught": "Caught fleeing from guards.",
    "street_encounter.guard.stay_out_trouble": "  \"Stay out of trouble, citizen.\"",
    "street_encounter.guard.continue_patrol": "  The guards continue their patrol.",
    "street_encounter.guard.msg_questioned": "Questioned by a guard patrol.",

    # Ambush - missing keys
    "street_encounter.ambush.assassins_leap": "  Assassins leap from the shadows!",
    "street_encounter.ambush.paid_gold": "  \"Someone paid good gold to have you killed!\"",
    "street_encounter.ambush.find_note": "  You find a note on the assassin's body...",
    "street_encounter.ambush.contract": "  \"Contract: Eliminate {0}\"",
    "street_encounter.ambush.unreadable": "  The employer's name is unreadable.",

    # Flee - missing keys
    "street_encounter.flee.escape_success": "  You manage to escape!",
    "street_encounter.flee.msg_fled": "Fled from an encounter.",
    "street_encounter.flee.catches_you": "  {0} catches up to you!",
    "street_encounter.flee.attack_back_turned": "  They attack while your back is turned!",
    "street_encounter.flee.take_damage": "  You take {0} damage!",

    # Bribe - missing keys
    "street_encounter.bribe.npc_attacks": "  {0} attacks anyway!",
    "street_encounter.bribe.opt_yes": "es, Pay {0} Gold",
    "street_encounter.bribe.opt_no": "o, Fight Instead",
    "street_encounter.bribe.takes_gold_leaves": "  {0} takes the gold and leaves.",
    "street_encounter.bribe.msg_bribed": "Bribed {0} with {1} gold.",
    "street_encounter.bribe.takes_gold_attacks": "  {0} takes the gold... and attacks anyway!",

    # Talk - missing keys
    "street_encounter.talk.reconsiders": "  {0} reconsiders and backs down.",
    "street_encounter.talk.msg_talked_down": "Talked down a hostile encounter.",
    "street_encounter.talk.not_interested": "  {0} isn't interested in talking!",

    # Grudge - missing keys
    "street_encounter.grudge.steps_out": "  {0} steps out of the shadows ahead of you.",
    "street_encounter.grudge.hesitates": "  They hesitate, sizing you up...",
    "street_encounter.grudge.thinks_better": "  The Level {0} {1} thinks better of it.",
    "street_encounter.grudge.guard_rushes": "  A Crown guard rushes to your aid!",
    "street_encounter.grudge.guard_strikes": "  The guard strikes {0}, dealing {1} damage!",
    "street_encounter.grudge.wounded_standing": "  {0} is wounded but still standing. (HP: {1}/{2})",
    "street_encounter.grudge.emerges_fury": "{0} emerges from the crowd, fury burning in their eyes!",
    "street_encounter.grudge.murder_quote_1": "\"You killed me once. I crawled back from death itself.\"",
    "street_encounter.grudge.murder_quote_2": "\"Now it's YOUR turn to bleed!\"",
    "street_encounter.grudge.enraged_stats": "ENRAGED! Level {0} {1} (HP: {2}/{3})",
    "street_encounter.grudge.barely_escape": "  You barely escape {0}'s wrath!",
    "street_encounter.grudge.cuts_off_escape": "  {0} cuts off your escape!",
    "street_encounter.grudge.murder_goes_down": "  {0} goes down again!",
    "street_encounter.grudge.stands_over": "  {0} stands over you.",
    "street_encounter.grudge.now_even": "  \"Now we're even.\"",
    "street_encounter.grudge.take_gold": "  They take {0} gold from you.",
    "street_encounter.grudge.waiting_unhappy": "{0} has been waiting for you, and they're not happy.",
    "street_encounter.grudge.think_again": "\"Thought you could beat me and walk away? Think again.\"",
    "street_encounter.grudge.settles_that": "  That settles that! {0} won't bother you again.",
    "street_encounter.grudge.takes_gold_satisfied": "  {0} takes {1} gold and seems satisfied.",
    "street_encounter.grudge.lowers_fists": "  {0} lowers their fists.",
    "street_encounter.grudge.dont_cross": "  \"Don't cross me again.\"",
    "street_encounter.grudge.sorry_not_enough": "  \"Sorry isn't good enough!\"",
    "street_encounter.grudge.attacks_fury": "  {0} attacks in a fury!",
    "street_encounter.grudge.even_for_now": "  \"We're even. For now.\"",
    "street_encounter.grudge.pockets_gold": "  {0} pockets the {1} gold.",
    "street_encounter.grudge.takes_gold_attacks": "  {0} takes the gold... then attacks anyway!",
    "street_encounter.grudge.not_enough_attacks": "  You don't have enough gold! {0} attacks!",
    "street_encounter.grudge.slip_away": "  You manage to slip away from {0}.",
    "street_encounter.grudge.catches_first_strike": "  {0} catches you and gets the first strike!",

    # Witness - missing keys
    "street_encounter.witness.title": "Witness Confrontation!",
    "street_encounter.witness.steps_in_front": "{0} steps in front of you, blocking your path.",
    "street_encounter.witness.saw_victim": "\"I saw what you did to {0}. You're going to pay.\"",
    "street_encounter.witness.saw_murder": "\"I saw what you did. Murderer.\"",
    "street_encounter.witness.stats": "Level {0} {1} (HP: {2}/{3})",
    "street_encounter.witness.opt_bribe": "Bribe ({0}g)",
    "street_encounter.witness.one_less": "  One less witness. {0} won't talk again.",
    "street_encounter.witness.justice_served": "  {0} got their justice. They take {1} gold.",
    "street_encounter.witness.takes_bribe": "  {0} takes {1} gold and looks away.",
    "street_encounter.witness.didnt_see": "  \"I didn't see anything.\"",
    "street_encounter.witness.gold_buy_silence": "  \"Your gold can't buy my silence!\"",
    "street_encounter.witness.not_enough_attacks": "  You don't have enough gold! {0} attacks!",
    "street_encounter.witness.slip_away": "  You slip away before {0} can react.",
    "street_encounter.witness.catches_guilty": "  {0} catches the guilty! No escaping justice!",

    # Spouse - missing keys
    "street_encounter.spouse.storms_toward": "  {0} storms toward you with murder in their eyes.",
    "street_encounter.spouse.stops_short": "  They stop short, trembling with rage, but don't attack.",
    "street_encounter.spouse.not_over": "  \"This isn't over,\" they hiss, and walk away.",
    "street_encounter.spouse.fists_clenched": "{0} confronts you, fists clenched.",
    "street_encounter.spouse.know_doing": "\"I know what you've been doing with {0}.\"",
    "street_encounter.spouse.find_out": "\"Did you think I wouldn't find out?\"",
    "street_encounter.spouse.just_friends": "  \"We're just friends, I swear!\"",
    "street_encounter.spouse.looks_uncertain": "  {0} looks uncertain...",
    "street_encounter.spouse.liar": "  \"LIAR!\"",
    "street_encounter.spouse.attacks_rage": "  {0} attacks in a blind rage!",
    "street_encounter.spouse.admit_sorry": "  \"I'm sorry. It meant nothing.\"",
    "street_encounter.spouse.punches_you": "  {0} punches you square in the face! ({1} damage)",
    "street_encounter.spouse.stay_away": "  \"Stay away from {0}. Final warning.\"",
    "street_encounter.spouse.taunt_better": "  \"Your {0} deserves better than you!\"",
    "street_encounter.spouse.roars_fury": "  {0} roars in fury!",
    "street_encounter.spouse.settle_this": "  \"Let's settle this.\"",

    # Throne - missing keys
    "street_encounter.throne.confronts": "{0} (Level {1} {2}) confronts you!",
    "street_encounter.throne.times_up": "\"Your time on the throne is up, Your Majesty.\"",
    "street_encounter.throne.your_decree": "Your decree: ",
    "street_encounter.throne.accept_steel": "  \"Then let steel decide!\"",
    "street_encounter.throne.still_king": "  You defeated {0}! The throne is still yours!",
    "street_encounter.throne.imprisoned": "  {0} is imprisoned for {1} days!",
    "street_encounter.throne.defeated_claims": "  {0} defeats you and claims the throne!",
    "street_encounter.throne.guards_remove": "  You signal your guards to remove the upstart.",
    "street_encounter.throne.guards_drag": "  The guards drag {0} away!",
    "street_encounter.throne.guards_hesitate": "  Your guards hesitate... their loyalty is wavering!",
    "street_encounter.throne.face_yourself": "  You'll have to face {0} yourself!",
    "street_encounter.throne.no_guards": "  You have no guards! {0} laughs and attacks!",
    "street_encounter.throne.offer_role": "  You offer them a role in your court.",
    "street_encounter.throne.considers_seat": "  {0} considers... and accepts a seat on your council.",
    "street_encounter.throne.want_throne": "  \"I don't want a seat — I want the throne!\"",
    "street_encounter.throne.challenger_attacks": "  {0} attacks!",
    "street_encounter.throne.seize_treason": "  \"Seize them! This is treason!\"",
    "street_encounter.throne.dragged_away": "  {0} is dragged away to the dungeon!",
    "street_encounter.throne.no_guards_imprison": "  You have no guards to carry out the arrest!",
    "street_encounter.throne.laughs_attacks": "  {0} laughs at your empty threat and attacks!",

    # Turf - missing keys
    "street_encounter.turf.surround": "Members of '{0}' surround you!",
    "street_encounter.turf.hold_ends": "\"Your hold on this turf ends now,\" says {0}.",
    "street_encounter.turf.fight_best": "  \"Send your best!\"",
    "street_encounter.turf.backs_off": "  {0} backs off! '{1}' retreats from your turf!",
    "street_encounter.turf.cheers_lost": "  '{0}' cheers as you fall!",
    "street_encounter.turf.hand_over": "  You hand over {0} gold.",
    "street_encounter.turf.smart_move": "  \"Smart move,\" says {0}.",
    "street_encounter.turf.hard_way": "  \"Guess we're doing this the hard way,\" says {0}.",
    "street_encounter.turf.takes_control": "  '{0}' takes control of the area.",
    "street_encounter.turf.dodge_escape": "  You dodge through the crowd and escape!",
    "street_encounter.turf.cut_off": "  {0} cuts off your escape!",

    # Murder - missing keys
    "street_encounter.murder.assassin_strike": "  Your assassin's instinct guides a devastating first strike! (-{0}% enemy HP)",
    "street_encounter.murder.off_guard": "  You catch them off guard! (-{0}% enemy HP)",
    "street_encounter.murder.clean_job": "  Clean job. The Shadows are pleased.",
    "street_encounter.murder.see_face": "  You'll see their face in your nightmares.",
}

# Spanish translations
missing_es = {
    # Hostile
    "street_encounter.hostile.opt_run": "uir",
    "street_encounter.hostile.stats": "  {0} - Nivel {1} {2} (PV: {3}/{4})",

    # Pickpocket
    "street_encounter.pickpocket.grab_thief": "  Agarras al ladron — es {0}!",
    "street_encounter.pickpocket.shout_guards": "  Gritas pidiendo guardias!",
    "street_encounter.pickpocket.thief_flees": "  El ladron huye entre la multitud!",
    "street_encounter.pickpocket.msg_scared_away": "Ahuyentaste a un carterista.",
    "street_encounter.pickpocket.pretend_not_notice": "  Finges no darte cuenta y sigues adelante.",
    "street_encounter.pickpocket.msg_avoided": "Evitaste un encuentro con un carterista.",
    "street_encounter.pickpocket.bumps_into": "  Alguien te empuja entre la multitud...",
    "street_encounter.pickpocket.gold_missing": "  Notas que te faltan {0} monedas de oro!",
    "street_encounter.pickpocket.msg_stolen": "Un carterista te robo {0} oro!",
    "street_encounter.pickpocket.nothing_to_steal": "  Alguien te empuja pero no encuentra nada que robar.",
    "street_encounter.pickpocket.msg_found_nothing": "Un carterista lo intento pero no encontro nada.",

    # Brawl
    "street_encounter.brawl.squares_up": "  {0} se pone en guardia contra ti!",
    "street_encounter.brawl.duck_escape": "  Te agachas bajo una silla voladora y escapas por atras!",
    "street_encounter.brawl.msg_escaped": "Escapaste de la pelea ileso.",
    "street_encounter.brawl.hit_by_mug": "  Intentas esquivar pero una jarra te golpea en la cabeza!",
    "street_encounter.brawl.msg_hit_escaping": "Te golpeo una jarra al escapar de la pelea.",
    "street_encounter.brawl.buy_round": "  Compras una ronda para todos!",
    "street_encounter.brawl.toast_health": "  Todos brindan a tu salud! La tension se disipa.",
    "street_encounter.brawl.msg_bought_drinks": "Compraste bebidas para calmar la pelea.",
    "street_encounter.brawl.not_enough_gold": "  No tienes suficiente oro para eso!",

    # Challenge
    "street_encounter.challenge.accept_honor": "  Aceptas el desafio con honor!",
    "street_encounter.challenge.decline_reply": "  \"Hoy no,\" respondes.",
    "street_encounter.challenge.scoffs": "  {0} se burla de tu cobardia.",
    "street_encounter.challenge.msg_declined": "Rechazaste un desafio. (-5 Fama)",
    "street_encounter.challenge.opt_insult": "nsultar",
    "street_encounter.challenge.insult_honor": "  Insultas su honor y a su madre!",
    "street_encounter.challenge.pay_for_that": "  \"Pagaras por eso!\" ruge {0}!",

    # Mugging
    "street_encounter.mugging.gold_or_life": "  \"La bolsa o la vida!\"",
    "street_encounter.mugging.draw_weapon": "  Desenvaina tu arma!",
    "street_encounter.mugging.defeated_found_gold": "  Derrotaste a los asaltantes y encontraste {0} oro!",
    "street_encounter.mugging.msg_defeated": "Derrotaste a {0} asaltantes!",
    "street_encounter.mugging.msg_lost": "Perdiste contra los asaltantes...",
    "street_encounter.mugging.hand_over": "  Entregas {0} oro.",
    "street_encounter.mugging.thugs_disappear": "  Los matones desaparecen en las sombras.",
    "street_encounter.mugging.msg_surrendered": "Entregaste {0} oro a los asaltantes.",
    "street_encounter.mugging.sprint_escape": "  Corres y los pierdes en los callejones!",
    "street_encounter.mugging.msg_escaped": "Escapaste de los asaltantes!",
    "street_encounter.mugging.caught_beaten": "  Te atrapan y te golpean!",
    "street_encounter.mugging.damage_and_gold": "  Recibes {0} de dano y te roban {1} oro!",
    "street_encounter.mugging.msg_caught": "Atrapado y golpeado por asaltantes.",

    # Gang
    "street_encounter.gang.heard_team": "  \"Hemos oido hablar de tu equipo, '{0}'.\"",
    "street_encounter.gang.our_territory": "  \"Este es nuestro territorio. Retrocede.\"",
    "street_encounter.gang.opt_fight_territory": "elear por Territorio",
    "street_encounter.gang.opt_negotiate": "egociar",
    "street_encounter.gang.opt_leave": "rse en Paz",
    "street_encounter.gang.need_friends": "  \"Parece que necesitas amigos.\"",
    "street_encounter.gang.opt_join": "nirse a su Banda",
    "street_encounter.gang.opt_refuse": "echazar",
    "street_encounter.gang.wrong_answer": "  \"Respuesta equivocada.\"",
    "street_encounter.gang.victory_spreads": "  La noticia de tu victoria sobre '{0}' se extiende por las calles!",
    "street_encounter.gang.plus_fame": "  (+20 Fama)",
    "street_encounter.gang.looks_you_over": "  El lider de la banda te examina...",
    "street_encounter.gang.welcome": "  \"Bienvenido a '{0}', amigo.\"",
    "street_encounter.gang.msg_joined": "Te uniste a la banda '{0}'!",
    "street_encounter.gang.too_weak": "  \"Vuelve cuando seas mas fuerte, debil.\"",
    "street_encounter.gang.msg_too_weak": "Demasiado debil para unirse a la banda.",
    "street_encounter.gang.not_recruiting_1": "  El lider de la banda niega con la cabeza.",
    "street_encounter.gang.not_recruiting_2": "  \"No estamos reclutando ahora. Sigue tu camino.\"",
    "street_encounter.gang.msg_not_recruiting": "La banda no esta reclutando.",
    "street_encounter.gang.let_you_pass": "  A reganadientes te dejan pasar.",
    "street_encounter.gang.msg_avoided": "Evitaste la confrontacion con la banda.",
    "street_encounter.gang.nobody_refuses": "  \"Nadie nos rechaza!\"",

    # Romance
    "street_encounter.romance.buy_drink": "  \"Puedo invitarte a una bebida?\"",
    "street_encounter.romance.opt_yes": "i, Por Favor",
    "street_encounter.romance.opt_no": "o Gracias",
    "street_encounter.romance.pleasant_time": "  Pasan un rato agradable juntos...",
    "street_encounter.romance.wonderful_conversation": "  Una conversacion maravillosa! Te sientes mas encantador. (+1 Carisma)",
    "street_encounter.romance.msg_connection": "Hiciste una conexion genuina.",
    "street_encounter.romance.purse_lighter": "  ...pero tu bolsa se siente mas ligera.",
    "street_encounter.romance.stole_gold": "  Te robaron {0} oro!",
    "street_encounter.romance.msg_scam": "El encuentro romantico fue una estafa!",
    "street_encounter.romance.token_affection": "  Te dejan un pequeno recuerdo de afecto. (+5 Fama)",
    "street_encounter.romance.msg_fame": "Ganaste fama de un encuentro romantico.",
    "street_encounter.romance.another_time": "  \"Quiza en otro momento,\" dices cortesmente.",
    "street_encounter.romance.smile_walk_away": "  Sonrien y se van.",
    "street_encounter.romance.msg_declined": "Rechazaste cortesmente un encuentro romantico.",

    # Merchant
    "street_encounter.merchant.cloaked_figure": "  Una figura encapuchada te hace senas desde las sombras.",
    "street_encounter.merchant.buy_special": "  \"Psst... quieres comprar algo especial?\"",
    "street_encounter.merchant.waves_over": "  Un mercader ambulante te hace senas.",
    "street_encounter.merchant.fine_wares": "  \"Finas mercancias para el aventurero exigente!\"",
    "street_encounter.merchant.no_thanks": "No gracias",
    "street_encounter.merchant.buy_prompt": "Comprar cual articulo? ",
    "street_encounter.merchant.purchased": "  Compraste {0}!",
    "street_encounter.merchant.msg_bought": "Compraste {0} de un mercader ambulante.",
    "street_encounter.merchant.come_back": "  \"Vuelve cuando quieras!\"",
    "street_encounter.merchant.msg_declined": "Revisaste las mercancias de un mercader.",

    # Beggar
    "street_encounter.beggar.approaches": "  Un mendigo harapiento se acerca a ti.",
    "street_encounter.beggar.thanks": "  \"Que los dioses te bendigan!\" (+5 Caballeria)",
    "street_encounter.beggar.plus_chivalry": "  (+{0} Caballeria)",
    "street_encounter.beggar.msg_gave": "Diste oro a un mendigo.",
    "street_encounter.beggar.bless_you": "  \"Los dioses te bendigan, generoso!\"",
    "street_encounter.beggar.strange_amulet": "  El mendigo te pone un extrano amuleto en la mano.",
    "street_encounter.beggar.luck_amulet": "  \"Para la suerte,\" susurra.",
    "street_encounter.beggar.msg_large_donation": "Hiciste una gran donacion a un mendigo.",
    "street_encounter.beggar.opt_large": "onacion Grande (50)",
    "street_encounter.beggar.rob_possessions": "  Revisas las escasas posesiones del mendigo...",
    "street_encounter.beggar.rob_result": "  Encontraste {0} oro. (+15 Oscuridad, -10 Caballeria)",
    "street_encounter.beggar.msg_robbed": "Robaste a un mendigo.",
    "street_encounter.beggar.walk_past": "  Pasas de largo sin decir nada.",
    "street_encounter.beggar.msg_ignored": "Ignoraste a un mendigo.",

    # Rumor
    "street_encounter.rumor.dungeons_dangerous": "Las mazmorras han sido mas peligrosas ultimamente...",
    "street_encounter.rumor.king_adventurers": "El rey busca aventureros valientes.",
    "street_encounter.rumor.strange_creatures": "Se han visto criaturas extranas cerca de las afueras.",
    "street_encounter.rumor.temple_blessings": "El templo ofrece bendiciones especiales esta semana.",
    "street_encounter.rumor.fortune_hunting": "Hay una fortuna cazando en las profundidades de la mazmorra.",
    "street_encounter.rumor.guild_recruits": "El gremio busca activamente nuevos reclutas.",
    "street_encounter.rumor.watch_back": "Cuida tu espalda en los callejones oscuros de noche.",
    "street_encounter.rumor.weapon_shipment": "Llego un nuevo envio de armas a la tienda de armas.",
    "street_encounter.rumor.secret_passage": "Dicen que hay un pasaje secreto en los pisos profundos.",
    "street_encounter.rumor.exotic_goods": "Un mercader con productos exoticos fue visto cerca del mercado.",
    "street_encounter.rumor.saw_npc": "Vi a {0} dirigiendose hacia {1} antes.",
    "street_encounter.rumor.npc_team": "Escuche que {0} busca nuevos aliados.",
    "street_encounter.rumor.msg_heard": "Escuchaste un rumor interesante.",

    # Guard
    "street_encounter.guard.patrol_approaches": "  Una patrulla de guardias se acerca.",
    "street_encounter.guard.crown_insignia": "  Los guardias notan tu insignia de la Corona.",
    "street_encounter.guard.crown_business": "  \"Asunto de la Corona, entendido.\"",
    "street_encounter.guard.step_aside": "  Se hacen a un lado y te dejan pasar.",
    "street_encounter.guard.halt": "  \"Alto! Tu!\"",
    "street_encounter.guard.looking_for_you": "  \"Te hemos estado buscando. Nivel de oscuridad: {0}\"",
    "street_encounter.guard.arrested": "  Los guardias te arrestan!",
    "street_encounter.guard.confiscate": "  Confiscan {0} oro!",
    "street_encounter.guard.sentenced": "  Eres sentenciado a {0} dias de prision.",
    "street_encounter.guard.msg_arrested": "Arrestado por la guardia.",
    "street_encounter.guard.darkness_guards": "  Derrotar guardias solo aumenta tu notoriedad! (+30 Oscuridad)",
    "street_encounter.guard.overpowered": "  Los guardias te someten!",
    "street_encounter.guard.sentenced_resisting": "  Sentenciado a {0} dias por resistir el arresto con violencia!",
    "street_encounter.guard.msg_defeated_arrested": "Derrotado por guardias y arrestado.",
    "street_encounter.guard.bribed": "  El capitan de la guardia se guarda el oro discretamente. \"Circulen.\"",
    "street_encounter.guard.msg_bribed": "Sobornaste a los guardias.",
    "street_encounter.guard.escape_crowd": "  Desapareces entre la multitud!",
    "street_encounter.guard.catch_you": "  Los guardias te alcanzan!",
    "street_encounter.guard.running_extra": "  \"Huyendo de la ley, eh? Eso es un dia extra!\"",
    "street_encounter.guard.sentenced_days": "  Sentenciado a {0} dias de prision!",
    "street_encounter.guard.msg_caught": "Atrapado huyendo de los guardias.",
    "street_encounter.guard.stay_out_trouble": "  \"No te metas en problemas, ciudadano.\"",
    "street_encounter.guard.continue_patrol": "  Los guardias continuan su patrulla.",
    "street_encounter.guard.msg_questioned": "Interrogado por una patrulla de guardias.",

    # Ambush
    "street_encounter.ambush.assassins_leap": "  Asesinos saltan de las sombras!",
    "street_encounter.ambush.paid_gold": "  \"Alguien pago buen oro para que te mataran!\"",
    "street_encounter.ambush.find_note": "  Encuentras una nota en el cuerpo del asesino...",
    "street_encounter.ambush.contract": "  \"Contrato: Eliminar a {0}\"",
    "street_encounter.ambush.unreadable": "  El nombre del contratista es ilegible.",

    # Flee
    "street_encounter.flee.escape_success": "  Logras escapar!",
    "street_encounter.flee.msg_fled": "Huiste de un encuentro.",
    "street_encounter.flee.catches_you": "  {0} te alcanza!",
    "street_encounter.flee.attack_back_turned": "  Te atacan por la espalda!",
    "street_encounter.flee.take_damage": "  Recibes {0} de dano!",

    # Bribe
    "street_encounter.bribe.npc_attacks": "  {0} ataca de todas formas!",
    "street_encounter.bribe.opt_yes": "i, Pagar {0} Oro",
    "street_encounter.bribe.opt_no": "o, Pelear",
    "street_encounter.bribe.takes_gold_leaves": "  {0} toma el oro y se va.",
    "street_encounter.bribe.msg_bribed": "Sobornaste a {0} con {1} oro.",
    "street_encounter.bribe.takes_gold_attacks": "  {0} toma el oro... y ataca de todas formas!",

    # Talk
    "street_encounter.talk.reconsiders": "  {0} lo reconsidera y retrocede.",
    "street_encounter.talk.msg_talked_down": "Calmaste un encuentro hostil.",
    "street_encounter.talk.not_interested": "  {0} no esta interesado en hablar!",

    # Grudge
    "street_encounter.grudge.steps_out": "  {0} sale de las sombras frente a ti.",
    "street_encounter.grudge.hesitates": "  Duda, evaluandote...",
    "street_encounter.grudge.thinks_better": "  El Nivel {0} {1} lo piensa mejor.",
    "street_encounter.grudge.guard_rushes": "  Un guardia de la Corona corre a ayudarte!",
    "street_encounter.grudge.guard_strikes": "  El guardia golpea a {0}, causando {1} de dano!",
    "street_encounter.grudge.wounded_standing": "  {0} esta herido pero sigue en pie. (PV: {1}/{2})",
    "street_encounter.grudge.emerges_fury": "{0} emerge de la multitud, con furia en los ojos!",
    "street_encounter.grudge.murder_quote_1": "\"Me mataste una vez. Volvi de la muerte misma.\"",
    "street_encounter.grudge.murder_quote_2": "\"Ahora es TU turno de sangrar!\"",
    "street_encounter.grudge.enraged_stats": "ENFURECIDO! Nivel {0} {1} (PV: {2}/{3})",
    "street_encounter.grudge.barely_escape": "  Apenas escapas de la ira de {0}!",
    "street_encounter.grudge.cuts_off_escape": "  {0} corta tu escape!",
    "street_encounter.grudge.murder_goes_down": "  {0} cae de nuevo!",
    "street_encounter.grudge.stands_over": "  {0} se cierne sobre ti.",
    "street_encounter.grudge.now_even": "  \"Ahora estamos a mano.\"",
    "street_encounter.grudge.take_gold": "  Te quitan {0} oro.",
    "street_encounter.grudge.waiting_unhappy": "{0} te ha estado esperando, y no esta contento.",
    "street_encounter.grudge.think_again": "\"Pensaste que podias ganarme y marcharte? Piensalo de nuevo.\"",
    "street_encounter.grudge.settles_that": "  Eso lo resuelve! {0} no te molestara mas.",
    "street_encounter.grudge.takes_gold_satisfied": "  {0} toma {1} oro y parece satisfecho.",
    "street_encounter.grudge.lowers_fists": "  {0} baja los punos.",
    "street_encounter.grudge.dont_cross": "  \"No me vuelvas a provocar.\"",
    "street_encounter.grudge.sorry_not_enough": "  \"Disculpas no es suficiente!\"",
    "street_encounter.grudge.attacks_fury": "  {0} ataca con furia!",
    "street_encounter.grudge.even_for_now": "  \"Estamos a mano. Por ahora.\"",
    "street_encounter.grudge.pockets_gold": "  {0} se guarda las {1} monedas de oro.",
    "street_encounter.grudge.takes_gold_attacks": "  {0} toma el oro... y luego ataca!",
    "street_encounter.grudge.not_enough_attacks": "  No tienes suficiente oro! {0} ataca!",
    "street_encounter.grudge.slip_away": "  Logras escapar de {0}.",
    "street_encounter.grudge.catches_first_strike": "  {0} te atrapa y golpea primero!",

    # Witness
    "street_encounter.witness.title": "Confrontacion de Testigo!",
    "street_encounter.witness.steps_in_front": "{0} se pone frente a ti, bloqueando tu camino.",
    "street_encounter.witness.saw_victim": "\"Vi lo que le hiciste a {0}. Vas a pagar.\"",
    "street_encounter.witness.saw_murder": "\"Vi lo que hiciste. Asesino.\"",
    "street_encounter.witness.stats": "Nivel {0} {1} (PV: {2}/{3})",
    "street_encounter.witness.opt_bribe": "Sobornar ({0}o)",
    "street_encounter.witness.one_less": "  Un testigo menos. {0} no hablara mas.",
    "street_encounter.witness.justice_served": "  {0} obtuvo su justicia. Te quitan {1} oro.",
    "street_encounter.witness.takes_bribe": "  {0} toma {1} oro y mira para otro lado.",
    "street_encounter.witness.didnt_see": "  \"No vi nada.\"",
    "street_encounter.witness.gold_buy_silence": "  \"Tu oro no puede comprar mi silencio!\"",
    "street_encounter.witness.not_enough_attacks": "  No tienes suficiente oro! {0} ataca!",
    "street_encounter.witness.slip_away": "  Te escabulles antes de que {0} reaccione.",
    "street_encounter.witness.catches_guilty": "  {0} atrapa al culpable! No hay escape de la justicia!",

    # Spouse
    "street_encounter.spouse.storms_toward": "  {0} se lanza hacia ti con furia en los ojos.",
    "street_encounter.spouse.stops_short": "  Se detiene en seco, temblando de ira, pero no ataca.",
    "street_encounter.spouse.not_over": "  \"Esto no ha terminado,\" sisea, y se va.",
    "street_encounter.spouse.fists_clenched": "{0} te confronta, con los punos cerrados.",
    "street_encounter.spouse.know_doing": "\"Se lo que has estado haciendo con {0}.\"",
    "street_encounter.spouse.find_out": "\"Pensaste que no me enteraria?\"",
    "street_encounter.spouse.just_friends": "  \"Solo somos amigos, lo juro!\"",
    "street_encounter.spouse.looks_uncertain": "  {0} parece inseguro...",
    "street_encounter.spouse.liar": "  \"MENTIROSO!\"",
    "street_encounter.spouse.attacks_rage": "  {0} ataca cegado por la ira!",
    "street_encounter.spouse.admit_sorry": "  \"Lo siento. No significo nada.\"",
    "street_encounter.spouse.punches_you": "  {0} te da un punetazo en la cara! ({1} de dano)",
    "street_encounter.spouse.stay_away": "  \"Alejate de {0}. Ultima advertencia.\"",
    "street_encounter.spouse.taunt_better": "  \"Tu {0} merece algo mejor que tu!\"",
    "street_encounter.spouse.roars_fury": "  {0} ruge de furia!",
    "street_encounter.spouse.settle_this": "  \"Vamos a resolver esto.\"",

    # Throne
    "street_encounter.throne.confronts": "{0} (Nivel {1} {2}) te confronta!",
    "street_encounter.throne.times_up": "\"Tu tiempo en el trono se acabo, Majestad.\"",
    "street_encounter.throne.your_decree": "Tu decreto: ",
    "street_encounter.throne.accept_steel": "  \"Que el acero decida!\"",
    "street_encounter.throne.still_king": "  Derrotaste a {0}! El trono sigue siendo tuyo!",
    "street_encounter.throne.imprisoned": "  {0} es encarcelado por {1} dias!",
    "street_encounter.throne.defeated_claims": "  {0} te derrota y reclama el trono!",
    "street_encounter.throne.guards_remove": "  Senala a tus guardias para que retiren al intruso.",
    "street_encounter.throne.guards_drag": "  Los guardias arrastran a {0}!",
    "street_encounter.throne.guards_hesitate": "  Tus guardias dudan... su lealtad flaquea!",
    "street_encounter.throne.face_yourself": "  Tendras que enfrentar a {0} tu mismo!",
    "street_encounter.throne.no_guards": "  No tienes guardias! {0} se rie y ataca!",
    "street_encounter.throne.offer_role": "  Le ofreces un puesto en tu corte.",
    "street_encounter.throne.considers_seat": "  {0} lo considera... y acepta un asiento en tu consejo.",
    "street_encounter.throne.want_throne": "  \"No quiero un asiento — quiero el trono!\"",
    "street_encounter.throne.challenger_attacks": "  {0} ataca!",
    "street_encounter.throne.seize_treason": "  \"Arrestenlo! Esto es traicion!\"",
    "street_encounter.throne.dragged_away": "  {0} es arrastrado a la mazmorra!",
    "street_encounter.throne.no_guards_imprison": "  No tienes guardias para ejecutar el arresto!",
    "street_encounter.throne.laughs_attacks": "  {0} se rie de tu amenaza vacia y ataca!",

    # Turf
    "street_encounter.turf.surround": "Miembros de '{0}' te rodean!",
    "street_encounter.turf.hold_ends": "\"Tu control sobre este territorio termina ahora,\" dice {0}.",
    "street_encounter.turf.fight_best": "  \"Enviad a vuestro mejor!\"",
    "street_encounter.turf.backs_off": "  {0} retrocede! '{1}' se retira de tu territorio!",
    "street_encounter.turf.cheers_lost": "  '{0}' celebra cuando caes!",
    "street_encounter.turf.hand_over": "  Entregas {0} oro.",
    "street_encounter.turf.smart_move": "  \"Buena decision,\" dice {0}.",
    "street_encounter.turf.hard_way": "  \"Parece que lo haremos por las malas,\" dice {0}.",
    "street_encounter.turf.takes_control": "  '{0}' toma control de la zona.",
    "street_encounter.turf.dodge_escape": "  Esquivas entre la multitud y escapas!",
    "street_encounter.turf.cut_off": "  {0} corta tu escape!",

    # Murder
    "street_encounter.murder.assassin_strike": "  Tu instinto de asesino guia un devastador primer golpe! (-{0}% PV enemigo)",
    "street_encounter.murder.off_guard": "  Los pillas desprevenidos! (-{0}% PV enemigo)",
    "street_encounter.murder.clean_job": "  Trabajo limpio. Las Sombras estan complacidas.",
    "street_encounter.murder.see_face": "  Veras su rostro en tus pesadillas.",
}

for lang, missing in [('en', missing_en), ('es', missing_es)]:
    path = f'Localization/{lang}.json'
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    added = 0
    for key, value in missing.items():
        if key not in data:
            data[key] = value
            added += 1

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"{lang}.json: added {added} missing street_encounter keys")
