#!/usr/bin/env python3
"""Merge temple_keys.json into en.json and generate es.json equivalents."""
import json
import sys
import os

base = os.path.join(os.path.dirname(__file__), '..', 'Localization')

# Load files
with open(os.path.join(base, 'en.json'), 'r', encoding='utf-8') as f:
    en = json.load(f)

with open(os.path.join(base, 'es.json'), 'r', encoding='utf-8') as f:
    es = json.load(f)

with open(os.path.join(base, 'temple_keys.json'), 'r', encoding='utf-8') as f:
    new_keys = json.load(f)

# Spanish translations for the new temple keys
es_translations = {
    "temple.enter_area": "Entras al Area del Templo",
    "temple.worship_god": "Adoras a {0}.",
    "temple.follow_immortal": "Sigues al inmortal {0}.",
    "temple.not_believer": "No eres creyente.",
    "temple.description_line1": "El area del Templo esta llena de monjes, predicadores y",
    "temple.description_line2": "procesiones de sacerdotes camino a los altares.",
    "temple.description_line3": "Los profetas del fin del mundo intentan llamar tu atencion.",
    "temple.ancient_stones_hint1": "En el rincon lejano, piedras antiguas forman los cimientos del templo...",
    "temple.ancient_stones_hint2": "Parecen mas antiguas que cualquier altar aqui.",
    "temple.services": "Servicios del Templo:",
    "temple.sr_worship": "W. Adorar",
    "temple.sr_desecrate": "D. Profanar altar",
    "temple.sr_holy_news": "H. Noticias Sagradas",
    "temple.sr_altars": "A. Altares",
    "temple.sr_contribute": "C. Contribuir",
    "temple.sr_item_sacrifice": "I. Sacrificio de Objeto",
    "temple.sr_status": "S. Estado",
    "temple.sr_god_ranking": "G. Ranking de dioses",
    "temple.sr_prophecies": "P. Profecias",
    "temple.sr_pray": "Y. Rezar",
    "temple.sr_prayed_today": "(Ya rezaste hoy)",
    "temple.sr_examine_stones": "E. Examinar Piedras",
    "temple.sr_deep_temple": "T. El Templo Profundo",
    "temple.sr_meditation_chapel": "M. Capilla de Meditacion (alguien reza solo...)",
    "temple.sr_faith_seek": "F. La Fe (busca a la Alta Sacerdotisa...)",
    "temple.sr_faith_serve_another": "F. La Fe (sirves a otro...)",
    "temple.sr_faith_member": "Eres miembro de La Fe.",
    "temple.sr_inner_sanctum_meditated": "N. Santuario Interior (meditaste hoy)",
    "temple.sr_inner_sanctum_cost": "N. Santuario Interior ({0}g)",
    "temple.sr_ascended_gods": "Dioses Ascendidos:",
    "temple.sr_join_immortal_following": "J. Unirse al Rebano Inmortal (Siguiendo: {0})",
    "temple.sr_join_immortal_unaffiliated": "J. Unirse al Rebano Inmortal (sin afiliacion)",
    "temple.sr_sacrifice_gold": "$. Sacrificar Oro (a tu dios inmortal)",
    "temple.sr_leave_immortal": "L. Dejar la Fe Inmortal",
    "temple.sr_return": "R. Volver",
    "temple.menu_worship": "dorar             ",
    "temple.menu_desecrate": "rofanar altar     ",
    "temple.menu_holy_news": "oticias Sagradas",
    "temple.menu_altars": "ltares            ",
    "temple.menu_contribute": "ontribuir         ",
    "temple.menu_item_sacrifice": "acrificio Objeto",
    "temple.menu_status": "stado             ",
    "temple.menu_god_ranking": "anking de dioses  ",
    "temple.menu_prophecies": "rofecias          ",
    "temple.menu_pray": " Rezar",
    "temple.menu_prayed_today": "(Ya rezaste hoy)",
    "temple.menu_examine_stones": "xaminar Piedras    ",
    "temple.menu_deep_temple": "emplo Profundo",
    "temple.menu_meditation_chapel": "apilla Meditacion ",
    "temple.menu_meditation_hint": "(alguien reza solo...)",
    "temple.menu_the_faith": " La Fe ",
    "temple.menu_faith_seek": "(busca a la Alta Sacerdotisa...)",
    "temple.menu_faith_serve_another": "(sirves a otro...)",
    "temple.menu_faith_member": " Eres miembro de La Fe.",
    "temple.menu_inner_sanctum": " Santuario Interior",
    "temple.menu_meditated_today": "  (meditaste hoy)",
    "temple.menu_inner_sanctum_cost": "  ({0}g)",
    "temple.menu_join_flock": "nirse al Rebano Inmortal ",
    "temple.menu_following": "(Siguiendo: {0})",
    "temple.menu_unaffiliated": "(sin afiliacion)",
    "temple.menu_sacrifice_gold": "acrificar Oro       ",
    "temple.menu_sacrifice_gold_hint": "(a tu dios inmortal)",
    "temple.menu_leave_faith": "ejar Fe Inmortal",
    "temple.menu_return": "olver",
    "temple.invalid_choice": "Opcion invalida. Escribe 'look' para redibujar el menu.",
    "temple.follow_immortal_currently": "Actualmente sigues al inmortal {0}.",
    "temple.abandon_for_elder": "Abandonar a {0} por un dios anciano? (Y/N) ",
    "temple.renounce_immortal": "Renuncias a {0}. Su presencia divina se desvanece de tu mente.",
    "temple.remain_faithful": "Permaneces fiel a tu patron inmortal.",
    "temple.currently_worship": "Actualmente adoras a {0}.",
    "temple.lost_faith": "Has perdido tu fe en {0}? (Y/N) ",
    "temple.dont_believe": "Ya no crees en {0}.",
    "temple.powers_diminish": "Los poderes de {0} disminuyen...",
    "temple.send_note": "Enviar una nota a {0}? (Y/N) ",
    "temple.note_prompt": "Nota: ",
    "temple.done": "Hecho!",
    "temple.no_longer_believer": "Ya no eres creyente.",
    "temple.gods_dont_like_apostates": "Bien por ti. Los dioses no son amables con los apostatas.",
    "temple.choose_god_worship": "Elige un dios para adorar",
    "temple.raise_hands_pray": "Alzas tus manos y rezas al todopoderoso {0}",
    "temple.for_forgiveness": "por perdon",
    "temple.now_believer": "Ahora eres creyente de {0}!",
    "temple.bond_severed": "Tu vinculo con el inmortal {0} se ha roto.",
    "temple.gods_smile": "Los dioses sonrien ante tu fe!",
    "temple.desecration_limit": "Los guardias del templo te vigilan de cerca tras tu sacrilegio anterior.",
    "temple.wait_tomorrow": "Tendras que esperar hasta manana.",
    "temple.no_evil_deeds": "No te quedan actos malvados!",
    "temple.upset_gods": "Realmente quieres molestar a los dioses? (Y/N) ",
    "temple.good_for_you": "Bien por ti!",
    "temple.select_god_desecrate": "Selecciona un dios para profanar altar",
    "temple.not_allowed_abuse_own": "No puedes profanar a tu propio Dios!",
    "temple.confirm_desecrate": "SEGURO que quieres profanar el altar de {0}? (Y/N) ",
    "temple.wise_choice": "Sabia eleccion. Los dioses recuerdan a quienes muestran respeto.",
    "temple.no_good_deeds": "No te quedan buenas acciones!",
    "temple.who_receive_gift": "Quien recibira tu ofrenda?",
    "temple.not_your_god": "{0} no es tu Dios! Estas seguro?",
    "temple.mighty_not_happy": "El poderoso {0} no estara contento.",
    "temple.continue_prompt": "Continuar? (Y/N) ",
    "temple.no_gods_exist": "No existen dioses en este reino.",
    "temple.altar_of": "Altar de {0} el {1}",
    "temple.believers_count": "  Creyentes: {0}",
    "temple.power_count": "  Poder: {0}",
    "temple.god_ranking_header": "   Inmortales                Rango               Seguidores",
    "temple.gods_watch": "Los dioses vigilan el reino...",
    "temple.divine_interventions": "Las intervenciones divinas moldean el destino de los mortales...",
    "temple.prayers_reach": "Oraciones y sacrificios llegan a los cielos...",
    "temple.total_gods": "Total de Dioses Activos: {0}",
    "temple.total_believers": "Total de Creyentes: {0}",
    "temple.most_powerful": "Mas Poderoso: {0}",
    "temple.most_popular": "Mas Popular: {0}",
    "temple.no_gods_available": "No hay dioses disponibles.",
    "temple.select_prompt": "{0} (o presiona Enter para cancelar):",
    "temple.no_god_match": "No se encontro dios que coincida con '{0}'. Intenta de nuevo.",
    "temple.multiple_matches": "Multiples coincidencias encontradas:",
    "temple.be_more_specific": "Se mas especifico.",
    "temple.selected_god": "Has seleccionado: {0}, {1}",
    "temple.alignment_info": "  Alineacion: {0} | Creyentes: {1}",
    "temple.selection_cancelled": "Seleccion cancelada.",
    "temple.no_gods_accept": "Ningun dios acepta adoradores actualmente.",
    "temple.type_name_hint": "(Escribe parte del nombre de un dios, ej., 'Sol' para Solarius)",
    "temple.sacrifice_to": "Sacrificio a {0}",
    "temple.sacrifice_gold_option": "(G) Oro",
    "temple.sacrifice_status_option": "(S) Estado",
    "temple.sacrifice_return_option": "(R) Volver",
    "temple.invalid_choice_short": "Opcion invalida.",
    "temple.gold_sacrifice_prompt": "Cantidad de oro a sacrificar: ",
    "temple.invalid_amount": "Cantidad invalida.",
    "temple.not_enough_gold": "No tienes tanto oro!",
    "temple.confirm_sacrifice_gold": "Sacrificar {0} oro a {1}? (Y/N) ",
    "temple.god_power_growing": "El poder de {0} esta creciendo!",
    "temple.reward_will_come": "Puedes sentirlo...Tu recompensa llegara.",
    "temple.power_increased": "Poder aumentado en {0} puntos!",
    "temple.duration_minutes": "Duracion: {0} minutos",
    "temple.darkness_accepts": "La oscuridad acepta tu ofrenda. (+{0} reputacion Sombras)",
    "temple.devotion_noted": "Tu devocion ha sido notada. (+{0} reputacion Fe)",
    "temple.god_seethes": "*** {0} HIERVE DE IRA! ***",
    "temple.betrayal_not_forgotten": "Tu traicion no sera olvidada. Las mazmorras guardan tu destino.",
    "temple.god_furious": "{0} se enfurece por tu traicion!",
    "temple.darkness_awaits": "La oscuridad te espera en las profundidades...",
    "temple.god_displeased": "{0} esta disgustado por tu infidelidad.",
    "temple.beware_shadows": "Cuidado con las sombras en tu futuro...",
    "temple.god_no_longer_exists": "Tu dios {0} ya no existe!",
    "temple.faith_shaken": "Tu fe ha sido sacudida...",
    "temple.good_deeds": "Buenas Acciones: {0}",
    "temple.evil_deeds": "Malas Acciones: {0}",
    "temple.god_label": "Dios: {0}",
    "temple.god_none": "Dios: Ninguno (Pagano)",
    "temple.prophecy_maelketh_defeated": "La Espada Rota se ha destrozado. La guerra encuentra paz al fin.",
    "temple.prophecy_maelketh_saved": "La Espada recuerda el honor. La guerra sirve a la justicia otra vez.",
    "temple.prophecy_veloura_defeated": "El Corazon Marchito ya no late. El amor se desvanece del mundo.",
    "temple.prophecy_veloura_saved": "El amor florece de nuevo donde se planto esperanza.",
    "temple.prophecy_thorgrim_defeated": "El Juez Vacio ha sido silenciado. Los mortales deben buscar su propia justicia.",
    "temple.prophecy_noctura_allied": "El hilo de la Tejedora te guia a traves de la oscuridad.",
    "temple.prophecy_noctura_defeated": "Las sombras se dispersan. Los secretos quedan al descubierto.",
    "temple.prophecy_aurelion_defeated": "La Luz Menguante se ha extinguido. La verdad muere en la oscuridad.",
    "temple.prophecy_aurelion_saved": "La Luz arde de nuevo dentro de un recipiente mortal.",
    "temple.prophecy_terravok_defeated": "La Montana se derrumba. Los cimientos se rompen.",
    "temple.prophecy_terravok_saved": "La Montana se alza. Los cimientos permanecen eternos.",
    "temple.prophecy_manwe_resolved": "La pregunta del Creador ha sido respondida. Que viene despues?",
    "temple.prophecies_sealed": "Las profecias permanecen selladas para quienes aun no estan listos.",
    "temple.prophecies_grow_stronger": "Hazte mas fuerte, y los susurros te encontraran...",
    "temple.vision_seven_figures": "Ves siete figuras en un circulo de luz.",
    "temple.vision_faces_beautiful": "Sus rostros son hermosos, radiantes, divinos.",
    "temple.vision_darkness_creeps": "Luego la oscuridad se arrastra. Una por una, su luz se apaga.",
    "temple.vision_beauty_twists": "Su belleza se retuerce. Sus sonrisas se vuelven gruñidos.",
    "temple.vision_meant_to_guide": "\"Fuimos hechos para guiaros,\" susurra uno.",
    "temple.vision_broke_hearts": "\"Pero rompisteis nuestros corazones.\"",
    "temple.vision_endless_halls": "Te ves caminando por pasillos interminables.",
    "temple.vision_faint_light": "Adelante, una luz tenue parpadea - apenas visible.",
    "temple.vision_light_fades": "Una voz habla: \"La Luz se apaga con cada mentira.\"",
    "temple.vision_find_me": "\"Encuentrame antes de que la verdad muera para siempre.\"",
    "temple.vision_from_temple": "Sientes que la vision viene de... aqui. El Templo.",
    "temple.vision_throne_stars": "Te encuentras ante un trono de estrellas.",
    "temple.vision_figure_older": "Sobre el se sienta una figura mas antigua que el tiempo.",
    "temple.vision_come_far": "\"Has llegado lejos, hijo del polvo.\"",
    "temple.vision_final_question": "\"Pero la pregunta final permanece.\"",
    "temple.vision_worth_cost": "\"Valio la creacion el precio?\"",
    "temple.deep_temple_sealed": "El camino al Templo Profundo esta sellado.",
    "temple.deep_temple_prove": "Debes probarte contra los otros Dioses Antiguos primero.",
    "temple.deep_temple_descend": "Desciendes escalones de piedra pulidos por milenios de peregrinos.",
    "temple.deep_temple_torches": "Las antorchas aqui arden con llamas palidas y parpadeantes.",
    "temple.deep_temple_air_thick": "El aire se vuelve denso con el peso de oraciones olvidadas.",
    "temple.deep_temple_watches": "Algo te observa desde las sombras entre la luz.",
    "temple.aurelion_altar_dark": "El altar donde Aurelion habito esta oscuro y frio.",
    "temple.aurelion_ash_remains": "Solo cenizas quedan donde el dios de la verdad parpadeo.",
    "temple.aurelion_sense_loss": "Sientes una profunda sensacion de... perdida.",
    "temple.press_enter_return": "Presiona Enter para volver...",
    "temple.aurelion_warm_light": "Una calida luz llena la camara.",
    "temple.aurelion_presence": "Sientes la presencia de Aurelion dentro de ti - verdad hecha carne.",
    "temple.aurelion_thank_you": "\"Gracias,\" su voz resuena en tu mente.",
    "temple.aurelion_new_vessel": "\"Por dar a la verdad un nuevo recipiente.\"",
    "temple.aurelion_glow": "Un tenue resplandor pulsa en el corazon del Templo Profundo.",
    "temple.aurelion_weak": "Es debil... apenas visible... pero inconfundiblemente divino.",
    "temple.aurelion_see_me": "\"Tu... puedes verme?\" susurra una voz.",
    "temple.aurelion_few_can": "\"Pocos pueden ya. Las mentiras han crecido tanto...\"",
    "temple.approach_light": "Acercarte a la luz menguante? (Y/N) ",
    "temple.aurelion_flickers": "La luz parpadea pero no puede manifestarse completamente.",
    "temple.aurelion_too_weak": "\"Soy... demasiado debil. Debes enfrentar a los otros primero.\"",
    "temple.aurelion_defeat_siblings": "\"Derrota a mas de mis hermanos caidos. Solo entonces...\"",
    "temple.step_back": "Retrocedes de la luz menguante.",
    "temple.aurelion_understand": "\"Entiendo,\" susurra la voz con tristeza.",
    "temple.aurelion_not_ready": "\"No todos estan listos para la verdad.\"",
    "temple.must_worship_first": "Debes adorar a un dios antes de poder sacrificar objetos!",
    "temple.visit_worship": "Visita la opcion (W) Adorar primero.",
    "temple.kneel_before": "Te arrodillas ante el altar de {0}.",
    "temple.what_sacrifice": "Que sacrificarias?",
    "temple.sacrifice_weapon_option": "(W) Arma - Ofrece tu arma por bendicion divina",
    "temple.sacrifice_armor_option": "(A) Armadura - Ofrece tu armadura por proteccion divina",
    "temple.sacrifice_potions_option": "(H) Pociones curativas - Ofrece pociones por favor divino",
    "temple.sacrifice_return": "(R) Volver",
    "temple.sacrifice_prompt": "Sacrificio: ",
    "temple.no_weapon": "No tienes arma para sacrificar!",
    "temple.confirm_sacrifice_weapon": "Sacrificar tu arma (Poder: {0}) a {1}? (Y/N) ",
    "temple.dissolves_divine_light": "Tu arma se disuelve en luz divina!",
    "temple.god_accepts": "{0} acepta tu sacrificio!",
    "temple.divine_power_increased": "Poder divino aumentado en {0}!",
    "temple.blessing_strength": "{0} te bendice con +{1} Fuerza!",
    "temple.no_armor": "No tienes armadura para sacrificar!",
    "temple.confirm_sacrifice_armor": "Sacrificar tu armadura (Poder: {0}) a {1}? (Y/N) ",
    "temple.armor_dissolves": "Tu armadura se disuelve en luz divina!",
    "temple.blessing_defence": "{0} te bendice con +{1} Defensa!",
    "temple.no_potions": "No tienes pociones curativas para sacrificar!",
    "temple.have_potions": "Tienes {0} pociones curativas.",
    "temple.how_many_sacrifice": "Cuantas sacrificar? ",
    "temple.not_enough_potions": "No tienes tantas pociones!",
    "temple.confirm_sacrifice_potions": "Sacrificar {0} pociones curativas a {1}? (Y/N) ",
    "temple.potions_evaporate": "Tus pociones se evaporan en esencia divina!",
    "temple.god_restores_health": "{0} restaura completamente tu salud!",
    "temple.darkness_notes_devotion": "La oscuridad nota tu devocion. (+{0} reputacion Sombras)",
    "temple.light_notes_devotion": "La luz nota tu devocion. (+{0} reputacion Fe)",
    "temple.desecrated_altar": "Has profanado el altar de {0}!",
    "temple.darkness_flows": "La oscuridad fluye en tu alma! (+{0} Oscuridad)",
    "temple.xp_from_profane": "Experiencia ganada por conocimiento profano! (+{0} XP)",
    "temple.god_curses": "{0} te maldice desde el mas alla!",
    "temple.divine_fury": "La furia divina es abrumadora!",
    "temple.stat_diminish": "Sientes tu {0} disminuir mientras el poder divino la arranca! (-1 {1})",
    "temple.divine_damage": "Recibes {0} de dano divino!",
    "temple.ancient_stones_revealed": "Las piedras antiguas siguen en pie, pero su secreto fue revelado.",
    "temple.remember_truth": "Recuerdas la verdad de la creacion...",
    "temple.walk_past_altars": "Caminas mas alla de los altares concurridos, mas alla de los adoradores,",
    "temple.far_corner": "al rincon lejano del templo donde pocos transitan.",
    "temple.massive_stones": "Aqui, piedras masivas forman los cimientos del edificio.",
    "temple.older_than_temple": "Son mas antiguas que el templo mismo - mas antiguas que cualquier dios",
    "temple.whose_altar": "cuyo altar se alza arriba.",
    "temple.monks_say": "Los monjes dicen que estas piedras estaban aqui antes de construir la ciudad.",
    "temple.before_mortals": "Antes de que los mortales vinieran a esta tierra.",
    "temple.before_gods": "Antes incluso de que los dioses caminaran la tierra.",
    "temple.touch_stone": "Tocar la piedra antigua? (Y/N) ",
    "temple.step_back_stones": "Retrocedes de las piedras.",
    "temple.perhaps_another_time": "Quizas en otro momento...",
    "temple.hand_touches": "Tu mano toca la piedra fria...",
    "temple.at_first_nothing": "Al principio, nada.",
    "temple.warmth_pulse": "Luego calor. Un pulso, como un latido.",
    "temple.stone_glows": "La piedra BRILLA bajo tu palma.",
    "temple.ancient_symbols": "Simbolos antiguos cobran vida - un idioma",
    "temple.older_language": "mas antiguo que cualquiera hablado por mortal o dios.",
    "temple.voice_speaks": "Una voz habla directamente en tu mente:",
    "temple.seek_truth": "  \"Buscas la verdad. Tan pocos lo hacen ya.\"",
    "temple.first_seal": "  \"Este es el Primer Sello - la historia de la creacion.\"",
    "temple.remember_well": "  \"Recuerdalo bien, pues el entendimiento comienza aqui.\"",
    "temple.press_enter_continue": "  Presiona Enter para continuar...",
    "temple.must_worship_to_pray": "Debes adorar a un dios antes de poder rezar por bendiciones.",
    "temple.visit_worship_first": "Visita la opcion (W) Adorar para elegir una deidad.",
    "temple.already_prayed": "Ya has rezado hoy.",
    "temple.return_tomorrow": "Vuelve manana para otra bendicion.",
    "temple.kneel_altar": "Te arrodillas ante el altar de {0}...",
    "temple.prayers_rise_immortal": "Tus oraciones se elevan al reino inmortal...",
    "temple.divine_power_surges": "  El poder divino de {0} surge a traves de ti!",
    "temple.prayer_amplifies": "  La oracion amplifica las bendiciones de tu patron:",
    "temple.combat_blessing": "  Bendicion de combate: +{0}% dano/defensa por {1} combates",
    "temple.no_boons_configured": "  {0} aun no ha configurado favores divinos.",
    "temple.prayer_heard_no_boons": "  Tu oracion es escuchada, pero no fluyen bendiciones.",
    "temple.god_no_longer_exists_short": "Tu dios ya no existe...",
    "temple.prayers_rise_incense": "Tus oraciones se elevan como incienso hacia los cielos...",
    "temple.warm_light_fills": "Una calida luz llena la camara mientras tu dios te escucha.",
    "temple.shadows_coil": "Sombras se enroscan a tu alrededor mientras tu dios reconoce tu devocion.",
    "temple.balance_clarity": "Una sensacion de equilibrio y claridad te invade.",
    "temple.damage_bonus": "  Dano: +{0}%",
    "temple.defense_bonus": "  Defensa: +{0}%",
    "temple.xp_bonus": "  Bonus XP: +{0}%",
    "temple.duration_label": "  Duracion: {0} minutos",
    "temple.blessing_upon_you": "La bendicion de {0} esta sobre ti!",
    "temple.prayers_unanswered": "Tus oraciones quedan sin respuesta hoy...",
    "temple.faith_standing_gain": "(+1 reputacion Fe)",
    "temple.shadows_standing_gain": "(+1 reputacion Sombras)",
    "temple.meditation_chapel_empty": "La capilla de meditacion esta vacia.",
    "temple.only_silence": "Solo silencio y humo de velas llenan la pequeña sala.",
    "temple.step_into_chapel": "Entras en una pequeña y tranquila capilla junto al templo principal.",
    "temple.candle_illuminates": "Una sola vela ilumina a una mujer arrodillada ante un altar vacio.",
    "temple.faded_robes": "Viste las tunicas desgastadas de una sacerdotisa, aunque no llevan simbolo.",
    "temple.hands_clasped": "Sus manos estan unidas, pero sus labios no se mueven.",
    "temple.prays_to_nothing": "Reza a... nada. Un espacio vacio donde la fe una vez vivio.",
    "temple.notices_watching": "Nota que la observas.",
    "temple.turns_back": "Se vuelve hacia el altar vacio.",
    "temple.this_is_companion": "Esta es {0}, {1}.",
    "temple.role_label": "Rol: {0}",
    "temple.abilities_label": "Habilidades: {0}",
    "temple.sr_ask_join": "R. Pedirle que se una",
    "temple.sr_talk_past": "T. Hablar de su pasado",
    "temple.sr_leave_prayers": "L. Dejarla con sus oraciones",
    "temple.visual_ask_join": "[R] Pedirle que se una",
    "temple.visual_talk_past": "[T] Hablar de su pasado",
    "temple.visual_leave_prayers": "[L] Dejarla con sus oraciones",
    "temple.leave_silent_vigil": "La dejas en su vigilia silenciosa.",
    "temple.speaks_without_turning": "Al llegar a la puerta, habla sin volverse:",
    "temple.dungeons_dangerous": "\"Las mazmorras son peligrosas,\" dices. \"Una sanadora seria invaluable.\"",
    "temple.looks_long_moment": "{0} te mira por un largo momento.",
    "temple.flickers_in_eyes": "Algo parpadea en sus ojos. No esperanza - algo mas pequeño.",
    "temple.a_question": "Una pregunta, quizas.",
    "temple.want_me_to_heal": "\"Quieres que sane,\" dice.",
    "temple.always_been_able": "\"Puedo hacerlo. Siempre he podido.\"",
    "temple.will_it_matter": "\"Pero importara? Importara algo de esto?\"",
    "temple.doesnt_wait": "No espera una respuesta.",
    "temple.perhaps_help": "\"Quizas si te ayudo lo suficiente, lo descubrire.\"",
    "temple.rises_from_altar": "{0} se levanta del altar vacio.",
    "temple.candle_flickers": "La vela detras de ella parpadea - pero no se apaga.",
    "temple.companion_death_warning": "ADVERTENCIA: Los companeros pueden morir permanentemente. Ella puede encontrar su respuesta en el sacrificio.",
    "temple.sit_beside": "Te sientas a su lado. El silencio se extiende entre ustedes.",
    "temple.was_healer_veloura": "\"Era sanadora en el templo de Veloura,\" dice finalmente.",
    "temple.corruption_came": "\"Cuando llego la corrupcion... los sanadores se convirtieron en otra cosa.\"",
    "temple.escaped_left_faith": "\"Escape. Pero deje mi fe atras.\"",
    "temple.personal_quest_label": "Mision Personal: {0}",
    "temple.keep_praying": "\"Sigo rezando,\" susurra.",
    "temple.to_empty_altar": "\"A un altar vacio. A nada.\"",
    "temple.if_i_stop": "\"Porque si me detengo... no se que soy.\"",
    "temple.ask_join_prompt": "Pedirle que se una? (Y/N): ",
    "temple.squeeze_shoulder": "Le aprietas el hombro suavemente y te vas.",
    "temple.faith_approach": "Te acercas al santuario interior del Templo, donde solo los mas",
    "temple.faith_devoted": "devotos tienen permitido. Una anciana sacerdotisa de tunicas blancas te saluda.",
    "temple.mirael_intro": "\"Soy la Alta Sacerdotisa Mirael,\" dice, su voz gentil pero firme.",
    "temple.mirael_watched": "\"He observado tu viaje con interes, viajero.\"",
    "temple.mirael_studies": "Te estudia con ojos conocedores.",
    "temple.already_serve": "\"Ya sirves a {0}.\"",
    "temple.no_divided_loyalties": "\"La Fe no acepta lealtades divididas.\"",
    "temple.renounce_seek_again": "\"Si alguna vez renuncias a tu lealtad actual, buscame de nuevo.\"",
    "temple.sacred_flames": "Señala las llamas sagradas que arden eternamente en el altar.",
    "temple.faith_old_gods_pure": "\"La Fe cree que los Dioses Antiguos fueron una vez puros y buenos.\"",
    "temple.faith_guided": "\"Guiaron a la humanidad con amor, sabiduria y verdad.\"",
    "temple.faith_corrupted": "\"Pero la adoracion mortal los corrompio - nuestros miedos, nuestros odios,\"",
    "temple.faith_absorbed": "\"nuestras mentiras... lo absorbieron todo hasta que se rompieron.\"",
    "temple.faith_healed": "\"Creemos que los dioses pueden ser SANADOS, no destruidos.\"",
    "temple.faith_devotion": "\"A traves de devocion, sacrificio y fe inquebrantable,\"",
    "temple.faith_restore": "\"los restauraremos a su antigua gloria.\"",
    "temple.benefit_healing": "\u2022 25% descuento en servicios de curacion",
    "temple.benefit_prayers": "\u2022 Acceso a oraciones y bendiciones especiales",
    "temple.benefit_npcs": "\u2022 Trato amigable de clerigos y NPCs del templo",
    "temple.benefit_standing": "\u2022 La reputacion con La Fe crece mediante devocion",
    "temple.faith_requires": "La Fe requiere:",
    "temple.faith_req_level": "\u2022 Nivel 10 o superior",
    "temple.faith_req_standing": "\u2022 Reputacion Fe 100+ (haz ofrendas de oro, reza diariamente)",
    "temple.faith_your_standing": "  Tu Reputacion Fe: {0}",
    "temple.mirael_return": "\"Vuelve cuando tu fe arda mas brillante,\" dice Mirael amablemente.",
    "temple.mirael_offerings": "\"Haz ofrendas en nuestros altares. Reza diariamente. Muestra tu devocion.\"",
    "temple.mirael_extends": "La Alta Sacerdotisa Mirael extiende su mano hacia ti.",
    "temple.mirael_noted": "\"Tu devocion ha sido notada. Tus ofrendas aceptadas.\"",
    "temple.mirael_oath": "\"Tomaras el juramento sagrado y te uniras a La Fe?\"",
    "temple.join_warning": "ADVERTENCIA: Unirse a La Fe:",
    "temple.join_lock_out": "\u2022 Te bloqueara de La Corona y Las Sombras",
    "temple.join_decrease": "\u2022 Reducira reputacion con facciones rivales en 100",
    "temple.join_prompt": "Unirse a La Fe? (Y/N) ",
    "temple.mirael_understanding": "Mirael asiente con comprension.",
    "temple.mirael_not_for_everyone": "\"El camino de la fe no es para todos. Pero sabe esto:\"",
    "temple.mirael_doors_open": "\"Nuestras puertas permanecen abiertas, si alguna vez buscas la luz.\"",
    "temple.kneel_sacred_flames": "Te arrodillas ante las llamas sagradas.",
    "temple.mirael_stands": "La Alta Sacerdotisa Mirael esta de pie ante ti, con las manos alzadas.",
    "temple.repeat_after_me": "\"Repite conmigo:\"",
    "temple.oath_line1": "\"Prometo mi alma a la restauracion de los dioses.\"",
    "temple.oath_line2": "\"Sanare lo que esta roto, remendare lo que esta desgarrado.\"",
    "temple.oath_line3": "\"A traves de la fe, sere la luz en la oscuridad.\"",
    "temple.oath_line4": "\"Hasta que los dioses sean puros, no descansare.\"",
    "temple.flames_flare": "Las llamas sagradas brillan intensamente, banandote en calida luz.",
    "temple.profound_peace": "Sientes una profunda sensacion de paz invadiendote.",
    "temple.mirael_welcome": "\"Bienvenido, hijo de la luz,\" dice Mirael calidamente.",
    "temple.mirael_never_waver": "\"Ahora eres uno de nosotros. Que tu fe nunca flaquee.\"",
    "temple.as_member_receive": "Como miembro de La Fe, recibiras:",
    "temple.receive_discount": "\u2022 25% descuento en todos los servicios de curacion",
    "temple.receive_recognition": "\u2022 Reconocimiento de NPCs del Templo",
    "temple.receive_blessings": "\u2022 Acceso a bendiciones y oraciones exclusivas de La Fe",
    "temple.sanctum_sealed": "  El Santuario Interior esta sellado para forasteros.",
    "temple.sanctum_faith_only": "  Solo miembros de La Fe pueden entrar.",
    "temple.sanctum_already_meditated": "  Ya has meditado hoy.",
    "temple.sanctum_ready_tomorrow": "  El santuario estara listo de nuevo manana.",
    "temple.sanctum_stillness": "  Una camara de perfecta quietud. El incienso flota en el aire.",
    "temple.sanctum_runes": "  Runas antiguas pulsan tenuemente en las paredes.",
    "temple.sanctum_cost": "  La meditacion profunda cuesta {0} oro.",
    "temple.sanctum_grant": "  El santuario otorga +1 permanente a un atributo aleatorio.",
    "temple.sanctum_gold_label": "  Oro: {0}",
    "temple.sanctum_enter_prompt": "  Entrar al santuario? (Y/N): ",
    "temple.sanctum_cant_afford": "  No puedes pagar la ofrenda.",
    "temple.sanctum_kneel": "  Te arrodillas en la piedra fria y cierras los ojos...",
    "temple.sanctum_warmth": "  El calor te inunda. Algo cambia dentro de ti.",
    "temple.sanctum_stat_gain": "  +1 {0}!",
    "temple.sanctum_power_mark": "  El poder del santuario ha dejado su marca en ti.",
    "temple.no_ascended_gods": "  No hay dioses ascendidos para adorar.",
    "temple.worship_which": "  A que dios adorar? (0 para cancelar): ",
    "temple.already_follow": "  Ya sigues a {0}.",
    "temple.currently_follow": "  Actualmente sigues a {0}.",
    "temple.abandon_prompt": "  Abandonarlos? (Y/N): ",
    "temple.currently_worship_elder": "  Actualmente adoras al dios anciano {0}.",
    "temple.abandon_elder_prompt": "  Abandonar a {0} por un dios nacido mortal? (Y/N): ",
    "temple.renounce_elder": "  Renuncias a {0}!",
    "temple.elder_strikes": "  {0} te derriba por tu traicion!",
    "temple.elder_damage": "  Recibes {0} de dano! (HP: {1}/{2})",
    "temple.elder_watches": "  {0} observa en silencio mientras te alejas...",
    "temple.kneel_immortal": "  Te arrodillas ante el altar de {0}.",
    "temple.divine_presence": "  Sientes una presencia divina reconocerte.",
    "temple.divine_favors_flow": "  Sientes sus favores divinos fluir hacia ti:",
    "temple.must_worship_immortal_sr": "  Debes adorar a un dios inmortal primero. Usa J para unirte a un rebano.",
    "temple.must_worship_immortal": "  Debes adorar a un dios inmortal primero. Usa [J] para unirte a un rebano.",
    "temple.sacrifice_gold_to": "  Sacrificar oro a {0}",
    "temple.gold_on_hand": "  Oro disponible: {0}",
    "temple.amount_to_sacrifice": "  Cantidad a sacrificar (0 para cancelar): ",
    "temple.not_enough_gold_sacrifice": "  No tienes tanto oro.",
    "temple.gold_upon_altar": "  Colocas {0} oro sobre el altar de {1}.",
    "temple.offering_burns": "  La ofrenda arde con fuego divino! (Poder: {0})",
    "temple.warm_glow": "  Sientes un calido resplandor de favor divino.",
    "temple.no_immortal_god": "  No sigues a ningun dios inmortal.",
    "temple.abandon_faith_prompt": "  Abandonar tu fe en {0}? (Y/N): ",
    "temple.turn_away": "  Te alejas del altar de {0}.",
    "temple.without_patronage": "  Estas una vez mas sin patrocinio divino."
}

# Add new keys to en.json
added = 0
for key, value in new_keys.items():
    if key not in en:
        en[key] = value
        added += 1

# Add Spanish translations to es.json
added_es = 0
for key, value in es_translations.items():
    if key not in es:
        es[key] = value
        added_es += 1

# Write back
with open(os.path.join(base, 'en.json'), 'w', encoding='utf-8') as f:
    json.dump(en, f, indent=2, ensure_ascii=False)
    f.write('\n')

with open(os.path.join(base, 'es.json'), 'w', encoding='utf-8') as f:
    json.dump(es, f, indent=2, ensure_ascii=False)
    f.write('\n')

print(f"Added {added} keys to en.json")
print(f"Added {added_es} keys to es.json")
