import json

en = json.load(open('Localization/en.json', 'r', encoding='utf-8'))
es = json.load(open('Localization/es.json', 'r', encoding='utf-8'))

missing = {k: en[k] for k in en if k not in es}

translations = {
    "team.desc_line1": "Una habitaci\u00f3n trasera llena de humo con mesas toscas. Estandartes de equipos cuelgan de las",
    "team.desc_line2": "vigas, y las paredes est\u00e1n cubiertas de recompensas, desaf\u00edos y registros de equipos.",
    "team.your_team": "Tu Equipo: {0}",
    "team.turf_control_yes": "Control del Territorio: S\u00cd - \u00a1Dominas esta ciudad!",
    "team.turf_control_no": "Control del Territorio: No",
    "team.no_team_hint": "\u00a1No eres miembro de ning\u00fan equipo. Crea o \u00fanete a uno para ganar poder!",
    "team.sr_title": "Rinc\u00f3n de Equipos de Aventureros",
    "team.sr_turf_yes": "Control del Territorio: S\u00ed",
    "team.sr_turf_no": "Control del Territorio: No",
    "team.sr_no_team": "No est\u00e1s en un equipo.",
    "team.sr_info_section": "Informaci\u00f3n del Equipo:",
    "team.sr_actions_section": "Acciones del Equipo:",
    "team.sr_comm_section": "Comunicaci\u00f3n:",
    "team.sr_online_section": "Funciones en L\u00ednea:",
    "team.bbs_team_label": " Equipo: {0}",
    "team.bbs_controls_town": " *CONTROLA LA CIUDAD*",
    "team.bbs_no_team": " \u00a1No est\u00e1s en un equipo. Crea o \u00fanete a uno!",
    "team.bbs_info": " Info:",
    "team.bbs_actions": " Acciones:",
    "team.invalid_choice": "\u00a1Opci\u00f3n inv\u00e1lida! El l\u00edder de la banda niega con la cabeza.",
    "team.no_teams_yet": "A\u00fan no se han formado equipos.",
    "team.be_first": "\u00a1S\u00e9 el primero en crear un equipo!",
    "team.turf_legend": "* = Controla el territorio de la ciudad",
    "team.which_team_info": "\u00bfDe qu\u00e9 equipo quieres informaci\u00f3n? ",
    "team.info_header": "Informaci\u00f3n del Equipo: {0}",
    "team.not_in_team": "No perteneces a un equipo.",
    "team.status_header": "Estado del Equipo: {0}",
    "team.team_name_label": "Nombre del Equipo: {0}",
    "team.town_control_yes": "\u00a1Control de la Ciudad: S\u00cd - Tu equipo domina esta ciudad!",
    "team.town_control_no": "Control de la Ciudad: NO",
    "team.status_online": "En L\u00ednea",
    "team.status_offline": "Desconectado",
    "team.status_alive": "Vivo",
    "team.status_gone": "Ausente",
    "team.status_dead_label": "Muerto",
    "team.total_members": "Total: {0} miembros ({1} jugadores, {2} NPCs)",
    "team.online_tag": " [EN L\u00cdNEA]",
    "team.member_dead_tag": " (Muerto)",
    "team.already_in_team": "\u00a1Ya eres miembro de {0}!",
    "team.quit_current_first": "Primero debes abandonar tu equipo actual.",
    "team.creation_cost": "\u00a1Crear una banda cuesta {0} oro!",
    "team.you_only_have": "Solo tienes {0} oro.",
    "team.creating_gang": "Creando una nueva banda...",
    "team.registration_fee": "Cuota de registro: {0} oro",
    "team.enter_gang_name": "Nombre de la banda (m\u00e1x. 40 caracteres): ",
    "team.invalid_team_name": "\u00a1Nombre de equipo inv\u00e1lido!",
    "team.team_name_exists": "\u00a1Ya existe un equipo con ese nombre!",
    "team.player_team_exists": "\u00a1Ya existe un equipo de jugador con ese nombre!",
    "team.enter_gang_password": "Contrase\u00f1a de la banda (m\u00e1x. 20 caracteres): ",
    "team.invalid_password": "\u00a1Contrase\u00f1a inv\u00e1lida!",
    "team.gang_created": "\u00a1Banda '{0}' creada exitosamente!",
    "team.now_leader": "\u00a1Ahora eres el l\u00edder de {0}!",
    "team.paid_registration": "Pagaste {0} oro en cuotas de registro.",
    "team.which_gang_join": "\u00bfA qu\u00e9 banda te gustar\u00eda unirte? ",
    "team.enter_password": "Ingresa la contrase\u00f1a: ",
    "team.joined_team": "\u00a1Correcto! Ahora eres miembro de {0}!",
    "team.wrong_password": "\u00a1Contrase\u00f1a incorrecta! Acceso denegado.",
    "team.no_active_team": "\u00a1No se encontr\u00f3 un equipo activo con ese nombre!",
    "team.not_in_team_excl": "\u00a1No perteneces a un equipo!",
    "team.confirm_quit": "\u00bfRealmente abandonar {0}? (S/N): ",
    "team.left_team": "\u00a1Has abandonado el equipo!",
    "team.must_be_in_team_recruit": "\u00a1Debes estar en un equipo para reclutar miembros!",
    "team.create_first_hint": "Crea un equipo primero con la opci\u00f3n (C)rear equipo.",
    "team.team_full": "\u00a1Tu equipo est\u00e1 lleno! (M\u00e1x. {0} miembros)",
    "team.team_label": "Equipo: {0}",
    "team.current_size": "Tama\u00f1o Actual: {0}/{1}",
    "team.no_npcs_available": "No hay NPCs disponibles para reclutar ahora mismo.",
    "team.try_again_later": "\u00a1Int\u00e9ntalo m\u00e1s tarde - los NPCs se mueven por el mundo!",
    "team.available_recruits": "Reclutas Disponibles:",
    "team.your_gold": "Tu Oro: {0}",
    "team.enter_number_recruit": "Ingresa n\u00famero para reclutar (0 para cancelar): ",
    "team.need_gold_recruit": "Necesitas {0} oro, pero solo tienes {1}.",
    "team.npc_joined": "\u00a1{0} se ha unido a tu equipo!",
    "team.paid_recruitment": "Pagaste {0} oro por el reclutamiento.",
    "team.daily_wage": "Salario diario: {0} oro/d\u00eda (deducido autom\u00e1ticamente)",
    "team.recruit_quote": "\"{0} dice: '\u00a1Luchar\u00e9 a tu lado, jefe!'\"",
    "team.invalid_choice_generic": "Opci\u00f3n inv\u00e1lida.",
    "team.examine_prompt": "\u00bfExaminar qu\u00e9 miembro del equipo? (ingresa ? para ver tu equipo)",
    "team.member_not_found": "No se encontr\u00f3 miembro del equipo llamado '{0}'.",
    "team.status_label_alive": "Estado: Vivo",
    "team.status_label_dead": "Estado: Muerto",
    "team.enter_current_password": "Ingresa la contrase\u00f1a actual: ",
    "team.wrong_password_short": "\u00a1Contrase\u00f1a incorrecta!",
    "team.enter_new_password": "Ingresa la nueva contrase\u00f1a: ",
    "team.password_changed": "\u00a1Contrase\u00f1a cambiada exitosamente!",
    "team.message_prompt": "Mensaje para los miembros del equipo:",
    "team.message_sent": "\u00a1Mensaje enviado al equipo!",
    "team.your_message": "Tu mensaje: \"{0}\"",
    "team.sack_prompt": "\u00bfA qui\u00e9n DESPEDIR? (ingresa ? para ver tu equipo)",
    "team.confirm_sack": "\u00bfRealmente despedir a {0}? (S/N): ",
    "team.member_sacked": "\u00a1{0} ha sido despedido del equipo!",
    "team.no_resurrectables": "No hay miembros del equipo que puedan ser resucitados.",
    "team.permadead_reason_age": "muri\u00f3 de vejez",
    "team.permadead_reason_slain": "asesinado permanentemente",
    "team.all_alive": "\u00a1Todos los miembros de tu equipo est\u00e1n vivos!",
    "team.dead_members_header": "Miembros Muertos del Equipo:",
    "team.enter_number_resurrect": "Ingresa n\u00famero para resucitar (0 para cancelar): ",
    "team.need_gold_resurrect": "\u00a1Necesitas {0} oro para resucitar a {1}!",
    "team.member_resurrected": "\u00a1{0} ha sido resucitado!",
    "team.resurrect_cost": "Costo: {0} oro",
    "team.must_be_in_team_allies": "\u00a1Debes estar en un equipo para reclutar aliados jugadores!",
    "team.create_join_first": "Crea o \u00fanete a un equipo primero.",
    "team.no_other_players": "No se encontraron otros jugadores en tu equipo.",
    "team.recruit_players_first": "\u00a1Recluta otros jugadores para unirse a tu equipo primero!",
    "team.available_player_allies": "Aliados Jugadores Disponibles:",
    "team.echo_description": "Su eco lucha a tu lado en la mazmorra.",
    "team.select_ally": "Seleccionar aliado (0 para cancelar): ",
    "team.echo_already_in_party": "\u00a1El eco de {0} ya est\u00e1 en tu grupo!",
    "team.echo_will_join": "\u00a1El eco de {0} se unir\u00e1 a tu pr\u00f3xima incursi\u00f3n a la mazmorra!",
    "team.echo_ai_note": "Luchar\u00e1n como aliados controlados por IA con sus estad\u00edsticas reales.",
    "team.no_living_members": "Tu equipo no tiene miembros NPC vivos para equipar.",
    "team.team_members_label": "Miembros del Equipo:",
    "team.select_member_equip": "Seleccionar miembro para equipar (0 para cancelar): ",
    "team.equip_header_label": "EQUIPAMIENTO: {0}",
    "team.current_equipment": "Equipamiento Actual:",
    "team.options_label": "Opciones:",
    "team.offhand_2h": "(usando arma a 2 manos)",
    "team.offhand_empty": "(vac\u00edo)",
    "team.equip_to_header": "EQUIPAR OBJETO A {0}",
    "team.available_equipment": "Equipamiento disponible:",
    "team.select_item": "Seleccionar objeto (0 para cancelar): ",
    "team.cannot_use_item": "{0} no puede usar este objeto: {1}",
    "team.which_hand_sr": "\u00bfQu\u00e9 mano? M para mano Principal, O para mano Secundaria.",
    "team.equipped_success": "\u00a1{0} equip\u00f3 {1}!",
    "team.equip_failed": "Error al equipar: {0}",
    "team.unequip_header": "DESEQUIPAR DE {0}",
    "team.no_equipment_unequip": "{0} no tiene equipamiento para desequipar.",
    "team.equipped_items": "Objetos equipados:",
    "team.select_slot_unequip": "Seleccionar ranura para desequipar (0 para cancelar): ",
    "team.cursed_cannot_remove": "\u00a1El {0} est\u00e1 maldito y no puede ser removido!",
    "team.took_item": "Tomaste {0} de {1}.",
    "team.item_added_inventory": "Objeto a\u00f1adido a tu inventario.",
    "team.unequip_failed": "Error al desequipar objeto.",
    "team.take_all_confirm": "\u00bfTomar TODO el equipamiento de {0}?",
    "team.take_all_warning": "Esto los dejar\u00e1 sin nada. \u00bfConfirmar (S/N)?",
    "team.took_items_count": "Tomaste {0} objeto(s) de {1}.",
    "team.no_equipment_take": "{0} no ten\u00eda equipamiento para tomar.",
    "team.cursed_not_removed": "No se pudieron remover objetos malditos: {0}",
    "team.war_must_be_in_team": "\u00a1Debes estar en un equipo para hacer la guerra!",
    "team.your_team_war_label": "  Tu Equipo: {0}",
    "team.active_war_exists": "\u00a1Tu equipo ya tiene una guerra activa!",
    "team.no_other_teams": "No hay otros equipos para desafiar.",
    "team.challenge_team_num": "  Desafiar equipo #: ",
    "team.war_wager": "  Apuesta de guerra: {0} oro (el ganador se lleva todo)",
    "team.confirm_war": "  \u00bfConfirmar guerra contra {0}? (S/N): ",
    "team.not_enough_gold_wager": "  \u00a1No hay suficiente oro para la apuesta de guerra!",
    "team.no_members_war": "  \u00a1Uno de los equipos no tiene miembros!",
    "team.war_title": "GUERRA DE EQUIPOS: {0} vs {1}",
    "team.round_label": "  Ronda {0}: ",
    "team.fighter_wins": "- \u00a1{0} GANA!",
    "team.war_score": "  Puntuaci\u00f3n: {0} - {1}",
    "team.war_spoils": "  \u00a1Bot\u00edn de guerra: {0} oro!",
    "team.war_lost_gold": "  Perdiste {0} oro en la apuesta de guerra.",
    "team.no_wars_yet": "  A\u00fan no se han librado guerras.",
    "team.hq_must_be_in_team": "\u00a1Debes estar en un equipo para acceder al cuartel general!",
    "team.hq_title": "CUARTEL GENERAL - {0}",
    "team.vault_display": "  B\u00f3veda del Equipo: {0} / {1} oro",
    "team.choice_label": "\n  Opci\u00f3n: ",
    "team.upgrade_num_prompt": "\n  Mejora # (1-5): ",
    "team.max_level_reached": "  \u00a1Nivel m\u00e1ximo alcanzado!",
    "team.upgrade_cost_info": "  Mejorar {0} a Nv {1} cuesta {2} oro.",
    "team.vault_and_gold": "  La b\u00f3veda tiene {0}o, t\u00fa tienes {1}o.",
    "team.vault_not_enough": "  \u00a1No hay suficiente oro en la b\u00f3veda!",
    "team.personal_not_enough": "  \u00a1No hay suficiente oro personal!",
    "team.facility_upgraded": "\n  \u00a1{0} mejorado a Nivel {1}!",
    "team.vault_full": "\n  \u00a1B\u00f3veda llena! Mej\u00f3rala para m\u00e1s capacidad.",
    "team.deposit_prompt": "\n  \u00bfCu\u00e1nto depositar? (m\u00e1x. {0}): ",
    "team.deposited": "  \u00a1Depositaste {0} oro en la b\u00f3veda del equipo!",
    "team.vault_empty": "\n  La b\u00f3veda est\u00e1 vac\u00eda.",
    "team.withdraw_prompt": "\n  \u00bfCu\u00e1nto retirar? (la b\u00f3veda tiene {0}): ",
    "team.withdrew": "  \u00a1Retiraste {0} oro de la b\u00f3veda del equipo!",
    "team.withdrawal_failed": "  Error al retirar.",
    "team.failed_generic": "  \u00a1Fall\u00f3!",
}

count = 0
for k in missing:
    if k in translations:
        es[k] = translations[k]
        count += 1
    else:
        print(f"MISSING TRANSLATION: {k}")

with open('Localization/es.json', 'w', encoding='utf-8') as f:
    json.dump(es, f, ensure_ascii=False, indent=2)

print(f"Added {count} Spanish translations. es.json now has {len(es)} keys.")

# Verify sync
en2 = json.load(open('Localization/en.json', 'r', encoding='utf-8'))
es2 = json.load(open('Localization/es.json', 'r', encoding='utf-8'))
still_missing = [k for k in en2 if k not in es2]
print(f"Still missing: {len(still_missing)}")
